### PR TITLE
fix buggy runtime events test_caml_parallel test

### PR DESCRIPTION
**Pull request by sadiqj**
This fixes the test failure seen on #11750

### CODE REVIEW

**Comment by gasche** [comment]
The code is still very odd. The record stored for each domain is mutable, so why replace it with itself instead of just mutating the field? We should only need to add the record on the first time we encounter its domain.

**Comment by sadiqj** [comment]
> The code is still very odd. The record stored for each domain is mutable, so why replace it with itself instead of just mutating the field? We should only need to add the record on the first time we encounter its domain.

Yes, it was odd. Have rewritten it.

**Review by gasche — APPROVED** [review]
This looks fine, thanks!

Note: there is a comment at the end of the file that seems to refer to an assertion that has been removed since.

```
    (* this is num_full_majors rather than num_full_majors*num_domains
        because in the worst case it can be that low. *)
```

**Comment by sadiqj** [comment]
Thanks @gasche . Have nipped that old assert comment. Will merge when CI is good.

**Pull request merged**
