### PR TITLE
Inria Jenkins CI fix - isatty test

### PR DESCRIPTION
**Pull request by dra27**
@shindere - please could you schedule a build of this branch, and we'll see if it correctly skips the /dev/tty test?

/cc @mshinwell

### CODE REVIEW

**Comment by shindere** [comment]
David Allsopp (2017/09/15 14:41 +0000):
> @shindere - please could you schedule a build of this branch, and
> we'll see if it correctly skips the /dev/tty test?

Sure, but just a quick question please.

Am I correct that the problem is cygwin-related rather than
Jenkins-related?

To me, it seems that Jenkins has nothing to do here because it just
executes tests on clients and the tests see that files / devices that
are available on the client / slave. Or am I missing something, here?

**Comment by dra27** [comment]
@shindere - sorry the branch was faulty before, it will want restarting if you'd done it straightaway (I misnamed some files).

This definitely isn't a Cygwin problem - the four Windows ports are fine! I have seen a report that Jenkins does not expose /dev/tty (see here: https://github.com/zerovm/zerovm/issues/246). I am slightly puzzled as to why the Cygwin ports themselves aren't working, though.

**Comment by dra27** [comment]
Ugh - something still isn't working on Travis <sigh>

**Comment by dra27** [comment]
Hopefully third time lucky...

**Comment by shindere** [comment]
David Allsopp (2017/09/15 08:15 -0700):
> Hopefully third time lucky...

Waiting till done with ocamltest and then testing your branch.

**Comment by shindere** [comment]
David Allsopp (2017/09/15 14:41 +0000):
> @shindere - please could you schedule a build of this branch, and
> we'll see if it correctly skips the /dev/tty test?

Done. This test was causing the ocamltest PR to fail, at least on some
slaves, so I started with this PR. I was tempted to test both at the
same time but it's perhaps better not to. It's build #6 of job
shindere-ocamltest.

**Comment by shindere** [comment]
So at least on linux-32 tests/lib-unix/isatty/isatty_tty.ml failed.

**Comment by dra27** [comment]
Hmm - I think it will be necessary to poke around on the build slave directly at some point - in the meantime, the commit I've just pushed should disable the test for the non-Windows slaves.

**Comment by xavierleroy** [comment]
I would propose a different fix within the .ml file: report the tty test as a success if neither `/dev/tty` nor `CONIN$` can be opened.  Something like:
```
  match Unix.(openfile "/dev/tty" [O_RDWR] 0) with
  | fd -> Unix.isatty fd
  | exception Unix.Unix_error _ ->
  match Unix.(openfile "CONIN$" [O_RDWR] 0) with
  | fd -> Unix.isatty fd
  | exception Unix.Unix_error _ -> true
```
Under Unix it is quite possible for a process to have no controlling TTY, e.g. because it is [launched from] a daemon, in which case `/dev/tty` cannot be opened.

**Comment by shindere** [comment]
David Allsopp (2017/09/15 15:56 +0000):
> Hmm - I think it will be necessary to poke around on the build slave
> directly at some point

Can do that, e.g. later next week.

Shall I run the build again?

**Comment by dra27** [comment]
@shindere - what's here should now unblock you, yes (even if with a sledgehammer)

@xavierleroy - I'm somewhat loathe to have a test which returns success when it didn't actually run! I'd assumed in that first attempt that if I could stat /dev/tty then it might work, but that obviously isn't enough... I'll have a poke about for a better solution when I get back from vacation (but as I say, I think what's here should unblock the problem in the meantime)

**Review by damiendoligez — APPROVED** [review]
Reviewed, tested locally, fixed a bug in `testsuite/makefiles/Makefile.several`. Let's see how it fares on the Inria CI. Merging now.

**Comment by dra27** [comment]
Thanks for the Makefile fix - I'd mistakenly thought the incorrect result on my machine was because I was using a slightly older compiler!

**Pull request merged**
