### PR TITLE
Make asmgen tests run v2

### PR DESCRIPTION
**Pull request by Gbury**
Successor of #9152 

cc @shindere

### CODE REVIEW

**Comment by shindere** [comment]
Thanks. This is currently going through precheck as build 339,
will approve and merge if all the CI are happy.

**Comment by Gbury** [comment]
So, it happened that the harness code for running the asmgen tests didn't take care to properly align the stack frames before calling the code generated from cmm, and some systems/OS/libc implementations seem to be more strict with regards to that. The last commit should fix that for amd64, but other archs might have similar problems.

**Comment by shindere** [comment]
Many thanks for the fix @Gbury.

Let's see what [precheck](https://ci.inria.fr/ocaml/job/precheck/341/)
says, now.

**Comment by Gbury** [comment]
So I pushed a fix for mingw64, which uses a different calling convention that wasn't reflected in the `testsuite/tools/asmgen_amd64.S`. Let's hope precheck is happy with that.

**Comment by shindere** [comment]
Thanks. New [precheck round](https://ci.inria.fr/ocaml/job/precheck/342/)

**Comment by Gbury** [comment]
I don't have much time to work on this anymore, and there are other more important work going on in the backend right now, so I'm going to close this one.

**Pull request closed without merging**
