### PR TITLE
Use <> instead of != for ints inside the stdlib

### PR DESCRIPTION
**Pull request by hhugo**
I did not look at the rest of the codebase.

### CODE REVIEW

**Review by MisterDA — APPROVED** [review]

**Review by OlivierNicole — APPROVED** [review]
Clearly correct, thanks.

**Comment by gasche** [comment]
I am slightly worried that we might be going back and forth between the preferences of two different groups, "avoid physical equality when it's not needed" (sounds reasonable) and "avoid polymorphic comparison" (also somewhat reasonable). No strong opinion on the change, it looks fine, but maybe it would be helpful to have some clearer guidelines on what people want.

**Comment by OlivierNicole** [comment]
For context, I think (?) this is to improve JSOO: https://github.com/ocaml/ocaml/pull/13438#issuecomment-2440028890

**Comment by gasche** [comment]
This is fine, but yes having more pointers to justification is helpful. If later people tell us that they want to remove `<>` again, we can please everyone by moving to the elegant `not (Int.equal foo bar)`.

**Comment by hhugo** [comment]
> This is fine, but yes having more pointers to justification is helpful. If later people tell us that they want to remove `<>` again, we can please everyone by moving to the elegant `not (Int.equal foo bar)`.

This is mostly for consistency with the rest of the code base. `!=` is easily used instead `<>` (and `==` instead of `=`)  (see https://github.com/ocaml/ocaml/pull/9080)

Also note that  documentation of `==` says
> On non-mutable types, the behavior of [( == )] is
   implementation-dependent;

**Pull request merged**
