### PR TITLE
Add --profinfo XX to ./configure

### PR DESCRIPTION
**Pull request by lefessan**
Support for adding profinfo in headers is added by Spacetime. This commit
generalizes that support by providing this feature without Spacetime.
You can now specify "./configure --profinfo 22" for example to tell OCaml that you want the last 22 bits of the header (on 64 bits) to be preserved to store block profiling information.

### CODE REVIEW

**Comment by lefessan** [comment]
The patch also contains some fixes on Spacetime:
- `{asmrun|byterun}/spacetime.h` are converted to a single file in `caml/spacetime.h`
- `PROFINFO_WIDTH` is used in `mlvalues.h` in a place where its previous value (26) was hardcoded

**Comment by mshinwell** [comment]
Maybe `--profinfo-bits` for the configure option would be more descriptive?

Could you please split the patch for the fix to the hard-coded value in `mlvalues.h` into a separate pull request against the 4.04 branch?  That was an oversight, and we should fix it there.

**Comment by alainfrisch** [comment]
I like the feature, but not the name.  If I understand correctly, this is about reserving bits from the header words, for whatever purpose one can imagine.  This could be used for debugging (e.g. tracing where a value has been created) as well as profiling, for instance; and possibly for other purposes.

What about `-reserved-header-bits`?

**Comment by lefessan** [comment]
I followed @alainfrisch naming advice for the option in `configure`, but it is still called `profinfo` internally, following the initial name from Spacetime. I am not sure it is worth also changing the name internally.

Maybe we can merge, and change the name later if really important.

**Comment by lefessan** [comment]
Looks like we have no opposition to the latest version, so merging.

**Pull request merged**
