### PR TITLE
manual: switch to utf-8 encoding

### PR DESCRIPTION
**Pull request by Octachron**
This PR proposes to switch the encoding of the manual to utf-8.
This amounts essentially to:
- changing hevea charset
- changing latex encoding option
- switching the encoding of diacritics in French names.

### CODE REVIEW

**Comment by Octachron** [comment]
I forget to mention, that this change does not allow to freely use unicode characters in the manual, since it requires to declare each unicode characters with `\DeclareUnicodeCharacter{0394}{\Delta}` in the preamble. But *good* unicode support would require to switch to lualatex.

**Comment by pmetzger** [comment]
I'm very much in favor of this. It's a change whose time has come.

**Review by gasche — DISMISSED** [review]

**Comment by gasche** [comment]
It took me some time to find a reliable way to grep for non-ascii characters on my machine, but the following script

```shell
# compute differences
for f in $(find . -name '*.etex'); do iconv -f latin1 -t utf8 $f > $f.utf; done

# review the differences
for f in $(find . -name '*.etex'); do diff -u $f $f.utf; done | less
```

shows that there are more latin1-specific characters in the `.etex` files of the manual. Could you make sure that they are all gone?

```shell
$ for f in $(find . -name '*.etex'); do diff -q $f $f.utf; done 
Files ./tutorials/advexamples.etex and ./tutorials/advexamples.etex.utf differ
Files ./biblio.etex and ./biblio.etex.utf differ
Files ./allfiles.etex and ./allfiles.etex.utf differ
```

**Comment by Octachron** [comment]
I will transcode the biblio.etex file (which is an old French file). However, for the other files,  I think that your test is caught on the issue that the utf-8 byte séquence for precomposed "é" and "ô" are also valid latin1 byte sequence for "Ã©" and "Ã´" .

**Comment by gasche** [comment]
Indeed, only `biblio.etex` needs an update; I think that the other two files are just here because I ran my tests from `trunk` rather than your branch -- apologies for not pointing that out earlier.

**Comment by Octachron** [comment]
I have transcoded the incriminated file (and now I am wondering how many of those documents are still available by ftp ).

**Comment by xavierleroy** [comment]
Farewell, Latin-1.  You served us well, but your time is over. 

I suggest to remove the `biblio.etex` file entirely.  It is not included in the manual, and for good reason: it hasn't been updated since 1995 or so, and is still centered on Caml Light.

**Comment by gasche** [comment]
I decided to go ahead and merge -- the current proposed changes are good. @Octachron, if you do decide to remove `biblio.etex` and check that it works as intended, you might consider pushing directly instead of doing a PR.

**Comment by sanette** [comment]
currently all HTML files in the `libref` dir have `charset=iso-8859-1`. Would it be possible to switch them to UTF8 as well?
Leaving isolatin is not consistent in some files, eg Ocaml_operators.html, that use some UTF8 chars.

**Comment by gasche** [comment]
Yes, switching them to UTF8 sounds perfectly fine. Would you like to submit a PR?

**Comment by sanette** [comment]
It seems that it is enough to add "-charset "UTF-8"" to ocamldoc in the Makefile. I can do it if you want

**Pull request merged**
