### PR TITLE
Derive magic numbers from VERSION file

### PR DESCRIPTION
**Pull request by nojb**
This PR is an experiment along the lines of @xavierleroy's suggestion https://github.com/ocaml/ocaml/issues/9627#issuecomment-639602066.

The idea is to derive the magic numbers from the `VERSION` file, so that developers no longer need to maintain them manually.

- Version `M.mm.pp+...` corresponds to magic number `Caml1999XMmm`, where `X` is a character that depends on the file type.
- `utils/config.ml` now depends on `VERSION`. 
- `VERSION` should be updated just before performing a bootstrap.

The first commit contains a transient change of version to `0.27` in order to be able to compile. The second commit contains the version change + bootstrap and restores the version to `4.12`.

What do you think?

### CODE REVIEW

**Comment by dra27** [comment]
The following patch releases have bumped magic numbers:
- 3.11.1 bumped cmo and cma magic numbers
- 4.07.1 bumped cmi and cmt magic numbers

There might want to be a mechanism for this?

**Comment by gasche** [comment]
I think that we would have more control with a MAGIC_NUMBER file that is separate from VERSION. (Updating them both at release time is easy, and we could decide to also do it for patch releases when necessary.)

Having magic numbers correspond directly to the user-facing version number is nice (it would help a lot for good error messages on magic mismatches). But this leads to difficulties if we want to keep the same magic-number size (which sounds important for users, at least as long as they are not using the recent `Magic_number` module).

We *could* have the room for optional patchlevel bumps if we used a more compact encoding, for example using hexadecimal-then-stuff for the first two letters (major, minor), and a convention to bump the third one in exceptional situations.

**Comment by nojb** [comment]
> I think that we would have more control with a MAGIC_NUMBER file that is separate from VERSION. (Updating them both at release time is easy, and we could decide to also do it for patch releases when necessary.)

True. But unless the extra flexibility is justified, I think it would be nice to avoid the extra file, for simplicity's sake. As you mention below, we could just include the patchlevel in the magic number, but it would mean changing the general format of magic numbers (and necessarily doing a bootstrap for each patch release).

> Having magic numbers correspond directly to the user-facing version number is nice (it would help a lot for good error messages on magic mismatches). But this leads to difficulties if we want to keep the same magic-number size (which sounds important for users, at least as long as they are not using the recent `Magic_number` module).

Are you aware of any projects that depend on the present format of the magic number?

**Comment by xavierleroy** [comment]
> Are you aware of any projects that depend on the present format of the magic number?

Well, the file(1) Unix command has a pretty good understanding of the present format:
```
#------------------------------------------------------------------------------
# $File: ocaml,v 1.5 2010/09/20 18:55:20 rrt Exp $
# ocaml: file(1) magic for Objective Caml files.
0	string	Caml1999	OCaml
>8	string	X		exec file
>8	string	I		interface file (.cmi)
>8	string	O		object file (.cmo)
>8	string	A		library file (.cma)
>8	string	Y		native object file (.cmx)
>8	string	Z		native library file (.cmxa)
>8	string	M		abstract syntax tree implementation file
>8	string	N		abstract syntax tree interface file
>9	string	>\0		(Version %3.3s)
```
If we change our format significantly, it will take a while to push an updated format description.

**Comment by xavierleroy** [comment]
I think a reasonable compromise is to use one "base 36" digit for each of the three components of the version number (MAJOR, major, minor), base 36 being 0 ... 9, A (=10) ... Z (=35).  So, 4.13.2 would be `4D2`.  That's somewhat readable (like hexadecimal is somewhat readable) yet leaves room for a lot of version numbers.

**Comment by dra27** [comment]
Sounds good. Would we want to bump the magic numbers routinely on a patch release? The other option would be to put the third part in config.mlp (so just the `4D` derived from VERSION). The 0 would _never_ be changed on trunk, but there would remain fine-grained control on release branches if needed?

It’s the weekend, so I propose that all that remains is an awk script to convert VERSION to the new format 😉

**Comment by gasche** [comment]
It is inconvenient to bump the magic number too often; for example, I think that Merlin needs an update whenever that happens. Doing extra patchpoint releases quickly is useful and I wouldn't want to slow that too much. Ideally we would have a mechanism to explicitly bump on a few rare patchpoint releases. (We could say that `4D0` means `4.13` and not `4.13.0`, or use `4D-` before the first patchlevel bump.)

**Comment by nojb** [comment]
So to summarize, the following alternatives have been proposed:

1. [this patch] `M.mm.pp+... -> Caml1999cMnn`.
   Pros: `M.mm` version can be read off the magic number; fully automatic
   Cons: cannot change magic numbers for patch releases
2. [@xavierleroy] `M.mm.pp+... -> Caml1999cXYZ` where `(X,Y,Z)` is the base-36 encoding of `(M,mm,pp)`.
   Pros: full version can kind-of be read off the magic number; fully automatic
   Cons: mandatory magic number change for every version change, even for small patch releases.
3. [@gasche] Use a different file `MAGIC_NUMBERS` separate from `VERSION` and update that by hand as needed.
   Pros: no need to manually update each magic number, just the one file.
   Cons: still an extra file to update.
4. [@gasche] `M.mm.pp+...` -> `Caml1999cXY0` where `(X,Y)` is the base-36 encoding of `(M,mm)` for every release of `M.mm` until the first magic number bump.
   Pros: no need to bump magic numbers for patch releases
   Cons: neither fully automatic nor fully manual. In my view, inferior to the other alternatives.

**Comment by dra27** [comment]
I think your characterisation of option 4 seems a tad harsh on it! All four options _automatically_ bump the magic number when _branching_ (so trunk will always have a different magic number from release branches). We then have to solve the question of whether we want manual or automatic bumping of the magic number for the patch part - option 1 is the only one which can't do either.

There is a downside to option 4 that there'd be a risk of merging a bumped patchlevel in `utils/config.mlp` back on to trunk by mistake, but I'm not sure why having that `0` or `-` remaining in `utils/config.mlp` constitutes such a downside?

**Comment by nojb** [comment]
> I think your characterisation of option 4 seems a tad harsh on it!

OK, I softened the language somewhat :)

> All four options _automatically_ bump the magic number when _branching_ (so trunk will always have a different magic number from release branches). We then have to solve the question of whether we want manual or automatic bumping of the magic number for the patch part - option 1 is the only one which can't do either.

I don't actually recall the usual workflow: is it the case that the `VERSION` file is updated just before making a release branch?

> There is a downside to option 4 that there'd be a risk of merging a bumped patchlevel in `utils/config.mlp` back on to trunk by mistake, but I'm not sure why having that `0` or `-` remaining in `utils/config.mlp` constitutes such a downside?

My main criticism of 4. is that it seems a bit too complicated for my taste. If we want control of the magic numbers regarding patch releases I would go with 3.

**Comment by Octachron** [comment]
>  I don't actually recall the usual workflow: is it the case that the VERSION file is updated just before making a release branch?

The version file is updated just before (to bump the dev version) and just after the branching (the new release branch dev number is incremented, and the minor version is incremented on trunk).

**Comment by dra27** [comment]
If I understand @gasche's suggestion correctly, a difference between 3 and 4 is that _all or none_ of the magic numbers would be bumped at once for a patch reelase whereas with 4 you can bump the specific ones affected (so the 3.11.1 bump, for example, would not have affected Merlin, if we'd had Merlin then!).

I'm still puzzled why `"Caml1999I%%SHORTVERSION%%"` is so much less complicated than `"Caml1999I%%SHORTVERSION%%0"`, but it's not relevant to the discussion! 🙂

**Comment by nojb** [comment]
> If I understand @gasche's suggestion correctly, a difference between 3 and 4 is that _all or none_ of the magic numbers would be bumped at once for a patch reelase whereas with 4 you can bump the specific ones affected (so the 3.11.1 bump, for example, would not have affected Merlin, if we'd had Merlin then!).

Actually I realize I didn't quite understand @gasche's suggestion for 4, so please disregard my criticism of it.

> I'm still puzzled why `"Caml1999I%%SHORTVERSION%%"` is so much less complicated than `"Caml1999I%%SHORTVERSION%%0"`, but it's not relevant to the discussion! 🙂

It is not, and it is :)

**Comment by gasche** [comment]
(I didn't mind the criticism.)

I think the important point, whose details we haven't actually discussed yet, is: what is the workflow if we want to have control over whether patchlevel releases bump the magic numbers or not?

Of course, if you do not have a provision for this, everything is simpler. But then either:
- We bump magic numbers at each patchpoint release. This would probably reduce our freedom to do patchpoint releases because it affects several tools.
- We don't bup magic numbers at patchpoint release. if you need to make an important fix that requires changing some file format, you have to make an extra major release.
Either workflow may be workable, but it's a conscious decision to make, probably with input from release managers.

I'm not completely sure that we can find a workflow that is flexible enough for our needs, and sensibly simpler overall than "write the right thing in release notes and have release managers do it by hand every couple months".

**Comment by nojb** [comment]
OK, I finally understood @gasche's original suggestion (and @dra27's comment following it), and it seems good!

In a nutshell the proposed approach/workflow is as follows: for a version `M.mm.pp+...` in `VERSION`, derive magic numbers according to the formula `Caml1999cXY0` where `(X,Y)` is the base 36 encoding of `(M,mm)` (so `pp` is ignored here).

This means we would systematically bump all magic numbers in the first commit after creating a release branch (since it is at this point that the `VERSION` file is updated).

If at any point it is necessary to bump the magic number in a release branch this can be done by manually editing `config.mlp` following the same encoding and bumping the third digit, eg `Caml1999cXY1`.

Does everyone agree? If yes, I can update the PR accordingly.

**Comment by dra27** [comment]
That sounds good to me! @gasche suggested using `-` instead of `0` and I can see the case for that. One could imagine being surprised that both 4.13.0 and 4.13.1 report magic numbers with `4D0` (I guess there can be a comment in config.mlp which explains that if a patch release needs a bumped magic number then the `-` gets changed to `1`, etc., but it's rare that this'll happen, so I expect it would be done carefully!).

The other thing would be to update https://github.com/ocaml/ocaml/blob/trunk/tools/release-checklist#L155 to include the need to bootstrap after bumping `VERSION` to a new number on `trunk` (in fact, `VERSION` itself should probably include a comment that changing the major/minor numbers requires a bootstrap?)

**Comment by nojb** [comment]
I rebased the PR as per what was discussed. The new format for magic numbers corresponding to `M.mm.pp+...` is `Caml1999cXY-`, where `(X, Y)` is the base36-encoding of `(M, mm)`. For `4.12`, we have `(X, Y) = (4, C)`.

The conversion is done with a `bash` script using POSIX `bc`. Not sure how portable that is. Better solutions welcome! (Feel free to even push directly to my branch.)

If everyone agrees with this, then I will update then doc, add a comment to `VERSION` explaining the need to bootstrap, etc.

**Comment by dra27** [comment]
https://github.com/dra27/ocaml/commit/5569ff68ef4a0cf6eff0d25f3629e2f70999f2e2 uses GNU make's `$(word )` function to do the conversion (I haven't actually run it on macOS, but the functions are available in GNU make 3.80, according to the manual...)

That introduces a slightly tedious chain `make` -> `make-version-header.sh` -> `make`, but `make-version-header.sh` is a hangover from pre-GNU make days. https://github.com/dra27/ocaml/commit/b163e8b6c7b26402934067859396de1964bcf333 eliminates it entirely (NB, if cherry-picking then the tiny refactoring https://github.com/dra27/ocaml/commit/55e642cdb9bf4b88f3e11d5cee38655a1b8cddab is needed)

I'd say that not introducing a dependency on a calculator is useful (the first commit) and the second part could be the subject of a separate PR (it's not actually related to this)

**Comment by nojb** [comment]
Thanks @dra27! I have cherry-picked your commits into this PR.

**Comment by dra27** [comment]
No problem - I see you also spotted the stray `prerr_endline`!

I obviously can't review my own code, but the rest of this looks fine to me. If the elimination of `tools/make-version-header.sh` is approved, I'd suggest that `tools/Makefile.version` is unnecessary and the `BASE36` and `B36` macros in it could be moved to `Makefile.common`. I'm not sure who owes whom a review at the moment (!!), but perhaps @shindere could take a look at `runtime/Makefile`, and I believe it's only polite to inform @damiendoligez of another of his shell scripts potentially being removed!

Note that the machinery in `runtime/Makefile` allows `OCAML_VERSION` to be overridden for testing purposes, so you can say `rm -f runtime/caml/version.h ; make -C runtime OCAML_VERSION="5.01.12+this+is+mean and what made+you+do+this" caml/version.h` and check that the commands executed look sensible. I note in the code that trailing spaces on the additional info are ignored (I'm not really sure that the inclusion of spaces was ever really intended?!) but there is one other minor difference: the new version does not support an absent patch number in `VERSION`, but I think that the only reason `make-version-header.sh` did is because it was written before OCaml 3.08.0.

**Comment by shindere** [comment]
I wouldn't mind reviewing `runtime/Makefile`, but where is it?

I didn't see it on the PR branch.

Did I miss something?

**Comment by nojb** [comment]
> I wouldn't mind reviewing `runtime/Makefile`, but where is it? I didn't see it on the PR branch. Did I miss something?

Can you check again? The diff is there as far as I can see.

**Comment by shindere** [comment]
Now I can see it.

I'm happy with the code.

The only thing I'd like to ask is the removal or rewording of the
initial comment. To me, the code is not the right place to document a
change, e.g. "before it was like this, now it is like that". This is
better documented in the commit message that introduces the change,
because the commit _is_ the change so that's where documentation of that
change should go.

**Comment by mshinwell** [comment]
We had a "real world" problem with magic numbers earlier this week for Flambda 2.0: we forgot to bump them when we changed the `.cmx` file format.  The setup with the dune build at present is such that the first-stage compiler (which for us is a normal Closure or Flambda 1 compiler) is used for the build of the stdlib.  This resulted in the Flambda 2.0 compiler trying to read the `.cmx` files written by the first-stage compiler.  A segfault and a certain amount of wasted time ensued.

So my question is this: how do we accommodate workflows like this under the new scheme?  This is not a different "version" of the compiler (in the sense of `VERSION`) and indeed it probably shouldn't be, as it might cause trouble when dropping it into existing environments that have version number expectations.  I doubt the Flambda 2.0 work is the last time this situation will arise.

**Comment by gasche** [comment]
@mshinwell the safest solution in your scenario would be to use a different magic number kind (the letter part) for `flambda2` than for `flambda`.

**Comment by mshinwell** [comment]
@gasche I guess so, but it seems a bit peculiar.  For example, it would affect `file` output, if I understand correctly.  It would also mean that the file extension to magic letter mapping isn't 1:1 any more, although that isn't necessarily a problem.

**Comment by dra27** [comment]
@mshinwell - in that case, can the development work on flambda 2 bump the patch part? i.e. bump the `-` to `1`, etc.?

**Comment by Octachron** [comment]
Going back to this PR which I find quite compelling, it seems that for flambda, and other alternative compilers, we could reserve higher patch versions (from A to W?) . And if one day this is not enough, we could switch to a variable-length encoding for those versions where backward-compatibility does not matter much.

**Comment by nojb** [comment]
Following discussion in the developer's meeting and in the spirit of trying to exercise a bit of PR discipline, I'm shutting this one down. The feature itself had a relatively positive reception so we may want to resucitate it in the future.

**Pull request closed without merging**
