### PR TITLE
Permanently stop building Camlp4 in Travis builds

### PR DESCRIPTION
**Pull request by ghost**
Camlp4 has been out for a few years now, we should stop building it on every PR.

### CODE REVIEW

**Comment by gasche** [comment]
Could you also remove ocamlbuild, which was only ever included to build camlp4, and also remove the commented-out `opam` lines?

**Comment by ghost** [comment]
Sure, it's done

**Review by gasche — APPROVED** [review]
For the record, this is the conclusion of a discussion that has been going on-and-on among maintainers about having CI failures when Camlp4 breaks. I personally always supported keeping Calmp4 as part of the CI (to make it easier / cheaper to have good camlp4 support at the time of a new OCaml release), but it sounds like there is a growing consensus that we could stop this part of the CI to simplify upstream OCaml development processes.

I therefore approve this PR; I hope that Camlp4 (and Camlp5) will keep being updated in a timely manner when new OCaml releases occur, but ensuring this will be the job of their respective maintainers, hopefully helped by other Continuous Integration tools (opam-builder or ci.ocaml.io, for example).

**Comment by xavierleroy** [comment]
Standing for our esteemed release manager who is on vacations, I'm happy to merge this.  Thanks all for the discussion and prompt resolution.

**Pull request merged**
