### PR TITLE
Update a copyright year

### PR DESCRIPTION
**Pull request by komainu8**
Hello,

I update copyright year in README.
Because it remains as it was 1996 - 2019.

At first, I was only going to add 2020 in it.
However, if that’s the case we need to update it every year.

So, I suggest that we describe "since 1996" instead of "1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020". 

Because the copyright only needs to describe the year of publication of the work.
By this, we don't need to update it every year.

Thanks,

### CODE REVIEW

**Comment by dra27** [comment]
Context: https://www.gnu.org/licenses/gpl-howto.en.html and https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

I would suggest that "are copyright every year 1996-2020 inclusive" may be appropriate. It's a question for @xavierleroy ultimately, though.

@Octachron - is this another (relatively) minor thing for the release-checklist 🙂

**Comment by xavierleroy** [comment]
On another project I was told recently that it's not necessary to list the years (of active work) in a copyright notice.  (It was in the US before 1989.)  So maybe we could simplify the release process by not listing the years at all.

**Comment by dbuenzli** [comment]
IANAL but I once read the swiss (YMMV) copyright law. What I got through this is that as an author your works are protected de facto, *whether you put a copyright notice or not*. Besides this protection expires 50 years after your *death* – 70 years for non-computer program works. 

This basically means that in switzerland the actual date of when the work occurs does not matter. At that point I decided I had better things to do in my life than updating copyright notices.

It would be interesting to ask your lawyers though. One could claim only the work of the original date relinquishes the rights according to the mentioned license, not further modifications. But I would be surprised if that was the case, as it would certainly be the author's *intention*, otherwise the author would have done it another file. But you never know, lawyers like twisted reasonings. Also of course, this may vary according to the juridiction you are subject to.

**Comment by xavierleroy** [comment]
What @dbuenzli describes is essentially the terms of the [Berne Convention for the Protection of Literary and Artistic Works](https://en.wikipedia.org/wiki/Berne_Convention), the international treaty that gives minimal, almost universally-accepted guarantees about copyright and author rights.  (Individual countries can offer stronger guarantees, and a few countries haven't signed it yet).

While the Berne convention was drafted and first signed by a number of European countries in 1887, it took a while to be accepted outside Europe, with the USA adopting it in 1989, China in 1992, and Russia in 1995.  That's why explicit copyright notices were necessary to establish copyright in the USA before 1989, but have been optional since 1989. 

Speaking of US copyright (https://en.wikipedia.org/wiki/Copyright_law_of_the_United_States):

> Copyright protection generally lasts for 70 years after the death of the author. If the work was a "work for hire", then copyright persists for 120 years after creation or 95 years after publication, whichever is shorter.

So, if we were shooting for maximal protection it might still be worth documenting the years of creation / publication.  Although those years are already documented in the Git log and the history of releases.

**Comment by komainu8** [comment]
Thank you for your comments.

To sum up, is it most appropriate to make the following modification?

```diff
diff --git a/README.adoc b/README.adoc
index 73d7a8861..5bd7c636a 100644
--- a/README.adoc
+++ b/README.adoc
@@ -76,8 +76,8 @@ the compiler may work under other operating systems with little work.
 
 == Copyright
 
-All files marked "Copyright INRIA" in this distribution are copyright since
-1996 Institut National de Recherche en Informatique et en Automatique (INRIA)
+All files marked "Copyright INRIA" in this distribution are copyright every year
+1996-2020 inclusive Institut National de Recherche en Informatique et en Automatique (INRIA)
 and distributed under the conditions stated in file LICENSE.
 
 == Installation
```

**Comment by xavierleroy** [comment]
In the end I went for an interval "1996-2020" without further elaboration, that should be clear enough.  I'm still unhappy that we'll have to update the file every year!  Thanks all for the discussions and advice.

**Comment by shindere** [comment]
Xavier Leroy (2020/08/29 07:51 -0700):
> In the end I went for an interval "1996-2020" without further
> elaboration, that should be clear enough.  I'm still unhappy that
> we'll have to update the file every year!  Thanks all for the
> discussions and advice.

Will the update really cost more than a simple sed script replacing
1996-2020 with 1996-2021 ?

**Pull request closed without merging**
