### PR TITLE
Do some trivial cleanup in parsing/location.ml

### PR DESCRIPTION
**Pull request by Armael**
I was trying to read `parsing/location.ml` and thought these small cleanups wouldn't hurt.

### CODE REVIEW

**Comment by gasche** [comment]
I am not terribly excited by the removal of `;;`, which adds noise and conflict risks for a not very good reason. I'd say, if a file uses a consistent style, respect it, otherwise do as you wish for the sentences you introduce, but leave other's double-semicolon-preferences in peace.

**Comment by Drup** [comment]
Well, after the patch, it uses a consistent style: the one used by 99% of the OCaml code in recent years. :)

I doubt there are many patches in progress that touches `location.ml` to have conflicts with, so that's not a very strong argument.

**Comment by trefis** [comment]
> so that's not a very strong argument.

I disagree. Merlin maintains patches against `location.ml` (to strip the "Error:" prefix, and similar things). The conflicts aren't necessarily hard to handle, but I'd still be happier if there weren't any. :)

**Comment by Armael** [comment]
> I am not terribly excited by the removal of ;; [...]. I'd say, if a file uses a consistent style

`location.ml` is not even consistent itself, at the moment. Half of it uses ;;, the other half doesn't.

> noise and conflict risks

Yes, I guess that's the generic argument against doing cleanups...

**Comment by Armael** [comment]
In any case, I surely do not want to make Merlin mainteners' life harder. So feel free to close this if you think it's not worth the trouble.

**Comment by gasche** [comment]
As I tried to hint at, I think the cost/benefit ratio would be higher without the double-semicolon changes.

**Comment by Armael** [comment]
I'm not sure I understand why. As I see it, the rest of the changes are as trivial/uninteresting and prone to conflicts as removing `;;`

**Comment by gasche** [comment]
The concrete details are for @trefis to say, but in his stead I would feel less miserable about rebasing a move of a local recursive function into a local scope than against a traveling double semicolon.

**Comment by trefis** [comment]
Actually, Armael just volunteered offline to look at the patches maintained on Merlin in the hope of doing the required upstream changes to minimise the patches Merlin needs to apply.

As I trust him to keep his word, I’d now be perfectly happy to merge any reasonable cosmetic changes (and I personally don’t find the double semicolon particularly less reasonable than the rest of the changes).

**Comment by dra27** [comment]
I would be more excited by the removal of `;;` if it were universal and came with machinery to prevent its reintroduction (e.g. a warning which could be turned on for the codebase)

However, I always like removing `open`s!

**Comment by gasche** [comment]
@trefis: The "Accept" button is there for you.

**Comment by trefis** [comment]
@dra27: **clearly** the follow-up to check typo should be to force the codebase to be ocamlformated. :)

**Comment by Armael** [comment]
Ok, I can leave the removal of ;; for another day if that makes everyone happier. Let me rebase the patch...

**Review by trefis — APPROVED** [review]
LGTM.

**Pull request merged**
