### PR TITLE
Rebase 4.04.0

### PR DESCRIPTION
**Pull request by dra27**
This is obviously related to #913.

This is a clean rebase of tag 4.04.0 onto trunk. Technical details to follow, but I'm wondering if we could do this rather than always having a merge commit. It's a pain when bisecting that you find the "merge changes from commit" and then have to repeat the bisect on that branch in order to get more detail.

I haven't refreshed the bootstrap or .depend files other than at the very end - not sure if that's a problem.

I also haven't (yet) double-checked that everything on 4.04 *after* the 4.04.0 tag is also on trunk (this should be done via cherry-pick).

There are 4 new commits at the end just prior to the bootstrap and .depend updates cleaning up Changes and the make clean.

Just wanted to get this in before any classic merge is completed for if there's a discussion of rebase vs merge for getting these back on to trunk.

### CODE REVIEW

**Comment by dra27** [comment]
I've tested this with msvc64+flambda and mingw64 - I'll let CI do the rest.

I've created an account on Inria but understandably not yet been approved for the ocaml project - please could a dev with the ability to check the results push this to precheck?

**Comment by dra27** [comment]
The final commit can be dropped once #963 is merged.

Technical details. I've had a few instances recently when doing large bisects where you find that the "Merge changes from OCaml x.y branch back into trunk" commits are your problem. The nuisance is that you then have to resume bisecting on that branch to narrow down the offending commit. I'd like to propose that we stop merging changes from release branches back into trunk and instead rebase them. *Addendum*: actually, that was the case up to 4.02 - 4.03 was merged back in without squashing, but this means the history is much longer than it needs to be (which increases the bisect time, if not creating the need to run two of them)

A consequence of this is that merge commits which include changes are a nuisance - in this case GPR#801 where comments were added in the merge commit itself.

Firstly, a commit adding "merge=ours" for /Changes was added to gitattributes (you need to run `git config --global merge.ours.driver true` once) was added after the 4.04.0 tag.

``git rebase -i -X theirs `git merge-base 4.04.0 trunk` ``
  - Move the new commit with the change to .gitattributes to the top
  - Commit 420d475 marked for editing
  - Commit setting test branch for camlp4 to 4.04 deleted
  - "first commit of branch 4.04" deleted
  - The 6 commits related to tagging the two beta releases deleted
  - Final two commits (tagging 4.04.0 deleted)

This means that VERSION is definitely not updated, though it also means that dependency and bootstrap changes within the development commits might not build - but I think I'm correct that the worst case when bisecting is that you'd have to build fully (so `make world bootstrap opt opt.opt` rather than just `make world.opt`)? The `-X theirs` means that conflicting bootstrap files *should* be ignored (I think it'll just keep what's on trunk already). When the rebase paused for the edit, I ran `git cherry-pick --no-commit -m 1 -X theirs f096c` which picked Damien's additions to #801 and then ran `git commit -m "Merge PR#801 into 4.04"` followed by `git rebase --continue`.

At this point, all the merge commits are eliminated and the branch is a linear sequence of commits. This can/should be checked with git diff 4.04.0 where the only change should be the alteration to .gitattributes. At this point, I ran `git rebase trunk` - it's important not to do an interactive rebase, or there are lots of pointless pauses at commits which have already been cherry-picked (a non-interactive rebase just silently drops them, which is what we want). There were of course a few merge conflicts - Alain's _opt additions and a few other further conflicting developments on trunk, but nothing that couldn't be clearly seen with a visualisation tool (i.e. gitk) to hand.

Finally, one more interactive rebase on to trunk allowed the fake first commit to be deleted (so /Changes restored to normal attributes) and then I checked `Changes` and tidied a few small build system things.

**Comment by dra27** [comment]
OK, I realise that no one wishes to review all these changes again, so I have attempted to combine the process of reviewing my diff and also rebasing Gabriel's. Here's what I did, starting on a clone of trunk called gasche-squash: `git merge --squash gasche/trunk-with-4.04`

The following minor merge conflicts:

```diff
diff --git a/driver/optmain.ml b/driver/optmain.ml
index 3535b8d..c82d20f 100644
--- a/driver/optmain.ml
+++ b/driver/optmain.ml
@@ -239,16 +239,12 @@ let main () =
     Arg.parse_expand (Arch.command_line_options @ Options.list) anonymous usage;
-    if !gprofile && not profiling then
+    if !gprofile && not Config.profiling then
       fatal "Profiling with \"gprof\" is not supported on this platform.";
-    if !output_name <> None && !compile_only &&
-          List.length !process_thunks > 1 then
-      fatal "Options -c -o are incompatible with compiling multiple files";
-    let final_output_name = !output_name in
-    if !output_name <> None && not !compile_only then
-      (* We're invoked like: ocamlopt -o foo bar.c baz.ml.
-         Make sure the intermediate products don't clash with the final one. *)
-      output_name := None;
-    List.iter (fun f -> f ()) (List.rev !process_thunks);
-    output_name := final_output_name;
+    Compenv.process_deferred_actions
+      (ppf,
+       Optcompile.implementation ~backend,
+       Optcompile.interface,
+       ".cmx",
+       ".cmxa");
     readenv ppf Before_link;
     if
       List.length (List.filter (fun x -> !x)
diff --git a/manual/README.md b/manual/README.md
index e640f7d..2b28dca 100644
--- a/manual/README.md
+++ b/manual/README.md
@@ -89,6 +89,7 @@ chapters (or sometimes sections) are mapped to a distinct `.etex` file:
     - The ocamlbuild compilation manager: `ocamlbuild.etex`
     - Interfacing C with OCaml: `intf-c.etex`
     - Optimisation with Flambda: `flambda.etex`
+    - Memory profiling with Spacetime: `spacetime.etex`
     - Fuzzing with afl-fuzz: `afl-fuzz.etex`
 
 Note that ocamlc,ocamlopt and the toplevel options overlap a lot.
diff --git a/manual/manual/allfiles.etex b/manual/manual/allfiles.etex
index 00b87b7..67f392f 100644
--- a/manual/manual/allfiles.etex
+++ b/manual/manual/allfiles.etex
@@ -73,6 +73,7 @@ and as a
 % \input emacs.tex
 \input{intf-c.tex}
 \input{flambda.tex}
+\input{spacetime.tex}
 \input{afl-fuzz.tex}
 
 \part{The OCaml library}
diff --git a/manual/manual/cmds/Makefile b/manual/manual/cmds/Makefile
index e5048de..adcb043 100644
--- a/manual/manual/cmds/Makefile
+++ b/manual/manual/cmds/Makefile
@@ -1,7 +1,7 @@
 FILES=comp.tex top.tex runtime.tex native.tex lexyacc.tex intf-c.tex \
   depend.tex profil.tex debugger.tex browser.tex ocamldoc.tex \
-  warnings-help.tex ocamlbuild.tex flambda.tex afl-fuzz.tex \
-  unified-options.tex
+  warnings-help.tex ocamlbuild.tex flambda.tex spacetime.tex \
+  afl-fuzz.tex unified-options.tex
 
 TOPDIR=../../..
 include $(TOPDIR)/Makefile.tools
@@ -10,8 +10,8 @@ TRANSF=$(OCAMLRUN) ../../tools/transf
 TEXQUOTE=../../tools/texquote2
 FORMAT=../../tools/format-intf
 
-WITH_TRANSF= ocamldoc.tex top.tex intf-c.tex flambda.tex afl-fuzz.tex\
-  lexyacc.tex debugger.tex
+WITH_TRANSF= ocamldoc.tex top.tex intf-c.tex flambda.tex spacetime.tex \
+  afl-fuzz.tex lexyacc.tex debugger.tex
 
 etex-files: $(FILES)
 
diff --git a/manual/manual/library/stdlib.etex b/manual/manual/library/stdlib.etex
index a8e1ad1..d8c4074 100644
--- a/manual/manual/library/stdlib.etex
+++ b/manual/manual/library/stdlib.etex
@@ -91,6 +91,7 @@ be called from C \\
 "Filename" & p.~\pageref{Filename} & operations on file names \\
 "Gc" & p.~\pageref{Gc} & memory management control and statistics \\
 "Printexc" & p.~\pageref{Printexc} & a catch-all exception handler \\
+"Spacetime" & p.~\pageref{Spacetime} & memory profiler \\
 "Sys" & p.~\pageref{Sys} & system interface \\
 \end{tabular}
 \end{latexonly}
@@ -131,7 +132,7 @@ be called from C \\
 \item \ahref{libref/Scanf.html}{Module \texttt{Scanf}: formatted input functions}
 \item \ahref{libref/Set.html}{Module \texttt{Set}: sets over ordered types}
 \item \ahref{libref/Sort.html}{Module \texttt{Sort}: deprecated}
-\item \ahref{libref/Spacetime.html}{Spacetime}
+\item \ahref{libref/Spacetime.html}{Module \texttt{Spacetime}: memory profiler}
 \item \ahref{libref/Stack.html}{Module \texttt{Stack}: last-in first-out stacks}
 \item \ahref{libref/StdLabels.html}{Module \texttt{StdLabels}: Include modules \texttt{Array}, \texttt{List} and \texttt{String} with labels}
 \item \ahref{libref/Stream.html}{Module \texttt{Stream}: streams and parsers}
```

followed by `git commit -am "Gabriel's merge"`. This commit can then be compared with this branch. Ignoring changes to .depend, bootstrap files and files updated at the end of this GPR, I find only the following differences:
 - Travis using the wrong camlp4 branch (already known)
 - Changes file (I believe all the differences are corrections in my branch resulting from double-merging)
 - A trivial difference in testsuite/tests/asmcomp/Makefile (my diff reflects history better!!)
 - A difference in how tools/Makefile is fixed. Gabriel has fixed this in a merge but it was actually a trunk GPR which broke this - hence I've put the slightly different fix in a separate commit https://github.com/ocaml/ocaml/pull/962/commits/75b8a5e98a4e3c80b424cc025883b879662aace2 at the end of the process.

One further thing for review (though it's more a procedural nit-pick than a problem): I don't think that the optimised _opt versions in String should be hidden in a merge commit. They weren't part of Alain's original GPR on trunk so, although obvious, I feel those should be separated hence https://github.com/ocaml/ocaml/pull/962/commits/98efe338dd6ed755f36c96dea9c4fcfc1130a934.

**Comment by shindere** [comment]
David Allsopp (2016/12/10 05:34 -0800):
> I've tested this with msvc64+flambda and mingw64 - I'll let CI do the rest.
> 
> I've created an account on Inria but understandably not yet been
> approved for the ocaml project - please could a dev with the ability
> to check the results push this to precheck?

DAvid, I just approved you so hopefully you should now have access to
the results of precheck.

**Comment by dra27** [comment]
Thank you! I'm just in the process of pushing it to precheck... for some reason my Internet connection is very slow this morning :sleepy:

**Comment by dra27** [comment]
Rebased to remove the conflict on appveyor.yml now that #963 is merged. The other merge this morning is trivial, so should affect the output.

**Review by damiendoligez — CHANGES_REQUESTED** [review]
This is the significant part of the diff between your merge and my merge. Please review and apply as appropriate...

```diff
diff --git a/Changes b/Changes
index 5e628b2..cdae871 100644
--- a/Changes
+++ b/Changes
@@ -298,6 +292,12 @@ OCaml 4.04.0 (4 Nov 2016):
    mirage-os uses "xen")
   (Anil Madhavapeddy)
 
+### Other libraries
+
+- MPR#4834, GPR#592: Add a Biggarray.Genarray.change_layout function
+  to switch bigarrays between C and fortran layouts.
+  (Guillaume Hennequin, review by Florian Angeletti)
+
 ### Code generation and optimizations:
 
 - PR#4747, GPR#328: Optimize Hashtbl by using in-place updates of its
diff --git a/manual/manual/refman/exten.etex b/manual/manual/refman/exten.etex
index 1460f5b..da81bfa 100644
--- a/manual/manual/refman/exten.etex
+++ b/manual/manual/refman/exten.etex
@@ -1810,7 +1810,9 @@ end
 \section{Extension nodes}\label{s:extension-nodes}
 
 (Introduced in OCaml 4.02,
-infix notations for constructs other than expressions added in 4.03)
+infix notations for constructs other than expressions added in 4.03,
+infix notation (e1 ;\%ext e2) added in 4.04.
+)
 
 Extension nodes are generic placeholders in the syntax tree. They are
 rejected by the type-checker and are intended to be ``expanded'' by external
@@ -1878,6 +1880,7 @@ Examples:
 \begin{verbatim}
 let%foo x = 2 in x + 1     === [%foo let x = 2 in x + 1]
 begin%foo ... end          === [%foo begin ... end]
+x ;%foo 2                  === [%foo x; 2]
 module%foo M = ..          === [%%foo module M = ... ]
 val%foo x : t              === [%%foo: val x : t]
 \end{verbatim}
diff --git a/stdlib/string.ml b/stdlib/string.ml
index 1d38227..39a6e94 100644
--- a/stdlib/string.ml
+++ b/stdlib/string.ml
@@ -23,14 +23,14 @@
 
 external length : string -> int = "%string_length"
 external get : string -> int -> char = "%string_safe_get"
-external set : bytes -> int -> char -> unit = "%string_safe_set"
-external create : int -> bytes = "caml_create_string"
+external set : bytes -> int -> char -> unit = "%bytes_safe_set"
+external create : int -> bytes = "caml_create_bytes"
 external unsafe_get : string -> int -> char = "%string_unsafe_get"
-external unsafe_set : bytes -> int -> char -> unit = "%string_unsafe_set"
+external unsafe_set : bytes -> int -> char -> unit = "%bytes_unsafe_set"
 external unsafe_blit : string -> int ->  bytes -> int -> int -> unit
                      = "caml_blit_string" [@@noalloc]
 external unsafe_fill : bytes -> int -> int -> char -> unit
-                     = "caml_fill_string" [@@noalloc]
+                     = "caml_fill_bytes" [@@noalloc]
 
 module B = Bytes
 
diff --git a/stdlib/string.mli b/stdlib/string.mli
index 6c250ef..2324ce3 100644
--- a/stdlib/string.mli
+++ b/stdlib/string.mli
@@ -58,7 +58,7 @@ external get : string -> int -> char = "%string_safe_get"
    Raise [Invalid_argument] if [n] not a valid index in [s]. *)
 
 
-external set : bytes -> int -> char -> unit = "%string_safe_set"
+external set : bytes -> int -> char -> unit = "%bytes_safe_set"
   [@@ocaml.deprecated "Use Bytes.set instead."]
 (** [String.set s n c] modifies byte sequence [s] in place,
    replacing the byte at index [n] with [c].
@@ -68,7 +68,7 @@ external set : bytes -> int -> char -> unit = "%string_safe_set"
 
    @deprecated This is a deprecated alias of {!Bytes.set}.[ ] *)
 
-external create : int -> bytes = "caml_create_string"
+external create : int -> bytes = "caml_create_bytes"
   [@@ocaml.deprecated "Use Bytes.create instead."]
 (** [String.create n] returns a fresh byte sequence of length [n].
    The sequence is uninitialized and contains arbitrary bytes.
@@ -338,11 +338,11 @@ val split_on_char: char -> string -> string list
 (* The following is for system use only. Do not call directly. *)
 
 external unsafe_get : string -> int -> char = "%string_unsafe_get"
-external unsafe_set : bytes -> int -> char -> unit = "%string_unsafe_set"
+external unsafe_set : bytes -> int -> char -> unit = "%bytes_unsafe_set"
   [@@ocaml.deprecated]
 external unsafe_blit :
   string -> int -> bytes -> int -> int -> unit
   = "caml_blit_string" [@@noalloc]
 external unsafe_fill :
-  bytes -> int -> int -> char -> unit = "caml_fill_string" [@@noalloc]
+  bytes -> int -> int -> char -> unit = "caml_fill_bytes" [@@noalloc]
   [@@ocaml.deprecated]
diff --git a/stdlib/stringLabels.mli b/stdlib/stringLabels.mli
index 0eb416f..9844901 100644
--- a/stdlib/stringLabels.mli
+++ b/stdlib/stringLabels.mli
@@ -24,7 +24,7 @@ external get : string -> int -> char = "%string_safe_get"
 
    Raise [Invalid_argument] if [n] not a valid index in [s]. *)
 
-external set : bytes -> int -> char -> unit = "%string_safe_set"
+external set : bytes -> int -> char -> unit = "%bytes_safe_set"
   [@@ocaml.deprecated "Use BytesLabels.set instead."]
 (** [String.set s n c] modifies byte sequence [s] in place,
    replacing the byte at index [n] with [c].
@@ -34,7 +34,7 @@ external set : bytes -> int -> char -> unit = "%string_safe_set"
 
    @deprecated This is a deprecated alias of {!BytesLabels.set}. *)
 
-external create : int -> bytes = "caml_create_string"
+external create : int -> bytes = "caml_create_bytes"
   [@@ocaml.deprecated "Use BytesLabels.create instead."]
 (** [String.create n] returns a fresh byte sequence of length [n].
    The sequence is uninitialized and contains arbitrary bytes.
@@ -243,11 +243,11 @@ val compare: t -> t -> int
 (* The following is for system use only. Do not call directly. *)
 
 external unsafe_get : string -> int -> char = "%string_unsafe_get"
-external unsafe_set : bytes -> int -> char -> unit = "%string_unsafe_set"
+external unsafe_set : bytes -> int -> char -> unit = "%bytes_unsafe_set"
   [@@ocaml.deprecated]
 external unsafe_blit :
   src:string -> src_pos:int -> dst:bytes -> dst_pos:int -> len:int ->
     unit = "caml_blit_string" [@@noalloc]
 external unsafe_fill :
-  bytes -> pos:int -> len:int -> char -> unit = "caml_fill_string" [@@noalloc]
+  bytes -> pos:int -> len:int -> char -> unit = "caml_fill_bytes" [@@noalloc]
   [@@ocaml.deprecated]
```

**Comment by dra27** [comment]
OK - everything apart from stdlib/string.ml{,i} and stdlib/stringLabels.ml was to do with commits after the 4.04.0 tag which I've now rebased as well. Just looking into the other now!

**Comment by dra27** [comment]
I'm confused (or more likely being slow) - where have those changes to the String external declarations come from? I don't see them either on 4.04 or trunk?

As far as I can see, those changes were part of #596 but were reverted in #772?

**Comment by dra27** [comment]
Oh, I see - I never was good at left and right (I'm looking at the diffs the wrong way around) - fix very shortly.

**Comment by dra27** [comment]
OK, I'm still confused but at least now I'm ready to hand it back - having looked through the conversation on it, why are we not merging #772 from 4.04 to trunk?

**Comment by damiendoligez** [comment]
In my opinion, #772 was a compatibility change to avoid last-minute breakage in 4.04.0, but it doesn't make sense to carry it forever. The `string_set` primitives will have to disappear at some point.

Could you merge with or without it (I'd prefer without, to avoid changing trunk back and forth) then open a specific PR, so we can reach a final decision about it without delaying the merge?

**Comment by dra27** [comment]
Right, four commits removed which will go back in a separate GPR shortly.

Just allowing CI to double-check everything and ensure that #949 hasn't done anything unexpected <sigh>

The four commits removed create the final diffs in `string.ml{,i}` and `stringLabels.mli` but also removes `%string_safe_set` and `%string_unsafe_set` from bytecomp/translcore.ml (which is correct).

Once Travis and AppVeyor come back, I'll merge and submit those 4 commits in a new GPR

**Comment by damiendoligez** [comment]
> but also removes %string_safe_set and %string_unsafe_set from bytecomp/translcore.ml (which is correct).

In fact, this is the part that will cause the most compatibility problems, but it's fine to do that in trunk at this point of the cycle.

**Comment by dra27** [comment]
Sorry - I phrased that badly. I mean that %string_safe_set and %string_unsafe_set are no longer *added* by my merge (all I meant was that your earlier comment with the diff didn't request their removal from my merge). So trunk will have no effects of #772 at all.

**Comment by dra27** [comment]
Final change was just to remove the GPR#770 notes from Changes - so merging now.

**Comment by gasche** [comment]
Nothing unexpected, but flowcaml is broken in 4.05 by the `string_safe_set -> bytes_safe_set` change in this PR.

**Comment by dra27** [comment]
@gasche - can you make noise on #972 instead (does flowcaml work with #972?)?

**Comment by gasche** [comment]
I'll give it a try, thanks.

**Pull request merged**
