### PR TITLE
otherlibs/unix/mmap.c: trial at supporting MAP_ANON or MAP_ANONYMOUS

### PR DESCRIPTION
**Pull request by UnixJunkie**
Untested yet.
I also need to update the related doc.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/ocaml/issues/10280

**Comment by UnixJunkie** [comment]
My test strangely says:
neither MAP_ANON nor MAP_ANONYMOUS

**Comment by UnixJunkie** [comment]
The test:
```ocaml
let create_mmapped_bigarray () =
  let fd = Unix.(openfile "ba_file" [O_RDWR; O_CREAT; O_TRUNC] 0o700) in
  let ba = Unix.map_file fd Bigarray.int Bigarray.c_layout true [|5|] in
  Bigarray.Genarray.set ba [|0|] 1;
  Bigarray.Genarray.set ba [|1|] 2;
  Bigarray.Genarray.set ba [|2|] 3;
  Bigarray.Genarray.set ba [|3|] 4;
  Bigarray.Genarray.set ba [|4|] 5;
  ba

let create_anon_mmapped_bigarray () =
  let fdm1: Unix.file_descr = Obj.magic (-1) in
  let ba = Unix.map_file fdm1 Bigarray.int Bigarray.c_layout true [|5|] in
  Bigarray.Genarray.set ba [|0|] 1;
  Bigarray.Genarray.set ba [|1|] 2;
  Bigarray.Genarray.set ba [|2|] 3;
  Bigarray.Genarray.set ba [|3|] 4;
  Bigarray.Genarray.set ba [|4|] 5;
  ba

let print_bigarray ba =
  for i = 0 to 4 do
    Printf.printf "read: %d\n%!" (Bigarray.Genarray.get ba [|i|])
  done

let overwrite_bigarray ba =
  Bigarray.Genarray.set ba [|0|] (-5);
  Bigarray.Genarray.set ba [|1|] (-4);
  Bigarray.Genarray.set ba [|2|] (-3);
  Bigarray.Genarray.set ba [|3|] (-2);
  Bigarray.Genarray.set ba [|4|] (-1)

let main () =
  (* test 1: share some values between processes using a mmapped bigarray *)
  let file_backed_ba = create_mmapped_bigarray () in
  Printf.printf "Created BA\n%!";
  print_bigarray file_backed_ba;
  (match Unix.fork () with
   | 0 -> (* child *)
     begin
       overwrite_bigarray file_backed_ba;
       exit 0
     end
   | _cpid -> (* father *)
     begin
       Unix.sleepf 0.1;
       Printf.printf "BA after child modifications\n%!";
       print_bigarray file_backed_ba
     end
  );
  (* test 2: share some values between processes using an anonymous
     mmapped bigarray *)
  let anon_mmapped_ba = create_anon_mmapped_bigarray () in
  Printf.printf "Created anon BA\n%!";
  print_bigarray anon_mmapped_ba;
  (match Unix.fork () with
   | 0 -> (* child *)
     begin
       overwrite_bigarray anon_mmapped_ba;
       exit 0
     end
   | _cpid -> (* father *)
     begin
       Unix.sleepf 0.1;
       Printf.printf "Anon BA after child modifications\n%!";
       print_bigarray anon_mmapped_ba
     end
  )

let () = main ()

```

**Comment by UnixJunkie** [comment]
Compiled with
```bash
ocamlbuild test.native -package unix -package bigarray
```

**Comment by UnixJunkie** [comment]
I guess something is wrong with the preprocessing directives; I'll look further another day.

**Comment by dra27** [comment]
If/when you come back to this, please "play CI golf" on your own fork (i.e. test with a different branch name and then merge/fast-forward this one once it's working). GitHub Actions is running in your fork too (see [the last run at github.com/UnixJunkie/ocaml/actions](https://github.com/UnixJunkie/ocaml/actions/runs/708123615)), but it ties up resources running it in ocaml/ocaml as well.

**Comment by UnixJunkie** [comment]
I have no idea on how to push this further honestly. Even defining _DEFAULT_SOURCE or _GNU_SOURCE before any header include in mmap.c doesn't define MAP_ANONYMOUS.

**Comment by UnixJunkie** [comment]
If @alainfrisch or @pmetzger know better, any advice would be welcome.

**Comment by UnixJunkie** [comment]
The following works and does show that MAP_ANONYMOUS can be used on my computer:
```C
#include <sys/mman.h>
#include <stdio.h>

int main(int _argc, char** argv) {
  int shared = 0;
#if defined(MAP_ANONYMOUS)
  shared |= MAP_ANONYMOUS;
  fprintf(stderr, "MAP_ANONYMOUS\n");
  fflush(stderr);
#elif defined(MAP_ANON)
  shared |= MAP_ANON;
  fprintf(stderr, "MAP_ANON\n");
  fflush(stderr);
#else
  fprintf(stderr, "neither MAP_ANON nor MAP_ANONYMOUS\n");
  fflush(stderr);
#endif
  return 0;
}
```

**Comment by Octachron** [comment]
@UnixJunkie : could you please do your preliminary tests on your own fork? You should only open a pull request when you have either a reviewable code (for a draft PR), or a mergeable code otherwise. 

Note that it is perfectly possible to work collectively on a branch on your fork. 

Taking in account the current state of this PR, I am closing it. Please don't hesitate to reopen this PR once you have sorted the existing issues.

**Pull request closed without merging**
