### PR TITLE
Add functions Unix.timegm and Unix.timelocal

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by nojb** [comment]
Have you tried this one on Windows ? As far as I remember there is no `timegm` on Windows.

**Comment by dra27** [comment]
@nojb - you are correct, `timegm` and `timelocal` are both GNU/BSD extensions and are not present in any version of the Windows CRT

@Chris00 - `timelocal` is equivalent to `mktime` - the [GNU docs](https://www.gnu.org/software/libc/manual/html_node/Broken_002ddown-Time.html#index-timelocal) seem to suggest its use should be rare - what's the argument here?

**Comment by xavierleroy** [comment]
Quoting the Linux man page: 

"These functions are nonstandard GNU extensions that are also present on the BSDs.  Avoid their use; see NOTES.

NOTES

The timelocal() function is equivalent to the POSIX  standard  function mktime(3).  There is no reason to ever use it.

For  a portable version of timegm(), set the TZ environment variable to UTC, call mktime(3) and restore the value of TZ.  "

**Comment by Chris00** [comment]
I should have read more carefully the man page indeed.  Would you mind that I add some documentation to the Unix module so that one does not have to look somewhere else?

**Pull request closed without merging**
