### PR TITLE
Compiler drivers: make -keep-locs the default

### PR DESCRIPTION
**Pull request by dbuenzli**
This PR changes the compiler drivers to use `-keep-locs` instead of `-no-keep-locs` by default as this provides better error messages to the end users.

While it is always tricky to change default values, it seems that the main effect will be to affect, in certain cases, the optimality of incremental (re)compilation for build systems that do not specify the option explicitly (see [this comment](https://caml.inria.fr/mantis/view.php?id=7574#c18022) by @alainfrisch). This drawback should be considered against the general improvement in the programmer experience of the OCaml compilers.

Fixes [MPR7575](https://caml.inria.fr/mantis/view.php?id=7575), partially fixes [MPR7574](https://caml.inria.fr/mantis/view.php?id=7574). [MPR6311](https://caml.inria.fr/mantis/view.php?id=6311) has additional discussion about making this the default.

The bootstrap was needed because compiling with `-keep-locs` changes the hash of `pervasives.cmi`.

### CODE REVIEW

**Comment by Drup** [comment]
I'm strongly in favor of this. Debugging complicated functor code is much easier with the additional locations (it is pretty essential for me when working on tyxml, in particular).

**Review by yallop — APPROVED** [review]
I find the arguments in favour of `-keep-locs` as the default (better error messages) stronger than the arguments against (additional recompilation for whitespace changes).

The implementation looks obviously correct.

**Comment by gasche** [comment]
@alainfrisch :-)

**Comment by alainfrisch** [comment]
Great.

Just wondering: was the bootstrap really needed?

**Comment by dbuenzli** [comment]
> Just wondering: was the bootstrap really needed?

Maybe I could have changed OCaml build system's to not use the new default. See #compiler slack on june 30th for the error.

**Comment by dbuenzli** [comment]
@gasche One thing that may be worth adding to the changelog and save someone else two hours is that the digest of cmi files will now depend on the paths given on the cli. This may break some fancy build systems (e.g. my way of circumenventing [MPR7589](https://caml.inria.fr/mantis/view.php?id=7589) point 4. in odig's [build system](https://github.com/dbuenzli/odig/blob/0df18d782f219237de917bbcc149fab7d393ac75/myocamlbuild.ml)).

(I proposed the change I guess it's fair I had to suffer from it)

**Comment by gasche** [comment]
Here would be my revised change entry:

```
- MPR#7575, GPR#1219: Switch compilers from -no-keep-locs to -keep-locs by default.
  This provides better error messages. Note that, as a consequence, .cmi digests
  now depend on the file path as given to the compiler.
  (Daniel Bünzli)
```

Is that what you had in mind? Otherwise feel free to suggest a different wording.

(The "given on the cli" part in your message is reassuring because it means that reproducible-builds are not broken by the change, or at least that building a project from two different clones of the same repository (at different absolute paths) will not see a difference, as long as in-project paths are passed as relative paths. Right?)

**Comment by dbuenzli** [comment]
That seems right.

**Comment by dbuenzli** [comment]
FTR this also seem to affect `ctypes` https://github.com/ocamllabs/ocaml-ctypes/issues/552

**Pull request merged**
