### PR TITLE
Attributes sometimes dropped by parser

### PR DESCRIPTION
**Pull request by let-def**
These look like mistakes introduced during refactoring.
I am not sure what is the exact syntax allowed for attributes, I just used what seemed obvious.

### CODE REVIEW

**Comment by alainfrisch** [comment]
Thanks!  This should probably go in 4.03.  Can you rebase on that branch (I think you need to open a new PR)?

**Comment by gasche** [comment]
One more reason to use Menhir ( #292 ) as a parser generator...

**Comment by gasche** [comment]
Do we know which faulty refactoring it was? Can we check that all mistakes it introduced were covered?

**Comment by Drup** [comment]
@gasche Pretty sure it was mine (https://github.com/ocaml/ocaml/pull/342) and menhir would help for only half of the patch. Enabling warnings is sufficient for the other half ...

**Comment by alainfrisch** [comment]
Indeed, adding `[@@@ocaml.warning "+27"]` to parser.mly would have detected the errors.

**Comment by alainfrisch** [comment]
We should really enable more warnings in the compiler.  I've started to work on it in this branch https://github.com/ocaml/ocaml/tree/enable_more_warnings and already found one probable bug in the type-checker.

**Pull request closed without merging**
