### PR TITLE
Improve boxing behaviour with flambda

### PR DESCRIPTION
**Pull request by lpw25**
For code like:

``` ocaml
let foo x = x +. 10.

let bar () =
  let y = 12.0 in
    (foo [@inlined never]) y +. (foo [@inlined never]) y
```

Flambda will currently produce clambda equivalent to:

```
(let (y 12.0)
  ((apply foo y)
   (apply foo y))
```

which, because of how unboxing now works, causes `y` to be unboxed and then re-boxed for both calls to `foo`.

This patch changes how flambda is converted to clambda, so that we instead get clambda like:

```
  ((apply foo 12.0)
   (apply foo 12.0))
```

which avoids the unnecessary allocation.

### CODE REVIEW

**Comment by alainfrisch** [comment]
The problem is in the new unboxing strategy in cmmgen (see my email to caml-devel this morning), which currently wrongly interprets constants as boxing constructions.  This should be easy to fix, and I think it's a better place than in flambda-specific passes.

**Comment by lpw25** [comment]
Even with fixes to `cmmgen` this patch will still be an improvement. It "un-anfs" constant expressions, which means that any optimisations which `cmmgen` performs will have more freedom. For example, if one of the uses of `y` should be unboxed and the other shouldn't then this patch makes it easy for `cmmgen` to naturally do the right thing.

**Comment by chambart** [comment]
As this is not obvious in leo's comment, since flambda try quite aggressively to share constants, writing

```
let bar () =
  (foo [@inlined never]) 12.0 +. (foo [@inlined never]) 12.0
```

will also result in the same code.

The change is simple and mix well with the 'spirit' of this pass and fix some flambda specific problem, so I think this is ok to be flambda specific here.

**Comment by mshinwell** [comment]
I think Un_anf should probably have been able to cope with variables used non-linearly (when appropriate, e.g. when bound to a constant) in the first place, so this patch seems appropriate.  I have not yet checked the details.

**Comment by chambart** [comment]
This applies to all kinds of constants. We may want to restrict this to some.

**Comment by mshinwell** [comment]
@chambart We think this can go into 4.04.  What do you want to do about your comment about restricting to certain varieties of constants?

**Comment by chambart** [comment]
@mshinwell @lpw25 , No this is not really important. This can be accepted as it is

**Comment by chambart** [comment]
I forgot to mark this as approved before, here it is !

**Pull request merged**
