### PR TITLE
Fix an oversight in #10188

### PR DESCRIPTION
**Pull request by damiendoligez**
Setting the default policy is not enough, we also have to set the initial value of the freelist function pointers...

x-ref #10188

### CODE REVIEW

**Comment by gasche** [comment]
It looks like there is now non-trivial implicit synchronization between various initialization places in the runtime. Could you add comments that link them together so that we don't forget to change half of them next time?

**Comment by stedolan** [comment]
> It looks like there is now non-trivial implicit synchronization between various initialization places in the runtime. Could you add comments that link them together so that we don't forget to change half of them next time?

Alternatively: leave `caml_fl_p_foo` null by default, but call `caml_set_allocation_policy` during startup.

**Comment by xavierleroy** [comment]
My understanding is that the code currently on trunk is broken and this PR fixes it.

Either @damiendoligez agrees to the proposed improvements and implements them quickly, or I'll merge this PR as is.

**Comment by damiendoligez** [comment]
I have implemented @stedolan's suggestion and I took the opportunity to do the initialization properly (i.e. in the same way as the other GC parameters).

This is now ready for review.

**Review by stedolan — APPROVED** [review]

**Comment by gasche** [comment]
Meta comment: we have an ongoing discussion about those annoying maintainers who approve PRs without merging them -- in situations where it is unclear what they are waiting for. For this one I thought about "the Changes entries still need a change" (but actually it looks okay-ish, if we consider this PR a minor update on an existing change) and "the CI run was not finished yet at approval time" (but then a clear way to mark this would be to use the "merge-me" label.) I'll assume that it was the latter, go ahead and merge.

**Pull request merged**
