### PR TITLE
Fix ocamltest's rm_rf function w.r.t. symlinks

### PR DESCRIPTION
**Pull request by dra27**
Found in opam, where we've cribbed the `rm_rf` function in our testsuite. It doesn't affect ocamltest (at least at the moment) but `Sys.file_exists "dangling-symlink"` returns `false` and `Sys.is_directory "dangling-symlink"` therefore raises `Sys_error` which causes the `rm_rf` function to fail if there any dangling symlinks in the tree being erased.

The fix is in two parts:
- Always call `Sys.remove`, even if `Sys.file_exists` returned `false` (so `rm_rf "dangling-symlink"` works)
- In the `erase` auxiliary function, we know that the path exists (because it was either positively tested with `Sys.file_exists` or it was returned by `Sys.readdir`; discounting race conditions, obviously), so the call to `Sys.is_directory` is guarded with an extra `Sys.file_exists`. If `Sys.file_exists` returns false, then we know we must be looking at a dangling symlink, and continue to `erase_file`

### CODE REVIEW

**Review by gasche — APPROVED** [review]
This looks ok. For the record, here is an implementation that I would find slightly easier to follow, because `erase` does not have any precondition:

```ocaml
let rec erase path =
  if not (Sys.file_exists path) then begin
    (* this could still be a dangling symlink, erase silently *)
    try Sys.remove path with Sys_error _ -> ()
  end else if Sys.is_directory path then begin
    Array.iter (fun entry -> erase (Filename.concat path entry))
               (Sys.readdir path);
    Sys.rmdir path
  end else
    erase_file path
in
try erase path
with Sys_error err ->
  raise (Sys_error (Printf.sprintf "Failed to remove %S (%s)" path err))
```

**Comment by gasche** [comment]
Is there a place in our testsuite to include a regression test for this issue?

**Comment by gasche** [comment]
Status: I made two change suggestions that may (or may not) warrant a small rebase before merging.

**Comment by dra27** [comment]
Your function isn't equivalent - errors should not be silently ignored once we start recursing. When `rm_rf path` is called, `path` could be a dangling symlink, which we can't test without pulling in more of Unix (we need `lstat`). So in that _one_ case we do a "hope for the best" removal of the dangling symlink. If `path` exists, and we call `erase`, all entries are now being read using `readdir` so the only thing we mustn't do is call `is_directory` on them without first checking that they "exist". If the _link target_ doesn't exist we still know that the symlink itself exists because it was returned by a `readdir` call, so we should not ignore errors deleting it.

**Comment by dra27** [comment]
For the tests, I can manually see that it's working with:

```diff
diff --git a/testsuite/tests/tool-ocamltest/dangling.ml b/testsuite/tests/tool-ocamltest/dangling.ml
new file mode 100644
index 0000000000..c9525f67bc
--- /dev/null
+++ b/testsuite/tests/tool-ocamltest/dangling.ml
@@ -0,0 +1,5 @@
+(* TEST
+* not-windows
+** script
+script = "ln -sf broken target"
+*)
```
but plumbing that in to be a failing test is non-trivial. On trunk, after `make -C testsuite one TEST=tests/tool-ocamltest/dangling.ml` the test will leave behind its `_ocamltest` directory; with this PR it doesn't, but it's already the case that `ocamltest` chooses to ignore errors when erasing the test directory (because Windows, IIRC).

**Comment by gasche** [comment]
I understand that the two functions are not equivalent ; sometimes doing something slightly weaker (tracking less precise static information about the calling context) is key to being able to simplify the code. My impression is the version I proposed is in fact acceptable, as it will only ignore failures that occur on files for which `Sys.file_exists` return false, and who cares about those files anyway? But if you insist that your version is better, so be it, and we can merge it.

**Comment by dra27** [comment]
In the `erase` function, the allowable time `Sys.file_exists` should return false is precisely for a dangling symlink for which `Sys.remove` is expected to succeed - any errors imply race conditions or something else going on which I certainly think shouldn't be dropped.

However, while musing on this doing something I realised there's another bit of the handling which is certainly worth hardening the code is very incorrect w.r.t. symlinks to directories in that it follows them! This would not have silently, because the final call to `Sys.rmdir` will fail on a symlink to a directory, but the extra commit attempts a deletion first and only recurses once it's certain that it's encountered a real directory.

**Comment by gasche** [comment]
I'm okay with also approving that, but at which point does it become reasonable to try to have a proper symlink-detection function in the ocamltest runtime? Making those guesses is getting increasingly complex, and I would be surprised if it didn't create some sort of fragility.

**Comment by dra27** [comment]
We either have to have those functions in the OCaml runtime itself (e.g. how `Sys.rmdir` came into being) or they have to go `Ocamltest_unix` but to go in there it has to be meaningful to run ocamltest without it, so we'd still have this code as the "fallback".

For what it's worth, I believe is now correct w.r.t. symlinks - they were just forgotten about before!

**Pull request merged**
