### PR TITLE
fix #11482: random crash in large closure allocation

### LINKED ISSUE #11482: Segmentation fault linked to a big closure allocation with OCaml 5.0
I observed a segmentation fault with OCaml 5.0 (`alpha0`, `alpha1` and `ocaml/opam:debian-11-ocaml-5.0` docker image), which can be reproduced with the following steps. The same steps do not trigger segmentation fault with OCaml 4.14 and below (but the problem looks such fragile with respect to any change that I am not sure it is related to OCaml 5.0).

```
$ docker run -it --rm ocaml/opam:debian-11-ocaml-5.0
opam@...:~$ opam pin add https://github.com/thierry-martinez/stdcompat.git#disable-magic
opam@...:~$ opam pin add https://github.com/thierry-martinez/metapp.git
opam@...:~$ opam pin add https://github.com/thierry-martinez/metaquot.git#ocaml-5.0-segfault
opam@...:~$ opam install refl
```

I wish I would be able to make a more standalone and small example, to be sure that the fault is not in my code, but I am stuck in how I can reduce it without making the segmentation fault disappears. I already asked for help on [discuss.ocaml.org](https://discuss.ocaml.org/t/need-help-for-understanding-a-segmentation-fault-with-ocaml-5-0/10265) and @lthls commented:

> I’ve started debugging the issue, and it looks like there is a big closure allocation (size 552, start of environment at 527) that is being initialized, and the GC is running in the middle of the initialization. Because the block is not initialized yet, the start_of_env field is not yet set properly, so the block is pushed on the mark stack with offset 0 (i.e. not skipping code pointers). After a bit of marking, the block is put back on the mark stack with a non-zero offset, and execution resumes. The initialization code finishes running, and when marking resumes it starts trying to mark code pointers. This is what triggers the segfault. I haven’t found yet why the GC manages to run between the initial allocation and its initialization though: the window is very short, and doesn’t contain any code that looks likely to trigger a GC. Hopefully someone more familiar than me about the GC will find the answer.

Sorry for such a non minimal example, and thank you very much!

### PR DESCRIPTION
**Pull request by damiendoligez**
Note: this is still a draft, I still want to check that it does make the bug disappear.

Fixes #11482

### CODE REVIEW

**Comment by damiendoligez** [comment]
Checked on 5.0.0~alpha0, it does fix the segfault. Now ready for review.

**Comment by damiendoligez** [comment]
Note: will have to move the Changes entry and cherry-pick to 5.0.

**Review by xavierleroy — APPROVED** [review]
This looks like a good fix for #11482.  Two minor remarks:
- I'm not super happy about the function name `caml_alloc_shr_with_safepoint`.  Is `check_urgent_gc` equivalent to the safe points that ocamlopt implements?  `caml_alloc_shr_check_urgent` might be more descriptive.  `caml_alloc_shr_check` would be shorter :-)
- I wondered about performance.  We can probably assume that ocamlopt-generated code rarely allocates directly in the major heap, in which case performance should be OK.

**Comment by damiendoligez** [comment]
I've renamed the function to `caml_alloc_shr_check_gc`. About performance, we are not doing more checks that before, but we're removing the double initialization, so this is a strict improvement.

**Review by xavierleroy — APPROVED** [review]
Looks good to me, thanks.  Could you please move the Changes entry to 5.0, merge in trunk, and cherry-pick -x in 5.0 ?  Thanks.

**Comment by damiendoligez** [comment]
Cherry-picked to 5.0 (as 43754a58038b4cff519c8a68d4e5884a4dfda6eb). Thanks for the review.

**Pull request merged**
