### PR TITLE
Add hash, seeded_hash to Int, Char, Bool, Float, Int32, Int64, Nativeint

### LINKED ISSUE #10259: hash function in modules Bool/Int/Char/String
It would be convenient if modules `Bool`/`Int`/`Char`/`String` would provide a `hash` function, so that we can pass them to functors such as `Hashtbl.Make`.

Of course, we can use the polymorphic hash function `Hashtbl.hash` for this purpose, or define custom hash function (e.g. the identity for type `int`), but that's less convenient from a user's perspective.

Note: module `Float` already provides a `hash` function.

### PR DESCRIPTION
**Pull request by nojb**
Follow-up to #11157.

This PR adds seeded and unseeded hash functions to the following modules: `Int`, `Char`, `Bool`, `Float` (which already included the unseeded hash function), `Int32`, `Int64` and `Nativeint`. The new functions should be compatible with the polymorphic hash functions `Hashtbl.hash` and `Hashtbl.seeded_hash`.

Fixes #10259

### CODE REVIEW

**Comment by c-cube** [comment]
Pardon me if I'm missing something, but should `String` get a hash function too?

Another thing: when I write hash functions for my types (and it happens surprisingly often given that I'm a big fan of hashconsing), the main building blocks are builtin type hash  functions (which this contributes), along with a series of [mixing functions](https://c-cube.github.io/ocaml-containers/3.6/containers/CCHash/index.html#val-combine2) (which I call `combine2`, `combine3`, etc.). I think it would be very helpful to have (some of) these are runtime builtins and in the stdlib.

**Comment by nojb** [comment]
> Pardon me if I'm missing something, but should `String` get a hash function too?

Yes, and this was done in #8878

**Comment by xavierleroy** [comment]
I think it's good to have `hash` and `seeded_hash` functions in these modules so that they can be used directly as arguments to `Hashtbl.Make` and `Hashtbl.MakeSeeded`.  However, you could have implemented the functions as calls to the generic seeded hash function.  Having specialized hashing functions written in C may be more efficient (by how much?) but adding C primitives is a bit of a burden for JS-of-OCaml.

**Comment by xavierleroy** [comment]
> Another thing: when I write hash functions for my types (and it happens surprisingly often given that I'm a big fan of hashconsing), the main building blocks are builtin type hash functions (which this contributes), along with a series of [mixing functions](https://c-cube.github.io/ocaml-containers/3.6/containers/CCHash/index.html#val-combine2) (which I call combine2, combine3, etc.). I think it would be very helpful to have (some of) these are runtime builtins and in the stdlib.

I'd prefer a different API.  Ideally, you don't combine final hash values (the integers in 0...2^30 returned by `Hashtbl.hash` and similar functions): you add data to a rolling hash, then apply a final transformation to get the final hash value.  It's more efficient and makes it possible to have more than 30 bits of information in the rolling hash.  I have some very preliminary code along these lines that I should finish and publish as a separate library.

**Comment by c-cube** [comment]
@xavierleroy I totally agree, if we can get a hashing state that's even better.

For reference, what rust does is quite nice because it does it in a way that doesn't depend on the actual hash function used:
- rust's [Hash](https://doc.rust-lang.org/std/hash/trait.Hash.html) (to define how to hash a type)
- rust's [Hasher](https://doc.rust-lang.org/std/hash/trait.Hasher.html) (the type updated by `Hash`, it is an object implementing some hash function — we can find examples of that in cryptokit, sha, etc. in OCaml I believe)

We have a library called [mhash](https://github.com/imandra-ai/mhash) that does that, with stubs for sha and a basic FNV implementation. Having something similar in the stdlib would be, of course, great. The question is how to keep good performance with the `Hasher`-like abstraction over the hash and the hashing result.

**Comment by nojb** [comment]
> However, you could have implemented the functions as calls to the generic seeded hash function. Having specialized hashing functions written in C may be more efficient (by how much?) but adding C primitives is a bit of a burden for JS-of-OCaml.

Good point. I followed the change in #8878 which added a dedicated C primitive for `String.hash` and `String.seeded_hash`. There are some performance numbers in [#8878](https://github.com/ocaml/ocaml/pull/8878#issue-481502852) for the case of `String`.

**Comment by nojb** [comment]
> you could have implemented the functions as calls to the generic seeded hash function.

This is now done. This PR needs two reviews if it is to move forward.

**Review by xavierleroy — APPROVED** [review]
Looks good to me, thanks!  If we find that these hashing functions are a bottleneck, we can always add back the specialized hash functions in C.  But this is great as a starting point.

**Comment by nojb** [comment]
Friendly ping. Anyone willing to do a second review of this easy PR?

**Comment by c-cube** [comment]
I'm no reviewer, but this looks good to me :slightly_smiling_face: .

As an alternative to specialized hash functions in C, is it in theory possible that in the future, the compiler spits out hashing code directly when the type is known, just like it does for `compare` and `=`?

**Comment by xavierleroy** [comment]
Probably not.  There's too much code involved.

**Comment by nojb** [comment]
Friendly ping.

**Comment by nojb** [comment]
A second official review is still needed before this PR can be merged. Perhaps @gasche or @Octachron can do the honours?

**Comment by gasche** [comment]
I am a bit perplexed by the duplication of the magical parameters `10 100` everywhere, and more generally the amount of duplication that must implicitly stay synchronized (because we advertize that `Hashtbl.seeded_hash` and `Foo.seeded_hash` give the same results). Should we consider having a CamlinternalHash module to share these definitions instead?

**Comment by xavierleroy** [comment]
> I am a bit perplexed by the duplication of the magical parameters 10 100

It could be "1 1" or anything non-zero, really, since the parameters control the recursive traversal of the value being hashed, and here we're hashing base types, so there's nothing to recurse into.

On the other hand, "10 100" is what's used for the generic hash functions, so it's reassuring (perhaps) to have "10 100" everywhere.

> Should we consider having a CamlinternalHash module 

This feels overkill to me.

**Comment by xavierleroy** [comment]
Still waiting for a second "official" review.

**Review by gasche — APPROVED** [review]
Okay. I'm not fond of the implementation (too much duplicated code to my taste) but there is no obviously-better approach, and I agree that the change is correct and useful.

**Comment by xavierleroy** [comment]
Thanks.  I'll merge when CI is green.

**Comment by nojb** [comment]
Thanks!

**Pull request merged**
