### PR TITLE
win32unix: find{first,next}: use abstract type for directory handle

### LINKED ISSUE #11344: Pointer to a custom block manipulated as an `int`
In the Windows implementation of `Unix`:
https://github.com/ocaml/ocaml/blob/5b7a1d16282bb8bd789095b38483201a3b24a549/otherlibs/unix/unix_win32.ml#L467-L471
The values declared as `int`s here, and manipulated by `{open,read,rewind,close}dir`, are actually pointers to a `struct filedescr`. Although I guess the code as it is works, it seems fragile in the sense that it may be broken in the future, for instance by some type-based optimization. It seems preferable to me to use the abstract type `file_descr` (and the `handle` field should be a `file_descr option`).

### PR DESCRIPTION
**Pull request by nojb**
Fixes #11344

### CODE REVIEW

**Comment by dra27** [comment]
The current implementation boxes only on the first directory entry - it's a shame that this approach adds an indirection to the handle on each call. I think it might be simpler to add:

```c
value caml_win32_invalid_handle(value unit)
{
  return caml_win32_alloc_handle(INVALID_HANDLE_VALUE);
}
```
to `unixsupport_win32.c` and then:

```ocaml
type handle

external get_invalid_handle : unit -> handle = "caml_win32_invalid_handle"

let invalid_handle = get_invalid_handle ()
```
to `unix_win32.ml` and use `invalid_handle` instead of `0` with the type updates?

**Comment by OlivierNicole** [comment]
I think what you suggest could work well in a sequential setting.

Does it also avoid crashes in multiple-domain situations? (For instance, with the existing code, concurrent calls of `rewinddir` and `readdir` can cause segfaults). It would be nice to solve both problems at the same time. But there is still possible racy accesses to the `handle` field, and I'm not good enough yet at reasoning with the OCaml memory model to see how bad that can be.

**Comment by nojb** [comment]
> it's a shame that this approach adds an indirection to the handle on each call. I think it might be simpler to add:

Yes, I know :) My personal opinion is that I like it better with the option type; but indeed we could do your suggestion if we wanted to avoid it. Let's wait a bit to see if there are other opinions either way...

**Comment by xavierleroy** [comment]
The runtime cost of an option type is probably negligible given the cost of the system calls involved.  However there might be other ways to write this code that handle the "empty directory" case more gracefully, e.g. making `dir_handle` into a record of functions.  Leave me some time to think about it.

**Comment by dra27** [comment]
@OlivierNicole - we shouldn't be segfaulting any more - I think that could only have been coming from situations where the `dir_handle` of `0` actually got passed to one of the C functions (which then tried to dereference it).

**Comment by nojb** [comment]
Still waiting for a better alternative, but not urgent. Closing.

**Pull request closed without merging**
