### PR TITLE
Flambda: Reduce cmx file sizes (especially in -Oclassic)

### PR DESCRIPTION
**Pull request by fyquah**
The primary motivation of this change is to reduce the cmx files in -Oclassic. Prior to this change, cmx files produced by -Oclassic is substantially bigger than those producted by closure.

Here are the sizes of cmx files in Jane Street's code base with this patch. Rest assured, the compiler from this patch compiles Jane Street's entire code tree:

With cmx files of other libraries hidden:

| Compilation Mode        | trunk   (MB)        | this patch (MB)  |
| ------------- |:-------------:|:-----:|
| -Oclassic                          | 2543.1        |  881.9 |
| -O3                                  |  2731.3       | 2020.7  |

With cmx files between libraries exposed:

| Compilation Mode        | trunk   (MB)        | this patch (MB)  |
| -------------                        |:-------------:|:-----:|
| -Oclassic                          | 2414.7        | 926.4  |
| -O3                                  | 5446.5       |   3689.4 |

Rest assured, the additional work does not noticeably increase compilation time. In fact, the reduced cmx file sizes seem to reduce overall compile time -- about 25% for a parallel -O3 build when cmx files are exposed.

Changes in this branch are on top of #1340 

### Changes to Classic Mode

- Add `is_classic_mode` field to `Flambda.function_declarations`. This means that it is possible to specialize functions from other modules, which are not compiled with classic mode, while compiling a module in classic mode.
- Change the type of `function_declarations` field in `Simple_value_approx.value_set_of_closures` to its a different `function_declarations` type, defined in the same module. The `free_variables`, `free_symbols` and `body` fields are combined to a single option type.
- In classic mode, the bodies of big or recursive functions are not stored in cmx files. (`function_body` is set to `None`). This is done in `asmcomp/build_export_info.ml`

### Changes to All Modes

- Add `Variable_name.t` to replace variable names with a variant, replacing strings at various places.
- Shorten `label` field in `Symbol.t`  by removing the `compilation_unit` prefix.
- Computes the transitive closure of the module's symbol when building `Export_info.t`. Values and symbols that are not referenced by anything in the cmx files are removed from the resultant `Export_info.t`.
- Sharing export id among different instances of `Export_info.Project_closure` in `Export_info.t` where the `closure_id` is same.
- Remove from `closures` field from `Export_info.t`

### CODE REVIEW

**Comment by lpw25** [comment]
I'm going to give this an initial review next week. So @chambart you don't need to read it until after then.

**Comment by xclerc** [comment]
As in #1340, you probably need to bump the magic numbers
for `cmx`/`cmxa` files.

**Comment by mshinwell** [comment]
It's not the main purpose of this pull request, but to give some idea as to how the numbers shape up relative to the existing Closure pass (with `-inline 20`):

- with `.cmx` files visible: the Flambda classic mode `.cmx` files (also with `-inline 20`, which should give approximately the same level of inlining) are about two-thirds of the size of those produced by Closure.  (Yes, Flambda is smaller.)

- with `.cmx` files hidden: the Closure `.cmx` files are about two-thirds of the size of those produced by Flambda.

**Comment by alainfrisch** [comment]
Excellent job.  Can you extend the results to show the corresponding numbers in "closure" mode, and also to include compilation time for the six configurations?

**Comment by lpw25** [comment]
Our numbers on compile times are less reliable (only run once, parallel build, etc.) but after this change they look like:

|         | Closure | Classic | O3 |
|-------|------------|-----------|------|
| Hidden cmx | 27min | 30min | 33min |
| Exposed cmx | 29min | 33min | 68min |

We don't have all the comparable numbers from before this change but `-O3` was 38min and 81min.

**Comment by alainfrisch** [comment]
Thanks, this looks very promising!  Does JS have plans to switch to using flambda (classic/o3), or has this already happened? (I kind of remember that some new projects had been written some time ago already in such a way that the runtime performance would be horrible without flambda.)

**Comment by yminsky** [comment]
We're already using Flambda in some projects, but it's not yet pervasive.
If we can get classic mode within spitting distance of ordinary
compilation, I expect we'll switch to using classic mode by default.

**Comment by chambart** [comment]
Nice update, thanks. I'll review when Leo gives the thumb up.

**Comment by mshinwell** [comment]
Update: @lpw25 is reviewing this at the moment.

**Comment by lpw25** [comment]
As part of reviewing this I decided to split it into three parts. The first of these is #1627. The other two will follow later.

**Comment by xclerc** [comment]
For the record, the second part is in https://github.com/ocaml/ocaml/pull/1665.

**Comment by xclerc** [comment]
For the record, the third (and last) part is in https://github.com/ocaml/ocaml/pull/1666.

**Comment by mshinwell** [comment]
This (very good) work has now been merged as separate pull requests.

**Pull request closed without merging**
