### PR TITLE
The Makefile.nt Rampage

### PR DESCRIPTION
**Pull request by whitequark**
I'm working on a proper Unix-to-Windows cross-compiler opam repository and the proliferation of completely unnecessary Makefile.nt files annoyed me to the greatest extent. So I did a cleanup pass.

After this, the only nontrivial Makefile.nt files are the ones in stdlib (reasonable), asmrun+byterun (needs to have pic/shared/profiling to be sorted out), otherlibs/systhreads (reasonable), and ocamldoc (stupid differences, but beyond my attention span to fix).

I tried to avoid creating a Makefile.shared if there wasn't one, or, conversely, removing, in an effort to keep the diffs tractable, though this results in some inconsistency.

### CODE REVIEW

**Comment by xavierleroy** [comment]
This is clearly a step in the right direction.  I believe that, with judicious use of GNU make features (like in this PR), the whole Makefile/Makefile.nt/Makefile.shared mess can be avoided and single unified Makefiles can be provided instead.  Any volunteers?

**Comment by whitequark** [comment]
Yes. While I am definitely looking forward to the moment when Makefile.nt does not exist, I also feel that it might be a case of too little, too late. The truth is that the Makefiles are 1) full of cruft like at least four different configuration interpolators, or a dozen of copy-pasted depend: targets, and 2) nearly unsuitable for proper cross-compiling, even though some recent additions allow to do it reasonably robustly when the stars align just right (e.g. for opam-cross-windows I have to do things like this: https://github.com/whitequark/opam-cross-windows/blob/master/packages/ocaml-windows32.4.02.3/files/install.sh#L5-L11).

Ideally the OCaml Makefiles would look something like this:
- No recursive make invocations.
- A proper separation between build, host and target compilation.
- Actual compilation rules extracted into make functions e.g. `$(call depend)` `$(call compile-c-build)` `$(call compile-c-host)` `$(call compile-c-target)` `$(call compile-ocaml-host)` `$(call compile-ocaml-target)` etc.
- Usage of the host ocamlrun/etc tools only as an optimization, if at all.
- One global Config.ml that corresponds 1:1 to Makefile.config.
- Reduce the amount of duplication in Makefile.config; there is really no need to have two separate rpath settings for the bytecode and native code C compiler, etc.

I'm strongly compelled to implement this on the basis of massive aesthetic improvement alone, but am unlikely to have time.

**Comment by mshinwell** [comment]
You may want to talk to @chambart , who I believe has some fairly extensive rearrangements so that parallel make always works properly (there might be conflicts or shared work).

**Comment by alainfrisch** [comment]
> I also feel that it might be a case of too little, too late.

Well, this can always be improved later, but this is already a great step forward.  It will reduce quite a bit the risk of divergence Makefile/Makefile.nt and reduce the maintenance efforts.  Unless technical problems are found, I'm in favor of merging soon to avoid conflicts in the future.  I'll try to find reviewing the changes this week.

**Comment by whitequark** [comment]
@mshinwell I've been annoyed by breakage in parallel make in the past, so I also fixed that, in f22564b84d7a5bc. According to my testing, i.e. running `make -j` (sic) repeatedly, there are no more parallel make bugs, although it is not inconceivable that I've missed a bug that arises only in some configurations.

**Comment by gasche** [comment]
@xavierleroy hasn't stated an opinion in favor of merging or not this PR. I would be willing to merge it if I had a clear indication that the PR has been tested on Windows. @whitequark, did you do that, or should we maybe ask Alain?

Pierre's parallelization PR is #442 ; it still says [WIP], so it's not to be considered for merging right now, and I'd work on a "first come, first served" basis here. I looked at the patches and it seems they would not conflict in important ways (they touch different parts of the Makefiles, and @chambart's work does not affect Makefile.nt at all).

**Comment by alainfrisch** [comment]
@whitequark What about the toplevel Makefile.nt?  Did you encounter any problem merging it into Makefile?

**Comment by whitequark** [comment]
@alainfrisch There are a few actual semantic differences, but mostly they differ in irrelevant trivia and `$(MAKEREC)`. I'm not sure what to do with `$(MAKEREC)`. Maybe we could just append `-f Makefile.nt` to `$(MAKE)`?

**Comment by alainfrisch** [comment]
First problem when testing under Windows: 'make -f Makefile.nt clean' fails because otherlibs/win32unix/Makefile.nt includes ../Makefile.nt, which includes Makefile but this refers to a Makefile file relative to the original file, i.e., otherlibs/win32unix/Makefile, and this does not exist.  otherlibs/win32unix should directly include ../Makefile instead.

**Comment by whitequark** [comment]
@gasche I did not since I do not have an environment set up to build on Windows; I'm exclusively interested in cross-compilation. I could probably set one up but it would greatly help if Alain tested it.

**Comment by alainfrisch** [comment]
Second problem:

```
make[1]: Entering directory '/home/frisch/ocaml/trunk/otherlibs/str'
Makefile.nt:19: warning: overriding recipe for target 'depend'
Makefile.shared:29: warning: ignoring old recipe for target 'depend'
Makefile.nt:21: .depend.nt: No such file or directory
```

**Comment by alainfrisch** [comment]
And more problems found later...   I'll see what I can do, but this might take longer than expected.  It would be so useful to have Windows CI running on PRs....

**Comment by whitequark** [comment]
Would a standard MSYS environment work here? If yes then I will set up one on a VM.

**Comment by whitequark** [comment]
Also, I think it should be straightforward to set up an Appveyor builder for OCaml.

**Comment by alainfrisch** [comment]
See https://github.com/ocaml/ocaml/pull/307 .  I don't know what remains to be done to enable the AppVeyor builder. @Chris00 ?

**Comment by alainfrisch** [comment]
I've pushed a branch https://github.com/alainfrisch/ocaml/tree/whitequark-Makefile.nt which starts from this PR and adds one commit (for now) to fix some problems under Windows.

@whitequark Feel free to include these commits in your branch so that they appear in this PR.

At least I get a successful "make -f Makefile.nt clean world opt opt.opt" with the MSVC 32-bit port.

**Comment by damiendoligez** [comment]
I can set up the Inria CI to test this branch under the "experimental" set of jobs if that makes things easier for you guys.

**Comment by alainfrisch** [comment]
> I can set up the Inria CI to test this branch under the "experimental" set of jobs if that makes things easier for you guys.

Yes, it would be helpful to have a test under the 6 Windows ports...  But it's better to wait for @whitequark to include the changes from my branch, I guess.

**Comment by samoht** [comment]
We can also enable [AppveyorCI](https://ci.appveyor.com/login) I have some scripts to set-up cygwin/mingw-{32,64} and opam [here](https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor.yml) and [there](https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor-opam.sh). I'm sure these can be adapted.

**Comment by whitequark** [comment]
@alainfrisch I've incorporated your changes and also rebased against trunk.

**Comment by chambart** [comment]
From what I see, it does not seem to be sufficient for massively parallel build, but don't bother too much with that. I will fix that later. This cleanup works will make the update a lot simpler. Thanks

**Comment by DemiMarie** [comment]
The Makefiles are such a mess that I am tempted to rewrite the build system entirely, either using GNU make or using Python + Ninja.  The latter would also allow getting rid of the ugly `configure` script.

**Comment by alainfrisch** [comment]
> using Python + Ninja

We don't really want to add more build-time dependencies.  (In particular, I suspect that most Windows users don't have a python on their dev machines.)

Modernizing the build system by using more of GNU make is much welcome, although I suggest to discuss the main directions before putting too much work on it.

**Comment by alainfrisch** [comment]
@samoht About AppVeyor: we already have #307.  I think we only need to actually enable the service.

**Comment by bschommer** [comment]
> We don't really want to add more build-time dependencies. (In particular, I suspect that most Windows >users don't have a python on their dev machines.)

Just a short note: Python is quite common as build requirement, for example llvm, qt and some other larger tools use it in their build.

**Comment by c-cube** [comment]
On my computer, python's package is 100MB, and OCaml is 100MB. I think it's a bit overkill as a dependency. On the other hand, ninja looks small, fast, and well-designed; would it be reasonable to generate the ninja build file from OCaml itself?

**Comment by bschommer** [comment]
> On my computer, python's package is 100MB, and OCaml is 100MB. I think it's a bit overkill as a dependency.

Most modern linux distribution ship with some kind of python. However I see  a potential issue there:
Python 2 vs. Python 3

> On the other hand, ninja looks small, fast, and well-designed; would it be reasonable to generate the ninja build file from OCaml itself?

Should be possible.

**Comment by alainfrisch** [comment]
I'm not overly concerned with modern linux distribution, rather with Windows.

**Comment by avsm** [comment]
I have activated the Appveyor service on the ocaml/ocaml GitHub repository now.

**Comment by bschommer** [comment]
> I'm not overly concerned with modern linux distribution, rather with Windows.

I think a lot of developers would be more happy to install python instead of cygwin under windows.

**Comment by alainfrisch** [comment]
We are a long way from eliminating cygwin anyway, since many packages out there depends on it at build time.

**Comment by alainfrisch** [comment]
> I have activated the Appveyor service on the ocaml/ocaml GitHub repository now.

Thanks, that's very nice!

Should one expect to see Appveyor status icons appearing on pull requests, as we have with Travis CI?

**Comment by avsm** [comment]
> Should one expect to see Appveyor status icons appearing on pull requests, as we have with Travis CI?

Yes -- the builds are rather slow, so I'll keep an eye on the status icon for the next few builds.  It doesn't seem to be updating the GitHub Status API just yet.

**Comment by bluddy** [comment]
Python is undoubtedly a better requirement than cygwin for Windows machines, and is far more common. 

> We are a long way from eliminating cygwin anyway, since many packages out there depends on it at build time.

You have to start somewhere. Unfortunately we have a build gap in OCaml since ocamlbuild didn't try to eliminate the need for Makefiles (the 'last mile' of symlinking the executable and choosing from different targets). If a top-down switch to Python instead of makefiles is initiated, it could take over the entire ecosystem, and we would have much better cross-platform compatibility.

**Comment by c-cube** [comment]
I still fail to see why python is needed (or useful) at all. Ninja would probably be great, but generating it from OCaml should be much better. I don't think the community as a whole will move all the packages to cygwin free build systems any time soon, and introducing python in the equation is not going to help…

**Comment by bschommer** [comment]
Python is just more convenient when using ninja, since ninja is written in python and offers a simple python API.

**Comment by c-cube** [comment]
Looks to me like ninja is written in C++, and is configured in python/provides a python API if needed

**Comment by bluddy** [comment]
> Looks to me like ninja is written in C++, and is configured in python/provides a python API if needed

I thought it was written in python as well. What do you suggest, c-cube? I would really love to start moving (not so much the compiler but more the community) away from depending on Makefiles or anything Unix-specific for building OCaml code. Where is the solution? OCamlbuild can't do it in its current state, and I'm not sure the will is there to get it to where it needs to be. ocp-build seems promising but doesn't seem to be getting much love.

**Comment by damiendoligez** [comment]
I have set this branch for the "experimental" set of jobs in Inria's CI.

**Comment by alainfrisch** [comment]
> It doesn't seem to be updating the GitHub Status API just yet.

Are you sure Appveyor is going to pick this PR which existed before you enabled the service?  Could closing/reopening be necessary?

**Comment by c-cube** [comment]
@bluddy can we discuss this elsewhere? I'm pessimistic on the likelihood that the community settles on a single package manager, but still...

**Comment by whitequark** [comment]
> ocp-build seems promising but doesn't seem to be getting much love.

Ah yes, the undocumented, unmaintained, not-invented-here clone of ocamlbuild that bootstraps for no apparent reason except sheer arrogance and disregard for the needs of its end users. I would rather _invoke ocamlc by hand_ than use ocp-build; not only is it more pleasant but also a more efficient use of time than trying to make those ostensibly responsible for ocp-build to listen to those who are forced to suffer it.

**Comment by whitequark** [comment]
> Unfortunately we have a build gap in OCaml since ocamlbuild didn't try to eliminate the need for Makefiles (the 'last mile' of symlinking the executable and choosing from different targets).

That's not quite the issue. It is trivial to add a few `copy_rule`s and a `world.itarget`, `opt.itarget`, etc, files. However, it doesn't offer a replacement to the `configure` script (or, less importantly, handle installation) and since that requires a full *nix environment, there is little to gain in practice from replacing GNU make with ocamlbuild.

I feel like the discussion is somewhat off the rails. Ocamlbuild would be fine as a buildsystem. Ninja, which has the exact same drawbacks as ocamlbuild in this case, would also be fine; I mildly prefer ocamlbuild but frankly, if I was working on replacing GNU make, I wouldn't care all that much whether it's ocamlbuild or ninja or something else that does basically the same job. The real question is, what generates the configuration (for ocamlbuild) / build rules (for ninja)?

I think the answer is straightforward: OCaml. Just ship the toplevel as `boot/ocaml`. At any rate, rewriting the configure script in Python is just as bothersome as in OCaml, and the latter wins us more.

**Comment by whitequark** [comment]
@alainfrisch I've updated the branch (by changing the date on the last commit) and now Appveyor is building the PR.

**Comment by whitequark** [comment]
It's green.

**Comment by gasche** [comment]
@alainfrisch any remaining objection to merging this?

**Comment by DemiMarie** [comment]
Regarding my suggestion to use Python in the build system: the problem with writing `configure` in OCaml is that one needs `configure` to build `ocamlrun` or any native-code OCaml program, and one needs `ocamlrun` to run any bytecode OCaml program.  This leads to a circular dependency issue in bootstrap.  Writing `configure` in Python avoids this.

**Comment by alainfrisch** [comment]
I'm concerned by the use of ocamlmktop.ml instead of the shell script under Unix.  The behavior is slightly different, since the script would call the ocamlc installed in `%%BINDIR%%` while the ocamlmktop.ml version would call the one found in the current PATH.  This is the same difference as for the "header" prepended to bytecode programs (on Unix, it calls a specific ocamlrun; on Windows, it looks up ocamlrun in the PATH).

What about calling `Filename.concat (Filename.dirname Sys.executable_name) "ocamlc"` (since ocamkmktop is installed in the same directory as ocamlc)?

(Ideally, ocamlmktop would be subsumed by a new command-line flag for ocamlc, but this is another story.)

**Comment by whitequark** [comment]
Fixed.

**Comment by alainfrisch** [comment]
Hmm, I guess one needs to do something to handle the case where the directory name contains whitespaces.  I'm not extremely familiar with the cmd.exe quoting conventions.  Is it enough to always put double quotes around the command name?

**Comment by whitequark** [comment]
I think `Filename.quote` should handle that.

**Comment by whitequark** [comment]
Fixed.

**Comment by gasche** [comment]
Alain, I'll let you merge yourself once you two have converged. Thanks !

**Comment by alainfrisch** [comment]
I've merged a rebased version (I assume this is why github does not show this PR as being merged?).

Thanks to whitequark for this useful effort.

I suggest longer terms discussions about the evolution of the build system to move to somewhere else.

**Comment by lefessan** [comment]
> I suggest longer terms discussions about the evolution of the build system to move to somewhere else.

What a pity ! FWIW, Ninja cannot compile OCaml files. It assumes it can discover dependencies while compiling the files the first time (something that it is true for C/C++, since you can compile your files in whatever order you want), whereas OCaml really needs to compile files in the correct order from the first time. No hope on that side...

**Comment by damiendoligez** [comment]
@drbo before you guys start rewriting `configure` in python, be aware that we are planning to switch to GNU autoconf within the next year.

**Comment by adrien-n** [comment]
Is the list of platforms in README(.adoc) complete?

When moving to autoconf, is the aim to have detection and testing of every library function? Autoconf can test for free() and check that free(NULL) is supported (it isn't on NeXT) but we don't care for NeXT. In other words, will this assume an almost sane OS?

PS: I'm wary of anything that comes from Google (that includes Ninja): only their usecases are supported and getting anything merged is a uphill battle.

**Comment by xavierleroy** [comment]
We (still) don't care for obsolete or exotic platforms such as NextStep or HPUX.  The main reason we're thinking of using autoconf is its very good support for cross-compilation.  As baroque as they are, the feature tests in autoconf embody decades of experience on how to detect features without running compiled code.  There is little point in trying to redevelop this experience independently.

**Comment by adrien-n** [comment]
I quite like autoconf. Wel, not that I like it that much but I believe it works.

A minimal configure.ac file doesn't do much but is often enough if you don't care about old and horrible OSes. At the other end of the spectrum, you get configure.ac files as the ones in some base GNU projects (coreutils, sed, make, ...) which test for hundreds of library functions and are therefore really slow. I was wondering where the target was between these two extremes. Is it going to be "minimal set of configure tests needed to support the same architectures plus cross."? [ that's actually what I'd prefer, if only so that people cannot complain about it being slow ]

**Comment by damiendoligez** [comment]
> Is it going to be "minimal set of configure tests needed to support the same architectures plus cross."?

Looks like a good target, at least for the first version. Then, if autoconf makes it easier to add architectures, we might do that.

**Comment by DemiMarie** [comment]
What about using CMake?  Much better Windows support, faster, should be capable of everything we need, extensible, and allows generating many kinds of IDE project files for those who want to use an IDE to work on the RTS and ocamlyacc.

I think that the OCaml parts should still use a custom build system.  The dependency on the RTS is basically "all OCaml code depends on the RTS, except that only links do if an external `ocamlc`/`ocamlopt` is used".

**Comment by whitequark** [comment]
As the person who implemented CMake rules for the LLVM in-tree OCaml bindings: I use and will keep using CMake for my C++ projects but the degree to which it can provide OCaml support is absolutely _godawful_, by which I mean that it was not only an astounding waste of time to implement, but also it is fundamentally incapable of properly interacting with `ocamldep`. Using CMake for OCaml projects is unambiguously a bad idea.

**Comment by whitequark** [comment]
> I think that the OCaml parts should still use a custom build system.

Sorry, I misunderstood that as "the OCaml parts should use a set of custom CMake rules". It's unlikely to happen seeing as ocamlbuild was branched off, but in that case I would get behind the CMake idea.

**Pull request closed without merging**
