### PR TITLE
Fix typo in coreexamples.etex

### PR DESCRIPTION
**Pull request by robblanco**

### CODE REVIEW

**Comment by gasche** [comment]
@dra27 you had an opinion in a similar discussion. Here the proposed change sounds correct to me, what do you think?

**Comment by dra27** [comment]
Indeed - the change is correct. Thanks!

**Comment by dra27** [comment]
@gasche - FWIW, this could go on 4.04&4.05, though I'm on my phone, so I can't cherry pick right now.

**Comment by damiendoligez** [comment]
Cherry-picked to 4.04 (69621b531aa4261a21715e6a666e18e6e1f86e40) and 4.05 (6f8be23dff29c99ccb11a6757796ba2b9a6ca685).

**Pull request merged**
