### PR TITLE
Remove Const_pointer remnants and fix the fallout

### PR DESCRIPTION
**Pull request by mshinwell**
This pull request should excise the last remnants of Const_pointer from the compiler.  It is a continuation of GPR#1580.

### CODE REVIEW

**Comment by mshinwell** [comment]
I'm not sure what's going on with Travis on this one for the flambda build.  On my machine I get the following test failures, which did not occur on Travis:
```
    tests/tool-ocamldoc/'Module_whitespace.ml' with 1 (ocamldoc) 
    tests/tool-ocamldoc/'No_preamble.mli' with 1 (ocamldoc) 
```
More notably, the `lib-set` tests do not segfault on my box.

**Comment by gasche** [comment]
You are observing an instance of the following issue, https://github.com/ocaml/ocaml/pull/1621#issuecomment-368503568 , due to a stale installation directory (`make install` should fix it). ping @Octachron.

**Comment by mshinwell** [comment]
This patch has been updated to do the following:
1. Remove all remaining references to "const pointer" in the compiler.
2. Fix a serious bug caused by GPR #1580.  (Guilty, for not spotting this earlier.)

The bug relates to instruction selection when mutable Cmm variables are involved.  As the code stood, the types of registers could be promoted from `Int` to `Val` when assignments to such variables were encountered.  Unfortunately when there is a loop, such a promotion can invalidate earlier code generation decisions, in particular those made by the `join` function.  For example, in the following two fragments, the variable `i` doesn't get registered across the call to `gg` because it remains at type `Int`:
```
(* This one is for the first optimised join case *)
let f g h gg (x : int) =
  let r = ref None in
  while true do
    let i =
      if g () < 0 then None
      else !r
    in
    gg ();
    r := Some (h i)
  done

(* This one is for the normal join case *)
let d g h gg (x : int) =
  let r = ref None in
  let rc = Sys.opaque_identity !r in
  while true do
    let i =
      if g () < 0 then rc
      else !r
    in
    gg ();
    r := Some (h i)
  done
```
Perhaps this bug would have been possible to produce even without the removal of "const pointer"; however it's much easier to provoke now, because things such as a mutable variable holding `None` (which previously was a "const pointer") start off at type `Int` rather than at type `Val`.

In the long run, team Flambda has a plan to propose the removal of mutable variables from Cmm (in the same way that we are removing them from Flambda); the equivalent effect would be achieved by a transformation (done just before Flambda, and also during the ref-elimination pass inside Flambda) which passes the values around the control flow graph as required.  One way of solving the present problem would be to effect such a transformation on Cmm code, but this is difficult because of the fact that mutable variables may be live into an exception handler.

After a lot of deliberation and false starts we eventually settled on the current approach which calculates correct types for mutable variables before the main instruction selection algorithm begins.  This necessitates a fixpoint in the presence of recursion, which is why at the same time, we took the liberty of removing the `Cloop` and `Iloop` constructs in favour of recursive "catches".  This provides a notable simplification to the code.  (This work is the same as GPR #1193 except that we haven't provided the optimisation using a map which @chambart did there---for the moment, let's just see if this is fine, which it very likely will be for real use cases.  We do include the fix for `spill.ml` from GPR #1193.)  We now never change the types of registers: as such the `typ` member of `Reg.t` is now immutable.

We experimented with incorporating a similar procedure directly in the main instruction selection algorithm, but it was just too complicated and subtle especially for the fixpoint case.  Having it separately means that there are only two things to think about: identifiers and register types, rather than also incorporating the selection environment and pseudoregisters into the mix.  I don't think the compile-time performance overhead is likely to be significant.

Our code should not degrade performance by e.g. causing loop counters to be registered as roots.  Yet another approach to solving the problem would have been to allow such degradation---except then, we fall into the trap of not knowing which variables are mutable; fixing that would require an unreasonably dirty hack in `Cmmgen`, annotations on every `Clet` (which would become redundant if we do eventually remove Cmm variables) or another pass in any case.

We have tested this on Jane Street's codebase and will continue to do further testing during the 4.07 stabilisation cycle.

**Comment by gasche** [comment]
(cc @xavierleroy)

**Comment by xavierleroy** [comment]
I had a quick look.  That's a serious shortcoming of #1580 indeed; bad enough that I'd suggest reverting #1580 for the 4.07 release, then reconsider.

Computing types in advance by fixpoint computation is a plausible solution, maybe not the only one.  Would be good to have some more time to think about it.

Finally, I don't like the replacement of `Iloop` by more complicated catches, and I don't like the way this change is sneaked in this bug fix.

**Comment by mshinwell** [comment]
I don't think it's fair to say the `Iloop` change was "sneaked in": it's explicitly in the description.  That change was done for what I believe to be sound software engineering reasons.  My view is that it is a mistake to have intermediate language constructs that overlap to the extent that `Iloop` and recursive `Icatch` do (the latter of these was of course introduced only recently).  Doubly so, in this case, because these constructs happen to be the ones where difficult iterative computations are required.  We have already had an example of a bug (the `spill.ml` change mentioned above) where behaviour of an analysis in one of these cases diverged from that in another.  This patch introduces another such iterative computation, which we did not want to duplicate; hence the decision to remove the redundancy.

If we are not going to include this in 4.07 then I would suggest that we revert the "const pointer" changes from 4.07 but aim to merge this (or a new version of this) in trunk in the near future after a consensus is reached.  The experience of @xclerc and myself this week has been that this stuff is rather tricky to think about, so it would be good to discuss and eventually merge whilst we still have it paged in!

**Comment by mshinwell** [comment]
@xavierleroy Ignoring the `Iloop` thing (which is on a separate GPR now) could we please try to reach consensus on this fix?  I was wondering if we could try to remove `Const_pointer` again for 4.08, but we'll need something like this.  We did spend several days thinking about the problem, writing this fix, and testing it carefully---it would be a shame to waste that.

**Comment by alainfrisch** [comment]
If there is reason to keep the 4.08 milestone on this PR?  There are many conflicts, and AFAICT the PR doesn't fix any bug, so I suppose it's perfectly fine to have it in the next version, no?

**Comment by xavierleroy** [comment]
Someone pinged me and @mshinwell about this PR but left no trace here...

Apologies if it was my turn to play and I just forgot.  At any rate, I like the idea of getting rid of `Cconst_pointer`, but I like less the idea of having to do a fixpoint iteration just to get the C-- types right.  If we are to infer types by fixpoint iteration anyway, maybe we don't even need types at the C-- level and could infer them much later.  So, we're back to the drawing table, and this PR as well as #1580 (the one that was reverted) should not be rushed in.

I'm taking the Bug and High-priority labels off, as they no longer apply since #1580 was reverted.

**Comment by mshinwell** [comment]
I was also confused as to how there wasn't a trace of @alainfrisch 's message here.  I'm rather tied up with gdb at the moment, but would like to come back to this after that, to see if we can find any better solutions.

**Comment by alainfrisch** [comment]
(Yes, sorry, I deleted my note shortly after writing it, since I realized a bug was indeed discussed there (and after deleting, I realized the PR that introduced the bug has been reverted).)

**Comment by mshinwell** [comment]
We should now be in a position to think about removing `Const_pointer` without fear of problems, but that can be done on a new PR.

**Pull request closed without merging**
