### PR TITLE
Fix dune build after using Atomic in Stdlib, II

### PR DESCRIPTION
**Pull request by gadmm**
This is a lighter and better solution following @jeremiedimino's explanations at #9662.

(cc @gasche)

### CODE REVIEW

**Comment by gasche** [comment]
I'm not convinced that this is a better approach. It changes a build script, now there are two distinct places of script-blessed module aliases, the overall complexity of the system increased. Moving *all* module aliases to the same place before the stdlib code may be sensible (if it works), but here I'm not convinced.

**Comment by gadmm** [comment]
That would actually work.
The main reason for keeping the others at the end is to be clear about which ones can be used inside `stdlib.ml`. But if you insist I can put them all at the beginning.

**Comment by gadmm** [comment]
Here at the top with comments saying which ones can be used inside `stdlib.ml`, for instance.

**Comment by nojb** [comment]
Sorry if this doesn't work/has been considered already, but wouldn't it be a bit better to just move the `at_exit` stuff (three functions or so) either after the whole list of aliases or just after the `Atomic` alias?

**Comment by gasche** [comment]
> The main reason for keeping the others at the end is to be clear about which ones can be used inside stdlib.ml.

For me the clearest way to clarify that something can be very early in the dependency chain (in particular, that the `Stdlib` implementation can depend on it) is to call it `camlinternalFoo`, which is what the current implementation is doing. I find it more convincing that the approaches proposed here.

Personally I would be happy to stick to camlinternalAtomic and consider the problem solved. I suspect we may be creating more discussion / consensus-building work for ourselves, for something that is not worth it.

**Comment by gadmm** [comment]
We have spent time learning how to do correctly the first approach, which is the one that comes naturally, but which requires knowledge of undocumented bits of the build system. This was encouraged by various people, including you at the top of this discussion. One benefit of setting up a way of depending on non-`Camlinteral*` modules is to record what we have learnt, and avoid that people stumbling across this natural problem in the future spend so much time on it.

**Comment by gasche** [comment]
I propose a simple setup where `Stdlib` only depends on camlinternal modules, and all stdlib-exposed modules can depend on `Stdlib`. This does not restrict expressivity thanks to the ability to use `include`; your code in trunk currently is "living documentation" in your sense.

You want a different setup where we have camlinternal modules, and then two different kind of stdlib-exposed modules, those that may depend on Stdlib and some "exposed internal modules" that Stdlib depends on. You new PR is "living documentation" of that setup. The general model is more complex, but it makes it more convenient to define "exposed internal modules" as one doesn't need to have two modules for them.

I will let other people voice their preference. I prefer the camlinternal approach, but I don't mind us merging the present PR if the exposed-internal approach has more support.

**Comment by gasche** [comment]
But what if we later want to extend `Atomic` in ways that require a dependency on `Stdlib` modules ? (For example we could have some support for atomic lists, and call `List.append` in the implementation.) I think that we would need to use the camlinternal approach then.

**Comment by nojb** [comment]
> But what if we later want to extend `Atomic` in ways that require a dependency on `Stdlib` modules ? (For example we could have some support for atomic lists, and call `List.append` in the implementation.) I think that we would need to use the camlinternal approach then.

I would rather stay with the `camlinternal` approach. Apart from the good reason quoted above, dealing with dependencies is not very pleasant in general with our `Makefiles`, and it feels better to keep things to the absolute simplest.

**Comment by gadmm** [comment]
> But what if we later want to extend `Atomic` in ways that require a dependency on `Stdlib` modules ? (For example we could have some support for atomic lists, and call `List.append` in the implementation.)

This is a good point, the chosen approach depends on the intended scope of the Atomic module. Though I am not sure to understand this example and why it would not better be in a new module for atomic lists. I am assuming that Atomic remains simple.

Likewise, I prefer the approach in this PR, but I do not mind closing it if the camlinternal approach has more support.

**Comment by xavierleroy** [comment]
> For me the clearest way to clarify that something can be very early in the dependency chain (in particular, that the Stdlib implementation can depend on it) is to call it camlinternalFoo, which is what the current implementation is doing.

For the record, that was not the historical motivation for the camlinternalFoo modules.  They were intended for functions that users are not expected to call directly, but that are called by compiled code or by other, exposed parts of the standard library.  The Atomic module being entirely exposed to users, it is strange to have it first hidden as CamlinternalAtomic then re-exposed as Atomic.

**Comment by Octachron** [comment]
What is the final verdict on this alternative approach? If this is only a matter of slight preferences, I would propose to close this issue until another module falls in the same edge case as `Atomic`.

**Comment by gadmm** [comment]
I would prefer not this to be decided by default, given the way the version currently in trunk has been merged, but also I do not think there is more arguing to do. I would prefer to hear clear support for `camlinternalAtomic` if it has to stay.

**Comment by gasche** [comment]
@gadmm brought this PR again. In the end he is not fond of his previous proposal in #9662 and he would prefer to merge this version. Personally I am not convinced it is an improvement, but I don't want to block things if it has support. Could someone say if they prefer the approach proposed in this PR? If there is a clear expression of preference we can go ahead and let @gadmm submit a rebased version.

**Comment by gasche** [comment]
A month later, no one seems to be interested in revisiting this question. I move to close this, but of course it would be perfectly fine to reopen if people change their mind or missed the first summons.

**Pull request closed without merging**
