### PR TITLE
Fix is_nonexpansive for Texp_open

### PR DESCRIPTION
**Pull request by trefis**
Ping @lpw25 .

### CODE REVIEW

**Comment by lpw25** [comment]
Looks good. Merging.

**Comment by gasche** [comment]
What about the suggestion to make the pattern-matching in this function non-fragile?

**Comment by objmagic** [comment]
@trefis Thanks for fixing this bug! sorry i missed it.

@gasche do you mean the `is_nonexpansive` function? and can you clarify what "fragile" here means?

**Comment by gasche** [comment]
Yes, I mean this function. "fragile" is in the sense of warning 4:

>   4 Fragile pattern matching: matching that will remain complete even if additional constructors are added to one of the variant types matched.

Typically a pattern-matching is fragile if it ends with a clause `| _ -> ...`.

**Comment by trefis** [comment]
I wanted to. But when I asked Merlin to do that for me, the pattern it generated was fairly ugly. So I backtracked.

**Pull request merged**
