### PR TITLE
Grouped open and include

### PR DESCRIPTION
**Pull request by Octachron**
This pull request add "grouped" open, local open and include to Ocaml syntax:

``` Ocaml
  module M = struct end 
  module N = struct end

 (* local grouped open *)
  let () = 
    let open M and N in 
    ()
  (* global grouped open *)
  open M and N

    (* grouped include *)
    module M_and_N = struct include M and N end 
```

I see three main advantages to these new constructions:
1. Logically related module can be grouped together
2. The new syntax is quite shorter for locally opening multiple modules
3. The new constructions are a quite natural generalisation of existing Ocaml syntax constructions. An equivalent syntax exists for `let`, `class`, `module rec`and `type` bindings and `with` constraint. Theses constructions should therefore be quite discoverable.

A potential problem with these new constructions is that the "and" operator is only partially commutative: `open M and N` is different to `open N and M` in the presence of identifier shadowing. To lessen this problem for module opening, the name resolution of the to-be-opened modules is done in the original environment. For instance, in

``` Ocaml
module M = struct 
  module N = struct end 
end 
module N=struct end 
open M and N  
```

the opened module N is the toplevel one and not the nested module N.M. Concerning identifier shadowing, the order of modules is respected and in `open M_1,..,M_n` or `include M_1,..,M_n`, the latest binding takes precedence over the others.

### CODE REVIEW

**Comment by alainfrisch** [comment]
This could be a nice way to (partially) address an issue with shadowing warning in case of re-exported definition ( http://caml.inria.fr/mantis/view.php?id=6762 ).  One could indeed decide that in "open M1 and M2", identifiers in M2 shadowing those in M1 don't trigger a warning (this makes sense if we use the feature to open "related" modules).

**Comment by gasche** [comment]
I would like `open M and N` to mark identifiers defined in both modules as ambiguous, and warn if one of them is used in the module (this is more robust than warning at opening time). `open! M and N` could get the uglier ordered semantics. On the other hand, `open!` does other things, and `include!` does not currently exist, so I guess this would bring some complications -- the current ordered choice is simpler.

**Comment by yallop** [comment]
> I would like open M and N to mark identifiers defined in both modules as ambiguous, and warn if one of them is used in the module 

I think we should go even further, and treat this situation as an error, by analogy with `let ... and ...`, which doesn't allow a variable to be bound twice.

**Comment by lpw25** [comment]
> I think we should go even further, and treat this situation as an error, by analogy with let ... and ..., which doesn't allow a variable to be bound twice.

That would certainly be the most consistent behaviour, especially for `include .. and ...`, if you define two things simultaneously then one cannot shadow the other.

**Comment by gasche** [comment]
The problem is that this early failure strategy makes the user at the mercy of the module providers, which may at any point in the future decide to add a new binding to their library and break your code without notice. On the contrary, marking the ambiguous identifiers as ambiguous and only complaining on ambiguous _use_ is much more resilient. It also allows to write `open M and N in let x = M.x in ...` to explicitly disambiguate `x` (exported by both `M` and `N`) to resolve the conflict.

This delayed ambiguity-handling strategy is already what we do with `open` variable shadowing. It is therefore consistent with how `open` scoping work in general and, I think, the better choice.

**Comment by damiendoligez** [comment]
> The problem is that this early failure strategy makes the user at the mercy of the module providers, which may at any point in the future decide to add a new binding to their library and break your code without notice.

But in fact this is true as soon as you use `open`.

**Comment by lpw25** [comment]
> On the contrary, marking the ambiguous identifiers as ambiguous and only complaining on ambiguous use is much more resilient. It also allows to write open M and N in let x = M.x in ... to explicitly disambiguate x (exported by both M and N) to resolve the conflict.

This is possibly true for `open`, although I think I still prefer the early failure approach, but `include` really needs to be an error since it is defining what is part of the module itself.

**Comment by gasche** [comment]
> But in fact this is true as soon as you use `open`.

I think there is a qualitative difference in the kinds of fragility involved. 

> but include really needs to be an error since it is defining what is part of the module itself. 

Agreed. Which helps my point, as this means `open`, `open!` and `include` would be enough to express the range of interesting horizontal-ambiguity behaviors (respectively delayed, eager and eager failure).

**Comment by Octachron** [comment]
First, I should precise that the current commit reuses the standard name shadowing warning for opens.

``` Ocaml
  module M = struct let x = 0 end module N = struct let x=() end 
    open M and N
```

triggers a warning 44 whereas `open! M and N` doesn't. However, the location information of the warning is currently confusing.
I agree that it would be better to have finer grained control over these errors. 

If I try to resume the discussion, we have a 3-level hierarchy of problematic situations:
1. A sequence of separated `open`s shadows a variable. In this situation, the choice of identifier might be unfortunate, but the user has clearly expressed an intended ordering of the modules. 
2. A grouped open `open M and N` introduces multiple definitions of an identifier. In this situation, the user intention is murky at best. However, if the user doesn't use the identifier, there is no real ambiguity.
   By using delayed warning as proposed by @gasche, we are more or less emulating opening modules restricted to the signature actually used. Since, it is (probably?) rare to use all identifiers defined inside a module, this seems to be a sensible default.
3. A grouped include with a collision of identifiers is not only unclear for both the user and the compiler, it can also create problem far away in the code. As suggested by @lpw25, an errors seems to be the way to go here. 

I think that a good way to handle the interactions between 1 and 2 would be to create a separate set of warnings for the use of identifiers multiply defined inside the same grouped open. Since it is a new and more problematic situation than the "vertical shadowing" problem, it could be sensible to make these new warnings default warnings. Concerned users could then promote these specific warnings to errors.
Following this logic, the override flag within `open!` variant could be applied to only ignore vertical shadowing, i.e. to the shadowing of previously defined identifiers. However, in this case, we lose both the possibilities to triggers eagerly warnings on module name collisions and to silence horizontal shadowing warnings.

**Comment by yallop** [comment]
To be clear, I think that only complaining for ambiguous uses is reasonable; it's what Haskell does, and seems to work well enough there.

However, attempting to use a variable bound in both `M` and `N` (in `let open M and N in e`) should be an error, not a warning.  Elsewhere in the language `and` means parallel binding, not sequential binding, and we should keep the same approach here.

**Comment by damiendoligez** [comment]
> However, attempting to use a variable bound in both `M` and `N` (in `let open M and N in e`) should be an error, not a warning. Elsewhere in the language `and` means parallel binding, not sequential binding, and we should keep the same approach here.

I totally agree, and I would add that `open! M and N` should **not** get the sequential semantics. That's just not what `!` means in general.

**Comment by gasche** [comment]
Agreed. In fact I cannot make sense of my last comment about `open` and `open!`. I would propose to always use the parallel semantics, with `open` and `open!` failing on ambiguous use (delayed -- the `!` is irrelevant here), and `include` failing on ambiguous inclusion (that is, eagerly).

**Comment by alainfrisch** [comment]
> should be an error, not a warning. Elsewhere in the language and means parallel binding

More or less.  It is fine if two types introduced in a single `and` declaration define common labels or constructors:

``` ocaml
  type t = A | B and s  = A | C;;
  (A : t);;
  (A : s);;
```

My concern with having a strong error, not a warning, is that it would typically prevent:

``` ocaml
   open Location and Asttypes
```

since these two modules both define `'a loc` (one being a re-export of the other one).  We could try to fix this explicitly by not complaining on re-export, but this doesn't look completely straightforward.

**Comment by damiendoligez** [comment]
Why does `Asttypes` reexport `Location.loc` if the two modules are supposed to be open at the same time?

**Comment by gasche** [comment]
> We could try to fix this explicitly by not complaining on re-export, but this doesn't look completely straightforward.

Just today Benjamin Farinier mentioned this problem in a slightly different setting: he was trying to compose modules by repeated inclusion, and this failed because all those modules exported a common type that was identical in all those modules. Not-failing on ambiguous resolutions (or multiple-definition) when the two candidates are aliases of each other would be very sensible -- but maybe this could be proposed as a separate PR.

**Comment by damiendoligez** [comment]
> Not-failing on ambiguous resolutions (or multiple-definition) when the two candidates are aliases of each other would be very sensible -- but maybe this could be proposed as a separate PR.

I agree: it's a lot more general than this PR.

**Comment by alainfrisch** [comment]
For the warning stuff: http://caml.inria.fr/mantis/view.php?id=6762

But to support inclusion of several modules defining the same type (one re-exported from the other), this seems even more complex, since this affects the module language definition, not just warnings (which don't need to be exactly specified).

**Comment by dbuenzli** [comment]
In general codes bases that are constantly  `open`ing and `include`ing modules are hard to understand. I don't see any value of providing means to encourage that practice. Personally the only `open` I find reasonable are those for namespacing and `include`s are those for defining public and private (but still exposed) interfaces. In both of these uses cases there is no deep need for what is proposed in this PR.

**Comment by Octachron** [comment]
I have added the required errors to enforce the "commutativity" of grouped open and include. 
As discussed, a repeated name error is raised if a name is defined multiple time in `include ... M_k ...`. Similarly, using a variable defined multiple times in grouped open triggers an ambiguous name error.

I agree that the question of alias detection in name collision is interesting but quite orthogonal to this pull request. Concerning the problem of including multiple modules with a shared type, does the module language really need to be modified? For two modules `M` and `N` with a common type t

``` Ocaml
include (M: module type of M with type t := t) and (N:module type of N with type t := t)
```

is syntactically heavy but valid. Could it not be sufficient to add some syntactic sugar or a ppx extension?

@dbuenzli: Thank you for your valuable criticism.
I agree that the overuse of `open` and `include` impedes code readability. However, `open`ing a large list of large modules is already the lightest syntax in many situations. I do not see any encouragements to this practice in my pull request. Contrarily, this pull request reduces (slightly) the relative syntactic cost of local open compared to `open` for multiple modules. It also allows to better organize module `open`s when it is a sensible option. In short, I believe that having an organised way to open a lot of small and self-contained modules – preferentially locally – might improve readability. I could be wrong.

**Comment by Octachron** [comment]
I am closing down this PR due to a low (benefits/complexity) ratio.

**Pull request closed without merging**
