### PR TITLE
toplevel: identify lists by their types

### PR DESCRIPTION
**Pull request by Octachron**
This small PR proposes to identify lists in the toplevel value printer by their types rather than rely on the exact path of the type constructors being printed.

In particular, this fixes the use case reported in the caml-list
```ocaml
# let open List in [1;2];;
```
was printed before this PR as

> - : int list = List.(::) (1, [2])

After this PR, the printer does catch that `[1;2]` is a list and prints

> - : int list = [1; 2]

### CODE REVIEW

**Comment by Octachron** [comment]
It is not necessary: list is the only type which is both a predefined type with specific literals and a data type. All other types with literals are abstracts and cannot be re-exported as a data type, which means that the printer will see them as abbreviation and expand them.

An alternative patch would be to also expand re-exported variant data types, but doing so straightforwardly will lose abbreviated paths for the constructor. 
(In other words, we don't want to print
```
module A_very_precisely_named_module = struct
  type t = Cstr
end
module M = A_very_precisely_named_module;;
M.Cstr;;
```
as
```
- : M.t = A_very_precisely_named_module.Cstr
```
)

**Comment by Drup** [comment]
> It is not necessary: list is the only type which is both a predefined type with specific literals and a data type.

And unit ? Although I don't think it matters for printing.

**Comment by Octachron** [comment]
Unit and bool are arguably using the ordinary prefix constructor syntax (but with non uident constructors).

**Comment by gasche** [comment]
There is something I don't understand here (I know little about the type-checker). In most of the compiler codebase we use `Path.same` to special-case type-specific behavior. (For example, this is what is used to check that a string literal is used as a format string.) Now you are saying that this approach does not work here. But then why does it work elsewhere? Or does it not-work elsewhere and we had never noticed before?

I remark that in other use-cases of `Path.same`, there seems to be some sort of normalization logic applied to the not-known path: the format-checking code calls `expand_head` on the type expression before checking that it is a Tconstr, and `git grep Path.same` shows some use of `Env.normalize_module_path` or (in printtyp) a `normalize` function.

Are those normalization functions not enough to solve the mismatch that is being solved by this PR? If your approach is really necessary, I would like to see a clear explanation (in the code) of when it should be used, and when Path.same is enough.

**Comment by Octachron** [comment]
The equality induced by `Path.same` is indeed too fine to be used on its own without normalization or expansion.

( Briefly, looking at the code that calls `Path.same` there is a similar issue with the code in `Env` which uses `Path.same` to recognize exceptions among unused extension constructors and decides that in
```ocaml
module M: sig end = struct type exn2 = exn = ..  type exn+=Exn type exn2+=Exn2 end
```
`Exn2` is not an exception contrarily to `Exn`.
)

The unique issue in genprintval is that the printing function is doing the expansion on its own (to avoid  unnecessarily prefixing constructor or labels) and takes two interfering decisions: 
First, the sugared form for list should only be used if the current path is equal to `list`.
Second, it is fine to stop if we found a type declaration (even if the type is a re-exporting abbreviation).

Maybe it would be clearer to split `tree_of_val` in two: a `sugared_tree_of_val` that is constructing the tree for builtin sugared form by looking at the fully expanded type and an ordinary `tree_of_val` that does not handle those special cases.

**Comment by gasche** [comment]
Coming back to this PR after a while: I have not done the work of fully understanding @Octachron's answer, and I am not sure I want to. My intuition remains that it should be possible to write the code as `Path.same (some_normalization_function path) Predef.path_list`, and that it would be nicer than special-casing various forms of really-the-same logic in various parts of the codebase. Anyway, this is fixing a small issue, so I would be in favor of merging the current fix: I don't find it intuitive, but it is also clearly correct.

**Review by gasche — APPROVED** [review]
So: good to go after rebasing the PR. (A change entry could help in the Bugfix section, I guess?)

**Comment by lpw25** [comment]
This PR has a bug. It breaks printing for types like:
```ocaml
type 'a foo = 'a option list
```
The code assumes that if `'a foo` is an instance of `'b list` then `'a = 'b`, which is clearly false.

**Comment by gasche** [comment]
Ah, Thanks! And apologies for the problematic merge.

Should we revert the PR and ask @Octachron to come with a fix?

If I understand correctly, the `is_list ty : bool` test should become `as_list ty : tyexpr option`, that returns the `list` type parameter in the matching case. @lpw25, you know the type-checker better than us two; besides the correctness issue, do you have a recommendation on how to write the is-it-a-list logic in the first place?

**Comment by Octachron** [comment]
This is a clear mistake on my part. A revert seems like a sensible option. I also have a fix at #10386, which takes some more care to only try to identify lists by their types in case of a re-export (and with the right logic for identify the type of the list elements).

**Comment by gasche** [comment]
After looking at #10386, I would vote for the revert: it gives us more time to discuss the proper fix without any guilt, and seeing the combined diff instead of the delta would I think be nice to discuss the implementation.

**Comment by Octachron** [comment]
Let's revert then.

**Comment by lpw25** [comment]
I think the correct fix for this issue, is to use this printing for all types that have a `type_kind` of `Type_variant` with two constructors that match the names and arities of the list constructors. Those are the types for which the syntax works, and it avoids any awkwardness around trying to recognise the list type specifically.

Another simple fix that would work is to expand all types which have manifests, even if they are not `Type_abstract`.

**Pull request merged**
