### PR TITLE
ocamltest: do not compare binaries produced by ocamlopt.opt and ocamlopt.byte

### PR DESCRIPTION
**Pull request by nojb**
The mismatch of binaries produced by `ocamlopt.byte` and `ocamlopt.opt` has been a source of failures in `ocamltest` for a while. These failures are not so easy to investigate and take up valuable developer time. Moreover, the consensus is that it is not really a bug if these binaries differ, as there are multiple reasons for this, including sharing of data structures (see #8853) and dependency on the system toolchain (see #9469).

As [suggested](https://github.com/ocaml/ocaml/pull/9469#issuecomment-643742606) by @xavierleroy, this PR disables the comparison of the binaries generated by `ocamlopt.byte` and `ocamlopt.opt` in all cases.

I renamed the `ocamltest` action `compare-native-programs` into `compare-binary-files` instead of removing it altogether, as it is still used by one test (`reproducibility/cmis_on_file_system.ml`).

### CODE REVIEW

**Comment by nojb** [comment]
cc @shindere

**Review by gasche — APPROVED** [review]
I believe the implementation is correct, and it simplifies the source. I will wait for a couple day and merge if there are no more comments.

**Comment by shindere** [comment]
Gabriel Scherer (2020/06/23 05:48 -0700):
> @gasche approved this pull request.

Please give me time to review, I'll comment to let know when done.

**Review by shindere — APPROVED** [review]
LGTM, thanks and sorry about the delay!

**Comment by nojb** [comment]
> LGTM, thanks and sorry about the delay!

Thanks! Do you think this needs a Changes entry?

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2020/06/23 07:51 -0700):
> > LGTM, thanks and sorry about the delay!
>
> Thanks! Do you think this needs a Changes entry?

I kinda wondered and thought we don't need one but no strong opinion on
it.

**Comment by nojb** [comment]
Thanks, merged!

**Pull request merged**
