### PR TITLE
Harden special character support in --prefix and friends

### PR DESCRIPTION
**Pull request by dra27**
Further to https://github.com/ocaml/ocaml/pull/9692#issuecomment-648028910, I made a cup of tea.

autoconf, for good or ill, sets up defaults for things like `--bindir` which contain (make) variables. So when you specify `./configure --prefix=/home/foo/local`, `BINDIR` is actually `${exec_prefix}/bin`, allowing you to do slightly strange things like `make exec_prefix=/home/haha/fooled-you install` (and of course completely break your OCaml installation, but that's another story).

This PR prevents shell special characters from being further interpreted, while leaving that autoconf-mechanism. So `./configure --prefix '/home/$$user/' && make -j world.opt && make user=magic install` now longer tries to install to `/home/magic`, but `make DESTDIR=$HOME install` will (successfully) install to the directory `$HOME/home/\$user`.

Best viewed commit-by-commit, the things of interest:
- The `install` target in `man/Makefile` had no quoting of the install directory, so spaces in a target name would have completely broken it before.
- `OCAML_STDLIB_DIR` is properly escaped as a C string in `runtime/Makefile`
- `ocamlmklibconfig.ml` is now generating rather more like `utils/config.ml` and `ocamltest/ocamltest_config.ml` which allows it to use the existing mechanisms to quote strings
- Travis, like AppVeyor, now installs to a weird path and tests that this works.

cc @shindere

### CODE REVIEW

**Comment by dra27** [comment]
Also [running through precheck](https://ci.inria.fr/ocaml/job/precheck/451/)

**Comment by shindere** [comment]
Hello,

Just wanted to let know that I am working on it.

Will report back ASAP.

**Comment by shindere** [comment]
Since I didn't feel confident enough to review this by myself only, I
asked for advise on the `help-make` GNU mailing-list (no feedback yet)
and also to @sthibaul, who is both a friend and an experienced Debian
maintainer.

@sthibaul confirmed my intuition that this PR takes further from
conforming to GNU standards than where we are now: GNU build systems
indeed seem to prefer simple quotes over double quotes.

In some cases, the behaviour achieved with double quotes is indeed
suitable and it seems not right to "protect" users from it.
`debian/rules` for example does use this behaviour:

`sphinxtrain/debian/rules: dh_auto_configure --
--libexecdir=\$${prefix}/lib`

It is oikely that other distros rely on this behaviour and it would be a
problem to not have it any longer.

**Comment by dra27** [comment]
Thanks for taking so much trouble with this, @shindere! I'm not sure I completely understand your comment with the coding standards - you mean that with GNU coding standards we _should_ prefer single quoted things?

For the behaviour, that use should be expressly still supported. The example you give is from a Makefile fragment, so the command `dh_auto_configure --libexecdir=\${prefix}/lib` will be executed and so `dh_auto_configure` will be called by the shell with the literal string parameter `--libexecdir=${prefix}/lib` and, assuming that gets written to a `Makefile`, **make** will expand `${prefix}` to its final value (e.g. at `make install` time). What this PR stops is `make foo=bar prefix=\$foo` causing libexecdir to be `bar/lib` instead of `$foo/lib` - i.e. you can specify variables at configure-time, but not unexpectedly in the `Makefile`.

**Comment by sthibaul** [comment]
> you mean that with GNU coding standards we should prefer single quoted things?

I think there was a typo there: GNU uses double quotes, not single quotes.

What I meant is: automake currently generates double quotes in all its commands, to allow for such expansion. Making ocaml-specific rules depart from this will probably be surprising for some use cases. I don't see why forbidding them unless a strong case is made: 

> make foo=bar prefix=\$foo causing libexecdir to be bar/lib instead of $foo/lib - i.e. you can specify variables at configure-time, but not unexpectedly in the Makefile.

why forbidding things that do have a technical sense, at the expense of possibly preventing some cases from working?

**Comment by dra27** [comment]
Oh my, time keeps flying - I'm sorry for the delay replying. I'm not sure that we're both on the same page, as it were. At present (with double-quotes) you get expansion of variables by `make` and also a second time by the shell. This PR proposes allowing only `make` to expand variables.

That still allows what I think this is a (very) reasonable use case:

```
./configure --prefix '${XDESTDIR}/usr/local'
make
# Installs to /home/dra27/usr/local
make XDESTDIR=/home/dra27 install
```

but then prohibits what I find to be quite bizarre/dangerous (it does the same thing, as I'm dra27):
```
./configure --prefix '${XDESTDIR}/usr/local'
make
# Also installs to /home/dra27/usr/local
make XDESTDIR='/home/$$USER' install
```

is that second case one you'd expect to be used - i.e. you specify a variable within a variable and expect the _shell_ to expand that inside _make_?

Is it definitely the case that there are uses of these which expect to be able to specify shell variables within make variables both to configure *and* to make?

**Comment by sthibaul** [comment]
Ok, I see, it's indeed more convoluted than what I initially thought.
That being said, this is still departing from what automake generates, and you will always find somebody who happens to use the fact that automake uses "" and not '' (yes, with automake projects `make install DESTDIR='/tmp/$$USER'` will do what you noticed)

**Comment by dra27** [comment]
OK, from that it does sound as though this change shouldn't cause immediate surprise to distro packagers such as your good self, though!

This is an obscure, but not unreasonable, configuration to request in a Windows environment (SQL Server, for example, scopes using `$` in names): `./configure --prefix='//server/app-platform$instance/ocaml`. I can swallow having to explain to a puzzled user that you have to understanding _make_ escaping here and have to write `./configure --prefix='//server/app-platform$$instance/ocaml'` but not acceptable that you have to understand both shell and make escaping and write `./configure --prefix='//server/app-platform\$$instance/ocaml'`. The obscure user who expected to be able to embed variables after `configure` I can cope with having to tell to update their installation process to be less obscure! Basically, the only benefit I can see of having the double-quotes is that it allows you to abuse expansion of variables to include other make variables, which seems like a really high price to pay for making a more reasonable use harder!

**Comment by sthibaul** [comment]
My point is: this is the same with all automake-based projects. If you can convince automake maintainers with your arguments, then that'll fix for all of them, and ocaml can proceed accordingly. But otherwise, changing it in ocaml can bring surprises: while ocaml apparently provides an autostuff interface, it would not really have he same behavior as automake. You can never know what people are doing and the consequences of such subtle escaping changes. Recently we have been hit by such kind of behavior change in make itself: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966241 .

**Comment by dra27** [comment]
OK, the switch to single quotes is just a part of this PR - there are bug fixes in it too. I've split that all off to #9813. My intention is to push for that to be merged and then rebase and reconsider this PR as just a switch to single-quotes. FWIW, I think automake is wrong in this matter.

**Pull request closed without merging**
