### PR TITLE
Ocamldep one file per line

### PR DESCRIPTION
**Pull request by gasche**
I got tired of the noisy diffs introduced by running `ocamldep` in the middle of PRs that require it (adding a new file), etc. This PR implements a one-dependency-per-line option for `ocamldep` output, which should result in much shorter, neater ocamldep diffs.

### CODE REVIEW

**Comment by nojb** [comment]
Do we really need to preserve backwards-compatibility on this one? Can't we simply use the new format everytime?

**Comment by gasche** [comment]
I have no opinion, but the cost of making this an option is extremely small.

**Comment by nojb** [comment]
Technically, yes. But in my opinion usability is harmed by a proliferation of options, especially if there is no clear reason to use the "old" format.

**Comment by shindere** [comment]
It seems a nice idea, thanks!

Will the behaviour also work when the dependencies are computed
by calling ocamlc ?

@gasche: I guess parts of the diffs you are referring to are also due
to the dependencies of the C files. Any idea to normalize them, too?

**Comment by gasche** [comment]
Yes, the behavior is shared between ocamldep and `ocamlc -depend`. This PR does not touch the behavior of `{all,}depend` for C files.

**Comment by gasche** [comment]
@nojb I amended the PR to make the one-dep-per-file behavior non-optional. This will now affect all ocamldep output.

The previous behavior (with a command-line flag) is still available in a local branch [ocamldep-one-file-per-line-option](https://github.com/gasche/ocaml/commits/ocamldep-one-file-per-line-option)

**Comment by samoht** [comment]
Is that used at link time too? If not, you can you also sort the dependencies in lexicographical order to ensure some kind of stability.

**Comment by xclerc** [comment]
(Just to underline that the output mode triggered by
the `-modules` switch is not affected. Hence, build
systems relying on this mode are not affected.)

**Comment by gasche** [comment]
@samoht I don't think we use this output for linking, but I would rather keep the dependency order unchanged for now (it may impact the Make build order in subtler way than I'd like). I will consider adding a sort later if I notice .depend noise caused by spurious changes in this order.

**Review by nojb — APPROVED** [review]
LGTM.

**Pull request merged**
