### PR TITLE
Install cmt[i] for stdlib and compiler-libs

### PR DESCRIPTION
**Pull request by dsheets**
See also [Mantis PR#6691](http://caml.inria.fr/mantis/view.php?id=6691).

### CODE REVIEW

**Comment by dsheets** [comment]
Travis fails on opam clone because opam directory already exists??

**Comment by planar** [comment]
Looks good, but you should also update Makefile.nt.

**Comment by Drup** [comment]
thanks @dsheets !

**Comment by dsheets** [comment]
Updated. I can't test the `Makefile.nt` edition but I'm reasonably certain it does the same thing after careful review.

**Comment by dsheets** [comment]
This doesn't cover ocamlbuild which neither has `-bin-annot` turned on nor installs `.cmt[i]` files (obv.). Personally tracked at dsheets/codoc#37.

Are there other pieces of the distribution that it should include? Cppo references `Ocamlbuild_plugin`.

**Comment by dsheets** [comment]
Also, ocamldoc.

**Comment by gasche** [comment]
What is the status of this patch? @dsheets , do you plan to update it for ocamlbuild and ocamldoc soon, or should we consider merging as it is?

**Comment by dsheets** [comment]
I would like to update it for ocamlbuild and ocamldoc. I don't know when I'll get to that. When does the window close for 4.02.2? I think it can be considered for merging as-is, also, with the rest of the distribution added in 4.03.0.

**Comment by planar** [comment]
> When does the window close for 4.02.2?

Good question. I'm aiming for mid-May, but there's still an uncomfortably large number of open bugs on the [Mantis roadmap](http://caml.inria.fr/mantis/roadmap_page.php).

**Comment by gasche** [comment]
Indeed, sorry for forgetting to close.

**Comment by dsheets** [comment]
It doesn't look like this made it into 4.02.2. :disappointed:

**Comment by damiendoligez** [comment]
> It doesn't look like this made it into 4.02.2. ￼

Sorry about that. Gabriel merged into trunk and closed the Mantis PR, and Mantis is still my main tool for tracking changes when I do a release...

**Pull request closed without merging**
