### PR TITLE
Following #330 (Fix "weak hash of serialised closures" from MPR#5942).

### PR DESCRIPTION
**Pull request by bvaugon**
Fix the Makefile of the lib-marshal-closure test from PR https://github.com/ocaml/ocaml/pull/330.
Add tests using ocamlc without -custom (keeping the -custom version).
Fix BYTECODE_ONLY and NATIVECODE_ONLY modes.

### CODE REVIEW

**Comment by bvaugon** [comment]
So, to continue the PR https://github.com/ocaml/ocaml/pull/330 discussion...

@alainfrisch It seems that even in PIC mode, the contents of the .text and .data segments should be stable (ie. they do not change from one run to the other). The page http://eli.thegreenplace.net/2011/11/03/position-independent-code-pic-in-shared-libraries/ contains some details about that.

However, the problem that you described in PR https://github.com/ocaml/ocaml/pull/330 discussion about the invalid behaviour of multiple execution of write32.native was a bug in my original patch. I fixed it (changing one line) in the second commit of this PR ("Fix code fragment digest..."). I added a non-regression test for that in testsuite/tests/lib-marshal-closure.

This fix consists in running the computation of code fragment digests at starting time. Until now, code fragment digests was **lazily** computed. Since the code is non-mutable, it was not a problem before this patch, but lazily computing the hash of the (mutable) data segment is of course a problem. Does anyone know why digests was lazily computed (maybe to speed up the loading time) and if computing them at starting time may be a problem for somebody?

**Comment by alainfrisch** [comment]
I'm not sure to get it.  When in PIC mode, the code should indeed be stable enough, but how could this be the case for the data section, which contains absolute pointer (to sub-values and code)?  Perhaps the main program is often loaded at the same location in the process memory, but this is certainly not the case for shared libraries / DLLs (i.e. cmxs for what concerns us).

**Comment by bvaugon** [comment]
About the second part of your question, for dynlinked libraries, the digest stored in the code fragment and used to check closure compatibility is the md5 of the contents of the whole dynliked file (see the loadfile function from otherlibs/dynlink/dynlink.ml and caml_register_code_fragment from byterun/meta.c). So dynlink is not a problem either with or without this PR.

**Comment by alainfrisch** [comment]
Ah yes, ok.  The basically the question remains whether one can safely assume that the main program is always going to be loaded at the same address in the memory space.  Is it indeed the case on all supported OS?  Including when extra amount of address space randomization is enabled for safety reason?

**Comment by bvaugon** [comment]
@bobot Currently, the hash is never computed at compile time, but it might be a good idea.

**Comment by xavierleroy** [comment]
@alainfrisch : you should read about "Address Space Layout Randomization", e.g. https://en.wikipedia.org/wiki/Address_space_layout_randomization .  ASLR is not activated by default on the majority of OS that run OCaml, although I'm not sure what happens for MacOS X.

@bobot : yes, it is tempting to use a hash of the executable file as the unique identifier for marshaled code pointers.  I don't think we can reliably store this hash inside the executable itself, but, on demand, we could just open (the C equivalent of) Sys.executable_name and hash it.  Pros: it avoids various problems with what happens at loading time, both in bytecode and native-code.  Cons: it may be a little slower, and irrelevant info such as debug info will influence the hash.

**Comment by alainfrisch** [comment]
> ASLR is not activated by default on the majority of OS that run OCaml, although I'm not sure what happens for MacOS X.

Well, the fact that it can be enabled should make us think twice about the current proposal.  Moreover, there is also the case where the "main program" is actually a .so/.dll (through -custom).

Marshal is inherently unsafe and relies on the programmer following specified rules. The check on digest for closure serialization is only a safety net to catch some errors.  Is it worth taking the risk to exclude valid uses in order to capture some more errors, which should be rather rare?

What about including in the .text section a digest of stuff that goes in the .data section (structured constants and so on)?  One could also compute the hash of all linked object files at link-time and include the digest in the "entry unit".

I'm against trying the compute the hash on the Sys.executable_name.  This would not work again for the case where the "OCaml entry point" is not in the main program, but in a loaded .so/.dll.  And it could also fail if the file is not longer readable or has changed at the time when the digest is computed.

**Comment by alainfrisch** [comment]
I'm thinking of reverting the current changes already merged in trunk, unless someone strongly objects.  I think we should look for another solution to the problem (or just document it) which avoids breaking valid uses or forcing extra computation at startup.

@bvaugon @xavierleroy Can you comment on my proposal to compute a digest of all linked objects/libraries (say, in Asmlink.link/Asmlink.link_shared) and pass this to make_startup/make_shared_startup_file so that it can be store as a piece of data in the startup object?  This removes the need to compute the digest as startup/load time and should be equivalent, semantically, to computing the digest on the executable / dll.

**Comment by alainfrisch** [comment]
Changes reverted in e888e099e26f15c36bf7e398d005b65808718708.  Let's try to find a less risky solution!

**Comment by damiendoligez** [comment]
FTR, ASLR is activated by default on the latest Mac OS X, as well as (I'm pretty sure) some Linux distributions. As it is a security feature I'd be **very** wary of breaking it.

**Comment by mshinwell** [comment]
@bvaugon Would you be able to spend some time on this one?  It's been dormant for nearly 18 months.

**Comment by mshinwell** [comment]
No progress for a very long time.  Please re-open if work is restarted on this issue.

**Pull request closed without merging**
