### PR TITLE
Minor TSan cleanup

### PR DESCRIPTION
**Pull request by ghost**
These two commits:
- add a few missing CFI annotations in TSan-specific code paths saving values on the stack.
- replace an occurrence of "56" in `caml_start_program` with a better computation ~~which also takes the optional frame pointer into account~~.

### CODE REVIEW

**Comment by gasche** [comment]
(I would be happy to approve on behalf of @fabbing or @OlivierNicole.)

**Review by fabbing — CHANGES_REQUESTED** [review]
Thanks @dustanddreams, we missed quite a few of these `CFI_ADJUST`!

We reviewed the PR with @OlivierNicole and apart from a few stylistic changes to match the rest of the file, there is a small slip: we shouldn't use `STACK_RETADDR_OFFSET` in `caml_start_program` because it never pushes frame-pointers (I copied this behaviour from 4.x).

```diff
diff --git a/runtime/amd64.S b/runtime/amd64.S
index 78e2d3e5c8..0d39d6bd17 100644
--- a/runtime/amd64.S
+++ b/runtime/amd64.S
@@ -812,13 +812,12 @@ CFI_STARTPROC
 #if defined(WITH_THREAD_SANITIZER)
     /* We can't use the TSAN_ENTER_FUNCTION macro as it assumes an OCaml stack,
        and we are on a C stack. */
-        pushq   C_ARG_1 /* Save C_ARG_1 before C call */
-        CFI_ADJUST(8)
+        /* Save C_ARG_1 before C call */
+        pushq   C_ARG_1; CFI_ADJUST(8)
         /* Read return address */
-        movq    STACK_RETADDR_OFFSET(%rsp, 8 + CALLEE_SAVE_REGS_SIZE), C_ARG_1
+        movq    (8 + CALLEE_SAVE_REGS_SIZE)(%rsp), C_ARG_1
         C_call  (GCALL(__tsan_func_entry))
-        popq    C_ARG_1
-        CFI_ADJUST(-8)
+        popq    C_ARG_1; CFI_ADJUST(-8)
 #endif
     /* Load Caml_state into r14 (was passed as an argument from C) */
         movq    C_ARG_1, %r14
@@ -895,12 +894,11 @@ LBL(108):
 #if defined(WITH_THREAD_SANITIZER)
     /* We can't use the TSAN_EXIT_FUNCTION macro as it assumes an OCaml stack,
        and we are on a C stack. */
-        pushq   %rax /* Save %rax before C call */
-        CFI_ADJUST(8)
+        /* Save %rax before C call */
+        pushq   %rax; CFI_ADJUST(8)
         movq    $0, C_ARG_1
         C_call  (GCALL(__tsan_func_exit))
-        popq    %rax
-        CFI_ADJUST(-8)
+        popq    %rax; CFI_ADJUST(-8)
 #endif
     /* Restore callee-save registers. */
         POP_CALLEE_SAVE_REGS
@@ -996,13 +994,11 @@ CFI_STARTPROC
         movq    STACK_RETADDR(%rsp), C_ARG_1   /* arg 1: pc of raise */
         leaq    STACK_ARG_1(%rsp), C_ARG_2  /* arg 2: sp at raise */
         movq    Caml_state(exn_handler), C_ARG_3 /* arg 3: sp of handler */
-        pushq   %rax
-        CFI_ADJUST(8)
+        pushq   %rax; CFI_ADJUST(8)
         SWITCH_OCAML_TO_C
         C_call  (GCALL(caml_tsan_exit_on_raise))
         SWITCH_C_TO_OCAML
-        popq    %rax
-        CFI_ADJUST(-8)
+        popq    %rax; CFI_ADJUST(-8)
 #endif
         jmp LBL(caml_raise_exn)
 CFI_ENDPROC
```

**Comment by ghost** [comment]
Thanks, changes applied.

**Comment by gasche** [comment]
I read the code as well, here are a couple minor notes:
- the "take into account the optional frame pointer" part is gone after @fabbing's review (Thanks!)
- the change makes the code more robust to Windows which has different callee-save registers (this may not matter today as Windows+TSan is probably not supported, but it could avoid headaches in the future)

**Review by gasche — APPROVED** [review]
Approved on behalf of @fabbing and @OlivierNicole.

**Comment by ghost** [comment]
>     * the change makes the code more robust to Windows which has different callee-save registers (this may not matter today as Windows+TSan is probably not supported, but it could avoid headaches in the future)

The point of this PR was definitely to avoid headaches in the future.

**Pull request merged**
