### PR TITLE
Turn the Lfunction case of Lambda.lambda in a record

### PR DESCRIPTION
**Pull request by chambart**
This will simplify adding fields to this case, in particular adding extensions annotations.

### CODE REVIEW

**Comment by gasche** [comment]
I'm not sure adding trunk language features in the codebase is a good idea; I'd use a non-inline record for now.

**Comment by alainfrisch** [comment]
Indeed, the standard policy seems to wait at least for version N+1 before using features introduced in version N.  (A recent counterexample is the use of the deprecated attribute in stdlib.)

**Comment by chambart** [comment]
I commited the missing part (closure.ml).
The patch turning it into an inline record is c94ff3947d210ae03ba388581a373cbd9488c0bd the rest is identical in both cases.

**Comment by chambart** [comment]
Is there some opposition to that change ?

**Comment by gasche** [comment]
I just added this to my merge list (complain if you don't like the change!). I will remove c94ff39 (no inline records).

**Comment by chambart** [comment]
Ok thanks for ```::```

**Comment by gasche** [comment]
Merged in trunk. I didn't include the inline-record patch, and I merged the two others (I understand the split make sense in your codebase, but I prefer to make compilable commits for bisecting convenience.) Thanks for the refactoring work!

**Pull request closed without merging**
