### PR TITLE
Add Proc.max_arguments_without_passing_on_stack

### PR DESCRIPTION
**Pull request by mshinwell**
Flambda may add extra parameters to functions.  For example, given a recursive function containing a single free variable, it may turn the free variable into an invariant parameter (with a suitable wrapper function being generated) such that an allocation is eliminated and the closure can be lifted to a symbol.  When it does this it aims to never inhibit tail call optimization.  To ensure this, it needs to know the maximum number of arguments that can be passed with none of them ending up on the stack, since the behaviour of Selectgen appears to be such that any stack-passed argument will inhibit tail calls.  The maximum number of arguments is currently hard-coded to the value for the amd64 backend.  This patch provides proper support for knowing this number.

The number for i386 is rather conservative, but I think it's ok at least for the moment.

@xavierleroy Does this look ok to you?

### CODE REVIEW

**Comment by xavierleroy** [comment]
Yes, that's a good idea.  Just to nitpick, I'd rather call this parameter "max_arguments_for_tailcalls".

For x86-32, the number can be higher for two reasons:
- As long as we are not unboxing floats across function calls (and I don't think we are or will any time soon), we have 6 integer registers to pass parameters.
- There is this awful hack of using global memory locations to pass more parameters without pushing them on stack, and it applies to FP arguments as well.  I'm not sure this hack will survive in a rosy future with multicore support, though.

**Comment by damiendoligez** [comment]
@mshinwell Can you please change the name and merge?

**Comment by mshinwell** [comment]
@damiendoligez I will do so later today.

**Comment by mshinwell** [comment]
I've changed the name.  I've also revised the numbers to assume no passing of unboxed floats across functions using the OCaml calling convention, as per Xavier's comment above.  I will merge shortly.

**Pull request merged**
