### PR TITLE
Remove bashism from testsuite/Makefile

### PR DESCRIPTION
**Pull request by dra27**
See https://github.com/ocaml/ocaml/pull/1380#issuecomment-338227237

cc @gasche

### CODE REVIEW

**Comment by shindere** [comment]
Just wondering: why was it necessary to remove the \r at the end of
lines while reading the ocamltests files, actually?

Naïvely, I would have assumed such a character to be considered a
separator by the shell and thus to be ignored. Am I missing something
here?

If it is not considered a separator by default, would it help to add it
to IFS, just for the loop?

**Comment by dra27** [comment]
@shindere - the IFS default is space, tab and newline. If the file has had \r\n translated to \n automatically, then you're fine but binary mounts on Cygwin don't do that any more, so you get \r at the end of the string and it causes the usual havoc!

However, your suggestion of using IFS is great - I've pushed a new solution which uses printf as a being a portable sledgehammer to get \r and \n reliably and that seems to be working correctly on both CRLF Windows checkouts and Linux.

It turns out my previous solution had fixed dash, but not bash in this tedious game of whack-a-mole. bash's echo command is not XSI-compliant so `echo "\r"` needs to be `echo -e "\r"` which is then not Posix so doesn't work on dash. I'm going to go and fix some Windows XP support now, as that's far less tedious than playing with myriad philosophies about a flaming shell! At least in the long wrong this whole thing gets handled by ocamltest!!

**Comment by gasche** [comment]
I don't understand the details enough to vouch for the correctness of the code, but merging this in trunk seems like a good choice to me. I don't remember whether the issue also affects 4.06, but in any case I would first way to see how things go for trunk before discussing any cherry-picking.

**Review by gasche — APPROVED** [review]
(Approved purely out of faith in the power of David's Carriage Return Benediction.)

**Comment by shindere** [comment]
@gasche: please don't merge yet.

I'd like to make sure I can "fix" CI so that Travais fails on this as it
shoudl have, before we integrate the fix. If that's fine with you?

**Comment by gasche** [comment]
Yes -- notice that I subtly delayed my merge to give you time to react if you wanted to, but didn't ping you to not distract you from other work otherwise :-)

**Comment by shindere** [comment]
I can handle distractions, no worries.

**Comment by dra27** [comment]
This does also affects the testsuite running on the 4.06 branch

**Comment by shindere** [comment]
David Allsopp (2017/10/24 10:20 +0000):
> This does also affects the testsuite running on the 4.06 branch

@dra27: btw, do you plan to change your fix to make use of IFS, or will
you leave the fix as it is?

**Comment by gasche** [comment]
David rebased his PR and the [current patch](https://github.com/ocaml/ocaml/pull/1441.patch) does use IFS.

**Comment by shindere** [comment]
Gabriel Scherer (2017/10/24 11:25 +0000):
> David rebased his PR and the [current
> patch](https://github.com/ocaml/ocaml/pull/1441.patch) does use IFS.

Ah great, sorry I didn't re-check.

Just submitted #1443 to improve error handling while running the new
tests

**Comment by gasche** [comment]
Merged, cherry-picked in 4.06 ( dde5a81bf2c854d89f2f02dd68f6330590ba0348 ).

**Pull request merged**
