### PR TITLE
ocamllex: better support for union of character sets

### LINKED ISSUE #10754: ocamllex: union of character sets
This is one of a few [features that I put in micmatch](https://mjambon.github.io/mjambon2016/micmatch-howto.html#regexp-basics) back in 2004 and were quite useful. I haven't asked about having these features in ocamllex until now, mostly because I hadn't been using ocamllex much until last year.

This first feature request is about allowing regexp definitions like this:

```ocaml
let lower = ['a'-'z']
let upper = ['A'-'Z']
let letter = lower | upper
let not_letter = _ # letter (* currently fails since 'letter' isn't understood as a character set *)
```
It's especially useful with complex sets like `let punct = [ ';' ':' ... ]` that we don't want to copy-paste.

I'm assuming this wouldn't change the semantic of the `|` operator where it's already permitted but maybe I'm missing something.

It looks like the implementation may be as simple as adding a case to the [`as_cset` function in `parser.mly`](https://github.com/ocaml/ocaml/blob/b6aa64e7eed6f0a9eddc4e5d2e3e1be282f5b729/lex/parser.mly#L44-L46) and tests. I'm happy to give it a shot if there's agreement on supporting the feature.

### PR DESCRIPTION
**Pull request by nojb**
Tiny quality of life improvement for `ocamllex`. cc @mjambon 

Fixes #10754

### CODE REVIEW

**Comment by shindere** [comment]
Nice feature!

I find the Changes entry a bit confisuing, though. Isn't it you @nojb
who authored the feature, thanks to information provided by @mjambon?
Sorry if I have been mistaken.

I was also wondering about the wording in the manual: "If both regular
expressions denote character sets". ISn't the `Regular expression`
misleading? To me, precisely the things on both sides of `|` are
identifiers rather than regular expressions, no?

In the test, how aobut giving more descriptive names than `set1` and
`set2`?

**Comment by nojb** [comment]
> I find the Changes entry a bit confisuing, though.

Yes, fixed, thanks.

> To me, precisely the things on both sides of `|` are identifiers rather than regular expressions, no?

No, they can be arbitrary regular expressions in general.

> In the test, how aobut giving more descriptive names than `set1` and `set2`?

Yes, OK.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2022/04/20 13:32 -0700):
> > I find the Changes entry a bit confisuing, though.
>
> Yes, fixed, thanks.

Thanks.

> > To me, precisely the things on both sides of `|` are identifiers rather than regular expressions, no?
>
> No, they can be arbitrary regular expressions in general.

Okay now I think I understand. Sorry.

> > In the test, how aobut giving more descriptive names than `set1` and `set2`?
>
> Yes, OK.

How about renaming `alpha'` to `alphanum` and giving a slightly more
significantname to the test file, e.g. `charset` rather than `cset`?

**Comment by nojb** [comment]
Not enough interest. Closing.

**Comment by mjambon** [comment]
I didn't realize this branch hadn't been merged. What's blocking it? How can I help?

**Comment by xavierleroy** [comment]
I think this small improvement is good to have in ocamllex.  The reason it didn't get interest lately is that we all have more urgent things to work on in preparation for the OCaml 5.0 release.  I'd be happy to reopen this PR, except that it's not possible as the branch was deleted.

**Comment by nojb** [comment]
> I think this small improvement is good to have in ocamllex.

PR reopened and rebased. Thanks!

**Review by Alizter — APPROVED** [review]

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Apart from the Changes entry that seems to wait to be completed, this PR
looks good to me.

**Comment by nojb** [comment]
> Apart from the Changes entry that seems to wait to be completed, this PR looks good to me.

Thanks. I updated Changes and unless someone objects, am planning to mege by end of day.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2022/09/27 08:36 -0700):
> > Apart from the Changes entry that seems to wait to be completed, this PR looks good to me.
>
> Thanks. I updated Changes and unless someone objects, am planning to
> mege by end of day.

Fine with me! Thanks!

**Pull request merged**
