### PR TITLE
Add optional thread name.

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by Octachron** [comment]
I am closing this PR as this looks like a mistake (don't hesitate to reopen it later)

**Comment by toots** [comment]
This is not a mistake. I was waiting to see the CI result to finalize the code.

**Comment by Octachron** [comment]
There is probably a misunderstanding here: the ocaml/ocaml repository is not your CI playground, and only finalized PRs should be submitted to the repository: the draft status indicates that you think that your PR should not be merged before discussing some important design choice. When writing a PR, you should use your own fork of the repository.

**Comment by toots** [comment]
The feature that I was developing is highly dependent on each compilation toolchain and I do not have access to all them nor am I aware of all of those that are required to consider the feature complete.

Do you have any suggestions as to how this could be achieved?

**Comment by lthls** [comment]
I expect that making a PR from your branch to the trunk branch of your fork will trigger the CI in the same way, except that only you will get the corresponding notifications. You might want to first update your trunk branch to sync it with the upstream one.

**Comment by toots** [comment]
> I expect that making a PR from your branch to the trunk branch of your fork will trigger the CI in the same way, except that only you will get the corresponding notifications. You might want to first update your trunk branch to sync it with the upstream one.

I'm afraid this won't be the case. It would be if the CI was defined in the code as a github actions one but the CI here is defined externally. See: https://github.com/toots/ocaml/pull/1

**Comment by toots** [comment]
Hmm my bad, you are correct. Thanks and sorry for the noise!

**Pull request closed without merging**
