### PR TITLE
Attribute scope and placement improvements

### PR DESCRIPTION
**Pull request by ghost**
This patch changes the placement and scope of attributes in types, following [mantis 6612](http://caml.inria.fr/mantis/view.php?id=6612):
- it tries to always put attributes after the syntactic elements they are attached to
- it extends the scope of attributes to be as left-wise as possible, like the `as` keyword
### Record field declaractions

Attributes attached to a record field declaration are placed after the type instead of before the `:`:

``` ocaml
type t = { x : int [@default 42] }
(* instead of: *)
type t = { x [@default 42] : int }
```
### Constructors declarations

Attributes attached to a constructor declaration are placed after the type instead of before the `of`:

``` ocaml
type t = A of int * int [@foo]
(* instead of: *)
type t = A [@foo] of int * int
```

same for polymorphic variants:

``` ocaml
type t = [ `A of int * int [@foo] ]
(* instead of: *)
type t = [ `A [@foo] of int * int ]
```
### Tuples

An attribute after a tuple type applies to the whole tuple and an attribute attached to a single element of the tuple requires parentheses:

``` ocaml
type t = int * int [@foo]
(* instead of: *)
type t = (int * int) [@foo]

type t = int * (int [@foo]) * int
(* instead of: *)
type t = int * int [@foo] * int
```
### Incompatible changes

This table summarize the incompatible changes introduced by the patch:

| code | current interpretation | new interpretation |
| --- | --- | --- |
| { x : int \* int [@x] } | { x : int \* (int [@x]) } | { (x : int \* int) [@x] } |
| { x : int [@x] \* int } | { x : (int [@x]) \* int } | rejected |
| int \* int [@x] | int \* (int [@x]) | (int \* int) [@x] |
| int \* int [@x] \* int | int \* (int [@x]) \* int | rejected |
| int -> int [@x] | int -> (int [@x]) | (int -> int) [@x] |
| int -> int [@x] -> int | int -> (int [@x]) -> int | rejected |

### CODE REVIEW

**Comment by whitequark** [comment]
:+1:

**Comment by alainfrisch** [comment]
The patch introduces 1 shift/reduce conflict in the parser.

**Comment by diml** [comment]
Indeed, it is for this case:

```ocaml
module type S = S with type t = int [@foo]
```

as it can be interpreted as (1):

```ocaml
module type S = S with type t = (int [@foo])
```

or (2):

```ocaml
module type S = (S with type t = int) [@foo]
```

I fixed the conflict so that the version without parentheses is recognized as (2), to be consistent with the other cases.

**Comment by alainfrisch** [comment]
Thanks!  What about:

    module type S = S with type t := int [@foo]

No conflict is reported by ocamlyacc, but it is currently recognized as

    module type S = S with type t := (int [@foo])

At least for uniformity, I guess it should be recognized as:

    module type S = (S with type t := int) [@foo]

which can be achieved by changing also the second production for with_constraint.

**Comment by diml** [comment]
Indeed, I changed that too.

**Comment by alainfrisch** [comment]
Thanks! Committed to trunk (rev 15897) and a modified version committed to 4.02 (rev 15896). Damien will monitor how much code this breaks on OPAM and decide to keep this for 4.02.2 or not.

**Comment by planar** [comment]
`riakc_ppx` contains code like that:
```
  type t =   | String [@key 1] of string [@key 2]
             | Integer [@key 3] of int [@key 4]
             | Bad_int [@key 5] of string [@key 6]
             | Unknown [@key 7] of string [@key 8] [@@deriving protobuf, show]
```
My understanding is that it shouldn't parse with the new rules, but apparently it did and I had to try a hacked version of the compiler to see the breakage.

My tests are 90% done, so it's likely that `riak_ppx` is the only package with this problem.

What should we do?

**Comment by Drup** [comment]
cc @struktured

**Comment by struktured** [comment]
If I understand the changes, this is more a question of how ```ppx_deriving_protobuf``` encodes these attributes, right (@whitequark)? Perhaps it needs to support something like

```OCaml
type t = | String of string [@keys 1,2] | Integer of int [@keys 3,4] ...
```

**Comment by whitequark** [comment]
This would become:
```
type t = | String of (string [@key 2]) [@key 1] | ..
```

There's no need to change ppx_deriving as new and old syntax are isomorphic.

**Comment by diml** [comment]
Also I just noticed that for some reason, while `type t = int[@int]` works correctly on trunk it is not parsed with 4.02. I'll debug this.

**Comment by struktured** [comment]
Ok so should I modify ```riakc_ppx``` to use the new preferred syntax?

**Comment by whitequark** [comment]
I think so, yes.

**Comment by diml** [comment]
A production on core_type got commented when the patch was applied to 4.02, I uncommented it (rev 15934) and it fixed the problem.

@planar, I am now able to compile riakc_ppx with the expected syntax changes. And I checked that `type t =   | String [@key 1] of string [@key 2]` is not accepted by the parser.

**Comment by struktured** [comment]
Updated ```riack_ppx``` master accordingly (struktured/riakc_ppx@b3b4cbf8cd18eb5aa7be4a81cb8dff5432199ee9)

**Comment by planar** [comment]
You can still do what you are doing, but the syntax has changed:
```
type t =   | String of (string [@key 2]) [@key 1]
             | Integer of (int [@key 4]) [@key 3]
```
Granted, it doesn't look as good as before, but apparently this is a rather unusual use-case for attributes.

**Comment by planar** [comment]
The only other package that "breaks" is `prob-cache` because it depends on `riakc_ppx`.
 I move that we keep the change and live with the inconvenience that `riakc_ppx` users will have to use a newer release in order to use it with 4.02.2.

**Comment by struktured** [comment]
I'm 95% sure I'm the only user of ```prob-cache```, so I think the ocaml community will survive just fine.

**Comment by c-cube** [comment]
I don't understand why the old syntax was removed without warning (in particular, attributes on record labels, which is useful in combination with `ppx_deriving`). Also, the tests of `ppx_deriving` broke (a new release was needed). I have some code (not published on opam, because it's not released) that breaks with 4.02.2, a **minor** version, and that is pretty annoying. The old syntax should have been deprecated but supported at least until 4.03.

**Comment by bluddy** [comment]
This is why I think it's good practice to label some language features as beta quality until they've settled down.

**Comment by ghost** [comment]
@c-cube sorry for the inconvenience caused. You can still add attributes on record label/constructor declarations and use them in combination with `ppx_deriving`, only the placement is changed.

There is one advantage in removing the old syntax sooner than later: since ppx is still a young feature there is not too much code using it. If we had waited until 4.03 there might have been a lot more code to update.

**Comment by c-cube** [comment]
Well, that's ok. Indeed I didn't have that many lines to update (thanks to vim registers that was not too painful). An annoying remaining problem is that it's difficult to support 4.02.1 and 4.02.2.

**Comment by whitequark** [comment]
Once .2 comes out there is really no reason to keep .1 around...

**Comment by damiendoligez** [comment]
Still, it would be good to have conditional compilation for this kind of case.

**Comment by IgnoredAmbience** [comment]
Late to find this thread, but a note in the changelog would have been helpful to flag this up.

**Comment by gasche** [comment]
Quite true. @edgemaster , it is still time to send a pull request updating the Changelog for future users encountering the issue (browsing back past Changelog entries can be useful years later to reason about backward-compatibility of code).

**Pull request closed without merging**
