### PR TITLE
s390x: allow builds with llvm/clang

### PR DESCRIPTION
**Pull request by ghost**
In the assembler code, explicit GOT-relative relocations can be written either as `@GOTENT` or `@GOT`, but Clang's integrated assembler only supports the latter.

Changing `@GOTENT` to `@GOT` allows OCaml to be built with Clang on Linux/s390x (3485 tests passed, 75 skipped, 0 failed, 140 not started), and you can guess what the next s390x PR will be.

A build with gcc/binutils is still happy with this, checking e.g. `runtime/s390x.o` with `objdump -dr` shows no difference between the use of `@GOTENT` and `@GOT`.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Seems like a trivial change and I trust your testing. Approved.

**Comment by gasche** [comment]
(I don't see a strong reason to backport this in 5.2. Feel free to complain if you disagree.)

**Comment by dra27** [comment]
I think there is a case for this to be cherry-picked along with #12915, since the TSAN support on s390x from what @dustanddreams says is much better with Clang than GCC at present.

**Comment by dra27** [comment]
@Octachron - I put the TSAN support for s390x and POWER in the 5.2 milestone for discussion but then managed not to be around for that discussion. Is it still OK to view this as extending a new 5.2 feature (TSAN) to remaining architectures, so can I cherry-pick this, #12915 and #12876?

**Comment by Octachron** [comment]
Yes, the backporting of the two other PRs to 5.2 merely slipped by. And it seems fine to me to include this PR as a dependency (this week preferably).

**Pull request merged**
