### PR TITLE
manual: fix build by including the common Makefile

### PR DESCRIPTION
**Pull request by Octachron**
cc @dra27 @shindere .
Hopefully, the last fix on top of  #11301 .

### CODE REVIEW

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Yes of course, obviously correct. thanks!

**Comment by gasche** [comment]
Probably not related to this PR, but I just got a CI failure report after merging #11685 on a manual build failure (probably unrelated to that PR), relevant build log included below:

```
curl -s "https://ocaml.org/img/search.svg" > ../webman/api/search_icon.svg
make[2]: *** [Makefile:57: ../webman/api/search_icon.svg] Error 35
```

**Comment by shindere** [comment]
Oops, should have waited for the CI.

**Comment by shindere** [comment]
I just pushed 7f8d1c63d6fceea8715e3ffbfa3d060ed7af2e3b which I believe
does fix the build of the manual.

**Pull request merged**
