### PR TITLE
Liveness changes / exceptions coming out of allocation points

### PR DESCRIPTION
**Pull request by mshinwell**
This patch teaches the liveness analysis pass that allocation points may raise exceptions.  This is necessary so that an assertion check against the output of the forwards dataflow pass used on the debugging branch can be implemented.

I think at the moment three things may cause an exception to come out of an allocation point:
1. An exception from a finaliser
2. An exception from a signal handler
3. The "out of memory" exception from the GC.

These issues were discussed on caml-devel two years ago.  One conclusion was that the "out of memory" exception should be turned into a fatal error.  I will submit another patch for that.

I think I am in favour of having exceptions from finalisers terminate the program.  At the moment they manifest as asynchronous exceptions, which can cause unusual behaviour.  Quoting an example from @alainfrisch:

```
  try (Hashtbl.find tbl key, true)
  with Not_found ->
     let r = f key in
     Hashtbl.add tbl key r;
     r, false
```

In this piece of code, there is no guarantee that if you are in the exception handler, then the key is in the table.  The allocation of the pair might have triggered a GC, which triggered a finaliser (or signal handler), which threw `Not_found` (even though `Hashtbl.find` had returned a datum).

If it can be agreed that exceptions from finalisers should terminate the program, I can prepare a patch.

The final case of signal handlers, as pointed out by @xavierleroy , is more problematic---for example they are very useful for catching Ctrl+C in interactive applications.  It is for this reason that I think we still need this patch so that the liveness pass doesn't produce erroneous information and then wrong code.

As an example of the trouble this causes at the moment, the program below will cause a segfault (at least without Flambda enabled):

```
let create () =
  let x = ref () in
  Gc.finalise (fun _ -> failwith "exn") x;
  x

let some_of_t t =
  try Some t   (* the exception from the finalizer will come out of here *)
  with Failure _ -> Some t

let () =
  let minor_size = (Gc.get ()).Gc.minor_heap_size in
  for i = 1 to 1000 do
    Gc.minor ();
    ignore (create () : unit ref);
    for i = 1 to minor_size / 2 - 1 do
      ignore (ref ())
    done;
    match some_of_t "some" with
    | Some s -> print_string s
    | None -> assert false
  done
```

The linearized form of that is:

```
camlFoo__some_of_t_1008:
  t/29[%rbx] := R/0[%rax]
  setup trap L101
  A/32[%rbx] := "caml_exn_Failure"
  A/33[%rdi] := [A/31[%rax]]
  if A/33[%rdi] !=s A/32[%rbx] goto L102
  {spilled-t/35[s0]*}
  A/34[%rax] := alloc 16
  [A/34[%rax] + -8] := 1024 (init)
  t/36[%rbx] := spilled-t/35[s0] (reload)   <-------
  [A/34[%rax]] := t/36[%rbx] (init)
  reload retaddr
  return R/0[%rax]
  L102:
  reraise R/0[%rax]
  L101:
  push trap
  ...
```

The line with the arrow shows a register that is claimed to be live, `spilled-t/35` -- but in fact, this register is not available; it was never spilled.

### CODE REVIEW

**Comment by damiendoligez** [comment]
Exceptions from finalisers should probably do the same thing as exceptions escaping from a thread.

Should they be ignored or terminate the program, that is the question.

**Comment by dbuenzli** [comment]
> Should they be ignored or terminate the program, that is the question.

I think there should be some kind of global exception trap to which these exception are given with a context indicating where they occured. Something like `Printexc.set_uncaught_exception_handler`.

**Comment by alainfrisch** [comment]
I'm slightly confused about the debugging-prerequiste tag and the first paragraph of the description.  This is actually about fixing an actual bug (an unsoundness in the liveness analysis which can cause segfaults), right?

Before merging, it would be interesting to assess the performance impact of the change (it it is too large and the reason to keep such "asynchronous exception" is to support Ctrl+C, one might try to find other ways to support Ctrl+C).

**Comment by alainfrisch** [comment]
> I think there should be some kind of global exception trap to which these exception are given with a context indicating where they occured.

Seems to be a good idea.  There remains the more anecdotal question of what to do with exceptions raised by this handler -- should one just call it again in that case, at the risk of going into an infinite loop?

**Comment by mshinwell** [comment]
@alainfrisch It's needed for the debugging branch so we can have an assertion that the new dataflow pass isn't going wrong.  It is an existing bug, though.  I agree that trying to measure the performance impact is probably sensible.

**Comment by mshinwell** [comment]
At the developer's meeting I believe it was agreed that this (just the liveness change) could be merged subject to checking the performance.  I ran some tests on 4.03 and it looks much of a muchness, so I'm going to merge this.  We can consider the issues about finalizers etc separately if we so desire.

**Pull request merged**
