### PR TITLE
testsuite: include an example of each spellcheck-style error message

### PR DESCRIPTION
**Pull request by gasche**
I wanted to experiment with solutions to #11927, and realized that it would be much easier if we had examples of the various "Did you mean ..." spellchecking hints in the testsuite. The present PR just adds an example of each of the spellchecking errors to the testsuite.

### CODE REVIEW

**Comment by Octachron** [comment]
This is a good reference document, but is it really a test?

**Comment by gasche** [comment]
It is a regression test for changes in the message formulation that may improve or degrade existing error messages.

**Comment by gasche** [comment]
(In general it's hard to work on error messages if we don't know what example may raise them, we can't even test them, so I think it is good to have at least one example of each message in the testsuite for future reference.)

**Comment by Octachron** [comment]
Let's agree that having a reference for those messages is useful, even if it is not really a test; and that I can spend some of my time later on in order to decouple tests from reference files.

**Review by Octachron — APPROVED** [review]

**Pull request merged**
