### PR TITLE
Minor cleanup around printing in the compiler (warnings, errors, etc)

### PR DESCRIPTION
**Pull request by v-gb**
If you look at this pull request, look commit by commit.

I was trying to understand/change what gets printed in these `ppf` formatters that get passed around in various places in the compiler. While doing this, I noticed that it's almost only the output of `-dlambda`, `-dcmm` etc, but a couple places also print warnings and fatals errors in there, whereas the rest of the compiler uses respectively `Location.formatter_for_warnings` and `stderr` for that.
So I bring these places in line with the rest of the compiler in the 1st, 3rd and 5th commit.

While working on the 3rd commit, I fixed missing warnings documentation (2nd commit) and stumbled once more on this Clflags.fast variable, whose name made sense 20 years ago when -unsafe was called -fast but not anymore, so I fixed that too (4th commit) (and while doing that renaming, I noticed that -unsafe removes the check for division and modulo by zero, which is not the documented behavior, that 0/0 is "optimized" from sigfpe to ocaml exception with -unsafe, and that this optimization happens through Sys.opaque_identity, but I didn't change these).

### CODE REVIEW

**Comment by gasche** [comment]
All commits look like nice simplifications to me, thanks!

I think that the most controversial one is 3d0299a185c5b1d330d9732274e0024fdde78f8f, which adds a new warning for something that is arguably fairly inconsequential. It's not clear to me that printing a warning here is a good idea; could you maybe trace when it was added? maybe @alainfrisch has opinions as well.

Overall I like the simplifications of the code and you have clearly been very thoughful when working on this, so my vote would go to trust you and merge, even if I'm not fully convinced by the new warning. I'll let others a change to give an opinion as well.

**Comment by v-gb** [comment]
Thanks for the review.
Unsurprisingly, the warning was added by de Rauglaudre in 2002, so people using camlp4 were confused by -unsafe not working. If you use -pp and -unsafe it does seem like a useful warning. Granted, -pp is rarer nowadays, but you use -ppx you're never going to see it anyway, so it's not like there's much downside.

**Review by gasche — APPROVED** [review]
I approve the PR, but will still give a day or two for others to comment if they wish to.

**Comment by alainfrisch** [comment]
I'm also ok with all changes. No strong opinion on  3d0299a.  It feels both a bit useless and harmless to introduce a warning for such use case.  (I would have said the same thing about just dropping the previous pseudo-warning; except that it would have simplified the code instead of "complexifying" it.)

**Comment by damiendoligez** [comment]
FTR, commit 3d0299a resolves one item of [MPR#6080](https://caml.inria.fr/mantis/view.php?id=6080).

**Comment by lpw25** [comment]
I just noticed this now, but isn't the new warning 64 not actually needed? Once upon a time the `-unsafe` option was implemented in the parser and so skipping the parser with a marshalled AST would mean it was ignored. However, it has long since been implemented in the back-end. This means that using a marshalled AST doesn't skip the handling of `unsafe` and so the warning seems completely unnecessary.

**Comment by damiendoligez** [comment]
There are still three occurrences of `Clflags.unsafe` in `parser.mly` so the warning is still useful.

**Comment by damiendoligez** [comment]
x-ref: #8758

**Pull request merged**
