### PR TITLE
Explain how to customize what the INRIA's CI does for custom branches

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shindere** [comment]
Many thanks, @diml!

Let me clarify just a few things.

"INRIA's CI runs the script tools/ci-build": actually, it's Inria CI's
"main" job. And also the precheck job. In addition, we have, at the
moemnt, two other jobs, namely parallel-build that just tests parallel
build and other-configs that tries severay other configs by running
tools/ci-build-other-configs

"For instance, parallel builds are only tested for the main builds.":
IMO, "for the main builds" should be replaced by "for trunk", which
seems more precise to me.

"In order to test parallel builds with a custom branch": perhpas: "In
order to use precheck to test parallel build on a custom branch"?

**Comment by ghost** [comment]
No problem. I made a few changes

**Comment by shindere** [comment]
Jérémie Dimino (2018/02/13 09:57 -0800):
> No problem. I made a few changes

Thanks a lot!

Squashed, rebased and merged into trunk as
1d20e28d987e03d7023ce565d38b02a8167ce63d

**Comment by ghost** [comment]
> Squashed, rebased and merged into trunk as

Thanks!

**Pull request closed without merging**
