### PR TITLE
Add "-g" for runtime system compilation (in part a regression since 4.05)

### PR DESCRIPTION
**Pull request by mshinwell**
There appears to have been a regression since 4.05 in that we're not compiling the native code runtime system with `-g`.  This patch fixes that.

Compiling the runtime system with `-g` is not only useful for debugging tricky failures.  It also appears to be required on ARM 32-bit platforms to correctly produce backtraces in platform debuggers.  (That's how we discovered the regression.)  These platforms require the use of DWARF information for stack unwinding and gcc doesn't seem to generate that information (via CFI directives) unless `-g` is specified.

This patch also enables `-g` for compilation of the bytecode runtime system.  I think this was an oversight some time ago (see MPR#5583).

@shindere : I imagine you will be interested in this change; if I haven't done quite the right thing please just directly push to my branch.  Thanks.

### CODE REVIEW

**Comment by shindere** [comment]
Mark Shinwell (2017/09/15 03:06 -0700):
> There appears to have been a regression since 4.05 in that we're not
> compiling the native code runtime system with `-g`.  This patch fixes
> that.

As far as I can remember, this had been discussed with @xavierleroy and
@damiendoligez and we all three thought it was okay and even better
*not* to use -g, indeed.

> Compiling the runtime system with `-g` is not only useful for
> debugging tricky failures.  It also appears to be required on ARM
> 32-bit platforms to correctly produce backtraces in platform
> debuggers.  (That's how we discovered the regression.)  These
> platforms require the use of DWARF information for stack unwinding and
> gcc doesn't seem to generate that information (via CFI directives)
> unless `-g` is specified.

Wouldn't it be better, then, to enable -g just on those platforms where
it is really required? (I don't mind finding a nice way to do so, if the
principle is approved.)

And by the way: if this is a regression maybe it is not quite a feature
and this can also be merged after today's freeze, meaning there is no
need to rush on that one? (I think we all already have plenty of things
to deal with so if this one can wait a bit perhaps we can leave it for,
say, next week)

> This patch also enables `-g` for compilation of the bytecode runtime
> system.  I think this was an oversight some time ago (see MPR#5583).

Ah indeed.

> @shindere : I imagine you will be interested in this change; if I
> haven't done quite the right thing please just directly push to my
> branch.  Thanks.

From the point of view of the way it's done, this looks good to me --
since you requested a GitHub review, do I have to do something in the
interface to tell GitHub I did my duty?

My only question is, do we really want -g everwhere (mytecode and native
runtime, all the platforms).

@xavierleroy ? @damiendoligez ?

**Comment by mshinwell** [comment]
This is only half a regression, since it wasn't enabled for the bytecode runtime before (although I think that was a mistake).

I am strongly in favour of having this enabled on the runtime system everywhere based on real-world evidence of its usefulness.  It is frustrating to have a failed OCaml program (e.g. from a core dump) and be unable to analyse it properly because the runtime is compiled without -g.  This situation arises with more frequency than you might imagine (I have seen an occurrence within the last week or so, for example).  I think the extra overhead in executable size, these days, is insignificant.

You can go to "files changed" in Github then use the green button in the top-right corner to submit a review.

**Comment by shindere** [comment]
Mark Shinwell (2017/09/15 12:48 +0000):
> This is only half a regression, since it wasn't enabled for the
> bytecode runtime before (although I think that was a mistake).

> 
> I am strongly in favour of having this enabled on the runtime system
> everywhere based on real-world evidence of its usefulness.  It is
> frustrating to have a failed OCaml program (e.g. from a core dump) and
> be unable to analyse it properly because the runtime is compiled
> without -g.  This situation arises with more frequency than you might
> imagine (I have seen an occurrence within the last week or so, for
> example).  I think the extra overhead in executable size, these days,
> is insignificant.

Let's see what Xavier and Damien think about it first.

> You can go to "files changed" in Github then use the green button in
> the top-right corner to submit a review.

Well in braille or with speech-synthesis "green" does not mean much. ;-)

More seriously: the accessibility of GitHub's web interface is, IMO, not
that great so I try to do as little as possible through it and as much
as possible through other means. But I'll see what I can do.

**Comment by damiendoligez** [comment]
> As far as I can remember, this had been discussed with @xavierleroy and
@damiendoligez and we all three thought it was okay and even better
*not* to use -g, indeed.

In all honesty, I don't remember this discussion, although I'm often adding `-g` to the makefile manually in order to debug gc-related stuff.

**Comment by bluddy** [comment]
I thought there was a discussion about it and it was brought up that '-g' can introduce performance penalties.

**Comment by mshinwell** [comment]
For C compilation with typical compilers such as gcc I do not think adding `-g` is going to have any noticeable impact (and probably none at all) on the generated code.  (This is not the case for adding `-g` to an OCaml compilation command line, though.)

**Review by damiendoligez — APPROVED** [review]
Looks good and should be cherry-picked to 4.06.

**Comment by mshinwell** [comment]
Merged to trunk and cherry-picked to 4.06 (bb16e1d27)

**Pull request merged**
