### PR TITLE
Suppress trigraph warnings from macOS assembler (PR#6373)

### PR DESCRIPTION
**Pull request by mshinwell**
Warnings complaining about trigraphs are emitted by clang when it is being used as an assembler on macOS.  This patch fixes that and for good measure applies the same flag for assembly via the "aspp" variable.

Tested on 10.11.6 El Capitan.

### CODE REVIEW

**Comment by shindere** [comment]
Is ignoring these warnings really the right way to go?
Couldn't the code be fixed so that they do not show up?

**Comment by xavierleroy** [comment]
The alternative is not to use `.string` directives with string literals, and instead use `.byte` directives with lists of ASCII codes.  (See `Emitaux.emit_{string,bytes}_directive`.)  The latter is a little slower because assembly files are bigger.  How much slower I don't know.

**Comment by mshinwell** [comment]
@shindere The idea was this for to be a minimal change.  I cannot imagine we want the assembler to ever interpret trigraphs, so disabling the warning seems ok.

**Comment by mshinwell** [comment]
Hmm, actually, this may not be good enough.  I read reports that Clang still interprets trigraphs even if the warning is suppressed, which presumably means that if the trigraph were valid, the assembler will produce the wrong thing.  Maybe we should emit byte sequences instead as @xavierleroy suggests, I will try that.

**Comment by mshinwell** [comment]
Sorry, that last comment was wrong.  I've checked again on the machine.  It seems when passing an assembly file to clang, trigraphs are not interpreted, so indeed the only thing to do is suppress the warning.  The patch appears correct then.

**Comment by mshinwell** [comment]
One other thing: using `.byte` in assembly files is going to be to the detriment of readability for developers, so it would probably be sensible to add comments saying what the strings are in that situation.

**Comment by shindere** [comment]
Mark Shinwell (2017/03/10 03:51 -0800):
> @shindere The idea was this for to be a minimal change.  I cannot
> imagine we want the assembler to ever interpret trigraphs, so
> disabling the warning seems ok.

I am wondering whether there perhaps is a directive to disable trigraphs
on a per-file basis. I couldn't find one, for the moment.
How about the -fno-trigraphs command-line option? Would that be helpful,
here?

**Comment by mshinwell** [comment]
It looks like there has been support added in clang for that recently, actually:

https://reviews.llvm.org/rL224790

**Comment by xavierleroy** [comment]
I think this is good, and was about to merge, but I need to be reassured that the new test actually works.  If a warning gets emitted while assembling, will it show up on stdout and cause the test to fail?

**Comment by xavierleroy** [comment]
Also, but unrelated: on line 984 the use of `if sh ./searchpath clang` looks like something from the past, probably `$ccfamily` should be tested instead.  Not asking you to do it as part of this PR, but making a note out of it.

**Comment by shindere** [comment]
Xavier Leroy (2017/03/26 10:51 -0700):
> Also, but unrelated: on line 984 the use of `if sh ./searchpath clang`
> looks like something from the past, probably `$ccfamily` should be
> tested instead.  Not asking you to do it as part of this PR, but
> making a note out of it.

Will look into this tomorrow, thanks. Why do you mention `$ccfamily`
rather than `$cc` ?

**Comment by xavierleroy** [comment]
> Will look into this tomorrow, thanks. Why do you mention `$ccfamily` rather than `$cc` ?

AFAIK, on Mac OS, `$cc` can be `cc` or even `gcc` and still refer to Clang...

Also, `$ccfamily` is what's used in other places to select GCC-specific or Clang-specific behaviors.

**Comment by shindere** [comment]
Xavier Leroy (2017/03/26 11:12 -0700):
> > Will look into this tomorrow, thanks. Why do you mention `$ccfamily` rather than `$cc` ?
> 
> AFAIK, on Mac OS, `$cc` can be `cc` or even `gcc` and still refer to Clang...
> 
> Also, `$ccfamily` is what's used in other places to select
> GCC-specific or Clang-specific behaviors.

Sure, but it was not clear to me that $ccfamily would always be a
program. I thought it was rather a configure-specific trick a bit in the
same spirit as $ccomptype.

**Comment by shindere** [comment]
Xavier Leroy (2017/03/26 10:51 -0700):
> Also, but unrelated: on line 984 the use of `if sh ./searchpath clang`
> looks like something from the past, probably `$ccfamily` should be
> tested instead.

Looking into this a bit more, I am still unsure it is really $ccfamily
which should be tested, here. It indeed contains both compiler name and
version.

With the work done in PR#1114, it becomes guaranteed that $cc contains
only the name of the compiler and no compiler options at all. Wouldn't
it be better to call searchpath on $cc, then? If that seems okay I will
add a commit to that build-system enhancements PR to do that.

**Comment by xavierleroy** [comment]
@shindere: don't agonize over this point, the current code is not broken (afaik) and no change is required.  I was just and am still slightly surprised at the differences in configure between the `amd64,macosx` case on line 977 and the `amd64,*` case on line 1008.  That's all.

**Comment by mshinwell** [comment]
@xavierleroy You are right, the test does not fail.

Unfortunately the way we call the assembler (e.g. in x86_proc.ml) means that there is no way of passing any flags to it (e.g. `-Werror`).  This seems like a mistake to me, but I'm not entirely sure of the best way of fixing it.  Should there be a new compiler option?  Should we pass the -cclib options?

**Comment by shindere** [comment]
Mark Shinwell (2017/03/27 02:48 -0700):
> @xavierleroy You are right, the test does not fail.
> 
> Unfortunately the way we call the assembler (e.g. in x86_proc.ml)
> means that there is no way of passing any flags to it (e.g.
> `-Werror`).  This seems like a mistake to me, but I'm not entirely
> sure of the best way of fixing it.  Should there be a new compiler
> option?  Should we pass the -cclib options?

Having an "-asopt" similar to "-ccopt" would seem cleaner to me.

**Comment by xavierleroy** [comment]
Concerning the test:
* We can choose not to put it in the test suite on the basis that regressions (on this asm warning business) are unlikely.
* There is probably a way to make a custom compile/run script for this test that looks for compile-time warnings.  I just hope it will be easier with the new test infrastructure.
* If you put the test in the test suite, by all means make it print the string and have the test harness check that: it will detect the unlikely but very damaging case where the assembler actually honors trigraphs!

**Comment by mshinwell** [comment]
Right then, I've changed the test case in order to check that trigraphs are not interpreted, on any platform.

I have also adjusted one of the testsuite's Makefiles so that the presence of a "silent compilation" sentinel file in the directory of tests causes the harness to insist that the output of the compilation/linking step is silent.  This causes the trigraph test to fail if the assembler emits a warning about trigraphs.

OK to merge?

**Comment by shindere** [comment]
Thanks, Mark. Since I am not able to review this PR I hope somebody else
will be able to do so.

**Comment by dra27** [comment]
Looks good to me - merging.

**Comment by shindere** [comment]
CI reports that tests/basic/trigraph.ml fails on MacOS 10.8, 10.9 and 10.10

**Comment by pmetzger** [comment]
I just ran tests on 4.07.1 on MacOS 10.14 with Xcode 10 just prior to updating MacPorts and this error occurred during the test suite execution.

**Comment by shindere** [comment]
Perry E. Metzger (2018/10/04 10:48 -0700):
> I just ran tests on 4.07.1 on MacOS 10.14 with Xcode 10 just prior to
> updating MacPorts and this error occurred during the test suite
> execution.

Is there anything that needs to be fixed, here?
Sorry, I'm confused.

**Comment by pmetzger** [comment]
Yes, it needs to be fixed. As I said, if you run the test suite for 4.07.1 on MacOS, you will get the trigraph warning problem again.

**Pull request merged**
