### PR TITLE
Untypeast

### PR DESCRIPTION
**Pull request by Drup**
This patch improves untypeast by putting it in an open recursion format and moving it to compiler libs, thus allowing uses out of the compiler (and slight customization of the output).

This patch also adds various cases that were not handled in the first version.

Some things will still produce parsetree that can't be printed and re-parsed, but other than that, it seems to hold on pretty well.

I tested with the branch https://github.com/Drup/ocaml/tree/untypeast_bootstrap that runs the typechecker, untype, print the untyped parsetree and then typecheck it again. It bootstraps and can compile (and run !) various applications I found on opam.

I added https://github.com/Drup/ocaml/commit/9e739392e4ed9bff0e5d1cf6ac14349546a8cd9c as it seems safe and is necessary to compile the stdlib with the modified compiler.

### CODE REVIEW

**Comment by gasche** [comment]
If I remember correctly, untypeast used not to handle GADTs correctly. Is that still the case? That's a major problem and I wouldn't advise anyone to use it as long as we don't cover the whole language.

**Comment by Drup** [comment]
Do you have an example of code that is not handled ? 
```ocaml
type 'a t = Int : int t | String : string t
let trois : type a . a t -> a = function
  | Int -> 3
  | String -> "trois"
let () = print_string (trois String)
```
works as expected.

and when bootstraping, bigarray and format compiles fine.

**Comment by trefis** [comment]
2015-01-26 14:51 GMT+00:00 Gabriel Radanne <notifications@github.com>:
>
> Do you have an example of code that is not handled ?

Same question.
I've been using untypeast in merlin for a few weeks and I didn't
notice any problem with GADTs.

**Comment by Drup** [comment]
@gasche (and others): ping ? Can you give more info ?

**Comment by gasche** [comment]
I investigated this afternoon. GADTs were indeed completely broken until dd61fb5e551c924effc0cf95580c92ec92b67725 , a fix in the extension_points branch that was integrated in trunk last August. Sorry for the worry.

**Comment by gasche** [comment]
As I feel guilty for leaving a cliffhanger I also looked at the code; it seems rather reasonable.

**Comment by gasche** [comment]
@Drup : Alain asked whether you could  split the major commit "Untypeast Improvements" to have one innocuous file move, and a second commit to move to open recursion style, to get more a readable diff -- this may be useful when browsing back code history in the future. If you can do that I'll merge the patch.

**Comment by Drup** [comment]
@gasche Done.

**Comment by gasche** [comment]
Merged in trunk, with better commit messages and a Changes entry. Thanks!

**Pull request closed without merging**
