### PR TITLE
MPR#7824

### PR DESCRIPTION
**Pull request by trefis**
Cf. https://caml.inria.fr/mantis/view.php?id=7824

### CODE REVIEW

**Review by garrigue — APPROVED** [review]
Calling `filter_row_fields` here cannot hurt, and it looks correct.

**Comment by trefis** [comment]
Thanks for the review.
Once merged, should this also be cherry-picked on the 4.07 branch?

**Comment by garrigue** [comment]
Indeed. This is all the point of keeping a bug fixing branch.

**Comment by trefis** [comment]
I moved the changelog entry to the 4.07 section, merged and cherry-picked on the 4.07 branch.

**Pull request merged**
