### PR TITLE
Fix bug in GPR#1476

### PR DESCRIPTION
**Pull request by mshinwell**
#1476 contains a bug which causes random segfaults.  The addition of the new code necessitated a root registration for the variable `result`, but this was not done.

The following reviewers are in the doghouse: @damiendoligez @lpw25 and @gasche .

### CODE REVIEW

**Review by gasche — APPROVED** [review]
The fix looks clearly correct to me. Why didn't we catch that? (I dream of a world where we can automate sanity checks of our C code.)

**Comment by gasche** [comment]
Minor thing, given that the GPR itself is recent, you could have just added this GPR number to its change entry (and your name in the credit list, "bugfix by ...") instead of doing your own entry. But the current approach is also fine.

**Comment by mshinwell** [comment]
The funny thing is that we thought the segfaults we were getting when building with trunk were all coming from #1660 ... but in fact there were two sources, this being the other!

**Comment by alainfrisch** [comment]
Oops, sorry about that, and thanks for the fix!

**Review by damiendoligez — APPROVED** [review]
The fix is clearly correct. Well done finding this!

**Pull request merged**
