### PR TITLE
Remove global state for typechecking patterns

### PR DESCRIPTION
**Pull request by ncik-roberts**
This is a follow-on cleanup from https://github.com/ocaml/ocaml/pull/12117, inspired by @garrigue's comment about global state. @lpw25 and @goldfirere reviewed a version of this patch that was merged to Jane Street internally.

This patch replaces global variables managed by `type_pat` with a (mutable) state value that's explicitly passed around. There are a few benefits apart from the obvious "global mutable state is hard to reason about":
  * the checking of or-patterns is a little more straightforward
  * this makes it more obviously correct to remove the unnecessary `module_patterns_restriction` argument from `partial_pred,` exposed in the mli. (And, I do remove it in this PR.) These two things don't interact in an interesting way (module patterns, exhaustivity checking), and the explicit scoping of the `type_pat_state` value makes it obvious that we can just ignore module patterns here.

## Implementation

The previous discipline was something like:
  1. Call `reset_pattern` to reset the global state
  2. Call `type_pat` (which writes into the global state)
  3. Read out the results from the pieces of global state (the global variables `pattern_variables`, `module_variables`, and `pattern_force`)
 
The discipline is now:
  1. Call `create_type_pat_state` to create `tps`, a fresh copy of pattern-checking state
  2. Call `type_pat` on `tps` (which writes into its fields)
  3. Read out the results from the fields of `tps`

I add a test to ensure that `pattern_forces` aren't dropped when checking or-patterns, as a draft of this PR made this mistake.

### CODE REVIEW

**Comment by gasche** [comment]
@t6s would you maybe be able to review this?

**Comment by goldfirere** [comment]
The Jane Street patch is at https://github.com/ocaml-flambda/flambda-backend/pull/1281 if you want to see the conversations that happened during initial review.

**Review by t6s — APPROVED** [review]
The changes make the code simpler and better documented.  Looks good to me.

As a side-product of my reviewing, I have done rebasing the branch to the current trunk,
with some comments added:
https://github.com/ncik-roberts/ocaml/pull/1

**Comment by t6s** [comment]
And, sorry for delaying my review so much.

**Review by gasche — APPROVED** [review]
Approving on behalf of @t6s. This is good to merge once rebased.

**Comment by ncik-roberts** [comment]
Thanks @t6s for rebasing. I've updated this PR with the result of that.

**Comment by gasche** [comment]
Merged, thanks @ncik-roberts for the nice patch and @t6s for the review.

Note: in the future (I'm noticing this as I just merged and I don't think it is important enough for this particular PR to request a change after the fact), I think it would be perfectly legitimate to credit people who reviewed on the internal flambda-backend repository (here Antal and Leo) as long as you consider their review was a substantial contribution (as far as reviews are concerned). (This is common practice in the Linux community where commit message tags are used to track review or testing work over the complex lifetime of each patchset.)

**Comment by ncik-roberts** [comment]
Ah, yes, that was a mistake&mdash;I thought to myself when I first opened this PR that I wanted to credit them as reviewers. Anyway, I agree it doesn't seem worth it to fix this omission in this case, but thanks for mentioning this.

**Pull request merged**
