### PR TITLE
make alldepend

### PR DESCRIPTION
**Pull request by trefis**
This seems to fix the parallel build of world.opt on my machine.

Also, the changes look reasonable.

Ping @gasche (who  ran `make depend` recently)

### CODE REVIEW

**Review by gasche — APPROVED** [review]
I don't think you need to do a PR for just `make {all,}depend`, feel free to just push directly.

**Comment by trefis** [comment]
Ack. Thanks.

**Comment by nojb** [comment]
Is there a good reason to have separate `make depend` and `make dependall` ?

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/12/03 09:19 -0800):
> Is there a good reason to have separate `make depend` and `make
> dependall` ?

As I understand it, at least in the past, `make alldepend` could not be
run before ocamldep had been compiled. Now that ocamlc can compute
dependencies this is no longer an issue but it was. So with
per-directories make depend targets you can e.g. just compute
dependencies for C files. Also it's possible to update the dependencies
only in one directory if they have changed only there. I am not saying
these reasons are good, I think everybody knows my opinion about storing
dependencies and the useless problesm this creates for, IMO, not such a
big gain. :)

**Pull request merged**
