### PR TITLE
Backport a configure change in 4.14

### PR DESCRIPTION
**Pull request by gasche**
I think we should backport #12918 to 4.14, but doing this resulted in a *lot* of churn in the `./configure` file. A quick, uninformed investigation suggests that I want to backport #11294 first, and then backporting #12918 on top of it is easy. I am sending the result of this as a PR against 4.14, so that @dra27 can yell if I did something very bad.

(I backported #11294 wholesale, which includes a tweak to the Github Actions yaml file. We probably don't *need* this in 4.14, but I thought that it would be easier to take the whole thing at one.)

### CODE REVIEW

**Comment by gasche** [comment]
(cc @dra27 or maybe @shindere, @MisterDA : it would be nice if someone who knows about `configure` better than I do checked that nothing nefarious is going on here.)

**Comment by dra27** [comment]
I try to avoid yelling 🙂 I'm puzzled as to the churn - `git cherry-pick -x -m1 b6ecc23` applies cleanly on 4.14 for me? I would avoid backporting #11294.

**Comment by gasche** [comment]
Hm, that must be just me doing something wrong. (.. and that asking through a PR was the right move.) Would you volunteer to push the rebase of #12918 to 4.14?

**Comment by gasche** [comment]
Also: thanks for looking at this!

**Comment by dra27** [comment]
No problem - done in 8cda21723524600df11d83d782482b0422d21dd4.

**Pull request closed without merging**
