### PR TITLE
Guess build machine when possible.

### PR DESCRIPTION
**Pull request by toots**
It is a bit of a niche use-case but I've been hit by it twice recently.

In some situations, the runtime environment used to build the compiler is not the same as the kernel architecture. I have seen two cases of this lately:
* Raspberry pi version 4 ships by default with a 64 bit kernel and 32 bit runtime. Please don't ask me why.
* Docker can run images from an architecture that is not the kernel's architecture, for instance 32 bit arm runtime with a 64 bit kernel. This is a much more likely use-case.

In situations like these, the configure script picks up the architecture from the kernel. This is an issue that comes from the corresponding `AC_CANONICAL_BUILD`.

This PR adds a preliminary check so that, if the caller did not explicitly pass a `--build`, `--host` or `--target` option and we can detect a compiler that is able to export the build machine triplet then we use that value for the build option.

The changes might need some polishing but I wanted to send an early one to see if there was interest in this.

### CODE REVIEW

**Comment by avsm** [comment]
Are you still seeing this problem on trunk, after #12227 was merged?  That only captures one specific aarch64/32 mixed mode case -- so a more general solution is appropriate -- but I'm wondering if it was sufficient to fix the rPi failure.

**Comment by toots** [comment]
> Are you still seeing this problem on trunk, after #12227 was merged? That only captures one specific aarch64/32 mixed mode case -- so a more general solution is appropriate -- but I'm wondering if it was sufficient to fix the rPi failure.

Oh, I see. Sorry I missed this.

Your changes seem to work but they are confusing because the `configure` logs report a 64 bit architecture first then 32 bit:
```
$ ./configure
configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking target system type... aarch64-unknown-linux-gnu
[...]
checking for off_t... yes
checking size of int... 4
checking size of long... 4
checking size of long *... 4
checking size of short... 2
checking size of long long... 8
configure: Target is a 32 bits architecture
```

The compiler appears functional but confusing after build:
```
$ ./runtime/ocamlrun ./ocamlc  -config
[...]
architecture: arm
model: armv8
int_size: 31
word_size: 32
system: linux
[...]
host: aarch64-unknown-linux-gnu
target: aarch64-unknown-linux-gnu
```

There might be more side effects as well from the autoconf tooling as well.

On the contrary, with the changes in this PR, the architecture is guessed right from the beginning:
```
$ ./configure
configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking build system type... arm-unknown-linux-gnueabihf
checking host system type... arm-unknown-linux-gnueabihf
checking target system type... arm-unknown-linux-gnueabihf
```

After build:
```
$ ./runtime/ocamlrun ./ocamlc  -config
[...]
architecture: arm
model: default
int_size: 31
word_size: 32
system: linux_eabihf
[...]
host: arm-unknown-linux-gnueabihf
target: arm-unknown-linux-gnueabihf
```

It seems to me that this approach would lead to a safer way to capture this situation.

BTW, a post-configure summary of the relevant options for the compilation to be displayed before starting the build would also be pretty great!

**Comment by shindere** [comment]
Sorry for the likely naïve question but if configure's heuristics are
not good enough to guess correctly the build and host system types
in your use-case, why isn't it sufficient to pass them explicitly?

I have to say that such a PR feels a bit ad hoc (and frightening)
to me so I'd like to make sure it is an absolute requirement before
departing from the very standard behaviour that we have now.

**Comment by toots** [comment]
> Sorry for the likely naïve question but if configure's heuristics are not good enough to guess correctly the build and host system types in your use-case, why isn't it sufficient to pass them explicitly?

It's always possible. These days most users use `opam` to build the compiler so the changes could be implemented there. 

I started looking at it but it's another can of worm. Actually, `opam var` also guesses the wrong architecture in this situation (it's using `uname` which refers to the kernel architecture).

> I have to say that such a PR feels a bit ad hoc (and frightening) to me so I'd like to make sure it is an absolute requirement before departing from the very standard behaviour that we have now.

I never said I was a fan either!

I'd say a better approach would be to use the machine triplet returned by `OCAML_CC_VENDOR` when this information can be extracted.

This would guarantee that the whole configure setup is consistent with the actual C compiler's architecture that the produced OCaml compiler will use. That would make things safer in this case I believe.

I just pushed that change.

**Comment by toots** [comment]
I submitted a PR for opam: https://github.com/ocaml/opam/pull/5587 I believe that this is a better solution.

**Comment by gasche** [comment]
The opam PR is nice and independent, but I am not sure that it replaces/supersedes the present one: if I understand correctly even after this PR the compiler packages in opam would still need to be changed to pass more accurate information to the configure scripts, and if I was an opam-repository maintainer I am not sure I would want to open this other can of worms: it is more logic in configure calls that are copy-pasted across dozen of separate opam files, and having an explicit override means that opam does not benefit from future improvement to the compiler's own auto-detection logic.

(Also I expect that there are various cases where people would build the compiler sources directly from within Docker without going through opam, for minimalism / because they want a very controlled environment. But I guess that the more common use-case then would be to build a binary package from their distribution.)

If there is a way to also fix this at the level of the compiler's configure script that is acceptable to configure people, I think this would be better than an opam-only solution.

**Comment by avsm** [comment]
I strongly agree that this is better solved in the OCaml compiler configure scripts rather than opam-repository.  There are many, many package managers out there now (of which opam is one) that package OCaml, and it would be better to get one clean solution in our home build scripts.   (This is not to say that the opam PR @toots has opened is wrong -- just that it's orthogonal to this PR).

I've not had a chance to look at the use of `cc -dumpmachine` detail yet, but seems like a good approach.  The main risk factor to consider is how it interacts with all the various cross-compilation mechanisms used.  My hope is that all of those specify their targets explicitly, and would be unaffected by the heuristic proposed here.

**Comment by toots** [comment]
Fine by me! I've launched the configure script with a specific `--host` and the CC check was indeed checking for the triplet-prefixed compiler first, even if `AC_CANONICAL_HOST` is placed after it so it would have picked up the right compiler if it was present. The new triplet code is also supposed to not be executed in this case.

**Comment by dra27** [comment]
I'm quite nervous about this change. The [autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Hosts-and-Cross_002dCompilation.html) clearly states:

> the chain of default is now simply: target defaults to host, host to build, and build to the result of `config.guess`

I'm not sure how thrilled some of the aforementioned packagers of OCaml would be at us tweaking defaults in a very non-standard way (ping @rwmjones for Fedora/RHEL and @glondu for Debian). Specifically, Fedora would normally set `--build` and `--host`, but it's presently disabled (see [`ocaml.spec`](https://src.fedoraproject.org/rpms/ocaml/blob/rawhide/f/ocaml.spec#_217-218)); Debian I think in a quite standard way sets `--host` explicitly under the assumption that `config.guess` will do the right thing for `--build` (see [`rules`](https://salsa.debian.org/ocaml-team/ocaml/-/blob/debian/sid/debian/rules#L57)).

This works in Docker (as done in the base images) because you run everything through `linux32` and so change the personality (then it just works - uname thinks it's an i686). I also see the slightly confused state the compiler ends up in when you run a 32-bit distro on a 64-bit kernel _not_ through linux32, though. However, `config.guess` returns different values here (it detects that the C library is different), so I think the error is in what _we're_ then doing with that default, not that the default is incorrect. I'd like to have a more detailed look at this (especially as I left my Raspberry Pis in the office, and there's a lot of wind and rain between me and them, now!) and then I'll waffle some more.

**Comment by dra27** [comment]
(to be explicit, though: I think that the default behaviour of `configure` in the two cases @toots identifies above should "do the correct thing" and don't at the moment; it's just the means that we're using to achieve that which I'm not sure about)

**Comment by rwmjones** [comment]
The Fedora build uses:
```
+ ./configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --libdir=/usr/lib64/ocaml --enable-flambda --enable-native-compiler --enable-native-toplevel --enable-frame-pointers 'OC_CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' 'OC_LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1  '
```
(see `build.log` from https://koji.fedoraproject.org/koji/buildinfo?buildID=2231320)

We never cross-compile.  We do build in a container (for protection rather than anything else) but AFAIK the kernel arch inside the container is the same as outside.

**Comment by dra27** [comment]
I've had a further look at this today. Updating our `config.guess` file to at least [gnu/config@f56a7140](https://git.savannah.gnu.org/cgit/config.git/commit/?id=f56a7140386d08a531bcfd444d632b28c61a6329) fixes this for Intel (e.g. in `docker run --platform linux/386 debian:bookworm` on a 64-bit host, `config.guess` now correctly returns `i686-pc-linux-gnu` (regardless of whether it's run directly or via `/usr/bin/linux32`).

@toots - with ~~https://github.com/dra27/config/commit/f56a7140386d08a531bcfd444d632b28c61a6329~~ https://github.com/dra27/config/commit/d1b9216fff3f8560077b966a78a1f10d13f89d7f, I'm getting the same kind of behaviour on 32-bit Raspberry Pi OS - i.e. where before it resulted in a 32-bit build, but with `ocamlc -config` reporting the wrong `target` and `host` values of `aarch64-unknown-linux-gnu`, now it correctly reports `armv8l-unknown-linux-gnueabihf`. I've submitted that patch to GNU config, but if you grab `config.guess` from that commit on my fork, does it work for you too?

**Comment by toots** [comment]
@dra27 thanks for the investigation. Do you mean grabbing https://raw.githubusercontent.com/dra27/config/f56a7140386d08a531bcfd444d632b28c61a6329/config.guess, placing it in `build-aux/` and running `./configure` ? 

If so, the wrong architecture is still reported here with the latest ocaml git:
```shell
$ ./configure
configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking target system type... aarch64-unknown-linux-gnu
```

I have tried to re-generate `configure` as well and confirmed I'm on a freshly official raspberry pi 32 bit userland with 64 bit kernel.

**Comment by dra27** [comment]
@toots - apologies, I meant grabbing the file from  https://github.com/dra27/config/commit/d1b9216fff3f8560077b966a78a1f10d13f89d7f and doing exactly as you did!

**Comment by shindere** [comment]
Romain Beauxis (2023/07/20 16:02 -0700):
> @dra27 thanks for the investigation. Do you mean grabbing
> https://raw.githubusercontent.com/dra27/config/f56a7140386d08a531bcfd444d632b28c61a6329/config.guess,
> placing it in `build-aux/` and running `./configure` ?

I think it's what David meant, yes.

> If so, the wrong architecture is still reported here with the latest ocaml git:
> ```shell
> $ ./configure
> configure: Configuring OCaml version 5.2.0+dev0-2023-04-11
> checking build system type... aarch64-unknown-linux-gnu
> checking host system type... aarch64-unknown-linux-gnu
> checking target system type... aarch64-unknown-linux-gnu
> ```
>
> I have tried to re-generate `configure` as well and confirmed I'm on a
> freshly official raspberry pi 32 bit userland with 64 bit kernel.

It is actually not necessary to re-generate `configure` when either
`config.guess` or `config.sub` get updated because `configure` only
calls whatever version of the script is there.

In case that helps, if your aim is only to see which build system would
have been taken as defalut by configure if none had been specified, then
it is enough to run `./build-aux/config.guess` to display just that. The
role of `config.sub` is to canonicalize the user-provided system types,
i.e. values for options --host, --build and --target.

**Comment by toots** [comment]
> Romain Beauxis (2023/07/20 16:02 -0700):
> @dra27 thanks for the investigation. Do you mean grabbing https://raw.githubusercontent.com/dra27/config/f56a7140386d08a531bcfd444d632b28c61a6329/config.guess, placing it in `build-aux/` and running `./configure` ?
> I think it's what David meant, yes.
> If so, the wrong architecture is still reported here with the latest ocaml git: ```shell $ ./configure configure: Configuring OCaml version 5.2.0+dev0-2023-04-11 checking build system type... aarch64-unknown-linux-gnu checking host system type... aarch64-unknown-linux-gnu checking target system type... aarch64-unknown-linux-gnu ``` I have tried to re-generate `configure` as well and confirmed I'm on a freshly official raspberry pi 32 bit userland with 64 bit kernel.
> It is actually not necessary to re-generate `configure` when either `config.guess` or `config.sub` get updated because `configure` only calls whatever version of the script is there. In case that helps, if your aim is only to see which build system would have been taken as defalut by configure if none had been specified, then it is enough to run `./build-aux/config.guess` to display just that. The role of `config.sub` is to canonicalize the user-provided system types, i.e. values for options --host, --build and --target.

Ok thanks. I won't have access to the hardware until mid week next week. I'l report shortly after.

**Comment by dra27** [comment]
@toots - the GNU config maintainer merged a version of my changes to `config.guess`, so trunk should now be working correctly. I'll let you confirm that first before closing this PR. We can obviously revisit this if there turn out to be other "exotic" configs like this which aren't working!

**Comment by toots** [comment]
@dra27 confirmed! Sorry it took me so long to test it:
```shell
checking build system type... armv8l-unknown-linux-gnueabihf
checking host system type... armv8l-unknown-linux-gnueabihf
checking target system type... armv8l-unknown-linux-gnueabihf
```
Should I close this ticket now?

**Pull request closed without merging**
