### PR TITLE
Add extension function for filename, add reverse function for string

### PR DESCRIPTION
**Pull request by fxfactorial**
Missing functions from stdlib that I think are useful enough to add.

Added `String.reverse` and `Filename.extension`

### CODE REVIEW

**Comment by fxfactorial** [comment]
Okay, it looks like its failing because something like:

```
../boot/ocamlrun ../boot/ocamlc -use-prims ../byterun/primitives -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -safe-string -strict-formats `./Compflags nativeint.cmo` -c nativeint.ml
```

1) this is saying `-nostdlib`, which is odd to me since other things in string.ml use the stdlib just fine, aka List and Bytes.
2) related to 1, build error is Error: Unbound module String, but I wasn't even referencing the module String, just other functions defined in the same file.

**Comment by fxfactorial** [comment]
Okay so amazingly learned that `"foo".[i]` syntax doesn't work in string.ml itself, separated out files too. Should build fine now.

**Comment by fxfactorial** [comment]
Hoping to have this quickly accepted and released (minor releases this year anyone?) because also want to open a PR for this, https://github.com/fxfactorial/ocaml/commit/87f6b359ed0303b7ec37dc050efd8d5c01b32c95 

Basically got fed up with all kinds of build system hacks I have to do, and I know others do as well, to get around the compilers only knowing about `.c` extensions, when often times I want to use `.mm`, `.m` and `.cpp`.

**Comment by nojb** [comment]
What's wrong with using `Filename.check_suffix` for your other PR ?

You proposed addition in this PR is so small that you could just inline the definition at the point where it is needed.

I wouldn't hold my breath about getting this merged; the question of how to extend and/or (re)design the `stdlib` has been going on for quite some time without any real agreement.

One thing seems clear though: adding bits and pieces here and there will not lead to a good, well-designed, flexible library.

AFAIK the only `stdlib` additions being considered these days are functions which are absolutely necessary for the compiler or that for technical reasons cannot be defined outside the standard library (e.g. because it requires access to some internal representation, etc.).

**Comment by fxfactorial** [comment]
For the other PR it just lead to cleaner code, otherwise would have to add more lines of `check_suffix`. It led to a reduction in the codebase, something usually desirable.

Its 2016, we are trying to make OCaml more popular and its still a debate whether or not the stdlib should have a `String.reverse` function?

**Comment by alainfrisch** [comment]
> AFAIK the only stdlib additions being considered these days are functions which are absolutely necessary for the compiler or that for technical reasons cannot be defined outside the standard library

The idea that evolutions of the stdlib are driven by the needs of the compiler is rather widespread, but wrong (at least these days).  The compiler has its own "stdlib extension", and there is no reason to bother adding a convenience function to the stdlib (which requires some bootstrapping) only to use it in the compiler.

There has been no progress on defining a policy for evolving the stdlib, but this does not mean that proposals are necessarily rejected.  The Changes files shows that there has been quite a few additions in 4.03 and since then.

Proposals for useful additions are still very much welcome.

**Comment by fxfactorial** [comment]
@alainfrisch I was aware that the stdlib is more for the compiler writers, but its precisely the fact that recent history does show an increased rate of additions to the stdlib. That gave me encouragement for this PR. (Although the second one I propose is very much still wanted independent of this)

**Comment by alainfrisch** [comment]
Concerning this specific PR:
- The two changes are unrelated. Why grouping them in a single PR?
- The implementation for `Filename.extension` is wrong; consider "/my.dir/foo".  Perhaps this is a good argument in favor of including this in the stdlib -- once fixed (a common enough feature that people are likely to implement wrongly).
- It's 2016, but I don't see the need for `String.reverse` (don't remember having ever needed that).  Moreover, it's wrong for "utf8 strings", which tend to become the de-facto standard in OCaml (but we don't want to include a utf8-aware string reversal either).  And as your implementation shows, it's a one-liner.  So, personally, I'm against this one.  As a general comment: when proposal something for inclusion, please at least mention one actual case where this would actually be useful.

**Comment by fxfactorial** [comment]
@alainfrisch 
Single PR was my mistake, should have done separate. 

Will fix extension, thank you I didn't consider that. 

The reverse came up became before I did this implementation of extension I tried a logic where I looped over the string from the right until I hit a ., and on each loop adding the char to a buffer, where at the end I would need to reverse the resultant string. But since I didn't go with that approach I kept it in the PR because I thought it was still useful. I also remember other times using a `ref []` with strings and then needing to do a List.rev when what I wanted would be String.reverse. It comes up often enough I'd say.

And yes, its a one liner, so what's the harm in having it instead of everyone having to rewrite that one liner over and over again. 

Also, I'll make another argument. As the organizer of the OCaml meetup in San Francisco, a big problem I see is that newcomers have to waste time reimplementing these functions before they get any gratification from using OCaml (Where many just give up and move on from the language even when they are genuinely interested in sticking with it). Telling Python, Nodejs, Ruby, Java, etc etc programmers to have to reimplement these functions when they are trying to get a grip with the language is a hinderance to adoption.

**Comment by alainfrisch** [comment]
I'm pretty sure that any code which would need to reverse bytes in a string is rather badly written.  If the need is common, you should be able to point to actual examples in the wild.

The fact that `String.reverse` would destroy strings encoded in multi-byte encodings makes its inclusion dangerous, and thus unlikely.

The stdlib should not encourage bad practices (such as accumulating bytes by string concatenation and then reversing a string) and encourage good ones (support utf 8 strings, or at least be agnostic to the encoding in libraries).

**Comment by alainfrisch** [comment]
> have to waste time reimplementing these functions

I can see this argument working for e.g. String.split, certainly not for String.reverse.

**Comment by fxfactorial** [comment]
Alright, I can't say I understand why if there would be any opposition to something that increases adoption of our favorite language, its almost as if we want it to stay niche, unknown. I wouldn't be surprised if this continued outlook just leads to reason creating a competing standard library, eventually making OCaml itself irrelevant.

If the implementation is wrong then I'm sure someone can step along and help me fix it, but since there is no apparent value here then I'll just close this PR.

**Comment by alainfrisch** [comment]
In case this was not clear enough, I'm rather in favor of Filename.extension (implemented correctly).

As far as I know, there is no built-in function to reverse a string in Javascript nor in Python.  Could you accept the idea that perhaps, perhaps, this is not such a common operation on strings?

**Comment by fxfactorial** [comment]
Yea, you're right, there wasn't one. I'll rebase, remove the reverse.

**Pull request closed without merging**
