### PR TITLE
Fix the dependencies for `.p.cmx` files

### PR DESCRIPTION
**Pull request by ghost**
Fix a regression introduced in #1010.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
This indeed corresponds to the spirit of the pre-#1010 state. Good for merging if CI passes.

**Comment by shindere** [comment]
Great! Thanks a lot for fixing!!

**Comment by ghost** [comment]
No problem

**Comment by shindere** [comment]
Jérémie Dimino (2018/02/12 15:59 +0000):
> No problem

Please, @anybody includng @diml, fel free to merge!
Won't be able to do it myself so let's not wait for me!

**Comment by shindere** [comment]
Jérémie Dimino (2018/02/12 15:59 +0000):
> Merged #1603.

Excellent, thanks.

**Pull request merged**
