### PR TITLE
FreeBSD amd64: emit .note.GNU-stack same as on Linux

### PR DESCRIPTION
**Pull request by kostikbel**
The lack of the annotation causes PT_GNU_STACK requesting executable stack on amd64 FreeBSD.

Another not quite cosmetic  consequence is that not too old GNU ld.bfd complains about lack of the note.  This breaks almost half of the test suite on FreeBSD.

### CODE REVIEW

**Review by nojb — COMMENTED** [review]
Change looks reasonable. @hannesm: as a frequent contributor of FreeBSD-related changes, could you take a look? Thanks!

**Comment by nojb** [comment]
Could you add a Changes entry as well? Thanks!

**Comment by nojb** [comment]
Also @haesbaert

**Comment by kostikbel** [comment]
> Could you add a Changes entry as well? Thanks!

Done.

**Comment by hannesm** [comment]
I think this is fine. Maybe worth to backport to 4.14 branch!? I haven't tested it, and won't be able to test it this month. But I'm sure your CI systems will complain if it is wrong.

**Comment by nojb** [comment]
I tested this on `precheck`, which passed: https://ci.inria.fr/ocaml/job/precheck/970/flambda=false,label=ocaml-freebsd-64

**Review by nojb — APPROVED** [review]
LGTM

cc @Octachron for the questoin of whether to backport this to 4.14.

**Review by ghost — APPROVED** [review]

**Comment by kostikbel** [comment]
Ping?

**Comment by nojb** [comment]
> Ping?

Sorry, I dropped the ball on this one. Will merge once CI passes (took the liberty of fixing some conflicts with `trunk`).

**Pull request merged**
