### PR TITLE
4.03 dropped attrs

### PR DESCRIPTION
**Pull request by let-def**
Same as #498 rebased on 4.03.
I added a few more corrections.

Fix: the github pull request was made against the wrong base. Sorry for the noise.

### CODE REVIEW

**Comment by Drup** [comment]
@def-lkb Arf, I was bound to miss some of them. Thanks!

**Comment by Drup** [comment]
@def-lkb I think it would be best to rebase on https://github.com/ocaml/ocaml/pull/487, just to make sure everything is alright and ease merging. You may have to adjust the tests too ..

**Comment by let-def** [comment]
No time right now. Kthxbye :)

**Comment by alainfrisch** [comment]
Thanks!

Fixed the testsuite, rebased and pushed to 4.03.

**Pull request closed without merging**
