### PR TITLE
fix a minor regression from #10462

### PR DESCRIPTION
**Pull request by gasche**
See https://github.com/ocaml/ocaml/pull/10462#discussion_r802457480

(You should look at the diff of that PR in addition to the diff here to review the current PR.)

This PR is against 4.14, we can also cherry-pick in trunk.

cc @Octachron

### CODE REVIEW

**Comment by sadiqj** [comment]
Good spot @gasche , thank you!

**Comment by sadiqj** [comment]
I presume we're going to need another PR to cherry-pick this against trunk?

**Comment by gasche** [comment]
No need, I can push directly.

(Note: `git cherry-pick -m 1 -x <the merge commit>`.)

**Comment by gasche** [comment]
(cherry-picked in trunk as a108b076e318ec181c7a05b23cbfb0b89add8eaf )

**Pull request merged**
