### PR TITLE
Check arity of %compare primitive

### PR DESCRIPTION
**Pull request by nojb**
See [MPR#7846](https://caml.inria.fr/mantis/view.php?id=7846).

### CODE REVIEW

**Comment by hhugo** [comment]
The problem exists with other primitives as well.
```ocaml
external a : ('a -> 'b) -> 'a = "%apply"
let () = a (fun x -> x)
```

**Comment by nojb** [comment]
Yes, this is known (see e.g https://caml.inria.fr/mantis/view.php?id=7408). Checking the arity of comparison primitives is easy but the general case is more work, and am not sure it is worth it given that it is an undocumented feature not meant for general use.

**Comment by hhugo** [comment]
I gave it a quick shot in #2015

**Comment by nojb** [comment]
Subsumed by #2015.

**Pull request closed without merging**
