### PR TITLE
Flambda: Add [Closure_origin.t] to trace inlined functions (merged)

### PR DESCRIPTION
**Pull request by xclerc**
see https://github.com/ocaml/ocaml/pull/1340.

(I have also re-read the diff after the merge to ensure the merge was correct.)

### CODE REVIEW

**Comment by mshinwell** [comment]
Approving based on approval from #1340 and @xclerc 's review of the merge diff.

**Comment by mshinwell** [comment]
Cherry-picked to 4.07 (`91b14d5e71601e2e9aac5ebd046452526f6deb32`).

**Comment by gasche** [comment]
I believe that this change caused a regression in optimization of long composition sequences, see [MPR#7849](https://caml.inria.fr/mantis/view.php?id=7849).

**Comment by xavierleroy** [comment]
The 4.07 cherry-pick must be reverted ASAP.  (The 4.07.1 release is imminent.)

**Comment by mshinwell** [comment]
@xavierleroy I'm not sure anything needs doing here.  This change was originally introduced because certain patterns of code were failing to compile at all (see #1340).  It was cherry-picked onto 4.07 for that reason and is in the existing 4.07 release.

MPR#7849 is an example of code that should not actually have been optimised in the way it was being optimised prior to this patch.  As such it seems reasonable for there to be an expected regression here.  We have done work, to be presented at some point in the future, which improves the treatment of recursion in conjunction with inlining.  This should optimise examples such as MPR#7849 robustly.

**Comment by xavierleroy** [comment]
I got the timeline wrong and thought it was cherry-picked after 4.07.0 and for 4.07.1, which is not the case.  Sorry about that.  Nonetheless, I'm still puzzled as to why this bug fix degrades performance that much.

**Comment by gasche** [comment]
The reporter was relying on a "magically smart" optimization done by flambda before, I'm not terribly surprised that those are fragile. As far as I'm concerned, I'm satisfied with Leo's explanation here, that he has plans for things to improve again in the future.

(I would guess that identifying closure sites with not just their static source position, but also a fragment of the calling context (say, when the caller is inlined as well), would help get the best of both world, at the cost of course of a compilation time increase.)

**Pull request merged**
