### PR TITLE
Remove unused includes from yacc/defs.h

### PR DESCRIPTION
**Pull request by ksromanov**
SunPRO compiler and linker fail to link `ocamlyacc` with error

```
/opt/bb/bin/cc -m64 -O -D_POSIX_PTHREAD_SEMANTICS -mt  -xcode=pic32 -m64 -xc99 -xtarget=generic   -o ocamlyacc closure.o error.o lalr.o lr0.o main.o mkpar.o output.o reader.o skeleton.o symtab.o verbose.o warshall.o
Undefined			first referenced
 symbol  			    in file
caml_fl_p_make_free_blocks          closure.o
caml_realloc_custom_table           closure.o
caml_fl_p_init_merge                closure.o
caml_fl_p_merge_block               closure.o
caml_fl_p_allocate                  closure.o
caml_realloc_ref_table              closure.o
caml_realloc_ephe_ref_table         closure.o
caml_fl_p_add_blocks                closure.o
```

This is due to deficiency of Sun linker — it needs definitions of all defined functions, even unused ones. So, the fix is to remove unused headers, which include "memory.h". 

I understand, that this problem does not happen on more advanced platforms. However, since the headers are not used anyway, why not to remove them?

### CODE REVIEW

**Comment by dra27** [comment]
I’d like to double-check this in precheck rebased to 4.14 (as it was added in #8621 so half the tests are now missing), but no objection in principle

**Comment by dra27** [comment]
Running through [precheck#800](https://ci.inria.fr/ocaml/job/precheck/800/)

**Comment by dra27** [comment]
It's fine through precheck, but I'm confused as to why this fixes anything? `osdeps.h` includes `misc.h` which includes `config.h`. `osdeps.h` then includes `memory.h` which amongst quite a few other things then includes `mlvalues.h`. It's a reasonable tidying up, but I'm not sure that it changes anything, does it?

If this is a build on trunk, that's referring to a whole series of deleted functions from the 4.x freelist implementation (all the `caml_fl_p_` functions are gone - is the problem here that `closure.o` has been compiled against an older runtime and needs recompiling?

**Comment by ksromanov** [comment]
> It's fine through precheck, but I'm confused as to why this fixes anything? 

This was correct before I added `osdeps.h` back again, since it does not pass Approver. At the moment I need to remove `osdeps.h` for our build on Sun separately.

**Comment by dra27** [comment]
OK - there is still the question of why the Sun compiler is complaining about functions which aren't _anywhere_ in the tree, though?

**Comment by ksromanov** [comment]
> OK - there is still the question of why the Sun compiler is complaining about functions which aren't _anywhere_ in the tree, though?

It is not the question, we should waste our time on. Life is too short to spend it reviving zombie systems. If you are ok with removing two unused includes, please merge. Otherwise I can close this PR.

**Comment by DemiMarie** [comment]
I say merge it :)

**Comment by dra27** [comment]
> > OK - there is still the question of why the Sun compiler is complaining about functions which aren't _anywhere_ in the tree, though?
> 
> It is not the question, we should waste our time on. Life is too short to spend it reviving zombie systems. If you are ok with removing two unused includes, please merge. Otherwise I can close this PR.

Slightly puzzling - I thought you started this because you were reviving a zombie system? 🤷

**Review by dra27 — APPROVED** [review]

**Comment by ksromanov** [comment]
> Slightly puzzling - I thought you started this because you were reviving a zombie system? 🤷

This is my fate, which I do not want burden you with. :-)

Honestly, at first I thought that `osdeps.h` is also included by mistake. However, AppVeyor proved that I was wrong. Nevertheless, since there are unused includes, why not to make a quick PR and clean OCaml code (I love this compiler and this language). Since `osdeps.h` is needed on Windows, I had to add it back, however this PR is still not completely useless.

**Comment by DemiMarie** [comment]
> > Slightly puzzling - I thought you started this because you were reviving a zombie system? shrug
> 
> This is my fate, which I do not want burden you with. :-)
> 
> Honestly, at first I thought that `osdeps.h` is also included by mistake. However, AppVeyor proved that I was wrong. Nevertheless, since there are unused includes, why not to make a quick PR and clean OCaml code (I love this compiler and this language). Since `osdeps.h` is needed on Windows, I had to add it back, however this PR is still not completely useless.

You can include it conditionally on `_WIN32` being defined.

**Comment by shindere** [comment]
Demi Marie Obenour (2022/11/12 10:57 -0800):
> > > Slightly puzzling - I thought you started this because you were reviving a zombie system? shrug
> >
> > This is my fate, which I do not want burden you with. :-)
> >
> > Honestly, at first I thought that `osdeps.h` is also included by mistake. However, AppVeyor proved that I was wrong. Nevertheless, since there are unused includes, why not to make a quick PR and clean OCaml code (I love this compiler and this language). Since `osdeps.h` is needed on Windows, I had to add it back, however this PR is still not completely useless.
>
> You can include it conditionally on `_WIN32` being defined.

Isn't it odd to include an osdep file base on OS-related tests?

Wouldn't it make more sense to modify `osdeps` itself so that the
windows specdific bits are included only when necessary?

To me including osdeps.h should either be needed or not needed at all,
but not needed in some OSes and not others.

**Pull request merged**
