### PR TITLE
Always serialize doubles in little-endian

### PR DESCRIPTION
**Pull request by dra27**
This is an extraction of the changes to `Marshal` from #11149 apropos https://github.com/ocaml/ocaml/pull/11149#issuecomment-1084664866.

Previously, on double-big-endian systems, extern wrote doubles in big-endian format so that they would unmarshall natively. This PR makes the marshalling of OCaml's float more platform-independent, at a slight cost for unmarshalling on big-endian systems.

This PR has been through [precheck#680](https://ci.inria.fr/ocaml/job/precheck/680/) but I was unhappy with the failures so it's running through [precheck#681](https://ci.inria.fr/ocaml/job/precheck/681/) again.

At this stage, no benchmarking of this change has been made. If merged, this change extends reproducible bootstraps to big-endian systems (#11149 only provides reproducible bootstrap on non-double-big-endian systems).

### CODE REVIEW

**Comment by dra27** [comment]
The last major change to extern was in 4.11 as part of releasing the colour blue. In https://github.com/ocaml/ocaml/pull/9353#issuecomment-596525927, @ejgallego, @pascal-cuoq, @bobot, @jvillard, @jberdine and @ngorogiannis were pinged as users interested in the performance of `Marshal`, and I hope they don't mind being pinged again here!

This time, though, the question is only relevant for s390 and only if the marshalling includes heavy use of floats / float arrays - are there some useful benchmarks which can be run?

**Comment by xavierleroy** [comment]
After all these years I still like the idea of marshaling data using the native endianness of the machine that does the marshalling, because most of the time unmarshalling is done by the same machine, and no endianness conversion is needed.

It seems that this idea is too cute for its own good...

At any rate, endianness conversion was a hot issue back in the 1990's, when little-endian platforms (x86, VAX, MIPS, Alpha) and big-endian platforms (M68K, SPARC, MIPS too, POWER, s390x) had comparable market shares.  Nowadays, little-endian dominates, and the lone System Z machines can probably tolerate a bit of overhead.

**Comment by pascal-cuoq** [comment]
In the context of saving/restoring Frama-C/TrustInSoft Analyzer save states, the energy already spent restoring the “maximal sharing” invariant dominates any additional overhead that byte-swapping might incur.

**Comment by dra27** [comment]
Just for the record, in #11149, there was originally https://github.com/ocaml/ocaml/commit/7d49c5714aaea841ac762ddf2c98c996896f54b1 which exposed this change as an opt-in flag in `Marshal` - that version of course doesn't simplify anything.

**Comment by dra27** [comment]
(added to the 5.0.0 milestone just so we remember to make a decision one way or the other)

**Comment by xavierleroy** [comment]
Here is a simple benchmark:
```
let write filename size =
  let oc = open_out_bin filename in
  output_value oc (Array.init size (fun i -> float i));
  close_out oc

let read filename =
  let ic = open_in_bin filename in
  ignore (input_value ic);
  close_in ic

let _ =
  match Sys.argv.(1) with
  | "write" -> write "/tmp/data" (int_of_string Sys.argv.(2))
  | "read" -> read "/tmp/data"
  | _ -> assert false
```

**Comment by xavierleroy** [comment]
On our System-Z machine, with an array of size 50_000_000 :
* if `/tmp/data` is created locally, in big-endian format, reading takes 0.10s user and 0.24s system time
* if `/tmp/data` is created on an x86 machine, in little-endian format, then copied to the System-Z machine, reading takes 0.28s user and 0.24s system time.

So, yes, endianness conversion makes a difference.  Then, it may not matter that much, or endianness conversions could be optimized some more, e.g. to use "byte swap" instructions provided by the processor.

**Comment by dra27** [comment]
Thanks! I see the same performance drop on ours - a quick experiment with `__builtin_bswap64` showed that it narrows the margin a little bit.

**Comment by xavierleroy** [comment]
See #11242 for a small change that should improve performance of byte-swapping.

Amusingly (or not), marshaling uses... big-endian format for custom marshalers, e.g. for big arrays...  That's a poor choice of endianness, and it makes efficient byte-swapping even more important.

**Comment by dra27** [comment]
Your new reverse macros in #11242 are giving me basically the same performance as the temporary, incompatible, and to-hell-with-alignment-concerns `#define Reverse_64(dst,src) *(dst) = __builtin_bswap64(*(src))` 🙂 I already thought that the difference was too small to warrant using `__builtin_bswap64`, etc. as well.

The original version of this had `Marshal.Little_float` as a flag to allow the bootstrap to specify that it didn't want native bootstraps. An alternative might be to add `Marshal.Native_float` - so a program which knows it cares about big-endian performance opts _in_ to the doubles being written that way. And, of course, a further alternative would then be only to do this after someone reports that the slowdown is genuinely causing a problem?

**Comment by xavierleroy** [comment]
I'm removing the 5.0 milestone from this PR because I don't think we need to address this in 5.0, but I do think we need to release 5.0 quickly.  For the time being, I'm fine with bootstraps being reproducible on little-endian machines only.

**Comment by dra27** [comment]
(added to the 5.1 milestone as I think we should either merge it or close it before 5.1 is branched)

**Pull request closed without merging**
