### PR TITLE
codefrag.c: protect the digest by a fragment-local mutex

### PR DESCRIPTION
**Pull request by gasche**
See #11791.

This is approach (2) proposed in
  https://github.com/ocaml/ocaml/issues/11791#issuecomment-1339190326

(conflicts with #11795)

### CODE REVIEW

**Comment by xavierleroy** [comment]
This is better than no lazy hashing at all.  The mutex could be replaced by atomics + a bit of busy wait, see #11304.

**Comment by xavierleroy** [comment]
Meta comment: it's good to discuss designs before submitting PRs that implement them.

**Comment by gasche** [comment]
My understanding of the design discussion in #11791 is that the approach of the current PR is considered acceptable, and we could move to the review-the-details phase.

(If we later find out that taking a lock in the common case (read an already-computed digest) is too expensive for certain workloads, we can of course refine with more subtle usage of atomics as proposed in https://github.com/gasche/ocaml/tree/codefrag-mutex-atomic-status . )

**Review by xavierleroy — APPROVED** [review]
Obviously correct.  I quite like the "double locking" variant of this code, but this will do fine for the time being.   Could you please add a Changes entry and merge?

**Comment by gasche** [comment]
Thanks! I also added a comment to document the potential refinement.

**Pull request merged**
