### PR TITLE
Editing

### PR DESCRIPTION
**Pull request by rleonid**
Clear up infix usage of the extension points in manual.

### CODE REVIEW

**Comment by gasche** [comment]
I don't think your change proposal is correct: in `let%foo`, the extension identifier follows the keyword, it is not followed by it.

The whole paragraph is obscure and could probably be rephrased. I also wonder what examples there are with several keywords (if this is `let rec`, my understanding is that it is always the first keyword that takes the extension suffix).

**Comment by Drup** [comment]
> if this is let rec, my understanding is that it is always the first keyword that takes the extension suffix

This is correct. `let%foo rec ...`.

**Comment by rleonid** [comment]
You're  correct, in my haste I did not read the result that carefully. I think the correct form should be (editing after the colon in the original text and now including @Drup confirmation.):

"...: the first keyword followed by the percent sign and then an extension identifier."

If that's acceptable, I'll edit this commit.

**Comment by gasche** [comment]
Yes, that seems fine, thanks.

**Pull request merged**
