### PR TITLE
Install all include files, and access internals with CAML_INTERNALS

### PR DESCRIPTION
**Pull request by lefessan**
Currently, OCaml only installs some of its include files, and remove some "private" sections from these public headers. This PR changes this behavior by installing _all_ include files, but keeps them private (i.e. they will exactly define the same values as before) unless a macro `CAML_INTERNALS` is defined. The rationale is that specific applications might require more access to the internals of the runtime, but they should be warned of the possibility of incompatible changes by setting this macro.

To have access to internals, all C files within the distribution must also set `CAML_INTERNALS`.

This PR is needed for OCamlPro's memory profiler to work on an unpatched version of OCaml.

### CODE REVIEW

**Comment by lefessan** [comment]
I have personal preference to put such information ("this source relies on the OCaml internals" => `#define CAML_ACCESS_INTERNALS`) into the sources, instead of putting them in the build system, that is meta-layer above the code.

> Could you find a place in the manual to say that there is no compatibility guaranty if this flag is selected. 
> Could you also at the same time add a warning in the documentation that there is no guaranty if someone access a symbol of the runtime through another mean than exported interface (external in C or OCaml).

Where is the source of the documentation ?

**Comment by damiendoligez** [comment]
I agree with Fabrice, it's better to have a `#define` in each file.

I think the name is not quite right. What does this have to do with "access"? It should probably be `CAML_INTERNAL_DEFINITIONS` or even just `CAML_INTERNALS`.

> Where is the source of the documentation ?

Duh? It's in `manual/`. You should probably document this feature somewhere at the end of `manual/manual/cmds/intf-c.etex`.

**Comment by lefessan** [comment]
I have switched to CAML_INTERNALS and updated the manual. Is the short paragraph that I added enough ? Since it is supposed to grant access to the "private" parts of the headers, it was not clear for me that it had to be documented in the "public" manual...

**Comment by lefessan** [comment]
Sounds like there are no other comments, so merging.

**Comment by lefessan** [comment]
@gasche 
How do you see this warning ? `make all` in `testsuite` does not show it on my laptop. So I cannot know if adding `#define CAML_INTERNALS` in that file will fix the problem or not.

By the way, it made me notice that there is still a private section in `caml/intext.h` that should be replaced by `#ifdef CAML_INTERNALS`...

**Comment by gasche** [comment]
The warning shows when I build all tests with "make all", but in the middle of the list of all tests, not in the summary at the end. Otherwise just "cd tests/lib-marshal; make" shows it. But it may depend on your compiler (I have GCC 6.1.1).

So I tested and `#define CAML_INTERNALS` just before `#include <intext.h>` (with an `#undef` after it) silences the warning.

**Comment by gasche** [comment]
@lefessan I'll let you commit this along with the `intext.h` fix you mentioned.

**Comment by lefessan** [comment]
See #737

**Pull request merged**
