### PR TITLE
Add compiler primitives for tag values

### PR DESCRIPTION
**Pull request by nojb**
This PR follows-up #1725.

In that PR, `Obj.set_tag` was deprecated and `Obj.with_tag` was introduced as its replacement. As an optimization, for the case when one wants to allocate a new block and immediately set its tag, a rewriting was implemented at the level of `Lambda` which recognizes `Obj.with_tag n (Obj.repr e)` (where `e` is the allocation of a block and `n` is an integer *literal*) in order to avoid the double allocation. 

This optimization has the downside that `n` must be a literal, so one cannot use the constants defined in `Obj` for tag values.

This PR improves this by defining these tag values as compiler primitives which means that the compiler now can optimize them away.

Concretely, terms such as `Obj.with_tag Obj.object_tag (Obj.repr e)` will now benefit from the optimization of #1725.

cc @stedolan

### CODE REVIEW

**Comment by lthls** [comment]
I'm not very happy with this patch.
My preference would be to move the optimisation from #1725 later in the backend (in Closure and Flambda), where the cmx file loading will have resolved the various `Obj.foo_tag` to integers so the optimisation will apply.

Is it really important for you that this optimisation also applies to bytecode ?

**Comment by nojb** [comment]
> My preference would be to move the optimisation from #1725 later in the backend (in Closure and Flambda), where the cmx file loading will have resolved the various `Obj.foo_tag` to integers so the optimisation will apply.

This is actually what I did in the first version of this patch (which I did not submit): I implemented the optimization in `Clambda` which was enough. But it seemed like this was an overly complicated solution (depending on inter-module inlining) compared to the fact that these constants are actually known and used by the compiler -- they truly are "compile-time constants". Incidentally, I think @gasche was also favourable to exposing more things in `Obj` as compiler primitives.

FWIW I am happy with either approach, but this one seemed simpler overall.

Other opinions welcome!

> Is it really important for you that this optimisation also applies to bytecode ?

Not really.

**Comment by lthls** [comment]
I was thinking about implementing the optimisation in Closure and Flambda because they both have passes that perform similar optimisations already, and can rely on a notion of approximation to know whether the argument is constant or not.
This makes it a lot more reliable than simple rewriting passes like the one currently in `Simplif` and, I assume, the one you wrote for Clambda.
I can try to implement my suggestion if you're interested in what it would look like.

Among the things I don't like with your current approach is that you're only exposing special tags, not regular ones, and you're also exposing things that are not meant to be valid tags to pass to `with_tag` (`final_tag`, `int_tag`, `out_of_heap_tag`, `unaligned_tag`).

**Comment by nojb** [comment]
> I was thinking about implementing the optimisation in Closure and Flambda because they both have passes that perform similar optimisations already, and can rely on a notion of approximation to know whether the argument is constant or not.
> This makes it a lot more reliable than simple rewriting passes like the one currently in `Simplif` and, I assume, the one you wrote for Clambda.
> I can try to implement my suggestion if you're interested in what it would look like.

Sure, go ahead. Having both approaches side-by-side should streamline the discussion.

**Comment by lthls** [comment]
I've got something that kind of works, but I'm not very satisfied with it:
- It does not work on constant blocks, so `Obj.with_tag 1 (Some 0)` will always allocate one block
- There are a few painful points on the Flambda side, which mean I'm not 100% certain that it won't fail to compile in certain cases

I could probably invest more time in this and fix these issues, but even I am starting to doubt that the result will be better.

However, if I remember correctly you only use `with_tag` with `object_tag`. Would it make sense to either restrict your PR to exposing `object_tag`, or introduce a primitive `with_object_tag` ? I think either of these would make your PR simpler.

I also have a commit that makes a proper primitive out of `with_tag` instead of this weird "C function given special meaning by the compiler" that we have now, if you're interested.

**Comment by nojb** [comment]
> However, if I remember correctly you only use `with_tag` with `object_tag`. Would it make sense to either restrict your PR to exposing `object_tag`, or introduce a primitive `with_object_tag` ? I think either of these would make your PR simpler.

Yes, I could do this, but it seems too ad-hoc and specific. My preference would be to expose a well-defined subset of tags which includes `Obj.object_tag`. What about the tags presently defined by this PR, minus the "invalid" tags (`final_tag`, `out_of_heap_tag`, `int_tag` and `unaligned_tag`)?

> I also have a commit that makes a proper primitive out of `with_tag` instead of this weird "C function given special meaning by the compiler" that we have now, if you're interested.

That was also discussed in the context of #1725 and I think would be interesting, but is orthogonal to the issue addressed by this PR.

**Comment by lpw25** [comment]
How about having `with_foo_tag` for all the tags you propose? And maybe restricting `with_tag` to only work at all for the ordinary tag values? That doesn't seem ad-hoc, and it avoids having a weirdly specific optimisation to maintain.

**Comment by nojb** [comment]
@lpw25 I'd rather not add more functions to `Obj`... What about moving the existing optimization later in the pipeline, as @lthls mentioned? That would be fine by me as well.

**Comment by lthls** [comment]
I believe the optimisation can't be done in Flambda directly (the current code is not adapted for generating new code during simplification, and the constant lifting pass doesn't handle well things that are only constants if their arguments have a given shape).
However, it can be done while exiting Flambda (in un_anf) or at the Clambda level if needed. I've got a working Closure version lying around too.

I'll note that after these experiments, I'm starting to feel very uneasy about the `caml_obj_with_tag` function. It does not perform any kind of check (neither on the tag nor on the value), so it doesn't feel like we should be encouraging its use at all.

**Comment by nojb** [comment]
> I'll note that after these experiments, I'm starting to feel very uneasy about the `caml_obj_with_tag` function. It does not perform any kind of check (neither on the tag nor on the value), so it doesn't feel like we should be encouraging its use at all.

None of the functions in `Obj` perform any kind of check, all are unsafe and are generally not meant to be used unless you know what you are doing. Definitely no-one is encouraging their use. This PR is about making an *existing* optimization (to avoid a double allocation) actually usable. Otherwise we may as well get rid of the optimization.

On our side we have performance critical code that uses this trick to implement efficient generic comparison and hashing of hash-consed values... so I would prefer that we keep this optimization :)

This is a summary of the alternatives that have been discussed so far:

1) expose tag values in `Obj` as compiler primitives (`%object_tag`, ...)
   - applies at the Lambda level so it benefits all backends
   - ad-hoc

2) move optimization to `Closure`:
   - does not apply in bytecode
   - does not apply under Flambda
   - no worse than the existing optimization

3) add specialized `with_object_tag` function to `Obj`
   - ad hoc

Would 2) be an acceptable compromise? (@lthls mentioned that he has this implemented somewhere already)

**Comment by lthls** [comment]
Wait, what about patching your code to use `Obj.with_tag 248(* Obj.object_tag *) (Obj.repr e)` ? I don't see any drawback to that.

**Comment by nojb** [comment]
Fair enough.

**Pull request closed without merging**
