### PR TITLE
Move split_default_wrapper to Simplif

### PR DESCRIPTION
**Pull request by mshinwell**
The code for generating wrappers for functions with default parameters lives in Closure at the moment, but needs to be used by Flambda, which we would like to keep separate from Closure.  Simplif seems an appropriate place to put the split_default_wrapper code.  This patch just moves it.

(In the future, Flambda might do this transformation itself, but it doesn't yet.)

### CODE REVIEW

**Comment by mshinwell** [comment]
Please could someone else OK this.

**Comment by gasche** [comment]
I have no particular opinion on the change, but I'm not convinced that Simplif is a natural place to put this function. The signature of Simplif is very simple right now: it (takes a recursive dependency from the backend and) provides exactly one function that simplifies lambda-code. The moved function would probably be more natural directly in Lambda (but maybe there is a reason not to put it there?).

**Comment by mshinwell** [comment]
I don't think this should live in Lambda.  This is a transformation, not a part of the language definition.
We can put it in a separate file if you prefer?

**Comment by gasche** [comment]
>  This is a transformation, not a part of the language definition.

Well neither are `subst_lambda` or `patch_guarded`.

**Comment by mshinwell** [comment]
Well, maybe subst_lambda should live outside too (the equivalent in Flambda does, in fact).  However it could reasonably be justified that such a transformation is fundamental enough to put it directly inside Lambda.  I don't think it can reasonably be justified that this is the case for the optional argument transformation.

**Comment by mshinwell** [comment]
Leo and I have discussed this today.  We've decided to just leave this in Closure for the time being.  The longer-term plan has always been to reimplement this code as a transformation on Flambda in any case.

**Comment by mshinwell** [comment]
I'm reopening this, unfortunately.  We can't sensibly use Closure since it breaks the split between the new "middle end" optimization parts and the backend.
So I think this should just go in Simplif as before.

**Comment by damiendoligez** [comment]
Enough bike-shedding on this one. OK for merging as is.

**Pull request merged**
