### PR TITLE
Unix.poll

### PR DESCRIPTION
**Pull request by toots**
We had some reports on `ocaml-duppy` of errors generated by `Unix.select` reaching its maximum number of file descriptors. This made me realize that OCaml doesn't have a support for `poll()`, which is the usual alternative when reaching this limitation.

Would you guys be interested to add it? I think this PR pretty much covers it, it's just missing some documentation.

### CODE REVIEW

**Comment by nojb** [comment]
Hello, thanks for your contribution! FYI, `poll` exists in Windows since Vista and is called `WSAPoll`.

Having said that, I am not convinced by this PR.

While `poll` has some advantages over `select` they both suffer from the same fundamental problem, the more descriptors you ask them to check, the slower they get. An event-based function (`kqueue`, `epoll`, ...) is the only sane option if you go beyond a small number of file descriptors. Providing good support for these kind of interfaces is a lot of work (not `stdlib` material IMO) and there are already good libraries out there that do this (`lwt`, `async`, etc).

**Comment by toots** [comment]
Hi,

Thanks for your comment.

Re: windows: I have no ways to test on vista. I am always vey wary of the subtle difference in impementation for windows "equivalents" to POSIX functions so I'd rather leave that alone until someone who knows what they are doing is interested by it.

As for limitations and alternatives to `poll()`, I agree with you that this is not the perfect function. However, I personally always prefer better over perfect and, the way I see it, this provides better functionalities to the language even if not the "perfect" solution.

Cheers!

**Comment by nojb** [comment]
What about using `poll` to implement `Unix.select` in those platforms where it is available?

**Comment by dra27** [comment]
IIRC, the full Windows implementation of `select` doesn't have a limit on descriptors, but the "fast" path used when all the descriptors are sockets does.

+1 to @nojb's suggestion that adding `poll` itself doesn't seem to add enough value to be worth the maintenance effort, but using it under-the-hood to "improve" the implementation of `select` could be worthwhile.

**Comment by toots** [comment]
Ok, I've done those changes. They'd have to also be implemented in the `threads` library.

**Comment by nojb** [comment]
I took a look at your patch; since we are not trying to expose `poll` to the users, I think it can be greatly simplified: the patch should not touch any OCaml code nor add any new OCaml primitives.  Rather a small wrapper can be added directly in `unix/select.c` to call `poll` instead of `select`.

**Comment by rgrinberg** [comment]
Is it such a good idea to replace select with poll under the hood like that? I can imagine being really confused when stracing my program for example. I kind of appreciate the Unix module choosing to be rather thin whenever possible.

**Comment by nojb** [comment]
@rgrinberg Good point. FWIW a quick glance shows we already do this: `Unix.times` (where we call `getrusage` under the hood if it is available), `Unix.pipe` (use `pipe2` if available) and of course `Unix.getenv` (use `secure_getenv` if available).

Having said that, it may be a good idea to wait to hear from other developers before spending too much time on this, in case there are more objections to making this admittedly small improvement to `Unix.select`.

**Comment by alainfrisch** [comment]
I know almost nothing about select and poll, but the idea that one could keep the user-facing OCaml API of select, implement in terms of poll instead, and benefit from improved performance seems counter-intuitive to me, since select is exposed to OCaml with an API which looks isomorphic to the C API.  If we benefit from switching to poll, wouldn't the same improvement benefit applies to C as well?  If so, I would assumed that select itself be implemented as a call to poll.

In particular, for both poll and select, one has to turn the OCaml list of file_descr to a C data structure, which takes at least linear time in both cases.  In case of sparse file_descr, the size of the C structure can become larger, but for non sparse sets, it would be more compact.  So the gain is not obvious to me.

Anyway, if the direction is to use poll under the hood for performance reasons only, the decision would depend at least on convincing benchmarks.

(I can also see the limitation in the number of file descriptors for select, but for really large number of file descriptors, poll is not good either.)

**Comment by toots** [comment]
I actually agree with @alainfrisch and @rgrinberg. Having had to deal with `select()` and debugging it, it's already pretty maddening to understand the POSIX intricacies to not add another layer of complexity.

It feels to be that, appart from obvious cases where there is no POSIX equivalent, any `Unix` API exposed by `OCaml` should be as close as possible to the original POSIX so that the usual precautions translate easily for the programmers who are used to them.

If y'all aren't interested by adding `poll()` that's fine with me but I don't think it's a good idea to murky the water here. I still think having `poll()` as standalone would be nice tho :-)

**Comment by toots** [comment]
As for the file descriptor limitation, I've had a user reporting about it. Performance is one thing but it'd be nice to at least make it possible to get passed that limitation.

**Comment by xavierleroy** [comment]
@alainfrisch: the main advantage of `poll()` over `select()` is that `select()` uses fixed-size bitmaps to represent sets of file descriptors, hence puts an arbitrary bound on the integers representing file descriptors, while `poll()` avoids this limitation.  

Another oddity is that `poll()` specifies timeouts in milliseconds while `select()` uses microseconds.  I suspect few OSes implement sub-millisecond resolution for this kind of I/O polling, but still, it makes me nervous to just replace `select()` with `poll()`.

I agree with @nojb that applications that run into select()'s limitations probably need something more efficient than poll() anyway, and that Lwt and Async do a great job at abstracting over all this cruft.

**Comment by rgrinberg** [comment]
@toots what's the issue of having it standalone? In practice you have to support a bunch of old OCaml versions anyway and you can make and publish improvements at your own pace, not that bindings to poll will change much.

**Comment by toots** [comment]
Standalone works for me. I actually already wrote a C binding for my app, I was just trying to see if I could contribute back. :-)

**Comment by xavierleroy** [comment]
Several of us have cold feet about merging this poll()-based implementation, so I propose to close this pull request.

**Comment by toots** [comment]
Sounds good thanks for the time and feedback.

**Pull request closed without merging**
