### PR TITLE
Replace constant pointers by regular integers

### PR DESCRIPTION
**Pull request by lthls**
Following a suggestion by @mshinwell , here is a proposal to replace occurrences of `Const_pointer` constructors by representations of regular integers in all parts of the compiler.
The motivation behind this patch is not only a small simplification of the code base by removing extra constructors, but also the result of a reflection that led us to think that the differentiation between regular integers and integers produced as constant constructors of a variant type is neither necessary nor sufficient to ensure that every register that can hold a pointer is annotated as such in the backend.
Not sufficient, because there were bugs found with GADTs where a register could end up storing values of different types, so the fact that a register can hold values of type `int` doesn't mean that it cannot be joined with a register that can hold pointer values (See #555 and #600).
Not necessary, because as a consequence of fixing the bugs, `Selectgen` now properly computes the right register type at join points, and adjusts register types on assignments based on the value being assigned. Treating constant constructors as potentially holding pointers is obviously a safe approximation, but safety is now guaranteed even without this approximation.

More than the patch itself, what we would like from this pull request is confirmation of our assessment that constant pointers are not necessary anymore (or counter-examples). Mark noticed inconsistencies in the use of constant pointers vs. regular integers in the front end, and it would be nice to know it doesn't really matter.

There is also a theoretical performance gain by marking more registers as `Int` instead of `Val`, but we haven't tried to measure it and are not hoping for significant improvements.

Side note on the patch: `Lambda.structured_constant` still has a `Const_pointer` constructor, because removing the constructor would have required a bootstrap (since `Lambda.structured_constant` values can end up in `.cmo` files). All expressions using it have been adapted, so it should only remain present in patterns.

### CODE REVIEW

**Comment by mshinwell** [comment]
To summarize why I think this is safe:
- `Selectgen` now handles register typing correctly at join points and applications;
- For "set field" primitives generating `caml_modify`, the primitive is marked with "immediate or pointer", so we have the correct judgement about "all values of the type" which is required.  (For the static judgement as to whether to generate `caml_modify` or not, what matters is the total set of kinds of values which may be held in the location, not the kind of some arbitrary value being put in there.)

The inconsistencies in the use of "const pointer" in the frontend and a good general simplification throughout the compiler make me in favour of this change.

**Comment by stedolan** [comment]
This looks like a great change. I presume the intent is to bootstrap after this and then remove Const_pointer entirely?

**Comment by mshinwell** [comment]
@stedolan Yes, I think that's right.

**Comment by chambart** [comment]
I reviewed it and the changes itself is ok. I'm quite confident that the assumption is effectively valid, and will remain valid.

The travis error is due to the absence of `Changes` update. I don't consider that strictly required, but can still be added since this will affect producers of lambda like @stedolan's malfunction.

As this is not urgent, I will not merger right now, waiting for at least an acknowledgment from @xavierleroy.

**Comment by xavierleroy** [comment]
I feel very positive about this change.  I'm at a conference right now but will do my best to review within a week.

**Review by xavierleroy — APPROVED** [review]
I read the changes and ran a round of CI.  It's a big diff but almost all of it is systematic and makes the code simpler.  In the end it all hinges on the correctness of type inference at join points in the Selection pass, but if there is a bug there, 1) we need to know anyway, and 2) we'll find out more quickly than with the current code.

**Comment by xavierleroy** [comment]
@lthls would you mind rebasing on trunk and fixing the conflicts? Then we'll merge.

**Comment by lthls** [comment]
I've rebased and fixed the conflicts. I can add a Changes entry if you want, and if you wish for Const_pointers to be completely removed from `Lambda.structured_constant` I can add the bootstrap steps needed (maybe not until next week though).

**Comment by xavierleroy** [comment]
Thanks for the rebase.  A Changes entry is welcome.  Don't bother with the bootstrap, I or another core developer can do it directly on trunk.

**Comment by mshinwell** [comment]
@lthls Let me know next week when you want to do the bootstrap and I will do it for you.  Thanks for working on this one (and thanks to @xavierleroy for the review).

**Comment by mshinwell** [comment]
I've removed `Lambda.const_pointer` and bootstrapped (rev. b4fa820b7).
It looks like there are a few remnants of "const_ptr" in the Flambda code, which I will make another GPR for in a moment.

**Comment by mshinwell** [comment]
One further comment: the bootstrap commit has changed the `.cmo` format.  I didn't update the magic numbers because I hear that now those numbers are going to be changed only immediately prior to the release.

**Comment by damiendoligez** [comment]
Given the state of the discussion in #1660, I have reverted this PR to prepare for the 4.07 freeze, as we don't yet have consensus on how to solve the bug introduced here. (commits d42422a0cfb2d0daf8d8070eb19a699e12b858dd, e52f39cbe9d7cef666fbce4c2dc085957670cc65, f854511e47e5f2af58efe4acc5239a04ffb8e7d0)

**Pull request merged**
