### PR TITLE
Store the path of cmos inside debug section at link time 

### PR DESCRIPTION
**Pull request by hhugo**
Following #14  (Add absolute directory names to bytecode format for `ocamldebug` to use).

This PR add the absolute directory of compilation units to debug section when linking a bytecode program.
It provides the location of `*.cmo` ,where one may find other files such as `*.cmt`.
It's especially useful when dealing with installed libraries.

I wonder if `*.cmt` could be used (/ are already used) by `ocamldebug`. Anyhow, one may decide to install `*.ml` next to `*.cmo` to ease debugging when using this library. (OCaml already install source files that way)

Note that this patch just add a new path to the existing path list introduced by #14 and does not change the format of bytecode binary

### CODE REVIEW

**Comment by hhugo** [comment]
cc @jwatzman

**Comment by planar** [comment]
For reference, this is related to the following:
http://caml.inria.fr/mantis/view.php?id=6270
https://github.com/ocaml/ocaml/pull/14
https://github.com/ocaml/ocaml/pull/58
http://caml.inria.fr/mantis/view.php?id=6841

**Comment by hhugo** [comment]
Any chance to see this in the next minor release ?

**Comment by damiendoligez** [comment]
I'm running some tests and I'll commit to 4.02 if all goes well.

On the other hand, I think it's important to advertise the fact that library authors should (at least provide the option to) install the sources along with the .cmi/cma files of their libraires. Could you send a mail to caml-list? Is there any other repository for such advice?

**Comment by damiendoligez** [comment]
Patch applied in branch 4.02 (commit 16119).

**Comment by gasche** [comment]
I found this issue again as I was working on reproducible builds for OCaml with `-g` -- of course #14 is also concerned. I'll try to implement the current protocol devised by the [reproducible-builds](https://reproducible-builds.org/) people (I'm currently at the Mirage retreat talking to @infinity0 about this) to support arbitrary mapping from absolute path prefixes to user-chosen values, which would let people opt-in to having reproducible builds: see the [BUILD_PATH_PREFIX_MAP specification](https://reproducible-builds.org/specs/build-path-prefix-map/).

**Pull request closed without merging**
