### PR TITLE
Add Obj.null, a value that can work as a null pointer

### PR DESCRIPTION
**Pull request by chambart**
Add Obj.null, a value that can work as a null pointer

### Purpose

To implement some data structure that can contain unfilled uninitialized fields, it can be useful to have a filler value. But this value has to be recognizable: it can't be any value that the user could create.

This could be used for instance in https://github.com/ocaml/ocaml/pull/11563 , or to make a space efficient option array.

### How

This is exposed as a single value `Obj.null` of type `Obj.t`. This is a statically allocated block of length 0 that is not an atom.
There is a special case for marshaling. (should the magic number change ?).
The only runtime cost incurred to unrelated things is an additional branch when marshaling an atom.

The only way to properly interract with that value is `==`

As an example the last commit shows an Optionarray submodule using it. A proper version would need an additionnal C stub to allocate the uninitialized array efficiently. This part is not really proposed in this PR.

### CODE REVIEW

**Comment by nojb** [comment]
Loosely related: https://github.com/ocaml/ocaml/pull/9535

**Comment by c-cube** [comment]
This could also be useful to implement an open addressing version of `Hashtbl`. The modern hashtables in C++ (abseil, etc.) and rust use the [Swiss table](https://www.youtube.com/watch?v=ncHmEUmJZf4) which has a separate array for hashes and for key/values[^1]; in any case these kinds of tables need to be able to represent empty slots.


[^1]: it also uses SIMD to check 4 or 8 slots at a time, but we probably can't do that.

**Comment by gadmm** [comment]
The goal is to unbox the option type when denoting uninitialized values, so one way to see it is that the sole purpose is performance in this particular use-case.

If accepted, null should nevertheless not be considered a well-formed OCaml value like others: the user should never have to check for null values they did not create. For instance, data structure implementations should make sure that this form of null never escapes. Similarly the convention should be made that the C `value` type denotes a non-null value in API interfaces.

One drawback of this approach is that there is an additional load for every null check, compared to using the 0 bit pattern. Beyond null-initialization, checking for null is the only thing you do with it, so the simpler the better IMO. In the Dynarray implementation of `get`, this null check would come in addition to two separate range checks already (dynarray size and backing array length).

Also, in the end the implementation does not look much simpler than the PR #9535 that represents null as `NULL`.

Taking a step back, you essentially want to treat null as an immediate, distinct from all other immediates. With this in mind, one could also investigate representing null as `0x2`, indeed this offers an efficient test `Is_block(v) ≝ (v & 0x3 == 0)` and probably gets the null check factored with existing checks in some parts of the runtime. (Regarding the use of the `0x2` bit pattern to encode raised exceptions in some parts of the C API, one could strengthen the test `Is_exception_result`, or simply do nothing about it as users should not return it as normal values.)

**Comment by lpw25** [comment]
I've intended to add a this for a long time. As a maintainer of [Base.Option_array](https://github.com/janestreet/base/blob/master/src/option_array.ml) it would make my life easier. I had always planned to use the traditional null value though and just update a couple of places in the GC to avoid it following null pointers. Can you comment on the difference between this approach and the one with the not-quite-atom value?

**Comment by xavierleroy** [comment]
You could define `Obj.null` as `Obj.new_block 42 0` and it would work about as well, but no change would be required in the marshaler.  (Atoms with tag <> 0 are never used in the representation of OCaml datatypes, currently.)

**Comment by chambart** [comment]
@gadmm We could also reduce a bit the cost of accessing that null value by allowing direct access to a C symbol with something like that: https://github.com/chambart/ocaml-1/commit/bc740dcb92256bc85873dfb1f5c56edbbdc0418d and https://github.com/chambart/ocaml-1/commit/e0d6287cbf845a9ea20d79dc1680efbecdd21166
The generated code for a null test would be 
```OCaml
external null_value : t = "caml_null_value"
let test_null u a b =
  if null_value == u then
    a
  else
    b
```

```assembly
camlTtt.test_null_272:
        .cfi_startproc
.L101:
        movq    %rax, %rsi
        movq    %rdi, %rax
        movq    caml_null_value@GOTPCREL(%rip), %rdi
        cmpq    %rsi, %rdi
        jne     .L100
        movq    %rbx, %rax
        ret
```
Of course this is still a bit less compact than a zero test.

@lpw25 I don't really have a preference for either choice. My main argument would be that I think that this version incur a lower mental burden to the GC maintainers. Since I'm not the one doing it, I wouldn't chose by default to impose that on them. But if they are happy with the null is 0 version, it's completely ok for me.

@xavierleroy Yes of course, but I would not have been confident about reusing something like that. If you are ok with it I have no objection about reusing atoms.

**Comment by c-cube** [comment]
I'm wondering about `Optionarray` living in `Array`.

It's a pretty niche use case, and in #11563 I would rather have a somewhat more unsafe version that doesn't allocate `Some _` for every valid access. Instead, I'd like access to something like `get_value_or_null : 'a t -> int -> 'a`, which can be used in combination with `Obj.null` to test for the presence of a value. This would make more sense if `Optionarray` lived in `Obj` instead for now, I think.

**Comment by gasche** [comment]
I have a naïve question about these proposals, from the point of view of a library author considering the usage for a  ¨missing value" value for optimization. My optimizations assume that I'm the only one using this "missing value" value, so that I know for sure that it comes from my code and was not put there by the user. But how can I make this assumption if the stdlib provides one `null` value that is useful for various things, including for things that my users may want to do?

Basically there seems to be an inherent problem of composability, at least assuming a single `null` value. If I want to design a clever data structure backed by a `'a Dynarray.t`, and I use `Obj.null` for missing values at my level, there is a risk that `Dynarray` itself makes assumptions on the meaning of `null` (probably hidden under the abstraction boundary) so I cannot tell if my code is safe. Maybe it will blow up with an assertion failure due to `Dynarray` assuming that I'm not using `null`.

Am I missing something?

In the Dynarray PR #11563 I mentioned using a module-local freshly allocated block to represent a missing value. This is a common trick that is also used by other people. (It was used by the Multicore runtime itself to track domain identity at some point, for example.) It does not suffer from the composability problem above, and does not need runtime support. (It could benefit from some compiler support in that I would ideally like to be able the fresh block address to be compiled as a constant, but currently I need to create a mutable block to ensure that it will not be silently equated to another equivalent value, so it is not compiled as a constant.)

**Comment by lthls** [comment]
The freshly allocated value is unsafe in the presence of marshalling. If you marshal a Dynarray, and reload it, then the blocks representing absent values are not detected as such anymore, and if you search for them you will return a type-unsafe value.
The `Obj.null` versions do not suffer from this.

**Comment by alainfrisch** [comment]
>  If I want to design a clever data structure backed by a 'a Dynarray.t, and I use Obj.null for missing values at my level, there is a risk that Dynarray itself makes assumptions on the meaning of null (probably hidden under the abstraction boundary) so I cannot tell if my code is safe. 

Obj.null is obviously unsafe, and it shouln't be advertised as a solution for the general audience to write clever data structures.  As long as the Dynarray is part of the Stdlib, I think this is fine.  Then, if people want to take the risk of writing their own clever data structures, they should indeed make sure that the functions they call will work well with Obj.null (you wouldn't generally expect to be allowed to pass Obj.null to an arbitrary functions, and there is no reason to believe it is ok to pass it to Dynarray).

**Comment by gasche** [comment]
@lthls I think we could keep the fresh/private value as part of the structure metadata (a new field of the toplevel record). Then marshalling should be safe as long as it preserves sharing.

@alainfrisch I think you are suggesting to deal with the lack of compositionality by simply forbidding people to try to compose abstractions using `Obj.null`. I am skeptical that this would work, and it is only a workaround rather than a fix. Is there a better, more composable design?

Note to self: intuitively it is okay if several people use `Obj.null` in *members* of their data structures, but never as *top-level values* -- and conversely preserve the discipline that we can check other values for equality with Obj.null, but not their unknown/abstract internal fields.
This is in fact similar to the current invariants on unboxed float values in the OCaml runtime, which can only occur safely inside structures -- or raw pointers. In this two cases we use metadata in the container to let the runtime know that those fields are not valid, and there is no in-language mechanism to manipulate them directly -- for now. Here the runtime would see this as a valid value but we try to preserve the not-at-toplevel invariant through careful programming.

**Comment by xavierleroy** [comment]
> The freshly allocated value is unsafe in the presence of marshalling.

Not if it is part of the data structure.  See my comment https://github.com/ocaml/ocaml/pull/11563#issuecomment-1258374194 .

I share @gasche 's reservations about this PR.  The only way NULL can be tolerated is if each abstract data type that needs it has its own private NULL, not visible to anyone else.  Putting it in Obj doesn't do anything to hide it.

I move to close this PR.

**Comment by bluddy** [comment]
Given the unfortunate hackiness of this solution and the usecase for filling in missing values, it makes just as much sense to fill the values with OCaml zeros, right? And just mask them with `Obj.magic`?

**Comment by gadmm** [comment]
Is there a precedent in the stdlib for the fact that the No_sharing flag would create a value which is unsafe after unmarshalling (despite having the right type)? Let me guess however that this is secondary because No_sharing is already for people who know what they are doing (and there would be warnings in the documentation of Dynarray).

@gasche I think implicitly some of us see null from the point of view of having a different kind, inside the sort of type system with kinds for unboxing Leo & Stephen have worked on (cf. ML workshop last month). Most data structures would have type arguments with the default kind "value" that excludes null. So the situation regarding compositionality is well-understood with null (this is essentially the problem of unboxing two layers of `option` at once), but also it could realistically be made safe in the future. 

Now the only advantage I see from this approach (besides No_sharing) is that the code generated for the null check is optimal. It looks to me that the implementation strategy from the current PR has the drawbacks without the advantages.

**Comment by c-cube** [comment]
@xavierleroy @gasche I fail to see how `Obj.null` would be worse than what is already possible, for example `Obj.magic 0`. At least `null` would be a unique bit pattern that is guaranteed to not be confused with valid values by accident, so it's strictly better than the status quo. And of course `null` is not composable, and should not be passed around in public interfaces. If you try to make it composable and expose it as a regular value… you shouldn't use `Obj`, right?

**Comment by gasche** [comment]
@gadmm I thought of the connection to unboxed kinds (which generalize unboxed floats and unboxed naked pointers in my examples), but note that the mode of use that we have in mind is not explained by kinding alone. When we put "a value or ǹull`" in a dynarray slot, intuitively one would model this as a union type (not a disjoint union / sum) `union(ty, null)`, and the check `is_null` serves to decide to which member of the union a slot content actually belongs. Two consequences:

1. It is not clear how to give a non-star kind to `null` in this situation in a way that makes sense. One could think of having a superkind of both `star` and `null`, and have the union live in this superkind, but then why is it valid to store values of this non-star kind inside an array in the first place?
2. The fact that `union(ty, null)` is safe makes distinguishability assumptions on the runtime representation -- the kinding discipline in itself does not guarantee that values inhabiting types at incompatible kinds have disjoint representations. Those runtime-representation assumptions are integral to the safety of the whole construct.

@c-cube before "blessing" a particular unsafe idiom by adding it to the Obj module, I would like to understand how/when it is supposed to be used safely. If we don't know how explain how to use it safely, then maybe it's not such a good idea. I think this is the discussion with @gadmm. You point out that we can already do worse, and that it's okay if it's not always safe if it's in `Obj`, but these counter-arguments could very well (unintentionally) hide the fact that there is a design flaw and code using this new trick is deeply flawed in a non-obvious way.

**Comment by gadmm** [comment]
`'a array`, and some other primitive types, would explicitly accept `'a : value or null`.

A type family `nullable : value -> value or null` would be provided, behaving as a disjoint union (the union is disjoint, by virtue of having a distinct representation for null).

**Comment by bluddy** [comment]
Would it be helpful if Obj.null *didn't* exist as its own entity, but instead was hidden behind primitives? We would then have `Obj.array_set_null: 'a array -> int -> unit` `Obj.array_is_null : 'a array -> int -> bool` taking an array and an offset etc. It limits what you can do with it, but maybe that's the point -- we don't have the type theory to introduce something like this into the language, but limiting its uses to specific usecases means we're also minimizing the damage it can do.

**Comment by gasche** [comment]
Yes, i think that @bluddy's suggestion actually make sense. (If it's `'a array`, the primitive can deal with float-arrays vs boxed-arrays, and it could be just a C function in array.c instead of a compiler primitive. We could also give it a more low-level interface like `set_null: Obj.t -> int -> unit` that works for other (mutable) blocks, but I'm not saying it's a good idea.)

**Comment by c-cube** [comment]
I'd be fine with nullable arrays being the primitive provided by the
compiler + Obj. In a way it's like `Weak`, it only exists in array
version…

**Comment by gadmm** [comment]
I do not think that the issue here is the color of the tapestry. What implementation do you have in mind? The simplest still seems to be special-casing null in a couple of places in the runtime and this does not change anything.

**Comment by xavierleroy** [comment]
> Is there a precedent in the stdlib for the fact that the No_sharing flag would create a value which is unsafe after unmarshalling (despite having the right type)? Let me guess however that this is secondary because No_sharing is already for people who know what they are doing (and there would be warnings in the documentation of Dynarray).

I agree with your guess.  This is a minor limitation and it can be documented.

**Comment by xavierleroy** [comment]
Quoting my comment earlier:

> The only way NULL can be tolerated is if each abstract data type that needs it has its own private NULL, not visible to anyone else. Putting it in Obj doesn't do anything to hide it. I move to close this PR.

I don't see the problem being addressed  in this PR, so I'll close.

**Pull request closed without merging**
