### PR TITLE
Stop pushing default arguments when there is an unlabeled argument

### PR DESCRIPTION
**Pull request by garrigue**
In MPR#7531, Stephen Dolan points out that sometimes the evaluation of default arguments is delayed too much.
This patch fixes this, by only pushing them after the first non-labeled argument.

### CODE REVIEW

**Comment by mshinwell** [comment]
Please rename the test case to `eval_order_5.ml` if you could, or it will clash with #1162.

**Comment by garrigue** [comment]
Done the renaming. Will merge now, as it seems that there is no blowup with this change.
(Cf exchange with Xavier Leroy of 2000-08-31)

**Comment by stedolan** [comment]
Thanks!

**Comment by lpw25** [comment]
This change produces quite a lot of regression in terms of extra allocations for terms like:

```ocaml
let f ?(x = 0) y z = ()
```

because this is no longer a single three argument function and so produces a closure allocation. Really this needs to be fixed in 4.06 as the change in allocations is quite noticeable.

To be honest it is not at all clear to me why the new behaviour introduced by this patch is an improvement on the old behaviour. It still moves default argument evaluation about in a possibly unexpected way, but treats labeled and unlabeled arguments differently. I think one of two options would make more sense:
1. Revert to the old behaviour of always pushing default arguments underneath functions, it is consistent with what OCaml manual says and avoids producing unnecessary closures.
2. Use a syntactic check of purity to decide whether to push an argument, and then push pure arguments under all functions. This would provide the "expected" semantics for when default arguments are evaluated and in the vast majority of cases (i.e. a pure default) it would avoid needless closure allocation.

**Comment by alainfrisch** [comment]
Indeed, this looks quite bad.  At this point in the release process and considering the previous behavior was not so bad compared to the (un)spec, I'd argue for reverting.  We should also add a non-regression test that monitors the allocations of such cases.

**Comment by garrigue** [comment]
I have no problem with reverting first and thinking later.

**Comment by garrigue** [comment]
@lpw25 To clarify the goal of this patch: the semantics, as in [Labeled and optional arguments for OCaml](http://www.math.nagoya-u.ac.jp/~garrigue/papers/index.html), says that default arguments should be evaluated once a function is applied to an unlabeled argument. This is what this tries to implement, and I think it's correct (the only difference is that you cannot trigger the evaluation manually by applying to ?x:None, but this is more an artefact on the implementation than a guaranteed semantics). All this pushing was originally introduced to avoid performance problems with lots of default arguments,  so the performance problem should be solved first. Your option 2 seems reasonable, but I agree there is no hurry (I see no code around depending critically on the evaluation of the default argument not being delayed). I'm not sure what you mean by "consistent with the manual".

**Comment by lpw25** [comment]
> I'm not sure what you mean by "consistent with the manual".

I just meant that [Section 6.7](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sec122) of the manual states:

> A function of the form fun ? lab :(  pattern =  expr0 ) ->  expr is equivalent to
>
> `fun ? lab :  ident -> let  pattern =`
>  `match  ident with Some  ident ->  ident | None ->  expr0 in  expr`
>
> where ident is a fresh variable, except that it is unspecified when expr0 is evaluated.

which clearly allows for the previous semantics.

**Comment by garrigue** [comment]
Thank you. I hadn't read the last sentence :)
I suppose I added that after adding `push_defaults`.
So at least we follow the manual. It might be worth adding "when, and how many times".

**Comment by garrigue** [comment]
Reverted the merge in trunk and 4.06, commits 7257acb4f and ce172adc4.

**Pull request merged**
