### PR TITLE
Restore `SYSTEM`, `ARCH` and `MODEL` information for bytecode-only architectures

### PR DESCRIPTION
**Pull request by dra27**
The mechanism used to mark the "no native backend yet" configurations for OCaml 5.0 in #10871 accidentally reverts #10044 (and which I just noticed while trying to use the value of `system` on a bytecode-only architecture).

This affects/regresses the output of `ocamlc -config` on the affected architectures, so I think it ought to go on 5.0.

### CODE REVIEW

**Comment by dra27** [comment]
Running through [precheck#791](https://ci.inria.fr/ocaml/job/precheck/791/)

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
The diff is not trivial to read IMO but I do think the change is correct
and should be merged as soon as possible.

**Comment by dra27** [comment]
Thanks, @shindere!

**Comment by dra27** [comment]
Pushed to 5.0 in 76d6baec15 along with @Octachron's fix for Jenkins in 3411237cc1

**Pull request merged**
