### PR TITLE
Improve handling of platforms that do not have gprof profiling support

### PR DESCRIPTION
**Pull request by shindere**
Two questions:

1. Is a fatal error okay when ocamlopt -p is used whereas profiling with
gprof is not supported, or would a warning be better?

(I am personnally in favour of a fatal error but if people think this may
break existing code it can be a warning, too.)

2. Where / how to best modify the Changes file for such a PR?

### CODE REVIEW

**Comment by gasche** [comment]
Re. Changes: either "Compiler user-interface and warning" or "Code generation and optimization" would seem fine to me.

**Comment by shindere** [comment]
Gabriel Scherer (2016/11/24 13:12 -0800):
> Re. Changes: either "Compiler user-interface and warning" or "Code
> generation and optimization" would seem fine to me.

Done, thanks.

**Comment by gasche** [comment]
The INRIA CI is failing on this change (at least: trunk-cygwin-32, trunk-zsystems-64). I pushed the current trunk into `precheck` to get full reports, and then temporarily reverted the change.

**Comment by shindere** [comment]
Gabriel Scherer (2016/11/25 08:13 -0800):
> The INRIA CI is failing on this change (at least: trunk-cygwin-32,
> trunk-zsystems-64). I pushed the current trunk into `precheck` to get
> full reports, and then temporarily reverted the change.

PR#933 was not the direct cause, it just revealed a bug in
asmrun/Makefile.

So, re-applied the reverted commit plus the fix to the other bug.

**Comment by gasche** [comment]
Ok, thanks. There was no issue with the failing CI of course, but I like to revert in a systematic way when that happens because it gives more time to people to relax and think about the fix -- although obviously that wasn't really necessary in this specific case, you solved the issue very quickly.

**Comment by shindere** [comment]
Gabriel Scherer (2016/11/25 08:29 -0800):
> Ok, thanks. There was no issue with the failing CI of course, but I
> like to revert in a systematic way when that happens because it gives
> more time to people to relax and think about the fix --

It may still be a good idea to ask people what _they_ would

**Pull request merged**
