### PR TITLE
[TSan] rework the volatile accesses rules

### PR DESCRIPTION
**Pull request by ghost**
Following the discussion in #13059, I suggest the following changes:

- unaligned accesses are always considered non-atomic
- aligned reads are always considered atomic
- aligned writes are considered atomic if they are of register width. (this assumes an LP64 model)

Since the tsan instrumentation uses distinct callbacks for unaligned vs aligned accesses, this is simple to implement.

Note that these changes rely upon all native backends being LP64 platforms (i.e. sizeof long == sizeof pointer == 64 bits), which is not the case of Win64... but there is no TSan support for it yet.

This makes the s390x spurious issue mentioned in the original issue disappear. Might make some false positives disappear as well.

### CODE REVIEW

**Comment by gasche** [comment]
I don't have the expertise to judge this PR, but I like that the code is made simpler. I wish there was a documentation comment that explains the final design intention.

**Review by fabbing — COMMENTED** [review]
I don't know if I'm rusty from not playing with TSan lately, but I found this PR way more subtle to review than I expected.

This is how the PR description is implemented in the code changes, can you confirm that I have mapped it well?

> Following the discussion in #13059, I suggest the following changes:
> 
> * unaligned accesses are always considered non-atomic

This is achieved by directly using `__tsan_unaligned_volatile_read##size` instead of factoring it with `__tsan_volatile_read##size`.

> * aligned reads are always considered atomic

Reads of size {1, 2, 4, 8} bytes are considered atomic because of the code generated by `DEFINE_TSAN_VOLATILE_READ_WRITE(...);`, this also allows to discard the `size <= sizeof(long long)` test.
While reads of size 16 bytes are not because of the definition of `__tsan_volatile_read16`. 

> * aligned writes are considered atomic if they are of register width. (this assumes an LP64 model)

This is stricter than what the Linux kernel does (https://github.com/torvalds/linux/blob/8cd26fd90c1ad7acdcfb9f69ca99d13aa7b24561/kernel/kcsan/core.c#L1069). Is this due to the s390x architecture? 
> 
> Since the tsan instrumentation uses distinct callbacks for unaligned vs aligned accesses, this is simple to implement.
> 
> Note that these changes rely upon all native backends being LP64 platforms (i.e. sizeof long == sizeof pointer == 64 bits), which is not the case of Win64... but there is no TSan support for it yet.

I suggest making this clear in the code by adding a comment and a static assertion (see below).
> 
> This makes the s390x spurious issue mentioned in the original issue disappear. Might might some false positives disappear as well.

```diff
diff --git a/runtime/tsan.c b/runtime/tsan.c
index bbbd4eabe..8b028d529 100644
--- a/runtime/tsan.c
+++ b/runtime/tsan.c
@@ -20,6 +20,7 @@
 #undef TSAN_DEBUG
 #endif
 
+#include <assert.h>
 #define UNW_LOCAL_ONLY
 #include <libunwind.h>
 
@@ -190,6 +191,11 @@
    fetch_add of zero. */
 
 
+/* Validate the assumption that TSan is executing on an LP64 backend */
+static_assert(sizeof(long) == sizeof(void*), "");
+static_assert(sizeof(long) == 8, "");
+
+
 Caml_inline void caml_tsan_debug_log_pc(const char* msg, uintnat pc)
 {
 #ifdef TSAN_DEBUG
```

**Comment by fabbing** [comment]
I also haven't been able to write code that would generate a call to `__tsan_unaligned_volatile_read`.

In particular, dubious pointer arithmetic as below still generates a call to to `__tsan_volatile_read`, but there is at least a compiler warning: `warning: initialization of 'volatile int *' from incompatible pointer type 'volatile char *' [-Wincompatible-pointer-types]`.

```c
volatile int *p = (volatile char*)data + 1;
```

With this PR we drop the runtime check of pointer alignment, and thus should get better performance, but we will have to be careful not to miss this kind of compiler warning, as TSan will consider these volatile accesses to be atomic.

**Comment by ghost** [comment]
> > Following the discussion in #13059, I suggest the following changes:
> > 
> > * unaligned accesses are always considered non-atomic
> 
> This is achieved by directly using `__tsan_unaligned_volatile_read##size` instead of factoring it with `__tsan_volatile_read##size`.

Yes.

> > * aligned reads are always considered atomic
> 
> Reads of size {1, 2, 4, 8} bytes are considered atomic because of the code generated by `DEFINE_TSAN_VOLATILE_READ_WRITE(...);`, this also allows to discard the `size <= sizeof(long long)` test. While reads of size 16 bytes are not because of the definition of `__tsan_volatile_read16`.

Yes.

> > * aligned writes are considered atomic if they are of register width. (this assumes an LP64 model)
> 
> This is stricter than what the Linux kernel does (https://github.com/torvalds/linux/blob/8cd26fd90c1ad7acdcfb9f69ca99d13aa7b24561/kernel/kcsan/core.c#L1069). Is this due to the s390x architecture?

My understanding of the TSan runtime is that calls to `tsan_volatile_read*` implies alignment (i.e. the `IS_ALIGNED` check in the linux code is redundant). If I am wrong, then this checks needs to be brought back.

**Comment by fabbing** [comment]
While I haven't been able to write code that would generate such a `tsan_unaligned_volatile_...` call, I have noticed tests in LLVM that check for this feature (https://github.com/llvm/llvm-project/blob/8ab3caf4d3acef29f373e09bc6a0ac459918930e/llvm/test/Instrumentation/ThreadSanitizer/volatile.ll#L109).

I agree with you that this PR is an improvement because it leverages compiler's knowledge and should be more efficient at runtime. But, on the other hand, I'm a little bit worried that unaligned pointers might be missed from the many pointer offsetting that happen behind explicit cast in the runtime.
Anyway, in the end, the volatile accesses considered like atomic accesses are supposed to be a temporary solution before moving to proper `atomic` qualifier, so I guess I shouldn't stress too much about it.

I would still really like to see a comment and an assertion that checks for an LP64 backend, this is too subtle not to be written into the code.

**Comment by gasche** [comment]
For me the goal of this PR is not efficiency, but to avoid false alarms on some architectures.

**Comment by ghost** [comment]
I've brought back the address alignment checks, just to be sure to err on the safe side.

**Comment by gasche** [comment]
@dustanddreams : @fabbing suggested a static assert for implicit pointer-size assumptions, is this something that you are planning to add, that you don't want to add, or that you would want to add but it's a hassle to remember how to do it and we should ask @fabbing?

**Comment by ghost** [comment]
With the last changes I think there is no LP64 dependency anymore, so no need to at an assertion about that.

**Comment by gasche** [comment]
Ah, I had missed that, apologies. @fabbing, do you approve now?

**Review by fabbing — APPROVED** [review]

**Review by gasche — APPROVED** [review]
Approved on behalf of @fabbing.

@dustanddreams could you write a Changes entry, or decide that you don't plan to?

**Comment by ghost** [comment]
Done.

**Comment by gasche** [comment]
Thanks -- and @fabbing for the review. Merged!

**Pull request merged**
