### PR TITLE
Typo in arg.mli documentation

### PR DESCRIPTION
**Pull request by craff**

### CODE REVIEW

**Review by Octachron — APPROVED** [review]

**Comment by shindere** [comment]
Thanks. If the change entry is kept I think it has to contain the name
of the reviewer(s) so if the intention is to keep it then it should
probably be amended. That being said I am not sure we do want to have
changes entries for typo fixes so I added the no-change-entry-needed
label to this PR so that its change entry can be removed without
disturbing the CI.

**Comment by Octachron** [comment]
Concerning the changes entry, I am tempted to have a shared `Typo fixes` change entry to list all authors of typo fixes in a lightweight way.

**Comment by shindere** [comment]
Florian Angeletti (2023/07/07 06:04 -0700):
> Concerning the changes entry, I am tempted to have a shared `Typo
> fixes` change entry to list all authors of typo fixes in a lightweight
> way.

That sounds sensible, indeed.

**Comment by Octachron** [comment]
Cherry-picked in 5.1 as 22d83db2 .

**Pull request merged**
