### PR TITLE
Badges. We need badges.

### PR DESCRIPTION
**Pull request by dra27**
Badges. You can't have too many badges.

### CODE REVIEW

**Comment by dra27** [comment]
The code isn't very enlightening, but it can be seen rendered [here](https://github.com/dra27/ocaml/tree/badges#readme)

**Comment by gasche** [comment]
(It's not very clear that the not-very-nice-looking gray logo is the (Appveyor) indicator of the Windows build, but otherwise that seems fine.)

**Comment by dra27** [comment]
I know - if there's an Asciidoc expert who can come up with a better rendering, there's certainly room for improvement! There doesn't seem to be any choice as to the actual badge (at least from the official URL)

**Comment by shindere** [comment]
Not being familiar with badges, I would have appreciated a more
informative commit message.

**Comment by dra27** [comment]
Apologies, @shindere - I was in a silly mood nearing the end of a long day!

**Comment by shindere** [comment]
David Allsopp (2017/05/16 07:51 -0700):
> Apologies, @shindere - I was in a silly mood nearing the end of a long
> day!

No problem! I have seen the updated version, thanks.

I'm sorry but I really do not know what badges are, how they are useful,
etc. Is it something that is supposed to be known nowadays or is it
something that could be explained in a bit more details in the logs?
That's a genuine question, I really don't know.

I'd also prefer a more neutral PR / commit title, perhaps with a bit
more information?

Something like

Badges linking to CI pages?

Also: I think I finally understand that this becomes useful when the
README.adoc is displayed in the GitHub interface, or at least in a
browser, is that correct?
 
Sorry if all this is obvious to you guys, I'm actually reading these
kind of files with less or something similar, that's probably why I am
not aware of such features.

**Comment by dra27** [comment]
@shindere - yes, I'm afraid the feature is only useful when the file is rendered, as the graphic displayed varies depending on the status of the build in each CI. Unfortunately, this isn't in any way accessible, as it's effectively adding scripting to AsciiDoc by the use of an image loaded from another server.

The flippancy of the commit title was a reference to people who measure the success of a GitHub project by the number of stars and, apparently, the number of different badges displayed in the project's README (you can get ones for code coverage, issue closure rate and pretty much anything you can manipulate the API to summarise!).

**Comment by shindere** [comment]
Okay thanks a lot for all your explanations, @dra27.
Was really not aware of all this business.

**Comment by mshinwell** [comment]
Can this PR be merged?

**Pull request merged**
