### PR TITLE
Migrate most of typing-warning tests to expect

### PR DESCRIPTION
**Pull request by nojb**
All tests except `pr7261.ml` (which tests a syntax error) have been migrated.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Very nice, thanks a lot!

Good to merge if CI passes.

**Comment by gasche** [comment]
(There is a minor typo in the last commit message: "expece" => "expect")

**Comment by nojb** [comment]
Thanks, will fix but after the CI finishes.

**Comment by gasche** [comment]
(or not fix at all)

**Comment by nojb** [comment]
What do we do when some of the `expect` output fails `check-typo` ? (line 111 in `unused_values.ml`)

**Comment by gasche** [comment]
Usually you can reduce the line width by breaking lines in the source code of the tests. Once I had to fix formatting in a compiler message.

**Comment by gasche** [comment]
@nojb here indeed it looks like a warning that doesn't contain enough break hints. You probably need to turn the spaces around the constructor names into breakable spaces`@ `, and/or to turn the text fragments into `"%a" pp_print_text "..."` arguments. Need any help?

**Comment by nojb** [comment]
I fixed this one by shortening the constructor name, but I will give a look at the error message later and see if I can improve the breaking hints.

**Comment by nojb** [comment]
There is another `check-typo` failure due to some overly long output from the toplevel. The input is:
```ocaml
let not_ambiguous__several_orpats = function
  | `A ((`B (x, Some _, _) | `B (x, _, Some _)),
        (`C (y, Some _, _) | `C (y, _, Some _)),
        (`D1 (_, z, Some _, _) | `D2 (_, z, _, Some _))) when x < y && x < z ->
      ()
  | _ -> ()
;;
```
and the output
```ocaml
val not_ambiguous__several_orpats :
  [> `A of
       [> `B of 'a * 'b option * 'c option ] *
       [> `C of 'a * 'd option * 'e option ] *
       [> `D1 of 'f * 'a * 'g option * 'h | `D2 of 'i * 'a * 'j * 'k option ] ] ->
  unit = <fun>
```
The long line is 82 characters long. By default the formatter has the margin set to 78 characters, and I looked briefly at the printing code in `Oprint` and I didn't see any glaring problem opening and closing boxes. Does anyone understand why this line is not broken? I was able to get the line to break by setting the margin manually to 75.

/cc @Armael who has worked on related issues recently.

**Comment by Armael** [comment]
Unfortunately, I have no clue why this is happening... :(

**Comment by Octachron** [comment]
The problem is that there is no break hints available in ` ] ] ->`. Thus once the inner `hv` box `` `D1 of 'f * 'a * 'g option * 'h | `D2 of 'i * 'a * 'j * 'k option`` is deemed to fit on the current line, the layout engine can only break the line at the next break, just after the arrow.

**Comment by nojb** [comment]
Thanks for the explanation @Octachron! Do you think it would be OK aesthetically to add a break before the second `]` ?

**Comment by Octachron** [comment]
Let me iterate a bit on an alternative to https://github.com/ocaml/ocaml/blob/trunk/typing/oprint.ml#L299, then I will open a PR with the alternative.

**Comment by gasche** [comment]
GPR #1991 was merged, so the testsuite should now pass check-typo (after a rebase).

**Comment by nojb** [comment]
`changes` check failing, in spite of the `no-change-entry-needed` label.

**Pull request merged**
