### PR TITLE
Fix variance composition

### PR DESCRIPTION
**Pull request by Octachron**
In #11018, a small typo in the computation of variance composition made OCaml 5.1.0 forget to count a possible positive occurrence under a possible negative occurrence as a possible negative occurrence. This made the typechecker accepts absurd statement like:

    type -'a n
    type +'a p
    type +'a ko = 'a p n

This PR fixes this typo and adds test to catch this mistake if it were reintroduced.

### CODE REVIEW

**Comment by yallop** [comment]
It's worth noting that this is a soundness bug, so there's a strong argument for backporting it to 5.1.0:

```ocaml
$ cat var.ml
module F(X: sig type -'a n end) =
struct
  type +'a p = 'a
  type +'a ko = {ko: 'a p X.n}
  let cast (x : < m:string > ko) = (x :> < > ko)
end

include F(struct type 'a n = 'a -> unit  end)
let g ko = (cast {ko}).ko
let h = g (fun m -> print_endline m#m) (object end)

$ ocaml var.ml 
Segmentation fault
```

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
Obviously correct. (And I support the idea of backporting in 5.1.)

How did you find this bug?

**Comment by Octachron** [comment]
The bug was reported yesterday by @polytypic .

**Comment by gasche** [comment]
(I suspect that Jeremy also reviewed the implementation and deserves reviewer credit, if only for doing the extra leg work of turning it into a an unsafe cast.)

**Comment by Octachron** [comment]
That's fine with me, @yallop did you have a look at the fix?

Note that the `Positive_ref` module in the testsuite that exposes a covariant reference type was my version of an unsafe cast.

**Comment by yallop** [comment]
I've now looked at the (clearly correct) fix, but there's no need to credit me.

**Comment by garrigue** [comment]
Indeed this was a stupid typo, sorry for introducing it to start with, and thanks for fixing it so fast.

**Pull request merged**
