### PR TITLE
Add a cute ascii-art Camel to copyright headers

### PR DESCRIPTION
**Pull request by EmileTrotignon**
This PR adds a cute ascii-art camel to the copyright headers.

I hope this matter will be taken with the seriousness it deserves : this will allow the OCaml sources to catch up with the cuteness of the Coq project which has an ascii art of a rooster in its copyright headers : https://github.com/coq/coq/blob/master/Makefile 

The first commit modifies `tools/check-typo` to check for the presence of the camel, and the second adds the camel to every copyright header.

The second commit does modify every file, so it would be quite tedious to review, but I have generated it with this script : https://github.com/EmileTrotignon/ascii_camel. It has `dune`, `re`, and `cmdliner` has dependencies and you can use it to generate the second commit.

From your ocaml directory :
```bash
cd ..
git clone https://github.com/EmileTrotignon/ascii_camel.git
cd ascii_camel
dune exec bin/main.exe $(find ../ocaml -type f) 
```

Then you should be able to automatically check that the diff is the same, and reviewing my script should be sufficient.

I do add an extra line to the copyright header, which was necessary to give legroom for the camel, without bothering the authors bellow who might be resting anywhere on their line. 

Here is an example of a copyright header with the beast displayed : 
```awk
#**************************************************************************
#*        ^o3                                                             *
#* ~/\_/\_|)                       OCaml                                  *
#* |/=_=\|                                                                *
#* "     "                                                                *
#*           Damien Doligez, projet Gallium, INRIA Rocquencourt           *
#*                                                                        *
#*   Copyright 2012 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************
```

### CODE REVIEW

**Comment by OlivierNicole** [comment]
Well, other considerations aside, it _is_ easily reviewable.

**Comment by gadmm** [comment]
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -901,10 +901,29 @@ endif()
 
 # Sandboxing: Landlock
 if(NOT SANDBOX_FOUND AND ENABLE_SANDBOX MATCHES "^ON$|^landlock$")
-    check_include_file(linux/landlock.h HAVE_LINUX_LANDLOCK_H)
+    # A compile check is done here because some systems have
+    # linux/landlock.h, but do not have the syscalls defined
+    # in order to actually use Linux Landlock.
+    check_c_source_compiles("
+        #include <linux/landlock.h>
+        #include <sys/syscall.h>
+        #include <sys/prctl.h>
+.
+        void my_sandbox(void)
+        {
+            (void)prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0);
+            (void)SYS_landlock_create_ruleset;
+            (void)SYS_landlock_restrict_self;
+            (void)LANDLOCK_CREATE_RULESET_VERSION;
+            return;
+        }
+
+        int main(void) { return 0; }
+        "
+    HAVE_LINUX_LANDLOCK)
```

Not sure why this belongs to this PR but it seems that you have a typo in the 4th line. With the typo, the test will always fail.

**Comment by EmileTrotignon** [comment]
Thank you for giving this a look @gadmm 
I do not understand where this comes from : I cannot find a file with the content from the diff in my local repo : is this a generated file ?

**Comment by wikku** [comment]
> ```
> /\_/\
> /=_=\
> ```

This appears to be an infiltration by the OKittn team

**Comment by yakobowski** [comment]
> Thank you for giving this a look @gadmm I do not understand where this comes from : I cannot find a file with the content from the diff in my local repo : is this a generated file ?

It's a joke-in-the-joke. It comes from this week-end's discovery of a backdoor in `xz`.

**Comment by NickBarnes** [comment]
Can we reduce the vertical size?
```
#**************************************************************************
#*        ^o3                      OCaml                                  *
#* ~/\_/\_|)                                                              *
#* |/=_=\|        Damien Doligez, projet Gallium, INRIA Rocquencourt      *
#* "     "                                                                *
```
and/or call the ASCII art by reference rather than touch 1500 files?

**Comment by ghost** [comment]
In order to really be pet-friendly, this camel picture ought to be written in [PETSCII](https://en.wikipedia.org/wiki/PETSCII) instead of ASCII.

**Comment by EmileTrotignon** [comment]
> Can we reduce the vertical size?
> 
> ```
> #**************************************************************************
> #*        ^o3                      OCaml                                  *
> #* ~/\_/\_|)                                                              *
> #* |/=_=\|        Damien Doligez, projet Gallium, INRIA Rocquencourt      *
> #* "     "                                                                *
> ```
> 
> and/or call the ASCII art by reference rather than touch 1500 files?

Its certainly possible to reduce the vertical size either by having the same design poke its head through the `***`s or by redesigning (maybe just cut of the feet ?)

I am not sure what you mean by calling the ascii art by reference.

**Comment by NickBarnes** [comment]
`#include <caml-art.h>` (or put it in `LICENSE` which is already referred to by every header).

**Comment by shindere** [comment]
We are grateful to the author for having made one of our triaging
meetings a bit more fun than they usually are and appreciate this
contribution.

We did discuss this PR quite seriously. The final decision was not take
it, because we find it convenient that the information reported by
GitHub re:when a file has been changed for the last time is meaningful.
This PR would pretty much reset this information for almost all the files
in the repository, which we thought was not so convenient.

Very much looking forward to Apri 1st 2025!

**Pull request closed without merging**
