### PR TITLE
Reimplement mutexes and condition variables in OCaml using atomics + suspend/notify

### PR DESCRIPTION
**Pull request by xavierleroy**
This is an experiment, not ready for merging, just another data point in the discussion about semantics of mutexes (#9757, #9846, #9863).

Here, mutexes and condition variables are implemented mostly in OCaml, using the recently-introduced Atomic standard library module and  a new suspend/notify mechanism.  The implementation of mutexes "naturally" has binary semaphore semantics, where `Mutex.unlock` can be called from any thread, not just the one that locked the mutex.  Additionally, a bunch of OS-dependent C code is removed.

### CODE REVIEW

**Comment by stedolan** [comment]
I have grown to strongly dislike the `wait`/`notify` style API, due to the implicit global state of "has this thread been notified?". It makes it hard to reason about operations in a composable way, and can lead to very long debugging sessions if wait and notify get out of sync. (For instance: deadlock-freedom of the condition variable implementation here relies on the fact that `Mutex.unlock` never calls `wait`).

Instead, how about this variant?

```ocaml
type notifier
val create_notifier : unit -> notifier
(** Create a notifier for the current thread *)
val wait : notifier -> unit
(** Blocks until the notifier is signaled.
    If the notifier was already signaled, returns immediately.
    The notifier must have been created by the current thread *)
val signal : notifier -> unit
(** Signals the notifier, waking the owning thread if sleeping.
    Signalling twice has the same effect as signalling once 80
```
The list of threads queuing for a mutex would become a list of notifiers. With separate notifiers for each operation, it's impossible to get wait and notify calls out of sync.

**Comment by dra27** [comment]
Assuming this implementation has better or similar performance than #9863, being in pure OCaml would allow for `Mutex` to have go from undefined behaviour to well-defined errorcheck behaviour (i.e. merge #9846) and this version could live independently of systhreads?

**Comment by xavierleroy** [comment]
> I have grown to strongly dislike the wait/notify style API, due to the implicit global state of "has this thread been notified?"

I'm not really proposing this as an API, just as a basis for implementing mutexes and condition variables.  I put the functions in thread.mli with detailed comments to help me and reviewers understand what's going on, but I'd rather not see them used by end-users.  If we go this way I'll un-export them.

> Instead, how about this variant?

It looks nicer but may be hard to implement efficiently under Windows.  Win32 events are a nice tool for this kind of suspend/resume synchronization patterns.  But as I mentioned in #9894 they are kernel objects and we can't allocate one per mutex or one per condition variable; one per thread is about as much as we can do.  I hear that CRITICAL_SECTION use events under the hood for passive waiting, but use a pool of events and what not to avoid allocating one event per CRITICAL_SECTION.  I'd rather not go through the same kind of hoops just to get a nicer API for a low-level mechanism that is used in exactly two places.

**Comment by xavierleroy** [comment]
> being in pure OCaml would allow for Mutex to have go from undefined behaviour to well-defined errorcheck behaviour 

Not sure I understand the question correctly. But, yes, this implementation could easily be extended to implement error-checking mutexes instead of binary semaphore mutexes.  

> and this version could live independently of systhreads?

Again, not sure I understand the question.  But, yes, this implementation makes few assumptions on the underlying threading engine.  In particular, it does not depend on the existence of a global lock.  It does assume a correct implementation of the Atomic interface, and a suspend/notify mechanism, though.  Also, with POSIX threads mutex operations are strong memory barriers, while this implementation may need some additional memory barriers to get the full POSIX guarantees w.r.t. memory ordering.

**Comment by xavierleroy** [comment]
Post-scriptum:

> this implementation makes few assumptions on the underlying threading engine. In particular, it does not depend on the existence of a global lock.

However, if real parallelism is involved, a good implementation of POSIX mutexes and condition variables would probably be more efficient and possibly more fair.  With a global lock that serializes everything, the extreme simplicity of this implementation could be good enough, and maybe even a win.

**Comment by xavierleroy** [comment]
Now that #9846 is merged, with the error checking semantics for mutexes, I won't pursue this experiment.  Closing.

**Pull request closed without merging**
