### PR TITLE
Attempt to fix a probable bug introduced by GPR#156.

### PR DESCRIPTION
**Pull request by alainfrisch**
See my last note on #156.

It would be interesting to re-run benchmarks done when accepting #156 to see if the gains are confirmed after this fix.

### CODE REVIEW

**Comment by alainfrisch** [comment]
We've got confirmation that this patch fixes the segfaults on several tests for our customer, so I've merged this PR.

> I confirm this patch is the cause of some segfaults; we've seen this on Coq with flambda at high inlining > levels.

@mshinwell @chambart Can you confirm that the patch proposed here (now merged) fixes those segfaults?

**Comment by chambart** [comment]
@alainfrisch The fix seems correct. In fact it was missing only missing

```
   frametables = new_frametables
```

There is no need to move the last expressions into the if branches (frametables is correctly NULL at that point in the first branch)

Sorry for the bug, it seems that I introduced it while renaming things in the patch https://github.com/chambart/ocaml-1/commit/3fdaf0224a7776ceaef4c1779bc8a9ec9903f247#diff-3c7717e893a739a54e5fbc92ec4b7100L148

**Comment by alainfrisch** [comment]
> frametables is correctly NULL at that point in the first branch

I don't understand.  Since frametables is NULL,  `tail->next = frametables` will set `tail->next` to NULL, but tail still points to the last new frametable;  this will in effect remove previous frametables from the linked list.  Or did I miss something?

**Comment by chambart** [comment]
Effectively, sorry...

**Comment by xavierleroy** [comment]
Is this solved to everyone's satisfaction?  If so please close this PR as well as PR#156.

**Comment by alainfrisch** [comment]
I closed #156, but for some reason, I don't see a "Close" button on this one.

**Comment by gasche** [comment]
It is automatically considered closed (in fact "Merged") since you merged the corresponding patch -- this PR does not appear in the list of open PRs anymore.

**Comment by alainfrisch** [comment]
Ah thanks, I was confused by Xavier's request.

**Comment by xavierleroy** [comment]
My bad, I was probably looking at an outdated Web page generated by Github.

**Pull request merged**
