### PR TITLE
[minor fix] add -dshape option to ocamlopt, not just ocamlc

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by gasche** [comment]
Currently both `ocamlc -bin-annot` and `ocamlopt -bin-annot` compute shapes, but only `ocamlc` supports `-dshape`, this is a minor bug.

**Comment by Octachron** [comment]
Should we also add `-dshape` to `ocamlnat`, since it is supported by `ocaml`?

I should also try to apply the step 2 of my simplification plan for `main_args` at some points to remove the duplication in the argument lists too.

**Comment by gasche** [comment]
Sure, I added it to `ocamlnat` as well, thanks.

**Review by Octachron — APPROVED** [review]
Thanks!

**Comment by gasche** [comment]
Thanks! I'll go ahead when the CI agrees, merge and backport to 4.14.

**Comment by gasche** [comment]
(Cherry-pick to 4.14 in 9886564f47ffedaee2014868f7b281ccff352ed8 )

**Pull request merged**
