### PR TITLE
Extension of "record with" to allow deep field assignment like: { r with f.g.h = e }

### PR DESCRIPTION
**Pull request by rbardou**
This proposal allows writing:

```
{ r with f.g.h = e }
```

instead of:

```
{ r with r.f = { (r.f) with g = { (r.f.g) with h = e } } }
```

It works for an arbitrary depth.

This is implemented entirely in the parsing phase, as a syntactic sugar.

Issue 1: warning 23 is raised when writing `{ r with a.f = 5; b.f = 6 }` if `r` has two fields, `a` and `b`. I don't think one can fix that without propagating changes to the typed phase. But I don't think it's worth the trouble.

Issue 2: `r` is required to be an identifier when deep fields are used. Otherwise, the expression would be evaluated several times, which is probably not what the user wants. To fix this, I could introduce a let-binding, but I don't know how to choose a fresh identifier…

### CODE REVIEW

**Comment by Octachron** [comment]
I also like the idea of the extension but I am not so convinced by the implementation. Is there a specific reason why this extension is implemented as syntactic sugar at parsing time rather than during the translation to lambda terms?

**Comment by rbardou** [comment]
The reason I implemented this as a syntactic sugar is to make it simpler; I was thinking that the type-checker did not need to know. I was surprised by warning 23, but I thought I would propose the idea before changing anything and see people's opinion. No point in adding an AST node if the language extension is liked by nobody :)

I can of course propagate the change to the parsetree so that the type-checker can do the expansion itself. It should allow to get rid of warning 23 and would probably help with issue 2, as I'm guessing that it's easier to introduce fresh identifiers during typing. It would also maybe allow some future extensions like expansion points, I don't know.

This was my first pull request and did not really know what was expected. I'll update the changelog and tests, and I'll add comments. I saw almost no comment in parser.mly so I just kept the same style, but I'm happy to add more!

**Comment by rbardou** [comment]
Oh and yeah I totally forgot about issue 3, which is more important than issues 1 and 2: your example, { r with x.f = ...; x.g = ... }, does not pass the type-checker. Here I was also planning on first gauging the interest before doing anything. Of course if one is to accept this the only reasonable semantics seems to be { r with x = { f = ...; g = ... } }.

The problem is that we may need to reorder some field definitions, and thus the order of evaluation. I don't known if that is a problem. Is the order of field evaluation specified officially? Once again we can add let-bindings to enforce a specific order, if needed.

**Comment by rbardou** [comment]
It's my fault, I should have made it more clear!

**Comment by agarwal** [comment]
> Perhaps we should add to Contributing.md that a prefix of “[WIP]” should be added in the title.

Or use labels.

**Comment by rbardou** [comment]
I started working on a version which is not just syntactic sugar. It is available in another branch:
https://github.com/rbardou/ocaml/tree/deepfields

As expected it is more complicated to implement this way. I'm about at the same point as before:
- warning 23 is still here when it should not;
- nothing prevents you from writing `{ (f ()) with x.y = ... }` causing `f` to be evaluated several times (I plan on disabling it as in the previous patch, unless you know of a way to easily introduce a local let-binding with a fresh identifier?);
- `{ ... with f.x = ...; f.y = ... }` still causes a type-error as fields are not merged.

There is something new though: I generalized a bit, to simplify the implementation, and it means that one may now write:

```
{ f.x = 5 }
```

instead of:

```
{ f = { x = 5 } }
```

As fields are not merged this is not very useful unless the subrecord has only one field, but I think it is an interesting extension as well. Once/if merging is introduced one will be able to write an e-mail header like this, for instance:

```
{ contact.mail = "me@host.com";
  contact.name = "Me";
  contact.username = "me";
  subject = "Hello" }
```

What do you think?

**Comment by lefessan** [comment]
I don't remember much code that would benefit from such an extension `{ x with x.f.g = E }`. Could you point us to some OCaml projects (github files) that would benefit from it ?

The second version extension `{ contact.mail = E; ... }` seems much more interesting, although actually more verbose, since `contact.` has to prefix all labels.

**Comment by rbardou** [comment]
One example is games, when one decides to use immutable data structures (which allow some interesting features like replaying a game more easily). The state is a record of records of records, and updating is done using `{ ... with ... }`. For instance:

```
{ state with player = { state.player with position = { state.player.position with x = state.player.position + 1 } } }
```

There is always a way to write it differently of course, like:

```
let move position = Vector.(position ++ (1, 0)) in
let update_player player = { player with position = move player.position } in
{ state with player = update_player state.player }
```

But it will never be as concise as:

```
{ state with player.position.x = state.player.position.x + 1 }
```

I mention games because there is an example in Fury Puyo (https://forge.ocamlcore.org/plugins/scmdarcs/cgi-bin/darcsweb.cgi?r=furypuyo/furypuyo;a=headblob;f=/game.ml). This file has a lot of `{ ... with ... }` and one of them is nested, towards the end. My recent projects have more examples but none of them is available online, sorry.

**Comment by bluddy** [comment]
I strongly support this. It's especially useful for applications with many hierarchical levels of state, such as simulators and games, but any program that refactors to do serious hierarchical state management and localization (mutable or immutable) could heavily benefit from this change.

**Comment by alainfrisch** [comment]
FWIW, we had exactly this extension in LexiFi's local version of OCaml for some time, also implemented purely in the parser.  We got rid of it because it was useful in a few cases, but not enough to justify the extra maintenance efforts (merges with upstream OCaml), and the implementation in the parser was not very satisfactory (as you noticed).

Ensuring that the "original" record expression is evaluated only once seems necessary for inclusion of the feature, and restricting to pure expressions only is not satisfactory (even though allowing only identifiers would be ok in practice).  This is certainly worth some extra efforts to avoid introducing a weird corner case in the language.  As for preserving a natural evaluation order, this would be nice but much less critical in my opinion.  The cleanest approach would probably be to keep the new form even in the Typedtree and treat it directly when mapping to Lambda;  this is obviously much more difficult since the type-checking logic for records is not so trivial, but perhaps this is still the way to go (expanding the syntactic sugar at the Typedtree level already amounts to some form of code generation, which should not be done there).

Also, one tricky aspect of the feature is that it makes it less visible which sub-records are copied, which is important in presence of mutable fields.  I wonder if one should do something about it (disallowing implicit copying of sub-records with mutable fields?).

**Comment by rbardou** [comment]
Thank you Alain for your insights. It's nice that you already experimented with this before!

I agree that propagating to the code generation phase sounds cleaner. I took some time to look at what should be done to have this, but it seems rather tricky. As you say, the type-checking logic for records looks very easy to mess up, and I'm not so confident about this. Also, there are some arguments to be made for desugaring during the type-checking phase.

Indeed, the code for merging labels together kind of needs to be done during type-checking anyway, notably to check for duplicates such as `{ f.x = 1; f.x = 2 }` or even `{ f = 1; f.x = 2 }`, and to check for warning 23 correctly. So even if we push towards code generation, this part of the code generation should probably be done while type-checking.

Also, it seems more modular to expand before type-checking. This way, the type-checking code can be split in two: first, desugar deep fields, then, type records normally. This makes it easier to understand and maintain, as the two are independent. If we want to push towards code generation the two would no longer be independent. We would be typing a tree of labels instead of a list, and that would propagate rather far.

From what I can see, there seems to be no big problem with this approach of expanding during type-checking, except that code generation would be performed in the wrong compilation unit. I don't know how much of a show stopper this is?

So for now I continued with the simple approach. I added a new patch in the other branch ( https://github.com/rbardou/ocaml/tree/deepfields ) which contains the merging part. One may now write:

```
type vector = { x: int; y: int }
type player = { position: vector; speed: vector }
type game = { player: player; adversary: player }

let move player =
  { player with
    position.x = player.position.x + player.speed.x;
    position.y = player.position.y + player.speed.y }

let initial_game =
  { player.position.x = 100;
    player.position.y = 200;
    player.speed.x = 0;
    player.speed.y = 0;
    adversary.position.x = 100;
    adversary.position.y = 200;
    adversary.speed.x = 0;
    adversary.speed.y = 0 }
```

The merging code performs the check for duplicate fields. There was a comment that the previous duplication check should probably be done elsewhere anyway.

Now I need to fix warning 23 (not that easy actually but I have some ideas to do it without rewriting everything) and the issue of evaluating the expression only once.

**Comment by alainfrisch** [comment]
Minor technical "concerns" with doing the expansion during type-checking:
- It becomes harder to define the evaluation order.  We probably don't care.
- The information is lost in the Typedtree (and so in .cmt files), and locations for sub-records might be quite bogus (possibly giving badly located error message?).

**Comment by rbardou** [comment]
Good points!

If I remember correctly, fields are sorted by index during typing by type_label_a_list, so I guess this defines evaluation order in a way which is relatively simple to understand. Even if evaluation order is unspecified officially, at least existing code which relies on a specific order should not break.

I tried to be careful about keeping reasonable locations when expanding, but obviously it is not possible to have a clean location for a subrecord which does not actually exist in the code. But it reminds me that there is room for improvement regarding error messages. For instance, in:

```
{ f.g.x = 5; f.g.x = 6 }
```

It says that field `x` appears twice, but it would be better to say that field `f.g.x` apears twice.

**Comment by mshinwell** [comment]
This pull request has been inactive for more than a year and I don't see especially strong support for it.  @alainfrisch seems to suggest there are various potential corner cases of this feature---do these actually require sufficiently much work to resolve in a coherent and understandable manner that the effort outweighs the benefit of this change?  The ongoing maintenance effort and extra complication of the code also needs to be thought about.  Is it really worth it?

Specifically regarding two points above: my view is that we should avoid cases which make the evaluation order hard to think about if possible.  Preservation of location information is also becoming increasingly important with more sophisticated debugging tools.

As regards the examples above: I don't find the use cases particularly convincing, as they appear to demonstrate somewhat of a lack of abstraction in the code.

**Comment by rbardou** [comment]
I kind of gave up because the changes required to make the feature available in the AST and typed tree instead of being a simple syntactic sugar are hard to implement, especially because the existing code for records is already quite complicated.

I agree with your points regarding evaluation order and location preservation.

Regarding lack of abstraction, I see what you mean (the vectors in the example above are usually better written as a type Vector.t with an operation Vector.(++), for instance). But when I wrote this patch I had a really practical case. It was an implementation of an existing protocol, with a lot of information in messages organized in a hierarchical way. The hierarchy followed the protocol specification. All I did with this hierarchy was create values, update some deeply nested fields, and read some other values. Updating was a pain and no abstraction would have helped. Unfortunately the code is not open-source so I can't share it.

**Comment by gasche** [comment]
Lenses are a way to abstract over get/set functions that allow to build "deep field update" from functional combinators. See for example Tim McGilchrist's blog post [Lenses in OCaml](http://lambdafoo.com/blog/2015/01/16/ocaml-lenses/).

For the record (no pun intended), I like the proposed syntax extension and I think there is a very clear semantics for what its semantics should be:

- the evaluation of subexpressions should be left-to-right
- duplicate assignments to the same subfield path should be forbidden

I don't see any difficulties there, and the implementation also seems clearly determined: at each level, group all assignments to each subfield together and this tells you (recursively) how to update a sub-record (with the common subfield removed from the paths). When you end up on a group of empty paths, `[] = e1; [] = e2; ...`, you know from the "duplication forbidden" invariant that there is a single assignment `[] = e` and you return `e`.

It is believable to me that this would not be so useful in practice -- altough I find the research on [copatterns](http://lambda-the-ultimate.org/node/4818) a nice reminder that field nesting deserves to be taken seriously -- and that nobody will thus bother to provide a proper implementation.

**Comment by mshinwell** [comment]
@gasche Well, left-to-right evaluation is exactly the opposite of what usually happens ;)
I think @alainfrisch 's point about mutability is important too.

**Comment by alainfrisch** [comment]
> I don't see especially strong support for it. 

FWIW, I think it would be a very nice addition if the identified issues are fixed and one finds a nice implementation strategy.  I mentioned that we dropped a similar local extension at LexiFi, partly because of the drawbacks related to maintaining a local patch that also had all the reported issues, and also because we did not find many use cases.  For some reasons, we have more and more such cases, and as a language user, I'd be strictly (a bit) more happy if the language had this feature.

Could this be an opportunity to streamline a bit the implementation of record type-checking?

**Comment by bluddy** [comment]
I personally think this is a great feature to include in the language, if we can get it right. As far as I can tell, the main paradigm for modern OCaml programming is to have a global state object that is passed around between functions, and which contains layers of inner records for the entire application. Some of these records may be updated via monads, but in general, updating records is one of the most common operations any state-based application (ie. not compilers or parsers) will be doing, and it's a good idea to optimize this operation.

**Comment by OvermindDL1** [comment]
As a user that at times has very deeply nested records due to storing library state, I would *love* this feature.

**Comment by alainfrisch** [comment]
Let's close this PR.  We discussed it during today's dev meeting, and while the feature is pretty nice, the current implementation approach does not seem adequate.  Feel free to open a Mantis ticket to record the feature request, in case anyone wants to work on a different implementation.

**Comment by gasche** [comment]
Done: [MPR#7491](https://caml.inria.fr/mantis/view.php?id=7491).

**Pull request closed without merging**
