### PR TITLE
ocamltest: allow TEST block at end of file

### PR DESCRIPTION
**Pull request by damiendoligez**
Following up to the discussion in #9871, the patch is rather short.

Let's have a discussion on whether this is a good idea.

### CODE REVIEW

**Comment by dra27** [comment]
I think it's the case that if you included a `TEST` block at the top _and_ bottom that this would quietly ignore the one at the top?

I would prefer it still to be the case that there must be a `TEST` block at the top, but have an instruction which tells the lexer to keep scanning to the bottom of the file. e.g.

```
(* TEST_AT_EOF *)
...
(* TEST
actual commands
*)
```

I don't think that lexer would be too much more complicated.

**Comment by dra27** [comment]
Having also had to alter some of these before, I wholeheartedly approve of anything which reduces noise on these reference files, given the obvious risk of promoting a reference file without meticulously checking the line number changes!

**Comment by gasche** [comment]
I agree with @dra27 that it would be nice to have a marker at the top. I would propose `TEST_AT_THE_END` instead of `TEST_AT_EOF` (EOF is jargon).

**Comment by dra27** [comment]
> I would propose `TEST_AT_THE_END`

Shall we have a full stop at the end? 😉

**Comment by gasche** [comment]
Can we make progress on this issue?

- @dra27 and myself agree that it would be useful to have a short header to announce that the header is at the end; call it TEST_AT_EOF, TEST_AT_THE_END or whatever you prefer.
- I realize now that @shindere was not cced on the issue yet, he may want to look at the implementation.

**Comment by shindere** [comment]
I was not aware of this, indeed.

Can't review today but will do so at the very beginning of next week.

**Comment by damiendoligez** [comment]
@dra27 I've implemented your suggestion and the code is even simpler. For the marker I've settled on `TEST_SCRIPT_BELOW` because the actual test block can be anywhere in the file.

**Review by gasche — APPROVED** [review]
The code is very simple and the feature is useful, thanks! Approved.

**Comment by shindere** [comment]
I like the idea, thanks.

I just wold like to nitpick about the names.

The test blocks begin with

```
(* TEST
```

`SCRIPT` is never mentionned.

So, in my opinion, the token used to declare that the test will come
furthershould rather just be:

```
(* TEST_BELOW *)
```

Without the mention of `SCRIPT` which looks gratuitous to me.


Would you mind changing this, please?

Also, the names of the tokens marking the begin and end of the test
block should keep the same name, I think.

**Comment by gasche** [comment]
> Also, the names of the tokens marking the begin and end of the test
block should keep the same name, I think.

I don't understand, what do you mean here?

**Comment by shindere** [comment]
Gabriel Scherer (2021/04/29 09:24 -0700):
> > Also, the names of the tokens marking the begin and end of the test
> block should keep the same name, I think.
>
> I don't understand, what do you mean here?

Goign through the patch I got the impression that the tokens that were
used to mark the begin and end of test block got renamed but maybe I'm
wrong on that one?

**Comment by damiendoligez** [comment]
@shindere 
>Goign through the patch I got the impression that the tokens that were
used to mark the begin and end of test block got renamed but maybe I'm
wrong on that one?

IIRC there were new ones added in the first version of this patch, but this is not the case anymore.

**Comment by damiendoligez** [comment]
I followed @shindere's solution and changed the keyword to `TEST_BELOW`. I'll merge soon assuming everyone finds this choice palatable.

**Comment by dra27** [comment]
LGTM!

**Pull request merged**
