### PR TITLE
[doc] Fix: String.{starts,ends}_with introduced in 4.13 (not 4.12)

### PR DESCRIPTION
**Pull request by thierry-martinez**

### CODE REVIEW

**Review by Octachron — APPROVED** [review]
Thanks for the fix!

**Review by gasche — APPROVED** [review]
Looks good to me.

@Octachron this looks like something to cherry-pick in the 4.13 release branch, right?

**Comment by Octachron** [comment]
@gasche : this ought to be cherry-picked indeed.

**Comment by Octachron** [comment]
Cherry-picked on 4.13 as edbeb95e372e1 .

**Pull request merged**
