### PR TITLE
Alternative fix for statmemprof tests in `-disable-flat-float-array` mode

### PR DESCRIPTION
**Pull request by jhjourdan**
This is an alternative fix for the bug in #9371.

### CODE REVIEW

**Comment by jhjourdan** [comment]
This requires no change entry.

**Comment by jhjourdan** [comment]
Note : this also include a trivial fix in test comballoc.ml.

**Comment by jhjourdan** [comment]
Anyone for reviewing this PR? It is rather trivial, and should be merged in 4.11 as a bugfix.

**Review by stedolan — APPROVED** [review]

**Comment by jhjourdan** [comment]
Would somebody consider merging? @gasche?

This is a bugfix, this should be integrated in 4.11. And this is low-risk, since it only affects the test suite.

**Comment by stedolan** [comment]
I'm happy to merge & cherry-pick, but there's now a conflict because I've just merged #9096 that changed the backtrace format. Can you verify that these tests are still OK and push the new reference files?

**Comment by jhjourdan** [comment]
Thanks. This should be OK now.

**Comment by stedolan** [comment]
Merged and cherry-picked in 068c314edf53276dd2c34ab9b5ca07f94b315901

**Pull request merged**
