### PR TITLE
get rid of compare_val in String.concat

### PR DESCRIPTION
**Pull request by ygrek**
apparently `ensure_ge` is not inlined :(

### CODE REVIEW

**Comment by dra27** [comment]
Thanks! @damiendoligez - given that it's just a type annotation, can this go in 4.05??

**Comment by dra27** [comment]
@ygrek - is it inlined in flambda?

**Comment by alainfrisch** [comment]
Are we sure this was related to the lack of inlining, rather than to the fact that type-based specialization of primitives occur before inlining?

**Comment by damiendoligez** [comment]
@dra27 OK for cherry-picking to 4.05, if you manage to slip it in before #1228 is merged.

**Comment by xavierleroy** [comment]
@alainfrisch is right, type-based specialization occurs before inlining.  So, for the time being, type specialization "by hand" is the only way to improve the generated code.

**Comment by ygrek** [comment]
@dra27 I don't know, and my guess about inlining was wrong anyway

**Comment by bluddy** [comment]
I would expect flambda to do well here, since it iterates over the process of inlining/type specialization/lifting etc for several rounds (unless I'm mistaken).

**Pull request merged**
