### PR TITLE
Add Functor, Applicative, Monad, Identity, and Option modules

### PR DESCRIPTION
**Pull request by alan-j-hu**
Monads are a frequent used in functional code, including several third-party OCaml libraries, such as Jane Street's alternative standard libraries and Lwt. I am proposing the addition of monads, along with functors and applicatives, to the standard library, to provide a uniform interface. As the Monad module uses the more generalized monad transformers, I am also including an Identity module for the identity monad. Finally, I am including an Option module that demonstrates use of the Functor, Applicative, Monad, and Identity modules and provides convenience functions that may be used instead of pattern matching the option value.

The Functor, Applicative, and Monad modules follow the standard library's pattern of having a signature S as well as a functor Make, which in this case derives functions given a minimal definition.

One bikeshedding issue is that "functor" in OCaml means "higher-order module," and having a Functor module with the Haskell definition may cause confusion. Perhaps Functor could be renamed to Mappable?

I am considering the addition of an infix map operator. In Haskell, the operator is `<$>` as a reference to the `$` operator. OCaml's equivalent to `$` is `@@`, so should the infix map be named `<@@>`, or is this name too long to be convenient?

I am also considering the addition of Kleisli composition to the Monad module. What should the function be named? Haskell uses `>=>` and `<=<`, but I suggest the more descriptive names `compose` or `compose_m`.

### CODE REVIEW

**Comment by mseri** [comment]
I had a brief look for curiosity. It‘s nice and simple but I think the documentation should be way more detailed and probably it would be good to provide usage examples.

As much as I like these higher constructions, in OCaml they are not as essential as in Haskell and many people could be not used to them and their meaning. Look for example at how extensive is the documentation of the monad module in [bap](
https://github.com/BinaryAnalysisPlatform/bap): 
https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/monads/monads.mli

I think the lack of combinators for certain types provided by the standard library is an annoyance (like having to require `rresult` to be able to have combinators for the `result` type or having to write the ones for the `option` type all the time, unless you want to rely on one for the standard libraries) but I am not convinced these algebraic constructions should be in the ocaml standard library yet (maybe we should wait to see how things need to change with effects, modular implicits and the new flambda):

- there is a clash of names and meanings, that may require rethinking the interface
- there is the issue of precedence of the operators, that depends on the character used instead of being associable to each operator
- there is a question of “balance”, in the sense that one could go all the way and have a comprehensive interface like https://github.com/IndiscriminateCoding/clarity or keep it small. In this case I think we should make it a bit more comprehensive than what it is and consider what from e.g. Semigroup, Monoid, Foldable, Traversable and Alternative to include. And add the various implementations for Options, Results, Lists, Arrays, Hashtables and Maps.
- there is a question of overhead if we swap the current implementation with implementations that are behind multiple levels of indirections (maybe it‘s not a problem, I am not an expert)

I only had a brief look and that is what came to mind. Also, if the common feeling is that we should integrate it to the standard library, it would probably be good to review Base, Core, Containers and Batteries to see what they all implement and how. And find what interfaces and helpers are more commonly used/required.

**Comment by alan-j-hu** [comment]
Okay, I have added a map operator, `<@@>`, and Kleisli composition functions, `compose_before` and `compose_after`.

**Comment by alan-j-hu** [comment]
Mr. Seri,

Thank you for your feedback. I'm sorry for not responding sooner. I just checked my email today. (A fault that I will fix is me not checking my email enough.) I checked my PR discussion page every day, but for a reason that I don't yet know, your reply does not appear on GitHub for me.

> As much as I like these higher constructions, in OCaml they are not as essential as in Haskell and many people could be not used to them and their meaning. Look for example at how extensive is the documentation of the monad module in [bap](https://github.com/BinaryAnalysisPlatform/bap):
> https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/monads/monads.mli
>
> I think the lack of combinators for certain types provided by the standard library is an annoyance (like having to require rresult to be able to have combinators for the result type or having to write the ones for the option type all the time, unless you want to rely on one for the standard libraries) but I am not convinced these algebraic constructions should be in the ocaml standard library yet (maybe we should wait to see how things need to change with effects, modular implicits and the new flambda):

In terms of evaluating the changes to the standard library, I think that it's worth separating the addition of Functor, Applicative, and Monad interfaces from the addition of an Option module, as the former is more radical than the latter. My main impetus to make this PR is my annoyance at the lack of functions to abstract away pattern matching over optional values, and I figured that if I was going to implement the functions in a PR, I ought to be thorough and officially define functors, applicatives, and monads. As an added benefit, by defining monad transformers and the identity monad, the standard library gets the identity function via the identity monad's return and function composition via its Kleisli composition. However, perhaps option deserves a module, but functors, applicatives, and monads don't?

> - there is a clash of names and meanings, that may require rethinking the interface
> - there is the issue of precedence of the operators, that depends on the character used instead of being associable to each operator
> - there is a question of “balance”, in the sense that one could go all the way and have a comprehensive interface like https://github.com/IndiscriminateCoding/clarity or keep it small. In this case I think we should make it a bit more comprehensive than what it is and consider what from e.g. Semigroup, Monoid, Foldable, Traversable and Alternative to include. And add the various implementations for Options, Results, Lists, Arrays, Hashtables and Maps.
> - there is a question of overhead if we swap the current implementation with implementations that are behind multiple levels of indirections (maybe it‘s not a problem, I am not an expert)

- By "a clash of names and meanings," are you referring to the meaning of "functor" or something else that I'm missing? If the former, what do you think of the name "Mappable?" On a tangent, I'd like to remark that "map" has a name clash between the dictionary data structure and the structure-preserving operation of type (a -> b) -> f a -> f b, yet programmers that use both meanings of map don't seem to be confused, even when the OCaml standard library defines a map function for maps!

- All the operators that I have introduced start with > or <, so they are left-associative and have a precedence as described here: http://caml.inria.fr/pub/docs/manual-ocaml/expr.html. As a comparison, in Haskell, >>=, <*>, and <$> are all left-associative, with <*> and <$> binding tighter than >>=. I don't see the precedence as an issue; the worst inconvenience is the need for parentheses, which aren't even necessary when chaining the same operator. I'd say that explicit parentheses can also be seen positively, and the fact that the OCaml operators all have the same precedence makes OCaml's treatment of them during parsing easier to remember than Haskell's treatment of them.

- I am personally open to having more "typeclass" style interfaces, but I think that the discussion and decision should be made by the OCaml developers, not me. (Unless, of course, you are addressing this email to everyone in general. I'm replying to it as a conversation between us only because it isn't appearing on GitHub, at least for me, and I haven't received any other responses, either on GitHub or in my email.) If this PR gets approval, I will definitely make modules such as List and Array conform to the monad interface.

- When I wrote the auto-derivation of the interface, I did have concerns about efficiency. For example, maps over lists would be defined by creating lists of length one via monadic bind and then concatenating them, as opposed to simply iterating over the list. As a comparison, Jane Street's standard library has an option for providing a custom map implementation. I was thinking of having multiple functors that derive their interfaces from different user-supplied definitions. With the PR in its current form, to override the default implementation, users would simply define the module members themselves rather than writing `include <output of deriver functor>`, at the cost of having to explicitly define the members that do use the deriver functor's definition. One solution for this ergonomics problem would be the ability to include a module (or signature) while listing members to exclude, but perhaps this idea belongs in another discussion. The indirection overhead from monad transformers could perhaps be alleviated by defining the identity monad's map and <@@> functions as external functions that use the primitive OCaml function application instruction "%apply," and bind as the primitive instruction "%revapply." I'm also not an expert on the OCaml internals, so I don't know what would be optimized away.

Additionally, do you happen to know why I'm not seeing your response on GitHub? I apologize in advance if the reason is something that I should have known. In the case that I'm not the only one who can't see your reply on GitHub, I definitely think that it deserves to be public on GitHub and read by others.

Many thanks,
TheAspiringHacker

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dbuenzli** [comment]
Personally I'm against adding these kind of abstract constructs to the stdlib. 

Trying to discover the algebraic structures underlying the problems you are solving is certainly a good idea, but I have never been fond of the idea that you should give generic names (`bind`, `pure`, `return`, etc.) to refer to those; use the ones that are appropriate for your problem domain. I also find the structuring power of monads to be rather limited in practice as they do not compose well (I don't consider monad transformers a proper solution to the problem).

Other than my concerns about monads in general, as a programmer adding what you propose can buy you two things:

1. The ability to functorize your code over a monad. I.e. write monad-generic code.
2. The ability to produce a few generic combinators given the base monad definition.

I'd say 1. is highly unlikely, most of the things you do with a monad remains tied to its underlying semantics. 2. here you run again in the problem of generic names which could be better served by domain specific ones, besides the code is actually saves you is generally quite trivial.

**Comment by gasche** [comment]
@dbuenzli, I have a somewhat different take on your advantage (2). When you try to write monadic code in OCaml (for example, there are parts of the compiler codebase that I would like to rewrite in a CPS monad), you find out that:

1. The library functions that you would like to use do not offer monadic versions (fold -> foldM, map -> mapM, etc.), making it subtle and inconvenient and bloated to port code to a monadic style, and
2. Outside libraries that provide those monadic combinators exist, but they all use slightly different signatures so you are not sure which one to pick.

I think that having a standard monad signature would alleviate those problems, which makes more of a difference than what you say. That said, I'm not sure the functorized style we would have to use to provide those monad-generic functions today is convenient enough to be used in practice, so to some extent the monadic liberation may be blocked on having some form of implicits /  type-classes.

**Comment by dbuenzli** [comment]
> I think that having a standard monad signature would alleviate those problems, which makes more of a difference than what you say.

I don't think that adding a standard *minimal* monad signature would alleviate the problem you mention. You could say the monad signature should be larger and impose your view about what it should be but then what ? you only define foldM on `list`s ? That seems a bit limited.

> That said, I'm not sure the functorized style we would have to use to provide those monad-generic functions today is convenient enough to be used in practice, so to some extent the monadic liberation may be blocked on having some form of implicits / type-classes.

Since that won't solve the monad composition problem, I don't see a clear liberation here but in any case note that the liberation you are seeking for can be done without functors, using first-class modules arguments (basically explicit dictionary passing). 

So you could provide these via a `Foldable.S`, `Monad.S` signatures and `Monad.fold` values  rather than through a `Monad.Make` application.

Adding minimal *signatures* might make sense to make it easier to write such functions (which would be useful even if monadic instances do not refer to them). I do however remain unconvinced about adding the functors that derive the various menagerie of operators and derived functions.

**Comment by xavierleroy** [comment]
As a matter of general policy, proposals such as this PR should be discussed and worked out first in an external library (preferably Core or Batteries, as those have good dev teams and good user bases) before being proposed for inclusion in OCaml's standard library.

As a matter of personal opinion, I think Functor, Applicative, Monad, Identity are largely useless without type classes or modular implicits or similar inference mechanism.

**Comment by nojb** [comment]
The consensus from the previous discussion is that, absent a suitable inference mechanism, the programming style imposed by these interfaces is not a natural one in OCaml. Hence, for now at least, there isn't enough support to have this merged.

**Pull request closed without merging**
