### PR TITLE
Add ocaml manuals in the repository

### PR DESCRIPTION
**Pull request by bobot**
It adds the source of the ocaml manual in a `manual` subdirectory. The last commit fe318c9719c751f529209afa48d7218eebd1c5e5 of this branch simplifies a little the build of the makefile since we know where the ocaml source are.

The step used:
1. Clone the git mirror of the ocaml manual https://github.com/ocaml/ocaml-manual
2. Move, for all the history, the files inside the `manual` directory by running `git filter-branch --index-filter $(pwd)/filter_branch.sh`.
3. Add this clone as a remote of an ocaml repository
4. Fetch this remote. Git could warn that there is no commit in common.
5. Merge the new remote branch

The script `filter_branch.sh` is:

``` shell
#!/bin/sh -eu

git ls-files -s -z | sed -z -e "s-\t\"*-&manual/-" | \
     GIT_INDEX_FILE=$GIT_INDEX_FILE.new git update-index -z --index-info

if test -e "$GIT_INDEX_FILE.new"; then mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"; fi
```

### CODE REVIEW

**Comment by gasche** [comment]
I will merge if we can get someone else to test the branch and confirm that it also works for them.

**Comment by Octachron** [comment]
It works for me; at least it build and the pdf manual looks fine at first glance. There was however a minor caveat: building `make all` before `make tools` generates an empty `manual/allfiles.tex` that messes up ulterior compilations. It may be not really problematic but it took me several minutes to figure what was happening; so it might be worthwile to correct this behavior at some point. 

Partially related, an explicit licence for the manual could be nice; at least to clarify that forks of the
manual are not copyright violations.

**Comment by gasche** [comment]
Thanks for the testing and the judicious question about the license. I checked with @xavierleroy , there is in fact a license hidden in [foreword.etex](https://github.com/ocaml/ocaml-manual/blob/6254779f9eab3590c10f72b8cce07edd849ef772/manual/foreword.etex#L48-L66) (so it is visible in the rendered document). I agree a more explicit LICENSE file at the root of the project would be better -- and, while we're at it, maybe moving to a more convenient Creative Commons license could be nice.

**Comment by gasche** [comment]
Maybe one thing we could do is to add a 0-th item in the Building section of [the modified manual README](https://github.com/bobot/ocaml/blob/add_ocaml_manuals/manual/README.md) to request that the OCaml distribution itself be installed already, and add a second N.B. in the same section to describe @Octachron's issue (and hopefully a fix: is `make clean` in the manual subdirectory enough to get out of trouble?)

**Comment by Octachron** [comment]
I just wanted to confirm that a `make clean` is indeed enough to get out of trouble. 

I also agree that explaining the current shortcomings of the building process is a good first step. Moreover, I am not sure if replacing the current tools by latex package would be worthwhile, since any TeX black magic used  by the package would need to be reimplemented on the hevea side.

**Comment by gasche** [comment]
@xavierleroy : I added a [LICENSE](https://raw.githubusercontent.com/ocaml/ocaml/88a4f088cd6265684f83cbca12e39f367d4eea03/manual/LICENSE) file directly extracted from the foreword.etex license. Feel free to eventually change it to something else.

**Comment by bluddy** [comment]
Sorry for exhuming this old PR. I'd like to ask if it's possible to change the manual to a more liberal license. Some people in the community may be interested in creatively contributing to the manual or trying out different documentation presentations, but are turned off by the restrictive license.

**Comment by gasche** [comment]
I had a discussion about this with other developers. Personally I agree that a less restrictive license would be better (CC-by-sa was mentioned), but we would need to get agreement from the authors, and more importantly we need to retrace and understand the rationale for adding these restrictions in the first place. We are going to ask the people who made this choice decades ago, but it may take a bit of time -- and if the effort ends up higher than most people care, it may stop there, so please don't get your hopes up.

**Comment by nojb** [comment]
> I had a discussion about this with other developers. Personally I agree that a less restrictive license would be better (CC-by-sa was mentioned), but we would need to get agreement from the authors, and more importantly we need to retrace and understand the rationale for adding these restrictions in the first place. We are going to ask the people who made this choice decades ago, but it may take a bit of time -- and if the effort ends up higher than most people care, it may stop there, so please don't get your hopes up.

This message (and the thread it is in) may be relevant: https://inbox.ocaml.org/caml-list/07e8a536-984b-850b-6dec-2c30ea0cfb2d@inria.fr/

**Pull request merged**
