### PR TITLE
Flambda trunk

### PR DESCRIPTION
**Pull request by lefessan**
Here is the branch of Pierre Chambart containing an improved optimization pass, called flambda. We are looking for testers and reviewers to help for its integration in trunk !

### CODE REVIEW

**Comment by alainfrisch** [comment]
I've had a very quick look at the code.  Here are some first (random) questions:

 - Why are flambda and related moduled in bytecomp/ and linked in ocamlc?

 - What's the relative responsibilities of flambda and clambda concerning cross-module inlining/constant folding/etc?    Since cmx_format is extended with flambda-related information, do we need to keep the clambda approximation as well?

 - Is there a real purpose in keeping both flambda and clambda?  They seem conceptually very close, witnessed by the simplicity of the mapping between them.

 - As already discussed on caml-devel in March 2014, I'm wondering what it would take to also merge lamba and flambda, i.e. enrich lambda to be able to express closure conversion in it.  I see some uses in being able to use the same code for optimizations in lambda and in flambda.  Applying higher-level optimizations to bytecode is not completely useless: think about js_of_ocaml.

 - Also already discussed:  flambda seems to keep informative meta-data (such as unit for closure elements, or vc_fun) which are not really required.  I'd prefer to have a tighter definition, for which it is possible to attach a semantics to each field.

 - cl_free_var: if it is still the case that the flambda in the map are always variables, I'd prefer to materialize this in the type definition.

 - I'm still not convinced by the cl_specialised_arg field.  Isn't it possible to keep the information in a table "on the side" during the optimization, not in the main flambda data structure?

 - In which cases do we need Uconst_ref (_, None)?

 - Do we really need Pset/getglobalfield?  Would it be possible to detect the corresponding pattern directly?

 - What's the purpose of the type variable in the definition of flambda?  Is it really instantiated with different types?  The standard style used in the compiler to attach generic meta-data to each node in AST-like trees is to use a record at each node, with a "desc" field.  Is there a specific reason to avoid this style here?

 - Is the Closure module still used?  If not, it should be removed.

 - Set.Make now exports an of_list function, no need to recreate it.

 - sort_connected_components.ml misses standard headers.

**Comment by lpw25** [comment]
> As already discussed on caml-devel in March 2014, I'm wondering what it would take to also merge lamba and flambda, i.e. enrich lambda to be able to express closure conversion in it. I see some uses in being able to use the same code for optimizations in lambda and in flambda. Applying higher-level optimizations to bytecode is not completely useless: think about js_of_ocaml.

As an alternative to this, how about basing the bytecode off of FLambda instead of Lambda? That way bytecode benefits from optimisations, but we still have a high-level representation to make writing the code generation from ASTs simpler. I think it is important that the AST -> Lambda phase of the compiler is kept simple and maintainable.

**Comment by lefessan** [comment]
Alain, you have tons of questions. Would it make sense to organize a meeting to discuss your questions, and then come back here to discuss what could not be fixed during the meeting ?

**Comment by alainfrisch** [comment]
> I think it is important that the AST -> Lambda phase of the compiler is kept simple and maintainable.

Extending Lambda to support expressing closure conversion in it should not change the AST -> Lambda phase (it wouldn't use the new features).

Basing the bytecode off of flambda is interesting, but the current simplicity of the bytecode compilation chain is also one of its advantages.

**Comment by alainfrisch** [comment]
> Alain, you have tons of questions. 

Indeed, and some of them probably came too early in the discussion.

The most important questions to me, at this stage are:  what's the rationale for introducing a new intermediate language ?  which optimizations cannot easily be expressed on clambda and couldn't we change clambda instead of introducing another language (and try to minimize the less important changes, which would facilitate the review) ?

**Comment by chambart** [comment]
Sorry for the lag, I missed your recent questions.

So as a first quick answer to why adding a new intermediate language rather than using lambda:
Clambda is too low level on a few points to be resonnably used for complex inlining. The main restriction is that it is difficult to keep track of which closure elements comes from where. This information is almost always needed for inlining function containing local function. Provinding higher level closure representations that implies that more transformation is needed when going to cmm. Merging this transformation with cmmgen would have made something quite complicated and really unreadable. It is a lot simpler to do that in two passes and clambda is the right representation for the intermediate step.

Since I was introducing one intermediate language, I could benefit from cleaning/reorganising a few things to be a better representation for some manipulations. One extensive change is the use of `Abstract_identifiers.variable` instead of  `Ident.t`. The main difference with ident is the presence of the original compilation unit in the variable. This was originaly for debugging purpose, but this also proved usefull to be able to share some informations between different cmx files (abstract values can contains references to values from other files).

**Comment by planar** [comment]
I thing we should get @xavierleroy 's opinion on adding another intermediate language.

**Comment by mshinwell** [comment]
Damien, I thought Xavier had discussed this with Pierre, although I may be wrong.

**Comment by drbo** [comment]
I am very excited about this.

One criticism of OCaml is that high-level coding has a performance penalty compared to the same in (say) MLton. This patch should reduce that penalty.

**Comment by gasche** [comment]
We discussed flambda in general in the developer meeting today, and there was agreement on trying to get it in the next release if it is ready on time. Mark was aiming for the 4th of December as a landing date.

**Comment by alainfrisch** [comment]
@gasche Why did you close this PR?  Should we look at another branch?

**Comment by gasche** [comment]
I suspect that the in-development branch is [chambart/ocaml-1#flambda_trunk](https://github.com/chambart/ocaml-1/commits/flambda_trunk), but I am not sure Mark and Pierre are expecting us to pry on their development history. Having a separate "clean" branch for review made sense at some point, but it looks like the release timeline is too short for this to be effective in practice.

I just closed the PR as a issue-handling reaction: my idea is to maximize, among the open PRs, the proportion of those that require review/decisions, in order to direct the attention of interested contributors (core team or external contributors alike). The writing is already on the wall for this one, so I closed it. If you think (even as a mild intuition) that keeping it open is the better thing to do (encourage the miraculous review from someone?), I'm fine with reopening.

**Comment by alainfrisch** [comment]
No, no, I was just wondering.

**Pull request closed without merging**
