### PR TITLE
Make Memprof deterministic

### PR DESCRIPTION
**Pull request by stedolan**
This patch ensures that Memprof-ing the same computation with the same sampling rate yields the same samples. (The lack of this property was annoying when writing a Memprof client - it made it hard to test changes to the callback logic, as the whole trace was different)

The hard part here is making the sampling independent of any allocation done by the callbacks. This bit was already done by @jhjourdan in #9628.

This patch contains the easy part (resetting the PRNG whenever Memprof starts), and a test.

### CODE REVIEW

**Comment by jhjourdan** [comment]
I am not convinced this change is enough to make Memprof deterministic for several memprof runs in the same OCaml process.

Indeed, the status of the minor heap influences how minor samples get renewed. This means that you would need to empty the minor heap when starting Memprof, because the status of the minor heap influences how minor samples get renewed.

> The hard part here is making the sampling independent of any allocation done by the callbacks. This bit was already done by @jhjourdan in #9628.

This statement seems wrong too, for the same reason: the allocations performed by the callbacks can change the status of the minor heap, and hence have an influence on determinism.

In the same order of ideas, the state of the major GC have its influence, since it determines when the promotion/deallocation callbacks get called, and hence when these callback will change the state of the minor heap.

There are probably other pieces of state that need to be reset, but I don't know for now. Probably the action pending flag has a role to play....

**Comment by stedolan** [comment]
Hmm, I think you're right. I'd forgotten about the renew_minor_sample that happens at the end of a minor GC.

I'll leave this lying around for a while in case either of us think of a way to do it easily, but I'll probably close it in a week or two. I don't think this property is important enough to put serious work into attaining it. (I made this patch only because I thought it was easy!)

**Comment by jhjourdan** [comment]
I have thought a bit about that, and I don't think there is an easy way to achieve this goal.

Note, however, that Memprof should be deterministc for several runs of the same program.

**Comment by stedolan** [comment]
> I have thought a bit about that, and I don't think there is an easy way to achieve this goal.

Same!

**Pull request closed without merging**
