### PR TITLE
Fix spelling errors reported by Lintian

### PR DESCRIPTION
**Pull request by glondu**

### CODE REVIEW

**Comment by dra27** [comment]
Thanks for these! The use of "one" in many cases here isn't very idiomatic - better to drop the infinitive instead. See https://github.com/dra27/ocaml/commit/2e71bb6e72b027802d8d645908e58304fdc066c1 for alternatives - does that still pass the Lintian checks?

**Comment by glondu** [comment]
@dra27: Your wording is better (and passes Lintian). I've updated my branch with your changes. I've also added some fixes to ocamldoc, where some error messages were in French... (!)

**Comment by dra27** [comment]
Thanks, @glondu!

@Octachron / @gasche - I wouldn’t normally propose non-docs spelling corrections on a maintenance branch, but on the basis it’s from an automated tool, would these all be ok for 4.08?

**Comment by gasche** [comment]
At this stage in the release process we don't want to merge non-critical changes to 4.08 (it would push us to make another release candidate). We could wait until 4.08.1 is released to merge this, or merge in trunk now and cherry-pick later.

**Comment by hannesm** [comment]
As far as I can see, this has been merged into the 4.08 branch (in contrast to @gasche comment above) -- and should as well be picked to 4.09 and trunk!?

**Comment by gasche** [comment]
Indeed, I have to do the cherry-picking -- done, dfd448fb830a79a06bd35c73de0f463bd577ebd7 in 4.09 and 4c303cc88a511966aa76339c119e7d1bf2f1ac32 in trunk.

**Comment by gasche** [comment]
The reason why we finally merged is that we realized we would have other patches to merge in the preparation of the 4.08.1 release, notably #8830, so I thought we might just as well merge this one -- ordinarily I wouldn't merge this kind of patches in a release branch, but the idea here is that it streamlines the Debian CI process for 4.08, and doesn't cost much on our side.

(In the it may have been a mistake, because #8830 seems sort of stuck for now, but at worst we have to do another RC.)

**Pull request merged**
