### PR TITLE
Genarray.nth_dim: add missing bounds check

### PR DESCRIPTION
**Pull request by nojb**
See [MPR#7705](https://caml.inria.fr/mantis/view.php?id=7705).

### CODE REVIEW

**Comment by gasche** [comment]
Please add a Changes entry with at least yourself and the reporter. (And the mantis PR number and this one, preferably in the right place with respect to MPR ordering, in the "Bug fixes" section.)

I have had a quick look at the file, I don't think that a similar error exists elsewhere. (Have you checked as well?)

**Comment by nojb** [comment]
Yes, I went through the file and checked all the other existing bounds check for missing cases, but this one seems to be the only missing one.

**Review by gasche — APPROVED** [review]
Good to merge when CI passes.

**Comment by gasche** [comment]
I think we should consider this for the 4.06 maintenance branch. @damiendoligez?

**Comment by damiendoligez** [comment]
Yes, this should be cherry-picked to 4.06.

**Comment by xavierleroy** [comment]
Cherry-picked to 4.06

**Pull request merged**
