### PR TITLE
Improve compilation time for toplevel include(struct ... end : sig ... end)

### PR DESCRIPTION
**Pull request by alainfrisch**
This is intended to fix MPR#7357, which uses the natural way of specifying an inline signature for a unit without using an external .mli file.

The trick is similar to the one applied for compiling `module X = (struct ... end : sig ... end)`. Identifiers of the inner structure are "lifted" as extra fields of the top-level structure.

I'd argue this special case is relevant since it corresponds to the natural way of restricting a unit's signature without specifying an external .mli file.  For instance, the change would be beneficial to #217 or to people using that encoding manually.

The trick is currently not applied to `include (struct .... end)`; it would not be difficult to do so, but there is no real reason to use that form anyway (except perhaps to simplify code generators, or to customize warnings locally in a section), and one might argue that simplifying that to just the inner structure should be done earlier in the compilation process.

A minor point: I'm not sure about the call to `Translattribute.check_attribute_on_module`.  In the current version, attributes on the include structure item are considered, not attributes on the either of the two module expression (the Tmod_structure and Tmod_constraint nodes).  This is similar to what was done for the Tstr_module cases (starting from 58d6da114e8e5025b98c9e0127186db5b1463310), but it does not look right to me.  @chambart Can you comment?

### CODE REVIEW

**Comment by bobzhang** [comment]
thanks for the quick fix.
Note that `include (struct .. end )` is still useful for `local open` in code generator, but it is not a high  priority.

**Comment by alainfrisch** [comment]
Does anyone want to review this?

**Comment by alainfrisch** [comment]
@garrigue Do you want to review this?

@chambart Can you comment on the attribute stuff (I think it was introduced by you in the existing case, which I only mimic here)?

**Comment by garrigue** [comment]
I'm not sure I'm the best qualified to review this (except for having introduced my share of bugs in this part of the compiler).
Anyway, the code is clean, compact and non-intrusive, so if it passes the testsuite I would be tempted to say this is fine.
The improvement is limited to a specific pattern, but I understand it is an important one, particularly for generated code.

**Comment by alainfrisch** [comment]
Thanks @garrigue.  Waiting a few days before merging in case @chambart's wants to comment about the attributes stuff.

**Comment by alainfrisch** [comment]
Rebased and added a Changelog.

**Pull request merged**
