### PR TITLE
x86 asm: handle unit names with special characters

### LINKED ISSUE #9461: Can't compile a filename containing "-" character in OCaml 4.11 on AMD64
perl4caml contains an old test which is literally called `001-start.ml`.  This fails to compile on x86-64 only with the new compiler:
```
ocamlopt -w s -I wrappers -c test/001-start.ml
File "test/001-start.ml", line 1:
Warning 24: bad source file name: "001-start" is not a valid module name.
/tmp/camlasm8c525e.s: Assembler messages:
/tmp/camlasm8c525e.s:59: Error: expected comma after name `caml001' in .size directive
File "test/001-start.ml", line 1:
Error: Assembler error, input left in file /tmp/camlasm8c525e.s
```
While we should obviously rename the test, this appears to be an unintentional regression.

### PR DESCRIPTION
**Pull request by nojb**
Fixes #9461

### CODE REVIEW

**Comment by gasche** [comment]
I looked at other direct uses of `make_symbol` in `emit.mlp` files, and saw no instance of a similar bug. (It would be nice to have a dedicated type for symbols different than `string`, and in particular it would rule this error out).

**Comment by nojb** [comment]
Anyone willing to formally approve ?

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
Done.

**Comment by nojb** [comment]
Thanks! Will merge once CI passes.

**Comment by nojb** [comment]
OK, there is an issue with the `^` in the filename (actually two) under Windows:
1. `ocamltest` needed to handle this when calling `diff` to compare the outputs. I pushed a commit with a fix.
2. `flexdll` needs to be adapted to handle this special character.

Since synchronizing with `flexdll` will be difficult, I suggest we remove the caret from the file name.

**Comment by gasche** [comment]
@nojb I think that the use of `Filename.quote_command` is a pretty nice fix. Shouldn't we also use it in other places where `Sys.command` is used in the distribution? Now that you are drawing attention to it, I am a bit worried about, for example, in `ocamltest/main.ml`:

```
Sys.command ("rm -rf " ^ test_build_directory_prefix)
```

This could turn into a disaster if there is a quoting problem in the argument.

Other uses have the general `foo > bar` form you fixed, including one in the toplevel.

I think it could be nice to try to adapt all relevant uses of `Sys.command`, possibly in a separate PR.

**Comment by nojb** [comment]
> I think it could be nice to try to adapt all relevant uses of `Sys.command`, possibly in a separate PR.

Indeed, I will prepare a separate PR for that. I removed the `ocamltest` fix from this PR, as it is not needed as I removed the caret from the file name. I will include it in the coming PR.

Am (still) planning to merge this as soon as CI passes :)

**Comment by gasche** [comment]
Very good, thanks!

**Comment by nojb** [comment]
The test breaks under openbsd/freebsd in INRIA's CI; fix in #9473

**Comment by stedolan** [comment]
> (It would be nice to have a dedicated type for symbols different than string, and in particular it would rule this error out).

To this end, have a look at [@mshinwell's RFC](https://github.com/ocaml/RFCs/pull/13).

**Pull request merged**
