### PR TITLE
Contributing.md: how to contribute changes to the OCaml distribution

### PR DESCRIPTION
**Pull request by gasche**
This supersedes @bobot's RFC #209 .

### CODE REVIEW

**Comment by xavierleroy** [comment]
Looks good to me.  No idea why it causes CI to fail, though...

**Comment by avsm** [comment]
Hm, that's not good...

```
[ -e  dose.3.3+opam.tar.gz ] || curl  -OL http://opam.ocaml.org/archives/dose.3.3+opam.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  256k  100  256k    0     0   459k      0 --:--:-- --:--:-- --:--:-- 1212k
ocaml ../shell/md5check.ml dose.3.3+opam.tar.gz 558ab0e2129ce18adb4a2bfdaacf85cb
MD5 for dose.3.3+opam.tar.gz differ:
  expected: 558ab0e2129ce18adb4a2bfdaacf85cb
    actual: 6c14696d8ab24fb88c1e592b8518c48a
mkdir -p tmp
cd tmp && tar xfz ../dose.3.3+opam.tar.gz
```

**Comment by objmagic** [comment]
@avsm also, some PRs failed because CI cannot build `type_conv 113.00.00` and I'm pretty the error has nothing to do with PR. Here is the [detail](https://travis-ci.org/ocaml/ocaml/builds/81989248#L5767)

`type_conv 113.00.02` [fixes it](https://github.com/janestreet/type_conv/commit/a7bece864b94f6754e2e5e05a53bca9e4615861e#diff-8c15a29ba4f61a60aa5443c9ebf31f8aL298) and maybe we should use 113.00.02?

See also #236 #234 #245

**Comment by avsm** [comment]
See #253 for a Travis refresh to use the more reliable infrastructure.

**Comment by gasche** [comment]
Merged in trunk.

**Pull request closed without merging**
