### PR TITLE
add String.get_opt and Bytes.get_opt functions with doc and tests

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I added `String.get_opt` and `Bytes.get_opt` functions.

They are the same as their `get` counterpart, except that they wrap their result in an option.

### CODE REVIEW

**Review by nojb — COMMENTED** [review]
Typically `_opt` functions are not supposed to return `None` in the case of programmer error (eg passing invalid indices) as these errors are bugs in the program and should not be handled by the normal program flow. You can see this behaviour in other functions of the same modules, eg `String.index_from_opt`.

**Comment by redianthus** [comment]
That's not what `List.nth_opt` does and it's more similar to the functions I'm proposing.

EDIT: you were only talking about the case where the indice is < 0, right ? In that case you're right. My bad! I'll fix it.

**Comment by nojb** [comment]
> EDIT: you were only talking about the case where the indice is < 0, right ? In that case you're right. My bad! I'll fix it.

Actually I was referring to both error conditions. The existing convention in the `stdlib` is that conditions which raise `Invalid_argument` (programmer errors) in the non-`_opt` functions should still do so in the `_opt` functions. You will see that `nth` actually raises `Failure` in the case of a too-large index, so it does not conflict with this convention.

See #885 and #9816 for some related discussion.

**Comment by redianthus** [comment]
OK. I'm not sure why `String.get` should raise `Failure` in the case of a too-large index when `List.nth` should raise `Invalid_argument` but anyway...

So, if I'm making the function raising an exception in case of a too large index, it clearly becomes useless. If I'm not making it, then, you are suggesting that I find another name so it doesn't conflict with this convention, right ? I don't see any good name other than this one.

**Comment by dra27** [comment]
> So, if I'm making the function raising an exception in case of a too large index, it clearly becomes useless.

I wouldn't use the word useless, of course, but I don't think these functions are needed. `Bytes.length`/`String.length` are O(1) operations whereas `List.length`, `Set.mem`, `Hashtbl.mem` etc. are not. The other `_opt` functions exist for the case where avoiding the exception raised by their counterpart would involve non-trivial or computationally expensive work. For example, you cannot avoid `Failure` in `List.nth` without first computing the length of the list (expensive); you cannot avoid avoid `Failure` in `Float.of_string` without first parsing the string to see if it's a floating point constant (non-trivial).

For `String.get`/`Bytes.get` (and `Array.get`), you avoid `Invalid_argument` by checking the length of the value first, which is neither expensive nor difficult.

**Comment by xavierleroy** [comment]
> If I'm not making it, then, you are suggesting that I find another name so it doesn't conflict with this convention, right ?

I'm afraid @nojb and @dra27 suggest that these new access functions (that return None if the index is out of bounds) have no place in the OCaml standard library.  And I agree with this viewpoint.  So, I'm closing this PR.

**Pull request closed without merging**
