### PR TITLE
Fix assembler detection in configure (4.08 version)

### PR DESCRIPTION
**Pull request by dra27**
4.08 version of #2311

cc @damiendoligez, @shindere

### CODE REVIEW

**Comment by dra27** [comment]
Both these fixes I think would be good for 4.08, but I don't think we can drop them in without another beta (@damiendoligez?). See comments starting at https://github.com/ocaml/ocaml/pull/2311#issuecomment-472076042

**Comment by shindere** [comment]
@dra27: @damiendoligez says there will probably not be any more beta,
but there will definitely be a release candidate. Is that good enough?
Can we merge this as it is? And then I think #8528 should be
cherry-picked here, too.

**Comment by dra27** [comment]
Oh yes, an RC is fine, too... I should have remembered that there would be one of those, before, sorry!

**Comment by shindere** [comment]
David Allsopp (2019/03/20 04:28 -0700):
> Oh yes, an RC is fine, too... I should have remembered that there
> would be one of those, before, sorry!

Well I forgot, too. So shall we merge this, now,

**Comment by shindere** [comment]
David Allsopp (2019/03/20 04:29 -0700):
> Merged #2320 into 4.08.

Thank you so much, David!

**Comment by shindere** [comment]
Unfortunately this broke Inria's CI (Mac OS 10.14) at configure time.
Will investigate and report back here.

**Comment by shindere** [comment]
Ultimately the CI problem is due to a segfault of the C compiler...
Let's see whether that happesn again. Worth mentionning is that
no error was reported for flambda=true so there is probably
no real problem with this PR, actually.

**Pull request merged**
