### PR TITLE
Update GitHub CI Ubuntu from 22.04 to 24.04.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
There's two parts to consider in this change. The first is that we should explicitly ask for Ubuntu 24.04 in CI, since GH is updating runners and which version of Ubuntu we get might change without warning. 

The second part is better sanitisation of the LLDB output on Linux, which needs more consideration and probably re-writing to use Python API rather than running commands as the CLI. Using the Python API should allow better control over what gets  printed out.

### CODE REVIEW

**Review by MisterDA — APPROVED** [review]

**Comment by shym** [comment]
For the record, I went with forcing CI to use 22.04 on my fork for now.
https://github.com/shym/ocaml/commit/287b21ab66f2561435e3f849188d13885c661e07

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
I'm unsure how to proceed with this PR. It does not pass CI at the
moment.

@shym do you think we can force Ubuntu 24.04 on the main remo
as you did on yours untilthis PR gets merged?

Unless @tmcgilchrist can so something about it but I believe he is
off and would rather prefer not to pressure him.

**Comment by shym** [comment]
> @shym do you think we can force Ubuntu 24.04 on the main remo as you did on yours untilthis PR gets merged?

As 20.04 is still supported, I guess the 22.04 image will not be retired very soon. So I guess that a good way to let the dust settle on the present PR.

**Comment by dra27** [comment]
The two commits I just pushed should fix this (the whole lot can be squashed together at merge)

**Pull request merged**
