### PR TITLE
Revert "Use ocamlyacc's support for OCaml-style comments"

### PR DESCRIPTION
**Pull request by MisterDA**
Just got bitten by this, the problem has been reported two weeks ago in #11718.

This reverts commit 514a830eae3991aec12146d3f6aeff3aa2d8406a.

> I think these changes may have led to a small regression.
> 
> When I do `dune build @libs` in ocaml source code now, I get:
> 
> ```
> $ dune build @libs
> File "ocamltest/tsl_parser.mly", line 1: syntax error
> (**************************************************************************)
> ^
> ```
> 
> I don't know how important this error is and if it has any practical impact.

https://github.com/ocaml/ocaml/pull/11718#issuecomment-1475316277

> The dune build system for the OCaml compiler is morally a hack, it uses the tools from the ambient opam switch to build the compiler codebase -- which can break whenever the compiler distribution has more recent tools than the opam switch, and uses the more recent features in its own codebase.
> 
> This is what is going on here: @DemiMarie introduced a new ocamlyacc feature, and also started using it in the compiler codebase in the non-essential commit [514a830](https://github.com/ocaml/ocaml/commit/514a830eae3991aec12146d3f6aeff3aa2d8406a). If we want dune to work well, a reasonable solution is to revert [514a830](https://github.com/ocaml/ocaml/commit/514a830eae3991aec12146d3f6aeff3aa2d8406a) for now, and wait until the next OCaml version is released (with the new ocamlyacc feature) to merge it again. At this point the dune build will be possible with the most recent OCaml release as your opam switch.
> 
> (I think that having dune more-or-less working to build subset of the compiler distribution is more useful than having a consistent comment syntax for .mly files, so I would suggest doing that.)

https://github.com/ocaml/ocaml/pull/11718#issuecomment-1475338016

I'll try making a dune file to build trunk's ocamlyacc to avoid these problem in the future.

cc @gasche @DemiMarie @damiendoligez (people involved with the previous PR).

### CODE REVIEW

**Review by gasche — APPROVED** [review]
I agree that this is a good approach for the time being. (We have to wait at least one release cycles to use new ocamlyacc features.)

**Comment by gasche** [comment]
> I'll try making a dune file to build trunk's ocamlyacc to avoid these problem in the future.

Meh. This only solves the ocamlyacc-related issues, but those are rare, and similar issues come from changes in the compiler itself. And that sounds like a non-trivial amount of work. I am not sure that it would be a good use of your OCaml contribution time. (I'd rather have someone fill in with the Windows stuff, Github Actions, what have you.)

**Comment by MisterDA** [comment]
it is a good amount of work.
I've already spend like 10 minutes on it, and I've realized the compiler is using Dune 1, Dune cannot build full C executable easily, and so on and so on.
I'll leave that aside for the time being.

**Comment by gasche** [comment]
I have a related question, while we are at it: personally my only reason to use the Dune files is to have Merlin working for the compiler. But this is rather inconvenient because I need rerun `dune` regularly when interfaces change, and I need to `make clean` before each dune build. I often wonder if we could just bite the bullet and commit .merlin files in the compiler, so that I don't have to do this anymore. (I'm fine with people using the dune build system for their own reasons, as long as they maintain it on their own.) Would you by chance be motivated to look into writing .merlin files for the compiler, or know someone who would? It doesn't sound more painful than building ocamlyacc in dune, and I think it would be directly useful to many people.

**Comment by MisterDA** [comment]
Dune and Merlin devs have spend a ton of efforts in the past years to auto-generate Merlin files from Dune. I miss some context and experience around this, but from far away it seems wrong to write Merlin files by hand. They might know better. Possibly Dune could be extended to support more use-cases from here. 
Nevertheless I think it's reasonable to require from tools at version x to be able to build tools at version x+1, or maybe I've missed some documentation about the dune build explaining work around.

**Comment by gasche** [comment]
I remember now why writing `.merlin` files by hand does not quite work: the problem is that this assumes that the currently-installed Merlin can read the build artifact produced by the dev version of the compiler, which is not the case most of the time. With the dune build system, we try to build the sources from the currently-installed version of the compiler, which (sometimes chokes on parts of the project but) is always compatible with the currently-installed Merlin. To do better than this I would need a version of Merlin that tracks the current trunk, and this does not exist -- Merlin is only updated at release time.

**Comment by DemiMarie** [comment]
Time to make Merlin part of the compiler source tree?

**Comment by shindere** [comment]
@gasche: for some time I was about to suggest that if Dune is able to
genrate the `.merlin` files then the compiler's official build system
could do the same but I now understand  that this owuldn't work either,
right?

Apart from integrating Merlin in the compiler, is there something we
could do upstream to make generating merlin files easier?

**Pull request merged**
