### PR TITLE
Don't commute negation with float comparison

### PR DESCRIPTION
**Pull request by lpw25**
#1215 made an incorrect assumption about float comparison which can cause `not` applied to a float comparison to produce the wrong result for `nan`. This patch just removes the offending optimisation and adds a test case.

I've made this against 4.06 so that a bug fix release can be done. For trunk I intend to write a slightly more involved patch that will use a corrected version of the optimisation taking advantage of the support for negated float comparisons in mach.

### CODE REVIEW

**Comment by alainfrisch** [comment]
Could we keep the optimization for `=` and `<>` ?

**Comment by mshinwell** [comment]
It appears to be the case that it is correct to leave this optimization in place for equality and inequality.  Perhaps @xavierleroy could confirm.

That said, for 4.06, I think we should do the most obvious fix of removing the optimization for all of the comparison operators.

**Comment by xavierleroy** [comment]
Yes, for `=` and `<>` the optimization is sound, because IEEE754 guarantees that `x neq y` is the Boolean negation of `x eq y`.

**Review by xavierleroy — APPROVED** [review]
Obviously correct.

**Comment by gasche** [comment]
Note: PRs marked for release/maintenance branches are a bit annoying, because they make the decision to merge in trunk instead painful. Whenever a PR also makes sense for trunk I think it's better to send it there, being explicit that we also want it also cherry-picked in another branch.

**Comment by gasche** [comment]
Travis fails because a Changes entry is missing.

**Comment by xavierleroy** [comment]
@lpw25 @gasche: please make up your mind as to the base branch for this PR.  Then add the corresponding Changes entry.

**Comment by gasche** [comment]
I just added a new "4.06 maintenance branch" section to the `trunk` and `4.06` Changes. The Changes entry should go there about rebasing, and I think that targetting `trunk` is better (I wasn't aware that it seems possible now to change the target branch of a PR on the fly).

**Comment by lpw25** [comment]
I was planning to use #1487 on trunk instead of this one, but I guess that would drop the changes entry, so I'll retarget this one at trunk.

**Comment by lpw25** [comment]
Ok, I've retargeted this at trunk and added a changes entry.

**Comment by gasche** [comment]
@lpw25 my inclination would be to merge this in trunk now and cherry-pick in 4.06. Do you agree that this is the right move, even though #1487 is around the corner?

**Comment by gasche** [comment]
(Why is AppVeyor broken?)

**Comment by alainfrisch** [comment]
(Travis did not run either, apparently.)

**Comment by gasche** [comment]
(I just performed the close-reopen weather dance and it seems to have worked.)

**Comment by xavierleroy** [comment]
@gasche: agreed, it feels like the right thing to do to have this simple fix in 4.06.1 and the cleverer fix #1487 in 4.07 and up.

**Comment by lpw25** [comment]
> Do you agree that this is the right move, even though #1487 is around the corner?

I agree

**Comment by xavierleroy** [comment]
Merged on trunk and cherry-picked as [4.06 a6cb296].

**Pull request merged**
