### PR TITLE
Keep approximation of type representation on abstract types

### PR DESCRIPTION
**Pull request by alainfrisch**
Here is another take at https://caml.inria.fr/mantis/view.php?id=7485 .  See also https://github.com/ocaml/ocaml/pull/1261 .

This is WIP.

The initial goal is to make sure one can write:

````ocaml
  type 'a t
  type s = A : 'a t -> s [@@ocaml.unboxed]
````

This is not safe in general, since `'a t` could be `'a`, which would allow to mix float and non-float values in type `s`, which is unsafe because of the dubious automatic float array unboxing hack.

So the idea is to generalize the existing `@@ocaml.immediate` attribute, by letting the user annotate abstract types with an approximation of their runtime representation.  This PR currently supports the following forms:

 - `@@ocaml.immediate` (represented as integers)
 - `@@ocaml.float`
 - `@@ocaml.lazy` [EDIT: dropped this case, which does not bring more info than non_float for now]
 - `@@ocaml.non_float`
 - `@@ocaml.addr` (values can be neither float nor lazy)

The annotation are mostly useful on abstract types without a manifest.  On other types, they are just checked to be correct, but the type system will keep the inferred representation if more precise.

The PR also combines several existing approximations of representation, to make them benefit from the new annotations.  For instance:

 - Specialization of primitives on abstract types implemented as float.
 - There is an optimization to compile `lazy x` as the identity when `x` is known to be neither lazy nor float.
 - If a module creates an all-float record type but expose the type of fields as abstract, this would usually lead to an error message.  Cf https://caml.inria.fr/mantis/view.php?id=4584.  This can now be fixed by exposing the float representation of the abstract type (which better protects the abstraction than exposing a private float).
 - Array accesses are optimized if the compiler can detect the elements are non floats.

### CODE REVIEW

**Comment by gasche** [comment]
I think this is a good idea. For Mantis references, see also Pascal Cuoq's [MPR#5361](https://caml.inria.fr/mantis/view.php?id=5361).

**Comment by alainfrisch** [comment]
Should we use a single attribute whose payload describes the representation (as in #1261) or a different attribute for each kind?

What about the naming?  I'm still not 100% convinced by `immediate`.  `float` and `non_float` are clear enough, but `addr` is quite opaque.  Perhaps `non_float_non_lazy`?  Hopefully it should not be used too often (it's only use, I think, is to avoid an extra wrapping with a lazy thunk).  One should also perhaps allow to mark something explicitly with the generic representation.

It is also tempting to default to `non_float` for abstract types.  This would avoid having to mark many exported types with that representation in order to benefit from optimizations (and unboxing of single-constructor existentials).  But while doing that for exported types (in covariant positions) could break only code that expose abstract types implemented as float (which should be quite rare), doing it in contravariant position (in functor arguments) means that e.g. Set.Make cannot be applied on `float`, which is quite bad.  And it seems ugly to do something different in covariant and contravariant positions.

**Comment by alainfrisch** [comment]
I'm also considering adding another case: `float_or_non_float` (or a better name), that specifies that the "floatiness" doesn't depend on any type argument.  It is always the case for non-parametric abstract types (and would thus be the default for them), and considering how rare parametric abstract types that don't satisfy the predicate are, it might even be possible to make it the default for them (with an annotation for the really generic case).  Basically, the criterion is exactly the one needed to allow `type s = A: 'a t -> s [@@unboxed]`, and both `float` and `non_float` can be allowed without a need to distinguish them.

Cases that would be rejected for this annotation are parametric types that extract part of their type parameters "at the root":  `type 'a t = 'a`, or `type 'a t = 'b constraint 'a = 'b list`, or examples with aliases and/or unboxed types.

**Comment by alainfrisch** [comment]
Closing this PR: not a lot of interest nor activity here, and the benefits are greatly reduced when "unboxed float arrays" are disabled.

**Pull request closed without merging**
