### PR TITLE
Update FlexDLL to 0.37

### PR DESCRIPTION
**Pull request by dra27**
Also switch AppVeyor back to only testing the bootstrap on the mingw32 build and also some tweaks to the docs.

For 4.06 and trunk

**It's important to let AppVeyor finish testing this one**

### CODE REVIEW

**Comment by shindere** [comment]
In appveyor_build.sh, I'd suggest to introduce a variable like

flexdll_files := \
  flexdll.h flexlink.exe flexdll*_msvc.obj \
  default.manifest default_amd64.manifest

And then use that variable in the for loop. It would make the line
shorter and, IMO, improve the readability a bit.

**Comment by gasche** [comment]
I find it surprising that you download both `.tar.gz` and `.zip`, and that you do different things with them. This may be what you mean in

> Also switch AppVeyor back to only testing the bootstrap on the mingw32 build 

but it's a bit cryptic for the non-expert. Is there a place that describes why you are using these two archives?

**Comment by dra27** [comment]
@gasche - there's room for expanding the paragraphs in HACKING.adoc on what and how AppVeyor tests, but I don't really want to have to do that here. There was a hiatus with the binary release of FlexDLL 0.36, and the principle change to AppVeyor is to revert necessary changes made in #1200 as FlexDLL 0.37 doesn't require it to be tested that way. I've also reverted a change made 71dfcb5 which should have been reverted in b37db6a slightly longer ago. It doesn't download a "`.tar.gz` and `.zip`" - they are different things entirely, one is the source release of FlexDLL and the other is the binary release. msvc64 is tested using Visual Studio 2015 which requires us to build the C support objects manually (plan is to fix that properly in FlexDLL 0.38), msvc32 is built using Visual Studio 2010 so uses only files from the binary release. mingw32 tests the bootstrap process via the Git submodule. During development of #1200, it was necessary to switch all three builds to use the submodule because we needed "cutting edge" FlexDLL.

@shindere - I've shortened that line. Sorry, until those check-typo GPRs get merged (I'll deal with the first one shortly), I keep ignoring the output of my githook because it keeps referring to lines which aren't part of the patch!

**Comment by shindere** [comment]
David Allsopp (2017/10/25 13:15 -0700):
> @shindere - I've shortened that line. Sorry, until those check-typo
> GPRs get merged (I'll deal with the first one shortly), I keep
> ignoring the output of my githook because it keeps referring to lines
> which aren't part of the patch!

Okay, np. I guess it'd be nice to somehow make check-typo clever enough
to check just the + lines in patches.

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
Merged in trunk, cherry-picked in 4.06 ( 3e0a0ac1316f1932209a274d48d695eaab0d5cf1 ).

**Pull request merged**
