### PR TITLE
Read config from external file

### PR DESCRIPTION
**Pull request by nojb**
Let's experiment with reading the configuration (the values substituted in `config.mlp` at build-time) from an external file (see #6200, also [here](https://github.com/ocaml/ocaml/issues/9291#issuecomment-632217959)).

For this experiment, I borrowed [an existing module](https://github.com/AbsInt/CompCert/blob/19aed83caebcae1103e0c4f6e200744492f17545/lib/Readconfig.mll) from CompCert that handles parsing the config file (the format for each line is `key=value` or a comment starting with `#`; `value` follow POSIX conventions). Not sure if this poses problem from a copyright perspective. This was just to get the ball rolling, we can decide if we want to reimplement the functionality/make different design choices/etc.

Currently, the external config file, named `ocaml.ini`, is supposed to be found either in the same directory as the compiler, or in the `lib/ocaml` directory (where `Makefile.config` and `VERSION` are also installed). See below for a sample.

The main issue to be resolved is that reading the configuration from an external file means that tools that link with `compilerlibs` depend on this file as well. This is OK for tools that run in an environment where a compiler toolchain is available (eg `opam`), but not for standalone environments where the tool binary is supposed to be self-contained.

To mitigate this, currently a hard-coded copy of the external file is included in the source of `config.mlp` (which is used if no external file is found). This means that tools that are executed in an environment where the external file is not available behave as before.

Points to discuss/improve:

- What to do with the dependency on the external file for tools linking with `compilerlibs`? As mentioned above, depending on the external file for standalone tools seems bad, but including the hard-coded copy of the config file in the source of the compiler is also not very nice (decreases reproducibility of `ocamlc`)
- command-line option to specify a config file? The difficulty here is that reading the config file happens a priori before arguments are processed, so special logic would be needed here (CompCert has some code for this, see [here](https://github.com/AbsInt/CompCert/blob/970c5aa11a629d81abc893e7f0428b53e556ab30/driver/Configuration.ml#L15-L22))
- better error handling: right now we just `exit 2` if there is a problem parsing the file; an exception should be raised instead and it should be displayed appropriately.

### CODE REVIEW

**Comment by nojb** [comment]
Sample config file:
```
afl_instrument=false
arch=amd64
arcmd='ar'
asm='clang -arch x86_64 -Wno-trigraphs -c'
asm_cfi_supported=true
bytecclibs='-lm  -lpthread '
cc='gcc'
ccomptype=cc
outputobj='-o '
ext_asm='.s'
ext_dll='.so'
exe=''
ext_lib='.a'
ext_obj='.o'
flambda=false
with_flambda_invariants=false
flexlink_flags=''
flexdll_dir=''
host=x86_64-apple-darwin19.5.0
libdir='/Users/nojb/Downloads/ocaml2/local/lib/ocaml'
libunwind_available=false
libunwind_link_flags=''
mkdll='gcc -shared -flat_namespace -undefined suppress                    -Wl,-no_compact_unwind'
mkexe='gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -Wl,-no_compact_unwind'
flexlink_ldflags=''
mkmaindll='gcc -shared -flat_namespace -undefined suppress                    -Wl,-no_compact_unwind'
model=default
nativecclibs='-lm '
ocamlc_cflags='-O2 -fno-strict-aliasing -fwrapv '
ocamlc_cppflags='-D_FILE_OFFSET_BITS=64 -D_REENTRANT'
ocamlopt_cflags='-O2 -fno-strict-aliasing -fwrapv '
ocamlopt_cppflags='-D_FILE_OFFSET_BITS=64 -D_REENTRANT'
packld='ld -r -arch x86_64 -o '
profinfo_width=0
ranlibcmd='ranlib'
force_safe_string=true
default_safe_string=true
windows_unicode=0
supports_shared_libraries=true
system=macosx
systhread_support=true
target=x86_64-apple-darwin19.5.0
with_frame_pointers=false
with_profinfo=false
with_spacetime=false
enable_call_counts=true
flat_float_array=true
function_sections=false
cc_has_debug_prefix_map=true
as_has_debug_prefix_map=false
```

**Comment by xavierleroy** [comment]
One thing you can simplify is the syntax and parsing of the .ini file.

CompCert uses `Unix.create_process` to launch external commands (assembler, linker), not `Sys.command` like OCaml.  For this reason, CompCert manipulates command lines that have already been split in words.  It's the parser for the .ini file that does the initial splitting (e.g. `"as -m32"` -> `["as"; "-m32"]`), following POSIX shell quoting conventions.

OCaml doesn't need to split configuration parameters: in the current config.ml there are no string lists.  So the .ini parser can be much simplified, taking as value anything right of the equal sign.  So, in the .ini file you put
```
ocamlc_cppflags=-D_FILE_OFFSET_BITS=64 -D_REENTRANT
```
(note the absence of quoting) and you get the string `"-D_FILE_OFFSET_BITS=64 -D_REENTRANT"`.

**Comment by xavierleroy** [comment]
Another tweak to consider is to use the GNU make `$(file )` function to write the .ini file, instead of shell echo commands.  The `$(file )` function is robust against special shell characters.

**Comment by nojb** [comment]
Thanks for the quick feedback!

> One thing you can simplify is the syntax and parsing of the .ini file.
> 
> OCaml doesn't need to split configuration parameters: in the current config.ml there are no string lists. So the .ini parser can be much simplified, taking as value anything right of the equal sign.

I did this; all the quoting mechanism is gone. Something to keep in mind, though: some of the variables have values with significant whitespace at the end (eg, `PACKLD` is `ld -r -arch x86_64 -o ` in OS X and it won't work without the final space). It is a bit less clear without the quotes (but I still think the simplification is worth it).

> Another tweak to consider is to use the GNU make `$(file )` function to write the .ini file, instead of shell echo commands.  The `$(file )` function is robust against special shell characters.

Unfortunately this function [appeared](https://lists.gnu.org/archive/html/make-w32/2013-10/msg00021.html) in v4.0, which is not the norm yet in some systems. For example, OS X 10.15 still ships 3.81.

**Comment by Armael** [comment]
>eg, `PACKLD` is `ld -r -arch x86_64 -o ` in OS X and it won't work without the final space

Hm, this sounds like it could result in a long head-scratching session for anyone using a text editor that removes trailing whitespace.

**Comment by dra27** [comment]
A ~couple of~few thoughts:
- I think it's reasonable that the compiler should be _built_ with a default config (i.e. I think the hard-coded `ocaml.ini` is the correct way to do it) - `ocaml.ini` can be used to override it and so I wouldn't expect us to install `ocaml.ini` normally.
- In a moderately bike-sheddy fashion, I find files `.ini` which I can't read with `[GetPrivateProfileStringW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestringw)` to be misnamed 🙂 Can it be called `ocaml.conf` or `compiler.conf`?
- Some things are properties of the compiler - i.e. the configuration being loaded would not be satisfiable by the compiler. In some cases, this would be the start of a change (for example, we _could_ have a compiler where `flambda` can be selected) but there will always be some things which can't be (host, for example). Is it worth making that distinction at this stage - i.e. some things kept with `sed` on `config.mlp`?
- The command line pre-processing could be circumvented with an environment but, apart from not being a fan of this in general, I think this would be a very bad idea (imagine opam trying to configure the compiler this way...). So `Config` will either have to pre-process `Sys.argv`. We could mandate that `-config-file` or whatever appears first. There's then the build tree problem for (i.e. interpreting `-nostdlib`) which should clearly inhibit loading of an installed config file. One possibility is that the compiler could determine from `Sys.argv.(0)` that it is not installed (this would also work for my relocatable proposal), but this is potentially brittle. Another option might be to have a file in the build tree which _suppresses_ the automatic loading.
- FWIW, I'd always expected this to be an opt-in feature - i.e. you'd have to tell the compiler to override the config options explicitly. I think we can still get the benfits of #6200 (and even possibly deal with https://github.com/ocaml/ocaml/issues/6200#issuecomment-667043735 by putting the data further down the file - I can't remember how the .cmx approximation stuff works, but I do remember that it's easy to have .cmx files unchanged while .o does, because it was a Jbuilder bug when checksums came in) without the potential complexity of an always-installed or picked up config file?

**Comment by bschommer** [comment]
I would avoid installing the `.ini` files in the library directory, instead I would use `datadir` as suggested by [GNU Coding Guidelines](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html). Also I like the idea to have a default configuration hard coded, since then one can print a more informative error message in case that a broken configuration is given.

**Comment by nojb** [comment]
Following discussion in the developer's meeting and in the spirit of trying to exercise a bit of PR discipline, I'm shutting down this "experiment" PR (there are still some design points that need working out and I don't have the time to do so at the moment).

**Comment by gasche** [comment]
I'm a bit sad to see this one go, as (I don't have time nor expertise to comment much here but) this looks like a step towards a feature that we want, and would have been useful a fair number of times already.

**Comment by xavierleroy** [comment]
We don't have to close all the PRs that have been blocked for a while!  But when we keep a PR open we should have some next steps in mind.  I agree with @gasche that this PR has potential, but what are the next steps and who is going to work on them?

**Comment by nojb** [comment]
> I agree with @gasche that this PR has potential, but what are the next steps and who is going to work on them?

Exactly! I am super-busy at the moment, and I agree that we should only keep PRs open that are either making active progress or for which there is a sequence of possible "next steps" to be taken. In this case, I don't have the time to work actively on it in the near future so I think it is best to close it down (it can alway be re-opened later). Something I could do is to write down a document (maybe in the RFC repo) explaining the approach taken by this PR and any unresolved issues, as a way of not letting the topic die away.

**Comment by gasche** [comment]
I've been thinking about this issue again.

My understanding is that `config` contains two different sorts of things:

- *constants* that only depend on the environment in which the compiler was built, not on the compiler itself; for example `libunwind_available=false` or `supports_shared_libraries=true`.
- *variables* that could conceivably be changed when invoking the compiler, but whose default value (and currently the only expressible value) was decided by the configure script; for example `ocamlc_cflags='-O2 -fno-strict-aliasing -fwrapv '`.

When we look at the justifications for the feature, they are generally of the form: "I would like to be able to set the value of this configuration *variable* more easily". But I think that there is an easy way to make this wish come true, that does not involve an invasive change:
- add a flag for this variable in Clflags
- treat the "configuration variable" as the default value for this flag, which was decided at configure-time. (Note: once interpreted as "default values", the configuration item becomes a constant, there is no point in trying to change it at compiler invocation time anymore.)

(Large simplification ahead!) If we did this for all configuration "variables", we would only have constants left in the configuration, and we would *not* need this feature. We would have many more command-line flags, but those can now be passed by file conveniently with the `-args/args0` parameters, so problem solved.

There are two problems with this approach:

1. Maybe we don't want to add 30 more independent command-line flags to our command-line interface. It may be that we should think of some key/value abstraction for a part of the cli interface, and have a generic mechanism to set key/value pair, and to list keys in `--help` documentation, etc. (But I still think that `-<key> <value>` is the more natural interface, rather than some `-config-set <key> <value>` construction, so maybe this key/value abstraction would just masquerade as today's flags.)
2. More fundamentally, the notion of what is constant and variable is in fact not so clear-cut! For now `arch` or `target` is a constant, the compiler is configured and compiled to support only one architecture, but people would like to move it to a variable to support cross-compilation more easily (make the target an invocation-time choice rather than configure-time choice). Taking things to the extreme, one could claim that even `host` could be a variable for bytecode programs that can work unchanged in very different environments.

I think that a natural answer to (2) is to just migrate things that are variables *today* into Clflags, and consider separately the question of shifting some aspects from constants to variables. If a configuration constant becomes a variable later, we can still add it to Clflags. The feature that is discussed in the present issue would not really have helped before that change happens, anyway.

**Pull request closed without merging**
