### PR TITLE
Update to Automake 1.17, libtool 2.5.4, and latest GNU config

### PR DESCRIPTION
**Pull request by MisterDA**
This PR updates the bundled scripts taken from Automake 1.17 ([Changelog](https://git.savannah.gnu.org/cgit/automake.git/tree/NEWS)), libtool 2.5.4 ([Changelog](https://git.savannah.gnu.org/cgit/libtool.git/tree/NEWS)), and latest GNU config.
They improve compatibility with various systems and tools; in particular support on Windows of MSVC, clang-cl, Cygwin, and MSYS2 should be improved. They recognize more systems, allow users to override the selection of some tools, support modern C compilers and language versions, and fix bugs.

This doesn't affect users ability to regenerate the `configure` script, as Autoconf doesn't override these files.

### CODE REVIEW

**Comment by shindere** [comment]
Thanks.

All this looks very reasonable to me. Just one thing: do we actually
need the automake bit?

I know I did add them myself but I simply cannot remember why and I
can't find a use for them in the sources, so was it maybe to please
autoconf?

If we cannot find any use of these files then  maybe, instead of
updating them we could rather get rid of them and of their mention in
`.gitattributes`?

**Comment by MisterDA** [comment]
`install-sh` is needed by `configure` if the `install` program is deemed faulty. The `compile` script is a wrapper for compilers which do not understand `-c -o`. We could use it to call `cl.exe`, but we call `cl.exe` directly instead, so as you wrote, I don't think we're using it now.

**Comment by MisterDA** [comment]
There's also the `missing` script, which I couldn't find a reference to either.

**Comment by shindere** [comment]
So, shall we get rid of both `compile` and `missing` for the time being,
with the idea that we can always re-introduce them if we find ourselves
actually needing them?

**Comment by MisterDA** [comment]
> So, shall we get rid of both `compile` and `missing` for the time being, with the idea that we can always re-introduce them if we find ourselves actually needing them?

I'm of that opinion too, and I've added a commit that does just that.

**Comment by shindere** [comment]
Thanks

**Review by shindere — APPROVED** [review]

**Pull request merged**
