### PR TITLE
Don't inline stubs in Closure (fixes error in GPR#957)

### PR DESCRIPTION
**Pull request by mshinwell**
GPR #957 contains a bug: it can unconditionally inline small "stub" functions in the `Closure` pass even if they contain closures.  The typical manifestation of this bug seems to be errors from the linker complaining about multiply-defined anonymous function symbols.

Given that in `Closure` this stub inlining won't affect many things (as noted in the comments for GPR #957) I think we should just turn it off for the moment; if people so desire we can then consider how to make this work properly.  I don't think we should revert the remainder of GPR#957.

### CODE REVIEW

**Comment by alainfrisch** [comment]
I'd like to fully understand the consequence of disabling inlining stubs in Closure.  In particular, does it affect inlining of the stubs created for dealing with default values on optional arguments?

**Comment by lpw25** [comment]
> does it affect inlining of the stubs created for dealing with default values on optional arguments

It makes them less likely to be inlined than on current trunk, although no less likely than in 4.04. One possible regression is that functions marked `[@inline]` with default parameters may not be inlined by the Closure path.

I think it is fine to merge this fix, but we should look to reenable the guaranteed inlining of stubs before 4.05. Probably a check that the stub does not contain a closure would be sufficient.

**Comment by alainfrisch** [comment]
>  although no less likely than in 4.04

Ok, thanks for the clarification.

**Comment by mshinwell** [comment]
@alainfrisch Are you able to approve merging this?  (It blocks building of some common packages at the moment, such as some ppx-related ones, and Merlin.)

**Comment by alainfrisch** [comment]
I won't have time to look at the code (I'd need to study GPR#957 first), but it you are confident that this (together with #957) does not introduce regressions for Closure compared to 4.04, then I think it is fine to merge.

**Comment by chambart** [comment]
This looks correct

**Pull request merged**
