### PR TITLE
[RFC] `ocamlbuild -documentation` support for parametrized flags

### PR DESCRIPTION
**Pull request by gasche**
Currently the `-documentation` tag only support non-parametrized flag declaration. This has the unfortunate consequence that, for example, the deprecated `warn_A` tag is documented, but not the parametrized `warn(A)` option.

This pull request provides support for documentation of parametrized flags, by providing at declaration time a "documentation instance" for the parameter. The documentation generated corresponds to the rule produced for this particular parameter instance. For example,

```
pflag ["ocaml"; "native"; "pack"] "for-pack" ~doc_param:"PackModule"
     (fun param -> S [A "-for-pack"; A param]);
```

generates the documentation

```
parametrized flag {. for-pack(PackModule), native, ocaml, pack .}
  "-for-pack PackModule"
```

If no documentation parameter is provided, we do not attempt to call the parametrized rule (because that could result in arbitrary side-effects), but instead just show

```
parametrized flag {. for-pack(?), native, ocaml, pack .} "<fun>"
```

I would be interested in feedback on the API and code of course (or the choice of parameter names for the various rules, see the current output for the built-in rules at the end of this message), but also on more immediate feedback on:
- the user experience: is the generated documentation clear enough? We are not trying to match the clarity of a lovingly written user manual, but rather give to comfortable users a simple way to exhaustively query the capabilities of build when they wonder whether (or under which name) a given feature is available.
- The developer experience: I also considered always passing `X` if no parameter is given (and catching exceptions and defaulting to `<fun>` when failure occurs), but whether this is acceptable or not depends on the action implemented in parametrized rules. If you have implemented exotic rules that should not be called with dummy parameters, please let me know. If you think passing `X` is much better than not calling the parametrized rule at all, this is also interesting. For now, the new `?doc_param` parameter is not exposed to plugin authors (all plugin-defined parametrized rules get the `<fun>` fallback), but I think it should be made available whenever we settle on a good interface.

### CODE REVIEW

**Comment by hcarty** [comment]
What you show in your examples is already better than nothing showing up at all. It would be nice to have X or ? shown as an argument for usage purposes if an author-provided value doesn't exist.

**Comment by gasche** [comment]
So I just tried, and `X` works rather well in general. I'll update the PR to try to apply it, and show `<fun>` only if it raises an exception. This means we may run arbitrary side-effects of parametrized tags, but (1) I don't expect people to define parametrized rule with dangerous effects if applied and (2) showing the documentation is never mixed with arbitrary compilation actions, at least when invoked by the main codebase through `-documentation`.

```
parametrized flag {. link, ocaml, runtime_variant(X) .} "-runtime-variant X"

parametrized flag {. compile, ocaml, open(X) .} "-open X"

parametrized flag {. ocaml, ocamldep, open(X) .} "-open X"

parametrized flag {. compile, ocaml, warn_error(X) .} "-warn-error X"

parametrized flag {. compile, ocaml, warn(X) .} "-w X"

parametrized flag {. infer_interface, ocaml, ppx(X) .} "-ppx X"

parametrized flag {. doc, ocaml, ppx(X) .} "-ppx X"

parametrized flag {. ocaml, ocamldep, ppx(X) .} "-ppx X"

parametrized flag {. compile, ocaml, ppx(X) .} "-ppx X"

parametrized flag {. infer_interface, ocaml, pp(X) .} "-pp X"

parametrized flag {. doc, ocaml, pp(X) .} "-pp X"

parametrized flag {. ocaml, ocamldep, pp(X) .} "-pp X"

parametrized flag {. compile, ocaml, pp(X) .} "-pp X"

parametrized flag {. compile, inline(X), native, ocaml .} "-inline X"

parametrized flag {. for-pack(X), native, ocaml, pack .} "-for-pack X"

parametrized flag {. compile, for-pack(X), native, ocaml .} "-for-pack X"

parametrized flag {. external_tokens(X), menhir_ocamldep .}
  "--external-tokens X"

parametrized flag {. external_tokens(X), menhir .} "--external-tokens X"
```

**Comment by gasche** [comment]
I rebased and completed this PR; I'll try to filter it and move it to the new ocaml/ocamlbuild repo as soon as possible, but comments and feedback are still welcome.

On the first iteration I was unsatisfied with the fact that `pflag_and_dep` calls were not documented. I fixed this and I think that the feature set is now ready to consider merging. (One could decide to also document `dep` calls, but that can come later.)

**Comment by gasche** [comment]
Recreated at ocaml/ocamlbuild#20 .

**Pull request closed without merging**
