### PR TITLE
Stop supporting obsolete platforms

### PR DESCRIPTION
**Pull request by shindere**
This PR simplifies the configure script by removing the support
for obsolete platforms. The list of removed platforms is documented
in the associated Changes entry.

This has been discussed with @xavierleroy and @damiendoligez.

### CODE REVIEW

**Comment by Armael** [comment]
BeOS is surely obsolete, but AFAIK Haiku is still under active development as an open-source project -- so I wouldn't consider it an obsolete platform.

**Comment by gasche** [comment]
(Haiku support was introduced in 2013 by user-provided patches in [MPR#6207](https://caml.inria.fr/mantis/view.php?id=6207).)

**Comment by shindere** [comment]
Armael (2018/09/06 05:59 -0700):
> BeOS is surely obsolete, but AFAIK Haiku is still under active
> development as an open-source project -- so I wouldn't consider it an
> obsolete platform.

Oh I was not aware and should have searched, sorry. Thanks for your
investigation, @gasche.

I restored the support for Haiku. It'd be even better if we could check
that this still works.

**Comment by gasche** [comment]
Thanks! This is a minor detail but you left "Haiku" listed in the Changes entry.

**Review by gasche — APPROVED** [review]
Good to go if CI and `precheck` pass. @shindere, could you run a `precheck` job?

**Comment by shindere** [comment]
Gabriel Scherer (2018/09/06 13:36 +0000):
> Thanks! This is a minor detail but you left "Haiku" listed in the
> Changes entry.

No it's a plain mistake! Thanks for having spotted it, it's fixed!

**Comment by jperkin** [comment]
Why was Solaris support removed? It was working perfectly fine, we've been shipping OCaml binary packages for SmartOS and illumos for many years, until pkgsrc upgraded to 4.08.1.

I will be adding back support regardless so that our users can continue to run OCaml software, but would appreciate it being put back so that we don't need to carry additional patches.

**Comment by cfcs** [comment]
@jperkin Did it actually stop building? From a cursory glance it looks like recent solaris on `x86_64` and `sparc` should still be building, after this PR removed builds for older `sunos` and 32-bit intel?
I'm not sure what exactly is matched by `*-*-solaris2*` but my guess would be that it was the `2.x` line of Solaris, ie pre-Solaris 7?

**Comment by jperkin** [comment]
No, `*-*-solaris2*` matches everything, illumos and Solaris 11 being "*-pc-solaris2.11".

And yeh, it stopped building, I'm still working on the patches to get it working again.

**Comment by jperkin** [comment]
FWIW I've also been maintaining the 32-bit Solaris build in pkgsrc (as you can see here: https://github.com/netbsd/pkgsrc/commits/trunk/lang/ocaml?author=jperkin), it also works fine but I understand if you want to start dropping 32-bit builds.

**Comment by cfcs** [comment]
@jperkin I don't have anything to do with the OCaml compiler, but I'm a bit confused why e.g. Haiku got to stay (for the reason of being a non-dead project, despite us not knowing if it even works) but IllumOS + SmartOS (which works) got nuked.

Of the relatively few people I've spoken to who use OCaml in production at their companies, (at least) one of them was using it on Solaris as late as last year.

If there was a massive problem with it and no one was around to fix it, I guess it would make sense to withdraw support, but when the justification is simply to "simplify the configure script" I can't help but think that maybe it was an accident that Solaris got included in this patch?

**Comment by Armael** [comment]
I think this is most likely an oversight, in an attempt to cleanup dead platforms from the configure script before the migration to autoconf.
I expect that there will be no problem with merging any patches that you have that restore Solaris support.

**Comment by pmetzger** [comment]
Just an FYI, although I don't understand why, there seem to be users of 32 bit MacOS platforms out there who get upset when I try to obsolete support for older versions of MacOS in MacPorts. Note that I don't personally have much stake in that; I can't effectively test support for such platforms regardless.

**Comment by shindere** [comment]
Armaël Guéneau (2019/09/18 05:24 -0700):
> I think this is most likely an oversight, in an attempt to cleanup
> dead platforms from the configure script before the migration to
> autoconf.

That's absolutely correct, thanks for having taken the time to write it.
And, sorry to have broken something useful.

> I expect that there will be no problem with merging any patches that
> you have that restore Solaris support.

That's correct again.

I will just add that it would be great if we could somehow find a way to
do some CI testing on such platforms which we don't do at the moment.

**Comment by dbuenzli** [comment]
> I don't understand why, there seem to be users of 32 bit MacOS platforms out there who get upset when I try to obsolete support for older versions of MacOS in MacPorts

A bit OT but this is likely because of iOS 32-bit cross compilation (e.g. for ocaml [here](http://psellos.com/ocaml/compile-to-iphone.html)).

**Pull request merged**
