### PR TITLE
Consistently guard unistd.h via HAS_UNISTD

### PR DESCRIPTION
**Pull request by haesbaert**
This is missing in some spots, no functional changes.

### CODE REVIEW

**Comment by nojb** [comment]
> This is missing in some spots, no functional changes.

Sorry for the naïve question, but do these files compile if `unistd.h` is not available?

**Comment by haesbaert** [comment]
> > This is missing in some spots, no functional changes.
> 
> Sorry for the naïve question, but do these files compile if `unistd.h` is not available?

Not at all, it will miss basic declarations like `write(2)/read(2)`. I added just for completeness sake, I can also just pull the whole `HAS_UNISTD` out (sorry I was just being conservative on my first PR :) )

The header is actually in posix: https://pubs.opengroup.org/onlinepubs/7908799/xsh/unistd.h.html

```
gcc -c -O2 -fno-strict-aliasing -fwrapv -pthread -g -Wall -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections  -I./runtime  -D_FILE_OFFSET_BITS=64  -DCAMLDLLIMPORT=  -o runtime/afl.b.o runtime/afl.c
runtime/afl.c: In function ‘afl_write’:
runtime/afl.c:68:7: error: implicit declaration of function ‘write’; did you mean ‘fwrite’? [-Werror=implicit-function-declaration]
   68 |   if (write(FORKSRV_FD_WRITE, &msg, 4) != 4)
      |       ^~~~~
      |       fwrite
```

**Comment by shindere** [comment]
Is that to say that, on Unix systems, the proper behaviour would be that
the configure script fails if `unistd.h` is missing?

One other possible approach would be that ocnfigure tests that each
element that is actually required (like write) is indeed available, in
case it would be provided by another header.

**Comment by haesbaert** [comment]
> Is that to say that, on Unix systems, the proper behaviour would be that the configure script fails if `unistd.h` is missing? One other possible approach would be that ocnfigure tests that each element that is actually required (like write) is indeed available, in case it would be provided by another header.

I'd say that on Unix systems, `unistd.h` is always provided, and any source in `otherlibs/unix` should be able to include it without any ifdef guards. 
On the other hand,  code outside of it, like `runtime/domain.c` should either be able to work without a `unistd.h` (meaning it doesn't rely on a POSIX interface) or make it mandatory (making all other guards obsolete).
`runtime/platform.c` is one offender, it wants `unistd.h` for `usleep(3)`, so in a sense it is already implying it requires a POSIX system. Some other places are a bit more careful, for example, `runtime/fix_code.c` includes either `unistd.h` or `io.h` (I'm guessing this is windows stuff !?).

I don't think configure tests for each individual function are a way to go, this would be too cumbersome and difficult to maintain. From a quick glance of the offenders, I don't think we can build ocaml on any system without a unistd.h.

**Comment by haesbaert** [comment]
@dra27  pointed me to the following:
https://github.com/ocaml/ocaml/pull/10505
https://github.com/ocaml/ocaml/pull/10505/commits/c541731edb9b144ab33ff7833f8d5438195c9045

Since this issues are already being addressed and David knows much more about it than me, I'm gonna close this PR.
Sorry for the noise.

**Pull request closed without merging**
