### PR TITLE
Fix "open struct .. end" on clambda backend

### PR DESCRIPTION
**Pull request by trefis**
This has been broken since the introduction of the feature (so, 4.08).

@Octachron: You might want to consider this for 4.09.

### CODE REVIEW

**Comment by Octachron** [comment]
An one line miscompilation fix does seem like a valid candidate for 4.09 .

**Review by lpw25 — APPROVED** [review]
LGTM

**Comment by Octachron** [comment]
@trefis, would you mind moving the change entry to the 4.09 section?

Also by curiosity, if I follow correctly, the problem with the previous code was that it was breaking the invariant that access to previously defined global fields should access the field by position rather than by name. Am I right?

**Comment by lpw25** [comment]
Yeah, if you look at this line:

https://github.com/ocaml/ocaml/blob/f861766703aa62abe8aa294f245d3919f409fc2d/lambda/translmod.ml#L964

you can see where this invariant is relied upon. `lam` has been made by compiling the items of a structure and `defined_idents str.str_items` contains identifiers for those items. Those identifiers are out of scope, so it is relying on the `subst` to replace all of them with projections instead.

**Comment by Octachron** [comment]
Thanks for the explanation.

**Comment by objmagic** [comment]
Thanks for the explanation and thanks again for fixing it... @trefis

**Comment by trefis** [comment]
@Octachron: done.

**Comment by trefis** [comment]
Cherry-picked on 4.09.

**Pull request merged**
