### PR TITLE
Fix the syntax of a couple format boxes

### PR DESCRIPTION
**Pull request by Armael**

### CODE REVIEW

**Review by nojb — APPROVED** [review]
Looks good!

(I wonder if it would make sense to have a warning to detect illegal uses of '@' in format strings...)

**Comment by gasche** [comment]
My mistake, sorry...

**Comment by Drup** [comment]
@nojb If you mean typo-catching things like `[@` ... yes, but I'm not sure where we would stop.

If you mean detecting badly closed tags and boxes, It would have to be dynamic, which is a bit problematic on itself.

**Comment by gasche** [comment]
There is a `-strict-formats` flags which does some sanity checking and is not enabled by default. It doesn't seem to catch `[@`. There is an escape sequence, `%@`, for "I really want a `@` in my output", so you *can* in theory warn on any `@` that is not escaped and not part of a format conversion. But the compiler doesn't have enough context to know if a format string will be interpreted by Printf or Format, and users will never think of escaping their `@` for Printf-only usage.

**Pull request merged**
