### PR TITLE
Tidy-up Option.join

### PR DESCRIPTION
**Pull request by nojb**

### CODE REVIEW

**Comment by alainfrisch** [comment]
Time to resurrect https://github.com/ocaml/ocaml/pull/8584 😃

**Review by dra27 — APPROVED** [review]
You could circumvent Alain by changing the title to Tidy-up Option.join :wink:

**Review by let-def — APPROVED** [review]

**Comment by dbuenzli** [comment]
Funny that people equate "tidy-up" with making code less obvious to understand.

**Comment by dra27** [comment]
Tongue-in-cheek responses to Alain's tongue-in-cheek comment to one side, the approval was based on:

```
(let
  (previous_join/80 =
     (function param/82
       (catch
         (if param/82
           (let (o/81 =a (field 0 param/82)) (if o/81 o/81 (exit 1)))
           (exit 1))
        with (1) 0a))
```
vs
```
(let
  (new_join/83 = (function param/85 (if param/85 (field 0 param/85) 0a)))
```
for a function which should never need further inspection.

**Pull request merged**
