### PR TITLE
Avoid data race in method caching in ocamlrun

### PR DESCRIPTION
**Pull request by OlivierNicole**
When calling a method with the opcode `GETPUBMET`, the method address is resolved and possibly cached by modifying a word in the bytecode. If multiple domains execute the same `GETPUBMET` opcode concurrently, this is technically a data race. However, any integer value in the correct range is a safe value. Therefore we inform the compiler of potential concurrent accesses by using atomic accesses with relaxed memory order.

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
Thanks!  Looks good to me.  We can wait a few days for a second opinion.

**Comment by garrigue** [comment]
As a side remark, I kind of remember that the benefit of method caching was pretty limited for bytecode.
So an alternative might be to just turn it off when there is concurrency around.
This said, it may be worth doing a new round of benchmarks with recent architectures.

**Comment by xavierleroy** [comment]
We got a second  opinion (of sorts), so let's merge this PR.  We could reconsider the use of method caching in bytecode later.

**Comment by xavierleroy** [comment]
Cherry-picked to 5.0: e4db53043e

**Pull request merged**
