### PR TITLE
Format trivial fix

### PR DESCRIPTION
**Pull request by ale64bit**

### CODE REVIEW

**Comment by dra27** [comment]
Thanks! While we're here, do you want to consider the other possibles?

- `manual/tutorials/moduleexamples.etex:191:  functor (Elt: ORDERED_TYPE) ->`
- `manual/tutorials/moduleexamples.etex:236:  functor (Elt: ORDERED_TYPE) ->`
- `manual/tutorials/moduleexamples.etex:261:module WrongSet = (Set : functor(Elt: ORDERED_TYPE) -> SET);;`
- `manual/tutorials/moduleexamples.etex:278:  (Set : functor(Elt: ORDERED_TYPE) -> (SET with type element = Elt.t));;`
- `manual/tutorials/moduleexamples.etex:284:module AbstractSet2(Elt: ORDERED_TYPE) : (SET with type element = Elt.t) =`
- `manual/tutorials/polymorphism.etex:245:module List2: COLLECTION = Implementation;;`
- `manual/tutorials/polymorphism.etex:264:module List2: COLLECTION = Implementation;;`
- `manual/refman/modtypes.etex:295:        functor (A: S) (B: S with type t = A.t) ...`
- `tests/cross_reference_checker.ml:67:type ml_reference = { loc: Location.t; pos: int list; status:status }`
- `manual/tutorials/advexamples.etex:154:module Account (M:MONEY) =`
- `manual/cmds/ocamldoc.etex:244:module M : functor (A:Module) -> functor (B:Module2) -> sig .. end`
- `manual/cmds/ocamldoc.etex:248:module M (A:Module) (B:Module2) : sig .. end`
- `tests/cross_reference_checker.ml:21:      {loc:Location.t; label:string; ocaml:int list; tex:int list}`
- `manual/tutorials/objectexamples.etex:514:class oref (x_init:int) =`
- `manual/tutorials/objectexamples.etex:791:fun (x:c0) -> (x : c0 :> c1);;`
- `manual/tutorials/objectexamples.etex:796:% fun (x:c0) -> (x :> c1);;`
- `manual/tutorials/objectexamples.etex:804:fun (x:c0) -> (x :> c2);;`
- `manual/tutorials/polymorphism.etex:174:  let x:x = `X;;`
- `manual/tutorials/polymorphism.etex:180:  let l:x list = [`X; `X];;`
- `manual/tutorials/coreexamples.etex:310:type first_record  = { x:int; y:int; z:int }`
- `manual/tutorials/coreexamples.etex:311:type middle_record = { x:int; z:int }`
- `manual/tutorials/coreexamples.etex:312:type last_record   = { x:int };;`
- `manual/tutorials/coreexamples.etex:324:let look_at_x_then_z (r:first_record) =`
- `manual/tutorials/coreexamples.etex:327:let permute (x:first_variant) = match x with`
- `manual/tutorials/coreexamples.etex:335:In the first example, "(r:first_record)" is an explicit annotation`
- `manual/cmds/ocamldoc.etex:842:referenced as "{!tree.Node}" or "{!const:tree.Node}", or possibly`
- `manual/refman/exten.etex:158:and N:sig val x: int val y:int end = struct let x = M.x let y = 0 end`
- `manual/refman/exten.etex:2191:type t1 = lbl:int (** Labelled argument *) -> unit`
- `manual/refman/exten.etex:2516:  let sort (type x) (x:x list) =`

**Comment by xavierleroy** [comment]
What's wrong with "x: t" ?

**Comment by dra27** [comment]
@xavierleroy - sorry, my use of checkboxes rather than bullets made them look rather more like tasks - it was the result of grep'ing `manual/` for patterns which looked like they might want checking.

**Comment by gasche** [comment]
I don't understand the pull request. Have we decided that `(module Foo: Bar)` is not correct? Why?

**Comment by dra27** [comment]
@gasche - it is formatted inconsistently with two lines above it

**Comment by gasche** [comment]
I see. Let me merge this now, which doesn't prevent people from continuing the hunt for other cases if they wish.

**Pull request merged**
