### PR TITLE
warning about unused modules

### PR DESCRIPTION
**Pull request by UnixJunkie**
cf. http://caml.inria.fr/mantis/view.php?id=6362
patch from Alain Frisch

I hope I can test the feature via opam then

### CODE REVIEW

**Comment by lpw25** [comment]
I think that http://caml.inria.fr/mantis/view.php?id=6662 needs to be resolved if this is added, so that there is a way to avoid the warning when using a functor for its side-effects.

**Comment by UnixJunkie** [comment]
Are there some more steps necessary so that there is an opam switch to test this PR ?

**Comment by planar** [comment]
I think the opam switches are created automatically. @asvm do you confirm?

**Comment by let-def** [comment]
@UnixJunkie Could you add some tests? You can look at `testsuite/tests/warnings`.

I would be in favor of merging once tests are provided.

**Comment by UnixJunkie** [comment]
at last... I will have a look at how to add tests.

**Comment by lpw25** [comment]
> I would be in favor of merging once tests are provided.

I would like to reiterate my request that http://caml.inria.fr/mantis/view.php?id=6662 be resolved first, otherwise there is no way to avoid this warning when using functors for their side effects.

**Comment by gasche** [comment]
@lpw25 well, you will have my support if you have a patch ready in exactly two days. I support the feature, but have no time to implement a patch myself.

(The PR discusses a lot of different features and I'm not sure I would support them all, but at least both `module _ = ..` and `module () = ...` have my sympathy.)

**Comment by alainfrisch** [comment]
> otherwise there is no way to avoid this warning when using functors for their side effects.

You can do:

``` ocaml
include (F(X) : sig end)
```

Perhaps not very nice, but this makes the need for a dedicated feature not blocking in my opinion.  Moreover, I understand that "functors for their side effect" is a common idiom in some projects -- they can always decide to disable the warning (or use function taking packaged modules instead?) -- and otherwise such uses of functors remains very rare for most users.

**Comment by UnixJunkie** [comment]
unit test added

**Comment by alainfrisch** [comment]
Updated in #684

**Pull request closed without merging**
