### PR TITLE
Remove recursion in caml_raise

### PR DESCRIPTION
**Pull request by gadmm**
Fixes https://github.com/ocaml/ocaml/commit/15b9d006a4792c88d0c461e8280d932364cb1404#r41619894

No Changes needed

### CODE REVIEW

**Review by jhjourdan — APPROVED** [review]
Looks good to me. Thanks.

**Comment by gadmm** [comment]
To pass the last test, please add the `no-change-entry-needed` label or if you really want I'll add a Changes entry (then: will it be for 4.12 or trunk?).

**Review by xavierleroy — COMMENTED** [review]
Thank you for this PR, I was still worried about this recursion in `caml_raise`.

However I don't like the test, because it looks like it is testing something else.  Plus, I don't think we really need a test here.

Hoping nobody will get offended, I'll merge without the test, both in trunk and in 4.12,

**Comment by xavierleroy** [comment]
Manually merged in trunk (c22da1f0e) and 4.12 (dcaa25125).

**Pull request closed without merging**
