### PR TITLE
WIP: docs mapping from old configure parameters to new

### PR DESCRIPTION
**Pull request by dra27**
Apropos https://github.com/ocaml/ocaml/issues/8658#issuecomment-494332400 this is a quick reformatting of a document I put together when reviewing the autoconf PR. There are various TODO notes still in it (some will be because I noted the mapping but had review points requesting further changes).

Any comments as it stands, including where to put it, appreciated!

cc @shindere, @gasche

### CODE REVIEW

**Comment by stedolan** [comment]
not a review, but: thank you for this!

**Comment by gasche** [comment]
I think it would make sense to have this as `configure-HACKING.adoc`.

**Comment by shindere** [comment]
Gabriel Scherer (2019/05/21 10:18 -0700):
> I think it would make sense to have this as `configure-HACKING.adoc`.

Ow, I have to say, I really don't like the name, I'm sorry! :)

Would it be okay to integrate this quite nice piece of documentaiton as
an appendix of of `INSTALL.adoc` and reference it from the beginning of
the file?

If there is an agreement on this, I'm willing to do the integration.

Just one thing regarding the doc, @dra27. It is not completely true, I
think, that `--prefix` etc. are unchanged. In fact, the syntax changed
from `--prefix /foo/bar` to `--prefix=/foo/bar`.

Re:TARGET_BINDIR, the change has not been done yet. Shall I do the
change even if the underlying machinery is not there?

RE:`-libunwinddir` and `-libunwindinclude`, see `LIBUNWIND_LIB_DIR` and
`LIBUNWIND_LIB_DIR`, respectively.

`-x11include*`, `-x11lib*` and `-no-graph` are actually no longer supported
since the graphics package have been moved to its own repository.


`-dldefs*`: I think we should have a `DLLIB_INCLUDE_DIR` variable,
right?

`-default-safe-string` is now passed as the `DEFAULT_STRING` variable.

**Comment by dra27** [comment]
@shindere - autoconf-generated `configure` accepts both `--prefix=foo` and `--prefix foo` so from the perspective of the old `configure` the valid input hasn't changed!

**Comment by shindere** [comment]
David Allsopp (2019/06/07 03:06 -0700):
> @shindere - autoconf-generated `configure` accepts both `--prefix=foo`
> and `--prefix foo` so from the perspective of the old `configure` the
> valid input hasn't changed!

Makes sense, indeed.

Still, the former configure also accepted `-prefix`, wih only one dash,
which I think is not accepted any longer so there is at least this
change, right?

**Comment by dra27** [comment]
@shindere - no, autoconf-generated scripts are extremely liberal (probably because they predate the GNU getopt work - cf. the various `-long-name` options in GCC). `configure` accepts `-prefix FOO`, `-prefix=FOO`, `--prefix=FOO` and `--prefix=FOO`

**Comment by shindere** [comment]
David Allsopp (2019/06/10 00:42 -0700):
> @shindere - no, autoconf-generated scripts are extremely liberal
> (probably because they predate the GNU getopt work - cf. the various
> `-long-name` options in GCC). `configure` accepts `-prefix FOO`,
> `-prefix=FOO`, `--prefix=FOO` and `--prefix=FOO`

Okay good then!

So would it be okay to add this mapping as an appendix to
`INSTALL.adoc`?

**Comment by dra27** [comment]
@shindere - I don't have an opinion as to whether it wants to be a separate file or an appendix (I agree that describing them as hacking options feels a bit strange, but equally I can't think of another name!). The main thing is the various comments I tagged "dra27"!

**Comment by shindere** [comment]
David Allsopp (2019/06/10 00:51 -0700):
> @shindere - I don't have an opinion as to whether it wants to be a
> separate file or an appendix (I agree that describing them as hacking
> options feels a bit strange, but equally I can't think of another
> name!). The main thing is the various comments I tagged "dra27"!

I believe that at least some of them have now been addressed, right?

**Comment by dra27** [comment]
@shindere - I mean that the documentation in this PR needs updating to address the comments, not that work on `configure` necessarily needs doing!

**Comment by shindere** [comment]
David Allsopp (2019/06/10 00:57 -0700):
> @shindere - I mean that the documentation in this PR needs updating to
> address the comments, not that work on `configure` necessarily needs
> doing!

Okay sorry :)

**Comment by damiendoligez** [comment]
@dra27 Thanks for this list, it was very useful for preparing ocaml/opam-repository#14282.

**Comment by dra27** [comment]
I think this PR has served its purpose!

**Pull request closed without merging**
