### PR TITLE
Invalid reads from complex bigarrays (simple version)

### PR DESCRIPTION
**Pull request by xclerc**
This PR contains the first/simple implementation of the fix mentioned in https://github.com/ocaml/ocaml/pull/1729.

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by xavierleroy** [comment]
If we cherry-pick to 4.07 -- and I think we should -- the Changes entry should be moved to the 4.07 section.

**Comment by xclerc** [comment]
(Entry moved to 4.07.)

**Comment by xavierleroy** [comment]
Merged (cb20d9b) and cherry-picked  (7d4092b)

**Pull request merged**
