### PR TITLE
Fixing typos in various files

### PR DESCRIPTION
**Pull request by Fourchaux**
**Note:**
Typos found with https://github.com/codespell-project/codespell

After adding https://github.com/codespell-project/codespell/pull/795 :)

### CODE REVIEW

**Review by Armael — APPROVED** [review]
LGTM. Thanks!

**Comment by Armael** [comment]
Amusingly, check-typo is failing, because line 273 is now over 80 columns in `typing/rec_check.ml`. Could you adjust it so that CI passes?

**Comment by shindere** [comment]
@Fourchaux many thanks for having taken the time to do this.

Several small comments:

In testsuite/tests/lib-unix/common/cloexec.ml, you could also replace "ocaml compiler"
by "OCaml compiler".

In ocamldoc/Changes.txt, you could also replace parenthesis by parentheses,
I believe that would be more accurate

In typing/parmatch.ml, you correctly fixed function in "Finally, there are two compatibility
fonction", but could you perhaps also add a plural?

Regarding the files your PR fixes under build-aux, as you may have guessed
they come from the libtool package so they probably should be fixed there,
too. Would you be willing to do that?

And a few questions for the other developers: if we merge this now, should
we cherry-pick to 4.08 to make it easier to compare the two branches and
make sure no change that got into trunk has been forgotten in 4.08?

And, how aobut adding this to CI? Should it be added to Inria's CI or to
Travis?

**Comment by gasche** [comment]
If we merge now, me must cherry-pick to avoid silly merge conflicts between the two branches in the future.

Adding this typo-checking to the CI seems reasonable, and I would put it in the Travis CI (it's cheap and not portability-related), possibly in the same check as the current `check-typo` invocation.

**Comment by shindere** [comment]
Gabriel Scherer (2019/02/13 07:36 +0000):
> If we merge now, me must cherry-pick to avoid silly merge conflicts
> between the two branches in the future.

That's my understanding, too.

> Adding this typo-checking to the CI seems reasonable, and I would put
> it in the Travis CI (it's cheap and not portability-related), possibly
> in the same check as the current `check-typo` invocation.

Sounds good, too!

Given the accessibility issues in Travis I can't offer to do that myself
so let's hope someone will be willing to do that bit!

**Comment by gasche** [comment]
After all, @Armael approved...

**Comment by Armael** [comment]
I'm happy to merge after @Fourchaux implements the few remarks from @shindere.
I agree it would be nice to integrate codespell into check-typo, but that can be done in a separate PR.

**Comment by Fourchaux** [comment]
Applying @shindere suggestions.


For info, here is the (semi-manual) command used to get (and correct) the typos:

$ codespell -i 3 -w --skip="*.png,*.gif,./ocaml/boot,./ocaml/.git,./ocaml/manual/styles,./ocaml/manual/manual/htmlman" -L minimise,instal,contructor,"o'caml",cristal,pres,clos,cmo,uint,iff,te,objext,nto,nd,mut,upto,larg,exten,leage,mthod,delte,tim,atleast,langage,hten,iwth,mke,contant,succint,methids,eles,valu,clas,modul,que,classe,missings,froms,defaut,correspondance,differents,configury,reachs,cas,approche,normale,dur,millon,amin,oje,transfert

**Comment by gasche** [comment]
(I'm making a mental note that maybe the special-cases that come from French (in comments, I suppose?) could be removed by translating this content into English.)

**Comment by Armael** [comment]
@Fourchaux Thanks for the command, that's very helpful. Does it *modify* the files? Could you give a variant of the command that only reports the typos? I think that's what we would want to use in the CI (and have it fails if the list of typos is non-empty)

**Comment by Fourchaux** [comment]
@Armael 

Yes, this full command modifies the files (sacré gain de temps ...)

Suppress **-i 3 -w** to only get the typos.

@gasche 
Sadly, some french words are not inside comments.

e.g. (Approche)
From: manual/manual/biblio.etex

L24: \item  Guy Cousineau and Michel Mauny. {\it Approche fonctionnelle de

**Comment by Armael** [comment]
Cherry-picked on 4.08.

**Pull request merged**
