### PR TITLE
[bytecode] Correctly trace C_CALLN instructions

### PR DESCRIPTION
**Pull request by ghost**
Back in OCaml 4, trace was done using `printf`, so it was safe, when tracing `C_CALLN`, to print the number of arguments and then `/* fallthrough */` into the `C_CALL[1-5]` case to output a bounds-checked primitive name.

But in OCaml 5, trace is done in a buffer which is then output, and the logic was not adjusted, thus the first part of the trace was overwritten by the second part.

This PR attempts to restore the expected trace behaviour.

Not sure this is worth a `Changes` entry. Will add one if people request it.

### CODE REVIEW

**Comment by shindere** [comment]
Miod Vallat (2024/09/18 08:24 -0700):
> Not sure this is worth a `Changes` entry. Will add one if people
> request it.

I'd say it may be worh one, yes, as the change actually is user visible.

**Comment by ghost** [comment]
Done. And I threw a comment fix for free.

**Review by MisterDA — APPROVED** [review]

**Comment by MisterDA** [comment]
Since you're also cleaning dust you could include a15d1d5791189f3104ae572a163647cca41ac3d6 that I found out by reading the surrounding code.

**Comment by ghost** [comment]
Sure thing.

**Comment by shindere** [comment]
Thanks!

Approving on behalf of @MisterDA.

**Review by shindere — APPROVED** [review]

**Pull request merged**
