### PR TITLE
MPR#7323 fix ocamllex -ml, works with -safe-string option

### PR DESCRIPTION
**Pull request by bobzhang**
It is a low-risk fix, would be nice to get this into OCaml 4.04 (CC @gasche , @damiendoligez )

### CODE REVIEW

**Comment by gasche** [comment]
Did you check that, with this patch only, `ocamllex` now produces `-safe-string`-compatible lexers?

**Comment by bobzhang** [comment]
I checked with Facebook flow lexer, it compiles fine with -safe-string -ml.
See Lexing module, only lex_buffer is of type bytes, and I checked all use case of lex_buffer

**Comment by bobzhang** [comment]
Note the CI failure is not relevant to this change

**Comment by alainfrisch** [comment]
Cherry-picked to 4.04.

**Pull request merged**
