### PR TITLE
Labels after calls, call GC points and checkbound points (again)

### PR DESCRIPTION
**Pull request by mshinwell**
Revised version of #644 that includes the fixes to all backends.  I just forgot that hadn't been done before merging last time.

### CODE REVIEW

**Comment by mshinwell** [comment]
@dim is going to read this

**Comment by ghost** [comment]
I read the patch and saw nothing suspicious

**Comment by mshinwell** [comment]
In the light of @diml 's complete review and the approval of #644, I am going to merge this.

**Comment by gasche** [comment]
I believe that this PR breaks the PPC machine in our continuous integration server. It took a long time for me to catch it because the merge happened at the same time as Damien's 4.03 merge, so I didn't suspect it was this one.

It seems that you introduced a type-checking dependency from Arch to Cmm on some architectures, with changes such as:

``` diff
+++ b/asmcomp/arm64/arch.ml
@@ -35,12 +35,14 @@ type addressing_mode =
 (* Specific operations *)

 type specific_operation =
-  | Ifar_alloc of int
-  | Ifar_intop_checkbound
-  | Ifar_intop_imm_checkbound of int
+  | Ifar_alloc of { words : int; label_after_call_gc : Cmm.label option; }
+  | Ifar_intop_checkbound of { label_after_error : Cmm.label option; }
+  | Ifar_intop_imm_checkbound of
+      { bound : int; label_after_error : Cmm.label option; }
   | Ishiftarith of arith_operation * int
-  | Ishiftcheckbound of int
-  | Ifar_shiftcheckbound of int
+  | Ishiftcheckbound of { shift : int; label_after_error : Cmm.label option; }
+  | Ifar_shiftcheckbound of
+      { shift : int; label_after_error : Cmm.label option; }
   | Imuladd       (* multiply and add *)
   | Imulsub       (* multiply and subtract *)
   | Inegmulf      (* floating-point negate and multiply *)
```

This is problematic for two reasons:
1. The dependency is only present on some architectures, so running `make depend` from another architecture (typically amd64) will not take it into account. I tried adding dummy dependencies from Arch to Cmm on amd64, but it doesn't work because...
2. Cmm already has an implementation dependency on Arch, so adding a dependency the other way around creates circular dependencies if you're not careful.

I think the circular dependency needs to be solved. (But it's not clear to me that this requires a revert for now.)

**Comment by alainfrisch** [comment]
I've applied an ad hoc fix for the power backend to restore CI for them at least.

**Comment by alainfrisch** [comment]
Note that `check_all_arches` is not robust enough to catch such problems, because it only removes .ml/.cmo files corresponding to platform-specific units.  It would for instance leave cmm.cmi from the previous build.  One could add a `rm -f asmcomp/*.cm*` to the rule, but this will significantly slow it down.  I'd still be in favor; let's be on the safe side here.

**Comment by alainfrisch** [comment]
An another fix for arm64 (57b8917)

**Pull request merged**
