### PR TITLE
Rename Changes => CHANGES.md

### PR DESCRIPTION
**Pull request by nojb**
See [MPR#7875](https://caml.inria.fr/mantis/view.php?id=7875).

This PR simply declares that markdown will be the official format for the "Changes" file (that file is already written in almost correct Markdown). If this is accepted, there are several cleanups that should be done to polish the formatting, but better to do those in a later PR to avoid conflicts in this one.

One point that needs attention is the distinction between backwards compatible and incompatible changes, where the current marker (a '*' heading) is not rendered differently in markdown.

### CODE REVIEW

**Comment by shindere** [comment]
Wouldn't it be better to bring the content to right markup first and
then do the renaming?

**Comment by nojb** [comment]
Yes, I can do that, but it would be nice to agree on the choice of markdown first.

**Comment by gasche** [comment]
Relevant:

- https://github.com/ocaml/ocaml/pull/1014, with a tool to automatically process and structure Changes entries (not merged, people were worried by the bureaucracy)
- https://github.com/ocaml/ocaml/commit/e63e9c69894aeb6283c54beb3a9c3fe95e510922 a (merged) script (`tools/markdown-add-pr-links.sh`) to turn GPR#foo and PR#bar references into Markdown links. I use it on various occasions, typically for content to put on Github, from either `Changes` or `News`.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/11/24 00:44 -0800):
> Yes, I can do that, but it would be nice to agree on the choice of
> markdown first.

I'm personally fine with that choice and think if other developers
agree, then it's better to change the content first than to do the
renaming and to have a file that wrongly claims to be mardkown and is
not for a few commits. Well I realise I'm picky here.

**Comment by mshinwell** [comment]
Related to @gasche 's comment above, I should point out that the current format of the `Changes` file really is problematic when trying to maintain stacks of patches, such as those currently in progress for the gdb work.  There are repeated conflicts upon almost every rebase.  I do wonder if we should again consider generating this file somehow upon a release.

**Comment by nojb** [comment]
See https://github.com/haskell/cabal/issues/5625 for some related discussion.

**Comment by nojb** [comment]
Closing this, as we first need to arrive at a consensus on the general handling of the Changes file.

**Pull request closed without merging**
