### PR TITLE
Deprecate the addr typedef

### PR DESCRIPTION
**Pull request by dra27**
Implements @xavierleroy's suggestion in https://github.com/ocaml/ocaml/issues/8892#issuecomment-524566279

CI will fail as this depends on #8895

### CODE REVIEW

**Comment by dra27** [comment]
See also [precheck#295](https://ci.inria.fr/ocaml/job/precheck/295/), which I'm using as an easy way of seeing the clang deprecation warnings.

**Comment by stedolan** [comment]
If we need to add deprecation warnings to avoid breaking code that uses things defined with `CAML_INTERNALS`, then what's the point of having `CAML_INTERNALS`?

**Comment by dra27** [comment]
The worry here is that with a broken public definition (`Is_young`) there’s the smallest chance that the `typedef` has been cheekily used in the wild, so the deprecation is a belt-and-braces nod to that.

**Review by xavierleroy — APPROVED** [review]
Personally I'm happy with this PR.  

I can understand @stedolan and others who would just remove the typedef.  But there may be other typedefs that we want to deprecate shortly, so it's good to have some infrastructure in place for that.  

Bottom line is that I'm approving but not merging so that others can comment further.

**Comment by xavierleroy** [comment]
Silence means assent.  Also, CI precheck has no problem with this code.  So, I'll merge.

**Pull request merged**
