### PR TITLE
Minor runtime/caml/m.h.in simplification

### PR DESCRIPTION
**Pull request by ghost**
When the compiler configuration was switched to autoconf a bit more than 5 years ago, the macros defining the 64-bit integer types and their `printf` format specifiers were put in `runtime/caml/m.h.in` for substitution by autoconf, yet they are not provided by autoconf and instead inferred in `runtime/caml/config.h`, and the generated `runtime/caml/m.h` always ends up with `/* #undef WHATEVER */` lines for them.

This trivial PR removes these unused defines from `runtime/caml/m.h.in`, as well as the non-applicable, thus confusing, comments.

Not sure this is worth a `Changes` entry.

### CODE REVIEW

**Comment by shindere** [comment]
Many thanks for looking into this!

I definitely agree that there is room for improvmeent here.

My only point of doubt is on whether the proposed fix is what we want to
do.

Rather that what you propose, wouldn't it be better to move the logic
which currently lives in `runtime/caml/config.h` so `configure.ac` so
that the current substitution logic would actually become useful, rather
than deletingit?

**Comment by ghost** [comment]
I am not sure it is possible to move this from `runtime/caml/config.h` to `configure`. There are some games being played with the value of `__USE_MINGW_ANSI_STDIO` in `runtime/caml/config.h` depending on whether `CAML_INTERNALS` is defined or not, which make these defines not exactly compile-time constants when targeting mingw64.

**Comment by shindere** [comment]
Miod Vallat (2024/01/22 02:55 -0800):
> I am not sure it is possible to move this from `runtime/caml/config.h`
> to `configure`. There are some games being played with the value of
> `__USE_MINGW_ANSI_STDIO` in `runtime/caml/config.h` depending on
> whether `CAML_INTERNALS` is defined or not, which make these defines
> not exactly compile-time constants when targeting mingw64.

Oh, is it really the case that we don't necessary info at configure
time?

I would have thought that it would be guessable, be it at the price of
adding a configure-ime compiler test?

@dra27 do you have any opinion on this?

**Comment by MisterDA** [comment]
Since we're discussing autoconf and headers, I'd like to note that idiomatic autoconf usage seems to have all the defines and substitutions in a single header. The quote below documents usage of `autoheader` to generate headers. We're not using this tool, but if we were, or if we were leading towards idiomatic autoconf, we'd probably have to merge

```m4
AC_CONFIG_HEADERS([runtime/caml/exec.h])
AC_CONFIG_HEADERS([runtime/caml/m.h])
AC_CONFIG_HEADERS([runtime/caml/s.h])
```

into a single

```m4
AC_CONFIG_HEADERS([runtime/caml/config.h])
```

and rename the current `runtime/caml/config.h` into the suggested `runtime/caml/config_post.h`.

> It is recommended that only one input file is used. If you want to append a boilerplate code, it is preferable to use `AH_BOTTOM([#include <conf_post.h>])`. File `conf_post.h` is not processed during the configuration then, which make things clearer. Analogically, `AH_TOP` can be used to prepend a boilerplate code. 

The substitutions done by `AC_CONFIG_HEADERS([runtime/caml/version.h])` should be made with `AC_CONFIG_FILE` instead.

The relevant section of the manual is [4.9 Configuration Header Files](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/html_node/Configuration-Headers.html).

**Comment by shindere** [comment]
I would really not mind getting rid of `m.h`, `s.h` etc., whose
distinctionis not always so clear anyway, I think.

The only potential blocker I can see is related to
backward-compatibility, if third-party code directly includes one of
those headers.

**Comment by shindere** [comment]
@dustanddreams you wrote "which make these defines not exactly compile-time constants"
but am I correct that what you really meant was *cinfigure*-time constants?

**Comment by dra27** [comment]
I'm sorry I had some notes on this for ages ago which I realise I hadn't posted:

`exec.h` is an internal header, albeit an installed one: I'm not convinced anything in it should get pulled into `config.h`. Granted, we could have a `config_private.h` or something, but this feels like we're starting to work for the tool, rather than it work for us?

However, prior to #1127, there was indeed only one config.h (m.h and s.h were used internally by the compiler, but users are supposed to assume config.h only.). The simplification in that PR was partly the good philosophical idea that installation should not generate files (`config.h` was munged at installation) and partly in preparation for the switch to autoconf. I could see that merging s.h.in and m.h.in could be a good change.

> The substitutions done by `AC_CONFIG_HEADERS([runtime/caml/version.h])` should be made with `AC_CONFIG_FILE` instead.

Is that just a matter of taste, or is there a technical reason? That said, that might also be a solution to my objection with `exec.h.in`.

**Comment by ghost** [comment]
> @dustanddreams you wrote "which make these defines not exactly compile-time constants" but am I correct that what you really meant was _cinfigure_-time constants?

Yes, that should-read "configure-time" indeed.

**Comment by MisterDA** [comment]
> `exec.h` is an internal header, albeit an installed one: I'm not convinced anything in it should get pulled into `config.h`. Granted, we could have a `config_private.h` or something, but this feels like we're starting to work for the tool, rather than it work for us?

The Autoconf manual recommends to separate the file containing the `#undef SYMBOLS` directive from other headers. See [4.9.1 Configuration Header Templates](https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/Header-Templates.html):

> If you absolutely need to hook it to the config header itself, please put the directives to a separate file, and `#include` that file from the config header template.

> I could see that merging `s.h.in` and `m.h.in` could be a good change.

Agreed, but probably not relevant to this PR.

> > The substitutions done by `AC_CONFIG_HEADERS([runtime/caml/version.h])` should be made with `AC_CONFIG_FILE` instead.
> 
> Is that just a matter of taste, or is there a technical reason? That said, that might also be a solution to my objection with `exec.h.in`.

The technical reason would be linked to a tool we're not using: `autoheader` reads the generated `configure` file, looks for all `AC_DEFINES`, builds the list of macros, and generate the `#undef SYMBOLS` list with documentation. It only looks at the first `AC_CONFIG_HEADERS`, so that would also be a justification towards merging `s.h.in` and `m.h.in` if we're leaning to more idiomatic Autoconf (even if we don't use `autoheader` yet).

> It is recommended that only one input file is used. If you want to append a boilerplate code, it is preferable to use `AH_BOTTOM([#include <conf_post.h>])`. File `conf_post.h` is not processed during the configuration then, which make things clearer.

[4.9.2 Using `autoheader` to Create `config.h.in`](https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/autoheader-Invocation.html)

Circling back to this PR —we've been a bit side-tracked— I think it can be merged as-is, we'll hack Autoconf and the headers later.

**Comment by shindere** [comment]
Antonin Décimo (2024/05/15 23:08 -0700):
> Circling back to this PR —we've been a bit side-tracked— I think it
> can be merged as-is, we'll hack Autoconf and the headers later.

Indeed! Funny/weird how much we discussed when the code is so simple!

Sorry about that @dustanddreams!

**Review by shindere — APPROVED** [review]

**Pull request merged**
