### PR TITLE
4.x: protect memory-safety in the event of Lazy.force races

### PR DESCRIPTION
**Pull request by gasche**
This is a 4.x fix for issue #13430.

cc @edwintorok, @lthls

### CODE REVIEW

**Review by lthls — APPROVED** [review]
A few details that are missing from the comments:
- We never short-cut a forward block pointing to a lazy block, so we cannot end up modifying a lazy block other than the initial one.
- Our closure may not be `raise_undefined`, it can also be another `raise_e` closure set by another thread. But a bit of induction would prove that this closure also raised `Undefined`, so we're fine.

I tend to think that a link to the bug report and this PR would be helpful; it could not only replace part of these comments but also gives some useful context.

The code is fine though, so as long as you don't change it you can assume that my approval still stands.

**Comment by gasche** [comment]
> Our closure may not be `raise_undefined`, it can also be another `raise_e` closure set by another thread.

I don't see how this can happen after the PR, do you have an example?

(I wonder if it's fully reasonable to torture our brains to explain precisely what is going on, when the less-precise explanation is reasonable and suffices to prove memory safety. But we are both nerd-sniped at this point so let's go on.)

**Comment by lthls** [comment]
> > Our closure may not be `raise_undefined`, it can also be another `raise_e` closure set by another thread.
> 
> I don't see how this can happen after the PR, do you have an example?

Yes:
- Thread 1 starts forcing, gets interrupted while computing the result
- Thread 2 starts forcing, gets the `raise_undefined` closure, calls it, catches the exception, sets the closure to `raise_e` with the `Undefined` exception
- Thread 3 starts forcing, gets the `raise_e` closure from thread 2, calls it, catches the exception, gets interrupted during allocation of `raise_e`
- Thread 1 resumes, changes the tag of the block, then yields again
- Thread 3 resumes, finds a tag mismatch and raises

Of course, in this case the `raise_e` function is mathematically equivalent to `raise_undefined`; and I think that it is true that any function we could have read here would have been equivalent to `raise_undefined`. But you wouldn't be able to test that with physical equality. The conclusion is the same though: if we reach this point `e` must be `Undefined`. The proof is just a bit more complex than the comment makes it look like.

> (I wonder if it's fully reasonable to torture our brains to explain precisely what is going on, when the less-precise explanation is reasonable and suffices to prove memory safety. But we are both nerd-sniped at this point so let's go on.)

I think it's fine to discuss in the PR as much as we want; it also helps future people (including ourselves) that want to know why the code is that way and check if other cases were covered. But I agree that we don't necessarily need to reflect every subtle detail in the comments; that's also why I suggested adding a link to the github issue/PR instead of too verbose comments.

**Comment by gasche** [comment]
I see, thanks! I made several attempts at writing a proof argument I found convincing, but they all crumbled down into a pit of untold complexity, and I decided that it's better to keep the source comments simple, with an explicit reference to the present discussion as you suggested.

**Comment by gasche** [comment]
For the record, here is my best attempt at writing down the argument for why we always have `e = Undefined` in the error case if we observe `tag <> Lazy_tag` at this point.

Let us write that a thread of execution (or asynchronous callback, etc.) "reads" a thunk closure when it dereferences the first argument of a block with tag Lazy_tag, and "writes" a thunk closure when it modifies this block. We further write that a thread T1 reads a thunk closure from T2 if the closure read by T1 is the closure set by T2 (no one has set the thunk closure in the meantime).

Now consider a set S of thread that observe (tag = Lazy_tag) and entered the `force_lazy_block` or `force_val_lazy_block` functions for the same thunk, in the case where one of them eventually observes `tag <> Lazy_tag` in the error-handling path of `force_lazy_block` (in particular, S is not empty). We want to prove that that one thread must have observed the error `Undefined`, and not any other exception.

The thunk closure read by any thread in S was written by one of the other threads in S, or is the closure that was initialized for the thunk. (No other function writes to thunk closure.) Because both functions atomically write `raise_undefined` in the thunk closure immediately after reading the thunk closure, exactly one thread in S read the initial value. We call it the "first" thread in S, because all other threads in S have read the thunk closure after the thunk thread.

Notice that all writes that set the thunk closure are in `force_lazy_block`, and they set it to a closure that always raises, either `raise_undefined` or `raise_e`. In particular, if a thread in S read the thunk closure set by another thread in S, then it has read a closure that always raises.

If we observe `tag <> Lazy_tag` in the error-handling case, then necessarily some thread in S succeeded to call `make_forward`, and in particular its `closure ()` call did not raise an exception. This thread cannot have read the thunk closure set by another thread in S (as such a closure will raise an exception), therefore it must be the first thread. In particular, the initial thunk closure did not raise an exception, it returned a value.

Now we can prove that any thread in S that sets the thunk closure sets it to a closure that raises `Undefined`, and no other exception. The proof proceeds by induction on the "T1 reads from T2" relation:

- the initial thread reads from no other threads, and it set the thunk closure to `raise_undefined`

- if T1 reads the thunk closure from T2, by induction hypothesis the `closure` it read always raises `Undefined`; if we are in `force_val_lazy_block` this interrupts the computation (so this thread does not set the thunk closure), if we are in `force_lazy_block` we go to the error path with `e` being `Undefined`, and the thread sets the thunk closure to `raise_e` which always raises `Undefined`.

From this we can conclude that at the point in the error path where we observe `tag <> Lazy_tag`, we must have read the exception `Undefined`:

- we cannot be in the first thread, as it does not reach the error path
- so we must have read the thunk closure set by another thread in S, which always raises `Undefined`

**Pull request merged**
