### PR TITLE
Add an include guard to yacc/defs.h

### PR DESCRIPTION
**Pull request by ksromanov**

### CODE REVIEW

**Comment by dra27** [comment]
It's good hygiene, regardless, but did this actually cause a bug or issue?

**Comment by ksromanov** [comment]
> It's good hygiene, regardless, but did this actually cause a bug or issue?

No, of course this ancient harmless code didn't cause any bug. We have an internal tool, that got confused by 

```c
#ifndef DEBUG
#define NDEBUG
#endif
```

in 4.14 version https://github.com/ocaml/ocaml/blob/81d18c16e898fe99f3325b5ae9f8cbde322093fe/yacc/defs.h#L18

The tool decided that it is a misprint in an include guard, and suggested to replace it with

```c
#ifndef DEBUG
#define DEBUG
#endif
```

:-)

Since it is too late to change 4.14, I am sending the PR to trunk.

**Review by yawaramin — APPROVED** [review]

**Comment by gasche** [comment]
Merged, thanks everyone!

**Comment by dra27** [comment]
If it would be helpful to have on 4.14, it can be cherry-picked. There’s likely to be a 4.14.3 at some point

**Comment by Octachron** [comment]
Let's cherry-pick anyway: this is a safe change that would only improve the 4.14.3 release.

**Comment by ksromanov** [comment]
Please, do not worry about us — we have an override in our include guard check.

Thanks for supporting the Compiler.

**Comment by Octachron** [comment]
Cherry-picked to 5.2 too on the basis that this a safe and harmless improvement.

**Pull request merged**
