### PR TITLE
Fix freshening substitutions

### PR DESCRIPTION
**Pull request by lpw25**
This fixes an issue where freshening substitutions might be applied to module types that had already been freshened. In the case of an identifier collision this produced the wrong result. This bug has probably been around for a long time (maybe since module aliases were added) but we only happened to see an actual collision recently.

The actual bug fix is in `Env.scrape_alias`: the old code sometimes returned a signature without the freshening substitution applied and sometimes with. The result of scrape_alias was later freshened, which meant that it could be freshened twice. If the freshened IDs happened to collide with distinct unfreshened identifiers that happened to have the same name then the signature gets corrupted (due to the amount of "happened to" needed to trigger this, the bug was rarely hit).

The fix here is to ensure everything is always freshened immediately, using the new `Subst.Lazy` module to do so efficiently. This allows us to delete the old and quite fiddly code that threaded the freshening substitution around the place.

### CODE REVIEW

**Review by stedolan — APPROVED** [review]
The change looks good to me, but since I was involved in this patch you might want to find someone else to review as well.

**Review by mrmr1993 — APPROVED** [review]
LGTM.

**Comment by gasche** [comment]
This needs a rebase and a Changes entry.

**Comment by lpw25** [comment]
Rebased and Changes entry added

**Pull request merged**
