### PR TITLE
First class module dynlink

### PR DESCRIPTION
**Pull request by chambart**
Adds an interface to get the first class module out of an cmo/cma/cmxs file.
This was started as a joke. I continued it a bit, and push it here to discuss the overall idea.

This adds a syntax to get a type witness of a module:
  `(sig Module:Module_type)` of type `(module Module_type) sig_t`
and adds two functions to dynlink: `load_modules : string -> module_info list` and `check_module : module_info -> 'a sig_t -> 'a option`

The witness contains only the digest of the cmi file for `Module` and `check_module` compares it with the digest of the interface a module implements. That way there is no need to add any new dependency to dynlink.

### CODE REVIEW

**Comment by gasche** [comment]
@chambart are you planning to do something with this feature? I find it very nice, and regret its absence whenever I'm considering using `dynlink` to do something.

**Comment by chambart** [comment]
@gasche I'm ready to update it to recent compiler and spend some time improving the interface. Last time it was discussed in a developer meeting, it was agreed that some 'real' feedback is needed to consider this for inclusion. Since I didn't have a serious use case for dynlink for quite some time and nobody else really tried, this is stalled since then.

I'm ready to spend some more time to bring that to a mergeable state, but I need to know first if this would be effectively accepted.

Note that I also need some feedback on the Dynlink module additions, and in particular, its semantics: when to effectively run the initialisation code.

**Comment by chambart** [comment]
By the way, one thing that I really don't like in this proposition is the necessity to have an explicit path for the module type:

```
module type T = module type of Chose
let crc : (module T) sig_t = (sig Chose:T)
```

or

```
module type T = module type of Chose
let crc : (module T) sig_t = [%signature Chose T]
```

The module type `T` seems completely useless, yet it is needed since there is no module type for `Chose`.

The various ways to avoid needing `module type of Chose` are:
- Restrict the construction to the structure level and declare a module type at the same time as the value. Since the module type is needed also to use the value, it means that the declared module type cannot be hidden.
- Implicitly declare a module type for each compilation unit.

I don't like the first one, and I don't know yet how to do the second well.

**Comment by lpw25** [comment]
> Just a dumb question is it really costly to really test the inclusion of the module type at runtime instead of using the hash?

I wouldn't even be confident it is semantically well defined in the general case. It is getting pretty close to trying to do type-checking dynamically which has all sorts of issues in the presence of abstraction. It might be all right with some restrictions (e.g. the module type only refers to types/modules that are defined globally) to try and make sure that there are no issues of abstraction involved, but it is not clear to me that those restrictions are any better than just referring to a .cmi file.

**Comment by chambart** [comment]
This would indeed be quite tricky and require that a program using dynlink essentially link the whole typechecker.
If we restrict to equality, we can imagine still using a hash of a module type without needing an explicit .cmi file, but after some discussion with @garrigue, it seems to be a nightmare in the current codebase.

Also this might be too cumbersome to use across different projets/repository as the same hash is required, but not necessarily the same file: it could be copied in the different projects.

**Comment by gasche** [comment]
> current ocaml build system must be extended to support the compilation of these plug-ins since you need to specify to use the .cmi that have been installed by the main tool.

Do you? I was hoping to be able to write, for example

``` ocaml
include (module type of Choose)
```

as the `.mli` of any of the modules intended for dynlinking. Wouldn't this work?

**Comment by garrigue** [comment]
@gasche This probably wouldn't work. The embedded hash in the cmo/cmx is that of the cmi used at compile time.
But you can easily write a wrapper.

``` ocaml
include Chose
```

and compile it along with the intended `.cmi`.

But now I understand what @bobot means: in its current form, this feature only really supports loading an already known module. If you want to be able to load several units, you need to force them to share the same `.cmi`. Technically, this is doable by giving them the same name, and compiling with a directory containing the `.cmi`, and also an `.mli` with the same name (otherwise the `.cmi` will be ignored). This doesn't sound ideal. So it would be nice to be able to declare at compile time that a physical module is actually using a specific `.cmi` to be found in the path.

**Comment by gasche** [comment]
Regarding real-world application, I wonder how much of [ocaml_plugin](https://github.com/janestreet/ocaml_plugin) could be superseded by this feature -- in a nicer way.

**Comment by lpw25** [comment]
> I wonder how much of ocaml_plugin could be superseded by this feature

Probably not that much. I think most of the work which ocaml_plugin does is in recreating the environment for compiling the plugin -- which it does by carrying around a tarball containing all the required cmi files (and also the compiler itself if required). I don't think ocaml_plugin actually supports loading `.cmxs` files directly: it insists on compiling all the `.ml` files it uses by hand to ensure that they are built in the desired environment.

**Comment by chambart** [comment]
Is there a reason why the name of the module is part of the hash ? Otherwise building plugins with a copied (or `ln -s`) and renamed `.mli` file would be ok for a compatible dynlink without too much build system complexity.

**Comment by v-gb** [comment]
Without testing the feature, I suspect it can't be used in ocaml_plugin nicely. The usual pattern is probably to have in some lib:

plugin_intf.ml:

```
module type S = struct
  .. (* the module type of loaded plugins *)
end
let univ_constr = ..
module Plugin_loader = OCaml_plugin.Std.Ocaml_compiler.Make(struct type t = (module S) let path = "Lib.Plugin_intf.S" .. end)
```

It seems this feature requires both to have a toplevel cmi of the relevant interface, and to name that interface as a signature, but neither of these are nice here.
First, having to have a cmi is annoying. We don't even accept mlis without ml here, so I suppose we'd need to change the build system. Second, relying on [module type of] to "copy" that cmi as a signature doesn't work. Anyone who builds with libraries that are "packed" with module aliases can't do that, as the module type of an alias contains additional type equalities. And that would prevent us from fixing [module type of] to stop creating incompatible signatures.

Here is an idea I haven't thought through: what if this sig_t, instead of being a digest, was essentially a cmi for the given interface (or both perhaps), along with [val cmi : _ sig_t -> string] or something? Would that help?
(the way to force the compiler to build a .ml with a given cmi is -intf-suffix .ml by the way, assuming the names match)

**Comment by alainfrisch** [comment]
Is anyone interested to shepherd this PR?  It has been around for 3 years, and the discussion died more than one year ago.  If nobody steps up, I suggest to close it.

**Comment by mshinwell** [comment]
I still reckon this would be a nice addition.

**Comment by alainfrisch** [comment]
> I still reckon this would be a nice addition.

I don't feel a lot of momentum to push the proposal forward.  Are you willing to shepherd it?

**Comment by mshinwell** [comment]
@alainfrisch I don't have time to at the moment, but others may...

**Comment by xavierleroy** [comment]
Two years after @alainfrisch's three-years-after ping, this PR is still dormant, so I'm taking the liberty to close it.

For the record: I, like many others, am interested in type-safe dynamic loading, and intrigued by the proposed approach.  If there is enough interest and developers willing to spend time on the design and implementation, I suggest to turn it into a roadmap item proposal and discuss at a developer's meeting.

**Pull request closed without merging**
