### PR TITLE
Added an update function for Hashtbl and Ephemeron and some tests for it

### PR DESCRIPTION
**Pull request by craff**
This partially solves #7644 by adding update for hashtbl and ephemeron which
is a function already present in Map:

 Hashtbl.update: ('a, 'b) t -> 'a -> ('b option -> 'b option) -> unit

This allows clean code and easier transition between Map and Hashtbl.
We can observe some speed increase (only for large keys and/or frequent removals) because
 - the hash is computed only once (instead of two when find fails and add is done after) 
 - we traverse only once the bucket when we do a removal.

Unfortunately, part of this gain if often lost by managing the option type and passing a closure to update.

I will add a particular case later for the frequent pattern (in Map, Hashtbl and Ephemeron) 
  find_add tbl key data =
    try Hashtbl.find tbl key
    with Not_found -> Hashtbl.add tbl key data; data

I will do that after this patch has been reviewed (committed or not as the reviewer prefers)

### CODE REVIEW

**Comment by craff** [comment]
I forgot to mention: for ephemeron I moved to a mutable bucket list as for Hashtbl, otherwise update
was too painful.

**Comment by damiendoligez** [comment]
@craff Please rebase onto trunk.

**Comment by craff** [comment]
OK, there is indeed no hurry...  This is done ...

**Comment by craff** [comment]
I am not sure the rebase was good ... If it is dirty, I better close this PR and do a clean PR from trunk after cherry-picking my commit in trunk ?

**Comment by shindere** [comment]
Christophe Raffalli (2017/10/02 15:18 +0000):
> I am not sure the rebase was good ... If it is dirty, I better close
> this PR and do a clean PR from trunk after cherry-picking my commit in
> trunk ?

You shouldn't need to do that to get a clean history.

First, on your branch do a

git reset --hard HEAD^

to reset your branch to the pre-merge state.

Then:

git checkout trunk

git pull

git checkout yourbranch

git rebase trunk

git push -f your-public-git-repositoy

And you are done.

There may be an even shorter way, this is just the one I use and it
works well for me.

**Comment by alainfrisch** [comment]
@craff Could you try @shindere instructions to produce a clean rebase?

**Comment by xavierleroy** [comment]
18 months later, any news on this PR?  If @craff doesn't keep it alive and the stdlib review committee doesn't adopt it, we should close it.

**Comment by nojb** [comment]
Closing this, as the PR is seriously out of date and no sign of activity. Speak up if you are interested in this!

**Pull request closed without merging**
