### PR TITLE
bump magic numbers and bootstrap to catch up with branch 4.08

### PR DESCRIPTION
**Pull request by damiendoligez**
In the process of preparing 4.08.0+beta1, I bumped the magic numbers on the 4.08 branch (following the release-checklist instructions) but now they need to be updated in trunk too.

Next time I'll bump them a little earlier, just before branching.

### CODE REVIEW

**Review by shindere — APPROVED** [review]

**Comment by trefis** [comment]
It looks like this PR is bumping `cmi_magic_number` to `Caml1999I024`.
As it turns out, that value is already used in [4.07.1](https://github.com/ocaml/ocaml/blob/4.07/utils/config.mlp#L87).

It's probably safer to just bump everything to `Caml1999*025`.

**Comment by damiendoligez** [comment]
Did the cmi format change between 4.07.1 and 4.08.0+beta1 ? If so, I have to bump the numbers in the 4.08 branch too. If not, we can keep 024, even in trunk.

@trefis @let-def @lpw25

**Comment by lpw25** [comment]
> Did the cmi format change between 4.07.1 and 4.08.0+beta1?

Yes, at the very least #1610 would affect the cmi format.

**Comment by trefis** [comment]
As well as #2147.
Even if that weren't the case, the cmt magic number was also `...24` in 4.07.1, and there are certainly a few more PRs that changed the typedtree.

In any case, I'd argue that even if it didn't change, we should just bump the number: for example, merlin's backend (i.e. the version of ocaml it recognizes) is currently selected by looking at the cmi magic number.
Having the same magic number span two versions is likely to cause trouble (if we have just one copy of the typer for two versions of ocaml, then for one of them we'll most likely produce incorrect results).

**Comment by shindere** [comment]
The magic numbers have been bumped both on trunk (6da5262dd184d2)
and 4.08 (e413426bc766c).

**Pull request merged**
