### PR TITLE
Remove ocamldoc's `literate` and `todo` generators

### PR DESCRIPTION
**Pull request by shindere**
(This is submitted in preparation for the merge of `ocamldoc/Makefile` into
the root `Makefile`, of which a provisional implementation can be
found
[here](https://github.com/shindere/ocaml/tree/merge-ocamldoc-makefile).)

It is @Octachron's belief that the targets and recipes this PR proposes to
remove have not been used for the last decade or so. If they are
however considered useful, onemay want to work on integrating them
to the testsuite somehow, but since this will represent some work let's
first decide whether they are actually useful or not.

Also, if we follow the removal road, then the question of how far we should
go arises. Indeed, given that ocamldoc's generators are not installed, one
may wonder whether it's useful to build them and then, if not, whether they
shouldn't simply be deleted, too.

(For the moment I'll use a no-changes-entry-needed label but I can
definitely add a proper Changes entry if the PR is ocnsidered useful)

### CODE REVIEW

**Review by gasche — APPROVED** [review]
This looks fine to me. There is a special pleasure for PRs that only remove lines of code.

**Comment by gasche** [comment]
> given that ocamldoc's generators are not installed, one
may wonder whether it's useful to build them and then, if not, whether they
shouldn't simply be deleted, too

I was not sure what you mean by "generators" (surely the ocamldoc backends are necessary to keep around). I looked. You mean the modules in `generators/` in the source tree, which apparently are two alternative backends/plugins to generate a TODO list, around 500 lines of code in total. If they are not installed nor used in the manual build process (I don't think they are), then yes it would be fine to remove them.

**Comment by shindere** [comment]
Gabriel Scherer (2023/09/29 03:03 -0700):
> @gasche approved this pull request.

thanks.

> This looks fine to me. There is a special pleasure for PRs that only
> remove lines of code.

Yeah, I do share this one.

Do you have an opinion on how far we should go, though?

**Comment by shindere** [comment]
Gabriel Scherer (2023/09/29 03:09 -0700):
> > given that ocamldoc's generators are not installed, one
> may wonder whether it's useful to build them and then, if not, whether they
> shouldn't simply be deleted, too
>
> I was not sure what you mean by "generators" (surely the ocamldoc
> backends are necessary to keep around). I looked. You mean the modules
> in `generators/` in the source tree, which apparently are one
> alternative backend/plugin to generate a TODO list, around 500 lines
> of code in total.

Yes, sorry for the lack of clarity here, I took it for granted that
everybody (except me before having to deal with ocamldoc's build system)
would knnow.

> If they are not installed nor used in the manual
> build process (I don't think they are), then yes it would be fine to
> remove them.

Okay, I'll add another commit doing that properly.

**Comment by shindere** [comment]
Just pushed one more commit removing the generators completely.

If that's fine with people I'll edit the PR's title and add a Changes entry.

**Comment by Octachron** [comment]
The `todo` generator in `ocamldoc/generators` has some value as an example of ocamldoc generators, but it should be fine to remove it (with an infinite amount of time at hand, we could resurrect it as a part of the ocamldoc documentation).

**Comment by gasche** [comment]
The CI fails due to a known-flaky test, `finaliser_handover.ml` -- the well-numbered issue #12345.

> If that's fine with people I'll edit the PR's title and add a Changes entry.

Yes, please.

**Comment by shindere** [comment]
PR title updated and Changes entry added

**Pull request merged**
