### PR TITLE
stdlib: Add Bytes.replace and String.replace

### PR DESCRIPTION
**Pull request by bn-d**
I found myself rewriting this function way too often. I believe this could be very handy in stdlib.

### CODE REVIEW

**Comment by gasche** [comment]
In case anyone wonders, like I did:

```ocaml
val replace : char -> char -> bytes -> bytes
(** [replace a b s] replaces all instances of character [a] inside [s] to [b]. 
    @since 5.0 *)

let replace a b =
  map (function
    | x when x = a -> b 
    | x -> x)
```

**Review by nojb — COMMENTED** [review]
A couple of questions for discussion:

- For `Bytes`, wouldn't it make sense to have in-place modification instead?
- For `String`, wouldn't UTF-compliant replace be more useful?

**Comment by bn-d** [comment]
- For `Bytes`, I think in-place replacement makes sense. Then the `String` implementation will be a copy and in-place replacement.
- For `String`, do you mean a `uchar` to `uchar` replacement or something. Honestly, I am more reserved on that. `char` to `char` is simple and straight-forward, and fits well with the reset of the `String` lib when `get`/`map`/`fold_left`/`for_all` etc. all work on `char`. It would useful to have a whole suite of UTF-compliant APIs, but I think that is beyond the scope of the PR.

**Comment by dbuenzli** [comment]
Personally that's not a function I find myself missing. General substring search and replace absolutely, but this no. I rarely need to substitute one byte for another but I often need to substitute sequences of UTF-8 encoded unicode characters for another.

As the implementation suggests this is simply a `map` away, so if people really want that in I'd suggest to rather add the function to `Char` and let people do `{Bytes,String}.map Char.replace` and keep the suggested name for a more useful and general function .

**Comment by xavierleroy** [comment]
I fully agree with @dbuenzli's assessment.

**Comment by bn-d** [comment]
I like the `{Bytes,String}.map Char.replace` idea. For `String.replace`, would you guys agree with something similar to Python `replace`
```python
txt = "one one was a race horse, two two was one too."

x = txt.replace("one", "three")

print(x)
# three three was a race horse, two two was three too.
```

So in OCaml it would be
```
val replace : string -> string -> string
```

**Comment by dra27** [comment]
I fear the choice of algorithm and intermediate data structure for implementing `String.replace` is rather more work than its type signature! From a quick glance at CPython, they have an unsurprisingly optimised (and huge) implementation based around Boyer-Moore. I haven't checked our history, but I've always assumed that we haven't had `String.replace` for arbitrary text because it's a difficult function to define for general use?

**Comment by nojb** [comment]
> we haven't had `String.replace` for arbitrary text because it's a difficult function to define for general use?

IMO it would be great to have a simple implementation of either Boyer-Moore or Knutt-Morris-Pratt in the Stdlib for search/replace. Off the top of my head I remember http://gallium.inria.fr/blog/kmp/...

**Comment by gasche** [comment]
What libraries out there offer a similar functionality? (If the answer is "none", maybe this should be a first step before adding stuff to the standard library.)

**Comment by gasche** [comment]
Answering myself partially: Astring does not have an efficient `find_sub` function, but containers' CCString module does implement KMP ([source code](https://github.com/c-cube/ocaml-containers/blob/34f76e9/src/core/CCString.ml#L69)).

**Comment by nojb** [comment]
There doesn't seem to be much support for this proposal in its current form, so let's close this PR.

**Pull request closed without merging**
