### PR TITLE
keep @@ attributes on exceptions

### PR DESCRIPTION
**Pull request by hhugo**
This is an early preview to gather feedback.

### CODE REVIEW

**Comment by hhugo** [comment]
We should be able to write the following 
```
exception E [@deprecated]
[@@deriving sexp]
```

**Comment by Drup** [comment]
The original version of attribute on structure items was indeed a bit simplistic for exceptions, so I can only approve.

You can add your tests to `parsing/attributes.ml` (and maybe `ppx/warning.ml`). I don't think we have tests that exercise the typedtree iterators.

**Comment by hhugo** [comment]
There is now a warning when `depracated` is misplaced on exceptions.
e.g `exception E [@@deprecated]`
```
File "w03.ml", line 17, characters 15-25:
Warning 53: the "deprecated" attribute cannot appear in this context
```

**Review by Drup — APPROVED** [review]
I had a look at the new commits. The tests are comprehensive and the handling of `deprecated` attributes looks good!

**Comment by hhugo** [comment]
Thanks for the review

**Comment by trefis** [comment]
This overall looks good, but I'm wondering: why not allow attributes on local exceptions (i.e. `Pexp_letexception`)?

**Comment by hhugo** [comment]
Attributes are already allowed in local exceptions.
```
  let exception M [@test]
  in ()
```

This PR is about adding "block" level attribute (`[@@test]`) which does not apply here I think.
Similarly, local modules accept `[@..]` but not `[@@..]`

**Comment by trefis** [comment]
Ah!

**Comment by gasche** [comment]
@trefis this is in the 4.07 Changes, but was not cherry-picked in 4.07. Am I correct that this should be moved to the trunk Changes?

**Comment by trefis** [comment]
I hadn't noticed that :)

I'll let you judge (@hhugo could give his opinion as well) whether it's better move the change entry to the trunk section, or to cherry-pick the changes.
(I personally have no trouble seeing this as a bugfix, but you guys might have a different opinion)

**Comment by gasche** [comment]
I don't want to change the parsetree again this late in the release cycle, so I'll leave it in trunk.

Edit: I just fixed the Changes entry placement.

**Pull request merged**
