### PR TITLE
Use `BUILD_PATH_PREFIX_MAP` when compiling primitives

### PR DESCRIPTION
**Pull request by xclerc**
Both `__LOC__` and `__FILE__` may contain the path to the compiled
file, it hence seems logical to apply the substitution specified through the
`BUILD_PATH_PREFIX_MAP` environment variable when compiling
these primitives.

This PR is a one-liner; I guess the main question is: should we do something
if the path is not absolute?

### CODE REVIEW

**Comment by gasche** [comment]
I see two questions:

- This function assumes that an absolute path is given in argument. (In fact the implementation would work for some combinations of relative paths and `BUILD_PATH_PREFIX_MAP` values, but this is not considered in the specification.) So far, I have only needed to use it in code paths that were naturally guarded by a failed `Filename.is_relative` check or directly on `Sys.getcwd ()`. I think that indeed you should only apply the function when the `__FILE__` value is an absolute path; this can be done by adding a test at the time or application, or maybe adding a wrapper function `Location.rewrite_path_if_absolute` (do we have better naming ideas?).

- Currently, `Location.rewrite_absolute_path` is only used on paths that are produced by the compilers, formed by `Sys.getcwd ()`  either alone or added before a user-provided relative path. The patch you propose is more general, it applies the transformation to a have path may have been provided (as an absolute path) by the user. I think that this is a sensible extension to make (especially if it comes with a concrete use-case where it improves reproducibility; for example, we have already discussed with @dbuenzli the fact that it is reasonable for build systems to always pass absolute paths to the compiler), but we should realize that this is a change in policy. (Is the long-term idea that we should rewrite all absolute paths, but we are doing the transformation lazily as problems are found? Or should we try to review now the absolute paths that are included in user-facing inputs?)

**Comment by xclerc** [comment]
Regarding the first item, I pushed a change guarding the call
to `Location.rewrite_absolute_path`. Indeed, even if it would
work for some relative paths, it is probably worthwhile to apply
the principle of least surprise (with respect to the specification)
and only rewrite absolute paths.

Regarding the second item, I must admit do not follow your line
of reasoning: to me a path is relative or absolute independently
of its origin. Moreover, if a user sets `BUILD_PATH_PREFIX_MAP`
in order to have absolute paths rewritten and then passes absolute
paths to the compiler, she would presumably be extremely surprised
to see these absolute paths not rewritten.

@diml @rgrinberg as Dune developers, what is you take on passing
absolute paths to the compiler? (possibly only if the user activates
a "reproducible" mode)

**Comment by gasche** [comment]
I can clarify my second point: when I proposed the BUILD_PATH_PREFIX_MAP feature, one of the things I said to convince people that it was innocuous is that the patch would only rewrite absolute paths built by the compiler, not absolute paths coming from the user. I am not saying it is a desirable property, personally I think that it is fine to rewrite user-provided (and I don't see a way to provide robust reproducibility without it), but I am just pointing out that the property wouldn't hold anymore after your patch -- maybe someone will look at the discussion at some point (possibly after a merge) and realize that it is a problem for them and say something.

**Comment by rgrinberg** [comment]
> @diml @rgrinberg as Dune developers, what is you take on passing
> absolute paths to the compiler? (possibly only if the user activates
> a "reproducible" mode)

I don't see any issues with supporting this on a technical level.

**Comment by xclerc** [comment]
@gasche thanks for the clarification! I would indeed be curious
to hear some feedback from these developers. I would argue
that to some extend it is easier for the user to anticipate the
effects of the substitution on paths she provides explicitly than
on paths built by the compiler.

@rgrinberg thanks for the feedback! I guess it is also OK on a
usability level; the log file will be slightly bigger, but that does
not seem to be an issue.

**Comment by xclerc** [comment]
I don't think we need an entry in the change log for this PR.
@gasche is it ready to be merged?

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
I approved the PR, but I would still feel a bit better if you included a Change entry. This is a change to the observable behavior of the compiler that users may want to be able to track down. Also, it advertises for the reproducible-compilation work, which is nice.

**Comment by xclerc** [comment]
OK, done.

**Comment by gasche** [comment]
(I'll let you take care of merging.)

**Comment by xclerc** [comment]
Well, I would but I can't.

**Comment by gasche** [comment]
... sigh, sorry. I I'll merge as soon as the CI returns.

**Comment by shindere** [comment]
This PR causes the `output-complete-obj`test to fail on OpenBSD because
ocamlc passes `-fdebug-prefix-map` to the C compiler although this option is
not supported. Would it be possible to provide a fix for this?

**Comment by xclerc** [comment]
Sure, I will have a look. Can you check the value of
`CC_HAS_DEBUG_PREFIX_MAP` in `config/Makefile`?

**Comment by xclerc** [comment]
Also, which compiler is used? (`gcc` or `clang`)

From what I read, `clang` supports the command-line
switch since at least 5.0 (and `clang` became the
default compiler with version 6.2).

(`gcc` supports the option since 4.3.)

**Comment by shindere** [comment]
Xavier Clerc (2018/06/29 02:04 -0700):
> Sure, I will have a look.

Thanks a lot!

> Can you check the value of > `CC_HAS_DEBUG_PREFIX_MAP` in
> `config/Makefile`?

Sure! It's `false` so it's correct AIUI.

If needed I can send you more information privately, just that I'm not
sure which email address to use but let me know (e.g. by sending me a
mail at Inria :) ).

**Comment by shindere** [comment]
Xavier Clerc (2018/06/29 02:17 -0700):
> Also, which compiler is used? (`gcc` or `clang`)
> 
> From what I read, `clang` supports the command-line
> switch since at least 5.0 (and `clang` became the
> default compiler with version 6.2).
> 
> (`gcc` support the option since 4.3.)

And we have gcc (GCC) 4.2.1 20070719 here... :(

**Comment by shindere** [comment]
In `utils/ccomp.ml` at line 96, it seems to me that `debug_prefix_map` is
called without checking that the option is acutally supported and the
function does not seem to check it either. Couldn't that be the
cause of this problem?

**Comment by xclerc** [comment]
Yes, it is; I came to the same conclusion.

**Comment by xclerc** [comment]
I will open a PR solving the issue shortly.

**Comment by shindere** [comment]
Xavier Clerc (2018/06/29 09:40 +0000):
> I will open a PR solving the issue shortly.

Great! Thanks!!

**Pull request merged**
