### PR TITLE
Enable natdynlink on x86_64 GNU/Hurd

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by MisterDA** [comment]
Maybe you should just add these changes to #13587?

**Comment by sthibaul** [comment]
Just like you prefer, please say which is preferred.

**Comment by ghost** [comment]
Don't forget to regen `configure`!

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Approved and merged, thanks.

I took the liberty to push 4f04b7c00c66199fb6e42388db452d58c95ec166 to
add myself as a reviewer in the Changes file.

**Comment by sthibaul** [comment]
Sure, you're welcome, thanks!

**Pull request merged**
