### PR TITLE
Actually run all lib-unix tests

### LINKED ISSUE #7909: ocaml teststuite: Most unix tests are not actually being run
**Original bug ID:** 7909
**Reporter:** gfxmonk
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** configure and build/install
**Monitored by:** @nojb @gasche

## Bug description

In reporting ocaml/ocaml#7908, I found that the following test preamble is common:
```
(* TEST
   * hasunix
   include unix
*)
```
However, this results in a test case which succeeds to check for unix support (or not), and does nothing else.

I believe the correct preamble to run the default tasks (but only if the unix lib is supported) is:
```
(* TEST
* hasunix
include unix
** bytecode
** native
*)
```
## Steps to reproduce

in testsuite, run `make one DIR=tests/lib-unix/common`

Observe many tests just print something like:
```
 ... testing 'getaddrinfo.ml' with 1 (hasunix) => passed
```

with my fixed preamble from above, it prints:
```
 ... testing 'getaddrinfo.ml' with 1 (hasunix) => passed
 ... testing 'getaddrinfo.ml' with 1.1 (bytecode) => passed
 ... testing 'getaddrinfo.ml' with 1.2 (native) => passed
```

This seems like a pretty easy bug to write, so I'd expect there to be more examples aside from `hasunix`.

### PR DESCRIPTION
**Pull request by nojb**
Fixes #7909 @shindere

### CODE REVIEW

**Comment by nojb** [comment]
Now that they are run, the tests from #2220 are failing on Windows. @toots

**Comment by gasche** [comment]
This is a fairly embarrassing issue that we should fix as quickly as possible. In this case, it might be the right choice to merge this PR now and fix the CI later -- we are not merging stuff that breaks the CI, we are revealing that it is already broken.

**Comment by toots** [comment]
I'll try to have a look at it but I cannot guarantee to have time in the short term.

**Comment by gasche** [comment]
@toots: of course; I think that "we" should be able to figure out the issue ourselves -- I have the felicity of not having a Windows machine to test on, so I can usually look the other way around when this happens :-'

**Comment by nojb** [comment]
I pushed a fix for the failing test. OK to merge if CI passes. @damiendoligez OK to cherry-pick?

**Comment by gasche** [comment]
@nojb thanks! 

I would be in favor of cherry-picking on 4.08 -- possibly by creating another PR for it, or ensuring that the tests work on Linux and Windows in some other way. We want a functional testsuite in the release branch.

Out of curiosity: is there some sort of relation between the issue in the testsuite and #7342? (Could it be fixed in a similar way by ensuring that Windows behaves nicely?)

**Comment by nojb** [comment]
> Out of curiosity: is there some sort of relation between the issue in the testsuite and #7342? (Could it be fixed in a similar way by ensuring that Windows behaves nicely?)

Doesn't look like it - here the test was passing but it was the spawned process ("echo") that was failing because it couldn't actually write into *its* standard output (supposedly because we never read from the pipe from the OCaml side).

**Comment by shindere** [comment]
Sorry for the late response and for not having seen the issue on Mantis,
I had some difficulties using it.

Also, thanks a lot for having fixed the issue, @nojb. I agree it was
embarrassing!

I dind't look at every file to understand why each individual test got
broken, but for what I could see, I'd say that:

There are tests which were initially working but got broken later. An
example of that is `dup.ml` which stopped being run after commit
b2a0f3b659a8d7e2f44c337718c1ea9373479d7d because before this commit the
tests were run by default and didn't need to be spelled out, which was
no longer the case after the commit (sorry for having missed that during
the review, @dra27).

Other thests have simply never worked, namely those who were created
after the transition to ocamltest. An example of this is the
`channel_of.ml` test.

**Comment by damiendoligez** [comment]
Yes, this should be cherry-picked to 4.08.

**Comment by nojb** [comment]
> Yes, this should be cherry-picked to 4.08.

Already done in #8521.

**Comment by damiendoligez** [comment]
Oh, I missed the reference, sorry.

**Pull request merged**
