### PR TITLE
More compatibility macros to Caml_state

### PR DESCRIPTION
**Pull request by kit-ty-kate**
https://github.com/ocaml/ocaml/pull/8713 moved a bunch of globals to the new `Caml_state` structure. This change in the C API breaks a number of packages that were using them.

To facilitate this change, compatibility macros have been introduced, however some of them were missing. This PR adds every remaining previously accessible globals that didn't change their type.
The only missing fields from `Caml_state` are:
* `caml_young_base` which was previously a static variable in `minor_gc.c`
* `caml_ref_table`, `caml_ephe_ref_table` and `caml_custom_table` which were previously global structures and not structure pointers

I've been noticing the missing globals when I tried to make Oleg Kiselyov's `delimcc` compile with OCaml 4.10. With at least the first commit from this PR, it compiles with very minimal change.

### CODE REVIEW

**Comment by gadmm** [comment]
Thanks, one thing that puzzles me is that Delimcc's `stack_native.c` has both `#define CAML_INTERNAL` and `-DCAML_NAME_SPACE`, so I do not see how `compatibility.h` gets included there (see #9167). Did you have to add it by hand?

**Comment by kit-ty-kate** [comment]
> Did you have to add it by hand?

oh yes it's the "very minimal change" I was talking about. I was a bit puzzled on the role of `CAML_NAME_SPACE` and cie. and I didn't really bother looking much more into it.

**Comment by gadmm** [comment]
Ok, thanks. So, if I understand correctly, with this patch and #9167, delimcc compiles without a change.

**Comment by xavierleroy** [comment]
Even if the discussion at #9205 is still ongoing, this PR is a clear improvement on the current 4.10 situation, so it is in!

I added a tweak to `.gitattributes` to escape the typography police.

Merged in 4.10 and cherry-picked to trunk (dc458a043).

**Pull request merged**
