### PR TITLE
Factorize the definition of the standard library flags

### PR DESCRIPTION
**Pull request by shindere**
This makes it possible to override them and to use another version of the
standard library when compiling the compiler and tools.

Also, an effort has been made to have the stdlib related flags appear
before any other flags, so that it is possible to override them
without overriding e.g. `-g`.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Looks good to me, thanks! Approved.

Do people know why certain subdirectories pass `-g` and others don't? I think we should do it by default (debugging is useful), and then when we don't enable it explain why explicitly.

**Comment by shindere** [comment]
Gabriel Scherer (2022/03/30 07:30 +0000):
> @gasche approved this pull request.
> Looks good to me, thanks! Approved.

Many thanks for the prompt review, @gasche!

> Do people know why certain subdirectories pass `-g` and others don't?

I don't, and wonder, too.

> I think we should do it by default (debugging is useful), and then
> when we don't enable it explain why explicitly.

I fully agree on this. That's actually one reason why I'd like to
factorize as many flag definitions as possible. In other words I can see
3 benefits: (1) cleaner code, (2)  possibility to override them
consistently and (3) make sure the sames flags are used everywhere, at
least by default. So I hope to submit further PRs in this direction.

And, by the way, I am looking for good names for the variables
containing different categories of floags. Basically, as far as
compiling is concerned, I can see a matrix of 6=2x3 categories:
compiling and linking on one axis and, on the other one, flags common to
both compilers (ocamlopt and ocamlc) and flags specific to one of them.

In an off-line discussion, @damiendoligez suggested to use the `CFLAGS`
and `LDFLAGS` bits to  refer to compilation and link flags,
respectively. It would remain to choose names for the other axis.Any
suggestion?

**Comment by nojb** [comment]
> I think we should do it by default (debugging is useful), and then when we don't enable it explain why explicitly.

I agree. Unrelated, but this discussion led me to https://github.com/ocaml/ocaml/pull/300#issuecomment-160462231 which made me wonder whether we shouldn't strip the debug information from `boot/ocamlc` to keep the size of the bootstrap down.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2022/03/30 07:43 +0000):
> > I think we should do it by default (debugging is useful), and then when we don't enable it explain why explicitly.
>
> I agree.

I just checked. `-g` is actually used everywhere (sometimes hidden in
the middle of the other compilation flags) except in the `lex` and
`ocamldoc` subdirectories.

Shall I take this opportunity and add a commit that adds `-g` to these
directories in the present PR?

> Unrelated, but this discussion led me to
> https://github.com/ocaml/ocaml/pull/300#issuecomment-160462231 which
> made me wonder whether we shouldn't strip the debug information from
> `boot/ocamlc` to keep the size of the bootstrap down.

We certainly could, yes. Perhaps in a different PR?

**Comment by shindere** [comment]
I went ahead and added the -g option for compiling and linking ocamldoc
and ocamllex, for which it was missing.

It makes the bytecode executables bigger but has no significant consequence
on the native ones.

The previous commit has also been updated because there was a remaining
occurrence of `-nostdlib` in `ocamldoc/Makefile`.

**Comment by gasche** [comment]
Thanks! I re-reviewed, and merged.

**Comment by shindere** [comment]
Gabriel Scherer (2022/03/31 00:57 -0700):
> Thanks! I re-reviewed, and merged.

Thanks!

There is a little problem, though.

I just pushed an update (the previous version was not complete).

How shall we proceed? Is it best to revert what has just been merged and
merge again? Or shall I open a new PR? Or just push a commit with the
unmerged changes?

I apologize. I noticed a few places where the factorization could have
been improved, and I also introduced the same kind of factorization for
the stdlib under boot.

**Comment by gasche** [comment]
Reverting a merged PR is painful. You should open a new PR or push directly (if you are confident that the additional changes are safe).

**Comment by shindere** [comment]
Gabriel Scherer (2022/03/31 01:30 -0700):
> Reverting a merged PR is painful. You should open a new PR or push
> directly (if you are confident that the additional changes are safe).

OK I had a look to the diff and it seemed reasonable enough for a direct
push dso I went for that. See commit
0a9b6b885903e2dec1f248067c9ea7bddffe1c8e.

**Comment by gasche** [comment]
Looks fine indeed.

**Comment by dra27** [comment]
> > I think we should do it by default (debugging is useful), and then when we don't enable it explain why explicitly.
> 
> I agree. Unrelated, but this discussion led me to [#300 (comment)](https://github.com/ocaml/ocaml/pull/300#issuecomment-160462231) which made me wonder whether we shouldn't strip the debug information from `boot/ocamlc` to keep the size of the bootstrap down.

We have done since #340 in 4.03.

**Comment by nojb** [comment]
> > > I think we should do it by default (debugging is useful), and then when we don't enable it explain why explicitly.
> > 
> > 
> > I agree. Unrelated, but this discussion led me to [#300 (comment)](https://github.com/ocaml/ocaml/pull/300#issuecomment-160462231) which made me wonder whether we shouldn't strip the debug information from `boot/ocamlc` to keep the size of the bootstrap down.
> 
> We have done since #340 in 4.03.

Right, thanks, should have checked before saying anything :)

**Pull request merged**
