### PR TITLE
lexer.mll: remove '<' from kwdopchar (first symbol in binding operators)

### PR DESCRIPTION
**Pull request by gasche**
There are three character classes in user-choosable operator symbols
in OCaml:
- 'symbolchar', which allows everything one can use in infix operators
- 'dotsymbolchar', which removes
  + '.', which creates ambiguities with ..> as valid object type syntax
  + '<', incompatible with Camlp4
  + '~', incompatible with MetaOCaml
- 'kwdopchar', which was introduced by Leo in #1947 (binding operators), which
  is similar to 'dotsymbolchar' but also
  + removes '!' and '?', only allowed in prefix operators
  + removes '%', incompatible with ppx syntax
  + removes ':' (why not?)
  + adds '<' back in (why ?)

It's fairly hard to justify these choices and have a coherent story
for the character classes. It would already be easier if at least we
had a monotonic hierarchy of more and more permissive classes.

The present PR removes '<' from the 'kwdopchar' set, so that it
corresponds to a core "safe characters" class that is included in all
others.

(This means that user programs that would use a let-operator such as
`let<@>` or `and<@>`, accepted in 4.08 and 4.09, would now be rejected
in future OCaml releases incorporating this change.)

### CODE REVIEW

**Comment by gasche** [comment]
cc @Octachron and of course @lpw25

**Comment by lpw25** [comment]
There is an important class missing from the lexer: the characters allowed to start an infix operator. The manual lists them as:

> = ∣  <  ∣  > ∣  @ ∣  ^ ∣  | ∣  & ∣  + ∣  - ∣  * ∣  / ∣  $ ∣  %

and `kwdopchar` is precisely these characters without `%` (because of ppx).

I think that definition is more consistent than the proposed one.

**Comment by gasche** [comment]
@lpw25 this sort of makes sense, but I'm still puzzled by some aspects (which I don't find discussed anywhere?). For example, why did you use `kwdopchar dotsymbolchar*` as the regexp instead of `kwdopchar symbolchar*` as could be expected, or a variant of this that removes `%` from the inner characters but does allow `.` as for infix or prefix operators?

This sorts of make sense, but still: why would we allow in the *middle* of a keyword a character because it's allowed at the *start* of infix operators?

If we converge on a reasonable logic/classification of these character classes, I can edit the PR to use them in the lexer. @Octachron is interested in documenting them (with justifications, if possible) in the user manual as well -- this is how the present PR started.

**Comment by lpw25** [comment]
>  why did you use kwdopchar dotsymbolchar* as the regexp instead of kwdopchar symbolchar* as could be expected

That one I do not remember. Your suggestion seems more natural, which makes me think I must have had a reason not to do it -- but maybe I just wasn't thinking about it much.

**Comment by lpw25** [comment]
> This sorts of make sense, but still: why would we allow in the middle of a keyword a character because it's allowed at the start of infix operators?

The characters that are allowed in operators but not at the start of operators are `.` and `:`.  IIRC they don't actually conflict with things when allowed in let operators. However, due to their pervasive use in the language with specific meanings they look confusing and it seemed best to not allow them.

The characters for prefix rather than infix operators are `!`, `?` and `~`. `!` after a keywords has an existing meaning in OCaml so that needed to be excluded. `?` and `~` are used in `let` expressions that define labelled parameters -- whilst not technically a conflict they seemed potentially confusing so it seemed best to exclude them as well.

The rest of the characters in operators seemed fine except `%` which conflicts with ppx.

**Comment by gasche** [comment]
I believe that this PR worked well as a discussion vehicle but, now that #9098 is out and paints a relatively reasonable picture without changing the current lexical rules, has outlived its usefulness.

**Comment by gasche** [comment]
(Thanks @lpw25 for the extra discussion.)

**Comment by gasche** [comment]
I still think that it is inconsistent to use `dot-operator-char` as the "inner" character class for keyword operators. We should use a class that corresponds to the full `operator-char`, without the dangerous `%` (and possibly other things), instead of picking the one existing class that does not contain `%`. `dot-operator-char` should be reserved to be the class of the first user-chosen character following a dot (in indexing operators).

**Pull request closed without merging**
