### PR TITLE
Various build-system fixes and enhancements

### PR DESCRIPTION
**Pull request by shindere**
The original purpose of this PR was to provide a configurable build variable
to provde C-compiler flags to be used specifically when compiling C object files for
linking with native code.

This is going to be useful for TSan, the threadsanitizer, but has been
designed to be general and suableby other features.

Finally this PR consists in a series of commits that enhance and fix the
build system in various ways.

It's best reviewed commit by  commit and the individual commit messages
hopefully explain each change.

Also, each commit is conciseandshould be rather self-explanatory and easy to
review.

### CODE REVIEW

**Review by MisterDA — APPROVED** [review]
We've reviewed the PR offline, and all the changes make sense to me. Thanks Sébastien!

**Comment by shindere** [comment]
Antonin Décimo (2023/03/17 08:44 -0700):
> @MisterDA approved this pull request.
>
> We've reviewed the PR offline, and all the changes make sense to me.
> Thanks Sébastien!

Thanks to you, Antonin. To complete what Antonin explained, let me said
that we really went through the PR on a commit by commit basis. Antonin
asked relevant questions for each commit andhe really tried hard to
understand themore  general context and, I think, he definitely succeded
to do so. He nnoticed alittle mistakein one commit: some compiler flags
were passed twice. It ddin'thurt but was useless andhas been fixed as
part of our in-person review process.

I am grateful to Antonin for his patience andhis determination. I do
think the review he did is a totally genuine one, not shallow at all.

**Review by nojb — APPROVED** [review]
LGTM (took a quick look at the PR; also approving based on @MisterDA's review)

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2023/03/18 00:31 -0700):
> @nojb approved this pull request.
> 
> LGTM (took a quick look at the PR; also approving based on @MisterDA's
> review)

Thanks. I went ahead and merged.

**Pull request merged**
