### PR TITLE
Fix memory leaks in intern.c when OOM is raised (alternative solution)

### PR DESCRIPTION
**Pull request by mlasson**
In the function `intern_alloc` there are three possible places where an exception
could occur when the program runs out of memory, when it calls:

```
1. `caml_alloc_for_heap`,
2. `caml_alloc_shr`,
3. `caml_stat_alloc`.
```

This is a source of memory leaks, since the caller to `intern_alloc` (eg.
`caml_input_val`) may statically allocate memory (eg. intern_input) that
will never be freed.

In PR #283, I proposed a fix which tries to free the memory just before
raising the exception. In this commit, I propose another solution guided
by advices of @gasche and @alainfrisch.

In this solution, the function "intern_cleanup ()" is now idempotent and
is called in and out of entry points and is not called anymore before
raising exception.

So this version works, but each time any exception is raised from
intern.c, the memory won't be cleaned until a function from intern.c is
called. This is not ideal. The next commit will wrap the calls in stdlib
to intern.c functions around an exception handler that calls intern_cleanup
before re-raising the exception. These two commits are separated in order to
ease bootstrapping.

As @alainfrisch pointed out, one advantage of this solution would be to
allow custom deserializers to raise exception directly (it makes
`caml_deserialize_error` useless)

### CODE REVIEW

**Comment by damiendoligez** [comment]
I don't much like the idea that the call to `intern_cleanup` is done from C when all is well and from OCaml when an exception is raised. What would you think of removing the call at the end of the C functions and doing this?

```
let unmarshal s =
  match unmarshal_unsafe s with
  | x -> intern_cleanup (); x
  | exception e -> intern_cleanup (); raise e
```

**Comment by mlasson** [comment]
I could do that, but I was actually about to put back the cleanups before the failwiths in intern_rec. 
It is because bad things could happen if the gc wakes up between the exception is raised and the call to intern_cleanup() in the caml wrapper. 

This is the part of intern_cleanup that should happen before garbage collection:

``` C
`if (intern_block != 0) {
     /* restore original header for heap block, otherwise GC is confused */
     Hd_val(intern_block) = intern_header;
}
```

This is ok for out_of_memory because it does not allocate to raise... but caml_failwith could trigger the gc :'(. May be this not such a great solution after all.

**Comment by mlasson** [comment]
The previous commit should fix the issue mentioned in previous comment.

**Comment by mlasson** [comment]
> What would you think of removing the call at the end of the C functions and doing this ?

Some intern.c function may be called from C and caml (caml_input_value_from_string), so if we do this we would need to add a third function.

I'm not one hundred percent sure, but all calls of demarshalling functions from C that raise an exception are fatal to the runtime (they jump to the default exception handler).

**Comment by xavierleroy** [comment]
I may have missed something in the discussions, but this solution looks technically inferior to that in PR#283, since memory is released later, or possibly never.  Why should we spend time considering this PR instead of concentrating on PR#283?

**Comment by gasche** [comment]
There are two changes in this PR, (1) the fact of making the cleanup function indempotent (which I think is a very nice idea), and (2) my suggestion to try to clean only on re-entry (which seems unpopular). The purpose of suggestion (2) was to increase the readability/maintainability of the use-sites of cleanup, but I wonder whether the indempotent version (1) could not be used for the same benefits within #283 .

**Comment by xavierleroy** [comment]
I still don't get what idempotence has to do with fixing a memory leak, but one of you will explain me the next time we see each others.  In the meantime, I'd like to concentrate on a basic fix to the basic issues raised in PR#283.  Can we please do that?

**Comment by alainfrisch** [comment]
The current state of #283 is not very satisfactory in the sense that each call site to the cleanup function is responsible for setting some values to NULL so that no spurious de-allocation occur.  It seems just cleaner to ensure that the cleanup function can be called from any context outside the main intern loop; hence the idempotence stuff, I think.

We also thought that capturing the exception on the caml side could allow customer demarshaler to raise arbitrary exception without going through the special function.  But this is not the case:  before the cleanup function is called, the OCaml heap is not in a stable state because of the modified header word on the big allocated block.  Marc and I discussed about allocating one extra word for this block so that we wouldn't have to modify its header during the intern loop, thus allowing to allocate during within custom demarshaler (to raise exception or for other purposes).  But this is not directly to the OOM problem, and perhaps not justified.

**Comment by mlasson** [comment]
> Marc and I discussed about allocating one extra word for this block so that we wouldn't have to modify its header during the intern loop

Note that this is implemented in commit 70bef6a above.

**Comment by mlasson** [comment]
Thanks for your replies !

> I may have missed something in the discussions, but this solution looks technically inferior to that in PR#283, since memory is released later, or possibly never. Why should we spend time considering this PR instead of concentrating on PR#283?

The memory leaks occur when exception are raised. There are two possible solutions for this problem. One is PR#283 which choose to deal with this problem by making sure no exception is raised before calling the clean up. The other (in this PR) attempts to make the whole thing resilient to exceptions raised anywhere by catching the exception in the "ocaml world" (ideally, I would have like the possibility to add an exception handler from C but that does not seem easy).  To me both solutions make sense and I am still not convince that one is strictly better than the other.

To sum-up:

| PROS of PR#283 | PROS of PR#287 |
| --- | --- |
| It is easy and deals with errors in the C fashion. | We do not have to make sure we did not forget any exception. |
| The code should behave exactly as before the fix when no exception is raised. | We do not have to duplicate existing function. |
| We never call cleanup when it is not necessary. | It is always safe to call cleanup. |
| We do not touch anything to the caml world. | The memory is never in a confusing state for the GC. |
| No need to notify third-party users (are there any ?) of exported functions of intern.c |  |

Tomorrow, in PR#283, I will replace calls to caml_stat_alloc_no_raise by plain mallocs and duplicate the code of caml_alloc_shr to implement the no_raise version to avoid the overhead (should I use macros to share the code ?). And I will be happy whatever the implementation adopted.

**Comment by mlasson** [comment]
There are less rows for PR#287 in the table above :-), let's close it.

**Pull request closed without merging**
