### PR TITLE
Fix detection of immediate64 types through unboxed types

### PR DESCRIPTION
**Pull request by lpw25**
`Typedecl.get_unboxed_type_representation` does not behave correctly if the unboxed representation is `[@@immediate64]`. This can be seen by examining the lambda code for:
```ocaml
module M : sig type t [@@immediate64] end = struct type t = int end;;

let foo (x : M.t) (a : M.t array) = a.(0) <- x;;

module Unboxed (T : sig type t end) = struct
  type t = T of T.t [@@unboxed]
end

module N = Unboxed(M)

let foo (x : N.t) (a : N.t array) = a.(0) <- x;;
```
which is:
```
(let (M/83 = (makeblock 0))
  (seq (setfield_ptr(root-init) 0 (global Foo!) M/83)
    (let (foo/84 = (function x/86 a/87 (array.set[int] a/87 0 x/86)))
      (setfield_ptr(root-init) 4 (global Foo!) foo/84))
    (let (Unboxed/147 = (function T/169 is_a_functor (makeblock 0)))
      (seq (setfield_ptr(root-init) 1 (global Foo!) Unboxed/147)
        (let
          (N/149 = (apply (field 1 (global Foo!)) (field 0 (global Foo!))))
          (seq (setfield_ptr(root-init) 2 (global Foo!) N/149)
            (let
              (foo/150 =
                 (function x/151 a/152 (array.set[addr] a/152 0 x/151)))
              (setfield_ptr(root-init) 3 (global Foo!) foo/150))
            0))))))
```
Note the `array.set[addr]` which should be `array.set[int]` on 64bit.

This is caused by some code in `typedecl_unboxed.ml` that tries to treat immediate types specially. However, the code is both incorrect and unnecessary, so this PR deletes it.

### CODE REVIEW

**Comment by stedolan** [comment]
This looks good to me!

The approach here causes a mild regression in an edge case. I think the edge case probably isn't worth worrying about, and fixing it would complicate the code unnecessarily (I tried a while ago...). If there is an immediate unboxed definition like:

    type t = Foo of M.t [@@unboxed] [@@immediate]

where the cmi file for `M` is missing, then this code will expand `t` to `M.t` and then give up, failing to notice that `t` is immediate. The old code would instead pretend that `t` is `int` as soon as it sees the immediate attribute and will therefore notice that `t` is immediate.

**Comment by gasche** [comment]
@stedolan's edge-case is giving me pause, because I don't think it is as unimportant as he writes; I think Dune is trying hard to remove transitive-dependencies .cmi these days, so the Not_found stuff here may occur more and more often. But on the other hand, I don't read the code the same way and I have the impression that there should be no regression on this example, @stedolan can you clarify? In `Typedecl_immediacy.compute_decl`, your example would previously be handled as a `This {{M.t}}` turning into `Ctype.immediacy env {{M.t}}` giving `{{M.t}}.type_immediate`, and now we should have `Some {{M.t}}` turning into `Ctype.immediacy env {{M.t}}` giving the same result. What am I missing?

I have the impression that the bug that @lpw25 is referring may have been caused, or at least helped, by the fragile pattern-matching in the Typedecl.get_unboxed_type_representation definition. We should think about turning this warning on by default -- now that local attribute tweaks make it easy to turn it off locally.
I wonder if it would be possible to fix the bug (in a worse way than the one proposed, but more local / less invasive) by checking for a new `| Only_on_64bits ty when Ctype.on_64bits ()` case in this function.

Overall the change is a nice simplification (less code is better), so this should be good to go if Stephen's counter-example happens to not be a counter-example.

**Comment by stedolan** [comment]
You're right, the issue I was thinking of is less severe than I thought, and doesn't occur in the case I mentioned. I think it will occur in this case:

    type 'a id = 'a
    type t = Foo of M.t id [@@unboxed] [@@immediate]

where `M.t` is some immediate type whose cmi later becomes unavailable.

Here, `t` (with `type_immediate = Always`) is expanded to `M.t id` (with `type_immediate = Unknown`) which would be expanded to `M.t` (with `type_immediate = Always`) if the cmi were available, but in its absence returns the not-obviously-immediate `M.t id`.

The old code stopped expanding on the first immediate type, while the new code keeps expanding until it runs out of fuel. The old code was wrong, because information may improve after multiple expansions (one may quickly learn that a type is `[@@immediate64]`, and only learn that it in fact has the stronger `[@@immediate]` property after further expansion). The new code is correct in principle, but sadly it is possible to lose information by expanding types because of missing cmis. (As I mentioned before, I think we should merge regardless, as behaviour with missing cmis is already weird and this patch fixes a bug)

**Comment by gasche** [comment]
I wondered if there are not other regressions among the consumers of `Typeopt.scrape_ty`. Most consumes also call `Ctype.immediacy` and do the right thing, but notably `value_kind` does not, which leads to the following example

```ocaml
type imm = A | B | C
type t = Foo of imm [@@unboxed]

let () =
  let test1 (x : t) = (x, x) in
  let test2 ((x : t), (y : t)) = x in
  ignore (test1, test2)
```

with 4.12:

```
       (let
         (test1/87 = (function x/89[int] (makeblock 0 (int,int) x/89 x/89))
          test2/90 = (function (param/97[int], param/98[int]) : int param/97))
```

with the PR:

```
       (let
         (test1/87 = (function x/89 (makeblock 0 x/89 x/89))
          test2/90 = (function (param/97, param/98) param/97))
```

which suggests that "being-an-int" type information has been lost.

**Comment by lpw25** [comment]
Well spotted. I've now included a fix to `value_kind` too.

**Review by gasche — APPROVED** [review]
This is an approval stamp. Some additional comments follow.

Unlike what @stedolan suggests, I'm not sure that the new implementation is "morally the right way" to implement this code. I think that the need to check immediacy separately in many places is the sign of an API smell with both the pre-PR and the in-PR code structures, and that better long-term solutions need to be found. In the long term:
1. We could consider having a stronger / more informative `classify` function that takes care of the tricky logic once, and that all other consumers call (this is something we have considered independently with @nchataing, and our head-shape-computation function may be such a stronger version)
2. We could consider getting rid of `get_unboxed_type_representation` and letting consumers of type expressions/definition unroll definitions progressively. This would make it possible/easy to implement @stedolan's idea of keeping track of immediacy information at intermediate steps during expansion, which I think is morally the right approach to compute immediacy if we accept missing cmis as a fact of life. (This is related to #10479: we want to be sure that we agree with a good approach to unroll unboxed definitions.)

In the short term, I believe that overall the PR change is beneficial, especially in that it reduces code size and removes complexity in the compiler codebase. When discussing the subtle point of regressions, we should keep in mind that immediate64 is a somewhat arcane feature, and that Jane Street, @lpw25's organization, is to my knowledge the main (possibly only) user for now. If the regression comes back to bite someone, it would probably be them, and I think trusting Leo to evolve this arcane feature (and maintaining the skills and code comprehension to do it) is the right choice.

**Comment by lpw25** [comment]
I've updated a number of expect test results that were changed by the last update. It seems that the lack of using `Ctype.immediacy` in `value_kind` was already a bug causing a lot of missed cases of `Pintval`.

**Comment by dra27** [comment]
It looks like not all the reference files were updated - see the [other-configs](https://ci.inria.fr/ocaml/job/other-configs/565/consoleFull) Jenkins job.

**Pull request merged**
