### PR TITLE
Remove some unused primitives

### PR DESCRIPTION
**Pull request by yallop**
More cleanup in the vein of #9744.  Remove:
* `caml_input_value_from_string` (unused since e227fb007d)  
* `caml_ml_flush_partial`, `caml_ml_output_partial` (unused since 705054b3)  
* `caml_obj_is_block` (unused since b1f93a66)

### CODE REVIEW

**Comment by nojb** [comment]
A bootstrap is needed?

**Comment by yallop** [comment]
Yes: 1c9e1e0

**Review by nojb — APPROVED** [review]
LGTM (once CI passes)

**Comment by xavierleroy** [comment]
While we are removing primitives, could someone please review #9763? It removes even more dusty C code!

**Pull request merged**
