### PR TITLE
Rename EffectHandlers module to Effect

### PR DESCRIPTION
**Pull request by avsm**
This makes the name more consistent with the rest of the stdlib, and neatly avoids a choice of snake or camelcase.  Discussed on caml-devel in December and one of the post-multicore-merge tasks in #10861.

Will require some changes in domainslib/eio to follow once merged, and in opam-repository in the base-effects package.

### CODE REVIEW

**Comment by nojb** [comment]
Is a bootstrap necessary?

**Comment by avsm** [comment]
It failed without it, but that might have been due to some lingering dependency. Let me drop the bootstrap with a clean tree and try again.

**Comment by avsm** [comment]
And it works fine without bootstrap with a `git clean -dxf`, as the compiler doesn't use effect handlers (yet!).  I've dropped that from the PR.

**Review by damiendoligez — APPROVED** [review]
LGTM

**Pull request merged**
