### PR TITLE
Remove `Domain.set_name` primitive

### PR DESCRIPTION
**Pull request by sabine**
As has become clear in #11174, the way forward for 5.00 is to remove `Domain.set_name`.

Removal of `Domain.set_name` requires bootstrapping, so here is a minimal PR to remove the primitive.

Also, the runtime no longer assigns POSIX thread names like "Domain", "Backup", and "Tick".

### CODE REVIEW

**Comment by dra27** [comment]
This just needs a bootstrap - either squashed with the first commit, or added immediately after it, and it should build. The second commit (removing the C primitive itself) doesn't require a bootstrap.

**Comment by kayceesrk** [comment]
It would be nice to keep the bootstrap step as a separate commit. Squashing the changes that require bootstrap with the bootstrapped changes has caused pains in the past for merging Multicore  branch, which had its own bootstrap commits.

**Comment by sabine** [comment]
Interestingly, doing these steps:
1. `make clean` `./configure` `make world`
2. remove primitive from .ml/.mli files
3. `make coreall` `make bootstrap`
4. remove primitive implementation from .c file
5. `make` fails with `unknown C primitive 'caml_ml_domain_set_name'`. However, when I perform another bootstrap instead of step 5:
6. `make coreall` `make bootstrap`, the build succeeds.

I shouldn't need to do two bootstraps here, right? Or should I?

@kayceesrk having the bootstrap as a separate commit sounds sane to me.

**Comment by kayceesrk** [comment]
I still see `caml_domain_set_name` in the source. IINM in the developer meeting we had decided not to set the names of threads by default. This will ensure that `top` command will display the name of the program rather than `Domain0`. CC @gasche @Octachron.

**Comment by damiendoligez** [comment]
> Interestingly, doing these steps:
> 
> 1. `make clean` `./configure` `make world`
> 2. remove primitive from .ml/.mli files
> 3. `make coreall` `make bootstrap`
> 4. remove primitive implementation from .c file
> 5. `make` fails with `unknown C primitive 'caml_ml_domain_set_name'`. However, when I perform another bootstrap instead of step 5:
> 6. `make coreall` `make bootstrap`, the build succeeds.

The instructions in `BOOTSTRAP.adoc` are not very clear but what you need to do is:
1. `make clean` `./configure` `make world`
2. remove primitive from .ml/.mli files
3. `make coreall`
4. remove primitive implementation from .c file
5. `make bootstrap`

(see steps 4 and 5 in the section "Adding, removing and renaming primitives")

**Comment by dra27** [comment]
@sabine - yes, I'd expect that. `make` is not quite the same as `make coreall` - the default target in the `Makefile` repeats `make coldstart`, which messes the tree up.

**Comment by sabine** [comment]
Ah ok, I see, so there is indeed only one bootstrap necessary, but it is **after** removing the C implementation of the primitive. `make coreall` after removing the OCaml bindings of the primitive is sufficient.

I think it's probably working as expected now: regular old `make` succeeds after the single completed bootstrap. (I also learned a lot about rebasing and `git cherry-pick` because there was another PR with a bootstrap merged in the meantime.)

**Review by kayceesrk — APPROVED** [review]
The PR works as expected. To be clear, I would update the original PR description to indicate that this PR removes the default naming of threads as "Domain<N>", "Backup<N>" and "TickThread" along with removing "Domain.set_name".

**Comment by sabine** [comment]
Can someone add the `no-change-entry-needed` label and rerun the checks? This is not visible to the user because 4.14 didn't have domains in the first place.

I think this is ready to merge.

**Comment by kayceesrk** [comment]
Thanks @sabine.

**Pull request merged**
