### PR TITLE
PR7083: fix assertion failure introduced by #305

### PR DESCRIPTION
**Pull request by trefis**

### CODE REVIEW

**Comment by alainfrisch** [comment]
Thanks for the quick fix!

**Comment by gasche** [comment]
I disagree with the merge. `filter_all` is called in other parts of the code and it is not clear at all to me that the change is correct there. As I said in #305, I would like to revert it and delay it to after the 4.03 release, when we have more time to review the implementation.

**Comment by trefis** [comment]
> `filter_all` is called in other parts of the code and it is not clear at all to me that the change is correct there.

It is actually, I checked all the places where `normalize_pat`, `discr_pat` and `filter_all` are called, and where their callers are called from.
I am reasonably confident that this change is safe and sufficient. I of course would be glad if you or Luc reviewed it more carefully.

**Comment by trefis** [comment]
N.B. Although I am reasonably confident the fix is correct, I make no such claim about whether it is the cleaner/most obvious way to do things (but then, there is a lot of that in parmatch)

**Pull request merged**
