### PR TITLE
Add ?size and ?random to Hashtbl.of_seq and related functions

### PR DESCRIPTION
**Pull request by dra27**
Split off from #2202 - note that the implementation of `Hashtbl.MakeSeeded.of_seq` is therefore wrong, but this would be corrected after #2202 is merged (if this GPR is accepted).

### CODE REVIEW

**Comment by dra27** [comment]
Ping @alainfrisch on this old one

**Comment by gasche** [comment]
See also #2236 which proposes to add an `of_list` with exactly the same question.

(Personally as I mentioned I think that the `{add,replace}_{seq,list}` are better building blocks and that we should de-emphasize `of_*` functions that force us to duplicate the API of the `create` all over the place. Unfortunately this tells nothing about what we should do with the *existing* `of_*` functions: leave them frozen in the errors of their ways, or bloat the API just for them?)

**Comment by dra27** [comment]
I agree, @gasche. The problem with the approach I put here is that this breaks:

```ocaml
seq |> Hashtbl.of_seq
```

I think it's better to document that `of_seq` always uses a "default" interpretation of `random` Hashtbl of size 16 and note to use `add_seq` if more control is needed:

```ocaml
(* with this PR:
seq |> Hashtbl.of_seq ~size:32 ~random:true
*)
seq |> Hashtbl.add_seq (Hashtbl.create ~random:true 32)
```

I have one question before closing this. Given that #2236 is never going to land, should we:
1. Just update the documentation for `Hashtbl.of_seq` as above
2. Deprecate it in favour of always writing the version with `add_seq`?

**Comment by gasche** [comment]
There is a consensus *against* the change proposed in this PR, so closing.

> I think it's better to document that of_seq always uses a "default" interpretation of random Hashtbl of size 16 and note to use add_seq if more control is needed

I agree. (I would document this, but not deprecate the function). Anyone, please feel free to open a PR with this documentation improvement.

**Pull request closed without merging**
