### PR TITLE
Do not poll for async callbacks in caml_leave_blocking_section

### PR DESCRIPTION
**Pull request by jhjourdan**
In #9722 and #8997, we discussed the possibility of removing the call to `caml_process_pending_actions` from `caml_leave_blocking_section`.

This PR does that, and mitigate one of the potential regressions that this changes would imply (explained in length in https://github.com/ocaml/ocaml/pull/9722#issuecomment-660252486 and https://github.com/ocaml/ocaml/pull/9722#issuecomment-662522314) by adding a call to `caml_process_pending_actions` at the beginning of `caml_raise`.

Arguably, we could also add polling at the end of some/all C library functions. There are several ways to do that:
- Manually, by adding a call to `caml_process_pending_actions` in all C functions having a blocking section. However, we cannot do that for external C libraries, and this is a rather large change in the runtime+Unix+Thread codebase.
- Automatically, by polling in `caml_c_call`. I'm afraid it's not an option, since it would have a performance cost, which would be paid by every C call (including those unrelated to blocking sections).
- Automatically, by modifying the code generated by ocamlopt when performing a C call (recall that polling is only a matter of comparing the young heap pointer). This would be less expensive, but I think probably still too expensive.

So, for now, I propose not to add polling at the end of C functions. @gadmm, can you think of  concrete example where this would be necessary?

This PR also adds a test for the pattern @stedolan describes in https://github.com/ocaml/ocaml/pull/9722#issuecomment-662522314.

### CODE REVIEW

**Comment by gadmm** [comment]
The discussion about this is (still) going on at #9722.

About polling when exiting non-`noalloc` C calls, we indeed mentioned it a while ago, and to me this makes sense as part of the work on BSP which will already have to manage some transition regarding the non-allocating dialect mentioned by @gasche. Those critical sections are still important in low-level code even with masking available, so the plan to have an option to disable the emission of new polling locations with no-poll blocks will be useful. So I think this should be out of the scope of the current work.

**Comment by gadmm** [comment]
> @gadmm, can you think of concrete example where this would be necessary?

I think the motivations are only those of the BSP patch.

**Comment by xavierleroy** [comment]
> The discussion about this is (still) going on at #9722.

I would say "running in circles" rather than "going on" :-)

**Comment by xavierleroy** [comment]
Globally I think it's a good idea to check for pending signals before raising exceptions, as one of the main use cases of signal handlers is to raise exceptions, and the logical order in which exceptions are raised is important. 

(Something similar happens in the bytecode interpreter, POPTRAP instruction, where signals are polled before popping the exception handler, just in case the signal handler raises and the current handler would handle it.  Interestingly, the native-code compiler doesn't poll at this point...)

After that, I see no compelling reason why leave_blocking_section should process pending signals.  So, if @stedolan and @jhjourdan think it's simpler not to, let's follow them and stop arguing endlessly about this point.

**Comment by stedolan** [comment]
The implementation here has a bug: by setting `signals_are_pending` to `1` in `caml_leave_blocking_section` but not setting `caml_something_to_do`, there is no guarantee that signals are eventually handled. (This shows up when context-switching between threads with different signal masks).

There's now a correct implementation and a test in #9722

**Comment by stedolan** [comment]
> Automatically, by polling in caml_c_call. I'm afraid it's not an option, since it would have a performance cost, which would be paid by every C call (including those unrelated to blocking sections).

While offering no opinion about whether this is a good idea, I remark that it's possible to do this with no performance cost: we know where the return address is in caml_c_call, and if a signal arrives we can overwrite it with the address of a stub that does the poll.

**Comment by jhjourdan** [comment]
Right, clever idea.

That said, even though I think this is a good idea, it seems that this would require writting assembly code for each of the platforms, which seems overkill for what we are trying to achieve here.

**Comment by jhjourdan** [comment]
Closing in favor of the correct implementation in #9722.

**Pull request closed without merging**
