### PR TITLE
runtime: add newline at end of error message

### PR DESCRIPTION
**Pull request by shindere**
A cosmetic PR which could probably have been pushed directly, but just to
make sure

### CODE REVIEW

**Comment by dra27** [comment]
The change is fine of course, but there are 4 other instances in this file with the same problem, all of which then exit with code 127... would it be worth duplicating the idea behind say `caml_gc_message` and have a `printf`-like function which prints a message to stderr, followed by `\n` and then exits with code 127?

**Comment by dra27** [comment]
(Sorry, I missed the word “fine” in “the change is fine, of course”)

**Comment by shindere** [comment]
David Allsopp (2019/10/18 11:44 -0700):
> (Sorry, I missed the word “fine” in “the change is fine, of course”)

Thanks a lot for having commented rather than just edited! Warmly appreciated!

**Comment by shindere** [comment]
David Allsopp (2019/10/18 11:43 -0700):
> The change is of course, but there are 4 other instances in this file
> with the same problem, all of which then exit with code 127... would
> it be worth duplicating the idea behind say `caml_gc_message` and have
> a `printf`-like function which prints a message to stderr, followed by
> `\n` and then exits with code 127?

That's a good idea, thanks!

PR updated accordingly.

**Comment by gasche** [comment]
The new PR code looks reasonable, but I haven't tested it directly. Have you tested it yourself, or do you know that the testsuite exercises it?

**Comment by shindere** [comment]
I did some manual testing, yes.

Generally speaking it would certainly be nice to be able to test the
runtime itself in the testsuite but that's not yet possible and it looks
it would be a bit more ambitious than the original PR.

**Comment by gasche** [comment]
It's just that I don't trust variable-argument functions very much, so it's good to ensure that they have been tested at least once.

(It doesn't sound too hard to write a "script" kind of test that produces some of the `ocamlrun` error conditions (for example: unknown command-line argument, file-not-found), and checks the error message and the return code before returning pass/fail information to ocamltest. But I agree it's not necessary as part of this PR.)

**Review by gasche — APPROVED** [review]

**Comment by shindere** [comment]
Gabriel Scherer (2019/10/19 02:58 -0700):
> gasche approved this pull request.

Thanks

**Comment by shindere** [comment]
Perhaps if you find it important you may want to create an issue for a
junio job?

**Pull request merged**
