### PR TITLE
iOS support for ocaml-4.02

### PR DESCRIPTION
**Pull request by gerdstolpmann**
Supports cross-compiling to iOS, both 32 bit and 64 bit mode.

Build instructions are included in the file README.ios.

Authorship: the iOS Porting Team (Gerd Stolpmann, Jeffrey Scofield, Mark Hayden).

### CODE REVIEW

**Comment by damiendoligez** [comment]
Can you rebase this onto 4.02.2? I will make a PR for OPAM to add it to the list of switches, under the name `4.02.2+ios`, unless you can think of a better name.

**Comment by gerdstolpmann** [comment]
Sure, will do this later today.

**Comment by gerdstolpmann** [comment]
I managed to do it today. There is a new branch "gs-4.02.2+ios" (https://github.com/gerdstolpmann/ocaml/tree/gs-4.02.2) and a tag "4.02.2+ios" (https://github.com/gerdstolpmann/ocaml/tree/4.02.2+ios). The tag is meant to point to the version users should pick (in case more fixes will be necessary). If you need this in a different repo, I'm happy to create a PR.

I had to fix a few conflicts, and also to remove some of the "CAMLRUN=..." variable overrides from the Makefile (these are simply no longer necessary after the cross-build fixups in 4.02.2).

I did a quick test with a super-simple app for both modes (32/64 bit).

**Comment by damiendoligez** [comment]
Silly me, I just realized that this will probably not work as a compiler switch for OPAM, and it would be better to make a new package for the cross-compiler. As I'm moving back to France next week, I won't have the time to do it before July. If anyone else wants to try in the meantime, feel free.

**Comment by gerdstolpmann** [comment]
There is now also a version of this patch rebased to 4.02.3: https://github.com/gerdstolpmann/ocaml/tree/gs-4.02.3+ios

**Comment by xavierleroy** [comment]
A quick update following discussions at the developers's meeting last Wednesday. We are very much interested in integrating this iOS port eventually, but it needs more work than we can allocate by the next major release (OCaml 4.03). Ideally, the integration should be done in 2016 as part of a more general work on cross-compilation support. Thanks for your patience.

**Comment by gerdstolpmann** [comment]
Thanks for letting us know. It should be no problem to maintain this work as external patch for some time.

**Comment by gerdstolpmann** [comment]
Unfortunately, I cannot support this work anymore - new job, new interests, no time. Sorry for any inconvenience.

**Comment by damiendoligez** [comment]
Note: branch saved to `ios-support` in the main repo. @shindere

**Pull request closed without merging**
