### PR TITLE
Fix lack of link error when missing modules providing externals

### PR DESCRIPTION
**Pull request by chambart**
Since 4.03 when a module provide an external and the external is used, the module must be linked.
This was implemented by generating dummy code, in the pr https://github.com/ocaml/ocaml/pull/602 I changed that. It now records in the cmo file that some module is required. This correctly made module provided by cma files to be linked, but nothing checked that this was not empty at the end.

This patch add the check.

I don't have time right now to test it correclty, so I will let the CI check that it does not break any other compilation. Sorry for that, and the bug.

### CODE REVIEW

**Comment by damiendoligez** [comment]
@garrigue could you review?

**Comment by chambart** [comment]
The problem seems to come from pack.
dynlinkaux.cmo is linked into a binary, and requires (among others Arg_helpers, which is provided by the pack). It is a pack made out of module not compiled with -for-pack (I think) (which is possible in bytecode), I don't know if this has to do with that.

**Comment by chambart** [comment]
No, I just checked, there is nothing removing required modules provided by the pack.

**Comment by chambart** [comment]
Here it is, as previous, not really tested yet...

**Comment by garrigue** [comment]
OK, I'm waiting for a complete fix before reviewing.
Note that it would not be too bad if this doesn't go into 4.04, as the behavior is correct when using a library, which was the main goal. It is also a bit surprising that the behavior with ocamlc and ocamlopt are different.

**Comment by damiendoligez** [comment]
I'm keeping the 4.04 milestone for now, we'll change it if this becomes the last PR to hold up the release.

**Comment by garrigue** [comment]
It seems almost ready, except for this strange failure on w55.opt-backend using ocamlopt with flambda.
The strange part is that it is listed as passed in the log, but then reported in the failed test section.

**Comment by garrigue** [comment]
By the way, your branch doesn't seem to include my addition of `testsuite/tests/manual-intf-c`. It would help checking.

**Comment by gasche** [comment]
@garrigue this test was disabled in the 4.04 branch by Damien in 38055ef558b22620bbe1cdf8ca9e8937dd149809, because it breaks on the testing machine as it seems to depend on the presence of a `curses` library. See the commit page ( 38055ef558b22620bbe1cdf8ca9e8937dd149809 ), with a (small) discussion on how this could be made to work.

**Comment by mshinwell** [comment]
@chambart It looks like some of the "`bound_name`" changes are mixed up in this patch by accident, maybe?

**Comment by damiendoligez** [comment]
It's not `'w55.opt-backend'` that fails, but `'w55.opt-backend' with ocamlopt` a few lines down. The reporting is slightly misleading but correct.

**Comment by chambart** [comment]
@mshinwell effectively, I appently started that on the wrong branch. I'll rebase on 4.04 removing that.
I didn't look at it yet, but this error seems highly unrelated.

**Comment by garrigue** [comment]
Looking at your code, it seems that it would be easy to turn the error into a link-time warning.
I wonder whether this would not be better, for backward compatibility (even though 4.03 had a hard error in that case).
However, to be coherent, this would also have to be a warning in native code.
Do you think this could be done easily?

**Comment by chambart** [comment]
@garrigue In byte code it is effectively quite simple to do a warning instead of an error. In native code, that might be a bit trickier as this is done by adding a fake dependency (loading the cmx file). We would have to distinguish it from normal dependencies. Not that much effort, but I don't know if the benefit is really worth it. Do you know any example in the wild where this might matter ?

**Pull request merged**
