### PR TITLE
Remove legacy Windows non-Unicode mode

### PR DESCRIPTION
**Pull request by nojb**
Windows Unicode mode has been enabled by deafult for 5 years and to my knowledge not a single bug has been reported. Shall we get rid of the legacy mode for 5.0?

cc @dra27

### CODE REVIEW

**Comment by dra27** [comment]
I'm for this change, but the metric may be incorrect - the legacy mode was there for users who depended on the old behaviour. It may be more a question of finding out who's actually using the legacy mode and if they still need to? Wasn't it for the worry of de-serialising things from databases, and such like??

**Comment by nojb** [comment]
> It may be more a question of finding out who's actually using the legacy mode and if they still need to?

Yes, you are right. Unfortunately, am not sure how we would go about finding these users.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2022/04/16 12:27 -0700):
> > It may be more a question of finding out who's actually using the legacy mode and if they still need to?
>
> Yes, you are right. Unfortunately, am not sure how we would go about
> finding these users.

How abouot taking a more progressive way and, e.g., starting by not
enabling this mode by default?

We could then mark it as deprecated in 5.1, and then remove it
completely in 5.2, or something like that?

**Comment by nojb** [comment]
> How abouot taking a more progressive way and, e.g., starting by not enabling this mode by default?

This is already the case today, it is not enabled by default.

> We could then mark it as deprecated in 5.1, and then remove it completely in 5.2, or something like that?

The README reads as follows:

> The legacy mode will be deprecated and then removed in future versions of OCaml. Users are thus strongly encouraged to use the Unicode mode and adapt their existing code bases accordingly.

I guess we could change the wording in the README to read "is deprecated" instead of "will be deprecated"...

**Comment by shindere** [comment]
Ah, sorry for my mistake.

I have no strong exception, except that 5.0 is a good time for making
potentially non-backward compatible changes, which seems to contradict
what I wrote earlier, sorry.

**Comment by MisterDA** [comment]
I also want to point out for the future that Windows Version 1903 (May 2019 Update) has introduced means to force a process to use UTF-8 as the process code page. Basically, my understanding is that if you enable this mode and use a `-A` function from the Win32 API, it'll interpret strings as UTF-8 rather than ASCII. That could be an interesting path to explore!

https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

**Comment by nojb** [comment]
No clear way forward at the moment; closing.

**Pull request closed without merging**
