### PR TITLE
Do path compression, and undo it in case of unification error

### PR DESCRIPTION
**Pull request by garrigue**
This is an attempt at doing the right thing with Tlink path compression:
the code compresses all paths of length more than 1, and undoes compression if unification fails, to allow readable error message partly undoing unification.
The testsuite goes through.
I would be interested in performance numbers on code which creates long chains of Tlink.

Note that in a discussion on caml-devel, it was mentioned that if we only compress paths longer than 2, then the testsuite goes through without undoing compression. You can tests this by replacing `n > 1` by `n > 2` in `repr_link` and reverting changes in `ctype.ml`.

The cost of allowing to undo compression is unclear: if there is already an active snapshot, then compression has to be logged anyway, so there is no cost; if there is no active snapshot, then this means creating one, which adds some cost to all modifications on types. However, since some parts of the type-checker already use snapshots, I'm afraid there is already an active snapshot most of the time.

### CODE REVIEW

**Comment by gasche** [comment]
Great, thanks! Whenever I have some time I will perform the following benchmarks:
- try to compile the compiler distribution (as a representative of the usual programs that we suspect do not benefit much from compression)
- try to compile a "menhir --table"-generated parser, with and without the fix of the previous regression
- try to compile a "menhir --code"-generated parser

I have discussed link compression with Jacques in the past, but other contributors may be interested in some context. The type-checker uses an union-find-like structure internally, but without performing link compression. Folklore knowledge of the type-checker implementation is that link compression rarely matters for performance, and that the additional bookkeeping costs mean that it could actually slightly degrade the type-checking performance for typical OCaml programs.  "menhir --code" parsers were for a long time the only way I knew to obtain programs that would benefit from link compression, but a recent regression (immediately fixed by Jacques) in the type-checker also affected "menhir --table" parsers, which have a simpler code structure.

**Comment by gasche** [comment]
```
### on current trunk

# type-checking only
# menhir --table: 0m0.715s
# menhir --code: 0m50.914s

# bytecode compilation
# menhir --table: 0m0.868s
# menhir --code: 1m0.705s

# ocamlbuild compile: 0m11.142s

### Before Jacques' fix (but after the regression)

# type-checking only
# menhir --table:  0m16.565s
# menhir --code: too long

# bytecode compilation
# menhir --table: 0m16.718s
# menhir --code: too long

# ocamlbuild compile: 0m11.168s

### Before Jacques' fix, before the regression

# type-checking only
# menhir --table: 0m0.754s
# menhir --code: 1m37.776s
# 
# bytecode compilation
# menhir --table: 0m0.898s
# menhir --code: 1m38.023s

# ocamlbuild compile: 0m11.139s


### trunk, plus GPR #294

# type-checking only
# menhir --table: 0m0.587s
# menhir --code: 0m3.895s
# 
# bytecode compilation
# menhir --table: 0m0.713s
# menhir --code: 0m12.718s

# ocamlbuild compile: 11.120s
```

**Comment by garrigue** [comment]
I'm copying some measures by @gasche, posted on Mantis (http://caml.inria.fr/mantis/view.php?id=7016).
They seem to show that, at least for menhir, path compression can make a big difference (up to 10 times faster for typechecking). Of course, we could also try to find the cause for slowness inside each individual algorithm, but this seems a never ending task.

```
### trunk, plus GPR 294

# type-checking only
# menhir --table: 0m0.587s
# menhir --code: 0m3.895s
# 
# bytecode compilation
# menhir --table: 0m0.713s
# menhir --code: 0m12.718s

# ocamlbuild compile: 11.120s

### on current trunk

# type-checking only
# menhir --table: 0m0.715s
# menhir --code: 0m50.914s

# bytecode compilation
# menhir --table: 0m0.868s
# menhir --code: 1m0.705s

# ocamlbuild compile: 0m11.142s
```

**Comment by gasche** [comment]
The ocamlbuild times also seem to indicate that this patch does not degrade the compilation times for usual OCaml programs (which we could have feared due to additional book-keeping).

**Comment by gasche** [comment]
To get another data point I measure the compilation time of Camlp4, that is known to be a bit heavy on type-checking. Times given are the best among five for `make clean; make all`. There seems to be no observable difference.

```
# after path compresion: 0m58.015s
# before path compression: 0m58.575s
# before path compression, before regression fix: 0m58.196s
```

**Comment by gasche** [comment]
Given the excellent performance numbers, I would be in favor of you ( @garrigue ) merging this, if you are confident about the correctness of the approach.

**Comment by garrigue** [comment]
For the path compression itself, the code is short and verifiable. For the undoing, this is a bit more subtle, but I think just the fact we pass the testsuite is sufficient proof, since both parts of the code are called a zillion times.
The thing I'm missing a bit is more examples of broken error messages when we don't undo the path compression. There appears to be only one in the testsuite. But it's hard to create one artificially... So we have lots of tests showing that both the path compression and its undoing do not break typing, but only one that the undoing is really avoiding breaking some error messages.

Despite this, I'm going to merge this soon, since it's safe enough.

**Pull request merged**
