### PR TITLE
Switch required autoconf to 2.71

### PR DESCRIPTION
**Pull request by dra27**
Minimum version moves with the GitHub Actions runners supported version on Ubuntu. The Ubuntu 22.04 runner on GitHub action is in beta at the moment, but we only need to use it for the Hygiene job.

At some point between the move of `ubuntu-latest` to 22.04 and the release of Ubuntu 24.04 the `ubuntu-22.04` will want changing back to `ubuntu-latest` 🙂

### CODE REVIEW

**Comment by dra27** [comment]
Just for belt-and-braces, as it's a build system change, this is running through [precheck#700](https://ci.inria.fr/ocaml/job/precheck/700/).

**Comment by xavierleroy** [comment]
CI seems to be happy.  Does this mean all our test platforms have Autoconf 2.71?  Any reason to suspect some platforms are stuck with earlier versions?  Actually, I'm a bit slow and I could use a more detailed explanation of the Ubuntu 22.04 situation and the need for the change.  Thanks!

**Comment by dra27** [comment]
Sorry, I rushed that one somewhat at the weekend, as @sadiqj had been bitten by it! The only CI worker which matters for this is the Ubuntu worker on GitHub Actions, as it's the one which does the Hygiene job which includes the check that `configure.ac` generates `configure`. The default version for the worker is 20.04 (autoconf 2.69 of April 2012 with a couple of patches) but there's an opt-in 22.04 worker image (autoconf 2.71 of January 2021).

The main thing is to have a version which most developers are using, as it's a pain to generate `configure` on your workstation and then discover when you push that CI rejects it. Debian stable and RHEL are still on autoconf 2.69, but Fedora, Debian testing, Ubuntu (LTS), Arch, etc. are all on autoconf 2.71.

**Comment by Octachron** [comment]
I am in favor of switching to autoconf 2.71 now that most desktop linux distribution have switched, that will make the release process slightly simpler.

**Comment by shindere** [comment]
David Allsopp (2022/06/06 13:03 -0700):
> The main thing is to have a version which most developers are using,
> as it's a pain to generate `configure` on your workstation and then
> discover when you push that CI rejects it.

Of course another way would be not to check this in CI but that's not
really suitable because we may lose the sync between configure.ac and
configure. Yet another possibility would be to not version configure on
trunk and to generate it only when forking release branches.

**Comment by shindere** [comment]
How about making the Changes entry slightly more precise by making
explicit which version was required before?

**Comment by xavierleroy** [comment]
My main development machines are still running Ubuntu 20.04 LTS and have Autoconf 2.69.  Does this mean I'll be in trouble until the upgrade to 22.04 LTS is offered to 20.04 users?  In other words, how do you determine "a version which most developers are using"?

**Comment by shindere** [comment]
Xavier Leroy (2022/06/07 02:28 -0700):
> My main development machines are still running Ubuntu 20.04 LTS and
> have Autoconf 2.69.  Does this mean I'll be in trouble until the
> upgrade to 22.04 LTS is offered to 20.04 users?

You may have an autoconf-2.71 package you can install. If so, you can
use that autoconf version like this:

```
tools/autogen autocnf2.71
```

Again, life would be simpler if we didn't version configure, at least on
trunk.

**Comment by dra27** [comment]
> My main development machines are still running Ubuntu 20.04 LTS and have Autoconf 2.69. Does this mean I'll be in trouble until the upgrade to 22.04 LTS is offered to 20.04 users? In other words, how do you determine "a version which most developers are using"?

Until August (when 22.04.1 comes out, and 20.04 offers the upgrade), yes. Which would make this an error. I don't think there's a backport package of 2.71 for 20.04, although this Docker command does do it when run from a Git checkout locally (!!):
```
docker run --rm -it -v $PWD:/home/opam/ocaml ocaml/opam:ubuntu-22.04-opam sh -c 'sudo apt install -y autoconf ; make -C ocaml configure'
```

Perhaps this should either be paused until August (I've not yet heard of someone trying to do this on a system which doesn't have autoconf 2.69 as a separate package), or we could decide to go with @shindere's suggestion in the meantime. I object to adding autoconf as a _release_ dependency of OCaml, but that objection is entirely satisfied by including `configure` either just with the release tags (which would therefore include them in the tarballs) or even just including `configure` on release branches. If we remove `configure` from trunk, it'd just need a small update to the opam-repository package.

**Comment by shindere** [comment]
David Allsopp (2022/06/07 03:03 -0700):
> I object to adding autoconf as a _release_
> dependency of OCaml,

That would definitely be agains all the usual conventions and,
therefore, is definitely not desirable.

> but that objection is entirely satisfied by
> including `configure` either just with the release tags (which would
> therefore include them in the tarballs) or even just including
> `configure` on release branches. If we remove `configure` from trunk,
> it'd just need a small update to the opam-repository package.

Yeah, I indeed never considered the option of not distributiing the
configure script in our releases. In my opinion, we definitely should /
must distribute it, be it generated only at releases time or at
branching time.

**Comment by xavierleroy** [comment]
> You may have an autoconf-2.71 package you can install. 

No autoconf-2.71 package that I could find in Ubuntu 20.4 nor Fedora 35 (those that have autoconf 2.69).
But there is an autoconf-2.69 package in Ubuntu 22.4.  Not sure about Fedora 36.

So, please, don't merge this PR until everyone is on one of these newer distros.  In the meantime, install the autoconf 2.69 package if you're running Ubuntu 22.4.

**Comment by xavierleroy** [comment]
For the record: Ubuntu 22.4.1 LTS is out and all Ubutu users are encouraged to upgrade to it.  So, we're getting to the point where Autoconf 2.71 is "a version which most developers are using".

**Comment by xavierleroy** [comment]
I think it's time to apply this PR, as it seems that Autoconf 2.71 is now "a version which most developers are using".

**Comment by dra27** [comment]
Rebased - good to merge from my perspective.

**Review by xavierleroy — APPROVED** [review]
Thanks for the rebase.  Here is a formal approval.  Will merge next.

**Comment by xavierleroy** [comment]
Cherry-picked to 5.0: 2224550063

**Pull request merged**
