### PR TITLE
PR6692: Support for UTF-8 identifiers

### PR DESCRIPTION
**Pull request by whitequark**
This depends on https://github.com/ocaml/ocaml/pull/124 and includes it here as a way to offer a test environment via OPAM.

See http://caml.inria.fr/mantis/view.php?id=6692. I will shortly explain the specifics of this PR.

### CODE REVIEW

**Comment by whitequark** [comment]
I've updated the PR against trunk. Also, `Oprint.parenthesized_ident` was fixed in an earlier commit already.

**Comment by whitequark** [comment]
@gasche Ping?

**Comment by planar** [comment]
How is this compatible with the current state of the system, where Latin1 identifiers are accepted (and flagged as deprecated)? You are considering any non-ascii character to be uppercase, this can't be right.

**Comment by whitequark** [comment]
@planar In fact it _improves_ the support for Latin-1 identifiers. Try using ocamldep (like via ocamlbuild) to compile the following two files (saved in ISO-8859-1 and with filesystem in ISO-8859-1):

main.ml:
```
let () = Étoile.x ()
```

étoile.ml:
```
let x () = print_endline "ok"
```

ocamldep will miss the dependency, because `É` is not a letter it thinks a module name could start from, and the build would fail.

Note that with the default lexer, `é` can never end up in the `deps` array here, as ocamldep will only extract names contained in the `UIDENT` tokens. The ranges corresponding to lowercase Latin-1 characters will only ever be engaged if the lexed input contained `UIDENT` tokens with UTF-8 text.

**Comment by planar** [comment]
> Note that with the default lexer, é can never end up in the deps array here, as ocamldep will only extract names contained in the UIDENT tokens.

Then I don't understand why this test exists at all. If the lexer only allows capitalized idents at UIDENT, why does `ocamldep` need to re-check them and why only for the ASCII range?

**Comment by whitequark** [comment]
Because there are identifiers like `*predef*.option`, injected in prelude. I agree that explicitly discarding these would be nicer but I am not 100% certain I can compose a list of all of these.

**Comment by planar** [comment]
Ah I see. This is really sneaky.

I've applied your patch to trunk (commit 15915).

**Comment by whitequark** [comment]
Thanks!

**Pull request closed without merging**
