### PR TITLE
A giant leap towards enforcing tools/check-typo on the entire repository

### PR DESCRIPTION
**Pull request by dra27**
Follows on from #1287, which needs merging first. The actual changes are just the last commit - 1c28da8

### CODE REVIEW

**Comment by dra27** [comment]
All the changes in this GPR relate to reducing line-lengths and fixing whitespace.

**Comment by damiendoligez** [comment]
@dra27 I think we should drop this PR and try again later (maybe piecewise?)

**Comment by dra27** [comment]
I don't think it needs breaking up - just rebasing (and updating).

**Comment by damiendoligez** [comment]
But won't it be too hard to rebase?

**Comment by dra27** [comment]
No - I've already done it! Just testing it... it's revealed a couple of little changes to ocamltest, so once the whole testsuite is passing again, I'll split the new bits into separate pull requests and push the new version of this one *just* with whitespace/line-length altering changes.

**Comment by shindere** [comment]
Great! Many thanks for the hard work, @dra27!

**Comment by dra27** [comment]
OK, this single commit contains fixes which are solely the correction of whitespace (with occasional knock-on consequences for the testsuite reference files) and overly long lines. Overly long lines are fixed using (hopefully) non-controversial string-splitting, etc.

This diff is much easier to look at using a whitespace-eliminating diff tool such as `patdiff`

**Comment by dra27** [comment]
A clearer view of this diff may be found at http://people.ds.cam.ac.uk/dra27/gpr1288-patdiff.html

**Comment by dra27** [comment]
Rebased, partly to kick AppVeyor, and partly because this branch should now represent a fully check-typo passing `trunk`

**Comment by dra27** [comment]
OK - assuming the revised version with GPR#1825 whitespace fixes passes, can this be merged? The patdiff-generated diff above is still correct (rebasing didn't have any conflicts).

**Review by damiendoligez — APPROVED** [review]
I have reviewed the patdiff and everything looks correct.

**Comment by dra27** [comment]
Thanks, @damiendoligez! Here goes, and apologies to everyone whose patches need updating...

**Comment by shindere** [comment]
David Allsopp (2018/06/14 07:15 -0700):
> Merged #1288.

Congrats! and many, many thanks for your hard work on this!!!

**Pull request merged**
