### PR TITLE
Manual: remove remnants of labltk documentation from the manual source tree.

### PR DESCRIPTION
**Pull request by Octachron**
This PR proposes to remove the last remnant of the documentation of labltk from the source tree of the manual. This documentation was no longer built (since the separation of labltk?) and thus invisible for users. 

Note that labltk is still mentionned (with ocamlbrowser) as a split library in the ocamlbrowser chapter.

### CODE REVIEW

**Comment by gasche** [comment]
Does the new home of labltk has the manual? Would they be interested in those files? (@garrigue would know?)

**Comment by Octachron** [comment]
The project page on ocamlforge does seems to have a manual. However, it does not seem accessible (and there is an issue open on this matter on the bug tracker). The source itself does not contain any documentation. Thus, I don't know if these files would be useful for the current distribution of labltk.

**Comment by mshinwell** [comment]
This seems fine to merge.  @garrigue has been pinged here and can take the diff if he so wishes.

**Comment by mshinwell** [comment]
(I think Travis may have had a spurious failure here; I will keep an eye on the main repo status after merging.)

**Comment by garrigue** [comment]
The manual has been available from the file download area of labltk since last year.
Just forgot to close the ticket.

**Pull request merged**
