### PR TITLE
[minor] missing @since tag in Filename.quote_command documentation

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by gasche** [comment]
The function was added in #1492 and the corresponding trunk commit is a8daa89500f2aee6d73b6915928f9f65f0a8dff3, first included in 4.10.

**Review by nojb — APPROVED** [review]
LGTM

**Review by xavierleroy — APPROVED** [review]
Sure thing.  Thanks for noticing.

**Comment by xavierleroy** [comment]
Cherry-picked to 4.12: 71ef9dc81

**Pull request merged**
