### PR TITLE
Remove uses of ;; from the codebase (spring cleanup)

### PR DESCRIPTION
**Pull request by shindere**
Obviously not the greatest contribution on earth, but it seemed
suitable to do that in preparation for OCaml 5.0.

There are three remaining uses of `;;` in the codebase itself, in
`tools/ocaml{c,opt}p.ml` and in `ocamldoc/odoc.ml`. I didn't dare to remove
them because the changes would have been less cosmetic (unless I missed a
cosmetic way to do that).

It could also be nice to remove the `;;` from the code generated
by ocamllex and ocamlyacc and from the manual when not talking about
toplevel phrases, but again I prefered to leave that out at the moment
so that the present PR, though a bit long, remains as trivial to review
as possible.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Why not? Usually we worry about conflicts on such cosmetic PRs, but this time I hope it's okay: most of the development pressure right now is on the runtime (.c files) which are not touched by this patch (except one .c file where a stray `;;` gets turned into its proper `;` form).

I guess it's nice to see patches that remove more lines than they add.

**Comment by gasche** [comment]
More thinking on this:
- It's easy to get dragged into long periods of indecisions on such PRs, which make things worse.
- So the easiest way to deal with them is to merge them quickly and move on.
- I'll still wait a day or so in case there is a Very Good Reason to not do this that I missed.

**Comment by shindere** [comment]
Gabriel Scherer (2022/02/25 02:12 -0800):
> @gasche approved this pull request.

Thanks.

> Why not? Usually we worry about conflicts on such cosmetic PRs, but
> this time I hope it's okay: most of the development pressure right now
> is on the runtime (.c files) which are not touched by this patch
> (except one .c file where a stray `;;` gets turned into its proper `;`
> form).

Indeed. For the record, a similar thing happens in `otherlibs/systhreads/st_stubs.c`.

> I guess it's nice to see patches that remove more lines than they add.

I admit it's a guilty pleasure for me to remove lines.

**Comment by shindere** [comment]
Gabriel Scherer (2022/02/25 02:13 -0800):
> More thinking on this:
> - It's easy to get dragged into long periods of indecisions on such
> PRs, which make things worse.

Indeed. The longer a PR waits, the more it's likely one has to rebase
it, which is both time-consuming and error-prone.

> - So the easiest way to deal with them is to merge them quickly and
> - move on.

I agree.

> - I'll still wait a day or so in case there is a Very Good Reason to
> - not do this that I missed.

Fine with me. Thanks a lot.

**Comment by shindere** [comment]
This broke a test and I didn't notice, sorry.

I am working on fixing that test and will push a fix ASAP and report it here.

**Comment by shindere** [comment]
Just fixed the broken test by pushing 03492e53f2d94d2933a7b760f7558ac03cd45890

**Pull request merged**
