### PR TITLE
Use a different type for primitives in clambda and lambda

### PR DESCRIPTION
**Pull request by chambart**
This patch defines a new `Clambda_primitive` module containing the primitive for Flambda and Clambda. The aim of this patch is to allow to refactor the types to remove the parts that are meaningless in the backend.

This does not yet contain a lot of the refactoring itself.

Note that this will be required by the future developments of flambda which includes a specific type for primitives in flambda that can't really be represented into the current primitive type of lambda without adding a lot of new cases useless for the bytecode implementation.

### CODE REVIEW

**Comment by chambart** [comment]
The CI failure are tests that does not compile to the exact same binary with ocamlopt.opt and ocamlopt.byte.

**Comment by chambart** [comment]
I must have misdone something. I never intended to close this...

**Comment by mshinwell** [comment]
I'm going to rebase this onto trunk since I've already had to do that once on the dev Flambda branch.

**Comment by chambart** [comment]
Rebased

**Comment by chambart** [comment]
@alainfrisch @xavierleroy would you object to this ? Otherwise this is ready to merge.

**Comment by xavierleroy** [comment]
Well, I tried to read the diff.  It's so big that I gave up.  I'm fine with the idea; it's just that someone else will have to check all those changes and vouch that they are correct and not excessively intrusive.

BTW: I see a .ml file containing type definitions only, and an identical .ml file.  What's the policy *du jour* concerning those?  It's no longer OK to have only the .mli?  or only the .ml?

**Comment by chambart** [comment]
It's problematic to have only the mli. It's ok to have only the ml, but the Makefiles do not seem to handle that well. Maybe a symlink is the right way to go.

**Comment by chambart** [comment]
There was some rebasing error. Pushed a cleaned version.

**Comment by chambart** [comment]
Rebased

**Comment by mshinwell** [comment]
I will review this once the CI passes.

**Comment by chambart** [comment]
Notice that it might be easier to review the patches separately rather than the complete diff.

**Comment by chambart** [comment]
On 64bits the build failure is a binary that is different in bytecode and native.
But on 32bits there is a real error with the string_access test. I'll look into this.

**Comment by chambart** [comment]
Rebased on trunk. (thanks @lthls)

**Review by lthls — APPROVED** [review]
I've reviewed the implementation, and I believe it is correct.

The actual changes in the rest of the code are minimal: the primitives for Lambda are left untouched, and the new type introduced for Clambda primitives is the same as the Lambda one except for the following changes:
- The `Pstring_load_*`, `Pbytes_load_*`, `Pbytes_set_*` primitives and their Bigstring equivalents have been merged into primitives taking a size argument (and a variant argument for safety instead of a boolean).
- The primitives `Pidentity`, `Pbytes_to_string`, `Pbytes_of_string`, `Pctconst`, `Pignore`, `Prevapply`, `Pdirapply`, `Pgetglobal` and `Psetglobal` have been removed. A new primitive `Pread_symbol` is added to replace `Pgetglobal`, the others are expected to be dealt with when translating from Lambda (most were already dealt with anyway).

The rest are mostly mechanical changes induced by the change in types.

This pull request is rather important for simplifying other pull requests on the backend, so it would be helpful to get it merged early in the 4.09 cycle.

**Comment by chambart** [comment]
Moved `Changes` entry to trunk section.

**Comment by chambart** [comment]
@alainfrisch Do you have any objection ? Otherwise I think this is good to go.

**Comment by alainfrisch** [comment]
I haven't reviewed the PR, but I have no objection in principle.

**Comment by chambart** [comment]
This has already been reviewed, that was the kind of non objection I expected.

**Comment by shindere** [comment]
Currently the Change entry for this GPR says:

Add a separate types for clambda primitives

Is there onlyone  type of are there several of them?

Could the change entry be fixed accordingly, please?

**Comment by damiendoligez** [comment]
ping @chambart

**Pull request merged**
