### PR TITLE
Remove Cloop and Iloop from Cmm and Mach

### PR DESCRIPTION
**Pull request by mshinwell**
Whilst working on #856 it occurred to me that we have rather a lot of duplication between the "loop" and "catch" constructions in Cmm and Mach.  The recent support for recursive continuations in "catch" means, I think, that we can easily express the previous looping construct using "catch".  This seems a win in particular since these recursive constructions involve tricky computations (e.g. during liveness and availability analysis) and it is better to have fewer of such things.

@chambart I noticed that in `spill.ml` the mutable state (current date and destroyed-at-fork map) isn't being saved and restored for `Icatch` in the same way as the `Iloop` case was doing.  Is this a mistake in the previous patch?

### CODE REVIEW

**Comment by chambart** [comment]
I'm going to fix spill as discussed.

**Comment by mshinwell** [comment]
I've merged (into this GPR) Pierre's patch which corrects the previous mistake with regards to `spill.ml`.  Pierre says about this patch:

"There was nothing seriously broken, but nested loops with some ifs inside could produce large association lists. Going for a map is probably the simplest way to fix that.

I had to make instructions comparable. The previous equality being a physical equality, it had to be with a unique identifier. That led to adding an `id` field in `Mach.instruction`, which contains a fresh identifier, and make `Mach.instruction` private to ensure it is updated. The majority of the patch is the substitution from `{ i with next = something }` to `Mach.with_ i ~next:something`"

**Comment by mshinwell** [comment]
@xavierleroy I would like to ask your opinion on a specific aspect of this patch before I spend time polishing it up.  We would like to change Mach instructions to be private so that they can hold a unique integer identifier maintained such that equality on such identifiers coincides with physical equality.  This means that we can efficiently use instructions as keys in maps.  Are you happy with that?

This is probably a good change anyway, but we have a specific application right now: to turn the association list in `Spill` for destroyed-at-fork information into a map.  When processing possibly mutually-recursive `Icatch` handlers we don't reset the destroyed-at-fork information each time around the fixpoint loop, unlike the "old" code does for `Iloop`, for simplicity because it isn't clear what the traversal order around the graph of handlers should be.  This could cause the association list to grow large, e.g. with nested loops and conditionals.  Given that the existing code clears the list for `Iloop` we presume you were concerned with the size of this list and thus it would be appropriate to use a map now that it may grow even longer.

**Comment by mshinwell** [comment]
Hmm, actually, thinking about this some more: maybe `destroyed_at_fork` should be reset at the start of the `fixpoint` function in the `Icatch` case.  During the first ("reload") phase the list is only added to; all that seems to matter is what was added to it in the last fixpoint iteration (since things added in previous iterations will correspond to instructions that will have been discarded).  If this is the case then maybe there's no problem and an association list will suffice.

**Comment by xavierleroy** [comment]
I don't feel the need for unique identifiers on every Mach instruction.  I do feel a need for unique names for the local, second-class, tail-called functions that are represented today using `Ccatch`.  The entrypoint of those functions correspond exactly to the nodes of the CFG where we want to memoize information during efficient dataflow analysis.  Proper naming of those functions would also avoid the need for a `rec_flag` on the `Ccatch` construct.

**Comment by chambart** [comment]
@xavierleroy, I would argue otherwise. An unique identifier allows to add more annotations to instructions without growing the type. It could allow to remove the live field from the type for instance. In this situation this is exactly what is happening. Some information about an instruction is stored to be retrieved in the following pass.

I think that the gdb improvements patchs add some other fields to mach. Exposing those pass as
"Mach.fundecl -> annotation Mach.Instruction.Map.t" rather than "Mach.fundecl -> Mach.fundecl"
feels better I think.

By the way having unique identifiers for those 'labels' would be an improvement (there is a PR in the work). Note that for efficient CFG node memoization, if and switch branch identifiers might be useful. This can be achieved by replacing
```OCaml
  | Iifthenelse of test * instruction * instruction
  | Iswitch of int array * instruction array
```
by
```OCaml
  | Iifthenelse of test * label * label
  | Iswitch of int array * label array
```

**Comment by chambart** [comment]
I made a quick and dirty try at removing live_set from Mach.instruction to see what it would look like:
Please disregard the obvious dirtyness in there: 
https://github.com/chambart/ocaml-1/commit/4f241141c999a90b36e89ef6dd3d649dd1a9f159

**Comment by mshinwell** [comment]
This has been superceded by #1660.

**Pull request closed without merging**
