### PR TITLE
Fix MPR#7852 by reverting #1737

### PR DESCRIPTION
**Pull request by trefis**
Fixes [MPR#7852](https://caml.inria.fr/mantis/view.php?id=7852) by reverting GPR #1737 .

It's currently impossible to test trunk on janestreet's codebase (and probably on a good chunk of opam) because of this bug, so let's do the quick fix and we can have a look later at how to arrange things.

Ping @Drup , @hhugo .

### CODE REVIEW

**Review by Drup — APPROVED** [review]
This makes me sad. The fault lies in the implementation in Env, not in your patch. Let's revert until we have a better solution.

**Review by gasche — APPROVED** [review]
Good to go if the CI passes.

In my experience it's tricky to remember to re-merge these things once they are reverted. Maybe one way to avoid this would be to open a new PR with the (about-to-be-reverted code), the WIP status, and a pointer to the issues that were created.

**Comment by trefis** [comment]
I had forgotten to `git add` the new test file :laughing: 
Running the CI again.

**Comment by damiendoligez** [comment]
@trefis will you open a new PR as suggested by @gasche? Or should I do it?

**Comment by trefis** [comment]
Meh. I'm not sure it's worth it honestly.
There were regression tests for #1737, which I left in (the output is just not what we'd want them to be). Apart from that I'm not sure an open GPR with no content buried 5 pages away on the GPR list is going to be much of a reminder.

Also, AFAICT, it'd be a non trivial amount of work to get that thing to work properly with the current architecture. (There might be some horrible hacks we can implement to get it working without too much work, but I really don't want to go there)

**Comment by gasche** [comment]
Could someone produce a clear explanation, somewhere, of what the problem is? @trefis and @Drup appear to know what the problem is, but there are no explanations in [MPR#7852](https://caml.inria.fr/mantis/view.php?id=7852) for others to understand.

**Comment by trefis** [comment]
I'll write something up.

**Comment by damiendoligez** [comment]
ping @trefis

**Comment by trefis** [comment]
I updated [MPR#7852](https://caml.inria.fr/mantis/view.php?id=7852).

**Pull request merged**
