### PR TITLE
cygwin CI: rebase to avoid fork problems

### PR DESCRIPTION
**Pull request by damiendoligez**
Temporary fix to the fork() problem on the Inria CI machines with cygwin.

@dra27 Does this look good?

### CODE REVIEW

**Comment by dra27** [comment]
Have you been seeing the problem with cygwin32 (that should have been fixed since 1.7.2)? I'd restrict the dorebase to cygwin64 only.

**Comment by damiendoligez** [comment]
I didn't see the problem on 32-bit cygwin, but I checked that the fix doesn't hurt. Since there is nothing in the script that discriminates between 32 and 64, I figured I'd use the fix for both. Do you think think might be a problem later?

**Comment by shindere** [comment]
Damien Doligez (2017/09/05 11:02 -0700):
> I didn't see the problem on 32-bit cygwin, but I checked that the fix
> doesn't hurt. Since there is nothing in the script that discriminates
> between 32 and 64, I figured I'd use the fix for both. Do you think
> think might be a problem later?

Should you have to discriminate, you may be able to do it rather easily
by grepping for ARCH_SIXTYFOUR in byterun/caml/m.h, I believe.

**Comment by xavierleroy** [comment]
This is "only" the testing infrastructure, so it doesn't need to be bullet-proof.  Merging!

**Pull request merged**
