### PR TITLE
allow syntax Functor(val x)

### PR DESCRIPTION
**Pull request by v-gb**
Instead of just `Functor((val x))` right now.

### CODE REVIEW

**Comment by garrigue** [comment]
Makes sense.

**Comment by alainfrisch** [comment]
Can you update the manual accordingly (in exten.tex)?

**Comment by v-gb** [comment]
I don't know if you want me to note in the manual something like "starting at 4.05 we can do F(val x)", or change the grammar in the manual. In the latter case, it's easy to change the manual the same way the parser was changed, but it sounds like too much detail. The grammar is already approximate, for instance:
```
pattern: ...
         | 'lazy' pattern
```

but `lazy lazy _` is not valid pattern.

**Comment by mauny** [comment]
lazy (lazy _) is a valid pattern, but needs parentheses.

**Comment by Octachron** [comment]
I don't think that updating the grammar here would be very useful since the grammar description in this chapter is indeed quite approximate.  I think that adding an "introduced in 4.05" note in the header and a short mention in the "Conversely, the module expression ( val expr : package-type )…" paragraph should be enough. Eventually, an example exercising the new syntax might be nice: it would help people that skim over the text description and focus on code examples.

**Comment by v-gb** [comment]
I added a change to the manual, but I don't think it's a good idea because the language is not changing here.

I'll point out that the manual doesn't build without commenting out the check-stdlib-modules check that complains about spacetime not being documented.

**Comment by Octachron** [comment]
> I don't think it's a good idea because the language is not changing here

I am not sure I follow your point here? With this PR, there are some code fragments that will parse with 4.05 but not with 4.04. This is a visible change for users that ought to be documented.

> I'll point out that the manual doesn't build without commenting out the check-stdlib-modules check that complains about spacetime not being documented.

This is fixed in 4.04 but the commit fixing this problem has not yet been merged in trunk.

**Comment by v-gb** [comment]
The change is documented in the changelog, just like any random typer or backend bug that prevents valid programs from being successfully compiled.

**Comment by garrigue** [comment]
Travis is successful but Appveyor fails.
Is it safe to merge?

**Comment by v-gb** [comment]
The Appveyor failure certainly looks spurious: the tests pass locally, and Appveyor is ok with the first commit, and the second commit only adds a couple of sentences to the manual so it's hard to see how would break dozens of tests.

**Comment by garrigue** [comment]
OK, then I merge. Thank you for the PR.

**Comment by v-gb** [comment]
Thanks.

**Pull request merged**
