### PR TITLE
Fix typographic issues in the doc of new modules

### PR DESCRIPTION
**Pull request by gadmm**
To backport as well.

### CODE REVIEW

**Comment by Octachron** [comment]
The inversion of type and documentation is unnecessary: the current style is also used in older modules (see the [Complex]( https://caml.inria.fr/pub/docs/manual-ocaml-4.00/libref/Complex.html) module for instance).

**Comment by gadmm** [comment]
This seems to cause issues in the case of variant types, see for instance https://caml.inria.fr/pub/docs/manual-ocaml/libref/Stdlib.Option.html .

**Comment by Octachron** [comment]
This is a very good point, this is indeed an error. However, the right fix is to add an empty doc comment:

```OCaml
type t = bool = false | true (**)
(** The type of booleans (truth values).
    ...
*)
```

**Comment by gadmm** [comment]
Interesting, where can I read up on the style mandated in this repository?

**Comment by Octachron** [comment]
It is not so much a question of style than a question of documentation attachment. This issue is discussed at the end of https://caml.inria.fr/pub/docs/manual-ocaml-4.08/manual041.html#sec276 .

**Comment by gadmm** [comment]
It says that mine is correct as well, so I am going to leave it as is for now.

**Comment by Octachron** [comment]
This is still an unrelated stylistic change. It would be better to keep your nice typographic fixes separated from those style changes — by splitting those changes in a different PR.

**Comment by gadmm** [comment]
Replying to you in private

**Comment by Octachron** [comment]
As discussed, I pushed a commit with the minimalist version. I also added the same fix for `List` and `ListLabels` if you wish to cross-check the change.

**Comment by gadmm** [comment]
LGTM. Indeed, I missed List and ListLabels. Thanks.

**Comment by gadmm** [comment]
@dra27 Your comment https://discuss.ocaml.org/t/ocaml-4-08-1-rc1/4116/4 reminded me of this, I quickly checked and this has not been cherry picked yet.

Here it's a very minor patch, but let me know if there's something better I can do to register my intent to backport in the future.

**Comment by dra27** [comment]
@gadmm - I think your original sentence at the top was enough!

@Octachron - I think this is safe to cherry-pick to 4.08?

**Comment by Octachron** [comment]
Yes, indeed. I had forgotten to cherry-pick it to 4.08 and 4.09.

**Comment by Octachron** [comment]
@dra27 , thanks!

**Pull request merged**
