### PR TITLE
Map typath

### PR DESCRIPTION
**Pull request by HyunggyuJang**

### CODE REVIEW

**Comment by gasche** [comment]
@HyunggyuJang could you explain what is the reason for this change?

**Comment by garrigue** [comment]
Currently `typath` is only used to type paths in several categories.
The idea of this PR is to introduce a symmetric encoding function, and use it where special type paths are created, rather than doing the encoding by hand as is done currently.
Eventually, we would like to extend this to include object types (the #c corresponding to a class c) and abstract rows, rather than having functions that decode the names.

**Comment by lpw25** [comment]
Any chance of just adding the additional constructors to `Path.t`? Encoding additional constructors in a type via whether they use capital letters is not the best software engineering practice. I wrote a patch to do that myself a number of years ago as part of some work on namespaces -- it didn't take very long and the code was definitely clearer.

**Comment by garrigue** [comment]
> Any chance of just adding the additional constructors to `Path.t`? Encoding additional constructors in a type via whether they use capital letters is not the best software engineering practice. I wrote a patch to do that myself a number of years ago as part of some work on namespaces -- it didn't take very long and the code was definitely clearer.

Interesting idea. Our idea was rather to use a different type for type paths (dropping the encoders and decoders); not sure which is lighter.

**Comment by garrigue** [comment]
@lpw25 We're now trying to include the information in the path itself, but having this go through `Env` is far from trivial.
Is your code still available somewhere?

**Comment by lpw25** [comment]
I couldn't find the old branch so I throw together a new one: https://github.com/lpw25/ocaml/tree/constructor-typath-in-path

**Comment by lpw25** [comment]
Here's the main commit: https://github.com/lpw25/ocaml/commit/7a21a1c353189bad6b779e09b48e27aaccc5a952

**Comment by garrigue** [comment]
> I couldn't find the old branch so I throw together a new one: https://github.com/lpw25/ocaml/tree/constructor-typath-in-path

Thanks, we are considering basing ourselves on that, adding #-types and abstract row types to this scheme.

**Comment by HyunggyuJang** [comment]
Subsumed by #11315

**Pull request closed without merging**
