### PR TITLE
Add "deprecated" warnings for uses of old C runtime function names

### PR DESCRIPTION
**Pull request by xavierleroy**
Unless `CAML_NAME_SPACE` is defined, users of the runtime system can still use short names like `stat_alloc` to refer to runtime functions like `caml_stat_alloc`.  These short names are implemented as macros in `<caml/compatibility.h>`.

There is talk of (finally!) removing short name support in OCaml 5.00.  In preparation for this removal, this PR proposes to add warnings when short names are used, and likewise for other runtime system macros that are considered deprecated.

The implementation is awful C macrology cobbled from stackoverflow, and works with GCC and Clang but not MSVC.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Example of warning produced by GCC:
```
stubs-zlib.c:191:13: warning: "alloc_small" is deprecated: use "caml_alloc_small" instead
  191 |   bucket = alloc_small(2, 0);
      |             ^~~~~~~~~~~~~~~~~                                                
stubs-zlib.c:194:13: warning: "mlraise" is deprecated: use "caml_raise" instead
  194 |   mlraise(bucket);
      |             ^~~~~~                                                 
```

**Comment by xavierleroy** [comment]
Clang finds it necessary to add much noise around the warning:
```
stubs-zlib.c:191:12: warning: "alloc_small" is deprecated: use "caml_alloc_small" instead [-W#pragma-messages]
  bucket = alloc_small(2, 0);
           ^
/usr/local/ocaml-experimental/lib/ocaml/caml/compatibility.h:47:21: note: expanded from macro 'alloc_small'
#define alloc_small CAML_DEPRECATED("alloc_small", "caml_alloc_small") caml_alloc_small
                    ^
/usr/local/ocaml-experimental/lib/ocaml/caml/misc.h:53:3: note: expanded from macro 'CAML_DEPRECATED'
  CAML_PREPROWARNING(name1 is deprecated: use name2 instead)
  ^
/usr/local/ocaml-experimental/lib/ocaml/caml/misc.h:51:31: note: expanded from macro 'CAML_PREPROWARNING'
#define CAML_PREPROWARNING(x) _Pragma(CAML_MAKEWARNING2(x))
                              ^
<scratch space>:128:6: note: expanded from here
 GCC warning "\"alloc_small\" is deprecated: use \"caml_alloc_small\" instead"
     ^
stubs-zlib.c:194:3: warning: "mlraise" is deprecated: use "caml_raise" instead [-W#pragma-messages]
  mlraise(bucket);
  ^
/usr/local/ocaml-experimental/lib/ocaml/caml/compatibility.h:107:17: note: expanded from macro 'mlraise'
#define mlraise CAML_DEPRECATED("mlraise", "caml_raise") caml_raise /*SP*/
                ^
/usr/local/ocaml-experimental/lib/ocaml/caml/misc.h:53:3: note: expanded from macro 'CAML_DEPRECATED'
  CAML_PREPROWARNING(name1 is deprecated: use name2 instead)
  ^
/usr/local/ocaml-experimental/lib/ocaml/caml/misc.h:51:31: note: expanded from macro 'CAML_PREPROWARNING'
#define CAML_PREPROWARNING(x) _Pragma(CAML_MAKEWARNING2(x))
                              ^
<scratch space>:132:6: note: expanded from here
 GCC warning "\"mlraise\" is deprecated: use \"caml_raise\" instead"
     ^
```

**Comment by shindere** [comment]
We obviously need such a deprecation mechanism and the implementation
looks correct to me. Very cool that it allowed to eliminate uses
of deprecated macros from the runtime itself!

**Review by shindere — APPROVED** [review]

**Comment by dra27** [comment]
If wanted, https://github.com/dra27/ocaml/commit/0681f81c86fdbfe0ffb0082868a8ef12e90f8d36 adds the message for MSVC and https://github.com/dra27/ocaml/commit/49c8aaa54a5aaf7e697e41c87e821ee5b9e1525c is a way of turning that into a warning (I haven't checked if turning on C4995 triggers elsewhere - although if it does, then that's something that should be fixed!)

**Comment by dra27** [comment]
There might be a version which works before VS 2019 (16.5) but according to the bug-tracker that's when `_Pragma` was added, so I went with that

**Comment by xavierleroy** [comment]
> We obviously need such a deprecation mechanism

Well, I'd like an opinion from the OPAM standpoint @kit-ty-kate maybe?
- If we have these warnings in 4.14, some packages will break (those that have GCC warnings as errors and use the deprecated short names) and other packages (the other packages that use short names) will produce copious amounts of warnings.
- If we don't do anything in 4.14 and just remove short name support in 5.00, both kinds of packages will work in 4.14 and break in 5.00. 

Which of the two approaches is most effective?

**Comment by kit-ty-kate** [comment]
> Well, I'd like an opinion from the OPAM standpoint @kit-ty-kate maybe?
> 
>     * If we have these warnings in 4.14, some packages will break (those that have GCC warnings as errors and use the deprecated short names) and other packages (the other packages that use short names) will produce copious amounts of warnings.
> 
>     * If we don't do anything in 4.14 and just remove short name support in 5.00, both kinds of packages will work in 4.14 and break in 5.00.
> 
> 
> Which of the two approaches is most effective?

I'm still in vacations so I don't have time to test much of what I'm going to say here but my guess is that most packages that have `-Werror` are also the ones that are broken by any tiny changes in either the compiler or GCC. So I suspect that this shouldn't be too radical in terms of the number of packages broken by this.

I would personally be in favour of adding the warnings as soon as possible and if it's really too much (but i doubt it), we can always revert down the line during the alpha stage.

**Comment by xavierleroy** [comment]
> If wanted, dra27@0681f81 adds the message for MSVC 

It's short and nice, so I picked it and put it in this PR.

> and dra27@49c8aaa is a way of turning that into a warning

It's ... less short and less nice, so I passed.

Also, following a recent discussion elsewhere, I added deprecation warnings for the macros caml_aligned_malloc, caml_strdup and caml_strconcat from misc.h.

**Comment by xavierleroy** [comment]
Our own test suite revealed strange behaviors when `CAML_INTERNALS` is defined but `CAML_NAME_SPACE` is not...  I pushed  some fixes, but a second review is in order.    

@damiendoligez : could you please look at 59f9caf  at least, and at the whole PR if possible?

FYI: "precheck" CI passes.

**Review by damiendoligez — APPROVED** [review]
This all looks good to me, including the changes to `major_gc.h`.

**Comment by yallop** [comment]
There's an issue with these deprecation warnings that I discovered when testing ctypes against the 4.14.0 alpha release.

The deprecation warnings are designed to catch uses of unprefixed identifiers that refer to externally-defined names.  However, they're also triggered by internal uses of names that happen to coincide with the names in `caml/compatibility.h`.

For example, the following file compiles without warnings with OCaml 4.13.1:

```c
#include <caml/mlvalues.h>
#include <stdlib.h>

typedef char int8;

int8 *twelve(void)
{
  int alloc = 12;
  return malloc(alloc);
}
```

However, OCaml 4.14.0~alpha emits lots of warnings:

```
test.c:4:13: warning: "int8" is deprecated: use "caml_ba_int8" instead
    4 | typedef char int8;
      |             ^~~~~~                                                
test.c:6:13: warning: "int8" is deprecated: use "caml_ba_int8" instead
    6 | int8 *twelve(void)
      |             ^~~~~~                                                
test.c: In function ‘twelve’:
test.c:8:13: warning: "alloc" is deprecated: use "caml_alloc" instead
    8 |   int alloc = 12;
      |             ^~~~~                                                
test.c:9:13: warning: "alloc" is deprecated: use "caml_alloc" instead
    9 |   return malloc(alloc);
      |             ^~~~~~~~~~~                                          
```

From one point of view the macros in OCaml 4.13.1 (which rename `alloc` and `int8` to `caml_alloc` and `caml_ba_int8`) result in the program being compiled rather strangely, since the names of local identifiers are silently changed.  However, from another point of view OCaml 4.13.1 is just performing harmless alpha conversion (which coincides with naive substitution in most realistic cases), and OCaml 4.14.0~alpha is warning about harmless uses of bound variables when problems are only likely to arise with free variables.

**Comment by dra27** [comment]
@yallop - really the deprecation warning is about _not_ defining `CAML_NAME_SPACE` before including the headers which has been documented since 2013 (see #4013) and more strongly warned about for two years (see #9257). Is the problem in c types eliminated if `CAML_NAME_SPACE` is defined?

**Comment by xavierleroy** [comment]
+1 for using `CAML_NAME_SPACE`.

This said, it could make sense to not have deprecation warnings for `int8`, `uint8`, `int16` and `uint16`, because these are fairly common names.  The warning would still trigger on the other unprefixed names coming from the bigarray C interface, and that should be enough to push users towards using prefixed names.

**Comment by yallop** [comment]
> Is the problem in c types eliminated if `CAML_NAME_SPACE` is defined?

It is - thanks!

Now that all the short names in `caml/compatibility.h` are deprecated, it'd be quite useful to have an additional warning when `CAML_NAME_SPACE` is not defined.

**Comment by dra27** [comment]
Perhaps we can add that to the deprecation message, e.g. `"alloc" is deprecated: use "caml_alloc" instead (see CAML_NAME_SPACE in Interfacing with C)` or some such?

**Comment by xavierleroy** [comment]
> it'd be quite useful to have an additional warning when CAML_NAME_SPACE is not defined.

This would penalize code that uses the caml_ prefixed names but doesn't define CAML_NAME_SPACE.  To me that's a correct use of the OCaml FFI and it should not trigger a warning.

**Pull request merged**
