### PR TITLE
Add some cross-references to the bigarray documentation.

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by dra27** [comment]
AppVeyor's backed up at the moment because of a technical problem at their end - can't see a downside to merging this!

**Comment by Octachron** [comment]
Small nitpicking, it would be nice to also replace`[Genarray.create]` by a cross-reference in the documentation of `Array0.create` at line 465.

**Comment by yallop** [comment]
@Octachron: thanks; see b11dfac.

**Comment by dra27** [comment]
Would it be particularly difficult for ocamldoc to warn that code references could be a cross-reference? Is there an obvious case when `{!foo}` is a valid cross-reference when it would be worse than `[foo]`?

**Comment by Octachron** [comment]
@yallop Perfect.

@dra27 For generic identifiers, I would say that there would be too many false positives.
Consider, for instance, a module with the following signature
```OCaml
type 'a t
val map: ('a -> 'b) -> 'a t -> 'b t

(** [filter_map ~map pred sth] filters any element [elt] such that [pred (map elt)] is false.
By default, [map] is the identity function *)
val filter_map: ?map:('a->'a) -> ('a -> bool) -> 'a t -> 'a t
```
in this situation replacing `[map]` with `{!map}` would be wrong. 
Contrarily, for identifiers of the form `A. … . b`, it might be worthwhile, I will have a look.

**Comment by Octachron** [comment]
Merged.

**Pull request merged**
