### PR TITLE
Fix #12255 - handle large signal numbers correctly.

### LINKED ISSUE #12255: Signals with large signal numbers not handled correctly
The `signals.c` module in the runtime uses a multi-word bitmap to record pending signals for delivery to the runtime. The C signal handler `handle_signal()` calls `caml_record_signal()` to set the appropriate bit in this bitmap. However, the dispatching function `caml_process_pending_signals_exn()` uses [an incorrect calculation](https://github.com/ocaml/ocaml/blob/48a321c0900424a785d1f2544aa383b02b4b76d7/runtime/signals.c#L85) to find the signal number for a set bit, if the bit isn't in the first (zeroth) word of the bitmap:
`signo = i * 8 + j + 1;` should be `signo = i * BITS_PER_WORD + j + 1;`

### PR DESCRIPTION
**Pull request by NickBarnes**
One-liner fixing #12255; see issue for description.

### CODE REVIEW

**Review by dra27 — APPROVED** [review]
LGTM, thanks! Origin is #10880. This ought to go on 5.1 just because, but in practice this will have only been observable on 32bit systems, and even then I think only ones using real time signals...

**Comment by NickBarnes** [comment]
I note in passing that we don't handle multiple delivery for POSIX realtime signals, which (along with signal queueing) is supported on Linux. If several instances of the same signal are queued for an OCaml process, I think that only one of them will be delivered. Similarly, we discard any value passed with a queued signal (see [sigqueue](https://pubs.opengroup.org/onlinepubs/009695399/functions/sigqueue.html)).

**Comment by xavierleroy** [comment]
Well spotted, thanks.  Regarding real-time signals, OCaml makes no attempt to support them, e.g. the Unix library gives no function or constant to refer to real-time signals, and this is fine.

**Comment by avsm** [comment]
@NickBarnes if you need real-time signals, then you can also create an issue on https://github.com/ocaml-multicore/eio/issues, as we should be able to support them in Eio_linux using signalfd (since we can use the full extent of syscalls in the Linux-specific portion of the library).

**Comment by NickBarnes** [comment]
> @NickBarnes if you need real-time signals, then you can also create an issue on https://github.com/ocaml-multicore/eio/issues, as we should be able to support them in Eio_linux using signalfd (since we can use the full extent of syscalls in the Linux-specific portion of the library).

I'm not bothered myself; it came up in discussion of this issue in the office because they're the only signals (on Linux) which can provoke the bug (i.e. signal numbers over 32), and I noticed when browsing the code that it doesn't support multiple delivery (which is an important aspect of Posix real-time signals).

**Comment by gasche** [comment]
Merged, and cherry-picked in 5.1 ( a5329d31b388b11c66d0d3a6096b404888b61cce ). Thanks!

**Pull request merged**
