### PR TITLE
Typos (documentation)

### PR DESCRIPTION
**Pull request by Fourchaux**
https://caml.inria.fr/pub/docs/manual-ocaml-4.11/index.html

Some snippets are without signature. 
e.g. §3.11 - §3.17 - §6.1 - §6.2

### CODE REVIEW

**Review by dra27 — APPROVED** [review]
LGTM, thanks!

**Comment by dra27** [comment]
FWIW, just waiting on Travis, since that actually builds the manual.

**Comment by gasche** [comment]
> Some snippets are without signature.
> e.g. §3.11 - §3.17 - §6.1 - §6.2

This is a minor issue in the documentation. It's worth fixing, especially if it means that those examples are not checked when they should/could be. (cc @Octachron). Note: combining the report with an unrelated PR makes it a bit harder to keep track of.

**Comment by Octachron** [comment]
@gasche, those examples are explicitly using the `*` version of the environment to suppress the toplevel output, there are not typos.

**Comment by gasche** [comment]
Thanks for the clarification. Nevermind! Laser-eyes @Fourchaux will have to get used to the explicit difference, then.

**Comment by Fourchaux** [comment]
@Octachron 
Of course, we're not talking about typos, BUT
I think several signatures are simply missing (except 2/3 being rather long, indeed)

e.g. §3.11 Polymorphic methods
**class intlist (l : int list) = ...** has its beautiful red signature 
while the **class intlist_rev l = ...** has nothing.

Do I have to open a different PR?

**Comment by Octachron** [comment]
We can certainly discuss if we want to have the full toplevel outputs in a separate PR, but my remark above is that those outputs have been purposefully removed by using the `caml_example*` macro rather than the `caml_example` one.

**Comment by gasche** [comment]
Merged, and cherry-picked in 4.12 ( 9251579df9 ). Thanks!

**Pull request merged**
