### PR TITLE
Tweak configure for supporting arm32 archs with musl

### PR DESCRIPTION
**Pull request by AltGr**
This tweak was necessary to properly compile the native backend on arm32 archs on musl-based distributions. It allowed me to provide the [static binaries for opam](https://github.com/ocaml/opam/releases/tag/2.1.0-rc2) in the same way as the x86 and arm64 ones.

### CODE REVIEW

**Comment by dra27** [comment]
I'm assuming that instead of `armv7*-*-linux-gnueabi` you get `armv7*-*-linux-musleabi` from the regexps? I think it would be worth a comment just explaining that, e.g. at L1043.

**Comment by dra27** [comment]
[precheck#603](https://ci.inria.fr/ocaml/job/precheck/603/), but LGTM (modulo adding a comment)

**Comment by xavierleroy** [comment]
Can we make progress, please?  It looks like we're waiting for @AltGr to add a comment to please @dra27.  I'm fine with the PR with or without the comment.

**Comment by dra27** [comment]
@AltGr is on holiday - it's on my list to nag him next week when he's back!

**Review by dra27 — APPROVED** [review]
LGTM, thanks!

**Comment by dra27** [comment]
Thanks, @AltGr! @Octachron - would this be OK to put in 4.13? (I'll move the Changes entry if so)

**Comment by EduardoRFS** [comment]
@Octachron if we could have this on 4.13 that would allow me to remove one patch from my stuff

https://github.com/EduardoRFS/reason-mobile/blob/master/patches/ocaml/files/arm-additional-eabi.patch

**Comment by Octachron** [comment]
This indeed looks safe for inclusion in the 4.13 beta as a configuration fix.

**Comment by dra27** [comment]
Done - and moved to the 4.13 section of Changes on trunk.

**Pull request merged**
