### PR TITLE
Test UTF-8 paths on AppVeyor

### PR DESCRIPTION
**Pull request by dra27**
See #1444.

This is based on #1447, just so that the diff is unaltered; it's also dependent on #1446 and #1448

### CODE REVIEW

**Comment by shindere** [comment]
Just out of curiosity:

+      cp $f "$OCAMLROOT/bin/flexdll/$f"

Why do you repeat $f?
I'd write it:

+      cp $f "$OCAMLROOT/bin/flexdll"

What do you think?

**Comment by dra27** [comment]
I wouldn't type it in a shell, but I generally prefer to be explicit in a script. That said, I would always (except when I forget!) append a slash in your version, to ensure that the files don't get created as flexdll if for some reason the directory doesn't exist.

**Comment by shindere** [comment]
David Allsopp (2017/10/25 13:42 -0700):
> I wouldn't type it in a shell, but I generally prefer to be explicit
> in a script. That said, I would always (except when I forgot!) append
> a slash in your version, to ensure that the files don't get created as
> flexdll if for some reason the directory doesn't exist.

/ would be fine.

**Comment by dra27** [comment]
@gasche - if the dependencies end up merged, then this could be activated on the 4.06 branch, but it doesn't need consideration as such, I think?

The Readme.win32.adoc stuff has ended up in the wrong GPR - I'll cherry-pick that off to trunk and 4.06 as it should have been part of #1447.

**Comment by gasche** [comment]
Yes, I wouldn't mind merging this in 4.06 given that it only affects the CI (we can easily correct it after the release, and it's fine if it doesn't get in user tarballs as they don't invoke these scripts themselves on a non-development version).

I'm using "consider-for-4.06.0" because it has the same semantics to me or Damien as "4.06.0", and it more clearly suggests to others that things may still be left out if time runs out.

I'm not sure why the CI fails here, and it's not easy to see which changes are not in the PR anymore since #1447 was merged -- maybe a rebase on your end could help.

**Comment by dra27** [comment]
It was failing because #1448 isn't merged. The changes to Readme.win32.adoc hadn't ended up in the wrong GPR - this GPR was (intentionally) based on #1447. I've now rebased it on to #1448 so while it still shouldn't be merged, it's just possible that AppVeyor will pass, unless I messed up the rebase!

**Comment by gasche** [comment]
> unless I messed up the rebase!

I notice the subtle way you complain about having to split PRs, but I am not moved :-)

**Comment by dra27** [comment]
Don't accuse me of subtlety - I prefer sledgehammers! :smile:

Actually, what I referring to was rebasing on top of #1287 which included some nice tidying of the AppVeyor script... so nice, that I do appear to have cocked up the rebase of this one!

**Comment by dra27** [comment]
Let's see how this one fares

**Comment by dra27** [comment]
The prerequisites of this GPR are now met ... assuming it still passes CI!

**Comment by gasche** [comment]
Edit: the message below was already-outdated, keeping it for posterity:

> This should be rebased now that #1448 is merged.

**Comment by gasche** [comment]
Cherry-picked in 4.06 : b97510363894240433731fdbc928f15b8d4ec686.

**Pull request merged**
