### PR TITLE
configure: recognize armv7hl as a hard-float target

### PR DESCRIPTION
**Pull request by olafhering**
Prior OCaml 4.08, a built-in config.guess was used to detect the target
system. This detected arvmv7 with hard floating point properly.
Starting with OCaml 4.08 a standard autconf file was used, which allowed
rpm package builds with the standard '%configure' macro. This macro does
also include global --host=/--build= flags.

Unfortunately, the list in configure.ac uses wildcards for several ARM
32bit targets, and relies entirely on the suffix to guess the floating
point support.

Add an explicit 'armv7hl' entry to detect hard float targets in
openSUSE and Fedora.

Fixes commit cc3f70b705dd624b5f9ba1de92cc7f2afe5b94de
Fixes issue #9431

Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Comment by gasche** [comment]
I did some digging on this issue, see my comment https://github.com/ocaml/ocaml/issues/9431#issuecomment-612203229. I understand now that Suse, and maybe Redhat/Fedora, use `arvm[67]hl-*-gnueabi` in a surprising way to mean that they want `gnueabihf`. I think that the patch is correct for Suse, and a low-effort way to make our configure script work correctly on their ARM distribution.

On the other hand, the change as written will also impact the users of the `armv7hl-redhat-linux-gnueabi` triple, and there I don't understand what is happening (as far as I can tell now, it should also be broken in the same way Suse is, but we got no report in that direction from @rwmjones). I looked at the downstream Fedora patchset and they do *not* appear to be patching this part of the configure. The patch should be correct for them as well, but it would be nice to get confirmation before changing our configure.

**Comment by xavierleroy** [comment]
Thank you @gasche for the nice explanations.  Your analysis is correct, and therefore Suse's use of `arvm[67]hl-*-gnueabi` is wrong, and therefore this PR is not going to be merged in OCaml's sources.  

Suse and others are welcome to apply it as patches of their own, or to invoke OCaml's configure script without options (the default config,guess does the right thing), or to use CPU-VENDOR-SYSTEM triples correctly.  They have plenty of choices.  It's not OCaml's business.

**Comment by gasche** [comment]
I came to the different conclusion that it would be reasonable to merge a version of this patch. The purpose of the configure script is to be a big pile of system-specific hacks designed to configure the distribution correctly on the end-users' system. The particular workaround that is suggested here sounds a bit fishy, but it is not endangering maintainability of our configure script, and it sounds easier to take it in than have this boring conversation again in the future for yet another Red Hat derivative?

(The searching I did around this problem got me more worried than I already was about the health of Linux distributions. The Fedora bugtracker is full of people who spot bugs related to, in this case, arm host triple mismatch, and suggest ugly hacks and workarounds for specific packages instead of looking at the big picture. I've seen discussions of downstream patches to `llvm` and `rpm` to work around this problem, which sounds completely unreasonable, or suggestions to fix a particular package by building it with gcc instead of clang. It's what you get with increasingly complex systems maintained by an aggregate of well-meaning but uninformed volunteers that are trying their best to fix things at their level, with the processes they are used to following. We are lucky at the OCaml level to spend most of our time talking to downstream packagers that are very good and what they do, and nice to work with. But what will the FLOSS distribution of the next generation look like?)

**Comment by xavierleroy** [comment]
I will be firm.  This is a packaging / distribution-level mistake.  You don't change upstream to work around a packaging mistake; you fix the package.

**Comment by gasche** [comment]
Firm is good for decision-making, thanks! Let's close this PR then.

@olafhering I reviewed it to be sensible and I think you should feel free to include it downstream in your OCaml packages. (Please try to convince other Suse people to use `-gnueabihf` for their triples when they want the hard-floating-point ABI.)

**Comment by Conan-Kudo** [comment]
@gasche @xavierleroy The reason that Red Hat, SUSE, Mageia, and other RPM based Linux distributions make this change to the platform triple is because the hard-float property is already being represented in the CPU type.

The `h` in `armv7hl` represents a CPU with hardware-based floating point support. Consequently, it was considered redundant and pointless to add the `-hf` suffix for the ABI at the end. Notably, the ABI itself does not change between hfp and sfp variants, but the instructions used for targeting the CPU do, and that's what causes the incompatibility. 

Indeed, it especially doesn't matter because you can override the "default" via a compiler flag for any ARM targeted build.

I do not know why `hf` is represented in the ABI section of the platform triple for ARM, but it's definitely wrong and inconsistent with how other architectures have handled CPU instruction variation (x86, POWER, MIPS, RISC-V, etc.)

In any case, this is a downstream fix in RPM distributions that generally has little to no impact for most software, as they configure and build properly based on the compiler flags passed in.

Within Fedora and other distributions, we will carry this downstream, but I figure it would make sense to give the rationale for this adjustment for upstream OCaml's reference and understanding.

**Comment by gasche** [comment]
> Notably, the ABI itself does not change between hfp and sfp variants

Are you sure? I know nothing about ARM specifically but I would assume that the calling-convention differs for floating-point arguments.

Again, I think the nicest approach would be to be very redundant and use `armv7hl-...-gnueabihf`, so that both the hardware support and the ABI choice are indicated. `armv7hl-...-gnueabi` would make perfect sense as a different thing (hardware support for hard-float operations but no specific calling convention, so that code is compatible with soft-float-compiled code). (Of course `arvm7l-..-gnueabihf` would not work and be invalid.)

**Comment by gasche** [comment]
Note: for example [this wiki page from Debian](https://wiki.debian.org/ArmHardFloatPort) says the following, which supports my impression (that it is *also*, and importantly, an ABI setting):

> The Arm EABI specification covers calling conventions across libraries and binaries. It defines two incompatible ABIs: one uses (VFP) floating point registers for passing function arguments, the other does not.
>
> Unlike many other architectures, Arm supports use of FPU instructions while still conforming to the base ABI. This allows code to take advantage of the FPU without breaking compatibility with older libraries or applications. This does incur some overhead relative to a full hard-float system, and obviously requires a VFP capable CPU.

**Comment by xavierleroy** [comment]
I'm getting tired of this argument.

In the ARM world it is perfectly normal to have a CPU with a hardware FP unit, yet use integer registers for passing FP arguments and results to functions.  This is actually the standard behavior mandated by the ARM Architecture Procedure Call Standard (AAPCS), chapter 5, "The base procedure call standard".

If the CPU supports VFP FP instructions and registers, a variant of the base standard, described in AAPCS section 6.1, can be used, where FP arguments and results are passed in VFP registers.

Which calling convention to use is not a function of whether the processor supports FP instructions.  Hard FP + standard calling conventions was a popular choice in the ARM embedded world until recently.

In a GNU triple CPU-VENDOR-SYSTEM, whether the processor supports FP instructions is encoded in the CPU field, but which calling convention to use is part of the SYSTEM field (`eabi` or `eabihf`).

The triple `armv7hl-suse-linux-gnueabi` means "use the base procedure call standard for an ARMv7 CPU that supports hardware FP".  If some Linux distributions give it a different meaning, they are in error.

**Comment by Conan-Kudo** [comment]
@jakubjelinek, what do you think about this?

**Comment by olafhering** [comment]
Both commits of mine which touch `configure.ac` are wrong.
They should have not been pushed to github,
See issue #9431 why both commits are WRONG, not just for OCaml and/or ARM32.

**Pull request closed without merging**
