### PR TITLE
Remove un-used and unsafe caml_drop_continuation

### PR DESCRIPTION
**Pull request by tmcgilchrist**
This change removes an un-used and unsafe function `caml_drop_continuation` that was marked as an OCaml primitive.

Originally it was introduced during OCaml Multicore #10831 to expose an Obj.drop_continuation function, commit
https://github.com/ocaml/ocaml/commit/d44ed5fdb3166b2fb1bcc799fb130cdeeab222f4 This function is no longer available on Obj. The function is unsafe as it frees continuation memory without unwinding the stack, which isn’t a safe operation in general as it will not release the resources that it holds. The correct behaviour for dropping a continuation is documented in https://v2.ocaml.org/manual/effects.html#s:effects-linearity.

### CODE REVIEW

**Comment by gasche** [comment]
At some point @dhil had an external, unsafe library for multishot continuations, that we supported by just keeping some primitives around. Is it one of these?

**Comment by dhil** [comment]
Thanks for the poke, @gasche! I am not using the `caml_drop_continuation` primitive as I rolled my own.

**Review by gasche — APPROVED** [review]
Thanks!

**Comment by gasche** [comment]
@tmcgilchrist could you add a Changes entry?

**Review by ghost — APPROVED** [review]

**Comment by tmcgilchrist** [comment]
Added section in Bug Fixes @gasche it seemed like the right place?
I also checked the released Opam packages using https://sherlocode.com to search for any references to this function and didn't find anything.

**Pull request merged**
