### PR TITLE
Preserve backtraces in match ... with exception e -> ...

### PR DESCRIPTION
**Pull request by ghost**
When translating into Lambda we treat the case of exception
handlers in match forms in the same way as exception handler in
try .. with in order to preserve backtraces.

A small test is included as well.

### CODE REVIEW

**Comment by gasche** [comment]
I reviewed the patch and believe that it is correct. We are replacing a case of `transl_cases` by `transl_cases_try`, and both are auxiliary functions with two levels of wrapping around a call to `transl_guard`, the difference being that one of them temporarily adds an identifier to the table `try_ids` of exception identifier that should be reraised instead of raised. (This change is made only on the exception cases of a `match with exception` construct.)

@doligez could we consider this for 4.03? Users care about backtrace quality and I'm worried that this could be a real inconvenience to people debugging their code. (They would naturally assume that the re-raise behavior is the same as with `try`)

**Comment by damiendoligez** [comment]
@gasche OK for 4.03 if you merge it within 2 days.

**Comment by gasche** [comment]
I merged this into 4.03 ( 67e44a4595b2aa1ebc8ed75e5e5983a1ea084524 ) and trunk ( 1dfac1f12b45c8be9c985d79f4e16dfdabdba185 ). I added a Changes entry ( @nojebar : stop forgetting about those! ) and added some explicit comments in the test, because I was initially unsure whether `exception (Foo "c") -> raise (Foo "c")` was expected to be a re-raised or not.

**Comment by ghost** [comment]
Thanks! Will remember to update Changes next time.

**Pull request closed without merging**
