### PR TITLE
nit: improve List.rev_append doc wording

### PR DESCRIPTION
**Pull request by kunigami**
I'm not really sure how to build the docs page locally. Do we have a guide for that?

https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#user-documentation

### CODE REVIEW

**Comment by gasche** [comment]
> I'm not really sure how to build the docs page locally. Do we have a guide for that?

Yes, see [HACKING.adoc#libraries](https://github.com/ocaml/ocaml/blob/08b3ae/HACKING.adoc#libraries). Thanks for the question and pointer on where you went looking, though, it is very helpful to know how to improve the documents.

(I think I should move the information about how to build the doc to `manual/HACKING.adoc`, and refer to that from both the root HACKING.adoc and this part of the CONTRIBUTING.md. Generally the CONTRIBUTING was written before HACKING and could benefit from reference to HACKING in relevant places.)

**Comment by Octachron** [comment]
Concerning the wording, I am wondering if replacing `concatenates` with `append` will not be clearer. With `concatenate a to b` I am not completely sure if this corresponds to `a @ b` or ` b @ a` and I have the suspicion that the inferred order might be highly variable accoss international readers.

**Comment by mshinwell** [comment]
Perhaps it would be better to simply remove the first sentence and just rely on the code fragment.  Which, incidentally, might be clarified (especially for those reading the documentation comment rather than the generated docs) by parenthesising the "`List.rev l1`" portion.

**Comment by damiendoligez** [comment]
I think `concatenate a and b` is a lot less ambiguous than `concatenate a to b`.
In this case, I would write `reverses [l1] and concatenates it with [l2]`.

I agree with @mshinwell : adding parentheses would make the code fragment easier to read, especially when reading the source rather than the rendered version.

**Comment by mshinwell** [comment]
@kunigami Can you please finish this pull request and get it up-to-date with trunk?

**Review by mshinwell — APPROVED** [review]
@trefis checked this too.

**Comment by mshinwell** [comment]
I took the liberty of updating this pull request since it still hadn't been finished, and will merge.

**Pull request merged**
