### PR TITLE
Remove three obsolete tools

### PR DESCRIPTION
**Pull request by shindere**
This PR removes the three following obsolete tools:
ocaml299to3, addlables and scrapelabels.

These tools were no longer compiled / installed.

### CODE REVIEW

**Comment by garrigue** [comment]
I agree that ocaml299to3 is now obsolete, but addlabels and scrape labels are actually useful tools, even though they're not up to date.
They would indeed be better in a separate repository.

**Comment by shindere** [comment]
Many thanks, Jacques. I can update this PR to only remove ocaml2999to3
if that's appropriate.

Do you have any idea about when scrapelabels and addlables are actually
used? Because for what I can see they are not even compiled by the main
rules.

**Comment by xavierleroy** [comment]
I did some archeology.  
* scapelabels and addlabels build fine in OCaml 4.00. 
* In 4.01, scrapelabels builds but addlabels fails (type error on `Pexp_open`)
* Since 4.02, both fail to build because they assume unsafe strings.

So, these tools have been broken since 2014 and nobody noticed.  I think this answers the question about actual uses...

**Comment by garrigue** [comment]
Yes, I was not suggesting to keep them in the distribution.
I will probably fix them and put them somewhere on GitHub, to be able to point to them when some related question arises (such as "how can I produce fully labeled code").

**Comment by shindere** [comment]
Xavier Leroy (2019/05/07 00:35 -0700):
> I did some archeology.  
> * scapelabels and addlabels build fine in OCaml 4.00. 
> * In 4.01, scrapelabels builds but addlabels fails (type error on `Pexp_open`)
> * Since 4.02, both fail to build because they assume unsafe strings.
> 
> So, these tools have been broken since 2014 and nobody noticed.  I
> think this answers the question about actual uses...

Many thanks for having investigated, Xavier. I should have done it, I
guess.

**Comment by shindere** [comment]
Jacques Garrigue (2019/05/07 00:47 -0700):
> Yes, I was not suggesting to keep them in the distribution.
> I will probably fix them and put them somewhere on GitHub, to be able
> to point to them when some related question arises (such as "how can I
> produce fully labeled code").

Jacques, are you asking that we wait until you have created that
repository, or could we proceed right now and you would take care of
creating the repository you would like?

**Comment by garrigue** [comment]
Removing it from trunk doesn't mean it disappears suddenly, so you can go ahead.
Anyway, at this point this is dead code.

**Comment by avsm** [comment]
@garrigue if you do clean them up for a separate repository, we can do a repo-transfer to the ocaml/ org and mark them in the README for that repo as historical tools (e.g. if you need them for a permanent reference in a paper or similar)

**Comment by shindere** [comment]
Jacques Garrigue (2019/05/07 01:28 -0700):
> Removing it from trunk doesn't mean it disappears suddenly, so you can
> go ahead.

OK thanks. Would you mind giving a formal approval, please?

> Anyway, at this point this is dead code.

Indeed.

**Review by gasche — APPROVED** [review]

**Comment by shindere** [comment]
Gabriel Scherer (2019/05/12 09:28 -0700):
> Merged #8663 into trunk.

And thanks a lot for that, too.

**Pull request merged**
