### PR TITLE
ocamltest: don't ignore EOL-at-EOF differences (alternative to #8983)

### PR DESCRIPTION
**Pull request by damiendoligez**
This is an implementation of the simple alternative to #8983 that I described in https://github.com/ocaml/ocaml/pull/8983#pullrequestreview-353088235

### CODE REVIEW

**Comment by damiendoligez** [comment]
cc @dra27 @shindere @dbuenzli

**Comment by shindere** [comment]
Thanks. that looks okay to me.

**Comment by dra27** [comment]
Sorry for my slowness - in investigating this last Monday, I disappeared down an ocamltest rabbit-hole for most of the week, emerging for air on Friday! I had to go through a little whiteboarding of the 16 EOF cases for this function to be sure I agreed that the two functions' approaches were really equivalent, but I agree that they are.

However, in doing so, I considered the other 16 cases - that is each of the EOF cases split for a single line file and a multiple-line file. I then considered normalisation on those. From that, it is possible to derive 4 _positive_ normalisation tests (that is, tests where you need the algorithm to be functioning _correctly_ for them to pass - there is a dual collection of tests which should always fail, but we don't have a FAIL case in ocamltest yet). I've pushed those here and to #8983. Note that this isn't a flaw in what you change here, it's a flaw in using the original normalisation code and just adding the EOF check on top of it.

The two cases where this PR still fails are:

1. A reference file with more than one line which actually ends with a CR. The CR gets incorrectly erased by the existing code, but is correctly left in #8983 because it is not followed by an LF. This case is parasitic.
2. Any file with more than one line and no EOL-at-EOF never normalises. This case is not parasitic, it's simply not happened yet. It's easy for it to happen, though, when reference files are automatically promoted. It can be triggered, for example, by altering the `redefine_largefile` test to be `print_endline "hello, world"; print_string "hello_world"` which then always fails with a native Windows build of OCaml.  

I couldn't see an easy fix in this PR for that second case, but I stared at the various comments and accusations of over-engineering and wondered if in fact what's gone wrong here is over-abstraction. To that end (and I really do hope it'll be an end!), I propose #9801 - the idea behind is to write a function which compares two text files, as opposed to the battle we've been having writing a function which produces a possibly normalised set of lines of a text file.

**Comment by dra27** [comment]
Thanks for the review in #9801, @damiendoligez! That's now merged, so closing this one as - hopefully - all normalisation and EOL-at-EOF questions in ocamltest are dealt with 🙂

**Pull request closed without merging**
