### PR TITLE
ocamltest: one line per passing test

### PR DESCRIPTION
**Pull request by nojb**
A small quality-of-life improvement: for passing (or skipped) tests, print only one line per test file, instead of one-line per "step" of the test script. In case of failure, we still print the result for every step.

Compare:

- trunk: https://github.com/ocaml/ocaml/actions/runs/7518244661/job/20465448229?pr=12888#step:5:209

- PR: https://github.com/nojb/ocaml/actions/runs/7518491599/job/20466004286?pr=12#step:5:103

### CODE REVIEW

**Comment by nojb** [comment]
(`summarize.awk` still needs to be adapted.)

**Comment by gasche** [comment]
I believe that @shindere would want to have a look at this.

**Comment by shindere** [comment]
Gabriel Scherer (2024/01/14 06:33 -0800):
> I believe that @shindere would want to have a look at this.

Indeed! Many thnaks for having given me the time to do so!

**Comment by shindere** [comment]
I did look and the code seems very okay to me, many thanks!

I also expect this to please @xavierleroy quite a bit.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2024/01/14 06:26 -0800):
> (`summarize.awk` still needs to be adapted.)

Do you intend to work on that, too, @nojb?

**Comment by gasche** [comment]
Did you mean to approve the PR, so that we can/should merge it in its current state?

**Comment by nojb** [comment]
> Nicolás Ojeda Bär (2024/01/14 06:26 -0800):
> (`summarize.awk` still needs to be adapted.)
> Do you intend to work on that, too, @nojb?

Yes, I will do that as soon as I get a bit of spare time.

> Did you mean to approve the PR, so that we can/should merge it in its cIurrent state?

`summarize.awk` needs to be adapted to handle the different format for the timestamp (which is now printed in the same line as the test), so I wouldn't merge the PR just yet :)

**Comment by shindere** [comment]
Gabriel Scherer (2024/01/18 05:46 -0800):
> Did you mean to approve the PR, so that we can/should merge it in its
> current state?

I canapprove it, yes, but does it work without the `summary.awk` change?

(I didn't approve yet under the assumption that it wouldn't work as long
as summary.awk has not been updated but feel free to correctme if I am
wrong and I will approve!)

>

**Comment by nojb** [comment]
I pushed the adapted `summarize.awk`. We now count only top-level tests which pass, fail, skip, etc, instead of individual steps (which I think it is a better semantics). The status lines for individual steps are simply skipped over by `summarize.awk`.

@shindere formal review would be appreciated, thanks!

**Comment by xavierleroy** [comment]
> I also expect this to please [@xavierleroy](https://github.com/xavierleroy) quite a bit.

Indeed, this looks great!

**Comment by xavierleroy** [comment]
Sorry for the closing, I pushed the wrong button...

**Comment by nojb** [comment]
> Sorry for the closing, I pushed the wrong button...

No worries :)

**Comment by nojb** [comment]
Friendly ping @shindere: formal review would be appreciated, thanks!

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2024/01/26 21:47 -0800):
> Friendly ping @shindere: formal review would be appreciated, thanks!

I diidn't realise that you added the `summarize.awk` adaptation bit,
because I do not get notified when pushes happen on PR branches and no
comment had been posted here to report that the feature was available
for review, I think?

In any case, I'll make sure to review promptly, likely tomorrow.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2024/01/20 02:21 -0800):
> I pushed the adapted `summarize.awk`. We now count only top-level tests which pass, fail, skip, etc, instead of individual steps (which I think it is a better semantics). The status lines for individual steps are simply skipped over by `summarize.awk`.
>
> @shindere formal review would be appreciated, thanks!

Oops, it seems I have missed that comment. Apologies about that. I did
review and approve formally, may thanks for the very nice work.

For this PR I think it's important to squash the commits before merging
to avoid any not-working intermediate state.

**Comment by nojb** [comment]
Thanks @shindere!

**Pull request merged**
