### PR TITLE
Add Array.map_{of,to}_list

### PR DESCRIPTION
**Pull request by nojb**

### CODE REVIEW

**Comment by dbuenzli** [comment]
An infinity of these functions can be added; what about `Array.filter_map_{of,to}_list` for example ? I think we should refrain from doing this. At least for `Array.map_to_list`, `Array.fold_{left,right}` is what you are looking for here.

**Comment by nojb** [comment]
Yes, but not all possible functions are equally useful. In my personal experience these functions (and those of #2236) are particularly useful. I am happy to close this PR if there is majority against adding them. Let us wait for some more developers to chime in before taking a decision.

**Comment by Drup** [comment]
All these functions are better written using something like the [iter/sequence package](https://github.com/c-cube/iter): `Iter.(x |> of_array |> map f |> filter p |> to_list)`. Or, if perf is not so important, just use `Seq`.

**Comment by nojb** [comment]
> All these functions are better written using something like the [iter/sequence package](https://github.com/c-cube/iter): `Iter.(x |> of_array |> map f |> filter p |> to_list)`. Or, if perf is not so important, just use `Seq`.

Not sure how that is "better", but in any case, I agree there are many ways to write these functions. The same can be said of many other functions in the `stdlib`.

The only question here is whether these *particular* functions are useful enough and common enough that they deserve a name all to themselves. I think so, which is why I proposed them.

**Comment by Drup** [comment]
It's better because it composes properly and is still exactly the same performance profile. Instead of having some hardcoded functions that goes from list to array while applying a map, you make your own family of functions that goes from X to Y while applying some transformation, for arbitrary X and Y. And those are still one-liners.

**Comment by nojb** [comment]
> It's better because it composes properly and is still exactly the same performance profile. Instead of having some hardcoded functions that goes from list to array while applying a map, you make your own family of functions that goes from X to Y while applying some transformation, for arbitrary X and Y.

I agree that from a composability point-of-view there are better, more orthogonal ways to express the same transformations. But in practice a small subset of all possible transformations come up much more often that the rest and it is useful to have a specific name for them. In my opinion, the functions here fall in that subset.

For the record, we recently merged `List.flatten_map` (see #2185) which seems to be in the same category as the functions in this PR.

**Comment by nojb** [comment]
Not enough support, so closing.

**Pull request closed without merging**
