### PR TITLE
Changes in simplif.ml - removal of try_depth ref

### PR DESCRIPTION
**Pull request by Anukriti12**
This Pull Request is created with reference to changes in lambda/simplif.ml which aims at removing try_depth ref (global mutable state).

### CODE REVIEW

**Review by dra27 — COMMENTED** [review]
Sorry that this has sat for so long without comment. It's not technically removing global state, as `try_depth` is a local variable to `Simplif.simplify_exits`, but removing the use of refs in recursive functions is generally an improvement.

I would suggest structuring it differently, though - most of the branches in both `count` and `simplif` are merely threading the value of `try_depth`, they don't actually need it. It is certainly neater (in terms of a smaller diff) and potentially faster (in terms of fewer arguments being pushed around in function calls) to structure it:

```ocaml
let rec count_main ~try_depth lam =
  let rec count = function
  | (Lvar _ | Lconst __ -> ()
  (* ... *)
  | Ltrywith(l1, _v, l2) -> count_main ~try_depth:(try_depth + 1); count l2
  (* ... *)
  and count_default sw = (* ... *)
  in
  count lam
in
count_main ~try_depth:0 lam;
```
and a similar trick can be done with `simplif`

**Comment by lthls** [comment]
> It is certainly neater (in terms of a smaller diff) and potentially faster (in terms of fewer arguments being pushed around in function calls)

I'm not convinced by the performance argument. Your version removes one argument to the function, but adds one closure allocation for each call to `count_main`, and changes accesses to `try_depth` from stack reads to heap reads (through the closure). So without benchmarks I wouldn't know which one is faster (and I don't think it would make a big enough difference to deserve such an effort).

With your approach we would also need to either re-indent the function (negating in part the smaller diff gains) or live with weird indentation.

But overall I'm fine either way. I can take care of fixing conflicts and rebasing, as I'm not sure if @Anukriti12 is still interested in working on this.

**Comment by lpw25** [comment]
I don't agree with the neater part or the faster part.

It's easier for people to mess up when you are recursing via two different entry points, much clearer to just pass the arguments around the loop.

Passing parameters around a function is generally cheaper than allocating a closure and accessing the values via it.

**Comment by dra27** [comment]
OK, fair enough - in which case it's just a matter of rebasing, as @lthls says.

**Comment by dra27** [comment]
> With your approach we would also need to either re-indent the function (negating in part the smaller diff gains) or live with weird indentation.

FWIW I had meant to add "modulo whitespace" (which is eliminated by patdiff)!

**Comment by lthls** [comment]
I've rebased, fixed a few long lines and tweaked indentation, and added a Changes entry. @Anukriti12 I've credited you by your Github handle, if you prefer a full name tell me either here or in private and I'll update the Changes entry.

**Comment by gasche** [comment]
Anukriti already appears in the Changes as "Anukriti Kumar", we should probably reuse that.

**Comment by lthls** [comment]
I forgot to check that, thanks for pointing it out

**Comment by lthls** [comment]
There's no formal approval, but it seems that enough people have looked at it and nobody complained, so I'll merge this PR before the end of the week (I've been involved in the creation of this PR so I thought somebody else should approve).

**Review by gasche — APPROVED** [review]
Approved on David's behalf. (I didn't do a full review, but I did look at the original code to check (this is non-trivial) that two functions using the shared reference do not interact with each other.)

**Pull request merged**
