### PR TITLE
Add configure option to disable gprof support

### PR DESCRIPTION
**Pull request by mshinwell**
This is the first in a couple of patches to help reduce the size of compiler installation trees.  It provides a new `configure` option to disable `gprof` support (for example in environments when `perf` is used instead).

### CODE REVIEW

**Comment by gasche** [comment]
Is there an explicit `-profiling` option to set the value to `true`?

**Comment by damiendoligez** [comment]
@gasche is right: you should add both `-gprof` and `-no-gprof` to control gprof support, and make `-gprof` the default.

**Comment by mshinwell** [comment]
What is the policy concerning options such as these which are subject to a check inside the configure script itself?  If you specify `-gprof` but gprof profiling is not supported on your platform, should the configure script cause an error, or just silently disable profiling?

**Comment by shindere** [comment]
Mark Shinwell (2018/05/30 06:55 -0700):
> What is the policy concerning options such as these which are subject
> to a check inside the configure script itself?  If you specify
> `-gprof` but gprof profiling is not supported on your platform, should
> the configure script cause an error, or just silently disable
> profiling?

I had a look to autoconf's documentation but couldn't find an answer to
this. IMO that would be worth a warning, at least. I would'nt mind an
error if something that has been explicitly requested is actually not
supported.

**Comment by gasche** [comment]
> If you specify -gprof  but gprof profiling is not supported on your platform, should the  configure script cause an error, or just silently disable profiling?

What we did for the `with_instrumented_runtime` setting is to implicitly disable it if no explicit setting was given, but fail with an error if it was explicitly requested. (The implementation could be an inspiration.)

**Comment by trefis** [comment]
Ping @mshinwell .

**Comment by mshinwell** [comment]
This is going to be superceded.

**Pull request closed without merging**
