### PR TITLE
Enough with multiple "common" definitions of C global variables

### PR DESCRIPTION
**Pull request by xavierleroy**
In C, multiple definitions of a global variable (without `extern` nor `static` modifiers) in different compilation units is often tolerated (the "common" model, by reference to the FORTRAN "COMMON" keyword), but not always, see #9144 and #9176 for examples).  

The first commit in this PR fixes two such multiple definitions in the runtime system (closing #9144).

These multiple definitions are programming errors: there should be one definition and N-1 `extern` imports.  But we don't notice them because most C compilers accept them silently.

The second commit in this PR adds the `-fno-common` flag to clang and gcc >= 5 so that future such multiple definitions show up as errors.

This should be merged in 4.10 as well as in trunk.

### CODE REVIEW

**Comment by mshinwell** [comment]
This seems correct to me.  Two points:
- It sounds like from your description that the gcc flag was predicated on a particular gcc version, but it doesn't seem to be.  This is fine, I think, as the flag exists now.
- The big change about git in configure seems odd, but I guess that's just autoconf...

**Review by mshinwell — APPROVED** [review]

**Comment by gasche** [comment]
The git-configure changes look like they come from #8995. It looks like someone erroneously *reverted* this change to the configure after that PR was merged.

**Comment by gasche** [comment]
The configure revert comes from #9123 and I guess it was missed during review? Adding it back is the right behavior (but it could have been done as a direct trunk push rather than included in an unrelated PR). This is good to merge when the CI comes back green.

**Comment by xavierleroy** [comment]
> It sounds like from your description that the gcc flag was predicated on a particular gcc version, but it doesn't seem to be. 

My comment was cryptic, sorry about that.  The autoconfiguration script discriminates on GCC versions: < 4, 4.0 to 4.2, 4.2 to 5.0, and >= 5.0.  To minimize the changes to the script, I added `-fno-common` only in the >= 5.0 case, on the grounds that nobody uses gcc < 5 any longer.

As to the configure script itself, I regenerated it using @dra27 's `./autogen` script.  I believe this is the correct thing to do when `configure.ac` changes.

**Comment by xavierleroy** [comment]
Merged in trunk and cherry-picked to 4.10.

**Comment by hannesm** [comment]
I stumbled across this, thanks for your work on it. I'm curious whether OCaml should pass the linker flag as well, `--warn-common` seems to be a widely support (GNU binutils and clang) option? Or is it sufficient to pass it to the C compiler?

**Comment by xavierleroy** [comment]
I think the two flags play slightly different roles.  

With `--warn-common` at link-time, you get warnings or perhaps even errors for all multiply-defined "common" variables, whether they come from the OCaml runtime or from system libraries.  I would be surprised, but there might be standard C libraries around that use old-style "common" definitions.  

With `-fno-common` at compile-time, you get link-time errors for all multiply-defined "common" variables in the OCaml runtime system.  System libraries are not checked.  This feels more robust to me.

**Comment by gasche** [comment]
#9128 depends on this PR (without it, it only changes one of the two duplicated definitions of `caml_atom_table`, so the build fails); in order to cherry-pick #9128 to 4.09, I cherry-picked the present PR into 4.09 as well.

(One could have chosen to cherry-pick the deduplication but not the `-fno-common` check, but I followed what Xavier had done for 4.10.)

**Pull request merged**
