### PR TITLE
autoconf tweaks

### PR DESCRIPTION
**Pull request by dra27**
The principal motivation for this change is to allow `make configure` instead of `./autogen`.

### CODE REVIEW

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
This looks all very nice to me, many thanks and sorry for the delay for
reviewing. Beware that CI does not seem happy, but once this is either
fixed or understood, as far as I am ocncerned, feel free to merge.

**Comment by shindere** [comment]
I am not merging yet because I don't know why Travis is failing, can anybody check this, please?

**Comment by gasche** [comment]
Travis is failing because (1) a `Changes` entry is missing and (2) `check-typo` is failing.

The `check-typo` failure is non-standard (it is not due to a typo), I believe that it comes from the following piece of code in `tools/ci/travis/travis-ci.sh` that probably needs updating:

```sh
 if [ -e CHECK_CONFIGURE ] ; then
    rm -f CHECK_CONFIGURE
    echo "configure or configure.ac altered in $1"
    echo "Verifying that configure.ac generates configure"
    git checkout "$1"
    mv configure configure.ref
    ./autogen
    if ! diff -q configure configure.ref >/dev/null ; then
      echo "configure.ac no longer generates configure, \
please run ./autogen and commit"
      exit 1
    fi
  fi
```

The relevant portion of the log is as follows:

```
configure or configure.ac altered in a453d65a7a3dcecdc594a1763b63f649c2d8e580
Verifying that configure.ac generates configure
HEAD is now at a453d65 Merge 53a93199f5b1ffa37b5a90bd748dfee0226d9c81 into f2c71fe44dd5ce6117234e954faf4d44b4e5c362
tools/autogen
configure.ac no longer generates configure, please run rm configure ; make configure and commit
The command "bash -e tools/ci/travis/travis-ci.sh" exited with 1.
```

**Comment by gasche** [comment]
(Apparently some of the `travis-ci.sh` code above was modified by the PR itself, so @dra27 should know about this.)

**Comment by shindere** [comment]
Thanks a lot, @gasche!

Will let you handle this if you don't mind, @dra27

**Pull request merged**
