### PR TITLE
Make sure Bigarray shadows Stdlib.Bigarray

### PR DESCRIPTION
**Pull request by ghost**
In trunk and 4.08, `Stdlib.Bigarray` shadows `Bigarray` (from the `bigarray` library). The reason is that the initial environment is constructed as follow:

```
env <- empty

env <- add_dir(env, stdlib_dir)
env <- open(env, Stdlib)

env <- add_dir(env, d1)
...
env <- add_dir(env, dn)

env <- open(env, M1)
...
env <- open(env, Mm)
```

Where `dX` are the include directories specified by the user via the `-I` option and `MX` are the implicitly opened modules specified via `-open`. This seems correct, however there is one catch: the `bigarray` library is installed in the same directory as the stdlib, which means that the `open(env, Stdlib)` shadows the toplevel `Bigarray` module :/

To workaround this issue, this patch reintroduces the names coming `stdlib_dir` after opening the `Stdlib` module, i.e. the initial environment is now constructed as follow:

```
env <- empty

env <- add_dir(env, stdlib_dir)
env <- open(env, Stdlib)
env <- add_dir(env, stdlib_dir)

env <- add_dir(env, d1)
...
env <- add_dir(env, dn)

env <- open(env, M1)
...
env <- open(env, Mm)
```

I tried but I didn't managed to write a test for this; in any test I wrote, `Stdlib.Bigarray` was still shadowing `Bigarray` even after this patch. I'm assuming that this is because the testsuite must use some special flags such as `-nopervasives` or `-nostdlib` in order to use a local stdlib. However, I did the following manual testing:

```
$ git clean -dfx
$ ./configure --prefix ~/code/ocamls/trunk
$ make world.opt -j20
$ make install
$ ocaml
# Bigarray.Array1.map_file
```

with trunk, I get a `unbound value map_file` error, while with this patch I properly get a deprecation message.

## Limitation

If one uses compilation flags such as `-nopervasives -open Stdlib` for special purposes, then `Stdlib.Bigarray` will still shadow `Bigarray`. I don't have a good solution for this, except installing the various libraries in their own sub-directory as done in #1569, which would avoid this issue altogether.

### CODE REVIEW

**Comment by damiendoligez** [comment]
The limitation is serious, as it means that we cannot try an uninstalled compiler without getting some weird behaviors. And as you noticed it somewhat messes up our test suite. This means it's probably time to try reopening #1569 or something similar.

**Comment by ghost** [comment]
Personally, I would like #1569 to be reopened as it makes reasoning about all this a lot simpler and it is also beneficial for users. I can think of alternative ways, but that would be more complexity that might make things more difficult in the future.

**Comment by ghost** [comment]
I'm closing this since this is not a good fix. I sent an email on caml-devel to discuss how to proceed.

**Comment by aantron** [comment]
@diml Would you mind pinging this issue again with the number of the follow-on issue or PR, once it is open/reopened, so that subscribers can monitor it?

**Comment by ghost** [comment]
Sure, no problem

**Comment by ghost** [comment]
@aantron, we discussed this on caml-devel. The only additional feature provided by the `Bigarray` module from the `bigarray` library is `ArrayX.map_file`. Given that these functions have been deprecated since 4.06.0, it doesn't too bad that the `bigarray` library is no longer accessible. The official answer is to simply switch to `Unix.map_file`. You might also want to stop relying on the existence of the `bigarray` library, since this library will disappear in the future.

FTR, we have been slowly moving `Bigarray` into the standard library. It has been a long process, but it should hopefully be completely over in a version or two of the compiler. Starting with 4.08, you should consider that the `bigarray` library is deprecated.

**Comment by aantron** [comment]
Thanks, @diml. I'll adapt Lwt with some conditional compilation (since we need to support old versions of OCaml).

**Comment by damiendoligez** [comment]
@aantron you should have a look at the discussion on #2263, maybe you won't need conditional compilation.

**Comment by aantron** [comment]
Thanks @damiendoligez!

**Pull request closed without merging**
