### PR TITLE
Fix name of install document and remove 'maccaml' from README.adoc

### PR DESCRIPTION
**Pull request by johnwhitington**
The following files are not described in "CONTENTS". I am happy to provide another pull request which adds them, if we actually want all them there:

CONTRIBUTING.md
Makefile.nt
Makefile.shared
VERSION
appveyor.yml
appveyor_build.sh
compilerlibs
configure
experimental
flexdll
man
manual
middle_end
testsuite

### CODE REVIEW

**Comment by gasche** [comment]
The current patch seems good. If we are going to revamp the README, here are some ideas for a change:
- all-caps titles are rather ugly, maybe we could have them lowercase (with just the first letter capitalized, or each word's first letter, depending on the patcher's preference for english titles)
- maybe we don't need to list all files in the in the README itself (eg. shown on the front github page of the project), it could be in a separate HACKING document.
- the "BUG REPORTS AND USER FEEDBACK" section only mention bugs, we could have some information about documentation and code contribution that would link to the CONTRIBUTING document.

**Comment by damiendoligez** [comment]
I've set the milestone to 4.04, but if someone wants to cherry-pick this change to 4.03, go ahead.

**Comment by johnwhitington** [comment]
I agree with the first and last points raised by @gasche, and will address them in a separate pull request next week, which can wait until 4.04.

The second point needs some thought and discussion I think.

It would be good to get the present PR into 4.03, since it corrects a couple of actual mistakes, and it uncontroversial.

**Comment by gasche** [comment]
Merged in trunk ( db9b05989f9ec586791fc606a8f4e4d00f6a34a1 ) and 4.03 ( fe54dc07d33cc1a4d1a01e5b7092c6fdb1cd5018 ), thanks.

**Comment by gasche** [comment]
I would like to have a `HACKING.adoc` document in which to keep track of Makefile rules that are useful when building the compiler (eg. `make runtop`, `make reconfigure` and `make -C testsuite parallel`) , and point to my `opam-compiler-conf` script.

(I'm posting this here as a reminder for myself mostly.)

**Comment by johnwhitington** [comment]
This could be started by moving the "Hard Bootstrap How-to" out of the Makefile into this new document.

**Comment by gasche** [comment]
I started working on a HACKING.adoc document in a branch `HACKING.adoc` of [my personal clone](https://github.com/gasche/ocaml/tree/HACKING.adoc) (see [HACKING.adoc](https://github.com/gasche/ocaml/blob/HACKING.adoc/HACKING.adoc) file). Will send a pull-request when it feels slightly better.

**Comment by Drup** [comment]
@gasche I also have a start [here](https://github.com/Drup/ocaml/blob/hackind_md/Hacking.adoc), it looks like we should be able to merge. :)

**Comment by gasche** [comment]
@Drup yours seems more advanced. Could you maybe integrate my stuff and submit a pull request?

**Pull request closed without merging**
