### PR TITLE
typecore: call repr before checking level to know if a disambiguation is principal

### PR DESCRIPTION
**Pull request by trefis**
This is exactly the same as https://github.com/ocaml/ocaml/pull/1661, but I believe I got all the instances this time.

### CODE REVIEW

**Comment by gasche** [comment]
Line [2251](https://github.com/ocaml/ocaml/blob/530cada3aa197831c5a4d539121c59ea171deea2/typing/typecore.ml#L2251) the format-checking codepath has a `ty_exp.level <> generic_level` comparison where `ty_exp` comes from `expand_head` without a `repr`. Is it safe? Other parts of the code (line [1932](https://github.com/ocaml/ocaml/blob/530cada3aa197831c5a4d539121c59ea171deea2/typing/typecore.ml#L1932) for example) use `repr` on the result of `expand_head`. And what about line [3180](https://github.com/ocaml/ocaml/blob/530cada3aa197831c5a4d539121c59ea171deea2/typing/typecore.ml#L3180)?

Maybe we could have a `is_generic : type_expr -> bool` function that would safely use `repr` as required, all the time?

**Comment by trefis** [comment]
I believe the `repr` is not needed after calling `expand_head`, as it itself always ends by calling `repr`.

Although a `is_generic` function does sound good to me.

**Review by gasche — APPROVED** [review]

**Comment by trefis** [comment]
@gasche do you want `is_generic` to be introduced or are you ok with the current PR?

**Comment by trefis** [comment]
(Given your silence I chose the path of least effort :))

**Pull request merged**
