### PR TITLE
change manual to include a subsection about 'let exception'

### LINKED ISSUE #10847: `let exception` is not documented at the right place
`let exception E in …` was introduced in 4.04, according to the changelog, but it's listed in [the core expression chapter](https://ocaml.org/manual/expr.html) rather than [the language extensions](https://ocaml.org/manual/extn.html) as I believe it should. It also doesn't indicate a minimum required version.

I can open a documentation PR to change that if needed.

### PR DESCRIPTION
**Pull request by c-cube**
close #10847

### CODE REVIEW

**Comment by gasche** [comment]
Looks good to me. @Octachron, does that also work for you?

**Comment by Octachron** [comment]
Yes, this looks good to me too.

**Review by gasche — APPROVED** [review]

**Comment by damiendoligez** [comment]
@c-cube could you add a `Changes` entry?

**Comment by Octachron** [comment]
For this kind of small changes, I think it is fine to let @c-cube decide if he wishes to add a Change entry (in the 4.14) or not.

**Comment by c-cube** [comment]
No need for a change entry imho :)

**Comment by nojb** [comment]
`4.14` f844e61592050243dc69c0de3e87af85b61909ad

**Pull request merged**
