### PR TITLE
Make aliases absent in module type of

### PR DESCRIPTION
**Pull request by lpw25**
Module aliases can be either absent or present -- indicating whether they exist at runtime or not. The two kinds of module alias can be coerced to each other, but they are not equal. This distinction is not observable to users because present aliases only exist in covariant positions and so they are never compared for equality only for coercibility. However, #1652 changes that by allowing module type of to copy a present alias into an invariant position. This leads to errors like:

```ocaml
module X = struct module N = struct end end
module Y : sig
  module type S = sig module N = X.N end
end = struct
  module type S = module type of struct include X end
end;;

Line _, characters 6-70:
  ......struct
    module type S = module type of struct include X end
  end..
Error: Signature mismatch:
       Modules do not match:
         sig module type S = sig module N = X.N end end
       is not included in
         sig module type S = sig module N = X.N end end
       Module type declarations do not match:
         module type S = sig module N = X.N end
       does not match
         module type S = sig module N = X.N end
       At position module type S = <here>
       Illegal permutation of structure fields
```

which aren't great. This PR fixes the problem by converting all aliases to absent in `module type of`.

### CODE REVIEW

**Comment by lpw25** [comment]
@garrigue Could you review this one? I think we should get it in to 4.07.

**Review by garrigue — APPROVED** [review]
Turning an alias into absent seems innocuous.

**Comment by garrigue** [comment]
By the way I'm still waiting for your input on #1676 .

**Comment by lpw25** [comment]
Thanks, I'll try to have a look at #1676 some time next week.

**Comment by lpw25** [comment]
Cherry-picked to 4.07 as 04cfaec229..0f8f761db8.

**Pull request merged**
