### PR TITLE
User-defined indexing operator without array indexing

### PR DESCRIPTION
**Pull request by Octachron**
This pull request cherry-picks the features of the user-defined indexing operators branch orthogonal to the current array data types proposal #616.

More precisely, it adds two families of operators:
- `.[]` for simple indexing 
- `.{}` for multidimensional indexing

that can be redefined by users like other operators. For instance,

``` OCaml
type matrix = { dim:int; array: float array }
let (.[]) m (i,j) = m.array.( i + j * m.dim )
let (.[]<-) m (i,j) v = m.array.( i + j * m.dim ) <- v 
```

(see #69 and the included manual documentation for more information)

The array-like indexing operators `(.( ))` are left unmodified and free to be improved. 

If the array data proposal focuses on array-like data types, this proposal is more concerned with other data types that implements a map between two finite sets. Standard library's map and hashtable or multidimensional array are three examples of data types that could benefits from a short indexing syntax. It seems difficult to describe within the compiler all the kinds of maps between finite sets; therefore user-defined indexing operators might be a better fit here than the specialized field projection proposed for array data kinds.  

Moreover, to compensate, the loss of one user-definable family of index operators, the current indexing syntax is extended to support module path prefix like in the array data type proposal:
- `a.M.[i]` ≡ `M.(.[]) a i`
- `a.M.[i]<-v` ≡ `M.(.[]<-) a i v`
- `a.M.{i}` ≡ `M.(.{}) a i`
- `a.M.{i}<-v` ≡ `M.(.{}<-) a i v`

Note that this pull request integrates all the compatibility patches for the Bigarray modules already present in the user-defined indexing operator branch and should not break any code except for code relying on the old and undocumented parser-level implementation of indexing operators (i.e. the mapping between a.(i) and Array.get a i).

### CODE REVIEW

**Comment by gasche** [comment]
We discussed this solution during the development meeting where @lpw25 first proposed type-directed array resolution: having `.( )` type-directed and `.[ ]`, `.{ }` scope-directed. (Maybe @lpw25 himself proposed that as a way to avoid reverting your change.)

I was opposed to it at the time and I still think it's a hack. Choosing the semantics of a language feature based on whether one uses parentheses or accolades feel completely arbitrary to me, and I see no justification other than "well they were two proposals at the time...". What if people later ask for `.[ ]` to be type-directed (bytes and string, say?), or for `.( )` to be scope-directed?

Is there not a more satisfying solution to resolve this tension?

(I wonder if it would be possible to use the type-directed discipline when the typing information allows it, and the scope-directed discipline otherwise. It seems tricky and possibly wrong from the point of principality -- adding more type information changes the lookup strategy --- but maybe it just extends what is done for records?)

(Another solution would be to let users define type-directed access iterators for arbitrary types -- instead of introducing new operators in scope as in this proposal. That is, make @lpw25's proposal user-extensible. Can we get a coherent design this way? `type t = foo with (.()) = get and (.()<-) = set`)

**Comment by lpw25** [comment]
> Choosing the semantics of a language feature based on whether one uses parentheses or accolades feel completely arbitrary to me, and I see no justification other than "well they were two proposals at the time...".

I don't really agree with this. Distinguishing two semantically different operations by which symbols they use seems fairly natural. Method call and record projection are distinguished by whether we use `.` or `#`, why not distinguish projection primitives (`.()`) from arbitrary indexing functions (`.[]`) by the choice of parentheses. It is slightly unfortunate that this proposal uses `.` for something other than a projection primitive, whereas currently `.` always indicates a projection, but I think the cost is probably worth it to have nice syntax for indexing functions.

> What if people later ask for .[ ] to be type-directed (bytes and string, say?), or for .( ) to be scope-directed?

I don't think of the choice as about type-directed or scope-directed, but as about whether these operations are primitives. The choice was already made to make primitive operations support type-based disambiguation whilst leaving regular functions completely scope directed. This choice is not currently observable with array primitives as there is only a single-array type, but by allowing multiple array types (including redefining some existing types as arrays -- string, etc) we naturally get type-based disambiguation of the array primitives.

We are already heading towards a situation where primitive operations use type-based disambiguation, whilst regular functions use modular implicits to get similar behaviour. I would expect the same thing to happen here. `.()`, as a primitive, would use type-based disambiguation whilst `.[]`, as an ordinary function, would use modular implicits.

I think there are tangible benefits from syntactically distinguishing primitive operations -- which have no computational content -- from function application. At the very least this is good for the value restriction.

Note that with the array data types proposal `.()` will work with string and bytes, so there will already be a type-directed primitive for these types. (Not actually implemented yet in the PR due to some issues with `-safe-string`, but I would implement that before suggesting merging).

So I would be in favour of merging this proposal. (To be clear, I have not reviewed the code itself, I just mean that I am in favour in principle).

**Comment by garrigue** [comment]
> We are already heading towards a situation where primitive operations use type-based disambiguation, whilst regular functions use modular implicits to get similar behaviour.

What are you pointing at? If this is about record field access and datatype constructor, I repeat my view that the semantics do not use the type at all (the disambiguation is purely a compilation artefact). How can you guarantee that if the user has to define his own accessor functions?

**Comment by lpw25** [comment]
> How can you guarantee that if the user has to define his own accessor functions?

For clarity, I'm precisely saying that user functions do not use type-based disambiguation, whereas primitive operations (record fields and variant constructors) on types do. My only proposal (in a different PR) is to use type-based disambiguation for array primitives (as part of allowing user-defined array types).

Gabriel is suggesting that having both my proposal and the one in this PR is unsightly because the array operations will use type-based disambiguation whilst the user-defined indexing operators won't. My point was that this difference is already in the language, and it is about whether or not something is a primitive operation or a user-defined function.

**Comment by garrigue** [comment]
OK, looks like I got confused by the two PRs.

I would not really describe this as primitive vs. user-defined, but rather (guaranteed) uniform semantics vs. ad hoc semantics; otherwise I agree with you that it is wise to distinguish the two semantics.

**Comment by xavierleroy** [comment]
Six month later, any progress made on this one?

**Comment by Octachron** [comment]
Seven months later, I still not see a clear-cut way to resolve the tension between the potentially primitive `.()` operators and the non-primitives `.[]/.{}` operators, which share the same basic objectives (accessing an element of an indexed family) but with a different status; and thus different scope rules.

A possible solution might be to increase the syntactic distance between the two indexing operators family. However, choices are limited (with ascii characters): if we do not want to add yet another brace variations,
we can only replace the separator `.` . If I am not mistaken,  the only possible separator here would be ``?``, `` ` `` or `~`.
The syntax `a?[x]` may work well (in particular for dictionary or other data type where the natural return type is an `'a option`), but `a?[x]<-y` is already more startling, and `?` might be too visually invasive.
I find ``a`[x]`` mildly acceptable but foreign, and I don't think `a~[x]` conveys the right meaning.
Nevertheless, all syntaxes would suffer from their exoticism.

All in all, I think that the `a.{x}/a.[x]` syntax is still the optimal one for user-defined indexing operations,
even if it is not perfect when combined with array data types.

Another point to consider, maybe, is that user-defined indexing operators are not the only advantages of the `(.[])` syntax: it can be also useful to be able to distinguish in the parsetree `a.[x]` and 
`String.(unsafe_)get`. In particular, this would make easier to deprecate the `.[]` syntax.

In brief:

| Positive                                                    | Negative                                           |
|-------------------------------------------------------|------------------------------------------------|
| Nicer syntax for user-defined data types | More design space for operator hell |
| More information in the parsetree AST    | Tension with projection primitive      |
| Deprecatable                                           | (?)  Bigarray compatibility hack        |


(I need to check if the move of bigarray towards stdlib is enough to remove the bigarray compatibility hack).

**Comment by Drup** [comment]
There is also `a#[3]`.

The good thing about `#` is that there is a concrete precedent for using `#` instead of `.` for ad-hoc-y things.

**Comment by Drup** [comment]
(This is half a joke by the way, I still think the best solution is to arbitrarily decide that `.( )` is for type based access and open all the others for redefinition, and live with that)

**Comment by hcarty** [comment]
One possible benefit to `( #[] )` is that it opens up `( #() )` too.  It removes some of the visual ambiguity between the behavior of `.()` and `.[]`.

It may make more sense as a method syntax though, if someone wanted to use `method ( #[] )` in a class for some reason.

**Comment by hcarty** [comment]
Is there any chance this will make it into 4.05.0?  If the answer is unknown is there anything users can do to help?

**Comment by Octachron** [comment]
During the last developper meeting, it was briefly discussed that having a clearly distinct syntax from primitive projection operator was desirable. Since such syntax is implemented in #1064, I am closing for now this specific PR.

**Pull request closed without merging**
