### PR TITLE
PR#6935:ocamldebug:load_printer raise uncaught exception when passing directory

### PR DESCRIPTION
**Pull request by lijunsong**
Fix by catching Sys_error exception.

### CODE REVIEW

**Comment by gasche** [comment]
Hi @lijunsong , sorry for the lack of reactivity. Could you also edit the Changes file as advised in our [contributor documentation](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#changelog)? Your change should go in the section "Toplevel and debugger" of the in-progress 4.03.0 changelog, and it is important to mention the mantis issue number (`PR#6935, GPR#298: ...`).

**Comment by lijunsong** [comment]
Hi @gasche, Great! I'll do.

**Comment by lijunsong** [comment]
Hi @gasche, entry added. Please let me know if other things need to change (e.g. my commit messages). Thanks!

**Comment by gasche** [comment]
This is fine, I merged the change. Thanks for you work!

**Comment by lijunsong** [comment]
Sure. This is a great start for me. Thank you!

**Pull request merged**
