### PR TITLE
Simplify systhreads thread-local state management

### PR DESCRIPTION
**Pull request by kayceesrk**
Use a global key to access the per-thread `caml_thread_t` rather than have a key per domain.

This PR fixes the issue reported in #11226.

### CODE REVIEW

**Review by dra27 — APPROVED** [review]
The fix looks both sensible and correct - it's presumably "a mistake" that we were wasting an entire TLS key per-domain before.

**Comment by jmid** [comment]
Here's a small reproducible test case hacked together with @patricoferris and @jonludlam 
```ocaml
let () =
  let max_iterations = 128 in
  Domain.at_exit (fun () -> if Random.bool () then Thread.delay 0.5);
  for i=0 to max_iterations do
    Printf.printf "%d %!" i;
    let dom1 = Domain.spawn (fun () -> ()) in
    let _dom2 = Domain.spawn (fun () -> ()) in (* domain not joined *)
    let dom3 = Domain.spawn (fun () -> ()) in
    Domain.join dom1;
    Domain.join dom3;
  done
```
Note: It needs the `threads` dependency to trigger the bug.

Pro: it is small and triggers the segfault reliably
Con: it takes ~50secs to complete successfully once the PR is merged - which adds to the test suite running time

I can wrap it up as an test suite commit if the above is acceptable.

**Comment by kayceesrk** [comment]
I've modified the test contributed by @jmid to make it run faster. The new test takes **1 second** to run on my MacBook Pro. This test **segfaults on 90%** of the runs on trunk.

**Comment by gasche** [comment]
Note that we have a TEST_SIZE (I think?) variable now to dynamically decide to run the "fast" or "slow" version of a test. Would that specific test benefit from this approach? (Otherwise: yes, 1 seconds is much better than 50 seconds, so that version would be better.)

**Comment by xavierleroy** [comment]
I'm not sure we need to add a test here.  The bug was reproduced easily, diagnosed very precisely, fixed by simplifying existing code, so I very much doubt this exact same bug will come back later.

If we do need to add a test, the 50s version is too costly, but even the 1s version spawns 1024 domains without joining them, so if we're unlucky with scheduling, it can exceed the maximal number of domains.  Experience shows that on CI virtual machines we are often unlucky with scheduling.

So, thanks, this is a great repro case, but no thanks, this shouldn't go into CI.

**Comment by jmid** [comment]
I'll let you decide what to include :man_shrugging: 

For the record, this has proven a bit tricky to reproduce reliably.
The test case I first shared would reproduce with 100% on an Intel Mac Mini. Unfortunately it would reproduce with 0% for @kayceesrk and on my Intel MacBook Pro. The revised variant from 35d6d59 (included below since KC might force-push) however reproduces 14/15 on the MacBook too - and runs in ~3secs. I thought it might be relevant to document for the future.
```ocaml
(* TEST
* hassysthreads
include systhreads
** bytecode
** native
*)

let () =
  let max_iterations = 8192 in
  for _i=0 to max_iterations do
    Printf.printf ".%!";
    let dom1 = Domain.spawn (fun () -> ()) in
    let _dom2 = Domain.spawn (fun () -> Thread.delay 0.005) in (* domain not joined *)
    let dom3 = Domain.spawn (fun () -> ()) in
    Domain.join dom1;
    Domain.join dom3;
  done
```

**Comment by xavierleroy** [comment]
And I forgot to add that under Windows, terminating a program while some domains or threads are still running often causes a general protection fault.  That's why all the CI tests must join all their domain and threads before exiting.

**Comment by dra27** [comment]
I agree - the underlying problem was undefined behaviour (as noted in https://github.com/ocaml/ocaml/issues/11226#issuecomment-1122307078, `st_tls_newkey` isn't idempotent), so the repro is great for the bug report, but not for CI.

Once the test's removed, I think this PR is good to merge.

**Comment by kayceesrk** [comment]
Thanks for the comments. I've removed the test case. The PR should be good to go.

**Review by xavierleroy — APPROVED** [review]
Nice fix, thank you!

**Pull request merged**
