### PR TITLE
Remove embellishment in HACKING.adoc

### PR DESCRIPTION
**Pull request by shindere**
At the moment, this PR just removes one character (actually two if
counting the leading space) in HACKING.adoc

This is because check-typo complains about this character
and the embellishment it provides didn't seem worth patching check-typo
or anything else just for the sake of preserving this character.

Note that check-typo complains about more than 34 other non-ascii characters:

./typing/HACKING.adoc:6.119: [non-ascii] non-ASCII character(s)
./asmcomp/interval.mli:8.33: [non-ascii] non-ASCII character(s)
./asmcomp/interval.mli:9.16: [non-ascii] non-ASCII character(s)
./asmcomp/linscan.mli:8.33: [non-ascii] non-ASCII character(s)
./asmcomp/linscan.mli:9.16: [non-ascii] non-ASCII character(s)
./asmcomp/linscan.ml:8.33: [non-ascii] non-ASCII character(s)
./asmcomp/linscan.ml:9.16: [non-ascii] non-ASCII character(s)
./asmcomp/interval.ml:8.33: [non-ascii] non-ASCII character(s)
./asmcomp/interval.ml:9.16: [non-ascii] non-ASCII character(s)
./.travis-ci.sh:31.11: [non-ascii] non-ASCII character(s)
./testsuite/tests/tool-toplevel/strings.ml:12.5: [non-ascii] non-ASCII character(s)
./testsuite/tests/tool-toplevel/strings.ml:14.3: [non-ascii] non-ASCII character(s)
./testsuite/tests/lib-bigarray/change_layout.ml:7.30: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:12.40: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:13.37: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:14.35: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:22.78: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:23.38: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:24.46: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:25.46: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:26.46: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:27.62: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/mltest.ml:29.34: [non-ascii] non-ASCII character(s)
WARNING: too many [non-ascii] in this file.  Others will not be reported.
./testsuite/tests/win-unicode/symlink_tests.ml:4.56: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/symlink_tests.ml:5.86: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/symlink_tests.ml:6.88: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/symlink_tests.ml:7.56: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/symlink_tests.ml:8.54: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/exec_tests.ml:3.78: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/exec_tests.ml:4.38: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/exec_tests.ml:5.46: [non-ascii] non-ASCII character(s)
./testsuite/tests/win-unicode/exec_tests.ml:6.46: [non-ascii] non-ASCII character(s)
./tools/lintapidiff.ml:5.35: [non-ascii] non-ASCII character(s)

Mostly this is about non-ascii letters in names of people.

Did we already decide how these characters should be handled?

Do we want to make check-typo more tolerant or rather remove the accents
where possible?

### CODE REVIEW

**Comment by Drup** [comment]
Ohno, My pretty camel :(

Jokes asides, I think it's not a good idea to remove the accents in people's name.

**Comment by gasche** [comment]
I would personally support patching check-typo to accept the "bactrian camel" unicode character U+1F42B. @Drup, would you volunteer to do it?

**Comment by xavierleroy** [comment]
Are we going to do one pull request per Unicode character of interest?

**Comment by gasche** [comment]
Well I did briefly wonder about "Dromedary Camel" but I suppose we don't want that.

**Comment by shindere** [comment]
Xavier Leroy (2017/10/09 12:40 +0000):
> Are we going to do one pull request per Unicode character of interest?

No no, sorry. It was just an excuse to fix the related issues.

This character does not show up properly everywhere anyway so I'm not
sure patching check-typo just for that is a good idea.

But this is secondary. IMO it would just be nice to be able to have a
trunk where check-typo runs silently.

**Comment by dra27** [comment]
I need to re-visit it, but I'm pretty sure this was being addressed in #1287

**Comment by dra27** [comment]
I have just rebased 1287 - note that in mine I replaced it with `:camel:`, rather than removing it completely!

**Comment by shindere** [comment]
David Allsopp (2017/10/11 10:35 +0000):
> I have just rebased 1287 - note that in mine I replaced it with
> `:camel:`, rather than removing it completely!

Is :camel: a markup syntax that will give the right character when
possible?

**Comment by dra27** [comment]
It is indeed - on the GitHub webpage view of this thread, that's how your writing `:camel:` has appeared.

I can't find an official list of them, but there's a reasonable-looking list at https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by shindere** [comment]
Okay, thanks.
It's a nice alternative, sorry I didn't notice it was part of your PR,
@dra27.

**Comment by dra27** [comment]
No problem at all - it reminded me that that GPR needed refreshing (as it has other things too). I think this one can be closed, therefore?

**Comment by shindere** [comment]
David Allsopp (2017/10/12 09:41 +0000):
> No problem at all - it reminded me that that GPR needed refreshing (as
> it has other things too). I think this one can be closed, therefore?

Sure.

**Pull request closed without merging**
