### PR TITLE
CONTRIBUTING: how to sign the CLA

### PR DESCRIPTION
**Pull request by gasche**
This summarizes Xavier's recommendations at
  https://github.com/ocaml/ocaml/pull/342#issuecomment-178720630
which were later reused at
  https://github.com/ocaml/ocaml/pull/307#issuecomment-183356057

In particular this should create a URL anchor to direct people to:
  https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#how-to-sign-the-cla

### CODE REVIEW

**Comment by gasche** [comment]
You can see the rendered result at
  https://github.com/gasche/ocaml/blob/cla-instructions/CONTRIBUTING.md#how-to-sign-the-cla

**Comment by chambart** [comment]
You should probably rephrase a bit the phrase

> This ability to re-license allows INRIA to provide members of the Caml Consortium with a license on the Caml code base that is more permissive than the public license.

I didn't find any good phrasing yet, but we probably also want to mention that this also allow the license to evolve, like the recent change to LGPL which wouldn't have been possible since the copyright owners of some contributions are probably very hard to find and reach.

**Comment by gasche** [comment]
I don't plan to do the change @chambart proposed myself. I like the current phrasing and am not particularly into CLA apologetics. (Also I feel ambivalent about saying "see CLA is good as we can easily change to better licences" given that OCaml used for decades the license that I personally like least of all possible free software licenses, unrelatedly to the existence of the CLA. Not really a great demonstration.)

**Comment by gasche** [comment]
(I decided to go ahead and merge this low-risk, nobody-cares change.)

**Pull request merged**
