### PR TITLE
Fix Makefile typo

### PR DESCRIPTION
**Pull request by nojb**
Following #10169 (I think)

### CODE REVIEW

**Comment by nojb** [comment]
Sorry, this is the wrong fix. By the way I am trying to fix the following warnings (observed in OS X and also in the RISC-V CI at least):

```
+ make -j4 --warn-undefined-variables
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
stdlib/StdlibModules:56: warning: undefined variable ' '
...
```

**Comment by Octachron** [comment]
My solution to please both check-typo and the undefined Makefile variable warning was to define a separate upper function:
https://github.com/ocaml/ocaml/blob/trunk/api_docgen/Makefile.docfiles#L22

**Comment by dra27** [comment]
A variant of this works:

```diff
--- a/stdlib/StdlibModules
+++ b/stdlib/StdlibModules
@@ -47,6 +47,9 @@ STDLIB_PREFIXED_MODULES=\

 # add stdlib__ as prefix to a module except for internal modules
 # and the stdlib module itself
+EMPTY=
+SPACE=$(EMPTY) $(EMPTY)
+$(SPACE) :=
 define add_stdlib_prefix
   $(or $(filter-out $(STDLIB_PREFIXED_MODULES), $1), \
     stdlib__$(shell echo $1 | cut -c1 | tr '[:lower:]' '[:upper:]')$\
```
More shortly...

**Comment by shindere** [comment]
I think the `EMPTY` variable is already defined in the build system
so it may not be necessary to define it again here. Perhaps the SPACE
variable can also be defined globally if used in more than one place.

**Comment by dra27** [comment]
Ack - just testing an alternate fix

**Comment by nojb** [comment]
Closing this in favor of #10270

**Pull request closed without merging**
