### PR TITLE
Only rebuild `flexlink.exe` when sources change

### PR DESCRIPTION
**Pull request by dra27**
The upstream repository for FlexDLL doesn't support bytecode building - it's forced on it by overriding the value of `OCAMLOPT`. This means that OCaml's build system doesn't know whether `flexdll/flexlink.exe` is a bytecode or native build. Consequently, `boot/flexlink.byte.exe` and `flexlink.opt.exe` were created by _moving_ `flexdll/flexlink.exe` after compilation.

However, this means that subsequent builds always compile a new `flexdll/flexlink.exe` which is wasteful.

Now, `boot/flexlink.byte.exe` and `flexlink.opt.exe` depend on the sources in `flexdll/` and `flexdll/flexlink.exe` is copied out and make is invoked with `-B` to force the linking of the target.

This is non-urgent, it's just been annoying me for a while, and while fixing something else flexdll-related, I addressed this too...

### CODE REVIEW

**Comment by shindere** [comment]
Why does upstream not support byte-code compilation?

Isn't it that bit that should be fixed, perhaps in addition to this PR?

Also, I am unclear about why we do have to move / copy files around. Is it
important in some situations, or could we use the compiled exacutables
directly rather than putting them in boot/ first?

Regarding the definition of `FLEXDLL_SOURCE_FILES`, don't you want to add
a `$(wildcard $(FLEXDLL_SOURCES)/*.mli)` bit? I do realise flexdll does not
have any `.mli` files yet, but hopefully that will change one day and then
you will be prepared for that already.

**Comment by dra27** [comment]
There's never been a reason to have a bytecode `flexlink.exe`, so upstream's had no reason to do it - even with OCaml 5 being bytecode only on 32-bit, the development is still heading towards a 64-bit system (Visual Studio 2022 only runs on 64-bit, for example). However, my bigger "problem" is that that would be adding code into flexlink's build system which it would never use and we'd only override (as we do already here, but at least we override a part of the build system which ocaml/flexdll also uses!). Changing flexlink's build system is also higher risk, as new versions of flexlink do need to work in older versions of OCaml (including the flexlink bootstrap).

We previously discussed the locations and names for `boot/flexlink.byte.exe` and `flexlink.opt.exe` in #10135 - in part it's to avoid putting files in `flexdll/` which aren't covered by `flexdll/.gitignore` and in part it's because `boot/flexlink.byte.exe` forms part of the infrastructure to support the boot compiler (along with the stdlib and runtime which get added there).

I can add the wildcard pattern for `flexdll/*.mli` if you really insist, but it reads more like a mistake to me to have a wildcard pattern which matches nothing. ocaml/flexdll's CI tests every PR against OCaml's flexlink bootstrap, so the change would be detected if it got made... not that I think it's terribly likely before flexlink gets completely rewritten anyway (at which point, the two build systems can be refactored to live in perfect harmony!)

**Comment by shindere** [comment]
Many thanks for your explanations, DAvid.

I won't insist on anything, no worries.

**Comment by shindere** [comment]
Note: I tried to approve the PR but so far I'm getting 500 errors.

**Comment by dra27** [comment]
Thanks @shindere! The interaction of the two build systems can definitely be made cleaner, I just feel that that should be done alongside other "disruptive" changes (like eliminating the wrapping of the linker).

GitHub is having issues (again, poor ops people!) - I don't know how accessible githubstatus.com is, although the status is also tweeted at [@githubstatus](https://twitter.com/githubstatus)

**Comment by shindere** [comment]
David Allsopp (2022/03/22 09:30 -0700):
> Thanks @shindere! The interaction of the two build systems can
> definitely be made cleaner, I just feel that that should be done
> alongside other "disruptive" changes (like eliminating the wrapping of
> the linker).

Okay no problem. Don't hesitate to involve me if there is something to
review on either side.

> GitHub is having issues (again, poor ops people!) - I don't know how
> accessible githubstatus.com is, although the status is also tweeted at
> ***@***.***(https://twitter.com/githubstatus)

I was not aware of those! Thanks!

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Approved and merged.

**Pull request merged**
