### PR TITLE
Allow shortcut for extension on semicolons

### PR DESCRIPTION
**Pull request by ghost**
Similarly to what is done for keywords.

The syntax is:

```
  <expr> ;%foo <expr>
```

and is a shortcut for: `[%foo <expr> ; <expr>]`

The rationale is to have the equivalent of the normal semicolon when
writing ml code using a monadic `let%foo`.

`;%` is currently a syntax error, so it doesn't break anything

### CODE REVIEW

**Comment by Drup** [comment]
If we are going this way, adding shortcuts on symbols (and I'm not convinced that we should), we might as well do it for all the symbols....

**Comment by ghost** [comment]
That would be a breaking change, so I don't think that's worth it. On the contrary we have a real use case for the semicolon and it doesn't break anything

**Comment by alainfrisch** [comment]
Do we really need to introduce a new token?  Whitespace is allowed between the keyword and "%", so it would be better if it would as well between ";" and "%"; or does it introduce some parsing problems?

**Comment by trefis** [comment]
It doesn't seem to introduce any conflict.
Did `[%`, `[@@@`, etc introduce parsing problems?

**Comment by bobzhang** [comment]
how is it different from `begin%foo e1; e2 end`

**Comment by ghost** [comment]
@bobzhang, it's the same, just shorter. Basically the first form is nicer than the second:

``` ocaml
(* first form *)
f x ;%bind
g y ;%bind
return ()

(* second form *)
begin%bind
  f x;
  begin%bind
    g y;
    return
  end
end
```

**Comment by alainfrisch** [comment]
You could probably extend the interpretation of %bind to all immediately nested sequences, allowing to write:

```
begin%bind
  f x;
  g y;
  return ()
end
```

**Comment by ghost** [comment]
Well, you'd need to interpret all the `let` as well, as we often mix `let ... in` and `;`, and that would be like the haskell do-notation. In practice, in real code we often have a mix of `let`, `let%bind` and `;` at the same level so having a block bind would introduce more visual nesting

**Comment by bobzhang** [comment]
@diml, can you also do this `{ %ext a = 3; b = 4}`, it is very similar to your extension here, I have a use case for it too, thanks!

**Comment by lpw25** [comment]
Is anyone strongly opposed to this?

As the change is trivial and only effects what syntax ppx writers can use, I'll probably merge it in a couple of days if no one objects.

**Comment by bluddy** [comment]
Just noticed this! This is great, especially if we adopt shortcuts like ;%b rather than using 'bind'. Still a little messy looking, but not too bad.

**Comment by hcarty** [comment]
@bluddy I started a patch for Lwt's ppx [here](https://github.com/ocsigen/lwt/pull/307) which we ended up closing due to a mixture of backwards-compatibility concerns and generally unpleasant-looking syntax with `;%lwt`.  The implementation was fairly straightforward though and should be simple enough to experiment with in other contexts.

**Comment by bluddy** [comment]
I agree that `;%lwt` isn't too appealing. `;%l` is a little better, but really, I'd much prefer it if `;%` was possible. Is there anything that theoretically prevents an empty string extension? In cases where brevity is desired, this could really be a game changer, because it's almost like a simple operator.

**Pull request merged**
