### PR TITLE
Fix dynlink init

### PR DESCRIPTION
**Pull request by dbuenzli**
See #9338. 

/cc @damiendoligez

### CODE REVIEW

**Comment by dbuenzli** [comment]
Btw. I ran the test suite on my machine and got a notification from github. Is there any documentation about what's happening here ?

**Comment by nojb** [comment]
> Btw. I ran the test suite on my machine and got a notification from github. Is there any documentation about what's happening here ?

The testsuite should run purely locally; what kind of notification did you get?

**Comment by dbuenzli** [comment]
Ah wrong inference of cause of effect. It seems that when I push on a branch of my github fork ocaml worfklow actions gets triggered. I disabled that there. (Sorry I'm not up-to-date with all the github wizbang).

**Review by xavierleroy — APPROVED** [review]
Obviously correct.  Thanks for the patch.

**Comment by nojb** [comment]
There is a Travis failure that looks related:
```
 ... testing 'test.ml' with 1 (native) => failed (The file /home/travis/build/ocaml/ocaml/testsuite/_ocamltest/tests/lib-dynlink-init-info/test/ocamlopt.byte/ocamlopt.byte.output was expected to be empty because there is no reference file /home/travis/build/ocaml/ocaml/testsuite/tests/lib-dynlink-init-info/test.compilers.reference but it is not:
========================================
File "_none_", line 1:
Warning 58 [no-cmx-file]: no cmx file was found in path for module Dynlink_compilerlibs, and its interface was not compiled with -opaque
========================================
```

**Comment by dbuenzli** [comment]
That's the very test that this PR adds and the problem is apparently that the test doesn't compile, any idea why this would only occur on that flambda variant ?

**Comment by nojb** [comment]
> That's the very test that this PR adds and the problem is apparently that the test doesn't compile, any idea why this would only occur on that flambda variant ?

The test compiles, but triggers Warning 58...

**Comment by nojb** [comment]
At first sight it seems like `ocamltest` is not passing `-I otherlibs/dynlink/native` which is where `dynlink_compilerlibs.cmx` is found.

**Comment by nojb** [comment]
Possible fix in #9791.

**Comment by lthls** [comment]
The `include dynlink` part will tell the compiler to look for objects in `otherlibraries/dynlink/`, but the `dynlink.cmx` file depends on other files hidden in the `native` subfolder. When compiling against an installed version of `Dynlink` these files are copied in the same folder as the main files, so the error would not occur.
Without flambda, the compiler doesn't need to look transitively for `cmx` files as often, which is why you only get the error with flambda.

To fix the error you have a few options:
- Modify the `ocamltest` header following the other dynlink tests, so that the output of the compiler is ignored
- Add an additional `-I` flag
- Disable the warning for your test
- Fix the dynlink support in `ocamltest` so that it also includes the `native` subfolder
- And probably other more or less hackish solutions

**Comment by lthls** [comment]
I took too long to post, and @nojb beat me to it...

**Comment by dbuenzli** [comment]
@lthls but I appreciate the details ! `ocamltest` remains quite obscure and not so user friendly to me (in particular I find it hard to understand failures and to what exactly they point to, in particular if the actual path to the tests could be output rather than have to dig them in the various directories that would be great).

**Comment by nojb** [comment]
> @lthls but I appreciate the details ! `ocamltest` remains quite obscure and not so user friendly to me (in particular I find it hard to understand failures and to what exactly they point to, in particular if the actual path to the tests could be output rather than have to dig them in the various directories that would be great).

If you want to get the PR merged quickly, feel free to disable Warning 58 as suggested by @lthls ... I will make sure to re-enable it as part of #9791

**Comment by nojb** [comment]
- #9791 has been merged, so I closed/reopen to run Travis again.
- Also, @dbuenzli Changes needs to be updated.

**Comment by dbuenzli** [comment]
Thanks @nojb for the `ocamltest` help, very much appreciated. `Changes` updated and all is green now.

**Comment by nojb** [comment]
Merged, thanks!

**Pull request merged**
