### PR TITLE
Fix #8558 by disabling optimization of local functions, for 4.08

### LINKED ISSUE #8558: Miscompilation in 4.08
The following code, when compiled with 4.08, raises
`Assert_failure` at run time (it does not with 4.07):

```
let () =
  let f () = () in
  let r = ref 0 in
  let g () = f (incr r) in
  g ();
  assert (!r = 1)
```

The initial lambda is:
```
(seq
  (let
    (*match*/86 =
       (let
         (f/80 = (function param/81 0a)
          r/82 = (makemutable 0 (int) 0)
          g/83 = (function param/84 (apply f/80 (+:=1 r/82))))
         (seq (apply g/83 0a)
           (if (== (field 0 r/82) 1) 0a
             (raise
               (makeblock 0 (global Assert_failure/28!) [0: "b.ml" 6 2]))))))
    0a)
  0a)
```

which becomes, after `Simplif.simplify_local_functions`:

```
(seq
  (let
    (*match*/86 =
       (let (r/82 = (makemutable 0 (int) 0))
         (seq
           (catch
             (catch (exit 4 0a) with (4 param/84) (exit 5 (+:=1 r/82)))
            with (5 param/81) 0a)
           (if (== (field 0 r/82) 1) 0a
             (raise
               (makeblock 0 (global Assert_failure/28!) [0: "b.ml" 6 2]))))))
    0a)
  0a)
```

then translated by `Simplif.simplify_exits` into:
```
(seq
  (let
    (*match*/86 =
       (let (r/82 = (makemutable 0 (int) 0))
         (seq (let (param/88 =a 0a param/87 =a (+:=1 r/82)) 0a)
           (if (== (field 0 r/82) 1) 0a
             (raise
               (makeblock 0 (global Assert_failure/28!) [0: "b.ml" 6 2]))))))
    0a)
  0a)
```

and finally by `Simplif.simplify_lets` into:
```
(seq
  (let
    (*match*/86 =
       (let (r/82 =v[int] 0)
         (seq 0a
           (if (== r/82 1) 0a
              (raise
                (makeblock 0 (global Assert_failure/28!) [0: "b.ml" 6 2]))))))
    0a)
  0a)
```

The problem, as I understand it, is that `Simplif.simplify_exits` introduces
let-bindings with kind `Alias` while the expression bound to `param/87`
contains a side effect. The let-binding then disappears because `param/87`
is never used. Indeed, a (tested) fix is to change `Alias` to `Strict` [here](https://github.com/ocaml/ocaml/blob/trunk/bytecomp/simplif.ml#L285).

It is not immediately clear to me what a good fix is (mainly because I do
not know whether expressions passed to static exits are expected to be pure).
Changing `Alias` to `Strict` unconditionally seems a bit harsh. We could
inspect the expression to check whether it is pure, or not apply one of
the rewriting above when it is not.

### PR DESCRIPTION
**Pull request by alainfrisch**
(TODO: adapt the testsuite and the Changes file.)

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm lost.  Could you please explain what you're doing?

**Comment by alainfrisch** [comment]
I'm disabling the optimization of local functions, which seems to be the safer fix to me to avoid correctness and performance regression in 4.08 compared to 4.07.

**Comment by alainfrisch** [comment]
(I was comfortable enough with my proposal in #8559, but not with your simpler fix, which seems too risky to me.)

**Comment by alainfrisch** [comment]
(I admit that it might be a bit too crazy to be concerned by performance regression on bytecode.)

**Comment by alainfrisch** [comment]
Oh right, never mind, I'll push the simpler fix after all.  If it degrades performance in bytecode, it's not the end of the world.

**Pull request closed without merging**
