### PR TITLE
make Stack.length constant time

### PR DESCRIPTION
**Pull request by ygrek**
and add a testsuite for Stack as a whole (shamelessly adapted Queue tests)

### CODE REVIEW

**Comment by gasche** [comment]
Of course I would merge the testsuite alone with my eyes closed.

I'm less sure about the extra `length` field, though: that's a classic compromise to make in data structure (length becomes O(1) at the cost of an amortized cost throughout the implementation), why would we change our mind about it today? Do you have a particular use-case for this is mind? Is there an argument that users would rather expect this choice? Is it more consistent with other choices in the standard library?

**Comment by ygrek** [comment]
It is just my gut feeling. Trying to rationalize it - seems like all mutable data structures in stdlib have constant-time length (Queue, Array, Hashtbl). And I  see people surpised discovering it is not the case with Stack - which led to this simple patch. As for performance cost - I believe (sic) that mutable update of pointer far outweighs the increment of immediate value so it shouldnt be noticeable at all.

**Comment by gasche** [comment]
The fact that all other mutable structures have this property is ok enough for me. @alainfrisch or @damiendoligez , a second opinion?

**Comment by alainfrisch** [comment]
I tend to be convinced as well.  A micro-benchmark to evaluate the time overhead of the extra field (when length is not used) would be useful.

**Pull request merged**
