### PR TITLE
Add documentation for contributing to the stdlib

### PR DESCRIPTION
**Pull request by alan-j-hu**
I would like to document the technical standard library contribution process so that future potential contributors don't need to read commits to figure out how to build the compiler with changes. These notes are based on my experience making the (rejected) pull request to add a monad interface to the standard library.

I tested out these instructions with a dummy module. I am aware that there is a `partialclean` target, but I used `clean` to be safe; perhaps I should see if the instructions also work with `partialclean`? Also note that the compiler built even though I had forgotten to update `otherlibs/threads/Makefile`, but I assume that the file *should* be updated since `otherlibs/threads` contains `stdlib.mli` and `stdlib.ml`.

Special thanks to @gasche and @Octachron for helping me build the compiler on discuss.ocaml.org.

### CODE REVIEW

**Comment by gasche** [comment]
The content seems fine to me, but it should be in a file HACKING rather than README (that's our convention for files that are of interest to contributors, not just people installing the software from sources). The convention is to have HACKING files be in AsciiDoc format (so HACKING.adoc rather than HACKING.md); if you see how to translate the markdown idioms that you use into AsciiDoc, that's nice (you can use the root HACKING.adoc for inspiration), but otherwise feel free to just write a HACKING.md, and ask someone else to do the porting.

**Comment by alan-j-hu** [comment]
I've translated the Markdown to AsciiDoc, and the document seems to render correctly on GitHub. `stdlib/HACKING.adoc` mentions and links to the `HACKING.adoc` (as well as `CONTRIBUTING.md`) in the repository's root without the `../`; should I rename the link text from `HACKING.adoc` to `../HACKING.adoc` (and `CONTRIBUTING.md` to `../CONTRIBUTING.md` as well, for consistency) to prevent confusion when seeing a reference to a file called `HACKING.adoc` in a file named (`stdlib/`)`HACKING.adoc`, or should which file the name refers to be obvious given that it's a link?

**Comment by gasche** [comment]
Yes, that would be nice, thanks!

**Comment by gasche** [comment]
I'd like ot have a second pair of eyes from someone that worked on the standard library recently ( @nojb ? ).

**Comment by Octachron** [comment]
Ideally, it would be nice to mention how to update the manual, but I can add this point later.

**Comment by dbuenzli** [comment]
> Ideally, it would be nice to mention how to update the manual, but I can add this point later.

This is not ideal, it's needed IIRC the CI won't pass if you don't do it. [This](https://github.com/ocaml/ocaml/pull/1940/commits/1798999b6543dcabfe9567e827851b5787cbc65a) PR should have everything for it to pass. 

The CI checks can be run locally but I'm no longer sure which ones they are. For sure there's [check-typo](https://github.com/ocaml/ocaml/blob/trunk/tools/check-typo) but the check for the presence of the new module in the manual I can't remember where it came from.

**Comment by Octachron** [comment]
All the manual consistency tests are in `manual/tests`: the CI runs `make -C manual/tests check-stdlib` .

**Review by gasche — APPROVED** [review]
Sorry for letting this PR wait by -- it was holiday season... We didn't get the second sanity-check that I hoped for, but I think that's okay, we can always improve the wording later if there are some mismatches. Merging!

**Pull request merged**
