### PR TITLE
Reduce the size of cmx files in classic mode (flambda)

### PR DESCRIPTION
**Pull request by xclerc**
(Basically https://github.com/ocaml/ocaml/pull/1343 rebased on top of https://github.com/ocaml/ocaml/pull/1663, minus the part already in https://github.com/ocaml/ocaml/pull/1627
and the computation of reachable symbols to keep approximations only for
such symbols)

Reduces the size of cmx files by changing the types of closures and sets
of closures in export infos to newly-introduced approximations for these
entities and keeping the bodies of functions in classic mode iff they can be
inlined.

### CODE REVIEW

**Comment by xclerc** [comment]
This PR was originally written @fyquah95, and reviewed by @lpw25 and myself.
My understanding is that we hence only need validation of the general approach
(typically from @chambart).

**Comment by chambart** [comment]
I'm ok. I made my remarks as a PR on this branch.

**Comment by damiendoligez** [comment]
Now we need a rebase. @xclerc

**Comment by mshinwell** [comment]
Ack, this is being worked on today.

**Review by damiendoligez — APPROVED** [review]
Approval based on @chambart's review. Good to merge after CI completes.

**Pull request merged**
