### PR TITLE
Fix tests/lib-dynlink-pr4229

### PR DESCRIPTION
**Pull request by damiendoligez**
This test compiled in the source directory, breaking `ocamltest`'s invariant that all generated files are in the `_ocamltest` directory. This means `make distclean` would not clean up the files in question.

For some reason, `ocamltest` does not copy/link the `main_native.ml` file. I simply got rid of it by sharing the code with `main.ml`. It did seem strange anyway to have a test script in a file (main.ml) that was testing another file (main_native.ml).

@shindere I also noticed that `ocamltest` fails to notice when the output and the reference file differ by the newline at the end of the last line, but this is not trivially fixable.

### CODE REVIEW

**Comment by damiendoligez** [comment]
BTW I think the test script in this file could be made much shorter.

**Review by nojb — APPROVED** [review]
LGTM.

If memory serves, I wrote this test originally; at the time I just made a line-by-line copy of the original `Makefile` test. It did (and does) look like it is overly long and complicated; suggestions for improvements welcome!

**Comment by damiendoligez** [comment]
The only CI failure is the absence of a Changes entry, so I merged. Thanks @nojb.

**Comment by shindere** [comment]
Again, sorry to come in so late.

To respond to @nojb's comment about whether there is a way to make the
test shorter: the shell script commands could be put in a script file.
That would not make the tests a lot shorter, but then at least creating
the subdirectory and copying the files there could be a script shared by
the two tests (native and bytecode).

Damien Doligez (2019/04/26 08:11 -0700):
> @shindere I also noticed that `ocamltest` fails to notice when the
> output and the reference file differ by the newline at the end of the
> last line, but this is not trivially fixable.

So @damiendoligez and I discussed this in person and it seems that the
problem is that a program reading a file with input_line will have no
way to distinguish a last-line ending with '\n' from one that has no
line terminator.

It is indeed unclear whether this should be fixed in sthe standard
library (and how) or whether one should simply not use input_line at all
in such a context.

**Comment by damiendoligez** [comment]
We should add a new function to the standard library and deprecate `input_line`.

**Comment by shindere** [comment]
Damien Doligez (2019/09/10 07:45 -0700):
> We should add a new function to the standard library and deprecate
> `input_line`.

@gasche do you feel this would be a good candidate for a junior task
(with some hand holding maybe)?

**Comment by gasche** [comment]
Yes, I think it would make sense. (It is entirely possible that a function with a better API exists somewhere in the OCaml library ecosystem, so it would be reasonable to start by looking around for what exists. That itself can be made a junior task.)

(I disagree that we should deprecate `input_line` as soon as a replacement exists. I would propose to wait for the replacement to be old enough (Debian stable).)

**Comment by shindere** [comment]
Gabriel Scherer (2019/09/10 09:03 -0700):
> Yes, I think it would make sense. (It is entirely possible that a
> function with a better API exists somewhere in the OCaml library
> ecosystem, so it would be reasonable to start by looking around for
> what exists. That itself can be made a junior task.)

Are you somehow taking care of gathering the junior tasks so that this
kind of exchange does not get lost?

**Comment by gasche** [comment]
No, not presently. I just added a github "label" to the present issue (but it's not going to be very useful as the issue is closed), someone needs to create a new issue to track the idea.

**Comment by shindere** [comment]
Gabriel Scherer (2019/09/10 09:16 -0700):
> No, not presently. I just added a github "label" to the present issue
> (but it's not going to be very useful as the issue is closed), someone
> needs to create a new issue to track the idea.

I just created #8931 but did not add the label because it's not very
easy to do for me.

**Comment by nojb** [comment]
> @shindere I also noticed that `ocamltest` fails to notice when the output and the reference file differ by the newline at the end of the last line, but this is not trivially fixable.

@shindere Sorry coming late to the discussion, but why doesn't `ocamltest` shell out to an external command to do the diff ? For example `git diff --no-index` is bound to be in every developer machine and it gives you colored diffs which may be easier to read for some.

**Comment by nojb** [comment]
> > @shindere I also noticed that `ocamltest` fails to notice when the output and the reference file differ by the newline at the end of the last line, but this is not trivially fixable.
> 
> @shindere Sorry coming late to the discussion, but why doesn't `ocamltest` shell out to an external command to do the diff ? For example `git diff --no-index` is bound to be in every developer machine and it gives you colored diffs which may be easier to read for some.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2019/09/10 23:46 -0700):
> @shindere Sorry coming late to the discussion, but why doesn't
> `ocamltest` shell out to an external command to do the diff ? For
> example `git diff --no-index` is bound to be in every developer
> machine and it gives you colored diffs which are much easier to read.

@nojb are you talking about the comparison or about the diff here? For
the diff, ocamltest does of course use an external command. This command
can not yet be ocnfigured, but it's definitely an external one and it's
on my TODO list to make it configurable. However I think that here the
problem has to do with how files are compared, much more than with the
way their differences are displayed.

**Comment by nojb** [comment]
> Nicolás Ojeda Bär (2019/09/10 23:46 -0700):
> @shindere Sorry coming late to the discussion, but why doesn't `ocamltest` shell out to an external command to do the diff ? For example `git diff --no-index` is bound to be in every developer machine and it gives you colored diffs which are much easier to read.
> @nojb are you talking about the comparison or about the diff here? For the diff, ocamltest does of course use an external command. This command can not yet be ocnfigured, but it's definitely an external one and it's on my TODO list to make it configurable. However I think that here the problem has to do with how files are compared, much more than with the way their differences are displayed.

Well, one could use `git diff --ignore-cr-at-eol --exit-code` to compare files; this will have exit code 1 if there are differences, or 0 otherwise, and will ignore Windows/Unix line ending differences. And it would not have the problem that `input_line` has.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2019/09/11 00:07 -0700):
> > Nicolás Ojeda Bär (2019/09/10 23:46 -0700):
> > @shindere Sorry coming late to the discussion, but why doesn't `ocamltest` shell out to an external command to do the diff ? For example `git diff --no-index` is bound to be in every developer machine and it gives you colored diffs which are much easier to read.
> > @nojb are you talking about the comparison or about the diff here? For the diff, ocamltest does of course use an external command. This command can not yet be ocnfigured, but it's definitely an external one and it's on my TODO list to make it configurable. However I think that here the problem has to do with how files are compared, much more than with the way their differences are displayed.
>
> Well, one could use `git diff --ignore-cr-at-eol --exit-code` to
> compare files; this will have exit code 1 if there are differences, or
> 0 otherwise, and will ignore Windows/Unix line ending differences. And
> it would not have the problem that `input_line` has.

I think it's @dra27 who thinks that it's not that simple and who
hardened the comparison algorithm because some differences in the way
lines are ending do need to be taken into acocunt?

There is also the efficiency problem when calling one or perhaps even
two external processes, especially on Windows.

**Comment by dra27** [comment]
Late to the party too. I think my concern has been conflated from a different one - the "usual" problem I have is the assumption that text-mode will solve the CRLF problem, which doesn't deal with the case of checking out a Windows-style file on Unix (in other words, building the Cygwin port or WSL from a Windows checkout of the sources). I don't think that's relevant to the issue here.

@nojb's suggestion to use `git diff --ignore-cr-at-eol` would be fine (you'd want to add `--no-index` I think too?). There was a preference to switch from an external to OCaml code (see https://github.com/ocaml/ocaml/pull/1426#issuecomment-336153652) when I eliminated `cmp`.

Checking whether the file has EOL at EOF is quite niche - it feels overkill to add a stdlib function for that. At EOF, I believe (I should say hope - I do it in opam!) it's sound to say:

```ocaml
with End_of_file ->
  set_binary_mode_in ic true;
  seek_in ch (in_channel_length ch - 1);
  input_char ch
```

and you now have the last character of the input file, so the logic can be tweaked as to whether `\n` is written on the last line or not.

**Comment by xavierleroy** [comment]
@dra27's approach might do the job. In the meantime I came up with the following function that reads an input channel as a sequence of characters, removing `\r` if it precedes `\n` or end-of-file and keeping `\r` everywhere else:
```
(* Read a file as a sequence of characters while normalizing end of lines:
 - a '\r' character that is followed by '\n' or by end of file is removed;
 - other '\r' characters are preserved.
*)

let read_channel ic : char Seq.t =
  let rec read last_was_cr () =
    match input_char ic with
    | exception End_of_file ->
        Seq.Nil
    | '\r' -> 
        if last_was_cr
        then Seq.Cons('\r', read true)
        else read true ()
    | '\n' ->
        Seq.Cons('\n', read false)
    | c ->
        if last_was_cr
        then Seq.Cons('\r', fun () -> Seq.Cons(c, read false))
        else Seq.Cons(c, read false)
  in read false
```
Now, comparing the contents of two files is easy:
```
(* Compare two sequences *)

let rec compare_seqs (s1: char Seq.t) (s2: char Seq.t) =
  match s1(), s2() with
  | Seq.Nil, Seq.Nil -> true
  | Seq.Cons(c1, s1), Seq.Cons(c2, s2) -> c1 = c2 && compare_seqs s1 s2
  | _, _ -> false

(* Compare two files *)

let compare_files file1 file2 =
  let ic1 = open_in_bin file1 and ic2 = open_in_bin file2 in
  let res = compare_seqs (read_channel ic1) (read_channel ic2) in
  close_in ic1; close_in ic2;
  res
```
This should be very robust against Windows EOL vagaries.

**Pull request merged**
