### PR TITLE
PR#7370: bump magic number (ocamldep segfault)

### PR DESCRIPTION
**Pull request by damiendoligez**
The question is: are there any other magic numbers we need to change, and how do we find them?

### CODE REVIEW

**Comment by alainfrisch** [comment]
What's the argument against systematically bumping all magic numbers before a release?

**Comment by damiendoligez** [comment]
You mean a major release, right?

**Comment by alainfrisch** [comment]
I actually meant any release.  I don't see a scenario where users would like to mix .cmi/.cmx/.cmxs files produced by different versions of the compiler.  Even if the format doesn't change, the behavior of the compiler does. And even if it didn't, who would take the risk?

**Comment by trefis** [comment]
It's not about mixing files, it's about the tools processing this file, is it not? Why would you require some tool to be "updated" and built for as many (minor) versions of the compiler if there is no need to?
For instance merlin usually doesn't really need updating between minor releases and you need only build on merlin to work with say ocaml 4.02.2 and 4.02.3.

**Comment by alainfrisch** [comment]
Even for external tools, I would expect that the installation be usually managed by OPAM, and that the workflow would guarantee that Merlin has been compiled exactly with the same version as the one used for compiling the edited files.

**Comment by mshinwell** [comment]
I tend to think it's preferable to not bump the version numbers unless required for minor releases. Extra time spent managing deployments that are not using OPAM is a concern here. However I think all of the numbers could reasonably be bumped upon a major release.  (Tools such as Merlin would probably need to be changed across such a release in any event.)

**Comment by damiendoligez** [comment]
We'll probably switch to bumping all the numbers on each major release, but not this time because I'd like to see a bit more discussion (and I'm feeling a bit nervous about breakage).

**Pull request merged**
