### PR TITLE
Simplify calls to caml_int_compare (and similar functions) (was #1809)

### PR DESCRIPTION
**Pull request by smuenzel**
Rebase #1809 to account for the new comparison primitive.

Also change the tests to force generation of assembly, so we can compare the output (which I did for amd64, and the simplification indeed works).

FYI @xclerc, @lthls

### CODE REVIEW

**Comment by smuenzel** [comment]
Does anyone have thoughts on this PR? A review was already done in #1809

**Comment by gasche** [comment]
@lthls could you by chance do another round of review on this?

**Review by lthls — APPROVED** [review]
The PR looks fine. In the Flambda 2 version that I implemented recently, I also handle `0 op compare x y`; I don't know how relevant it is in practice, so I'm fine with keeping the PR as it is.

**Comment by smuenzel** [comment]
Thanks @lthls. I will follow up later and check if the case with zero first occurs in the wild and submit a follow-up PR if it does.

**Pull request merged**
