### PR TITLE
Allow to manipulate the argument of an n-ary constructor as a tuple

### PR DESCRIPTION
**Pull request by alainfrisch**
This PR implements Mantis' PR#6455 ( http://caml.inria.fr/mantis/view.php?id=6455 ), i.e. the ability to manipulate the argument of an n-ary constructor as a real tuple, constructing or deconstructing the tuple on demand.

(It would be possible to use the tuple value in place of the constructor or vice-versa in patterns, when the constructor has tag 0.  This optimization is not included.)

### CODE REVIEW

**Comment by c-cube** [comment]
Is there a reason a constructor cannot always be used as a tuple? I thought the tag was not relevant for tuples, so, for instance, `a :: b` should always be allowed to be a `'a * 'a list` tuple?

**Comment by alainfrisch** [comment]
@c-cube See the Mantis ticket.  Using the constructor directly would break the polymorphic comparison.  Of course, in the example you suggest, the constructor has the same tag as the tuple (0), so one could reuse it directly.

**Comment by klakplok** [comment]
It seems like a good idea to get rid of this limitation, which is hard to justify to newcomers.
Does your patch handle `P ((cx, cy) as c)` ?

**Comment by alainfrisch** [comment]
> Does your patch handle P ((cx, cy) as c) ?

Yes, it does.

**Comment by lefessan** [comment]
I am concerned by the fact that this patch makes pattern-matching allocate a data structure transparently. I know that it is already the case for floats, but still, it could become a source of inefficiency for beginners, that do not realize that they are allocating this tuple. They will need a very good memory profiler :-)

**Comment by lpw25** [comment]
> I am concerned by the fact that this patch makes pattern-matching allocate a data structure transparently.

It is unfortunate but it is no worse than other operations which hide allocation (I'm looking at you currying). At least in this case I would expect a future version compiler to be able to optimise this allocation away in many cases.

> They will need a very good memory profiler :-)

I think that it is reasonable to expect beginners to need a memory profiler to fully optimise their program's memory performance, and I would expect an expert to already know that this operation allocates.

**Comment by alainfrisch** [comment]
When beginners start to worry about performances, they are no longer beginners.  Moreover, except for very tight loop, the cost of allocating is very small (and anyway, the allocation is required) and beginners are likely to introduce much worst sources of sub-optimal performance .

**Comment by xavierleroy** [comment]
I'm not a fan of this proposal.  It has been an early design decision in Caml Light then OCaml that constructors have an arity (0, 1, ..., N arguments), just like in term algebras.  This stands in contrast with the "0 or 1 argument" approach of early ML's and of SML.  I think the fact that constructors have arities should remain explicit to the OCaml programmer.

In perfect hindsight, Caml Light or OCaml should have switched to a curried syntax for constructor applications, like in Haskell, Coq or Agda.  The curried syntax is compatible with the N-ary nature of constructors.  The proposal in this PR is not compatible with the curried syntax.

**Comment by gasche** [comment]
I wouldn't want @xavierleroy to feel like he is the designed grumpy one, so here is another vote cast against this proposal for much of the same reasons. It comes from [an email](https://sympa.inria.fr/sympa/arc/caml-list/2015-11/msg00053.html) in [the related caml-list discussion](https://sympa.inria.fr/sympa/arc/caml-list/2015-11/msg00017.html).

> I'm personally not completely convinced by this feature -- Alain it "reduces bad
> surprises for beginners", but I suspect that adding more magic in this
> place could not actually help that much -- at least the current
> semantic model is simple.
> 
> Another problem with `C x` is the non-trivial performance implications of `C x -> x`
> which actually allocates. [editor note: no, the fact that other patterns are already broken in this regard is not such a convincing argument in favor of reproducing this dubious idea]
> 
> The problem would only get worse if we allowed
> 
> ```
> type t = { mutable x : int; mutable y : int }
> type u = Packed of { mutable x : int; mutable y : int }
> let pack x = Packed x
> ```
> 
> with an observable change in mutability semantics from the same code with
> 
> ```
> type u = Packed of t
> ```
> 
> (but Alain has not suggested adding this feature to decrease surprises
> (yet?), and luckily our tuples are immutable.)

Would it actually be that hard to switch to a currified syntax in a future OCaml version? (The last person to ask this was Alain, about immutable strings.) It is a purely file-local change, we could decide to add it as a compiler option, to become the default in a future OCaml version.

(I think the missing piece is a converter program that switches OCaml source from one syntax to the other without changing the rest of the code, so that the result could be reviewed and commited in a version-control system without generating unreasonably large commits.)

**Comment by c-cube** [comment]
@gasche if you change the syntax for this, please please please add `end` after if/match/try, it's more important imho

**Comment by alainfrisch** [comment]
I did not know that they were serious plans to switch to a currified syntax, and I don't see the benefits of it.  Partial application of n-ary constructors could be useful at times, but so does the ability to capture the arguments as tuple or build a constructor from a tuple.  What would justify such a big syntactic change?  Are there actual problems with the current syntax (except the confusion created by the use of tuple syntax, which is precisely the one I was trying to address)?

What are the benefits of having n-ary constructors instead of only constructors with arity 0 or 1?  Compactness of the representation is of course useful, and having the choice of representation based on the actual form of the type declaration is ok, but why should this "pollute" the expression language?  If we write down an untyped semantics of the core expression language, based on the current syntax, it's fine to consider that n-ary constructors actually take a single tuple argument.  Users can easily think in those terms, and the current restrictions seem rather ad hoc.

**Comment by bluddy** [comment]
I second @c-cube's request. I think it's time to build up a proposal for a revised ocaml syntax, with community input, fixing some of the retrospective errors of the past 20 years. We can decide what belongs in this revised syntax, and eventually implement a gradual switch-over program.

**Comment by gasche** [comment]
> I second @c-cube's request.

It is actually (1) an idea that is guaranteed to turn into a big mud puddle and never turn into anything applicable (hint: the "revised syntax" already exists, and almost nobody knows about it) and (2) rather off-topic in the present discussion, which is about one particular language feature proposed by Alain.

On the next first of April, we could propose a policy that for each feature request or language change proposed (directly or through comments) by a given user, they have to propose a bugfix or help review a proposed one. (@c-cube is in the clear for this one, thanks to #227 and various others.)

**Comment by xavierleroy** [comment]
Why wait for April 1st?  Also, make that 5 bug fixes / code reviews / community service activities per new feature or language change.  That's closer to what we need to go through the current backlog of pull requests and bug reports.

**Comment by alainfrisch** [comment]
Note that the present GPR is a direct response to a real Mantis ticket  :)

**Comment by alainfrisch** [comment]
I thought this proposal would be consensual (no counter argument was provided on the Mantis ticket).  Since it's clearly not the case, the ratio benefit / discussion cost seems way too low to me.  So I'm closing this pull request.

**Pull request closed without merging**
