### PR TITLE
BOOTSTRAP.adoc: mention an alternative way to test the bootstrap

### PR DESCRIPTION
**Pull request by shindere**

### CODE REVIEW

**Comment by xavierleroy** [comment]
The ./tools/ci/inria/bootstrap script is a fine test, but, with all due respect, I don't think it helps understanding what boostrapping is about, why and when it is necessary, and how to perform it --- which is what BOOTSTRAP.adoc is about.

**Comment by shindere** [comment]
Xavier Leroy (2018/06/07 10:28 -0700):
> The ./tools/ci/inria/bootstrap script is a fine test, but, with all
> due respect, I don't think it helps understanding what boostrapping is
> about, why and when it is necessary, and how to perform it --- which
> is what BOOTSTRAP.adoc is about.

Indeed, but it's not intended to explain, it's intended to provide a
quick way to test that a change has not broken the bootstrap procedure.

**Comment by xavierleroy** [comment]
One year and a few months later, I haven't changed my mind and probably @shindere hasn't either.  What do we do?

**Comment by shindere** [comment]
Xavier Leroy (2019/10/16 09:09 -0700):
> A lot of development and reviewing work by our finest youth went into
> this PR, so I'm sad to see it stalling and moving towards oblivion.
> On the other hand, that is a lot of code for a small benefit.  Can we
> decide to bring it to completion or forget about it completely?

Yeah, I confirm that I still can see a bit of usefulness in this
paragraph.

@xavierleroy Do you really think not providing this bit of information
is any better than providing it, as incomplete as you may find it?


To me there definitely is value in providing a way to automatically test
the bootstrap, especially given the fact that, as far as I know, none of
the current CI solutions that we use on PRs verifies that it has not
been broken. So, currently, this is verified only after a PR gets
merged, which means rather late.

Would there be a rewording or so that would make you like this PR more?

**Comment by shindere** [comment]
I just rebased this PR and, more importantly, rewrote the paragraph in a
hopefully clearer way.

**Review by gasche — APPROVED** [review]
Let's move forward. I rebased the PR and will merge if the CI agrees.

**Comment by shindere** [comment]
Thanks a lot, Gabriel.

**Comment by shindere** [comment]
Gabriel Scherer (2021/04/28 06:19 -0700):
> Merged #1819 into trunk.

Thanks again!

**Pull request merged**
