### PR TITLE
Fix wrong register typing in float (and boxed int) unboxing

### PR DESCRIPTION
**Pull request by trefis**
```
$ cat unbox_under_switch.ml
type _ t =
  | IO : int option t
  | F : float t

let bar : type a. a t -> float -> int -> a =
  fun t f i ->
    match t with
    | IO -> Some i
    | F -> f
[@@inline always]

let foo (t : float t) f i =
  let r = ref 0. in
  r := bar t f i

$ ocamlopt -c ./unbox_under_switch.ml
Fatal error: exception File "asmcomp/cmm.ml", line 83, characters 4-10: Assertion failed
Raised at file "asmcomp/cmm.ml", line 83, characters 4-16
Called from file "asmcomp/selectgen.ml", line 144, characters 13-51
Called from file "asmcomp/selectgen.ml", line 769, characters 18-42
Called from file "asmcomp/selectgen.ml", line 671, characters 18-32
Called from file "asmcomp/selectgen.ml", line 1102, characters 18-32
Called from file "asmcomp/selectgen.ml", line 1207, characters 2-16
Called from file "utils/misc.ml", line 28, characters 20-27
Re-raised at file "utils/misc.ml", line 28, characters 50-57
Called from file "asmcomp/asmgen.ml" (inlined), line 102, characters 15-18
Called from file "asmcomp/asmgen.ml", line 107, characters 2-75
Called from file "list.ml", line 106, characters 12-15
Called from file "utils/misc.ml", line 28, characters 20-27
Re-raised at file "utils/misc.ml", line 28, characters 50-57
Called from file "asmcomp/asmgen.ml" (inlined), line 102, characters 15-18
Called from file "asmcomp/asmgen.ml", line 180, characters 2-122
Called from file "asmcomp/asmgen.ml", line 155, characters 6-12
Re-raised at file "asmcomp/asmgen.ml", line 160, characters 6-15
Re-raised at file "asmcomp/asmgen.ml", line 171, characters 4-13
Called from file "driver/optcompile.ml" (inlined), line 67, characters 15-18
Called from file "driver/optcompile.ml", line 127, characters 16-303
Called from file "utils/misc.ml", line 28, characters 20-27
Re-raised at file "utils/misc.ml", line 28, characters 50-57
Called from file "driver/optcompile.ml" (inlined), line 67, characters 15-18
Called from file "driver/optcompile.ml", line 121, characters 10-626
Called from file "driver/optcompile.ml", line 139, characters 8-68
Re-raised at file "driver/optcompile.ml", line 144, characters 6-13
Called from file "utils/misc.ml", line 28, characters 20-27
Re-raised at file "utils/misc.ml", line 28, characters 50-57
Called from file "driver/compenv.ml", line 578, characters 6-35
Called from file "list.ml", line 106, characters 12-15
Called from file "driver/compenv.ml", line 654, characters 2-61
Called from file "driver/optmain.ml", line 256, characters 6-163
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Re-raised at file "parsing/location.ml", line 494, characters 14-25
Called from file "parsing/location.ml" (inlined), line 499, characters 31-61
Called from file "driver/optmain.ml", line 316, characters 6-37
Called from file "driver/optmain.ml", line 320, characters 2-9
```

This was initially noticed when building [Owl](https://github.com/owlbarn/owl/) with `-inline 20`, which caused [that call to Ctypes.(!@)](https://github.com/owlbarn/owl/blob/master/src/owl/lapacke/owl_lapacke.ml#L1385) to be inlined.

The bug is also present (and was noticed) on 4.07.

The fix was suggested by @lpw25.

### CODE REVIEW

**Comment by trefis** [comment]
I'd be in favor of backporting to the 4.07 branch and make an rc2.

**Comment by mshinwell** [comment]
Suggested by @lpw25 and yours truly.

The patch looks correct to me.

**Comment by trefis** [comment]
> Suggested by @lpw25 and yours truly.

Apologies  :)

**Comment by trefis** [comment]
check_typo was unhappy, I pushed a fix as well as a changelog entry; all the other tests passed.
Whoever approves should feel free to squash and merge.

**Comment by gasche** [comment]
I see the same header-ignoring logic in the third case of the `unbox_int` function. Should it be fixed as well?

**Comment by mshinwell** [comment]
Well spotted.  I think that code is wrong as well but won't actually cause a failure at present (because the types of registers used to hold unboxed integers and arbitrary values are compatible with respect to "join" in `Selectgen`).  However some work exists (#1192) which tightens up the register typing specifically with a view to catching this kind of error.  (I would still appreciate feedback on that work.)  If such change to the typing were merged, then the code in `unbox_int` could cause a compile-time failure, because the type of a register holding an unboxed integer (which cannot be scanned by the GC) would be incompatible with the type of a register holding an arbitrary value (corresponding to the `Some` case in the test case above).  So we should fix `unbox_int`, I think.

**Comment by mshinwell** [comment]
I've pushed a fix for `unbox_int`.  @lpw25 has reviewed this diff (`591718e`).

**Comment by mshinwell** [comment]
@chambart Could you please look at this?

**Comment by mshinwell** [comment]
@damiendoligez Do you want to backport this to 4.07?  It is needed to avoid a failure when compiling Owl, so I understand.

**Comment by chambart** [comment]
Looks good to me. You could be a bit more aggressive in that case: It would be sensible to produce some kind of trap (like the Uunreachable case).

**Comment by mshinwell** [comment]
@chambart Agreed.  However, I think that would involve adding cases that explicitly match the ill-typed cases, in addition to the well-typed cases that are picked out at the moment.  I'm not sure if it's worth doing this.  In the back of my mind I have that the next version of Flambda should have eliminated these branches (or replaced them with traps) by the time we get here.  How strongly do you feel about this?

**Comment by mshinwell** [comment]
@chambart Ping (we should make sure this goes into 4.08)

**Comment by trefis** [comment]
Note: unless @chambart speaks up, I will rebase and merge this on Tuesday.

**Comment by mshinwell** [comment]
@trefis Pierre is away for a while.  I think it's ok to merge this in its current form, and if needs be it can be improved upon later.

**Review by lpw25 — APPROVED** [review]

**Pull request merged**
