### PR TITLE
[webman] add button to display search help

### PR DESCRIPTION
**Pull request by sanette**
Concerning the search interface for the webmanual API:
https://ocaml.org/api/index.html

I propose to remove the weird 'mouse_over' display of the help tips, and replace it by a button to click.
The button is a "help" icon. Here you can see the **(?)** button on the right side:
icon-off

Here after you click:
icon_on

I'm not sure what is the best location to save that icon. It is currently in the `src` dir.

### CODE REVIEW

**Comment by gasche** [comment]
Nice idea! I think the second and third tips would also benefit from real-world example in addition to the syntax specification.

**Comment by sanette** [comment]
Here is a new proposition with examples

help_on2

**Comment by sanette** [comment]
We could also mention that the search widget can be accessed without clicking on anything, just hit TAB after page load.

**Comment by Octachron** [comment]
Do we need an icon or, would `ⓘ` be sufficient?

**Comment by sanette** [comment]
I don't have a strong opinion. Maybe some browsers don't have the full utf8 charset?

**Comment by sanette** [comment]
one could also produce a usual `i` or `?` with a CSS-rounded background

**Comment by Octachron** [comment]
We are already specifying a font for the post-processed version of the manual, aren't we? Then we can just use that font to be sure that we are using a font that contains `ⓘ`.

**Comment by sanette** [comment]
(done as you suggested)

Screenshot_20220128_195304

**Review by Octachron — APPROVED** [review]
The change looks good, but would you have the time to split the white space changes in the css from the main commits?

**Comment by sanette** [comment]
I have reverted the old white spaces in style.scss

**Comment by Octachron** [comment]
Thanks! 
(You could have kept the change in a separated commit)

**Pull request merged**
