### PR TITLE
fix several typos in comments

### PR DESCRIPTION
**Pull request by dhekir**

### CODE REVIEW

**Comment by gasche** [comment]
Thanks!

I am willing to merge this change eventually, but I wonder if there is a risk of increased conflicts with other patches (that would move comments around or delete affected code). I am leaning towards the "no reason not to merge" option, so my plan is to wait for a few days and then merge, unless someone expressed specific concerns.

**Comment by dra27** [comment]
I agree - merge to trunk just after 4.05 is branched, just to prevent last-minute angst on existing PRs!

Lovely set of corrections, thanks!

**Comment by Fourchaux** [comment]
@dhekir. Good job. 
I hope you would have more luck than me (for the merging of this kind of PR)
See [typos 817](https://github.com/ocaml/ocaml/pull/817/commits)

**Comment by gasche** [comment]
Thanks! Merged in trunk.

**Pull request merged**
