### PR TITLE
Fix GC free list accounting

### PR DESCRIPTION
**Pull request by dra27**
Split off from #1311 (see https://github.com/ocaml/ocaml/pull/1311#issuecomment-334766356)

### CODE REVIEW

**Review by damiendoligez — APPROVED** [review]
LGTM

**Comment by damiendoligez** [comment]
@dra27 could you rebase?

**Comment by dra27** [comment]
Done - definitely worth letting Travis complete as it re-enables the x86 tests.

**Comment by damiendoligez** [comment]
Travis is happy so I merged. Thanks!

**Pull request merged**
