### PR TITLE
In_channel.input_all: fix bug

### LINKED ISSUE #10976: In_channel.input_all limited to small inputs
It seems In_channel.input_all cannot read more than 65536 bytes, but I would have expected to be able to read much higher amounts:

$ ocamlopt --version
4.14.0+dev4-2022-01-20
$ cat h.ml
let () =
  ignore @@ In_channel.input_all stdin
$ ocamlopt -o h h.ml
$ head -c 65537 /dev/urandom | ./h
Fatal error: exception Invalid_argument("index out of bounds")

### PR DESCRIPTION
**Pull request by nojb**
Fixes #10976

### CODE REVIEW

**Comment by nojb** [comment]
To be cherry-picked to 4.14 cc @Octachron

**Review by Octachron — APPROVED** [review]
The fix is obviously correct.

**Comment by xavierleroy** [comment]
Apologies for being the killjoy who suggests to add a test, but: what about adding a test?  Use a pipe and two threads, one writing N bytes, the other `input_all` - ing them.

**Comment by nojb** [comment]
> Apologies for being the killjoy who suggests to add a test, but: what about adding a test? Use a pipe and two threads, one writing N bytes, the other `input_all` - ing them.

Good idea, will do.

**Comment by xavierleroy** [comment]
Lovely test, thank you !

**Comment by nojb** [comment]
`4.14` https://github.com/ocaml/ocaml/commit/98453445b47c4dd7720a7ee30958c58bfbc4a123

**Pull request merged**
