### PR TITLE
Clean-up some dead code in typecore.ml ("let separate = true in ...")

### PR DESCRIPTION
**Pull request by Armael**
Remove some dead code associated to some `let separate = true` in typecore.ml. These have been introduced in https://github.com/ocaml/ocaml/commit/0f85a64020890684bf703d08676449872fca57b3 (7 years ago) or https://github.com/ocaml/ocaml/commit/50ecb4 (as a bug-fix 2 years ago).

cc @garrigue ?

### CODE REVIEW

**Comment by garrigue** [comment]
Leave me some time to recall what it was about.

**Comment by trefis** [comment]
Removing dead code is good, but that particular instance had some (small) documentation value (at least with the comments that were attached).

I'd be happier if you removed the code but added a comment documenting what's going on, e.g. `(* Pretend separate=true *)`.

**Comment by Armael** [comment]
Good point. I rebased and implemented your suggestion.

**Review by trefis — APPROVED** [review]
LGTM.

**Comment by trefis** [comment]
I'm going to merge this as soon as the CIs come back green: if Jacques has more information to add than "Pretend separate = true" he can always do so :)

**Pull request merged**
