### PR TITLE
make ocamlnat build again

### PR DESCRIPTION
**Pull request by trefis**
This patch is a rebase of https://github.com/diml/ocaml/commit/0e78f60f663aebbb473ff8060d0eafce57aa1b6f on top of trunk.

### CODE REVIEW

**Comment by gasche** [comment]
There are some weird things in the patch (remove_directory, gen_printer, mod_use...). Do you need other things than the change in `Makefile{,.shared}`?

**Comment by trefis** [comment]
> There are some weird things in the patch (remove_directory, gen_printer, mod_use...)

I don't know the details but I'm guessing @diml needed these for utop.

> Do you need other things than the change in Makefile{,.shared}

Yes, the Makefile needs fixing. I'm working on it.

**Comment by trefis** [comment]
I fixed the Makefile.

Also, apparently I can't properly: no I don't think I need any more changes.
Someone more skilled than me in the arcane art of Makefile writing could update the makefiles to build ocamlnat along ocamlopt.opt when natdynlink is available (at the moment one still needs to call `make ocamlnat` manually), but it is not necessary.

**Comment by ghost** [comment]
@gasche, the `opttopfoo.ml` files haven't been updated in a while and they diverged from their `topfoo.ml` counterpart. The patch simply brings the native toplevel files up to date.

**Comment by gasche** [comment]
Ah, the horror.

When are we going to get stronger leverage to motivate someone to factorize these files than _before_ merging such a pull request? @trefis or @diml , have you looked at what it would take to reduce the redundancy there?

**Comment by ghost** [comment]
I wanted to look at this, and especially use the same modules in both case. To make it easier to build custom toplevels and such that work in both byte-code and native modes. But I didn't find the time yet.

**Comment by trefis** [comment]
I'll give it a go.

**Comment by trefis** [comment]
Here is a first attempt (only trying to factorize toploop, no effort was spent on topdirs yet).

I am unsure about the correctness of some parts of the patch, I'll add some comments inline and let you guys check.

**Comment by gasche** [comment]
I don't know much about toploop (if I remember correctly, @alainfrisch is the expert on the native toplevel). I won't look at what is done above before the week-end, and even then I probably won't do a full review. Currently ocamlnat is broken, so you can hardly make it worse and I am ready to accept any change blindfolded if you have tested them on your end. On the other hand, it is important of course to not introduce regressions in the bytecode toplevel during the refactoring. I would be ready to merge your changes on trust, provided we have your word that the refactoring preserves the bytecode-toplevel semantics.

**Comment by gasche** [comment]
So in fact I had a quick look at the patch. There is nothing that seems wrong, and I think it is a good first step, but that we could also go further.

Right now you ( @trefis ) gutted out the code that was obviously the same on both sides, relegated to a `Toploop_shared` module that (1) has no .mli file or proper interfance and (2) is include-d in `Toploop` and `Opttoploop` instead of opened, because it define some of the values exported in their .mli files. This is a good approach to have a minimally invasive change yet a nice factorization; and it also makes it explicit what the dependencies betwene the factorized and non-factorized code are (I noticed `set_eval_path` and  `set_execute_phrase`).

However, the post-patch code structure does not feel quite right. We still have two independent toplevels, defined by `Xtoploop + Xtopdirs` for `X` in `{,opt}`, that happen to conveniently share some auxiliary definitions. What I would rather expect (if I was asked to guess what a system with a bytecode and native toplevel built from scratch would look like) is to have two "low level toplevel bits", eg. `bytetopcore.ml` and `opttopcore.ml`, providing the nitty-gritty details that depend on byte/opt, and over it a single "user interface" (toploop and topdirs) that call functions in either modules. (Not unlike the way backtrace handling was recently refactorized by Frédéric). I think the way you do dependency injection with `set_foo` functions in your patch may be a sign that this "reversed" organization is the more natural one.

That said, (1) I only had a quick look at the code and you know it better, so maybe there is an obstacle to this approach that I haven't seen and (2) the evil is in the details, in particular if we had a user interface part that referred to _both_ the byte and native core modules (`if is_native then ... else ...`) then we may get into trouble when compiling on an architecture that does not support native compilation -- and trying to build two separate executables by linking the user interface modules with two core modules with the same module name is not going to be build system fun.

In any case, I think (my coarse view of) the result of your proposed change is already an improvement over the current state, so I would be inclined to merge it (provided someone, for example you, checks that the refactoring preserves bytecode semantics) even if this grand plan does not come to fruition -- it will be easier to attempt on top of your patch than the current state anyway.

**Comment by mshinwell** [comment]
@chambart We need to figure out how to make this work for flambda.  We don't have [Translmod.nat_toplevel_name] any more.

**Comment by alainfrisch** [comment]
ocamlnat was initially an unsupported quick hack which tried to be as un-invasive as possible on the "supported" code base, hence the absence of code factorization between bytecode and native versions.  I originally thought that nobody would be really interested in a native toplevel, but I was later proved wrong, with people insisting to get ocamlnat working with newer versions.

Before putting too much energy into cleaning up the code, one should perhaps have a discussion about changing the status of ocamlnat.  It would be interesting to understand why people are interested in a native toplevel, and then decide to make it a supported tool (or not).  Supported doesn't mean it has to be made working on all available platforms; but at least it would be compiled by default on major platforms where it is supposed to work, so that we can detect early when its compilation is broken.

Depending on the intended use cases for ocamlnat, it might also be worth discussing the resurrection of the work by B. Meurer to reduce latency: (1) using a faster register allocator (of the linear scan family), (2) avoiding external compilation and dlopen by generating machine code in memory directly.  Note that for (2), at least for Intel backends, this is somehow easier now that emit.ml produces an AST of the assembly (and OCamlPro has developed a direct machine code generator based on it, which LexiFi uses as its main backend, which proves it is quite robust).

**Comment by ghost** [comment]
These are our motivations for resurrecting the native toplevel at Jane Street:
- Internally, some of our libraries don't work well or even not at all in byte-code. We have no use for it, so it's better if we don't need to spend time making them work in byte-code only for the toplevel
- People often build toplevels during development, and it's better if we can reuse the same compiled object files as the one used to build other things. Even if byte-compilation is fast, when there is a lot of it it's still added compilation time
- `-short-paths` is dreadfully slow. We enable it by default and some of the toplevels we build have access to lots of libraries. It's still slow in native code but it's much better than in byte-code

So we'd be interested in having ocamlnat supported, and since we use it internally we can help maintain it.

**Comment by gasche** [comment]
I would like to merge @trefis 's work (at least the resurrection work; for the factorization, I'm a bit torn as I'm not sure the current state is a satisfying final state), but my understanding is that merging it now would make flambda's life harder. I would rather thus wait for flambda to land in trunk, and then merge whatever proposal @trefis has to make ocamlnat work again.

(I'm thinking of closing this PR to keep a relevant list of open issues, based on the prediction that the post-flambda patch may require more work than just rebasing this one. No firm decision yet, so please complain if for whatever reason closing this PR would be a mistake.)

**Comment by trefis** [comment]
I'm fine with that plan (trying to merge after flambda) but rebasing this patch will indeed not be enough.
So you can close this PR if you wish and I will make a new one in due time.

**Comment by gasche** [comment]
The bean-counters got me, I like to close pull requests now. Thanks for the work anyway, and looking forward to hear of the post-flambda rebirth.

**Pull request closed without merging**
