### PR TITLE
Remove unused primitives

### PR DESCRIPTION
**Pull request by dra27**
`caml_add_debug_info` and `caml_remove_debug_info` had their references in `Meta` removed in #1723, but the primitives remained in the primitives table since the functions are marked `CAMLprim`.

This PR removes them from the primitives table (with corresponding bootstrap)

### CODE REVIEW

**Review by xavierleroy — COMMENTED** [review]
Looks good to me.  However, since  it requires a bootstrap, and since other primitives may be removed later as part of @dra27's cleaning, I'd rather wait until we have a full list of primitives to be removed.  Those could be added to this PR just by changing the title (Remove unused primitives).

**Comment by dra27** [comment]
Hah - these two were spotted while checking things in headers, but your point made me do some more detailed checking.

- `caml_setup_afl` is emitted in native code with AFL instrumentation... it's not actually a primitive. Further, I've removed the "not available" version, as you shouldn't be attempting to link code generated by afl-enabled ocamlopt with a non-afl-enabled libasmrun. `caml_reset_afl_instrumentation` is different since that truly is a primitive, so you always want it.
- There are several array functions which ceased to be used as primitives when `-no-flat-float-array` was added. I think we can safely go a step further and hide them completely

I did a GitHub code search for these and couldn't find evidence of anyone doing silly things with them! I don't think there are any others - `caml_set_string` is still present in the runtime, but deprecated and `caml_sys_get_argv` is now no longer used, but is used in a small number of external places (and it still works correctly).

**Comment by xavierleroy** [comment]
The array primitives are mysterious to me, but I trust your analysis.  Let's wait a bit more in case other "dead" primitives are found, then we'll merge with a single bootstrap.

**Comment by dra27** [comment]
Rebased and bootstrap redone. Is this still wanted for 4.12, though, @Octachron?

**Comment by xavierleroy** [comment]
Let me merge in trunk while the bootstrap is still fresh.  Maybe we don't need to have this PR in 4.12, this will save one bootstrap on that branch, but I don't feel strongly either way and  @Octachron will make the final call.

**Comment by shindere** [comment]
Current trunk fails to build when configured with
`--disable-flat-float-array`:

The error message is:

```
gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DCAMLDLLIMPORT=  -o array.b.o array.c
array.c:228:14: error: ‘caml_array_unsafe_set_float’ defined but not used [-Werror=unused-function]
  228 | static value caml_array_unsafe_set_float(value array,value index,value newval)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
array.c:168:14: error: ‘caml_array_unsafe_get_float’ defined but not used [-Werror=unused-function]
  168 | static value caml_array_unsafe_get_float(value array, value index)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
array.c:127:14: error: ‘caml_array_set_float’ defined but not used [-Werror=unused-function]
  127 | static value caml_array_set_float(value array, value index, value newval)
      |              ^~~~~~~~~~~~~~~~~~~~
array.c:61:14: error: ‘caml_array_get_float’ defined but not used [-Werror=unused-function]
   61 | static value caml_array_get_float(value array, value index)
      |              ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

```

Bisecting seems to show that the failure is due to this PR and in
particular commit aef138881fad4e7be0fc041d9928d895c186565f

**Comment by dra27** [comment]
Thanks, @shindere - there's a fix in #10075 ready to go in

**Comment by shindere** [comment]
David Allsopp (2020/12/07 12:05 -0800):
> Thanks, @shindere - there's a fix in #10075 ready to go in

Ah, sorry, thanks!

**Pull request merged**
