### PR TITLE
Less verbose logs from `make`

### PR DESCRIPTION
**Pull request by xavierleroy**
It's still time to make small wishes for 2022.  One of mine is less verbose build logs.

The output of `make` looks almost decent when each command fits on one line, as Stuart Feldman envisioned it, and looks like complete gobbledygook otherwise.  Unfortunately, OCaml, like all serious projects, has very long build commands, what with all these `-I` and `-w` options.

But there's a trick!  The Makefile can run commands silently  after printing a short meaningful summary:
```
    @echo "Linking foo"
    @gcc bla bla bla bla bla -o foo
```
I think the Linux kernel build does this (or did it 25 years ago when I last built my own kernels).  I learned this trick from Coq, and use it with pleasure in CompCert.

This draft PR applies this trick to (parts of most of) the Makefiles of OCaml.  For example, it prints
```OCAMLC lambda/switch.ml```
instead of
```./boot/ocamlrun ./boot/ocamlc -nostdlib -I ./boot -use-prims runtime/primitives -g -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48 -warn-error +a -bin-annot -strict-formats -I lambda -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I driver -I toplevel -I tools -c lambda/switch.ml```
and
```CC runtime/addrmap.c -> runtime/addrmap.b.o```
instead of
```gcc -c -O2 -fno-strict-aliasing -fwrapv -pthread -g -Wall -Werror -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections  -I./runtime  -D_FILE_OFFSET_BITS=64  -DCAMLDLLIMPORT= -DIN_CAML_RUNTIME  -o runtime/addrmap.b.o runtime/addrmap.c```

The general format is `COMMAND inputfile` if there's no ambiguity about the output file, or `COMMAND inputfile -> outputfile` otherwise. The format is open to discussions; my only demand is that every output fits on a single line.

 I attach a full build log for reference: [log4.gz](https://github.com/ocaml/ocaml/files/10325615/log4.gz)

Currently, only the generic compile rules are modified; other rules such as linking steps still print in full.   And some Makefiles remain to be adjusted.  Yet, the log file is already 3 times shorter (340 k instead of 1M).  

As usual, I'll now switch to Q&A mode to speed up discussions.

Q: But if a command fails, I may need to see it in full!

A: Most of the time, we look at the error messages from the compiler, not at the command itself.  But in the rare case where you need to see the command in full, there's a simple trick.  After the failure, just do `make -n | head`.  With the `-n` option, commands are printed in full even when preceded by `@`.  If you're in a sequential build, the command that failed is the first command to re-execute, so it should be the first line of the `make -n` output.  If you're in a parallel build, you can reproduce the failure with `make`, then see the command with `make -n | head`.

It would also possible to have a make variable that controls whether to abbreviate commands or leave them printed in full.   But I don't know how to do this without some duplication and extra `if...else...endif` in the Makefiles.

Q: Why do you care? Do you really read the build logs?  

A: I too often have to search through build logs from CI, yes.  Smaller logs will be a relief for all our CI systems.  Apart from this, the fast scrolling of huge build commands in a terminal or Emacs buffer does make me uncomfortable, indeed.

### CODE REVIEW

**Comment by xavierleroy** [comment]
@shindere needs to know about this proposal.

**Comment by shindere** [comment]
Yes, thanks!

In short: I am fully in favour of this proposal. Actually, I had the
smae idea, with the very same source of inspiration (Linux Kernel),
but my plan was to propose it after the makefiles had been merged
to minimize the number of changes.

I am supposed to be on vacation until January 9th and I would like to be
given an opportunity to review this before it gets merged so can this
please wait until I'm back?

Thanks!

**Comment by gasche** [comment]
Two questions:

1. The "how to see the full command for reproducing a failure?" question is important. You answer in this PR, but could you put the answer in HACKING.adoc as well to make it easy to find again in the future?
2. This approach doubles the number of "commands" run in each build, is there a noticeable slowdown on Windows? (This is probably a question for @nojb or @dra27.)

**Comment by nojb** [comment]
I am generally in favor, this makes the logs much more readable.

> The format is open to discussions; my only demand is that every output fits on a single line.

At the moment, `OCAMLC` is used as a prefix both for `ocamlc` and `ocamlc.opt` (and similarly for `ocamlopt`). I think that showing `OCAMLC.OPT` for the second one would be slightly better. Is this doable without complicating things too much?

> is there a noticeable slowdown on Windows?

I did a quick benchmark of `make -j10`, starting from a clean tree, with the `mingw64` port, which shows a slowdown of ~7%. This is unfortunate, but I think it is still tolerable.

**trunk**

```
real    5m45.928s
user    8m46.635s
sys     5m49.594s
```

**This PR**

```
real    6m11.228s
user    9m23.653s
sys     7m9.884s
```

**Comment by dra27** [comment]
I’m also for this! For the slowdown, I think it may be possible to avoid the call to `echo` by using `$(info`?

**Comment by xavierleroy** [comment]
I just pushed a version that uses `$(info ...)` instead of `@echo "..."`, it should run faster.  Thanks a lot @dra27 for the suggestion!

@shindere : glad you like the idea.  My next wish is a less verbose output from ocamltest...

@nojb: the code that sets OCAMLC and OCAMLOPT could also set OCAMLC_NAME and OCAMLOPT_NAME variables (e.g. to `OCAMLC` or `OCAMLC.OPT`), which could then be used when printing the command.

**Comment by shindere** [comment]
Xavier Leroy (2023/01/02 00:54 -0800):
> I just pushed a version that uses `$(info ...)` instead of ***@***.*** "..."`, it should run faster.  Thanks a lot @dra27 for the suggestion!
> 
> @shindere : glad you like the idea.  My next wish is a less verbose
> output from ocamltest...

You mean all the time, or you mean when run by the CI? In the latter case
I have a branch that suppresses the output of ocamltest whn run by the
testsuite to just print the report, because I had the understanding that
this was what you were actually looking for. It had a bug which I never
understood so I never finished but if you like the idea I can definitely
give it one more try next week.

> @nojb: the code that sets OCAMLC and OCAMLOPT could also set
> OCAMLC_NAME and OCAMLOPT_NAME variables (e.g. to `OCAMLC` or
> `OCAMLC.OPT`), which could then be used when printing the command.

That looks cool. The variable could even be called `COMPILER_NAME` so
that the same code could be used for printing, no matter which compiler.
One other possibility would be to distinguish, in this variable,
`boot/ocamlc` from `./ocamlc` to make it clear whether it's the boot
compiler which is used, or not.

One further generalisation step would be to use e.g. `COMMAND`,
`INPUT_FILE` and `OUTPUT_FILE`, although the two last ones could also be
just `$<` and `$@` and in this case we would use the same display code
for all the commmands, which would make it easier to get a
by-construction guarantee that the printing format is consistent accross
all the invoked commands.

**Comment by nojb** [comment]
> I just pushed a version that uses `$(info ...)` instead of `@echo "..."`, it should run faster. Thanks a lot @dra27 for the suggestion!

I played around with the PR and did what seems to me like some improvements (as well as adapting more of the build system), see https://github.com/xavierleroy/ocaml/pull/1.

**Comment by xavierleroy** [comment]
Thanks @nojb for the nice improvements, they are now merged in this PR.

Given that the initial feedback is positive and that it's starting to look really good, I'm removing the "Draft" status to show that this PR is ready for review.  We will wait for @shindere's review.

**Comment by xavierleroy** [comment]
> > My next wish is a less verbose output from ocamltest...

> You mean all the time, or you mean when run by the CI?

I mean when run by `make -C testsuite`.  But I also think that the default output format for `ocamltest` should be a single line:
```
   name-of-test   (passed|skipped|failed)  [time taken]
```
and the current output should be explicitly requested with a `-v` option or something.

**Comment by avsm** [comment]
I don't have a development environment handy to test this at the moment, but if there are a lot of generated files then you may be able to speedup the Windows build by using the GNU Make [`$(file )`](https://www.gnu.org/software/make/manual/html_node/File-Function.html) function to write outputs instead of indirecting the `V_GEN` calls through an echo/cat and shell redirect.

**Comment by dra27** [comment]
There aren't too many generated files, fortunately (at least in the main build). Alas, `$(file ...)` is GNU make 4.0, so it's not at the moment available to us without considerable care to avoid it on macOS.

**Comment by shindere** [comment]
Just started to review this. Many thanks for the cool work. The result
looks much better than before, obviously.

Quick question: how important is the vertical alignment of filenames
to you (poor ;-) ) sighted people? I have two reasons to ask this question.

 1. In braille it makes the text less compact than it could be, so I loose a little bit of effiency in reading.
 2. More importantly: it may be nice at some point to e.g. distinguish 
BOOT_OCAMLC from OCAMLC in the printed messages and it may then become
harder to maintain the vertical alignment, except of course if it is made
big enough but still, all this means that if we have vertical alignment
we will have to maintain it. Is the visual gain really worth it?
It's a genuine question.

Am I correct that, in its present state, the PR does not provide any way to
see the details of a command?

In the implementation I have in mind, we would have a `V` variable to
control the verbosity. Basically, `make V=0` would be equivalent to `make -s` and would
let one verify that the build does not yield any unexpected message (the
output of `Make V=0` should be empty), `make V=1` would print the nice new
messages and `make V=2` would print the commands in full details as before.

Is the idea okay and, if yes, shall I try to add it to the present PR or rather to
a separate one? If it's in a separate one then likely I'll wait until all
the makefiles have been merge because that will make the work easier. But in
workin on the makefiles it would be useful to have a way to see the
commands.

How about the `mkdir` command? Shoudln't it get a nice output, too?

**Comment by xavierleroy** [comment]
> Quick question: how important is the vertical alignment of filenames to you (poor ;-) ) sighted people?

Not important to me.  

> How about the mkdir command? Shoudln't it get a nice output, too?

I think there will always be "raw" commands that occur too rarely to get a special output.  It's OK, especially if they fit on one line, which is the case for `mkdir` commands.  See also `ln` commands for which @nojb removed the nice output recently, as it was problematic (I guess).

> Am I correct that, in its present state, the PR does not provide any way to
> see the details of a command?

Correct.  But there's always `make -n`.

> In the implementation I have in mind, we would have a V variable to
> control the verbosity. Basically, make V=0 would be equivalent to make -s and would
> let one verify that the build does not yield any unexpected message (the
> output of Make V=0 should be empty), make V=1 would print the nice new
> messages and make V=2 would print the commands in full details as before.

Because there will always be "raw" commands, your "V=0" mode will not suppress all output, and it's better to rely on `make -s`.  There's something similar to your "V=1" and "V=2" in the Coq makefiles, if I remember correctly.

**Comment by nojb** [comment]
> See also `ln` commands for which @nojb removed the nice output recently, as it was problematic (I guess).

It wasn't problematic, but we were doing it for `ln` and not for `mkdir`, `cp`, etc; we should do it either for all of them or none of them, and it wasn't clear if it was worth doing it for these commands by the reasons mentioned.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2023/01/11 09:14 -0800):
> > See also `ln` commands for which @nojb removed the nice output recently, as it was problematic (I guess).
> 
> It wasn't problematic, but we were doing it for `ln` and not for
> `mkdir`, `cp`, etc; we should do it either for all of them or none of
> them, and it wasn't clear if it was worth doing it for these commands
> by the reasons mentioned.

To me, it wouldn't hurt to do it for such commands and would make things
clearer. It's not a lot of noise and still it can be precious, whereas
not having it can be problematic.

**Comment by shindere** [comment]
Xavier Leroy (2023/01/11 09:03 -0800):
> > Quick question: how important is the vertical alignment of filenames to you (poor ;-) ) sighted people?
> 
> Not important to me.

OK so if this is not retained in future changes you won't complain,
IIUC.

> > How about the mkdir command? Shoudln't it get a nice output, too?
> 
> I think there will always be "raw" commands that occur too rarely to
> get a special output.  It's OK, especially if they fit on one line,
> which is the case for `mkdir` commands.  See also `ln` commands for
> which @nojb removed the nice output recently, as it was problematic (I
> guess).

My preference would be to have something homogenous but it does not need
to happen in this PR.

> > Am I correct that, in its present state, the PR does not provide any way to
> > see the details of a command?
> 
> Correct.  But there's always `make -n`.

Will that really produce the very same output as we got before? I'm
indoubt but again, no problem, I'll reivew the current PR as it is and
submit adjustements once it's merged.

> > In the implementation I have in mind, we would have a V variable to
> > control the verbosity. Basically, make V=0 would be equivalent to make -s and would
> > let one verify that the build does not yield any unexpected message (the
> > output of Make V=0 should be empty), make V=1 would print the nice new
> > messages and make V=2 would print the commands in full details as before.
> 
> Because there will always be "raw" commands,

I don't see this as a fatality. I do think it's possible to have control
over all the commands, especially after the refactoring.



> your "V=0" mode will not suppress all output,

Let's bet. :-)

> and it's better to rely on `make -s`.

Incidnetally, here is the output of `make -s` on latest trunk:

```
File "../../stdlib/stdlib.mli", line 1500, characters 15-28:
1500 | module Stack = Stdlib__Stack
                      ^^^^^^^^^^^^^
Alert unsynchronized_accesses: module Stdlib__Stack
Unsynchronized accesses to stacks are a programming error.
```

> There's something similar to your "V=1" and "V=2" in the Coq
> makefiles, if I remember correctly.

I am pretty sure all of us have the same source of inspiration, namely
the Linux kernel, so what you write does not surprise me so much.

**Comment by shindere** [comment]
Xavier Leroy (2022/12/30 09:23 -0800):
> Q: But if a command fails, I may need to see it in full!
>
> A: Most of the time, we look at the error messages from the compiler,
> not at the command itself.  But in the rare case where you need to see
> the command in full, there&#39;s a simple trick.  After the failure,
> just do `make -n | head`.  With the `-n` option, commands are printed
> in full even when preceded by `@`.  If you&#39;re in a sequential
> build, the command that failed is the first command to do again, so it
> should be the first line of the `make -n` output.  If you&#39;re in a
> parallel build, you can reproduce the failure with `make`, then see
> the command with `make -n | head`.

The limit to this trick is that `-n` is dry-run so the commands are
indeed printed, but not executed. So it may indeed work to run `make -n`
just after having run `make`, but oneshould keep in mind that this can
nnot be generalized, as sometimes executing a command really makes a
difference for the rest of the build and which commands will be executed
afterwards.

> It would also possible to have a make variable that controls whether
> to abbreviate commands or leave them printed in full.   But I
> don&#39;t know how to do this without some duplication and extra
> `if...else...endif` in the Makefiles.

This has been implemented at the top of the `less-verbose-logs` branch
of `shindere/ocaml`: `make V=1` prints the commands the new way
(default) whereas `make V=2` prints the commands as they were printed
before this PR. Could this please be cherry-picked into this PR?

With the above mentionned PR, I was able to get a diff of build logs
before and after the PR (see attached - [buildlog-patch.patch](https://github.com/ocaml/ocaml/files/10424363/buildlog-patch.patch))

**Comment by shindere** [comment]
Gabriel Scherer (2022/12/30 13:21 -0800):
> 1. The "how to see the full command for reproducing a failure?"
> question is important. You answer in this PR, but could you put the
> answer in HACKING.adoc as well to make it easy to find again in the
> future?

This point from @gasche has not been addressed yet and, at the moment,
thePR does not have a Changes entry.

**Review by shindere — APPROVED** [review]

**Comment by xavierleroy** [comment]
> This has been implemented at the top of the `less-verbose-logs` branch
> of `shindere/ocaml`: `make V=1` prints the commands the new way
> (default) whereas `make V=2` prints the commands as they were printed
> before this PR. 

I'm a computer scientist: I don't know this "2" thing you're using, only "0" and "1" :-)

More seriously, according to Stackoverflow wisdom,  CMake, uses `make VERBOSE=1` and GNU autotools `make V=1` to select verbose output.  I strongly suggest we use one of these two conventions.

**Comment by shindere** [comment]
Xavier Leroy (2023/01/16 06:19 -0800):
> > This has been implemented at the top of the `less-verbose-logs` branch
> > of `shindere/ocaml`: `make V=1` prints the commands the new way
> > (default) whereas `make V=2` prints the commands as they were printed
> > before this PR.
>
> I'm a computer scientist: I don't know this "2" thing you're using,
> only "0" and "1" :-)

I'll tell you about the wonders of Peano numbers next time we have a
coffee together. You'll see, you're gonna be amazed!

> More seriously, according to Stackoverflow wisdom,  CMake, uses `make
> VERBOSE=1` and GNU autotools `make V=1` to select verbose output.  I
> strongly suggest we use one of these two conventions.

Here is the relevant bit of output of Linux's `make help`:

```
  make V=0|1 [targets] 0 => quiet build (default), 1 => verbose build
  make V=2   [targets] 2 => give reason for rebuild of target
```

My understanding of this is that it gives a point to each of us. One
point to you because it distinguishes `V=0` from `make -s`. One point
for me because they do use more than two values.

I can just say that what I proposed seems the more coherent to me: it
would make sense to me that `V=0` is an equivalent to `make -s` and it
is actually very easy to implement by modifying `MAKEFLAGS`; `V=1` what
we have and then we have 2 for all commands, why not 3 to mean `run the
commands in verbose mode`.



It may be interesting to hear the opinions of others. Finally between V
and VERBOSE I'd go for the first one which is more concise. And please,
fellfree to modify the commit directly and to take the authorship.

**Comment by gasche** [comment]
> It may be interesting to hear the opinions of others.

My opinion: I haven't looked at this and don't plan to, but it looks like there is a general consensus in favor of the change as, broadly, originally proposed, and less consensus on the proposed addition of an explicit verbosity setting. My recommendation would be to first merge the change at the scope of the original proposal, and split the verbosity setting patches to a follow-up PR where you can discuss more if you want.

(Re. V versus VERBOSE: in general I'm in favor of longer options because they are nicer on the reader, and I read more than I write. This being said, I guess I'm the sort of people who does not mind seeing long commands in the build logs.)

**Comment by damiendoligez** [comment]
For the flag, my vote goes to `V` and I see a good use for relative integers here:
`make V=-1` for a completely silent build
`make V=0` (default) for printing abbreviated commands
`make V=1` for printing full commands

**Comment by shindere** [comment]
Wouldn't it be nice, finally, to use floating pointnumbers? That way we
would have a main verbosity number which would be the integral part, and
then we could use the numbers after the dot to encode the verbosity of
different components and subcommands, which would give us all the
control and flexibility we can drema of.

Plus, it would be future proof because, if real numbers turn out to not
be enough to encode a verbosity setting, then we coudl very easily say
that the numbers we use are actually complex numbers.

**Comment by dra27** [comment]
> Re. V versus VERBOSE: in general I'm in favor of longer options because they are nicer on the reader, and I read more than I write

There’s no major reason not to have both? I keep meaning to add that in testsuite/Makefile for `KEEP_TEST_DIR_ON_SUCCESS` as my usage of it always begins with `grep KEEP Makefile` to remind me what the full name of the variable is…

**Comment by shindere** [comment]
David Allsopp (2023/01/16 08:46 -0800):
> > Re. V versus VERBOSE: in general I'm in favor of longer options because they are nicer on the reader, and I read more than I write
>
> There’s no major reason not to have both? I keep meaning to add that
> in testsuite/Makefile for `KEEP_TEST_DIR_ON_SUCCESS` as my usage of it
> always begins with `grep KEEP Makefile` to remind me what the full
> name of the variable is…

I really like the good intentions behind the proposal. No sarcasm
intended, I do like that. I'm just not sure whether it's a wise way to
go because it will likely create code duplication and/or questions about
which varialbe has the priority if they happen to contradict each
other...

**Comment by nojb** [comment]
I rebased this patch on top of `trunk`, and:

- Removed the extra whitespace between the command name and the target name (asked in https://github.com/ocaml/ocaml/pull/11844#issuecomment-1375788541);
- Added a flag `V=0` (default) and `V=1` to control whether to use the new shorthand or the full command lines. Other variants can be added later; and
- Added a `Changes` entry.

Planning to merge tomorrow...

**Comment by shindere** [comment]
Many thanks. I just find it very odd that `V=0` means something
different from silence but AIUI I'm the only one seeing things that way.

**Comment by xavierleroy** [comment]
> Planning to merge tomorrow...

Thanks!

**Pull request merged**
