### PR TITLE
MPR#7373: fix ocamlmklib when FlexDLL bootstrapped (4.05 version)

### PR DESCRIPTION
**Pull request by dra27**
4.05 version of #1023

### CODE REVIEW

**Comment by dra27** [comment]
This should also be mergeable on trunk (there are a lot of test cases, so I ran it against 4.05 as the one I preferred not to risk breaking!)

**Comment by damiendoligez** [comment]
As you mention `Makefile.nt` in `Changes`, I guess this will interfere with the great makefile unification? @shindere can check?

**Comment by shindere** [comment]
Coming into this a bit late, sorry.

-           -e 's|%%FLEXLINK_FLAGS%%|$(FLEXLINK_FLAGS)|' \
+           -e 's|%%FLEXLINK_FLAGS%%|$(subst \,\\,$(FLEXLINK_FLAGS))|' \

Isn't there another way to allow backslashes in FLEXLINK_FLAGS?

I am asking because before this, all the sed expressions were regular
and that was convenient in the perspective of the autoconf-based
substitution. This patch may not be that easy to translate into
autoconf. Perhaps the backslashes could be protected or wold it help to
replace the single quotes by double quotes in the sed expressions?

Same question for the three other variables.

+       mkdir -p "$(INSTALL_LIBDIR)/flexdll"

Could you please use $(MKDIR) ?

Also, it may be cleaner to use a variable like FLEXDIR_INSTALL or so to
represent "$(INSTALL_LIBDIR)/flexdll", which appears several times.

Unrelated question, to everybody actually: is it intended to have
ocamlmklibconfig.ml rather than relying on utils/config.ml?

About the let flexdll_dirs function: would it make sense to use
Filename.quote rather than doing the quoting by hand?

In utils/config.mlp, is it on purpose that flexdll_dirs's value is not
printed?

Shouldn't the configure script echo an empty definition of FLEXDLL_DIR
to config/Makefile?

Regarding Changes: now that the makefiles have been merged it would
indeed be better to stop mentionning Makefile.nt, thanks a lot for
having spotted this, @damiendoligez.

In the "flexdll: flexdll/Makefile flexlink" rule: is there a reason for
cd-ing to the flexdll directory rather than using $(MAKE) -C as in the
rest of the Makefile?

And about the most recent commit: in the long run, would it make sense /
simplify things to ensure that camlheader is compiled early enough? That
would avoid this trick at install-time...

**Comment by dra27** [comment]
@damiendoligez - the Changes entry remains in 4.04.1 (since that's where we introduce it) so it refers to Makefile.nt. The patch is correctly rebased (and tested!) only to alter Makefile

**Comment by dra27** [comment]
@shindere - no problem, thanks for the comments!

Backslashes. Perhaps this is being looked at the wrong way: *any* string being inserted into config.mlp could contain backslashes so an autoconf approach would be to uniformly escape everything? It's just to ensure that you don't get `"C:\OCaml\FlexDLL"` in config.ml.

$(MKDIR) - yes, of course... I hadn't spotted that! Similarly, FLEXDLL_INSTALL is a good idea.

I'm not sure why ocamlmklibconfig.ml and config.ml ended up - I would certainly agree that merging would be more sensible, but perhaps that's not for here.

For flexdll_dirs, I was concerned not to draw in any other quoting: it's just to ensure that you get -L"C:\Program Files\OCaml\FlexDLL". That assumption may be wrong, but I felt Filename.quote could do things I didn't want.

I did intentionally not print flexdll_dirs value in config.mlp, yes: I don't think it's an interesting value (the fact it is set can be easily seen by using -verbose to see commands being run). If it does seem interesting, then I could add it, but I wasn't really sure why you'd use it. Directories added by -thread aren't printed either.

FLEXDLL_DIR is configured for all platforms at the top of Makefile. I agree that once the Windows ports are using configure too, FLEXDLL_DIR should put into config/Makefile by configure but for now I think it's correct.

Assuming things haven't changed, the fix is approved for 4.04.1 so this is a forward-port of the fix - so the Changes entry refers to 4.04.1 (unless we want to repeat the entry in 4.05.0 - it's obviously the first time we release with two branches at once)

There's no reason not to use $(MAKE) -C - I think it's just that when I originally wrote this, it's before you'd cleaned it all up and the cd version was more common in the Makefile's :smile:

I didn't want to mess with the building of camlheader, because it varies hugely from platform to platform - there'd be no reason not to hoist its compilation (as it's either a C program or just a shell script).

**Comment by damiendoligez** [comment]
>For flexdll_dirs, I was concerned not to draw in any other quoting: it's just to ensure that you get -L"C:\Program Files\OCaml\FlexDLL". That assumption may be wrong, but I felt Filename.quote could do things I didn't want.

But this is only a partial solution. It fails (for example) when there are double quotes in the file name.

I think `Filename.quote` is exactly what you need: a way to pass a string to a command through one round of shell interpretation.

**Comment by dra27** [comment]
Double quotes aren't permitted in Windows filenames (other than via severe trickery for people who deserve no sympathy!) - my concern is that Filename.quote will apply wrong quoting rules (given that these strings are passed both to cl - a native program, and mingw-gcc - a Cygwin program)

**Comment by dra27** [comment]
(the concern may be ill-founded, given that the strings all go via flexlink)

**Comment by damiendoligez** [comment]
Interesting. You can very well have a double quote in a file name (cygwin can create the file easily) but the Windows shell doesn't handle them and the `dir` command maps them to `?`.

You should consider adding the quotes in all cases, not just when there is a space, because there are other metacharacter (for example the caret `^`).

**Comment by dra27** [comment]
Cygwin does it by a series of known character mappings (I think there are some settings under which it will refuse to do it). I can't remember if double-quote is one which you can use in underlying NTFS (I think it is, but the way to access those filenames is very odd and I don't think we should be trying to do that in general)

I'm wondering if there's any risk of double-escaping in using Filename.quote but given that these are corner cases, I'd prefer to be getting something in and possibly catch later. On that basis, I'd agree that it's probably better to use Filename.quote always and catch any issues later?

**Comment by dra27** [comment]
Some changes in an extra commit following Sébastien's review - easiest to look at https://github.com/ocaml/ocaml/pull/1101/commits/633a70d4e2aecb1ddbb00add19821f325f85a0b8

I have done some more looking into the quoting and I'm fairly convinced that **not** using Filename.quote is the right thing to do (I don't think that we're entirely doing the right thing anyway). Here, the double-quotes are just about keeping the entire parameter together, it's not about shell quoting.

Incidentally, OCaml's shell quoting itself is already very broken - in experimenting, I tried this:

```
C:\Users\DRA\Documents\ocaml-mgw64>set FU BAR=
C:\Users\DRA\Documents\ocaml-mgw64>md "%FU BAR%"
C:\Users\DRA\Documents\ocaml-mgw64>echo fubar>"%FU BAR%\t"
C:\Users\DRA\Documents\ocaml-mgw64>type "%FU BAR%\t"
fubar
C:\Users\DRA\Documents\ocaml-mgw64>set FU BAR=fubar
C:\Users\DRA\Documents\ocaml-mgw64>ocaml
        OCaml version 4.05.0+dev8-2017-03-20

# Filename.quote "%FU BAR%\\t";;
- : string = "\"%FU BAR%\\t\""
# Sys.command "type \"%FU BAR%\\t\"";
The system cannot find the path specified.
- : int = 1
```
That should work, but, and please enjoy this, you have to put:
```
# Sys.command "type ^%\"FU BAR\"^%\\t";;
fubar
- : int = 0
```
May I keep my simpler version, and we worry about proper cmd-escaping another time. [This SO question](http://stackoverflow.com/questions/30620876/how-to-properly-escape-filenames-in-windows-cmd-exe) also reveals how the rules for escaping become subtly different when parsing batch files as well (where `%%` can work as an escape for `%` but don't work at the prompt and so also in `cmd /c`)

**Comment by damiendoligez** [comment]
OK, you can keep your own version of escaping, but why not put double quotes in all cases and not just when there is a space?

**Comment by shindere** [comment]
David Allsopp (2017/03/23 15:33 -0700):
> I'm not sure why ocamlmklibconfig.ml and config.ml ended up - I would
> certainly agree that merging would be more sensible, but perhaps
> that's not for here.

So I looked into this a bit more, and actually the values printed to
ocamlmklibocnfig.ml are different from those already in config.ml. So I
think it is fine to remain with the current way. For autoconf, I guess
we will just have to .ml.in files and it is probably not a big deal.

**Comment by dra27** [comment]
Sorry for delay here - Sébastien's changes merged properly in and everything rebased. Same for the 4.04 version.

@damiendoligez - I want to re-run the tests for these two branches (which I'm just automating). I'm happy to make the change to quote -L always if you really want. My personal (and idiosyncratic) take is that I like the commands to use quoting only when it's strictly necessary (for me, somehow, it looks more like the authors of a tool understand quoting when it's done when necessary, rather than applied all the time). But it's not a view I take too strongly!

**Comment by dra27** [comment]
Right, re-running those tests has revealed one tiny little thing which, though not harmful, was not right. ocamlmklib would add the OCAMLLIB/flexdll search path even when only flexlink had been bootstrapped. It's a tiny change:

```diff
diff --git a/Makefile b/Makefile
index c818c390f..0b340c001 100644
--- a/Makefile
+++ b/Makefile
@@ -293,7 +293,7 @@ ifeq "$(FLEXDLL_SUBMODULE_PRESENT)" ""
 else
   BOOT_FLEXLINK_CMD = FLEXLINK_CMD="../boot/ocamlrun ../flexdll/flexlink.exe"
   CAMLOPT := OCAML_FLEXLINK="boot/ocamlrun flexdll/flexlink.exe" $(CAMLOPT)
-  FLEXDLL_DIR="+flexdll"
+  FLEXDLL_DIR=$(if $(wildcard flexdll/flexdll_*.$(O)),"+flexdll")
 endif
 else
   FLEXDLL_DIR=
```

**Comment by dra27** [comment]
This has been merged into 4.04 - rebased and awaiting CI answer before merging into 4.05 and trunk

**Pull request merged**
