### PR TITLE
PR#7272: ocamldoc, missing line breaks in type_* files 

### PR DESCRIPTION
**Pull request by Octachron**
[MPR#7272](http://caml.inria.fr/mantis/view.php?id=7272):

This PR should fix the problem of missing `<br>` tags within the `type_[modulename].html` files generated by ocamldoc ( compare e.g. [4.03](http://caml.inria.fr/pub/docs/manual-ocaml-4.03/libref/type_Arg.html) with [4.02](http://caml.inria.fr/pub/docs/manual-ocaml-4.03/libref/type_Arg.html) ) without regressing on [MPR#6341](http://caml.inria.fr/mantis/view.php?id=6341).

These two twin problems (MPR#6341) and (MPR#7272) stemmed from the combination of two errors in the generation of html encoding for OCaml code.

Such html code can be generated in two different contexts, either within `<pre> <code> ... </code> </pre>` tags or within a `<code>...</code>` tag. In order to obtain a similar rendered output in both environments, it is necessary to escape blank characters ( i.e. ` ` `\t` `\n`) inside the simple `<code>...</code>` context. 

However, ocamldoc was doing the reverse and escaped blank characters only within a `<pre>` tag.

Moreover, code output in `type_[modulename].html` files was generated for a `<pre><code>` context rather than the actual `<code>` context.

Before the fix for MPR#6341, these two errors partially compensated each other since:
- escaped characters in `<pre>` context were perfectly valid (if non-necessary) except for `\n`  that was escaped to `<br>\n` and thus interpreted as a double line break rather than a simple line break.
- `type_[modulename].html` code output was escaped and therefore,  `\n` was escaped to `<br> \n` and interpreted as a simple line break. Consequently, the generated html code rendered correctly.

The fix for MPR#6341, simply suppressed the escaping of `\n` to `<br> \n`, which was enough to fix the double line break issue in `<pre>` contex but simultaneously broke the generation of `type_[modulename].html`) files by removing the `<br>` tag that was needed in these files (aka MPR#7272).

This PR reverses ocamldoc escaping logic to escape blanks in code outside of a `<pre>` tag (see `odoc_ocamlhtml.mll`) and modifies the html backend to make it use the `<code>` generator (and not the `<pre><code>` generator) for `type_[modulename].html` files (see `odoc_html.ml`). Consequently, blank characters within Ocaml code are no longer escaped inside `<pre>` tags (but they never needed to be) and are escaped in `type_[modulename].html` files as required fixing both MPR#6341 and MPR#7272.

### CODE REVIEW

**Comment by gasche** [comment]
(I apologize in advance for the fairly un-original comment, but) Could we have regression tests as well?

**Comment by Octachron** [comment]
I have added a regression test for both MPR#6341 and MPR#7272. I apologize for not adding these tests in the initial commit: I wanted to double check the inversion of the escape logic before adding them.

**Comment by gasche** [comment]
@damiendoligez could I merge this into the 4.04 branch, to avoid [this ugliness](http://caml.inria.fr/pub/docs/manual-ocaml-4.03/libref/type_Arg.html) in the 4.04 manual? This is low-risk as ocamldoc only.

**Comment by gasche** [comment]
I forgot: thanks @Octachron for the nice work.

**Comment by damiendoligez** [comment]
@gasche go ahead, merge into 4.04.

**Comment by gasche** [comment]
I took the initiative to merge #806 as well -- it's also ocamldoc and low-risk and a significant improvement for some users (mobile).

**Comment by Octachron** [comment]
@gasche Thanks for taking care of the moves in the changelog.
However in the trunk version, you moved to the 4.04 section the wrong item: (7333,  short description for text) instead of this one: (7272, missing line breaks).

**Comment by gasche** [comment]
Thanks, fixed. (I decided not to backport 7333 as well because my gut feeling is that it is a slightly more regression-prone change.)

**Pull request merged**
