### PR TITLE
ocamldoc: remove debugging facility

### PR DESCRIPTION
**Pull request by shindere**
This seems old and unused.

@Octachron has found out that the `debug` target in `ocamldoc/Makefile` does
not even compile, at least since 4.06.

@gasche and @xavierleroy were in favour of this change so they may
accept to review it but others should feel free to do so,too.

### CODE REVIEW

**Comment by dra27** [comment]
The script was a pain for WSL cross-building as well, so I’m happy to see that back of it too!

**Review by gasche — APPROVED** [review]
This is good to merge if/when the CI agrees.

**Comment by shindere** [comment]
Thanks, @gasche.

Travis seems unhappy and I am still not able to figure out why. Could
you or @Octachron or somebody else tell me,please?

Thansk!

**Comment by Octachron** [comment]
Travis is merely unhappy about the lack of `Changes` entry.

**Comment by shindere** [comment]
Florian Angeletti (2020/06/09 05:44 -0700):
> Travis is merely unhappy about the lack of `Changes` entry.

Didn't I add a `no-change-entry-needed` label? Or perhaps I did a typo?

Well let's wait for AppVeyor anyway.

In case the label is wrong, would you mind fixing it, please?

Thanks a lot, @Octachron!

**Comment by Octachron** [comment]
The label was indeed missing, I fixed it.

**Comment by shindere** [comment]
Florian Angeletti (2020/06/09 05:47 -0700):
> The label was indeed missing, I fixed it.

Thank you! I guess the git-hub tool failed somehow, that's too bad.

**Comment by dra27** [comment]
Actually, GitHub seems to be having issues again - I can't restart the Travis job for you (this happened a few weeks ago, and then suddenly started working again)

**Comment by gasche** [comment]
It's fine if only the Changes test is failing. All other Travis tests are green, so let's wait until AppVeyor seems happy too and then merge.

**Comment by shindere** [comment]
Gabriel Scherer (2020/06/09 13:17 +0000):
> It's fine if only the Changes test is failing. All other Travis tests
> are green, so let's wait until AppVeyor seems happy too and then
> merge.

Done. Thanks.

**Pull request merged**
