### PR TITLE
Use AC_PREREQ to force Autoconf 2.69

### PR DESCRIPTION
**Pull request by dra27**
As suggested by @shindere in https://github.com/ocaml/ocaml/pull/8517#issuecomment-500323960

### CODE REVIEW

**Comment by shindere** [comment]
Thepatch looks good to me, except for one little thing:

```
# Some distros have this 2013 patch to autoconf, some don't...
```

I think "this 2013 patch" can be rather cryptic for an uninformed
reader. Woudl you mind clarifying a bit?

**Comment by dra27** [comment]
Sure, though it's a line only altered for whitespace in this PR...

**Comment by shindere** [comment]
LGTM, thakns. Will approve and merge.

Incidentally, I believe @damiendoligez pointed out that `sed -i` is not
supported on Mac OS so that might need to be fixed in a future PR.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Well CI does not seem happy at the moment and I don't know why so
I am not merging myself but if somebody can figure out what's wrong and
make sure it's a false positive, please anybody feel free to merge,
including yourself @dra27.

**Comment by dra27** [comment]
It's the Changes test - I've just kicked Travis

I've fixed the `sed` thing, so I don't know why that's merged - just trying to find the branch!

**Comment by dra27** [comment]
Yeah, this is fixed in #8652, which will need rebasing

**Pull request merged**
