### PR TITLE
Ocamltest conversion: basic-* tests

### PR DESCRIPTION
**Pull request by Octachron**
As an exercice, this PR converts the tests in the `basic-*` folders to ocamltest.
I have collected few remarks during the conversion:

- first, the `basic` folder is not converted because I was unsure of the best way to skip `basic/trigraph.ml` on i386 openBSD.

- second, the program comparison test between the native and bytecode ocamlopt compiler seems to be  brittle in presence of inlining. In particular, this test fails for `basic/morematch.ml`. 
Indeed, the digest of the generated cmx file differs between the bytecode and native version of ocamlopt due to different subexpression sharing in the inlining information when marshaling the cmx file (marshaling the cmx file with `Marshal.No_sharing` in `asmcomp/compilenv.ml write_unit_info` silences the problem) . For this reason, I added a variable to disable this program comparison (see the first commit  
3bf288c and the test header for `basic-more/morematch.ml`).

### CODE REVIEW

**Comment by gasche** [comment]
> marshaling the cmx file with `Marshal.No_sharing` in asmcomp/compilenv.ml write_unit_info silences the problem

Should we do this to help reproducible compilation? I would naively expect all `ocamlopt` executables of a given OCaml version to generate compatible `.cmx` files, at least on a architecture. What are the costs in terms of file size?

@Octachron, could you maybe send this change as a PR to foster discussion in a separate place?

**Comment by Octachron** [comment]
> What are the costs in terms of file size?

On the compiler code base, this seems to increase the overall size of cmx files (as reported by `du -ch -- **/*.cmx`) by 25% .

> could you maybe send this change as a PR to foster discussion in a separate place?

[Certainly](https://github.com/Octachron/ocaml/tree/stable_cmx), but would Mantis not be better suited for this kind of discussion?

**Comment by shindere** [comment]
@octachron first of all, a very big thank to you for your interest in
this taks!

Florian Angeletti (2017/11/11 13:00 +0000):
> As an exercice, this PR converts the tests in the `basic-*` folders to
> ocamltest.

Just to let you know: I did already migrate all these directories one
year ago, but was not able to get them merged at the same time than
ocamltest because of many issues with CI, the pre-feature freeze rush,
etc.

That's not to say it was a bad idea to have a look to thiese
directories, not at all! Quite the countrary, actually, because they are
the ones that are supposed to be the easy ones to migrate, in the sense
that ocamltest in its present shape is supposed to be expressive enough
to deal with all these tests.

Also, I can send you in a private e-mail the patch that contains the
tests migrated one year ago so that you can have a look to this.

> I have collected few remarks during the conversion:
> 
> - first, the `basic` folder is not converted because I was unsure of
> - the best way to skip `basic/trigraph.ml` on i386 openBSD.

This test should not need to be skipped any longer, because we now have
a flag that silences the warnings of the linker on this platform.

You can have a look to the ocamltest-with-basic-directory branch
of my public (shindere/ocaml) GitHub repository and in particular
to commit 25b803d529d0272b90da2fe6bd82b12833aa7f88 to see how this
is implemented (the parti of the commit related to safe-string is
probably irrelevant now).

> - second, the program comparison test between the native and bytecode
> ocamlopt compiler seems to be  brittle in presence of inlining.

Yep, I was aware of that. More precisely, IIRC, the programs start to be
different when the inlining level is either >5 or >=5, I'm not sure but
you should be able to figure this out.

> In particular, this test fails for `basic/morematch.ml`.

Absolutely.

> Indeed, the digest of the generated cmx file differs between the
> bytecode and native version of ocamlopt due to different subexpression
> sharing in the inlining information when marshaling the cmx file
> (marshaling the cmx file with `Marshal.No_sharing` in
> `asmcomp/compilenv.ml write_unit_info` silences the problem) .

Ah! I couldn't investigate myself so many thanks for having done so!

It may be worth noting that similar issues about programs not being the
same occur when flambda is enabled.

> For this reason, I added a variable to disable this program comparison (see the first commit  
> 3bf288c and the test header for `basic-more/morematch.ml`).

I don't know whether that's the right way to go. I mean: in general, I
like the idea of having a variable to disable program comparisons.
Perhaps there should even be two of them, one for bytecode program
comparison and one for native programs comparison, what do you think?

What I was not able to figure out is: why is this test compiled with
inlining? Is it on purpose? Is it something that should be preserved or
can we stop doing the inlining which would make the programs identical
again?

**Comment by xavierleroy** [comment]
Thanks @Octachron, it's great to see those converted tests starting to flow!  

Concerning the comparisons between the outputs of the .byte and the .opt compilers, I'd like to remind everyone that this is not a primary objective of the test suite.  Since these comparisons are fragile and cause tests to fail, I'd rather disable them until the whole test suite is converted, then revisit the issue.

**Comment by shindere** [comment]
Xavier Leroy (2017/11/11 17:14 +0000):
> Concerning the comparisons between the outputs of the .byte and the
> .opt compilers, I'd like to remind everyone that this is not a primary
> objective of the test suite.  Since these comparisons are fragile and
> cause tests to fail, I'd rather disable them until the whole test
> suite is converted, then revisit the issue.

It's worth mentionning that the comparison is already disabled, e.g.
when flambda is enabled.

Also, I agree that we should not be side-tracked by trying to fix
everything while migrating the testsuite, esecially because we don't
know how far we may have to go.

Finally, I have to say I quite like @octachron's idea to have a variable
that disables the comparison. With such a variable, we could still let
ocamltest perform the comparison and selectively disable it for those
tests where it fails. What I like in this approach is that the tests for
which the comparison does not work get marked and are then easy to
locate, later.

(I realise it would be possible to find them simply by re-running the
testsuite, but it's not as easy as having them explicitly marked, IMO.)

**Comment by shindere** [comment]
@octachron about the "program_comparison" variable you have introduced:

- I'd suggest to call it "compare_programs", what do you think?

For the moment, it is used only to control the comparison of native
programs. In my opinion, if it is used only there, then its name should
reflect it and it should be named compare_native_programs.

Or, and this second solution would have my preference, actually,
the variable could also be used to control the comparison of bytecode
programs.

Contrarily to what I wrote on Saturday, using the same variable for the
two things is perfectly fine, I think.

Since I am currently doing a big refactoring in ocamltest to add
support for running hooks, once we agree on what we want for this variable
I can include it in that refactoring.

**Comment by shindere** [comment]
@octachron about the way you have migrated the tests.

In the basic-more directory, you have done as follows:
```
(* TEST
   * native with testing
   ocamlopt_flags ="-inline 20"
   * bytecode with testing
*)
```
This is correct, indeed. However the same can be achieved in a more concise
way, as follows:
```
(* TEST
   include testing
   ocamlopt_flags ="-inline 20"
*)
```
That way you avoid repetitions and take advantage of the fact that the
bytecode and native tests are those run by default.

To give an insight, the "with" syntax has been introduced to run several
variants of the same test.

A number of toplevel tests, for instance, are run with and without the
-principal option. To express this in ocamltest's DSL, you can write
something like:
```
(* TEST
   * toplevel
   * toplevel with principal
*)
```

**Comment by Octachron** [comment]
@shindere , From my point of view, having a "compare_program" variable that controls both native and bytecode comparison makes sense, even if the bytecode comparison is not enabled for now or ever.

Concerning the comparison marking the failing cases may be a good idea to at least evaluate how many of them they are; and how often this comparison test breaks mysteriously in the long run. But it should be documented; probably in the ocamltest readme.

> This is correct, indeed. However the same can be achieved in a more concise
> way, as follows:
> 
> (* TEST
> include testing
> ocamlopt_flags ="-inline 20"
> *)

Thanks for the tip, it seems that I picked up the `with modifier` syntax by reading the TLS parser and did not make the connection with `include`. I think it may be worthy to add to the ocamltest README.

Overall, I think that the best course for this PR would be to close it once @shindere will have finished to dissect it and convert the collected information into a readme PR for ocamltest.

**Comment by shindere** [comment]
Florian Angeletti (2017/11/13 14:58 +0000):
> @shindere , From my point of view, having a "compare_program" variable
> that controls both native and bytecode comparison makes sense,

Good.

> even if the bytecode comparison is not enabled for now or ever.

Really? I thought it was the native comparison which was disabled under
some circumstances and that the bytecode comparison always takes place?

> Concerning the comparison marking the failing cases may be a good idea
> to at least evaluate how many of them they are; and how often this
> comparison test breaks mysteriously in the long run. But it should be
> documented; probably in the ocamltest readme.

Perhaps, yes. Actually, I duscussed the documentation of ocamltest with
@xavierleroy recently, asking him how we should proceed, whether we
should write documentaton first or give the priority to the migratio of
the testsuite.

His opition, as far as I understood it (but please @xavierleroy correct
me if I misunderstood you) was that it would probably be better to give
priority to the migration of the tests and then write ocamltest's
documentation once it has been proven stable and complete enough to deal
with all the test suite.

That does not mean, of curse, that we should not write any documentation
at all. It's just to give an insight about how we could deal with
things.

> > This is correct, indeed. However the same can be achieved in a more concise
> > way, as follows:
> > 
> > (* TEST
> > include testing
> > ocamlopt_flags ="-inline 20"
> > *)
> 
> Thanks for the tip, it seems that I picked up the `with modifier`
> syntax by reading the TLS parser and did not make the connection with
> `include`.

Yeah it was perhaps not very clear, sorry about that.

> Overall, I think that the best course for this PR would be to close it
> once @shindere will have finished to dissect it and convert the
> collected information into a readme PR for ocamltest.

Well. I'm working on ocamltest currently and hope to update it soon.
Once this is done, I rather think this PR could be rebased on the new
ocamltest. There is not much missing to integrate it, IMO. If you could
just rewrite the tests under basic-more as described I think it would be
enough. And then we'd have to deal with the compare_programs variable
once it's there and then the PR can be merged.

**Comment by Octachron** [comment]
> Really? I thought it was the native comparison which was disabled under some circumstances and that the bytecode comparison always takes place?

Sorry, I was momentarily confused.

> His opition, as far as I understood it (but please @xavierleroy correct me if I misunderstood you) was that it would probably be better to give priority to the migration of the tests and then write ocamltest's documentation once it has been proven stable and complete enough to deal with all the test suite. 

I agree that a full documentation can wait; but it may be useful to have an on-going collection of short tips for the migration.

> Once this is done, I rather think this PR could be rebased on the new ocamltest. 

Sure, I will be perfectly happy to do that.

> What I was not able to figure out is: why is this test compiled with inlining? Is it on purpose? Is it something that should be preserved or can we stop doing the inlining which would make the programs identical again?

Speaking of this point, after investigation, this inlining option was introduced by @garrigue in `9212dd34acb`. If I am not mistaken, this was only for the sake of `basic-more/pr6216.ml`.
Consequently, I am inclined to remove this option from all other tests; because it muddles the fact that inlining is essential to `pr6216` without bringing much to the table.

**Comment by shindere** [comment]
Florian Angeletti (2017/11/17 16:25 +0000):
> I agree that a full documentation can wait; but it may be useful to
> have an on-going collection of short tips for the migration.

I may try but think it may be even better if it is written by someone
else.

> > Once this is done, I rather think this PR could be rebased on the new ocamltest. 
> 
> Sure, I will be perfectly happy to do that.

Great, thanks!

> > What I was not able to figure out is: why is this test compiled with inlining? Is it on purpose? Is it something that should be preserved or can we stop doing the inlining which would make the programs identical again?
> 
> Speaking of this point, after investigation, this inlining option was
> introduced by @garrigue in `9212dd34acb`. If I am not mistaken, this
> was only for the sake of `basic-more/pr6216.ml`.
> Consequently, I am inclined to remove this option from all other
> tests; because it muddles the fact that inlining is essential to
> `pr6216` without bringing much to the table.

I fully agree. Is that fine with you @garrigue ?

**Comment by Octachron** [comment]
I have rebased the PR, factorized the test header with `include testing`, and removed the inlining flag outside of the pr6216 test.

**Comment by shindere** [comment]
Many thanks for your work, Florian.

Just a few cosmetic remarks:

In testsuite/tests/basic-manyargs/manyargs.ml:
Could you please remove just one space before "modules" so that it is
indented as "TEST" ?
Could you please also remove the blank lines before and after the *) ?

In testsuite/tests/basic-more/bounds.ml:
Is the "* native" line intentional? Does this test really have to be
executed in native mode only?
If you intent to keep this line you could fix its indentation.

In testsuite/tests/basic-more/function_in_ref.ml:
Could you please add a blank line after the end of the TEST block?

Once this is taken into account I'll be more than happy to merge.

Thanks again!

**Comment by Octachron** [comment]
>  In testsuite/tests/basic-manyargs/manyargs.ml: Could you please remove just one space before "modules" so that it is indented as "TEST" ? Could you please also remove the blank lines before and after the *) ?

Fixed

> In testsuite/tests/basic-more/bounds.ml: Is the "* native" line intentional? Does this test really have to be executed in native mode only? If you intent to keep this line you could fix its indentation.

The test was documented as targeting `ocamlopt`: https://github.com/ocaml/ocaml/blob/trunk/testsuite/tests/basic-more/bounds.ml#L1 . But yes, It is probably better to simply update this comment and also test the bytecode mode .

>  In testsuite/tests/basic-more/function_in_ref.ml: Could you please add a blank line after the end of the TEST block?

Fixed.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Merged, thanks a lot!

**Pull request merged**
