### PR TITLE
win32unix: quote the arguments to the Unix.exec* functions

### PR DESCRIPTION
**Pull request by xavierleroy**
As reported in #9320, the current Win32 implementation of the exec* functions split arguments at spaces.  This PR fixes this issue by performing the same quoting that the Win32 implementation of `Unix.create_process` performs.  

A test was added to the test suite.  CI precheck passes the test.

### CODE REVIEW

**Review by nojb — APPROVED** [review]
LGTM, but probably a good idea for @dra27 to take a look as well.

**Comment by dra27** [comment]
I'm still reading and deciding on the implication, but note that this works before this patch and fails with it:

```ocaml
#load "unix.cma";;
let c = open_out "Foo.txt" in
output_string c "Bar"; close_out c;
let find = Filename.concat (Filename.dirname (Sys.getenv "COMSPEC")) "find.exe" in
Printf.printf "With Sys.command\n%!";
let _ = Printf.ksprintf Sys.command "%s \"Bar\" Foo.txt" find in
Printf.printf "\nWith Unix.execv\n%!";
Unix.execv find [| "find.exe"; "\"Bar\""; "Foo.txt" |]
```

This example is invoking the Windows find utility (the reading of `COMSPEC` is just to guarantee that it picks up the one in `C:\Windows\system32` and never Cygwin's find). Before this PR it outputs:

```
With Sys.command

---------- FOO.TXT
Bar

With Unix.execv

---------- FOO.TXT
Bar
```
afterwards:
```
With Sys.command

---------- FOO.TXT
Bar

With Unix.execv
File not found - \BAR\

---------- FOO.TXT
```

It's possible we should just live this - I want to double-check why.

**Comment by dra27** [comment]
OK, to confirm the situation vis-à-vis https://github.com/ocaml/ocaml/issues/9320#issuecomment-609005680, looking at  `exec/cenvarg.cpp` of UCRT 10.0.10586.0, the function `construct_command_line` (which is used everywhere in the UCRT to convert lists of arguments to command lines) is equivalent to `String.concat " " (Array.to_list argv)`. In other words, the exec* (and all other) functions make no effort to conform to CRT/[CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) conventions - that's left to the caller.

This patch actually improves the support for exec'ing to Cygwin executables as well (I expect that there are still odd corner cases and my horrific `cygvoke` patches will remain in opam, but that doesn't matter). `find` is odd because it actually treats it command line as a single string (it's very old) - many more things get fixed by this change than are broken by it.

However, I feel that there should be a way of being able to create processes on Windows where you can actually pass the command line without having to go via writing your own C stub. Of course, the default should be as cross-platform and least surprising as possible.

I'm wondering therefore if the escaping operation could be exposed and an optional argument used for all the exec and other functions which convert argument lists, in a similar manner to `?cloexec` in many of the other functions - the default would be as you do here, but you could also override the mapping function with `Fun.id` (or, potentially, the correct Cygwin version). In particular, that would mean that `Unix.execv ~escape:Fun.id cmd [| arg |]` would allow arg to be literally the command line passed to `CreateProcess`.

**Comment by dra27** [comment]
Others have trodden here, incidentally: https://wiki.tcl-lang.org/page/exec+quotes+problem and https://bugs.python.org/issue436259. The Cygwin fun-and-games in opam is https://github.com/ocaml/opam/pull/3348/commits/dc3d3c7427e8e5173e6db25253e84ad9cc875cf2

**Comment by xavierleroy** [comment]
To characterize what this bug fix does: it makes sure that `Unix.execv cmd args` behaves like
`ignore (Unix.(createprocess cmd args stdin stdout stderr)); exit 0` as far as argument passing goes.

There should also be some kind of equivalence with `Sys.command (Filename.quote_command cmd args)`.

I think this makes sense, and is consistent with the POSIX world.

> However, I feel that there should be a way of being able to create processes on Windows where you can actually pass the command line without having to go via writing your own C stub

You can use the stub provided by win32unix:
```
external win_create_process : string -> string -> string option ->
                              file_descr -> file_descr -> file_descr -> int
                            = "win_create_process" "win_create_process_native"
```
The second `string` is the raw command line.

But I don't want to expose this operation in the Unix module interface, because it has no equivalent in the POSIX world.

> I'm wondering therefore if the escaping operation could be exposed and an optional argument used for all the exec and other functions which convert argument lists

Again that would make sense only for the Win32 implementation of the Unix module interface and not for the POSIX implementation.

**Comment by xavierleroy** [comment]
CI precheck passes.

**Comment by dra27** [comment]
I agree with the characterisation, but another key point of `execv*` vs `system` (i.e. `Sys.command`) is the latter involves the shell, where `execv` really is about process invocation. Especially on Windows, you tend to come to these functions precisely to escape shell-hell!

While the history of the library of course means it's called `Unix`, it'd be named `OS` if we rewrote it today. It may be niche, but I find it irritating that if I'm writing a Windows program, there are now programs which I cannot execute with these functions (i.e. before I could sort the escaping myself, now I can't - pun intended - escape it). [As a side-note, this kind of applies to the changes in 4.05 for `createprocess`]

Possibility 0 (as suggested): control the mapping of the args to a cmdline, with a default which covers most uses (most especially being as POSIX-like as possible on Windows)

Possibility 1 (your note above): we already have hatches like `?to_dir` in `symlink` which are Windows-specific. For what it's worth, I'd find exposing `win_create_process` a fairly decent solution (actively encouraging use of the C primitives is not). The Unix interpretation, which you'd never expect to use if you were writing either for POSIX or for actual cross-platform, would simply be to interpret `"cmdline"` as `[|"cmdline"|]`. It doesn't feel like too much to ask for the odd function and argument to keep the Windows-side of this library completely usable.

Possibility 2 (meh, maybe - this works at the moment): Special-case the singleton array and don't escape it at all (exactly as the underling `execv*` call doesn't). i.e. `Unix.execv find [| "find.exe \"Bar\" Foo.txt" |]` takes "find.exe \"Bar\" Foo.txt" as the complete command line.

**Comment by xavierleroy** [comment]
The time I'm willing to spend arguing over trivial bug fixes is about to reach zero, so I'll keep it short.

Under Windows, `exec*` are a rarely-used special case of `create_process`.  Basically, `createprocess` followed by `exit`.  That those two groups of functions disagree on the handling of arguments is a bug, and was reported as such.  `create_process` has the correct (in my opinion) / more useful (in your opinion) behavior of the two.  This PR fixes the bug by aligning `exec*` on `create_process`.  This is an improvement.  That's why I'm merging this bug fix now.

I agree that `Unix.create_process` doesn't let you call the `FIND` utility and its unique command-line handling.  It's an orthogonal concern.  This has been the case for a very long time and no user has reported a problem.  (I think the problem is with `FIND`, actually.)  Note that if you really must call `FIND` you can do `Sys.command` and deal with shell escapes; it's not entirely impossible.

If you want to propose changes to the Unix module that give access to the "raw" `CreateProcess` Win32 function, please do that in a separate PR.  But I still think this does not belong in the Unix module, which is about some kind of common abstraction between Win32 and POSIX.  There are a lot of POSIX features that are not in Unix, in part because they have no Win32 counterpart.  Anyone is welcome to develop a standalone Win32 library that would be all about "true" Win32 systems programming.

**Pull request merged**
