### PR TITLE
Move complugin and friends from BYTECOMP to COMP

### PR DESCRIPTION
**Pull request by lpw25**
This moves `Complugin` and its dependencies from the `BYTECOMP` Makefile section to the `COMP` Makefile section because they are used by parts of ocamlopt. In particular, without this change `ocamlopttoplevel.cmxa` cannot be linked without `ocamlbytecomp.cmxa` -- which is a regression from 4.03.0.

### CODE REVIEW

**Comment by gasche** [comment]
This seems correct to me, and I don't see much potential for regression. I'll merge in a couple days if nobody objects.

**Comment by gasche** [comment]
The way `Compdynlink` is built is tricky, the `.cmx` and `.cmo` don't use the same source (the `.cmo` uses `.mlbyte`, and the `.cmx` uses `.mlopt` or `.mlno` if natdynlink is unavailable), so they also don't have the same dependencies. Why would the opt-related `.cmxa` include `bytecomp/meta.cmx` if they don't depend on it?

**Comment by mshinwell** [comment]
This may need looking at in conjunction with #1063, which changes some of the dynlink source files around a bit.

**Comment by lpw25** [comment]
> Why would the opt-related .cmxa include bytecomp/meta.cmx if they don't depend on it?

Are you suggesting moving `meta.cmo` from `COMP` to `BYTECOMP`? But then wouldn't `ocamlcommon.cma` require linking `ocamlbytecomp.cma`?

**Comment by lpw25** [comment]
@gasche Could you clarify what you would like to be done differently? (or if you're happy with it approve it for merge)

**Comment by gasche** [comment]
On my first (incompelte) read, I thought that "only compplugin" had moved. I understand that its dependencies had to be moved as well, but I am uncomfortable with the fact that some dependencies that look "very bytecode" to me (`meta.cmo` in particular) is now moved to COMP. This changes the PR from "somethin small in scale touching a relatively new module" to "touches old old stuff in ways that feel a bit strange to me and that I don't understand". I don't feel like I am informed enough to review/approve the change.

My remark in the previous comment can be explicited: if I understand correctly, there are two implementations of compplugin, and only the bytecode one needs `meta`. I wondered if the fact that `compplugin` does *not* depend on Meta when used for native compilation meant that it was possible to keep `meta` in `BYTECOMP` instead of moving it to the shared zone. But I guess that does not work, as some things may use `COMP` but neither of `ASMCOMP` and `BYTECOMP`, and those would lack dependencies.

**Comment by mshinwell** [comment]
The point is that some of the files in the `bytecomp` directory are required to dynamically link plugins when the compiler itself is built as bytecode (irrespective as to whether the compiler produces bytecode or native code).  It seems better to adopt the approach in this patch, whereby these few small dependencies live in `COMP` together with accepting the fact that they will be linked when not needed (i.e. when the compiler itself is built as native code), rather than (a) having things that are clearly not at all related (e.g. emission of bytecode instructions) to the native compiler linked into it or (b) having the `.cmo` version of the dynamic-link support code be in a different library from the `.cmx` version.

This patch also fixes a regression if I understand correctly.

This is OK subject to the tests passing.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
