### PR TITLE
Aligned alloc

### PR DESCRIPTION
**Pull request by bartoszmodelski**

### CODE REVIEW

**Comment by xavierleroy** [comment]
As mentioned in the https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md guidelines:

The description of the merge request must contain a precise explanation of the proposed change.
Before going in the implementation details, you should include a summary of the change, and a high-level description of the design of the proposed change, with example use-cases.

Can you please provide this information?

**Comment by bartoszmodelski** [comment]
Woops, only opened it here by mistake! Apologies for the noise.

**Comment by dra27** [comment]
Looking at @bartoszmodelski's fork, I think it's possible this was supposed to be a self-PR (possibly for CI?) which GitHub has "helpfully" redirected here?

**Comment by dra27** [comment]
Ah - yes!

**Pull request closed without merging**
