### PR TITLE
Remove unnecessary executable bit from sources

### PR DESCRIPTION
**Pull request by dra27**
@mshinwell noticed various files in the middle end which had acquired the executable bit which it turned out was from #614. I've direct pushed those, but the incantation `git ls-tree -r HEAD | grep "^100755"` reveals that there are various other files which are unnecessarily marked executable. This GPR removes the `+x` bit - I just want to be certain, given the testsuite ones, that nothing was depending on that so this is here to run through CI.

As usual, this is kind of a Windows problem - it's mostly solved these days, as Git for Windows has, I think, set `core.fileMode` to `false` for some time (this means that on Windows to commit a file as executable, you must explicitly state `git update-index --chmod=+x foo` and Git ignores any changes to the executable bit for existing files). The problem can still occur if you use Cygwin's git on a tree checked out using Git-for-Windows, as Cygwin defaults many files to be executable on certain mounts.

When reviewing, one should be suspicious of the `100644 → 100755` line (see below)

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
Looks good to me.

**Comment by xavierleroy** [comment]
PS.  I did not see any suspicious `100644 → 100755` line.  Did I miss something?

**Comment by dra27** [comment]
@xavierleroy - I should have said "When reviewing *new PRs*", sorry!

**Comment by shindere** [comment]
David Allsopp (2019/02/28 13:49 +0000):
> @xavierleroy - I should have said "When reviewing *new PRs*", sorry!

Wouldn't there be a way to automate this?

e.g. perhaps we could somehow identify in .gitattributes files for which
the executable bit is legitimate and then raise a warning if files that
have not been declared there have it?

I guess @xavierleroy will ask whether it's really worth the effort, but
then I'd say, why not :)

**Comment by dra27** [comment]
It's possible that the test could be simpler - any executable file should start `#!` or be one of the bootstrap images in `/boot`

**Comment by shindere** [comment]
David Allsopp (2019/02/28 06:16 -0800):
> It's possible that the test could be simpler - any executable file
> should start `#!` or be one of the bootstrap images in `/boot`

Sounds good. Shall that be added to Travis, for instance?

**Comment by xavierleroy** [comment]
I think a check like what @dra27 describes would be good to have in a tools/check-file-modes script that could be called from CI.

**Comment by shindere** [comment]
Xavier Leroy (2019/02/28 07:27 -0800):
> I think a check like what @dra27 describes would be good to have in a
> tools/check-file-modes script that could be called from CI.

Done. See GPR #2274.

**Pull request merged**
