### PR TITLE
add `Stack.fold` (issue 0003622)

### PR DESCRIPTION
**Pull request by c-cube**
not too hard to write, but required twice on the bugtracker, and still open as far as I could tell.

### CODE REVIEW

**Comment by damiendoligez** [comment]
Could you write the documentation as a stand-alone description instead of referring to List.fold_left? As written now, I find it hard to decode.

**Comment by alainfrisch** [comment]
@c-cube Can you add an entry in the changelog before I merge the PR?

**Comment by mshinwell** [comment]
@c-cube Please resolve the conflict(s)

**Comment by c-cube** [comment]
done.

**Pull request merged**
