### PR TITLE
typecore: only 1k existential per match, not a 100k

### PR DESCRIPTION
**Pull request by trefis**
Fixes [MPR#7833](https://caml.inria.fr/mantis/view.php?id=7833) (confirmed thanks to the [test case](https://github.com/querycert/bug0007833) produced by @jeromesimeon).

---
Note: bootstrap required because:
```
File "asmcomp/mach.ml", line 1:
Error: The files asmcomp/arch.cmi and asmcomp/mach.cmi
       make inconsistent assumptions over interface Arch
```
which happens because:
- Arch is compiled twice, once with the bootstrapped ocamlc, once with a freshly compiled ocamlopt
- Arch doesn't have an .mli
- the stamp on idents won't be the same for .ml files as a result of this change

### CODE REVIEW

**Comment by jeromesimeon** [comment]
That was fast :) Looks good to me.

**Comment by gasche** [comment]
(cc @garrigue)

Just curious:
- why was the limit set to 100k when the comment already said 1k? Just a typo?
- what about the idea of upping the total limit from 10M to something larger? Are there reasons to keep it sensibly smaller than 2^31?

**Comment by trefis** [comment]
> why was the limit set to 100k when the comment already said 1k? Just a typo?

I think so.
I think there was a reason for bumping this at some point, but I can't find it again looking at the current code. So it's possible that it's a left over from a previous experiment that sneaked into a rebase (and looked innocuous enough that I never removed it).

> what about the idea of upping the total limit from 10M to something larger? Are there reasons to keep it sensibly smaller than 2^31?

You mean bumping `generic_level` right? I don't know, I think it could probably be bumped but that it's fairly independent from this issue (which is just reverting a regression).

If you bump it, you'll also want to:
- make sure that the (un)marking of types still works fine when the type is at the generic level
- keep a value that's easily recognizable in the debugger (that's actually really useful).

So you probably don't want to go as far as 2^31, but any good looking number below that will do just fine.

**Comment by garrigue** [comment]
Well, actually this is not currently 10 million but 100 million.
Knowing that we also use negative levels, the maximum would max_int, i.e. 2^30-1, which means at most a factor 10. Of course we would have to be careful about how computations are done on levels, so that we don't end up having bugs that only appear on 32 bit architectures...
I'm not sure the difference is worth it, at least not for a bug-fix release.

**Review by garrigue — APPROVED** [review]

**Comment by gasche** [comment]
Thanks for the replies, my curiosity is satisfied. Whoever merges, please remember to cherry-pick into the 4.07 maintenance branch.

**Comment by jeromesimeon** [comment]
Just to confirm: with this patch, I was able to compile the provided bug test in [test case](https://github.com/querycert/bug0007833) and also compile the extracted OCaml module in qcert that triggered this thread. x-ref: https://github.com/querycert/qcert/issues/104

**Comment by trefis** [comment]
It occurs to me that I probably didn't emphasize it enough but: I was annoyed by the fact that I needed to bootstrap here.
@gasche: I seem to remember that you looked recently at the makefiles to use a freshly built `ocamlc[.opt]` to compile the rest of the world instead of using the bootstrapped compiler, which I think would have avoided the bootstrap I had to do here.
Have you got anywhere with that?
Also, is there any reason why we would want to keep using the bootstrapped compiler?

**Comment by gasche** [comment]
I made various experiments but they are not ready for public consumption, and what I focused on mostly was whether I could store `.opt` compilers (byte and native) in `boot/` from a previous build, and use them to speedup rebuilding. I don't think that would have helped here, sorry. (Maybe I'll dust it off someday and make a PR, but not now.)

**Comment by damiendoligez** [comment]
@trefis the main problem is this:

>Arch doesn't have an .mli

**Pull request merged**
