### PR TITLE
remove typedtreeMap

### PR DESCRIPTION
**Pull request by trefis**
There are currently **two** typedtree mapper in the distribution: `Tast_mapper` and `TypedtreeMap`.
The first one is used in the compiler codebase, the second isn't.

Similarly, searching github for [`Tast_mapper`](https://github.com/search?l=OCaml&q=tast_mapper&type=Code) returns 110 results in OCaml, while searching for [`TypedtreeMap`](https://github.com/search?l=OCaml&q=typedtreeMap&type=Code) returns only 60.

Equipped with these very scientifically obtained numbers, and the initial insightful observation, it seems obvious the `TypedtreeMap` should be the one to go.

### CODE REVIEW

**Comment by gasche** [comment]
Doing this, we end up with an inconsistent API with `typedtreeIter` on one hand and `tast_mapper` on the other, but no `typedtreeMap` or `tast_iter` -- this is not just a naming concern, the visitor-pattern style is fairly different on both ends, with `typedtree{Map,Iter}` being more stream-like and `tast_{mapper,iter(ator?)}` being a simpler open recursion. (And none of them is "shallow" like `Btype.{iter,fold}_type_expr` and the new Lambda iterators, and Flambda has completely different APIs again...)

On the typedtree we have both `ast_{mapper,iterator}`, consistent in design with `tast_mapper` (same authors), so it makes sense to keep `tast_mapper` indeed, but maybe we could try, medium term, to actually write `tast_mapper` for consistency and migrate the only use of TypedtreeIter (in our favorite `parmatch.ml` file) to it. Could you maybe create a Mantis issue with the "junior job" tag for this?

**Comment by trefis** [comment]
> maybe we could try, medium term, to actually write `tast_iterator` for consistency and migrate the only use of `TypedtreeIter` (in our favorite parmatch.ml file) to it. Could you maybe create a Mantis issue with the "junior job" tag for this?

Sure, can do.
Although ideally, we would find a way to generate these iterators/mappers, instead of having to maintain them manually. (But that seems like a lot of work, and definitely not "junior" friendly).

Was your message a disguised approval of this PR?

**Comment by trefis** [comment]
[MPR#7878](https://caml.inria.fr/mantis/view.php?id=7878).

**Comment by Drup** [comment]
> Although ideally, we would find a way to generate these iterators/mappers, instead of having to maintain them manually. (But that seems like a lot of work, and definitely not "junior" friendly).

Janestreet mapper generators work very well on types/typedast. See: [this mapper for types](https://github.com/ocsigen/ocaml-eliom/blob/eliom/typing/types_mapper.mli) which was generated by ppx_traverse. I'm sure visitor would work as well.

When I was shopping for an visitor for the typedtree, I found `typedtree{Map,Iter}` to be barely usable at all, so moving to the style used by ppx/untypedast/* seems like a good direction to me.

**Comment by alainfrisch** [comment]
Do we really need to provide both mappers and iterators?  One could just use an identity+side-effects mapper, it doesn't really complicate the client code that much and the impact on performance should be ok for most cases (if needed, one could also optimize the mapper to detect physical equality of all children before/aften the sub-rewriting and return the original term when nothing changed).

**Review by gasche — APPROVED** [review]

**Comment by trefis** [comment]
@Drup: I think we would want to stay away from objects for that part of the codebase.
(And to clarify, though I think you know that, the annoying part is how to set up the code generator, in a way that integrates well with the build system, the bootstrap cycle, etc.)

**Comment by alainfrisch** [comment]
(Btw, the use of Tast_mapper in cmt2annot.ml is really an iterator.)

**Comment by gasche** [comment]
> Do we really need to provide both mappers and iterators?

I think that it is better on the consumer side to be able to use the right abstraction for the job. It's fine if one is implemented in term of the other on the library side, but the problem here is that the interfaces are larger than the implementations, and do have to be duplicated. We have to balance the cost for the user of the abstractions, with the cost when modifying the type declarations, and I'm not sure what is the right choice.

**Pull request merged**
