### PR TITLE
Add bigarray to the stdlib

### PR DESCRIPTION
**Pull request by ghost**
This PR is the next step in moving Bigarray to the Standard Library.

### Overview

It moves the Bigarray module to the standard library without the `map_file` functions. The bigarray library is kept for compatibility purposes and simply extends Stdlib.Bigarray with the deprecared `map_file` functions. This way users have more time to update their code, especially the ones who want to keep compatibility with OCaml < 4.06.0.

Other relevant details:

- `otherlibs/bigarray/bigarray_stubs` was appended at the end of `byterun/bigarray.c`
- the `CamlinternalBigarray` module was removed since it is no longer needed

### Limitation

Because all the cmi files are installed in the same directory, in the initial environment the module name `Bigarray` always resolves to `Bigarray` from the bigarray library rather than `Stdlib.Bigarray`. One has to use `Stdlib.Bigarray` explicitely in order to use bigarrays without depending on unix.

### Reviewing

Because some code was moved around, the diff shows a lot of added and deleted code. It is easier to review the following files with these commands:

- `stdlib/bigarray.ml`: `patdiff <(git show trunk:otherlibs/bigarray/bigarray.ml) stdlib/bigarray.ml`
- `stdlib/bigarray.mli`: `patdiff <(git show trunk:otherlibs/bigarray/bigarray.mli) stdlib/bigarray.mli`
- `byterun/bigarray.c`: `patdiff <(git show trunk:byterun/bigarray.c; git show trunk:otherlibs/bigarray/bigarray_stubs.c) byterun/bigarray.c`

### CODE REVIEW

**Comment by shindere** [comment]
FWIW, ocamltest has a bigarray modifier to include the bigarray library
under otherlibs.

Am I correct that this PR would make the modifier un-necessary?

If I amcorrect, then the PR could include its removal and perhaps also
an update to the tests that makeuse of it.

**Comment by ghost** [comment]
Indeed, I removed the modifier

**Comment by dra27** [comment]
~Assuming that repeatably fixes it,~ feel free to squash that commit into 97e616c

**Comment by mshinwell** [comment]
I am reviewing this.

**Comment by mshinwell** [comment]
This is going to produce an unrelated test failure which I have emailed @shindere about, but this patch is OK, and we should merge before 4.07.  A bootstrap commit will be needed to remove some redundant primitives; I will do this.

**Review by mshinwell — APPROVED** [review]

**Comment by mshinwell** [comment]
The only failure for a reasonable set of targets appears to be the one which @shindere is currently working on, and I need to follow this with a manual bootstrap commit anyway, so I am going to merge this now.

**Comment by mshinwell** [comment]
The bootstrap which completes this GPR is in `e866ba3f6891a18ede3235f125babd5f7fd6d03a`.

**Comment by dbuenzli** [comment]
This closes [MPR6139](https://caml.inria.fr/mantis/view.php?id=6139)

**Comment by gasche** [comment]
Thanks @dbuenzli, I'll add the mantis issue to the Changes entry.

**Comment by shindere** [comment]
@diml sorry for asking this question so late.

Am I correct that, as far as the source tree is concerned, the bigarray
files were not moved to the stdlib directory?

May I ask why and whether there is any plan to do so in a further PR?

**Comment by ghost** [comment]
They were moved, however the bigarray library is kept for compatibility. The `Bigarray.*.map_file` functions were deprecated in 4.06, so we just need to wait a reasonable amount of time before deleting the bigarray library entirely. I assume that deleting it in 4.08 should be ok.

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 14:05 +0000):
> They were moved, however the bigarray library is kept for
> compatibility. The `Bigarray.*.map_file` functions were deprecated in
> 4.06, so we just need to wait a reasonable amount of time before
> deleting the bigarray library entirely. I assume that deleting it in
> 4.08 should be ok.

OK I must really have missed something, sorry.

Which .cma file is one supposed to use when trying to use the bigarray
lib from the sources (without installing?)

**Comment by ghost** [comment]
You should just use the `Bigarray` module from the stdlib, so you don't need any special cma. However, if you pass `-I [...]/stdlib -I [...]/otherlibs/bigarray` to the compiler, you need to use `Stdlib.Bigarray` explicitly in your code in order to refer to the bigarray module from the stdlib. After installing, you always need to use `Stdlib.Bigarray`. This is because the `bigarray.cmi` file in the search path has precedence over `Stdlib.Bigarray`. `bigarray.cmi` is from the bigarray library.

If you do want to use the deprecated bigarray library, then you need to to use bigarray.cma as before.

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 14:35 +0000):
> You should just use the `Bigarray` module from the stdlib, so you
> don't need any special cma.

I do need to handle the cmas directly, see for instance the
lib-dynlink-csharp test, you can git grep for bigarray.cma in this
directory and you'll see.

**Comment by ghost** [comment]
Ok, this test should still work as bigarray.cma still exists at the same place.

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 14:45 +0000):
> Ok, this test should still work as bigarray.cma still exists at the
> same place.

Yeah I confim. I was just wondering why this file has not been moved to
stdlib?

**Comment by ghost** [comment]
Because it's not part of the stdlib :)

`Stdlib.Bigarray`, like all other stdlib modules, is compiled as `Stdlib__Bigarray` and ends up part of `stdlib.cma/cmxa`. `bigarray.cma` is only the deprecated bigarray library, which simply extends `Stdlib.Bigarray` with the deprecated functions.

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 14:57 +0000):
> Because it's not part of the stdlib :)
> 
> `Stdlib.Bigarray`, like all other stdlib modules, is compiled as
> `Stdlib__Bigarray` and ends up part of `stdlib.cma/cmxa`.
> `bigarray.cma` is only the deprecated bigarray library, which simply
> extends `Stdlib.Bigarray` with the deprecated functions.

Okay thanks. I'm not sure what one will have to do re:this
lib-dynlink-csharp test when the deprecated bigarray will be removed?

Perhaps the tes will simply no longer need to load it and will continue
to work?

**Comment by ghost** [comment]
> Perhaps the tes will simply no longer need to load it and will continue
to work?

I believe so. It should even work right now

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 15:03 +0000):
> > Perhaps the tes will simply no longer need to load it and will continue
> to work?
> 
> I believe so. It should even work right now

OK then I'll get rid of bigarray while porting to ocamltest

Thanks a lot for your support!


>

**Comment by shindere** [comment]
@diml and @alainfrisch :

I am assumiing that unix.cma and unix.cmxs were loaded only to support
bigarray and that they are thus not needed any longer either. Is that
correct?

I hope stopping to load them does not defeat the purpose of the test itself
but I don't think so. Would just appreciate this to be confirmed.

**Comment by ghost** [comment]
I admit I don't really know what this test is doing, but I assume that it should indeed load a few files. Maybe the plugin should be updated to test a different function

**Comment by shindere** [comment]
Jérémie Dimino (2018/04/18 16:03 +0000):
> I admit I don't really know what this test is doing, but I assume that
> it should indeed load a few files. Maybe the plugin should be updated
> to test a different function

Let's hope @alainfrisch will tell us. :)

**Pull request merged**
