### PR TITLE
Handle `[@inlined]` attributes under a module constraint

### PR DESCRIPTION
**Pull request by xclerc**
In 4.07/trunk, the following code:

```
module M = Set.Make [@inlined] (Int32)
```

triggers a puzzling warning "attribute cannot appear in this context".
This is quite puzzling because the following code does not trigger
the warning:

```
module M = Set_make [@inlined] (Int32)
```

@lpw25 helped me understand that an existing bug was indeed revealed
by the introduction of the `Stdlib` module. The code triggering the warning
goes through a module alias and hence a module constraint, so that the
`[@inlined]` attribute is not on the outer module expression as expected
but on the inner one.

### CODE REVIEW

**Review by lpw25 — APPROVED** [review]
Looks good to me and fixes an annoying bug. @damiendoligez Can I still backport to 4.07? Seems like the release is incoming and I don't want to get in the way, but I think this probably qualifies as a regression even though really 4.07 just uncovers an existing bug.

**Comment by xclerc** [comment]
I have just updated the PR number in the reproduction
case; the PR can be merged (I am unsure whether this
patch deserves an entry in the change log).

**Comment by lpw25** [comment]
It is possible to hit this bug in 4.06, so there should be a changes entry.

**Comment by xclerc** [comment]
Here it is.

**Comment by lpw25** [comment]
I see other people are still cherry-picking bug fixes into 4.07, so if you move the changelog entry to the 4.07 section then I'll do that now.

**Comment by damiendoligez** [comment]
@lpw25 OK for cherry-picking.

**Comment by lpw25** [comment]
Merged and cherry-picked onto 4.07 as d0cbd118c6

**Pull request merged**
