### PR TITLE
dynlink: improve dynlink_compilerlibs dependencies

### PR DESCRIPTION
**Pull request by gasche**
Before this PR, dynlink_compilerlibs/foo.cmi would not depend on
dynlink_compilerlibs/foo.mli, resulting in object files not being
properly recomputed in incremental-rebuild scenarios.

Because dynlink_compilerlibs/foo.mli depends on
dynlink_compilerlibs/.depend which in turn depends on all copied
source files, the present change has the impact of having the .depend
being regenerated much more often. We change its generator from
$(CAMLRUN) boot/ocamlc to $(BEST_OCAMLDEP) (using ocamlc.opt
when available); on my machine, when ocamlc.opt is available, the
.depend step goes from 0.6s to 0.2s.

### CODE REVIEW

**Comment by gasche** [comment]
(cc @lthls, who reviewed a similar PR, and @mshinwell who wrote the original Makefile)

**Comment by dra27** [comment]
In the Git sense, @mshinwell gets the blame, but in fact I think I ended up (re-)writing most of it 😆

This is correct, but there are some caveats, especially noting your https://github.com/ocaml/ocaml/pull/2268#issuecomment-568917032 - this means that `.ml` files must have an accompanying `.mli` (in particular, it means you cannot rename a `.mli`-only module to `.ml`).

**Review by dra27 — APPROVED** [review]
For the `.depend` issue, it's up to you if you'd like to change it in this PR or in a future one, but given that none of the rest of the tree regenerates dependencies automatically, perhaps it would be better to stop the `.depend` file being automatically regenerated? I think can be "simply" achieved by touching a cookie, depending on that, and putting the source files themselves as indirect dependencies (so after a `|`)

**Comment by gasche** [comment]
You are completely correct that the `.cmi -> .mli` dependency means that .ml-only units are not possible -- I had not foreseen that restriction. I think this is a reasonable assumption to make because (1) it is true today, (2) the way we rely on it means that if it becomes false tomorrow, things will fail in a  very visible way ("no rule to make foo.mli"), and (3) the build system of the dynlink package already takes care of creating a .ml file for .mli-only modules (by copying), I suppose it could be extended to create a .mli file for .ml-only modules.

(Note: it's easy to create an .ml file for a .mli, it's just a copy, while it may in general be more tricky to generate a .mli file for a .ml module. This suggests that maybe keeping .mli-only units is the better choice than keeping .ml-only units, contrarily to what I said in https://github.com/ocaml/ocaml/pull/2268#issuecomment-568917032. I'm not sure what is the right choice, and in any case the mli-related fix I made in #9211 preserves the ability to have .mli-only modules, so I didn't have to create any .ml-only module in the end.)

**Comment by gasche** [comment]
For `.depend`, I really don't know much about this part of the build system, and I would be happy to leave its evolution to other people :-) I'm personally fine with the way the thing is generated, as long as the dependencies are correct.

**Comment by gasche** [comment]
Ah: you are in fact not suggesting to change the `.depend` generation process, but to change the Makefile dependencies around the `.depend` file. I don't know about Makefile indirect dependencies with `|`, do you have a pointer to an explanation or a similar use somewhere else?

**Comment by gasche** [comment]
Thanks @dra27; I (updated the Changes) and added an explicit comment on the fact that `.ml`-only units are not supported by this part of the build system.

**Comment by dra27** [comment]
GNU make calls them "order-only dependencies" - see https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html. If the target is built (i.e. if `.depend` is missing) then they are respected as dependencies and built first, as you'd expect. The difference is that order-only dependencies can't cause the target to _require_ rebuilding on their own.

Thinking again, it doesn't need a make cookie - I think it's just literally a case of putting the dependency on the source files to the right of a `|`.

All that said, I'm in the camp that would like us to be generating the dependencies anyway! This particular depend file is a funny (and possibly unique?) case in the tree.

**Comment by dra27** [comment]
(TL;DR go ahead and merge!)

**Comment by gasche** [comment]
I merged. Thanks for the explanation and the pointer!

**Pull request merged**
