### PR TITLE
non-Linux power support cleanup

### PR DESCRIPTION
**Pull request by shindere**
This PR removes a few traces of support of non-Linux power
architecture in configure.

### CODE REVIEW

**Comment by ksromanov** [comment]
Do you still have machines with `AIX 4.3` and `POWER`? If not, you can remove lines

```
For AIX 4.3 with the IBM compiler xlc:

./configure -cc "xlc_r -D_AIX43 -Wl,-bexpall,-brtl -qmaxmem=8192"
```
from `INSTALL.adoc`.

Does `ocaml` compile for `PowerPC`-based versions of `OSX`? This system is also mentioned in `INSTALL.adoc`.

**Comment by shindere** [comment]
Konstantin Romanov (2019/03/22 19:36 -0700):
> Do you still have machines with `AIX 4.3` and `POWER`?

I don't think so.

> If not, you can remove lines
> 
> ```
> For AIX 4.3 with the IBM compiler xlc:
> 
> ./configure -cc "xlc_r -D_AIX43 -Wl,-bexpall,-brtl -qmaxmem=8192"
> ```
> from `INSTALL.adoc`.

Sure! That's a good idea, thanks!

> Does `ocaml` compile for `PowerPC`-based versions of `OSX`? This
> system is also mentioned in `INSTALL.adoc`.

I dont think so, either.

Thanks for your PR to my branch! I have merged it and rebased the branch
on latest trunk. would be great if somebody could approve/merge, if this
is okay.

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by xavierleroy** [comment]
Historical notes.  In 2014, with support from IBM, I revised the PPC (Power and PowerPC) port of OCaml to handle 64-bit PPC, little-endian and big-endian, in addition to the existing 32-bit PPC support.  (See e.g. commit 8815d7e1 .) In passing I removed support for MacOS and the BSDs on PPC 32 bits, because MacOS on PPC was long dead and because I didn't quite know what was going on with the BSDs.  I forgot to update the configure script, however.  

Now it's 2019 and nobody noticed the disappearance of PPC/BSD, so let's remove it from configure.

**Comment by avsm** [comment]
The OpenBSD/macppc port has been broken for a few years now due to the switch of that platform to PIE, so there is an actual code generation problem as well.  Sadly my venerable Powerbook G4 Titanium only switches on when I wiggle the power lead in a particular way now, so this hardware is indeed just historical and not worth the effort...

(cross-referencing https://github.com/ocaml/ocaml/pull/1409 where there was some discussion)

**Pull request merged**
