### PR TITLE
safe-string: clarify the relation between configure- and compile-time options

### PR DESCRIPTION
**Pull request by gasche**
There is a subtle interaction between the configure-time and compile-time options for string immutability: the configure-time option `-safe-string` guarantees that strings will always be immutable (which enables optimizations and different types in the C FFI), whereas compile-time `-safe-string` or `-unsafe-string` only set a preference on a per-module basis. If configure-time `-safe-string` is explicit set, `-safe-string` is ignored at compile-time and `-unsafe-string` is rejected.

#1252 switched `-safe-string` to be the default compile-time option (it is included in 4.06). This is not the same thing as setting the `-safe-string` configure-time option by default. Unfortunately, there is currently no configure-time way to revert this change that affects all OCaml packages, so users don't have a proper escape hatch to use `-unsafe-string` by default (for example if their dependencies don't build with `-safe-string`).

The present PR implements a richer configure-time language to be able to explicitly request both the previous and the current default. This is done by separating two sorts of configure-time flags: (un)safe-string decdes whether we force string immutability (`-unsafe-string` is the current default), and (un)safe-string-default decides what the compile-time per-module default is (`-safe-string-default` is the current default, `-unsafe-string-default` was the <4.06 default).

Note: My first attempt to implement something like this had a single, three-valued configure-time `-safe-string` option, which could be set to `safe` (safe-string), `unsafe` (unsafe-string, unsafe-string-default; pre-4.06 default) and `prudent` (unsafe-string, safe-string-default; 4.06 default). You can see the corresponding patch in my branch, 2d577af2f47ab3fdf9e3d3c6609332fb2bf312fa .

(cc @damiendoligez @alainfrisch @jpdeplaix)

### CODE REVIEW

**Comment by gasche** [comment]
I had to make a minor change to get Windows builds to work: I had not realized before that, when you add a new config/Makefile option, you have to manually add it to the config/Makefile.{mingw,msvc}{,64} files.

**Comment by dra27** [comment]
But at least you now have meaningful AppVeyor results to guide you to these things 😇

**Comment by kit-ty-kate** [comment]
Overall it seems to be a reasonable proposal. If I understand it correctly maybe it could be possible to also "safely" prevent any escape hatches (```export OCAMLPARAM``` and compile-time ```-unsafe-string```) in case the "strict" ```safe-string``` mode is enabled ?

However I find the name ```safe-string-default``` a bit misleading. What about replacing it by a new ```safe-string-scope``` option with two values (```universe``` or ```module``` for instance) ?
In this regard I found a weird bug if I try to enable both ```safe-string``` and ```unsafe-string-default``` at the same time: ```string = bytes``` but ```-unsafe-string``` is forbidden because apparently ```safe-string``` is enabled.

**Comment by gasche** [comment]
> If I understand it correctly maybe it could be possible to also "safely" prevent any escape hatches (export OCAMLPARAM and compile-time -unsafe-string) in case the "strict" safe-string mode is enabled ?

I don't understand, can you clarify? The goal indeed is that if `-safe-string` is used at compile-time, then it is *impossible* to set unsafe-string for a module (either OCAMLPARAM or command-line options should fail).

> However I find the name safe-string-default a bit misleading.

Proposals are welcome. (Do you prefer the `-safe-string`, `-prudent-string`, `-unsafe-string` split of the alternative implementation?). Your proposal is too complex (let's keep configuration values boolean for consistency and simplificity). Personally I find that the naming is not perfect but I think it's good enough for an advanced/niche feature -- and there is documentation of what the options mean in both `configure` and `utils/config.mli`.

**Comment by gasche** [comment]
> In this regard I found a weird bug if I try to enable both safe-string and unsafe-string-default at the same time: string = bytes but -unsafe-string is forbidden because apparently safe-string is enabled.

Indeed, this is a bug, it should have been rejected. Will fix right now.

**Comment by kit-ty-kate** [comment]
> I don't understand, can you clarify? The goal indeed is that if -safe-string is used at compile-time, then it is impossible to set unsafe-string for a module (either OCAMLPARAM or command-line options should fail).

Well I tried and at least the OCAMLPARAM escape hatch still works. I was proposing to forbid it.

> Proposals are welcome. (Do you prefer the -safe-string, -prudent-string, -unsafe-string split of the alternative implementation?).

Yes, I like your ```prudent-string``` proposal better. I believe it describes the gradual process of the safe-string acceptance better.

**Comment by gasche** [comment]
> Well I tried and at least the OCAMLPARAM escape hatch still works. I was proposing to forbid it.

This is the same issue as your "weird bug". Thanks for the report! It is now fixed.

(To my defense, the bug comes not from code added in my patch, but from the fragility of existing compiler code that checked `Clflags.unsafe_string` without checking for `Config.safe_string` first. We cannot hope to reliably protect all writes to a Clflags reference, so it is much safer to guard its read by a Config.safe_string check as is now done in my patch.)

Note that, in theory, it would be possible/sound to allow someone to explicitly set `-unsafe-string` in a switch configured with `-safe-string`, because the information is stored in the compiled interface, and linking with another module will be forbidden unless it also used `-unsafe-string`. I don't see the use-case for this, and it would require more strengthening of the compiler codebase (currently for example the immutability-based string optimizations would still work there), so this is forbidden by this PR.

**Comment by gasche** [comment]
With feedback from @damiendoligez I renamed the configure-time options: `-(no-)force-safe-string` (was previously `-(un)safe-string`) and `-default-(un)safe-string` (was previously `-(un)safe-string-default`). Only the `./configure` options where change, we cannot change `Config.safe_string` for compatibility (and I kept the C define `CAML_SAFE_STRING` for consistency with `Config`).

**Review by damiendoligez — APPROVED** [review]
LGTM

**Comment by gasche** [comment]
Cherry-picked in 4.06 ( https://github.com/ocaml/ocaml/commit/925ee7ea91e13083b9bcee3a13c5e7c743bf4b43 and https://github.com/ocaml/ocaml/commit/f8775b4149472363d2e8fecdeff99bc6c946826f ).

**Pull request merged**
