### PR TITLE
Ignore compatible --disable options in configure

### PR DESCRIPTION
**Pull request by dra27**
There will never be naked pointers again - for compatibility, we should keep the define for `NO_NAKED_POINTERS` in `m.h` and `NAKED_POINTERS=false` in `Makefile.config.in`, but there's no value in any of the rest of the codebase using it, which the first commit cleans.

I believe the update to the comment for `Obj.reachable_words` is correct?

Finally, when an option is removed from configuration, we keep the `AC_ARG_ENABLE` because it is clearer to explain to the user that the option requested no longer exists than to allow autoconf's default behaviour for an unrecognised option. This was done previously with the removal of vmthreads, spacetime and the graphics library.

The code used displayed an error for **both** `--disable-foo` and `--enable-foo`. However, there's no need to display an error for the `--disable-foo` parameter, since that's just being explicit about the new "default". This probably didn't come up with the previous three because graphics was trivially disabled on Unix by not having the libX11 headers (which are often not there by default anyway), vmthreads was unused and spacetime was off by default and so the `--disable-` forms were just less commonly used.

However, this isn't so true for CI-cache-saving systems which use options like `--disable-bigarray-lib` to squeeze a few more kilobytes out of freely available cache quotas. This commit tweaks the m4sh so that `--disable-spacetime`, `--disable-naked-pointers`, `--disable-naked-pointers-checker`, `--disable-vmthreads`, `--disable-graph-lib` and `--disable-bigarray-lib` are now silently ignored.

This completes https://github.com/ocaml/ocaml/pull/10831#discussion_r774656781

### CODE REVIEW

**Comment by xavierleroy** [comment]
Thank you for the cleanup work!  I fully agree with the first two commits.  I'm neutral about the third commit (ignoring configure options that are now the default).  Why should OCaml users keep passing these options?

**Comment by dra27** [comment]
It's not so much OCaml users, as some of its developers! I cannot remember exactly what it was, but I have certainly done a huge bisect in the past for something which required `--enable-force-safe-string`. In its present state, for the bisect you have to work out which side of this change you are as to whether you pass `--enable-force-safe-string` (etc.) or whether it's now the default vs just always passing that (automatically, as part of `git bisect run`). A variant of this is presently breaking FlexDLL's "trunk" build of OCaml because it passes `--disable-bigarray-lib` for 4.08+ (to save build time and, more importantly, precious AppVeyor cache quota).

So the rationale is that we want to keep the `AC_ARG_ENABLE`/`AC_ARG_VAR` for proper error messages and, at the cost of just one extra `AS_IF`, allow `configure` more simply by the odd developer by _ignoring_ compatible options. The main thing is that all this only goes as far as `configure` - there's no vestige of this in the build system or, even worse, the compiler itself!

**Comment by xavierleroy** [comment]
We need to make progress here.  We have two unquestionable commits that are blocked by a third, opinionated commit.  Could we get another opinion?  Or just merge the first two commits right now.

**Comment by gasche** [comment]
>  Could we get another opinion?

Reviewing is hard, but opinions: any day!

I would agree with @dra27 that accepting irrelevant options that were relevant in the past is a good choice. (Of course, we should not silently accept options that are incompatible with the current state.) In general I fully trust @dra27's instincts on good UI for configuration across versions, tools, "windows core runtime libraries" and all that horrible stuff.

**Comment by dra27** [comment]
Thanks, @gasche - I've gone with it as I'm just sorting out another part of FlexDLL for another task, and it'd be useful for that CI to work, too.

**Pull request merged**
