### PR TITLE
Remove gprof support

### PR DESCRIPTION
**Pull request by mshinwell**
Following a discussion on the core developers' list, which indicated that removing `gprof` support was a reasonable thing to do, this patch does just that.

The rationale is that there are better easy-to-use profilers out there now, such as perf for Linux and Instruments on macOS; and the gprof support has always been patchy across targets.  We save a whole build of the runtime and simplify some other parts of the codebase by removing it.

I'm marking this as a debugging-prerequisite since a final decision is needed on this before we can proceed with #2292, which is directly needed for the debugging work.

### CODE REVIEW

**Comment by xclerc** [comment]
Should this PR also delete `tools/ocamlprof.ml`?

**Comment by mshinwell** [comment]
I believe it should not: `ocamlprof` is a separate tool for instrumentation, unrelated to `gprof` as far as I know.

**Comment by stedolan** [comment]
There is also a chunk of profiling-related stuff to be deleted in `asmrun/i386.S` and `asmrun/arm.S`. Grep for `mcount`.

**Comment by xclerc** [comment]
Oh, OK, I thought `ocamlprof` was meant to be the implementation of `ocamlcp`.

(It should probably not block this PR, but at some point both the manual and the
man pages should be refreshed.)

**Comment by mshinwell** [comment]
Yeah, I am about to fix the manual.  And in fact I don't think `ocamlcp` should be removed, so I'm resurrecting that.  I've found various other things that need removing too -- another changeset coming soon.

**Comment by mshinwell** [comment]
Ah, so in fact `ocamloptp` is for `ocamlprof` as well, so that should stay.

**Comment by mshinwell** [comment]
New version pushed.

**Comment by stedolan** [comment]
This patch deletes `profiling` from `ocamlc -config`. Have you tested that this doesn't break package builds? Or is the intent to update any build systems with fragile `-config` parsers before 4.09? Alternatively, would you consider leaving `profiling: false` in `ocamlc -config`?

**Comment by mshinwell** [comment]
I did wonder about that.  @dra27 Do you think we should leave the line in the `-config` output, always `false`?

**Comment by avsm** [comment]
Given it's early in the 4.09 release cycle, we could remove it from the `-config` output and see if anything breaks. It can always be restored subsequently if it is a problem.

**Comment by mshinwell** [comment]
@avsm I think I'm in favour of doing that.

@stedolan Since you've looked at this partially, would you be able to review the rest and approve?  (I would like @xavierleroy 's signoff before we merge, however.)

**Review by stedolan — CHANGES_REQUESTED** [review]
Code changes look good to me! There's a couple of other places where references to profiling should be removed, though:

  - driver/main_args.ml: `mk_p` has now-wrong text for the `-p` option
  - stdlib/Compflags: has rules for `foo.p.cmx`
  - stdlib/.depend: has .p.cmx dependencies. (It looks like you updated the .depend generator, so I think all you should need to do here is rerun `make depend`)
  - manual, manpages

**Comment by mshinwell** [comment]
Thanks, I will check these.  I thought I dealt with the manual though.

**Comment by stedolan** [comment]
I don't see any changes to `manual/` here?

**Comment by mshinwell** [comment]
I think I must have lost those somehow.  I've done them again, there will be an update shortly.

**Review by stedolan — APPROVED** [review]
I was surprised that stdlib/.depend got so much shorter. Turns out there were duplicate entries for all the `cmo` files because of how the profiling dependencies were generated!

**Comment by mshinwell** [comment]
@gasche Given that @xavierleroy probably hasn't had time to look at this, are you willing to confirm that this feature removal is ok?

**Comment by gasche** [comment]
I'm afraid I can't replace Xavier in terms of decision-making legitimacy. If you want "formal approval", maybe it's okay to wait an extra week? (I'll meet him on Wednesday/Tuesday so that's a worst-case timeline for an answer.)

**Comment by mshinwell** [comment]
Sure, we can wait.

**Comment by xavierleroy** [comment]
I had a quick look at the diff and it looks OK.  I just started a round of precheck CI to make sure all architectures still compile and run.

**Comment by xavierleroy** [comment]
Precheck seems happy.  Based on this, @stedolan's careful review, my own cursory check, and my pleasure at seeing so much boring code going away, I'm happy to merge this PR right now.

**Pull request merged**
