### PR TITLE
Proper #help for toplevel and #show

### PR DESCRIPTION
**Pull request by berke**
See http://caml.inria.fr/mantis/view.php?id=6113

### CODE REVIEW

**Comment by gasche** [comment]
I would like to move forward and merge the pull request. @berke , could you add a Changes entry in the "Toplevel and debugger" section? (Entries are sorted by PR number).

**Comment by berke** [comment]
Added a Changes entry for PR#6113.

**Comment by gasche** [comment]
Thanks @berke . I rebased your changes against trunk in 70ee3c48cab1ff735653c0dc7fc6f5abc2ab787e in a personal branch [toplevel-branch](https://github.com/gasche/ocaml/tree/toplevel-help). One remaining issue is that you use tabulation boxes that were deprecated by Pierre Weis during this development cycle. Could you maybe rework the `dir_help` code to print it in a different way?

**Comment by berke** [comment]
Hi Gabriel,

I didn't see any Format functionality to replace the tabs, so I have added a few lines of code to calculate column widths manually.

**Comment by gasche** [comment]
Merged in trunk after some changes following #376 and personal bike-shedding. Thanks!

**Comment by UnixJunkie** [comment]
thanks to all contributors for this nice, user-friendly, addition to the toplevel

**Pull request closed without merging**
