### PR TITLE
Fix MPR#7259 by implementing switch branch sharing for flambda

### PR DESCRIPTION
**Pull request by chambart**
This implements only what is needed to share or-patterns. A complete comparison function (handling substitution) is quite difficult on flambda (due to some undefined orders in let-rec and sets of closures), hence we restrict to what is really needed.

### CODE REVIEW

**Comment by gasche** [comment]
http://caml.inria.fr/mantis/view.php?id=7259

**Comment by gasche** [comment]
@maranget any opinion on the change to the Switch argument signature? It seems fine to me.

**Comment by maranget** [comment]
@gasche Agreed, the change looks harmless.

**Comment by omion** [comment]
Minor typo: Changes lists
`report by uers 'omiom'`
which should be
`report by user 'omion'`

(My actual name's Reed Wilson - I don't know if you'd prefer to use that. Either way's fine by me)

**Comment by damiendoligez** [comment]
> (My actual name's Reed Wilson - I don't know if you'd prefer to use that. Either way's fine by me)

You're supposed to choose which one you want in `Changes`. We have a slight preference for real name but it's really up to you.

**Comment by gasche** [comment]
When people say they're fine with both, I usually pick the real name because I think sometimes it later turns out that they can mention this work in a professional context and it's easier if it's by-name rather than by-pseudo. (And people may not realise that or think that it matters at the time of submission, yet be glad later.) If people change their mind and prefer to remain pseudonymous we can always edit the changelog (but of course old releases will still have the previous name).

Unrelatedly: what we would need to move forward on this PR is a review/decision from someone that is familiar with the flambda side of the change.

**Comment by mshinwell** [comment]
I've reviewed this and tidied a few things up (including correcting a mistake in the comment).  I discussed with @lpw25 and we are happy to merge this.  Apart from anything else, it fixes a regression, and I think had we had more time we would have fixed this before the initial Flambda release.  In due course, probably after we've finished the first CPS-flambda version, we will also be considering matters relating to code de-duplication further.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
