### PR TITLE
-dno-locations: hide source locations (and debug events) from intermediate-representation dumps

### PR DESCRIPTION
**Pull request by gasche**
Source locations (and debug events) can hinder readability of intermediate-representation dumps. Compare for example (from the new testsuite items):

Before:
```
(setglobal With_locations_byte!
  (letrec
    (fib/80
       (function n/81[int] : int
         (funct-body with_locations_byte.ml(8):191-249
           (if (isout 1 n/81)
             (before with_locations_byte.ml(10):224-249
               (+
                 (after with_locations_byte.ml(10):224-235
                   (apply fib/80 (- n/81 1)))
                 (after with_locations_byte.ml(10):238-249
                   (apply fib/80 (- n/81 2)))))
             (before with_locations_byte.ml(9):213-214 1)))))
    (pseudo _none_(0)<ghost>:-1--1 (makeblock 0 fib/80))))
```

After:
```
(setglobal Without_locations_byte!
  (letrec
    (fib/80
       (function n/81[int] : int
         (if (isout 1 n/81)
           (+ (apply fib/80 (- n/81 1)) (apply fib/80 (- n/81 2))) 1)))
    (makeblock 0 fib/80)))
```

### CODE REVIEW

**Comment by gasche** [comment]
(cc @lthls @chambart ; this PR and #9200 saved me pain while tracking down a bug across `-dlambda` and `-dcmm` outputs, and I think they could help others as well.)

**Comment by lthls** [comment]
I'm not very fond of having tests that will fail for any slight modification to the compiler, but the feature itself is nice and I haven't found anything to nitpick in the implementation.

**Comment by gasche** [comment]
@lthls thanks for the feedback. Are you suggesting that I should remove the test, or parts of the test? (Personally I am fine with using `make promote` to update tests outputs automatically, and I don't dislike seeing the impact of compiler changes on the testsuite recorded IRs.) Would you be willing to eventually approve the PR, so that it can get merged?

**Comment by lthls** [comment]
I'm not sure how useful the tests are when the first reflex when it fails is to run `make promote`, but if you can get it to pass CI I can live with it.

I would usually wait until CI is green to approve, but given that the problem is only in crafting the right kind of test and I trust you not to merge with a broken CI, I can approve now.

**Review by lthls — APPROVED** [review]

**Comment by gasche** [comment]
Even if you run `make promote`, one see the changes in the git diff, and I find that helpful. When reviewing the test-changing PR, it gives me an example of the kind of changes brought by the PR. (But I agree that it adds some small friction; if the test turns out to be too frequently updated, we can remove or refine it.)

**Comment by gasche** [comment]
Note: the test failure comes from 32bits systems doing register-allocation differently. I will drop the output for the compiler phases that are not portable. (We could also restrict the relevant tests to only run on amd64, but meh.)

**Pull request merged**
