### PR TITLE
packed modtype lookup can fail due to missing cmi

### LINKED ISSUE #9406: File "typing/typemod.ml", line 1817, characters 27-33: Assertion failed
With OCaml 4.10, I get an assertion failed from the compiler when a transitive dependency is missing:

```bash
$ docker run --rm -it ocurrent/opam:debian-10
$ git clone https://github.com/talex5/typemod-crash.git
$ cd typemod-crash
$ opam depext -i dune
$ dune build @check
      ocamlc examples/.test.eobjs/byte/test.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I examples/.test.eobjs/byte -I lib/.current.objs/byte -I lib/.current.objs/native -no-alias-deps -opaque -o examples/.test.eobjs/byte/test.cmo -c -impl examples/test.ml)
Fatal error: exception File "typing/typemod.ml", line 1817, characters 27-33: Assertion failed

$ ocaml --version
The OCaml toplevel, version 4.10.0
```

OCaml 4.08 and 4.09 instead print:

```
Error: Unbound module type Current_term.S.ORDEREDFatal error: exception Not_found
```

Note that `dune-project` has `(implicit_transitive_deps false)`, and adding the `current_term` dependency to `examples/dune` fixes it.

### PR DESCRIPTION
**Pull request by Octachron**
Closes #9406: 

This PR makes module types from missing cmis behaves the same as abstract module type everywhere.

This was already the case in nearly all cases, except for a forgotten case in the function `Typemod.modtype_of_package`.

After this change, there is no call site of `Env.find_modtype`  that distinguish  between the case `None` and `exception Not_found`. It would probably make sense to fold the two cases into one.

### CODE REVIEW

**Comment by Drup** [comment]
Sounds good. This fixes the bug and make the behavior consistent again. The patch and tests look fine.

I would prefer if missing `cmis` were actually an error, but that's a contentious topic for another time. :)

**Comment by gasche** [comment]
> It would probably make sense to fold the two cases into one.

You are proposing that `Env.find_modtype` would never raise `Not_found` and only return `None`? (Are you planning to submit a PR?)

**Comment by Octachron** [comment]
Rereading the code, it would rather be a version of `find_modtype_expansion` that returns an option rather than raise a `Not_found` exception.

Maybe, we could split `find_modtype` into `find_modtype_decl`  for finding the declaration of the module type and `find_modtype` for looking up just the type with the `Not_found` -> abstract translation.
I am willing to submit a PR if we agree on a design.

**Comment by Octachron** [comment]
Reviewing the fix, I would prefer to start with integrating the current bugfix PR (to integrate the test) before potentially moving on to a refactoring PR.

**Review by gasche — APPROVED** [review]
The fix looks obviously correct. Approving. This is good to go if the CI passes and the patchset is rebased appropriately, please feel free to merge. (I will probably forget to do it myself.)

**Pull request merged**
