### PR TITLE
Fix float_of_hex parser to correctly reject some invalid forms.

### PR DESCRIPTION
**Pull request by bogdan2412**
Such as 0x, 0x., 0x.p0, 0xp0.
Added unit tests for these particular instances.

### CODE REVIEW

**Comment by braibant** [comment]
Reviewed the diff, this looks good.

**Comment by alainfrisch** [comment]
This PR also adds unrelated tests.  Is it on purpose?

**Comment by bogdan2412** [comment]
The PR only adds tests for float_of_string, specifically for the branch which causes it to call float_of_hex.

The other changes to test cases you see in the PR are not adding anything, but simply moving some modules that were used by one existing test from the same directory into the actual test file.  This was the simplest way I could figure out to allow both the old and new test coexist in the same directory.

**Comment by alainfrisch** [comment]
Thanks!

**Pull request merged**
