### PR TITLE
Compiling for Haiku OS: network functions reside in libnetwork

### PR DESCRIPTION
**Pull request by Sylvain78**
In Haiku, the network functions are in libnetwork.
I added the configure file too in the commit, but it should be rebuild hrough autoconf.

### CODE REVIEW

**Review by dra27 — CHANGES_REQUESTED** [review]
You appear to have manually re-run `autoconf` rather than `make -B configure`?

**Comment by Sylvain78** [comment]
> You appear to have manually re-run `autoconf` rather than `make -B configure`?

Yes. I wasn't aware of this way to recreate configure.

**Review by dra27 — APPROVED** [review]
The skipping of the function checking looks weird, but that's already "wrong" for mingw/msvc, so I don't think that's a worry here.

The docs for Haiku weren't entirely clear to me - it's always `-lnetwork` or is it sometimes `-lnet`?

This seems safe to me, given that it's for a non-supported OS, clearly tagged (and there are other instances) - @shindere, what do you think?

**Comment by dra27** [comment]
(If @shindere's happy with this, please do update the `Changes` file as well)

**Comment by shindere** [comment]
The change looks fine to me, thanks.

It would indeed be nice to have an entry added to the Changes file.
Also, it is important that the two commits get squashed so that
configure stays in sync with configure.ac at each commit.

Finally, we may want to consider this for 4.11 (@Octachron).

**Comment by Octachron** [comment]
Since it is a well-contained configuration refinement, I think it is fine to backport it to both 4.11.0 and 4.10.1 .

**Comment by xavierleroy** [comment]
For 4.10.1 to work under Haiku, you'd need to backport #9480 at least. I don't think it's worth it.

**Comment by shindere** [comment]
Florian Angeletti (2020/04/27 01:59 -0700):
> Since it is a well-contained configuration refinement, I think it is
> fine to backport it to both 4.11.0 and 4.10.1 .

Good, thanks!

**Comment by dra27** [comment]
Merged, and cherry-picked to 4.11, thanks!

**Pull request merged**
