### PR TITLE
Fixed typo in String.mli

### PR DESCRIPTION
**Pull request by JoanThibault**
replaced 'escape' by 'escaped'

### CODE REVIEW

**Comment by dra27** [comment]
Good spot, but please could you update it in `stringLabels.mli` too - you won't have to run the script noted at the top of string.mli, but Travis will shortly complain!

**Review by gasche — APPROVED** [review]
Looks good, thanks!

**Comment by dbuenzli** [comment]
I don't mind rebasing for that one. But could a decision on https://github.com/ocaml/ocaml/pull/9891 be taken please.

**Comment by JoanThibault** [comment]
> Good spot, but please could you update it in `stringLabels.mli` too - you won't have to run the script noted at the top of string.mli, but Travis will shortly complain!

done

**Comment by JoanThibault** [comment]
I'm not sure, should I make an entry in the Changes file ?

**Pull request merged**
