### PR TITLE
Capitalize the first letter of filenames of the standard library modules

### PR DESCRIPTION
**Pull request by shindere**
This PR implements a suggestion made by @Octachron in
https://github.com/ocaml/ocaml/pull/10451#issuecomment-899302629.

All the files that give rise to modules for the stdlib tget the first letter
of their names capitalized. this allows to remove some complexity in
`stdlib/StdlibModules`. It should also make the build faster on Windows
because the manipulation of filnenames required forking several processes.

Another benefit of this PR is that it removes the `\u` sed construct used
to compute the dependencies of the stdlib, making it possible to construct
them on Mac, where `\u` is not supported.

Also, this PR makes use of `configure` to generate `stdlib/Sys.ml` from
`stdlib/Sys.ml.in` instanciating the VERSION string, which constitutes
one further simplification of the build system.

This PR has been pre-reviewed by @Octachron but since it implements his idea
it's certainly a good idea that somebody else takes a bit of time to review
it.

It's worth noting that capitalizing otherlibs in the same way would allow
the removal of other complex parts of the build system.

which is

### CODE REVIEW

**Comment by pmetzger** [comment]
An asise: on MacOS, builds usually require homebrew or MacPorts, and one can simply have those depend on Gnu sed or some such.

**Comment by dbuenzli** [comment]
My amount of work on the system if very minimal but I once worked on a very messy code base that had multiple capitalization conventions for the same kind of files and it was incredibly frustrating to work with. I think if you really want to do that you should do it for all of the files of the project. 

But if the point was reached where changing the capitalisation of files makes the build system simpler, maybe it's time for root cause analysis :-)

P.S. Also that may not be important to people but on unix capitalized files are listed by `ls` first. This allows to give prominence to certain files like `README` or `Makefile` (as [recommended](https://www.gnu.org/software/make/manual/make.html#Makefile-Names) by `make`). With that new convention that nice ui feature is lost.

**Comment by nojb** [comment]
I don't have a strong opinion at the moment, but some random thoughts/questions nonetheless:

- if we decide that simplifying the build system justifies renaming files, wouldn't renaming `list.ml` into `stdlib__List.ml` be an even greater simplification?

- if one wanted to avoid the changes in backtraces, line directives could be inserted (eg `# 1 "list.ml"`)...

- the renaming makes it harder to access the git history of affected files (not really possible in the Github UI, need to pass `--follow` in the terminal)

> Also, this PR makes use of configure to generate stdlib/Sys.ml from
stdlib/Sys.ml.in instanciating the VERSION string, which constitutes
one further simplification of the build system.

I would put this in a separate PR as it is easy to review and independent of the renaming.

> It's worth noting that capitalizing otherlibs in the same way would allow
the removal of other complex parts of the build system.

Could you expand on this? As far as I can see there is no capitalization business going on in `otherlibs`...

**Comment by Octachron** [comment]
Daniel Bünzli (2021/08/21 03:58 -0700):
> My amount of work on the system if very minimal but I once worked on a
> very messy code base that had multiple capitalization conventions for
> the same kind of files and it was incredibly frustrating to work with.

Well, that PR would be a first step only, the final idea being to swich
everything to first letter as uppercase.

> I think if you really want to do that you should do it for all of the
> files of the project.

Yes, I agree. It just seemed too ambitious to do it in one step so I
thought better start small, not invest too much time (it already took
more than expected) and see how people react but if this PR gets
accepted I'll continue in the same direction.

> But if the point was reached where changing the capitalisation of
> files makes the build system simpler, maybe it's time for root cause
> analysis :-)

Do you have one particular root cause in mind?

> P.S. Also that may not be important to people but on unix capitalized
> files are listed by `ls` first. This allows to give prominence to
> certain files like `README` or `Makefile` (as
> [recommended](https://www.gnu.org/software/make/manual/make.html#Makefile-Names)
> by `make`). With that new convention that nice ui feature is lost.

Yes, I was aware of doing that and fetl sad about it because I like this
feature, too.
It just felt to me the gain would be bigger than the loss...

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2021/08/21 07:53 -0700):
> I don't have a strong opinion at the moment, but some random thoughts/questions nonetheless:

Sure!

> - if we decide that simplifying the build system justifies renaming
> files, wouldn't renaming `list.ml` into `stdlib__List.ml` be an even
> greater simplification?

Not sure because as far as I understand it the stdlib needs both
prefixed or unprefixed versions so it seems tbetter to me to startwith
unprefixed (simpler) names and add prefixes where appropriate rather
than starting with prefixed names and remove theprefix when needed.

> - if one wanted to avoid the changes in backtraces, line directives
> - could be inserted (eg `# 1 "list.ml"`)...

INdeed. Thanks a lot for the suggestion. Now what remains to be
determined, in case this PR is accepted, is whether it is wise to do
that in the long run, whether it is worth it. For sure it would help
with backwards compatibility, but then it would also mean we would have
to do the same even for files added later. I'd say it all depends on how
many people rely in such informations in backtraces.

> - this makes it harder to access the git history of renamed files (not
> - really possible in the Github UI, need to pass `--follow` in the
> - terminal)

Ah indeed, sorry about that.

> > Also, this PR makes use of configure to generate stdlib/Sys.ml from
> stdlib/Sys.ml.in instanciating the VERSION string, which constitutes
> one further simplification of the build system.
>
> I would put this in a separate PR as it is easy to review and
> independent of the renaming.

I could do that, sure. The gain in portability of this PR would be lost,
though, because we would stick to the `\u` sed construct which is GNU
sed specific.

> > It's worth noting that capitalizing otherlibs in the same way would allow
> the removal of other complex parts of the build system.
>
> Could you expand on this? As far as I can see there is no
> capitalization business going on in `otherlibs`...

Yes, sure, I should have done so right from the beginning, sorry.

See `api_docgen/Makefile.docfiles`, htat's where the other (dupplicated,
I think) capitalization machinery is.

**Comment by shindere** [comment]
Daniel Bünzli (2021/08/21 03:58 -0700):
> My amount of work on the system if very minimal but I once worked on a
> very messy code base that had multiple capitalization conventions for
> the same kind of files and it was incredibly frustrating to work with.

Well, that PR would be a first step only, the final idea being to swich
everything to first letter as uppercase.

> I think if you really want to do that you should do it for all of the
> files of the project.

Yes, I agree. It just seemed too ambitious to do it in one step so I
thought better start small, not invest too much time (it already took
more than expected) and see how people react but if this PR gets
accepted I'll continue in the same direction.

> But if the point was reached where changing the capitalisation of
> files makes the build system simpler, maybe it's time for root cause
> analysis :-)

Do you have one particular root cause in mind?

> P.S. Also that may not be important to people but on unix capitalized
> files are listed by `ls` first. This allows to give prominence to
> certain files like `README` or `Makefile` (as
> [recommended](https://www.gnu.org/software/make/manual/make.html#Makefile-Names)
> by `make`). With that new convention that nice ui feature is lost.

Yes, I was aware of doing that and fetl sad about it because I like this
feature, too.
It just felt to me the gain would be bigger than the loss...

**Comment by dbuenzli** [comment]
> Do you have one particular root cause in mind?

Namespacing via module aliases maybe ?

**Comment by shindere** [comment]
Daniel Bünzli (2021/08/23 02:59 -0700):
> > Do you have one particular root cause in mind?
>
> Namespacing via module aliases maybe ?

I'm sorry -- that's an aspect of the language I never followed tightly.
Could you a bit elaborate on what it is and why you thiink it's the root
cause of which problem?

Thanks!

**Comment by mshinwell** [comment]
I'm afraid I am not in favour of making this change.

The reduction in build system complexity does not seem worth it to me compared to the inconvenience the change seems likely to cause.  In the OCaml world, the established convention is that source filenames start with lower-case letters, and in the majority of cases are entirely lower case.  Having a set of files using a different convention (even if the whole compiler) is bound to lead to repeated paper cuts, with no tangible benefit for the majority of people involved.  Likewise (in fact even more so) for the breaking of the majority of the stdlib's git history.

Changing of the stdlib backtraces is likely to break code in the wild, although the proposal to add line directives is a sensible fix (I was going to propose such a change anyway).

The name mangling convention (and associated build system code) would be removed if the language and compiler had some kind of built-in support for namespacing.  As far as I understand it, there is still at least one semi-active proposal in this area (by @lpw25).  I think renaming of files en masse would be premature whilst such proposals are underway.

More generally, this PR makes me concerned that efforts to improve the build system may not be sufficiently concentrated on areas that would really make a difference to users.  As a suggestion, should there be a priority list?

**Comment by shindere** [comment]
I understand your concerns, Mark, and I am fine with them.

I can close the PR and just submit the configure-related part.

**Pull request closed without merging**
