### PR TITLE
Remove copyright notices in a few test files and fix a typo.

### PR DESCRIPTION
**Pull request by shindere**
The typo is in testsuite/tests/ast-invariants/test.ml

### CODE REVIEW

**Comment by gasche** [comment]
Hi! I suppose that `testsuite/tests/test-files-with-copyright-header` was useful to script the removal, but I'm not sure why you include it in the PR. Do you think it will be useful to have it around in the future?

**Comment by shindere** [comment]
Hello!

Sorry about the file you mention! It was indeed not intended to be
colmmitted. I will remove it from the PR ASAP (tomorrow).

**Comment by shindere** [comment]
PR rebased, completed and cleaned up. Hope it's okay now, sorry for the
trouble.

**Comment by gasche** [comment]
I merged the PR (I squashed the two commits into a single one) Thanks!

**Comment by shindere** [comment]
Gabriel Scherer (2016/05/03 04:39 -0700):

> I merged the PR (I squashed the two commits into a single one) Thanks!

Thanks to you! I must have forgotten an --amend somewhere!

Sébastien.

**Pull request closed without merging**
