### PR TITLE
recommended_domain_count: unit -> int

### PR DESCRIPTION
**Pull request by gasche**
See https://github.com/ocaml/ocaml/pull/11309#issuecomment-1246285856. (cc @xavierleroy, @haesbaert )

### CODE REVIEW

**Review by haesbaert — APPROVED** [review]

**Review by damiendoligez — APPROVED** [review]
LGTM

**Comment by xavierleroy** [comment]
@octachron: is it still time to have this change in 5.0 ?  Otherwise we'll have an incompatibility between 5.0 and 5.1.

**Comment by Octachron** [comment]
We really want this change in 5.0: it is better to break the API before the first 5.0 beta and hope that no one has yet a critical system in production that depends on the 5.0~alpha1. That might be less true if we wait for 5.1 .

**Review by xavierleroy — APPROVED** [review]
OK, let's have this in 5.0.

**Comment by xavierleroy** [comment]
Cherry-picked to 5.0: 4a609989c7

**Pull request merged**
