### PR TITLE
Add `-c-impl` option

### PR DESCRIPTION
**Pull request by lpw25**
This PR adds a `-c-impl` option analogous to the `-impl` option, which forces `ocamlc` and `ocamlopt` to consider a file as a C file even when its extension is not `.c`.

### CODE REVIEW

**Comment by damiendoligez** [comment]
You're unconditionally passing a `-x` option to the C compiler. Is this portable across exotic architectures? I'm thinking of Intel's and Sun's compilers in particular.

**Comment by lpw25** [comment]
Ah I'd forgotten about the Sun compiler. It doesn't seem to have any option for specifying the language of an input file. All the others I could think of (intel, pcc, clang, gcc) use `-x` except msvc which uses `/Tc`.

Not sure what to do about that. I guess we could test for `-x` at configure time and disable this feature in that case. Or create a tempory copy of the c file with a `.c` extension.

**Comment by dbuenzli** [comment]
> Not sure what to do about that. I guess we could test for -x at configure time and disable this feature in that case.

Please don't, that would lead to unportable build systems.

**Comment by avsm** [comment]
What's the motivation for wanting this in the first place?  Your solution of:

> Or create a tempory copy of the c file with a .c extension.

...seems far simpler and more portable.

**Comment by lpw25** [comment]
Avoid completely unnecessary copying and unnecessary complication of build rules. Essentially the same reasons for having `-impl` and `-intf`.

I think that having configure detect `-x` compatibility and then fall back to doing its own copying would be best.

**Comment by lpw25** [comment]
Oh probably also to give proper error locations without having to use `#line` directives.

**Comment by damiendoligez** [comment]
A symbolic link will be faster than a copy...

**Comment by lpw25** [comment]
Adding the support for the Sun compiler is more effort than I think I want to put into this PR, and it has sat here for a long time, so I'm closing.

**Pull request closed without merging**
