### PR TITLE
add colored output to ocamltest

### PR DESCRIPTION
**Pull request by c-cube**
Tests ought to be cheerful! Also, I heard that green was good for morale :green_heart:

### CODE REVIEW

**Comment by nojb** [comment]
Could you post a screenshot to see what it looks like ? (NB you can paste screenshots directly into a Github comment).

**Comment by gasche** [comment]
I'm not too excited with having the change proposed now.

1. It completely destroys the CI:

```
Summary:
  246 tests passed
   41 tests skipped
    0 tests failed
  987 unexpected errors
  1274 tests considered
```

2. It introduces a difference between the way ocamltest-based and makefile-based tests behave, which is bound to make someone's life difficult during the rest of the transition period (see above: CI completely broken).

3. The API is meh (I'm not sure why `string_of_result` takes an optional parameter set to `true` by default: it could just look at `Options` internally, or it is part of its interface to specify colors and then the parameters should not be optional.

4. That may not be an actual concern, but I have mixed feelings about spending time discussing color output changes for a tool that was designed and is actively developed and maintained by a blind developer.

I think (2) is probably the strongest point, and it suggests maybe waiting for the new era where all tests will be ocamltest-based before making these kind of output changes.

**Comment by shindere** [comment]
Thanks a lot for the PR and for the comments.

I did not look to the code yet so I will only comment the idea itself.

1. I very much appreciate people starting to talk about ocamltest. I
find this in itself to be a very cool thing.

2. If colours make the life of people that have the handicap of needing
them easier ( ;-) ),  then I am very much in favour of colours. You
sighted guys have the right to have an accessible world, too! :)

More seriously, if colours help I am very fine with adding them and at
the same time I very much appreciate @gasche's concern.

3. I indeed don't know what would be the best moment to add the but
let's continue discussing the matter!

**Comment by dra27** [comment]
Having spent a lot of time recently getting colour and VT100 working properly in Windows opam, I agree that it's useful - but I think @gasche's point 2 is the most important. Let's at least not then this feature on by default until all the tests are ported.

**Comment by c-cube** [comment]
Oh, sorry, I didn't realise ocamltest was that fresh. It was simple to modify, so I'll try to redo this once the migration is over :+1:

**Comment by shindere** [comment]
Simon Cruanes (2018/03/20 06:32 -0700):
> Oh, sorry, I didn't realise ocamltest was that fresh. It was simple to modify, so I'll try to redo this once the migration is over :+1:

Thanks! I take the "simple to modify" as a compliment! :)

**Pull request closed without merging**
