### PR TITLE
On CI, install after running tests

### PR DESCRIPTION
**Pull request by dra27**
WIP fixing trunk breakage caused by #1035 - waiting for CI response before pushing more commits.

### CODE REVIEW

**Comment by damiendoligez** [comment]
But the tests are supposed to be independent of whether the install was done or not. If they aren't, this is a problem we need to solve.

**Comment by dra27** [comment]
Not sure how we can in general - the problem is that the configured standard library directory allows the toplevel to pick up its cmi files?

**Comment by dra27** [comment]
Arguably this is a fix - it means that a dependency on the installation gets highlighted?

**Comment by dra27** [comment]
See also #1024, which I shall be rebasing to catch this scenario too...

**Comment by damiendoligez** [comment]
* We should use the `-nostdlib` option to the toplevel to avoid picking up the stdlib directory.
* Indeed this is a fix. I was confused and thought it was failing because of the already-installed files.

**Comment by dra27** [comment]
No - a rare instance of succeeding because of them! I'll alter Makefile.toplevel to include `-nostdlib`

**Comment by dra27** [comment]
That's weird - it already has -nostdlib

**Comment by damiendoligez** [comment]
I tried adding it to `tests/tools-toplevel/Makefile` and it didn't change anything, so I can confirm the `-nostdlib` flag doesn't work for this purpose.

**Comment by dra27** [comment]
It's already in Makefile.tools so, yes, something is definitely going on. I'm just trying to fix AppVeyor here and then I'll merge to unclog the trunk CI (are you happy with that?) then I'll look further into why the toplevel is picking up topdirs.cmi with -nostdlib.

**Comment by gasche** [comment]
Thanks for merging this -- I was in the process of writing a message to urge you to do it soon. We need a working CI asap.

**Comment by dra27** [comment]
I was sat watching and waiting for Travis to finish!

**Pull request merged**
