### PR TITLE
Make Unix.{getaddrinfo,getnameinfo} Unicode-aware on Windows

### PR DESCRIPTION
**Pull request by nojb**
Unicode host names anyone?

### CODE REVIEW

**Review by xavierleroy — COMMENTED** [review]
The code looks OK to me but I had a rather quick look at it, so it would be good to have a second pair of eyes.

Also, I am still not convinced that [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) are a good idea, with all the spoofing they enable.

**Comment by hannesm** [comment]
I'm a bit sceptical.

Portability: While `GetAddrInfoW` is supported on Windows, there is also an extension (via the `AI_IDN` flag and [more flags](https://www.unix.com/man-page/Linux/3/getaddrinfo/)) for GNU/Linux (but there is no POSIX extension for this - i.e. no way to do this (with libc only) on FreeBSD/OpenBSD/MacOSX).  What C applications usually do is to link against `libidn` (which I do _not_ suggest the OCaml runtime to do). 

This means this PR will introduce divergent behaviour between platforms.  I'd instead document that IDNs are not supported in the stdlib.  There exists [an (unreleased) library](https://github.com/cfcs/ocaml-punycode) which does the punycode conversion in pure OCaml.  Doing this depends on a unicode library, thus it is not suitable for the stdlib IIUC.

OTOH, if divergence between platforms is not an issue, surely this is ok.

**Comment by pmetzger** [comment]
IDN stuff needs to be considered very, very carefully when it is integrated because of the security issues that have been mentioned.

I note that OCaml's own unicode support is not yet quite complete, which makes it harder to figure out a good solution that works for all of OCaml's platforms.

**Comment by nojb** [comment]
@hannesm I was not aware of the `AI_IDN` flag for GNU/Linux and the divergence this PR would introduce, thanks for bringing it to my attention.

Technically speaking the divergence is already there today, because it is possible to use Latin-1 (or local code page encoded) hostnames under Windows but only ASCII under Linux (if I understand correctly).

I do not have a strong argument for merging apart from coherence with the rest of the `win32unix` library which has been shifted from code page encoding to UTF-8. I do not understand all the security implications of merging this at the moment, so I will happily follow the lead of anyone who does.

**Comment by nojb** [comment]
There does not seem to be a consensus for merging this PR, so closing for now. Can always be reopened if needed.

**Pull request closed without merging**
