### PR TITLE
C warnings 4.04

### PR DESCRIPTION
**Pull request by dra27**
4.04 version of #1116.

This includes both of the fixes found by enabling warnings in #1116 and also three of @shindere's fixes.

### CODE REVIEW

**Comment by damiendoligez** [comment]
I have reviewed and found no problem. @shindere could you also have a look?

**Comment by shindere** [comment]
Damien Doligez (2017/04/05 02:16 -0700):
> I have reviewed and found no problem. @shindere could you also have a
> look?

Sure, done. It looks good to me, too. Thanks a lot @dra27!

One thing that could perhaps have been done is to link those commits
that have been cherry-picked to their original trunk counterparts. But I
guess it's perhaps not worth the trouble so this suggestion is perhaps
more for future such commits.

**Comment by dra27** [comment]
@shindere - not entirely sure what you mean by link? git cherry shows:

```

$ git cherry -v trunk bd3405 b262daf
- 46dfad93ce99bb597cdf0de253c54b246576799d Fix implicit function declaration warning in bytern/fix_code.c.
+ 70a92f8d18de311c598d0c87f0c779405d790fa3 Fix a couple of warnings in C code.
- bd34053202bab839d3d7a8369e9a589314b58c7f Get rid of a few redeclarations of functions in C code. (#900)
```

and `diff <(git show f16c5f) <(git show 70a92f)` reveals that I had to make a couple of minor changes to do with Makefile.nt/Makefile changes.

**Comment by dra27** [comment]
A change appears to have been made which has upset the C compiler - I'm just looking into it

**Comment by shindere** [comment]
OK sorry I didn't realise. All's well @dra27.

**Pull request merged**
