### PR TITLE
Update GitHub CI Ubuntu from 22.04 to 24.04

### PR DESCRIPTION
**Pull request by dra27**
This is a rebased and updated version of #13665 - in a fresh PR, because the commits on that branch are passing GitHub Actions on my fork, but for some reason not on the original PR 🤷

### CODE REVIEW

**Comment by dra27** [comment]
I'd thought something funny was going on with caching, but having figured out the issue #13665 is now passing!

**Comment by shindere** [comment]
David Allsopp (2024/12/16 12:55 -0800):
> I'd thought something funny was going on with caching, but having
> figured out the issue #13665 is now passing!

So what is it that was not working and you managed to fix, if I may ask?

**Comment by dra27** [comment]
The build job was being done with 22.04 and cached and then that was being loaded into 24.04 to run the testsuite!

**Comment by tmcgilchrist** [comment]
Thanks @dra27

**Pull request closed without merging**
