### PR TITLE
Add raw_data primitives to avoid naked pointers

### PR DESCRIPTION
**Pull request by lpw25**
In preparing Jane Street's code base for a world without naked pointers, there is one pattern that I am having difficulty removing. Currently, you can keep a pointer to an out-of-heap address in an `int` by tagging it and then dereference it like so:
```ocaml
external int_as_int_array : int -> int array = "%int_as_pointer"

let load_int t =
  let p = int_as_int_array t in
  Array.unsafe_get p

let set_int t i =
  let p = int_as_int_array t in
  Array.unsafe_set p i

external int_as_float_array : int -> float array = "%int_as_pointer"

let load_int t =
  let p = int_as_int_array t in
  Array.unsafe_get p

let set_float t f =
  let p = int_as_int_array t in
  Array.unsafe_set p f
```
In each of those functions the value `p` is a short-lived naked pointer.

I tried replacing these functions with noalloc C functions, but the resulting performance cost was considered unacceptable.

This PR adds some primitives to dereference pointers stored in the recently added `Obj.raw_data` type:
```ocaml
external raw_data_load_int : raw_data -> int = "%rawdata_load_int"
external raw_data_load_float : raw_data -> float = "%rawdata_load_float"
external raw_data_set_int : raw_data -> int -> unit = "%rawdata_set_int"
external raw_data_set_float : raw_data -> float -> unit  = "%rawdata_set_float"
```
and another primitive that gives the raw tagged representation of an `int` as a `raw_data`:
```ocaml
external int_as_raw_data : int -> raw_data = "%int_as_rawdata"
```
These primitives seem pretty general, and they allow the above code to be replaced by:
```ocaml
let load_int t =
  let d = Obj.int_as_raw_data t in
  let d = Nativeint.sub d 1n in
  Obj.raw_data_load_int d

let set_int t i =
  let d = Obj.int_as_raw_data t in
  let d = Nativeint.sub d 1n in
  Obj.raw_data_set_int d i

let load_float t =
  let d = Obj.int_as_raw_data t in
  let d = Nativeint.sub d 1n in
  Obj.raw_data_load_float d

let set_float t f =
  let d = Obj.int_as_raw_data t in
  let d = Nativeint.sub d 1n in
  Obj.raw_data_set_float d f
```
which produces the same assembly as the original, avoiding any performance concerns whilst avoiding any naked pointers.

### CODE REVIEW

**Comment by nojb** [comment]
This PR is pretty close to #724. That PR was [closed](https://github.com/ocaml/ocaml/pull/724#issuecomment-433486482) because of opposition to exposing these primitives in `Obj`. Has the situtation changed? If yes, and the PR moves forward, shouldn't we also add the other operations that are in #724?

**Comment by lpw25** [comment]
In this PR, I'm only interested in replacing operations that are currently implementable using naked pointers. I do not think the operations in #724 can currently be implemented, so I'd rather they were left for some other PR.

My understanding was that #724 was closed because no-one actually had any use cases where using C primitives was not fast enough. Here I have specific users finding the C primitives too slow in their code and that loss of performance is in some sense a regression caused by removing naked pointers.

**Comment by xavierleroy** [comment]
This is the return of [PEEK and POKE](https://en.wikipedia.org/wiki/PEEK_and_POKE), a proposal that I have already rejected twice (#7252, #724) and that I am going to reject again.  I don't want my favorite language to provide support for that kind of programming.

**Comment by gasche** [comment]
Out of curiosity, do you have numbers on what you mean by "too slow" for the noalloc-C-stubs approach?

**Comment by lpw25** [comment]
@xavierleroy If you are unhappy with this approach, do you have any alternative suggestions for how to keep our programs working at acceptable performance when naked pointers are removed?

**Comment by lpw25** [comment]
@xavierleroy Following part of the discussion in #724, how about the version where the primitives are not exposed in `Obj`?

**Comment by xavierleroy** [comment]
@lpw25 I have no idea what your programs do with absolute memory addresses, nor do I want to know.  Perhaps you should ask one of the many OCaml experts at Jane Street.  Generally speaking, raw memory can be exposed to OCaml as a bigarray; that's what Ctypes does.  Still very generally speaking, if many calls to "peek" and "poke" C functions are too expensive, increasing the granularity could help, i.e. fewer calls to C functions that do more work than just "peek" and "poke".

**Comment by xavierleroy** [comment]
> Following part of the discussion in #724, how about the version where the primitives are not exposed in Obj?

That would be a little less awful, but I would still prefer that you find a way not to rely on memory accesses at absolute addresses in your code, because it just stinks. (Pardon my French.)

**Comment by lpw25** [comment]
Ok. For now then I think we'll just run with this patch on our internal compiler. It's maintenance is pretty trivial so we can basically do that indefinitely if we have to.

**Comment by gasche** [comment]
Could we still hear about how much of a performance regression you would get? If we are discussing design choices based on performance impact, it would be helpful to get a sense of the impact.

**Pull request closed without merging**
