### PR TITLE
Typed PPX

### PR DESCRIPTION
**Pull request by johnwhitington**
This GPR introduces a typed version of PPX. That is to say, a `-tppx` rewriter receives the typed tree, after typechecking has been completed, and returns the same or another typed tree.

Plainly TPPX rewriters which alter the tree may be unsafe. More on that later.

# See also

https://bitbucket.org/camlspotter/typpx (cc @camlspotter)

https://discuss.ocaml.org/t/ppx-transformation-from-a-typed-ast/2206 (cc @charguer)

https://stackoverflow.com/questions/32173627/basic-type-driven-ppx-rewriting

# Discussion

The motivation is that this is one of the prerequsites to the new version of ocamli, my OCaml interpreter (https://github.com/johnwhitington/ocamli.git). Essentially it will allow a program to be compiled natively, but with any expression annotated with [<span>@</span>interpret] will be interpreted, with the steps of evaluation printed out, just like OCamli. Thus, the compiled program will run all code which is not being inspected at full speed, and will integrate with any build system. It is "parachuted in" to the heart of the build system by the typed PPX mechanism.

However, typed PPX may be useful to others. See the "See also" section above for others who had this thought before me. Firstly, it might have uses which do not involve modifying the typedtree at all, just seeing it at compile time. The example typed ppx `tppx_showtype` (https://github.com/johnwhitington/tppx_showtype.git) will show the type of any expression annotated with [<span>@</span>showtype]. For example, we may compile this file with `-tppx tppx_showtype`:

```
let[@showtype] f (x [@showtype]) y = x + y [@showtype "result"]
```

And we will see:

```
$ ocamlopt -tppx ./tppx_showtype example.ml 
f : int -> int -> int
result : int
x : int
```

So this provides the typical "show the type under the cursor" functionality of e.g merlin, but without depending on the editor, and in particular without recourse to compiler artefacts such as `.cmt` files. I have no idea if this will turn out to be useful. It was simply the first example which sprung to mind.

The example in the documentation for Tast_mapper, which has been extended to be the interface to typed PPX, will swap with probability 0.5 the two elements of any pair of type a * a annotated with [<span>@</span>swap]. This is an example of a Typed PPX which modifies the typed tree but which (should) be safe. Perhaps such a thing has a use in fuzz testing. Again, this is conjecture.

# Safety

How could we make typed PPX safe? By re-typing the tree, for example by running it through Untypeast, and re-starting the compiler at an earlier stage. Unfortunatlely, Untypeast is not complete - for example, it can not always find original labels for labelled arguments, according to comments in the source:

```
   * For Pexp_function, we cannot go back to the exact original version
   when there is a default argument, because the default argument is
   translated in the typer. The code, if printed, will not be parsable because
   new generated identifiers are not correct.

   * For Pexp_apply, it is unclear whether arguments are reordered, especially
    when there are optional arguments.
```

A long term goal would be to make the first half of the OCaml compilation process bidirectional, in the sense that we could have:

Source text <---> Parse tree <---> Typed tree

From parse tree back to source cannot work at the moment. For example, `fun x y z` and `fun x -> fun y -> fun z` result in identical parse trees. Also, complete robustness of locations would be required to reconstruct the source. Typed tree back to parse tree cannot work until Untypeast is complete.

# Design

Typed PPX is implemented in much the same was as ordinary PPX. For now, it is very simple. It is not clear to me to what extent PPX facilities such as cookies and drivers and so on are required or would be identical to that of normal PPX. It may be that eventually the machinery from the new (small) file `typing/tppx.ml` could in fact be refactored into `parsing/pparse.ml`, so I have not replicated such complications for now.

The `Tast_mapper` module has been extended to become the interface to -tppx, in the same way as `Ast_mapper` is for -ppx. Its documentation has been exposed in the compiler-libs chapter of the manual.

Typed PPXs are used in the same way as PPXs, but with -tppx instead of -ppx on the command line.

Typed PPXs work in the top level too, just like PPXs with -tppx and #tppx.

The other example [<span>@</span>swap] I mentioned is here:

https://github.com/johnwhitington/ppx_test.git

# Known issues

I could not work out how to modfy the test typed-ppx to actually run and check the output of the program - it just checks the output of the compilation. It is modified from the ppx-contexts example.

When I accidentally enabled the writing out of the typed tree even when no -tppx was specified, and built the compiler, the build failed, because `stdlib/sort.ml` seems to produce a typed tree containing a functional value, such that `output_value` does not work on it. I presume this is a bug and that a typed tree should never contain a functional value?

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for looking at this problem.

I have worked a lot on the ppx infrastructure and I have been thinking about the question of using feedback from the typer in ppx rewriters as well. There are two questions that are problematic and I believe should be answered by a proposal for typed ppx rewriters:

1. how do typed ppx rewriters interact with dependency analysis (ocamldep)?
2. how do typed ppx rewriters interact with classic ppx rewriters?

Regarding 1, with classic ppx rewriters the situation is simple as we can perform the rewriting before dependency analysis. However, it is more complex with typed ppx rewriters as performing the rewriting requires typing the file, which requires the dependant modules to have already been typed, and to know the list of dependant modules, we need to have performed the rewriting...

There are a few ppx rewriters out there that already invoke the OCaml typer, and the way they deal with dependency analysis is by performing a different rewriting that doesn't involve running the OCaml typer when they are called from ocamldep. I suppose we would need something similar for typed ppx rewriters.

Regarding 2, the question is basically what happens when the output of a typed ppx rewriters contains annotations or extension points that are expected to be rewritten by a classic ppx rewriter.

Finally, I'm also curious about the scope of typed ppx rewriters. For instance, I would expect that we could rewrite classic ppx rewriters that currently use the typer as typed ppx rewriters. However, with the current proposal it seems that the whole file must be typable before being rewritten, which means that typed ppx rewriters cannot be used to rewrite extension points. In particular, ppx_import which is I believe the most widely used ppx rewriter using the OCaml typer, doesn't fit in this proposal.

**Comment by johnwhitington** [comment]
Some rough thoughts below, from a position of some ignorance on both ocamldep and PPX.

> There are two questions that are problematic and I believe should be answered by a proposal for typed ppx rewriters:
> 
> 1. how do typed ppx rewriters interact with dependency analysis (ocamldep)?
> 2. how do typed ppx rewriters interact with classic ppx rewriters?
> 
> Regarding 1, with classic ppx rewriters the situation is simple as we can perform the rewriting before dependency analysis. However, it is more complex with typed ppx rewriters as performing the rewriting requires typing the file, which requires the dependant modules to have already been typed, and to know the list of dependant modules, we need to have performed the rewriting...
> There are a few ppx rewriters out there that already invoke the OCaml typer, and the way they deal with dependency analysis is by performing a different rewriting that doesn't involve running the OCaml typer when they are called from ocamldep. I suppose we would need something similar for typed ppx rewriters.

PPX and Typed PPX [@] annotations have the same syntax, and only the build system knows whether to use -ppx or -tppx. For a -tppx which introduces dependencies, we could have the user give -ppx ppx_a -tppx tppx_a, and ppx_a could act as you describe when called by ocamldep. It may well be the case that many typed PPXs can calculate correctly (or at least conservatively) the set of dependencies which might need to be added from the parse tree alone. Or, of course, we could allow Typed PPXs to also register a plain ppx rewriter for the same purpose.

> Regarding 2, the question is basically what happens when the output of a typed ppx rewriters contains annotations or extension points that are expected to be rewritten by a classic ppx rewriter.

I had envisaged PPX and Typed PPX as being separate, and that there would be no such expectation, at least in the first instance. That is, a given source file is rewritten by any -ppx rewriters, typed, and then rewritten by any -tppx rewriters.

To support "going round again and again", we would need something like Untypedast, as I mention above. And, presumably, allowing parts of the complier to be re-run in such a loop would need careful attention to compiler artefact files and environments. This seems much more ambitious.

If we accept, for now, the elephant-in-the-room of unsafety for Typed PPX, then other restrictions, such as not being able to have PPX rewriters run after TPPX rewriters, are easy to swallow at first since they are, in comparison, tiny.

> Finally, I'm also curious about the scope of typed ppx rewriters. For instance, I would expect that we could rewrite classic ppx rewriters that currently use the typer as typed ppx rewriters. However, with the current proposal it seems that the whole file must be typable before being rewritten, which means that typed ppx rewriters cannot be used to rewrite extension points. In particular, ppx_import which is I believe the most widely used ppx rewriter using the OCaml typer, doesn't fit in this proposal.

Right. I should have mentioned that, of course, [% ] extension points are not supported by the proposal.

Could they, for example, be treated the same way as `assert false` by the compiler when being typed, and so a typed tree is produced, then the -tppx fills them in and we type again? For example, the -ppx part of a typed ppx could rewrite `let x = [%something payload]` into `let x = assert false [@something payload]` or `let x = type-witness [@something payload]` and then the -tppx part could fill it in. This seems as though it would not cover all cases, though.

**Comment by alainfrisch** [comment]
How much of the intended use cases would be covered by adding some kinds of hooks to the type-checker, to be registered through compiler (dynlinked) plugins?  For instance, a simple kind of hook would consist in allowing a plugin to rewrite a Parsetree sub-expression just before it is type-checked (having access to the type-checking environment, etc).  This would be safer than rewriting the Typedtree, and would allow producing, if needed, a preprocessed source file (without relying on untypeast).

(Another kind of hooks could be a post-processing step on the entire Typedtree, which would be roughly equivalent to an external "tppx", but this doesn't bring any safety.)

**Comment by ghost** [comment]
@alainfrisch that's what I was thinking as well, although relying on statically linked on-demand compiler drivers rather than dynlink for speed and portability, basically like what dune does for ppx drivers.


We could imagine that the user would provide a callback with this API for every extension point they want to expand:

```ocaml
type extension_point_expander
  =  Compilation_context.t
  -> Parsetree.payload
  -> Parsetree.expression
```

Where `Compilation_context.t` would be a handle allowing the user to do some query against the typer in a safe way. In fact, the vast majority of classic ppx rewriters should fit in this model.

**Comment by Drup** [comment]
I used to think this was a good idea. I don't anymore. First, not only is it unsafe, but I think it's more or less impossible to write anything that changes the typedtree safely (see [this topic](https://discuss.ocaml.org/t/what-would-it-take-to-unify-the-parsetree-with-the-typedtree/2225/7)). Second, I think you dismiss `Untypeast` far too quickly.

The only issues with `Untypeast` are:
- The AST obtained is not exactly equivalent to the original one. 
Some syntactic sugar has been removed and labeled argument might be re-ordered.
-  *printing* such AST might not result in a textual program that can be parsed.

It would be nice to solve these, but as far as compilation goes the two ASTs are completely equivalent, which is the only thing that matters for ppxs.
In particular, I have a branch (https://github.com/Drup/ocaml/tree/untypeast_bootstrap) which runs the typechecker, applies untypeast, retype. That branch used to pass bootstrap and a big chunck of the opam repository. My version of `eliom` also uses untypeast quite a lot.

In general, I find @alainfrisch 's idea more compelling, although making it really safe would still require some work. I think Haxe has something very similar.
By the way, there are already dynlink-based hooks in the typechecker, in `Typemod.ImplementationHooks` and `Typemod.InterfaceHooks`.

**Comment by mshinwell** [comment]
And there was me thinking that we might be able to reduce the complexity of the compiler's build system by removing support for dynlinking objects into the compiler...

**Comment by ghost** [comment]
We can definitely remove it. Instead of relying on dynlink, we can rely on linking plugins statically, dune already has the infrastructure to build such on-demand drivers.

**Comment by johnwhitington** [comment]
> I used to think this was a good idea. I don't anymore. First, not only is it unsafe, but I think it's more or less impossible to write anything that changes the typedtree safely (see [this topic](https://discuss.ocaml.org/t/what-would-it-take-to-unify-the-parsetree-with-the-typedtree/2225/7)).

From that topic, this is also what I would like:

>In summary, it seems that the sensible way to go is to express my program
transformation as a function that takes as input a typedtree with valid types,
and returns a typedtree with dummy type information, and then call the
type-checker again.

But, as you say, that would require unifying the ASTs.

> Second, I think you dismiss `Untypeast` far too quickly.
> 
> The only issues with `Untypeast` are:
> * _printing_ such AST might not result in a textual program that can be parsed.
> 
> It would be nice to solve these, but as far as compilation goes the two ASTs are completely equivalent, which is the only thing that matters for ppxs.

For an `ocamli`-based typed ppx (let's call it `ppx_interpret`), being able to print it is exactly the point, unfortunately. But this may not be true for most typed PPXs.

**Comment by ghost** [comment]
BTW, typing takes quite a bit of time, so we should avoid ending up in a state where we type every file twice as many times.

**Comment by Drup** [comment]
> BTW, typing takes quite a bit of time, so we should avoid ending up in a state where we type every file twice as many times.

Loading cmis takes a lot of time, typing itself is rather fast once everything is already loaded. Of course it's best not to do that for the whole ecosystem, but for smaller experiments, it's not so bad in practice.

**Comment by ghost** [comment]
I talked about this PR with other core developers who knows the OCaml typer well, and the general impression I get is that getting a sound rewriting system at the typedtree level would require quite a lot of work, and possibly even some theoretical work.

Without this work, the scope of the current PR will remain quite limited. Additionally, integrating typed ppx properly in the existing tooling would require a non-trivial amount of work, as exposed by the discussion about ocamldep. Finally, from what I understand it is already possible to achieve the same goals as the one stated in this PR by other means, in particular via compiler plugins.

Given all that, I don't believe the compiler should get support for typed ppx in the proposed form, so I'm closing this PR.

**Pull request closed without merging**
