### PR TITLE
Make the CI dump `config.log` and verbosely print failed commands

### PR DESCRIPTION
**Pull request by MisterDA**
I've been hacking the configure script and the Makefiles a lot lately, and although the CI build matrix is immensely useful to test the variety of systems at once, it's not great when one has to debug why the configure script failed or print the commands Make invokes.
This PR will:
- in case `configure` fails, dump `config.log` (the list of all commands executed by the configure script, with their output) ;
- ~in case `make` fails, re-run `make` dry-run, printing the last commands, including the one that failed, without executing them (as suggested in #11844)~;
- in case `make` fails, re-run it and print the commands executed.

I haven't changed the Make invocations in the AppVeyor script, which is a bit more complex, or the Inria precheck scripts.

I've included other little cleanups to the Github Actions script.

I've also added an easy way of toggling make's full printing of executed commands, with the `MAKEFLAGS` env var set to `V=1`.

(no change entry needed)

### CODE REVIEW

**Comment by shindere** [comment]
Thanks for the work, I am convinced it's an improvement.

May I nitpick about the commit message and ask that gha and ci are
upper-cased to GHA and CI, respectively?

Also, I notice that you test the exit value of configure and make but
since you don't keep them in a variable you then can't pass them and are
forced to exit 1, so some information (the precise exit code of
configure / make gets lost). What do you think of modifying this?

I also notice that, when you re-run make, you do so in parallel which
may impact the order in which the lines get printed so I was wondering
whether it wouldn't be better, if the parallel invocation fails, to
re-run it sequentially. It will either fail, too, meaning that the error
exists even in the sequential builds, or it won't fail, meaning that the
error is in the dependency graph.

I am also unsure how the error message will get printed if everything is
run in dry-run mode, including the command itself that produced the
error during the original invocation, if I understand correctly?

> I haven&#39;t changed the Make invocations in the AppVeyor script,
> which is a bit more complex, or the Inria precheck scripts.

Inria's CI does not only precheck :)

**Comment by MisterDA** [comment]
> May I nitpick about the commit message and ask that gha and ci are upper-cased to GHA and CI, respectively?

Done.

> Also, I notice that you test the exit value of configure and make but since you don't keep them in a variable you then can't pass them and are forced to exit 1, so some information (the precise exit code of configure / make gets lost). What do you think of modifying this?

Done.

> I also notice that, when you re-run make, you do so in parallel which may impact the order in which the lines get printed so I was wondering whether it wouldn't be better, if the parallel invocation fails, to re-run it sequentially. It will either fail, too, meaning that the error exists even in the sequential builds, or it won't fail, meaning that the error is in the dependency graph. I am also unsure how the error message will get printed if everything is run in dry-run mode, including the command itself that produced the error during the original invocation, if I understand correctly?

The goal wasn't to re-run Make (as in, rebuild things), but rather to print the last commands that have been executed. I've experimented further by adding failures late in the compilation stage (say, in the runtime_events library), and running with dry-run is very confusing and not that useful. In the end, I think that re-running make sequentially with the full verbosity, even if it's tedious and would print the error twice, is the most helpful we can get. That would be `make -j1 V=1`.

**Comment by shindere** [comment]
Thanks for your fixes!

Antonin Décimo (2024/06/10 09:04 -0700):
> The goal wasn't to re-run Make (as in, rebuild things), but rather to
> print the last commands that have been executed. I've experimented
> further by adding failures late in the compilation stage (say, in the
> runtime_events library), and running with dry-run is very confusing
> and not that useful. In the end, I think that re-running make
> sequentially with the full verbosity, even if it's tedious

Well not that tedious, I think, because `make` will see what has
already been built and will not attempt to rebuild it.

It is also worth noting that, the more the sub-makefiles will get merged
in the root one, the more the previous statement will become true as
the merges willmake Make's view of the dependency graph more andmore
complete and accurate.

> and would print the error twice,

Do you mean because Make is run twice? Otherwise I am not sure I
understand why a second invocation of Make would print the smae error
message twice?

> is the most helpful we can get. That would be
> `make -j1 V=1`.

Well then, `-j1` is not really useful...

I also wonder: did you consider putting this logic of `configuring and
showing config.log if it fails` in sort of shell library files that
could then be re-used across the different CI solutions? THat would open
the way for a more consistent experience, not even mentionning the gains
in maintenance. What do you think?

**Comment by MisterDA** [comment]
>> and would print the error twice,
>
> Do you mean because Make is run twice? Otherwise I am not sure I understand why a second invocation of Make would print the same error message twice?

Yes, because Make is run twice.

>> is the most helpful we can get. That would be `make -j1 V=1`.
>
> Well then, `-j1` is not really useful...

Ok, I can revert that.

> I also wonder: did you consider putting this logic of `configuring and showing config.log if it fails` in sort of shell library files that could then be re-used across the different CI solutions? That would open the way for a more consistent experience, not even mentioning the gains in maintenance. What do you think?

Yes, and the `runner.sh` script is already quite reusable. I think that this idea is better left for another PR, though. I'd like us first to see if we can improve the experience as-is.

**Comment by MisterDA** [comment]
>>> is the most helpful we can get. That would be make -j1 V=1.
>>
>> Well then, `-j1` is not really useful...
>
> Ok, I can revert that.

In the end we both feel (off list) that sequential make is better to avoid duplicated or scrambled output.

I think the PR is fine as-is, but we could print more things: some generated files, the output of `ocamlc -config` if we're not doing it already.

**Comment by shindere** [comment]
Antonin Décimo (2024/06/11 09:27 -0700):
> I think the PR is fine as-is,

It is, thanks a lot.

> but we could print more things: some generated files, the output of
> `ocamlc -config` if we're not doing it already.

Agreed. And also make sure the idioms you have introduced (print
config.log if configure fails, re-run make make sequentially and
verbosely when it fails, etc.) are re-suable (and actually re-used!)
across CI solutions.

**Review by shindere — APPROVED** [review]

**Pull request merged**
