### PR TITLE
Reveal the type of Unix.inet_addr as private string plus some new conven...

### PR DESCRIPTION
**Pull request by vbmithr**
...ience functions.

Added functions ipv4_addr_of_bytes, ipv6_addr_of_bytes and
inet_addr_of_string_raw to extract IP addresses from bytes and
raw_strings.

### CODE REVIEW

**Comment by damiendoligez** [comment]
About the function names, I propose `bits_of_inet_addr` and `inet_addr_of_bits`.

About @gasche's idea of using `Bytes.t` for immutable sequences of bytes, I think it's counter-productive. What the type system tracks is mutability, not printability. Trying to restrict `string` to printable stuff and `bytes` to non-printable stuff is not a good match for the guarantees provided by the type system especially because it entails trusting the programmers to avoid mutating `bytes` values that are not supposed to be mutated, without any help from the type-checker.

**Comment by gasche** [comment]
What should we do with this PR? @alainfrisch, as the new stdlib superhero, would you be interested in stewarding it? (I'm willing to retract my objection on bytes vs. string to let the PR move forward, although I'm still of the personal opinion that `bytes` would be more appropriate here.)

**Comment by xavierleroy** [comment]
This PR has been suffering for too long.  For what it's worth, I'm OK with `bits_of_inet_addr` and `inet_addr_of_bits`, taking and returning strings.

**Comment by alainfrisch** [comment]
General remark: I really wished people suggesting additions to the stdlib/otherlibs mentioned the reason for the request.  It might seem obvious to them, but one should not put the burden of imagining why something might be useful to reviewers.

Otherwise:

  - There is really no reason to expose a private type, which would restrict the ability to change the concrete representation.  Conversion functions in both direction are fine.

  - Is there a strong case to have conversion function from bytes (with an offset)?  This does not really avoid any copying, so it seems to be purely a convenience, not a performance-oriented choice.  Given that this triple the number of conversion functions to inet_addr, I'm not sure about this is a good idea.  The text of the exception raised bytes `Bytes.sub` might be a bit confusing.  Also, keeping these function would also strongly suggest having similar function in the other direction (blitting the raw inet_addr at some offset in a `bytes`) for symmetry, but this does not seem really useful for the same reason.

**Comment by mshinwell** [comment]
This PR from nearly 2 years ago has been dormant once again for many months, and the original author has been silent.  I am going to close it.  If the feature is to be requested again please take into account the above suggestions (especially those of @alainfrisch just above) before re-submission.

**Pull request closed without merging**
