### PR TITLE
Restructure letrec tests, use expect tests

### PR DESCRIPTION
**Pull request by gasche**
Before this PR, there was a test directory `letrec-disallowed`, containing examples that should be rejected statically by the recursive-value-checker, and a directory `letrec` that contains both examples that should be accepted by the recursive-value checker, and tests for the recursive compilation strategy.

After this PR, the tests are split between `letrec-check` which tests the static recursive-value-checker, and `letrec-compilation` that tests the compilation strategy. `letrec-compilation` is mostly the old `letrec` unchanged. `letrec-check` corresponds to `letrec-disallowed` plus `letrec/allowed.ml`, reordered to be grouped by language features (with both should-pass and should-not-pass in each file), and using expect tests.

While preparing this PR I realize that a new feature would be useful for expect tests: I would like to be able to write `[%%expect normal]`, and have this accept any toplevel output that contains only feedback on declarations, no warnings nor errors. (cc @trefis @Octachron).

Consider for example:

```ocaml
module type S = sig               val y : float end;;
module type T = sig val x : float val y : float end;;
type t = T : (module S) -> t;;
[%%expect{|
module type S = sig val y : float end
module type T = sig val x : float val y : float end
type t = T : (module S) -> t
|}];;

let rec x = let module M = (val m) in T (module M)
and (m : (module T)) = (module (struct let x = 10.0 and y = 20.0 end) : T);;
[%%expect{|
Line 1, characters 12-50:
  let rec x = let module M = (val m) in T (module M)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This kind of expression is not allowed as right-hand side of `let rec'
|}];;
```

I would like to write instead:

```ocaml
module type S = sig               val y : float end;;
module type T = sig val x : float val y : float end;;
type t = T : (module S) -> t;;
[%%expect normal];;

let rec x = let module M = (val m) in T (module M)
and (m : (module T)) = (module (struct let x = 10.0 and y = 20.0 end) : T);;
[%%expect{|
Line 1, characters 12-50:
  let rec x = let module M = (val m) in T (module M)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This kind of expression is not allowed as right-hand side of `let rec'
|}];;
```

### CODE REVIEW

**Comment by v-gb** [comment]
It's not entirely clear how to support this `[%%expect normal]` idea [1], but the original version of this expect test tool has a `#verbose boolean` directive for this purpose, which disables the printing of types/values (https://github.com/janestreet/toplevel_expect_test/blob/6a48060ae864df73eb2412214952a95d063df9be/src/main.ml#L111), so you could probably simply add the 4 relevant lines to your pull request.

[1] these extensions nodes are not attached to the declaration doing the printing, so it seems the tool would need to look ahead to see if it should silence the printing or not, but then it's not clear what to print/what corrections to generate on things like:
```ocaml
expr1;;
expr2;;
expr3;;
expr4;;
[%%expect normal]
[%%expect some-warning]
[%%expect normal]
```

**Comment by gasche** [comment]
My understanding is that `[%%expect]` talks about the toplevel behavior on the input since the last `[%%expect]` marker (or the beginning of the file), so your last example would not work: the first `%%expect normal` would be checked about the output of all the phrases (and fail if any of them emits a warning), and the second `%%expect {| ... warning ... |}` would always fail as it only observes an empty output.

Regarding the implementation, the difficulty comes from the fact that the expect-tool does not distinguish between the "normal" output of the toplevel and warnings/errors, due to a lack of abstraction in the Toploop API. There are many reasons why we want to improve the abstraction there (for example, to make the life of `utop` easier), so hopefully we could improve on that at some point, which would also make `%%expect normal` very easy to implement.

Thanks for pointing out `#verbose`; I suspect that it would be far from as convenient to use in practice, but maybe there would be a compromise approach: if we preprocess the toplevel phrases to detect the phrases whose following expectation is `normal`, then we can know at phrase-execution time whether we want verbose output or not.

**Comment by Octachron** [comment]
Differentiating the warning and error messages  is definitely doable  in `expect_test` itself  (i.e. I have a relatively short prototype implementation). Nevertheless, I agree that it would be nice to add to the toplevel API a version of `exec_phrase` that redirect all outputs to differentiated formatters during the phrase execution .

**Comment by ghost** [comment]
Another possibility would be to add a new construction to the language to display typing error. i.e. something like this:

```ocaml
# [%try_typing 42]
- (unit, string) error = Ok ()
# [%try_typing 1 + 'e']
- (unit, string) error = Error "This expression ..."
```

then we wouldn't even need two kind of expectation tests, i.e. [normal inline expectation tests](https://github.com/janestreet/ppx_expect) and toplevel expectation tests.

For instance the example above would be written this way:

```
module type S = sig               val y : float end
module type T = sig val x : float val y : float end
type t = T : (module S) -> t

let%test _ =
  print_error [%try_typing 
    let rec x = let module M = (val m) in T (module M)
    and (m : (module T)) = (module (struct let x = 10.0 and y = 20.0 end) : T)];
  [%expect{|
Line 1, characters 12-50:
  let rec x = let module M = (val m) in T (module M)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This kind of expression is not allowed as right-hand side of `let rec'
|}]
```

which would make it clearer what is being tested what is part of the test harness.

**Comment by gasche** [comment]
Would someone be willing to review this PR? It's just moving tests around and improving them.

**Comment by trefis** [comment]
I'm on it.

**Review by trefis — APPROVED** [review]
I only partially check the last commit: it's incredibly tedious to follow all the moves at the same time as the reordering.
But for the few things I looked for, any that disappeared from one place reappeared in another. So I'm just going to trust that you didn't drop any test of the floor while doing the moves.

The other two commits are obviously correct.

**Comment by gasche** [comment]
Thanks! Probabilistic reviewing is the future.

**Comment by trefis** [comment]
Either that or atomic commits :)

**Pull request merged**
