### PR TITLE
Add source data to signatures and structures

### PR DESCRIPTION
**Pull request by malekbr**
This change is added to address #12629. It adds location information to signatures and structures. Existing tests that passed before still pass or are fixed to pass.

Three things remain to be addressed, but I wanted to open the PR first to at least have a review pass at it and answer these questions:

- Naming clashes: a lot of the names that would naturally fit this new location information have been taken by structure_items/signature_items, e.g. pstr_loc, psig_loc, so I resorted to adding the word mod to scope signature and structure types, i.e. pstrmod_loc and pstrmod_loc. However, in the typedtree, signature and structure are already records and not just lists, and does not have a prefix to differentiate between structure and structure_item or signature and signature_item. For example, structure_item has str_loc, and structure has str_items. I added str_mod_loc and sig_mod_loc, but that seemed slightly inconsistent. Unclear what the recommended approach is here. Is stability more important, or should we rename the structure_item fields to make it more consistent? I fear the latter will cause a lot of churn for PPX maintainers if we change parsetree, although that's inevitable with this change. Typedtree changes should be cheaper.
- Testing: there's tests that print the AST and exercise the mapper/iterator. What additional tests if any do you think should be added?
- I did not make any modifications to the changes file yet.

### CODE REVIEW

**Comment by gasche** [comment]
Thanks!

The naming question is annoying -- it feels like accidental complexity but it is also important and there are no obvious good choices. I can see the following approaches:

1. Use `type structure = structure_item list loc`, where `'a loc` is `'a Location.loc` which carries both a `'a` and a `Location.t`.
2. Keep the `structure` definition unchanged and use `structure loc` at each use site in the parsetree.
3. Change the prefix for structures and signatures in the typedtree to something else than `str_` and `sig_` (to avoid conflict with structure and signature *items*), and use the same thing in the parsetree. For example, I think that `structure_` and `signature_` could work. (As you note, it would be more regular to change the item prefix to `stri_`, `sigi_`, but that requires non-trivial Parsetree changs which incurs more work for our ppx users.)

(1) and (2) look neat but I wondered whether we will eventually want to move to a proper record to add extra information anyway. What about attributes for example? I tested, and `module M = struct[@foo] end` does not store the attributes at the `structure` level but at the `module_expr` level above.

#### Taking a step back

I hadn't realized that the naming issue would be a difficult here, apologies!

I wonder if we should consider taking a step back and use a more minimal approach to typedtree and parsetree changes to get the info we need, but not (necessarily) more:

- We want the `structure` and `signature` types in the *typedtree* to have locations.
- This suggests that `type_interface` and `transl_signature` in Typemod should take a location argument.
- Can we get this with minimal parsetree changes?

One idea would be to introduce two new types `interface` and `implementation` in the parsetree, that would contain a signature/structure and location information (luckily the prefixes `intf_` and `impl_` are up for grabs in the parsetree), without requiring a change to the existing `structure` and `signature` types. Those new types would be used instead of `signature`/`structure` in the interface of driver/Compile_common, and pass location information to the typedtree.

**Comment by Octachron** [comment]
To track more precisely the dependency chain, ultimately we want `Includemod.compunit` to have access to the cmi source file. This requires us to read a signature location from the cmi, which requires us to have the location available in `Typemod.type_interface`, which requires us to have the location available in the parsetree (because we should let the parser handle the issue with line directive). 

The idea of having location in signatures and structures was to strike for the most regular solution, but we probably  swung too far in this direction. And with the naming issue, I tend to think it is indeed better to try to add locations to interfaces and implementations, since all other occurrences of Parsetree.structure (resp. signatures) happen under a module expression (resp. a module type) with a location. The implementation and interface locations are thus the only one that are not available right now.

Note that we have no use for the implementation location right now, but this doesn't seem like a good reason enough to break symmetry.

**Comment by malekbr** [comment]
No worries at all! I don't mind changing things everywhere from str to structure and sig to signature for the actual signature/structure types in both parsetree and typedtree if that's the best solution for the future (and/or if this is a problem that will have to be solved at some point). I thought about using loc, but it seemed to only be used for identifiers elsewhere. Otherwise, I'll look at the other solutions you mentioned.

**Comment by gasche** [comment]
I think that I have converged towards the "taking a step back" solution of adding separates `implementation` and `interface` types in the parsetree, and @Octachron (is not explicitly explicit about it but) seems to agree.

**Comment by gasche** [comment]
(I must say that I am impressed with the quality of this first submission and the thoughtfulness of the feedback you gave alongside the code. Thanks @malekbr! )

**Comment by malekbr** [comment]
Thanks @gasche ! I started looking at the alternative solution. I'll share it when I have something substantial.

**Comment by gasche** [comment]
I am closing this PR as I believe it is superseded by @malekbr's second iteration at #12654.

( @malekbr : you can update the code of a github PR by pushing more commits (or a different history altogether) to the same git branch on your github remote. When the implementation is completely different it sometimes makes sense to create a different PR altogether, which may have been the idea here. )

**Comment by malekbr** [comment]
Yup that was the idea! Thank you

**Pull request closed without merging**
