### PR TITLE
Switch a few externals to [@@unboxed]

### PR DESCRIPTION
**Pull request by ghost**
Switched a few externals to  `[@@unboxed]`:
- `Int{32,64}.{of,to}_float`
- `Int{32,64}.float_of_bits`
- `Int{32,64}.bits_of_float`

The last 4 functions are especially good candidates as they often show up during serialization. We have some horrors in bin_prot to avoid these allocations...

### CODE REVIEW

**Comment by xavierleroy** [comment]
Looks good to me.  

I just checked: gcc -O2 and clang -O2 are clever enough to inline the "unboxed" function within the "boxed" function, which is good for bytecode performance while keeping the source code clean and free of code duplication.

Concerning conversions between floats and int32/int64/nativeint, in most cases Cmmgen could produce inline C-- code for it, bypassing the C function entirely.  But we would need to introduce new primitives in the Lambda code, and maybe those operations are not used enough to justify this.

**Comment by xavierleroy** [comment]
Also, while you're at it, why not unbox the corresponding functions in Nativeint?

**Comment by chambart** [comment]
For bits_of_float/float_of_bits I already tried to do that in selection (for amd64) rather than cmmgen. It does not need a new primitive, replacing the C call is sufficient to generate good code. This is a nice side effect of having unboxed function: we can easilly have drop in assembly version replacement.

See the last 2 commits of https://github.com/chambart/ocaml-1/commits/optimised_float_of_bits
For a generic version that works on all architectures we might want a 'move between generic and float register' mach primitive. The amd64 version is trivial since the classic move already works for that, but on architectures that does not allow it, we will need to go through a memory location. And this would be easier on C-- since all the primitives already exist for doing that.

**Comment by chambart** [comment]
I did some completely unscientific quick and dirty microbenchmark extracted from ocplib-endian to see what we gained:

With all the patches:

```
safe set_double   0.504000
safe get_double   0.732000
safe set_float    0.724000
safe get_float    0.848000
unsafe set_double 0.212000
unsafe get_double 0.608000
unsafe set_float  0.396000
unsafe get_float  0.624000
```

Only unboxed primitives

```
safe set_double   0.616000
safe get_double   0.788000
safe set_float    0.788000
safe get_float    1.000000
unsafe set_double 0.480000
unsafe get_double 0.744000
unsafe set_float  0.556000
unsafe get_float  0.748000
```

Without any patch:

```
safe set_double   3.032000
safe get_double   2.084000
safe set_float    3.032000
safe get_float    2.072000
unsafe set_double 2.532000
unsafe get_double 1.780000
unsafe set_float  2.736000
unsafe get_float  1.932000
```

``` ocaml
external swap32 : int32 -> int32 = "%bswap_int32"
external swap64 : int64 -> int64 = "%bswap_int64"

external get_32 : Bytes.t -> int -> int32 = "%caml_string_get32"
external get_64 : Bytes.t -> int -> int64 = "%caml_string_get64"

external set_32 : Bytes.t -> int -> int32 -> unit = "%caml_string_set32"
external set_64 : Bytes.t -> int -> int64 -> unit = "%caml_string_set64"

let get_int32 s off =
  if not Sys.big_endian
  then swap32 (get_32 s off)
  else get_32 s off

let get_int64 s off =
  if not Sys.big_endian
  then swap64 (get_64 s off)
  else get_64 s off

let set_int32 s off v =
  if not Sys.big_endian
  then set_32 s off (swap32 v)
  else set_32 s off v

let set_int64 s off v =
  if not Sys.big_endian
  then set_64 s off (swap64 v)
  else set_64 s off v

let get_float buff i = Int32.float_of_bits (get_int32 buff i)
let get_double buff i = Int64.float_of_bits (get_int64 buff i)
let set_float buff i v = set_int32 buff i (Int32.bits_of_float v)
let set_double buff i v = set_int64 buff i (Int64.bits_of_float v)

let s = Bytes.create 16

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    set_double s 8 1.2345
  done;
  let t2 = Sys.time () in
  Printf.printf "safe set_double   %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    ignore(get_double s 8)
  done;
  let t2 = Sys.time () in
  Printf.printf "safe get_double   %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    set_float s 8 1.2345
  done;
  let t2 = Sys.time () in
  Printf.printf "safe set_float    %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    ignore(get_float s 8)
  done;
  let t2 = Sys.time () in
  Printf.printf "safe get_float    %f\n%!" (t2 -. t1)

(* unsafe version *)

external get_32 : Bytes.t -> int -> int32 = "%caml_string_get32u"
external get_64 : Bytes.t -> int -> int64 = "%caml_string_get64u"

external set_32 : Bytes.t -> int -> int32 -> unit = "%caml_string_set32u"
external set_64 : Bytes.t -> int -> int64 -> unit = "%caml_string_set64u"

let get_int32 s off =
  if not Sys.big_endian
  then swap32 (get_32 s off)
  else get_32 s off

let get_int64 s off =
  if not Sys.big_endian
  then swap64 (get_64 s off)
  else get_64 s off

let set_int32 s off v =
  if not Sys.big_endian
  then set_32 s off (swap32 v)
  else set_32 s off v

let set_int64 s off v =
  if not Sys.big_endian
  then set_64 s off (swap64 v)
  else set_64 s off v

let get_float buff i = Int32.float_of_bits (get_int32 buff i)
let get_double buff i = Int64.float_of_bits (get_int64 buff i)
let set_float buff i v = set_int32 buff i (Int32.bits_of_float v)
let set_double buff i v = set_int64 buff i (Int64.bits_of_float v)

let s = Bytes.create 16

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    set_double s 8 1.2345
  done;
  let t2 = Sys.time () in
  Printf.printf "unsafe set_double %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    ignore(get_double s 8)
  done;
  let t2 = Sys.time () in
  Printf.printf "unsafe get_double %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    set_float s 8 1.2345
  done;
  let t2 = Sys.time () in
  Printf.printf "unsafe set_float  %f\n%!" (t2 -. t1)

let () =
  let t1 = Sys.time () in
  for i = 0 to 200000000 do
    ignore(get_float s 8)
  done;
  let t2 = Sys.time () in
  Printf.printf "unsafe get_float  %f\n%!" (t2 -. t1)
```

**Comment by ghost** [comment]
> Also, while you're at it, why not unbox the corresponding functions in Nativeint?

No reason indeed, I'm  updating  the patch.

@chambart, OK, I let you propose further improvement. The numbers looks already quite good with just `[@@unboxed]`

**Pull request merged**
