### PR TITLE
Use system=linux for ppc64 and s390x

### PR DESCRIPTION
**Pull request by dra27**
Extracted from #12405 for possible inclusion in 5.1. These two ports are only supported on Linux - it's also the only instance where system doesn't match `linux*`.

### CODE REVIEW

**Comment by Octachron** [comment]
As far as I can see, those changes were some of the most consensual component of https://github.com/ocaml/ocaml/pull/12405 and it would reduce the complexity of the configuration on OCaml 5 with those architecture.

I am thus favorable with the changes and the inclusion in 5.1 (if there are no objections really soon).

**Comment by avsm** [comment]
The complexity of changing these arises from the fact that tools will have to check both the OCaml version number as well as the new (much better values).

With that in mind, it would be easier to include the whole of #12405 in 5.1, and just deal with the new values in one fell swoop with one check for the OCaml version number being > or < 5.1...

**Comment by xavierleroy** [comment]
I like the idea of changing all the names in one go, but in 5.2, not in 5.1 (too late for that).

**Comment by dra27** [comment]
> The complexity of changing these arises from the fact that tools will have to check both the OCaml version number as well as the new (much better values).

I don't think this is the case - in order to compatible, one simply needs to test for more values. If one compatibly wants to check for "Linux", one still does `String.starts_with ~prefix:"linux" Config.system || Config.system = "elf"`. The changes here mean that if one "naively" does `Config.system = "linux"`, it will now do what's expected everywhere.

Sherlocode and opam-grep in #12405 suggest that the values which simultaneously identified system and architecture (`linux_elf` - i386 Linux, `linux_eabi`/`linux_eabihf` - "aarch32" Linux, etc.) aren't used that way.

**Comment by dra27** [comment]
All good to leave this in its entirety for 5.2!

**Pull request closed without merging**
