### PR TITLE
Migrate tests under testsuite/tests/basic to ocamltest

### PR DESCRIPTION
**Pull request by shindere**
In addition to the migration of the tests itself, this PR includes a few
ocamltest fixes and adjustments.

Regarding the tests themselves, the migration of most of them is
straightforward. There are however two notable exceptions:

1. constrprop.ml which involves calling the C preprocessor

2. The trigraph test.

This PR removes the trigraph.ml.silent-compilation file.
It was here to mark that the compilation of the corresponding test
(trigraph) should not produce any output
(see testsuite/makefiles/Makefile.several). Such tricks are not
needed any longer because it is the default behaviour of ocamltest
to ensure that compiling tests produces no output.

Moreover, on recent versons of OpenBSD, the linker produces a
warning which caused the compilation not to be silent as required.
This is why 3ac92c0ceef63fd1402ca8fb0db5fff3b469f88c skipped tha
test on OpenBSD.

However, on such systems, ocamltest passes the -ccopt -nopie options
which avoid the warning and make compiling tests silent again, so that
the test does not need to be skipped on such platforms.

### CODE REVIEW

**Comment by gasche** [comment]
(I suppose that you have run `precheck` or are going to?)

Is it feasible to test the enabled-again test under OpenBSD? (It was only "OpenBSD i386", right?)

**Comment by shindere** [comment]
Gabriel Scherer (2017/11/30 17:13 +0000):
> (I suppose that you have run `precheck` or are going to?)

I didn't intent to, but I can, if you like.

> Is it feasible to test the enabled-again test under OpenBSD? (It was
> only "OpenBSD i386", right?)

What do you mean? You want to make sure the test is indeed working on
OpenBSD?

**Comment by gasche** [comment]
Yes, if the test was previously disabled and (if I understand correctly) you enable it again (because now you think that it should pass), it is possible that it would now fail, and this could be tested, right?

**Comment by shindere** [comment]
Gabriel Scherer (2017/11/30 09:27 -0800):
> Yes, if the test was previously disabled

Sorry I think I need to be more precise. It was skipped rather than
disabled.

> and (if I understand correctly) you enable it again (because now you
> think that it should pass), it is possible that it would now fail, and
> this could be tested, right?
Sure it could fail, but I think it will pass.

**Review by xavierleroy — APPROVED** [review]
Should be OK.  If OpenBSD causes problems, we'll see it soon on the CI at Inria.

**Comment by shindere** [comment]
Xavier Leroy (2017/12/05 13:57 +0000):
> xavierleroy approved this pull request.

Thanks.

> Should be OK.  If OpenBSD causes problems, we'll see it soon on the CI
> at Inria.

As far as I remember I tested manually.

**Comment by xavierleroy** [comment]
The CI at Inria fails on all platforms.  Typical error:
```
Running tests from 'tests/basic-modules' ...
 ... testing 'main.ml' with 1 (native) => Fatal error: exception Sys_error("/home/barsac/ci/builds/workspace/main/flambda/false/label/ocaml-linux-64/testsuite/tests/basic-modules/_ocamltest/tests/basic-modules/main/ocamlopt.byte/ocamlopt.byte.output: No such file or directory")
```
One full log at https://ci.inria.fr/ocaml/job/main/84/flambda=false,label=ocaml-linux-64/console

**Comment by nojb** [comment]
I *think* this is due to https://github.com/shindere/ocaml/blob/72bf205ea27340e353baf7b5daf3733ecd2e17b0/ocamltest/main.ml#L83; the old directory should be restored after the call to `Sys.chdir`.

Incidentally I fixed this bug in #1509 (see https://github.com/ocaml/ocaml/pull/1509/commits/1078d6f080ab33f27d613519d7e61f2df378f9e8).

**Comment by shindere** [comment]
Seen, thanks. Working on it.
Sorry. Should really use precheck, next time.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2017/12/05 14:33 +0000):
> I *think* this is due to
> https://github.com/shindere/ocaml/blob/72bf205ea27340e353baf7b5daf3733ecd2e17b0/ocamltest/main.ml#L83; the old directory should be restored after the call to `Sys.chdir`.

Well I thought I fixed that, too (in a different way). Apparently my fix
didn't work...

**Comment by shindere** [comment]
(hopefully) fixed trunk in commit c965e525d00261c0681f4f9b813c3a5cb67a3486

Fellow developers: the next time I am reluctant to use precheck,
please insist.

**Pull request merged**
