### PR TITLE
Migrate the asmcomp tests to ocamltest

### PR DESCRIPTION
**Pull request by shindere**
The tests were disabled in presence of Spacetime but apparently they do work
when spacetime is enabled so this PR enables them no matter whether
Spacetime is enabled or not.

Is that okay?

### CODE REVIEW

**Comment by shindere** [comment]
Just rebased on latest trunk.

Can somebody re"view, please?

@gasche? @nojb? @octachron? Thanks!

**Comment by nojb** [comment]
I will take a look.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/14 08:17 +0000):
> I will take a look.

Thanks a lot, @nojb!

**Review by nojb — CHANGES_REQUESTED** [review]
LGTM, except for the test `is_static_data_flambda.ml`
```
module IntMap = (Map.Make [@inlined])(Int)
```
 which triggers a warning:
```
========================================
File "is_static_flambda.ml", line 194, characters 28-35:
Warning 53: the "inlined" attribute cannot appear in this context
========================================
```
Incidentally, I ran the tests under Windows+Spacetime and Windows+FLAMBDA and things were OK (except for the above warning), but when I tried to run the tests under Windows+Spacetime+FLAMBDA I got a segmentation fault while building the compiler. But this is not related to this PR and is to be investigated separately.

**Comment by shindere** [comment]
Many thanks, @nojb !

Did you configure in a special way to get this warning?

I am asking because, as far as I can remember, I tested both without and
with flambda and didn't have this problem.

**Comment by nojb** [comment]
No, I don't think so - Travis also shows the same warning: https://travis-ci.org/ocaml/ocaml/jobs/341315277#L4067-L4073

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/14 10:06 +0000):
> No, I don't think so - Travis also shows the same warning:
> https://travis-ci.org/ocaml/ocaml/jobs/341315277#L4067-L4073

OK thanks, will look into it ASAP.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/14 09:52 +0000):
> nojb requested changes on this pull request.
> 
> LGTM, except for the test `is_static_data_flambda.ml`
> ```
> module IntMap = (Map.Make [@inlined])(Int)
> ```
>  which triggers a warning:
> ```
> ========================================
> File "is_static_flambda.ml", line 194, characters 28-35:
> Warning 53: the "inlined" attribute cannot appear in this context
> ========================================
> ```

Ow, I missed that one, I am sorry!

@chambart: you seem to be the person who has introduced the line causing
this warning, in commit 177713ec02. Can I just remove the inline
attribute? Is that fine with you?

> Incidentally, I ran the tests under Windows+Spacetime and
> Windows+FLAMBDA and things were OK (except for the above warning),

Oh thanks a lot for having taken the time to try this, too!

> but when I tried to run the tests under Windows+Spacetime+FLAMBDA I got a
> segmentation fault while building the compiler. But this is not
> related to this PR and is to be investigated separately.

Ah! This Windows+Flambda+SpaceTime combination is something Inria's CI
does not test, at the moment. May I ask which port it was, to see if I
can reproduce this segfault here?

**Comment by nojb** [comment]
> Ah! This Windows+Flambda+SpaceTime combination is something Inria's CI
does not test, at the moment. May I ask which port it was, to see if I
can reproduce this segfault here?

`msvc64`, thanks!

**Comment by shindere** [comment]
PR rebased, inlined attribute removed.

**Comment by shindere** [comment]
@nojb or @chambart could one of you perhaps have a look?

Everything should be okay now.

I'd be happy with just an approval, then I would rebase and merge.

**Review by nojb — APPROVED** [review]

**Comment by nojb** [comment]
LGTM

**Comment by shindere** [comment]
Thanks a lot, @nojb!

**Comment by shindere** [comment]
Merged

**Comment by shindere** [comment]
Okay I just checked and on msvc64 with flambda and spacetime both
enabled the build of OCaml also fails at Inria.

However, here the error is due to unresolved symbols.

Is SpaceTime actually supposed to work on Windows?

If so, does somebody test it?

@dra27, any thought?

**Comment by nojb** [comment]
Could you post the relevant log fragment?

"Basic" Spacetime functionality on Windows was fixed in #1478. But I am not sure if anyone is using/testing it actively.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/20 08:33 +0000):
> Could you post the relevant log fragment?

Sure, sorry for not having done so earlier:

boot/ocamlrun ./ocamlopt -g -nostdlib -I stdlib -I otherlibs/dynlink  -o ocamlc.opt compilerlibs/ocamlcommon.cmxa compilerlibs/ocamlbytecomp.cmxa driver/main.cmx -cclib "advapi32.lib ws2_32.lib version.lib"
** Cannot resolve symbols for driver/main.obj:
 caml_spacetime_allocate_node
 caml_spacetime_generate_profinfo
 caml_spacetime_indirect_node_hole_ptr
** Cannot resolve symbols for stdlib\std_exit.obj:
 caml_spacetime_allocate_node
 caml_spacetime_indirect_node_hole_ptr
** Cannot resolve symbols for C:\cygwin64\tmp\camlstartupfa3c7b.obj:
 caml_spacetime_allocate_node
 caml_spacetime_generate_profinfo
 caml_spacetime_indirect_node_hole_ptr
** Cannot resolve symbols for stdlib\stdlib.lib(stdlib__nativeint.obj):
 caml_spacetime_allocate_node
 caml_spacetime_generate_profinfo
** Cannot resolve symbols for compilerlibs/ocamlcommon.lib(typing/cmi_format.obj):
 caml_spacetime_allocate_node
 caml_spacetime_generate_profinfo
** Cannot resolve symbols for compilerlibs/ocamlcommon.lib(typing/includeclass.obj):
 caml_spacetime_allocate_node
 caml_spacetime_generate_profinfo
 caml_spacetime_indirect_node_hole_ptr
(and many similar errors)

**Comment by nojb** [comment]
Have you defined `#define WITH_SPACETIME` and `#define WITH_PROFINFO` in `m.h` ?

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/20 09:16 +0000):
> Have you defined `#define WITH_SPACETIME` and `#define WITH_PROFINFO`
> in `m.h` ?

Ah no, sorry. Will try this. But why does one have to define those on
Windows? Couldn't they be automatically defined based on the Makefile
variable?

**Comment by nojb** [comment]
Do not forget to also set `#define PROFINFO_WITH 26`.

It probably works to pass the relevant defines on the command line from the `Makefile`, but it introduces a difference with Unix, where the defines are put in `m.h` by `configure`.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/02/20 09:29 +0000):
> Do not forget to also set `#define PROFINFO_WITH 26`.

OK thanks for telling, I did "forget". Well I didn't know about these.

> It probably works to pass the relevant defines on the command line
> from the `Makefile`, but it introduces a difference with Unix, where
> the defines are put in `m.h` by `configure`.

Sure, got it. Thanks.

**Comment by shindere** [comment]
@nojb after all the adjustments, the build worked here.

How reproducible is the problem you noticed?

Can you send a build log? :)

**Comment by nojb** [comment]
Not sure, it just happened once and did not try again.  I am a bit tied up at the moment but will try it again when I have some spare time. Thanks for looking into it.

**Pull request closed without merging**
