### PR TITLE
Remove Memprof from the standard library in the 4.10 branch, as this will not be ready for 4.10.

### PR DESCRIPTION
**Pull request by jhjourdan**
This also removes the corresponding tests (which are therefore broken), and updates the `Change` file.

Then only thing that will need to be backported to trunk is the change to `Changes`.

### CODE REVIEW

**Comment by jhjourdan** [comment]
Since memprof does currently work in bytecode mode, another option would be to keep the API in the standard library, but say explicitly in `gc.mli` that it will change (cf #8920) and that it does not work in native mode.

**Comment by xavierleroy** [comment]
> memprof does currently work in bytecode mode

I didn't know that.  How usable is it?  In terms of how to display profiling results, etc.  If it is somewhat usable, and this fact is advertised, we might get useful feedback from early users.  I wouldn't mind profiling the bytecode version of CompCert, for example.  The OCaml compilers themselves could make good guinea pigs too.

**Comment by jhjourdan** [comment]
> How usable is it? In terms of how to display profiling results, etc.

statmemprof-emacs (cf https://github.com/jhjourdan/statmemprof-emacs/) is still available and should work out of the box, modulo a few easy changes. I also know that OCamlPro has some prototype client library available (cc @chambart).

That said, my forks for former OCaml release do exist (4.07 is the most recent), are just one opam switch away and do provide the same functionality (plus support for native code). Given that the API will change drastically soon, I would prefer not exposing the current 4.10 API, which is neither compatible with my forks nor with what will be released in the future.

Of course, if you think that is not really an issue, we can decide to keep the API and advertise the upcoming changes.

**Review by gasche — APPROVED** [review]
We discussed this with Jacques-Henri before and I agree it's a simple and reasonable thing to do.

**Comment by gasche** [comment]
@xavierleroy: there is already a few early-users of memprof (some people used it on Tezos if I understand correctly, PMP did early experiments with Coq profiling, Frédéric wrote an entire UI for it within Emacs, and Hannes wrote explicit support for it in Mirage), all using the experimental switch released by Jacques-Henri as a compiler fork (of older OCaml releases).

I think that the current somewhat-incoherent state of statmemprof at the point where we branched 4.10 is a result of Jacques-Henri's nice work to split the big fork in small PRs which are easy to review and improve on incrementally (the discussion with Stephen in particular resulted in a lot of improvements to the pieces that were merged); we're caught in a release branch with a half-baked solution whose API is not at all final. I think it's wise to hide the feature from users for 4.10, and focus on continuing the improvements in trunk to get the "final upstream version" soon, instead of being tempted to document and support what's already there (which would divert time away from trunk progress).

**Comment by gasche** [comment]
(I still need to backport the Changes changes.)

**Comment by gasche** [comment]
(I just backported the Changes changes. While I was at it, I added extra PR numbers that were missing from the Changes.)

**Pull request merged**
