### PR TITLE
Make transl_exception_constructor generate Immutable blocks

### PR DESCRIPTION
**Pull request by mshinwell**
I don't understand why [transl_exception_constructor] generates mutable blocks.  I think it's better (both for general cleanliness, and for flambda since we don't yet lift mutable blocks to toplevel) if these are immutable.  Does anyone see any problems with this patch?

### CODE REVIEW

**Comment by gasche** [comment]
The de-marshalling code uses the mutation operation to, if I understand correctly, refresh the object id of just-demarshalled object to avoid clashes with already-existing objects: [byterun/intern.c:319-336](https://github.com/ocaml/ocaml/blob/659615c/byterun/intern.c#L319-L336).

I guess the knowledgeable persons on any hard obstacle to immutability would be @alainfrisch and @garrigue .

**Comment by mshinwell** [comment]
I think there are two separate kinds of properties here:
(1) properties that apply to any value used as an "exception block" (unique ID and textual name);
(2) properties that apply only to exception blocks whose allocation points are known at compile time.

I suspect it is the case that the OCaml system does not have a property of kind (1) that requires all exception blocks to be mutable.

Property (2) is what this patch is concerned with; I don't think this should affect demarshalled exception blocks, since they're allocated in a different way and the mutation is presumably known to be on one of these blocks (rather than on any statically-allocated one).

**Comment by alainfrisch** [comment]
The proposal is a clear improvement. The current state is only the result of my laziness (reusing the runtime primitive already available, and consequently marking the block as mutable).

**Comment by mshinwell** [comment]
@garrigue Does this look ok to you?

**Comment by garrigue** [comment]
This is a new primitive, so this looks fine to me.
Actually, I've done the marshaling of objects, but not of exceptions, so as long as you don't break objects I'm fine :)

**Pull request merged**
