### PR TITLE
Fix PR7244

### PR DESCRIPTION
**Pull request by chambart**
Flambda does not handle constants like Lambda, hence lambda constant blocks where turned into a sequence of calls to the makeblock primitive to let the right pass deal with it.

On some examples with gigantic constant arrays, this turned to be a performance bottleneck (Because the representation with an enormous sequence of lets was just too big). This patch simply turn Lambda constants into that into Flambda constants to avoid creating those lets.

For reference http://caml.inria.fr/mantis/view.php?id=7244

### CODE REVIEW

**Comment by chambart** [comment]
This is apparently what prevents the guys from AHREF from testing flambda, so even if it fix a bug that isn't really critical, @damiendoligez would you accept that for 4.04 ?

**Comment by mshinwell** [comment]
I can review this within the next few days.

**Comment by damiendoligez** [comment]
> This is apparently what prevents the guys from AHREF from testing flambda, so even if it fix a bug that isn't really critical, @damiendoligez would you accept that for 4.04 ?

With careful review and a test case, yes. You should also add a `Changes` entry.

**Comment by chambart** [comment]
I'll do the Change, but I'm not sure how to write a test case for this. It only change the compilation time and memory.

**Comment by damiendoligez** [comment]
Just test that large constant arrays are compiled correctly, since that's the part of the compiler that you change.

**Comment by chambart** [comment]
Ok, that is easy to test (it does not need to be large). I will first check that it does not already exist. (I think this is the case)

**Comment by damiendoligez** [comment]
Can you get a review? @mshinwell or @lpw25 ?

**Comment by chambart** [comment]
This was triggering a problem somewhere else, so I added a fix for that also, and some tests.

The other problem was that constant float arrays (allocated at toplevel) couldn't be created with symbol arguments.

**Comment by mshinwell** [comment]
Please add a changelog entry, since this has affected at least one user.
I suggest copying the comment from one of the test cases about patching arrays post-hoc into the code somewhere, so we don't forget about it.
OK for 4.04 with those changes.

**Comment by damiendoligez** [comment]
ping @chambart ?

I could do the `Changes` entry myself but I don't know where to put the comment that @mshinwell asked for...

**Comment by chambart** [comment]
Comment added and branch rebased. Ready to go.

**Pull request merged**
