### PR TITLE
2 fixes for 4.04

### PR DESCRIPTION
**Pull request by lefessan**

### CODE REVIEW

**Comment by alainfrisch** [comment]
You should make this PR against the 4.04 branch, not trunk.

**Comment by lefessan** [comment]
Does it really matter ? I would expect one branch to merge it, the other one to cherry-pick the commit...

**Comment by alainfrisch** [comment]
@damiendoligez : what's your preference?  I would expect that things intended to go to 4.04 should go to that branch directly, and that branch will be directly merged in trunk at some point.  This avoids some manual work to identify which commits to cherry-pick (moreover, my understand is that git cannot really track cherry-picking, contrary to SVN, which increase the risk of conflict upon merges).

**Comment by lefessan** [comment]
@alainfrisch After discussion with @damiendoligez , the preferred process is to merge into trunk, and to cherry-pick commits to 4.04 (or vice-versa).

**Comment by damiendoligez** [comment]
git does track cherry-picking well enough.

**Pull request merged**
