### PR TITLE
PR#5960: add List.{cons,consr}

### PR DESCRIPTION
**Pull request by dbuenzli**
See http://caml.inria.fr/mantis/view.php?id=5960

### CODE REVIEW

**Comment by ygrek** [comment]
FWIW, in our codebase all usages of `cons` with this signature were written as `flip cons`, so eventually we switched to `cons : 'a list -> 'a -> 'a list`

**Comment by dbuenzli** [comment]
Right this won't work with e.g. `List.fold` but it does e.g. with `Set.fold`. It seems to me that the proposed signature of `cons` is too widespread in libraries and functional programming languages to be switched to what you propose. I'll add `List.snoc` to the proposal.

**Comment by dbuenzli** [comment]
Added `List.snoc`. About the name, I contemplated a few alternative:

* `rcons`, `rev_cons`. Dismissed as confusing w.r.t. to what the other `List.rev_*` functions do.
* `flipped_cons` a little bit long winded. 
* `fcons` maybe a little bit obscure, doesn't seem to be an established pattern. 

Depending on who you are `List.snoc` may seem obscure aswell but it's part of the functional programming folklore and culture, so I feel it fits with OCaml.

**Comment by yallop** [comment]
I think `snoc` is more commonly used for the operation that appends an element to a list, i.e. `snoc xs x` == `xs @ [x]`

**Comment by dbuenzli** [comment]
@yallop you are right, after all these years of OCaml programming I forgot all my lisp. Do you have a naming suggestion ? I'd go with `rcons` which is sufficently far from the `rev_` prefix but I'm not really fond of it because of the `String.r*` functions.

**Comment by dbuenzli** [comment]
Tentative with `consr`, an alternative could be `cons_right`.

**Comment by gasche** [comment]
I'd suggest not adding another operator -- `flip cons` is enough. Maybe adding `flip`.

**Comment by dbuenzli** [comment]
@gasche adding to `Pervasives` is going to be more contentious. Here's my case for two operators: lists are pervasives in our code, folding functions aswell, in right or left forms so I'd like a direct operator for both forms.

**Comment by dbuenzli** [comment]
Regarding `consr` vs `cons_right` I think `consr` is a good name. From a code reading point of view these functions will most of the time be passed to folding functions for building lists. In that case what you are interested is reading that a list is being constructed, and the minutiae of argument order shouldn't be so important for understanding (assuming you are reading a typed checked program) so I even see the one letter distance of `cons` and `consr` as a virtue as you can almost elide the `r`. Also I find `fold_left List.cons_right` a little bit noisy and handedness obsessed.

**Comment by gasche** [comment]
I still have bad feelings about the function that is not `cons`. Unless one of the other gatekeepers object, I am thinking of closing this PR next month -- I personnally don't want to merge it, and if nobody steps forward to do it I see no point in keeping it open forever.

**Comment by dbuenzli** [comment]
> I still have bad feelings about the function that is not cons.

What kind of bad feelings ? I think that the argument I made for `consr` is a good one. These functions are very useful, they provide you concise `to_list` functions whenever you have left or right foldable data structures.  

Isn't it absolutely hilarious (or embarrassing depending on your view point) that a functional programming language that values so much higher-order functions and lists does not provide one to construct them in its standard library ?

**Comment by gasche** [comment]
Pick random people and ask them what

   `val consr : 'a list -> 'a -> 'a list`

does. I doubt you'll get more than 40% giving the right answer. I also suspect your score will *worsen* if you spell it out as "cons right".

**Comment by lpw25** [comment]
Personally, I'm not bothered either way about `consr`, but could we just merge the `cons` part now? The lack of a `cons` function in the stdlib is pretty embarrassing, and sometimes quite annoying.

**Comment by dbuenzli** [comment]
> I also suspect your score will worsen if you spell it out as "cons right".

Some names have to be learned and that's all, I don't have a problem with it. Now it seems you don't have a better name for this. Besides it is `List.consr` it's not `consr`. So when you are reading this you know your in a `List` context and the `cons` prefix will already be a big hint for what the function could do. Maybe you will have to look it up the first two or three times, but then it will be all natural. This is a name that is easy to *learn*.

But then well maybe you are right, let's perpetuate the myth of OCaml as an excellent compiler technology undermined by  a subpar standard library and just close this. 

With the years all this is getting *very* tiresome.

**Comment by dbuenzli** [comment]
> Pick random people and ask them what
> 
> val consr : 'a list -> 'a -> 'a list
> does. I doubt you'll get more than 40% giving the right answer. I also suspect your score will worsen if you spell it out as "cons right".

Frankly I'm completely puzzled by this comment. We could say exactly the same for at least a dozen of the functions of the `List` module, `fold_left` and `fold_right` in the first place. These are names you have to learn what they do.

**Comment by trefis** [comment]
2015-04-13 16:48 GMT+01:00 Daniel Bünzli <notifications@github.com>:
>
> I also suspect your score will worsen if you spell it out as "cons right".
>
> Besides it is List.consr it's not consr. So when you are reading this you know your in a List context and the cons prefix will already be a big hint for what the function could do.

Yeah I'm not sure that people would be wondering whether it applies to
lists or not, the type can tell you that. However, given the name, one
might thing that this function adds an element "on the right of a
list" ("who would ever think about something like that?" you might
ask, well basically everyone coming from python and such).

> Some names have to be learned and that's all

That is true, but I'm not sure this quite applies here. In this case,
it's not that we don't know the name for the thing we want to do, it's
that we have a name whose meaning might be misleading.

I am in favor of cons, but I don't like consr.

**Comment by trefis** [comment]
2015-04-13 16:58 GMT+01:00 Daniel Bünzli <notifications@github.com>:
>
> Pick random people and ask them what
>
> val consr : 'a list -> 'a -> 'a list
> does. I doubt you'll get more than 40% giving the right answer. I also suspect your score will worsen if you spell it out as "cons right".
>
> Frankly I'm completely puzzled by this comment. We could say exactly the same for at least a dozen of the functions of the List module, fold_left and fold_right in the first place. These are names you have to learn what they do.

Once again, you have to learn fold_left/right if you have never
encountered such a function. If you come to ocaml with some functional
experience (haskell, erlang, whatever) the names there are the same
for these functions.

You won't find consr in these however.

**Comment by dbuenzli** [comment]
> However, given the name, one
> might thing that this function adds an element "on the right of a
> list" ("who would ever think about something like that?" you might
> ask, well basically everyone coming from python and such).

Again there are things that need to be learned. You cannot do anything against that unless you want to be fully explicit (think objective-c) and be completely unreadable. Besides since we have functions with `_left` and `_right` suffixes, assuming naming consistency you should not see a final `r` as standing for "right". Other than that it is always a bad idea to judge things in terms of beginners/newcomers, in designing the system you want to cater the working programmer.

> I am in favor of cons, but I don't like consr.

Then propose something better. I have pondered many alternative including `flipped_cons`, `cons_flipped`, `rev_cons`, `cons_rev`, which I find worse and more misleading (since the `flip` or `rev` could apply to the list itself). It seems hard to find a good name for this function, I think that `consr` is the least misleading and most learnable name. But I'll happily change it to something better if someone provides me a good name.

**Comment by dbuenzli** [comment]
> You won't find consr in these however.

Because they don't have a function with such a signature. I would have happily reused one of their names it they had one.

**Comment by trefis** [comment]
2015-04-13 17:22 GMT+01:00 Daniel Bünzli <notifications@github.com>:
>
> You won't find consr in these however.
>
> Because they don't have a function with such a signature. I would have happily reused one of their names it they had one.

Sure :)
I don't have any good name to propose, I'd rather use "flip cons"
(i.e. I would rather have flip in Pervasives).
I do have a question however: if rev_cons and cons_rev are more
misleading than consr, and "you should not see a final r as standing
for 'right'", how could consr be any less misleading?

**Comment by dbuenzli** [comment]
> I don't have any good name to propose, I'd rather use "flip cons"

I already made the case a few comments above for having both operators directly.

> I do have a question however: if rev_cons and cons_rev are more
> misleading than consr, and "you should not see a final r as standing
> for 'right'", how could consr be any less misleading?

`r` can be seen as either `right` or `reversed` but at the *argument* level (which is the reason why it's diffcult to convey in the name, we usually name things in terms of what they do on the structures they operate on). I won't dictate what you want to have in your head for that `r` (but the doc string I wrote hints that it stands for argument *reversed*). 

The problem with `rev` is that it is already used as a prefix in the `List` module to mean reversed list. `consr` is less misleading because its slighlty cryptic and unconventional nature means you will have to look it up and there's no chance you mix it up with another existing convention.

**Comment by dbuenzli** [comment]
> but at the argument level (which is the reason why it's diffcult to convey in the name, we usually name things in terms of what they do on the structures they operate on).

Well in fact if we look at the module (and disregard evaluation order which is unspecified anyways) the convention exists: `fold_left` and `fold_right`. So if people are really too concerned by this `consr` we could simply rename the two functions to `cons_left` and `cons_right`, be handedness obsessed and consistent.

**Comment by jpdeplaix** [comment]
I would personally be more in favor of adding ```flip``` (in Pervasives) and ```cons``` but not ```consr``` as ```flip``` is general enough to cover this.

**Comment by Octachron** [comment]
Concernig the naming debate, what do you think of `cons_to`? 

It avoids the semantic confusion with `cons_at_the_end_of_the_list` or `cons_and_reverse`. The similarity with `cons` might even help the reader to understand that the only difference with `cons` is the ordering of argument.

**Comment by dbuenzli** [comment]
> Concernig the naming debate, what do you think of cons_to?

Not a bad suggestion !

So if I get a clear indication that this will be merged I change the PR to either: 

1. `cons` and `cons_to`
2. `cons_{left,right}` which mirroringly resonate as the functional neutral element of `fold_{right,left}` and 

Personally I just want these two damned functions in the List module and don't really care if it's under the `cons[r]`, `cons[_to]` or `cons_{left,right}` forms.

**Comment by dbuenzli** [comment]
> Well in fact if we look at the module (and disregard evaluation order which is unspecified anyways) the convention exists: fold_left and fold_right.

Brain not good today. In fact the `_left` and `_right` is not only about argument flipping, it's also of course where you start from with the accumulator. So at that point I'd say it is better to either have `cons[r]` or `cons[_to]`.

**Comment by agarwal** [comment]
My 2 cents. I think only `cons` should be added. The stdlib (and other libraries) are full of functions where you wish the arguments were in a different order (sometimes). Should we add alternatives for them too? It seems messy to have multiple functions that do the same thing, unless you can come up with a systematic way of doing so (e.g. the *Labels modules). An `r` suffix doesn't succeed in that.

**Comment by dbuenzli** [comment]
> The stdlib (and other libraries) are full of functions where you wish the arguments were in a different order (sometimes).

Sure great, then we'll have `List.cons` in !  But it doesn't work most of the time (as @ygrek rightly mentions, i.e. left folds).

That's completely retarded. Fine, live in your retarded and misdesigned world --- or `flip`ped world if you manage to convince any of the God Gatekeeper to get that in `Pervasives`. I personally have better things to do in life than convince those pseudo-Gods Gatekeepers that live in another world than mine. 

Good luck, I no longer care. Let's just make jokes about the retarded state of the OCaml stdlib, it's going to be much more fun.

**Pull request closed without merging**
