### PR TITLE
Makefile: tests depend on ocamltest

### PR DESCRIPTION
**Pull request by madroach**

### CODE REVIEW

**Comment by dra27** [comment]
I'm largely neutral on these kind of changes in the toplevel Makefile. I think `make tests` is intended just to be shorter to type than `make -C testsuite all`. The tree needs to be built as well - what's your context for the change?

@shindere?

**Comment by madroach** [comment]
I'm currently fixing the regression test target in OpenBSD ports. I could also add a `pre-test:` recipe to build `ocamltest`. I don't have strong opinions on this. I just thought, testsuite depends on ocamltest, so let it depend on ocamltest in the Makefile, too.

**Comment by dra27** [comment]
Is this packaging from a release tarball? Assuming it's 4.11 or later, you also pass `--enable-ocamltest` to `configure` which will force ocamltest to be built during `gmake world.opt` for release tarballs (and release tags in git)

**Comment by madroach** [comment]
I could do that as well. Is `ocamltest` supposed to be installed alongside the compiler or is it more of an internal thing ?

**Comment by dra27** [comment]
It’s entirely internal, which is why by default it’s off in the release builds (just because otherwise something is compiled which is neither installed nor used). I should have added that `--enable-ocamltest` still doesn’t install `ocamltest`

**Comment by madroach** [comment]
Ok. Got it. Now, should I fix this by adding `--enable-ocamltest` or rather by this PR, which is what I currently do?

So, accept or reject this PR?

**Comment by dra27** [comment]
For the OpenBSD package, I'd fix it with `--enable-ocamltest`, yes. For the PR, I leave that up to @shindere - my "problem" is that it moves goes from specifying no dependencies at all to only specifying one/some of them... but I'm not strong enough in that opinion to accept or reject!

**Comment by shindere** [comment]
I think I prefer this to be fixed by the use of the configure option
which is here especially for that.
It makes not much sense to me to enforce in the build system something
that is nicely achieved by configure. Somehow it feels to me accepting
this PR would duplicate a logic unnecessarily.

Also, I'd like to mention that ocamltest is indeed not installed
currently. But, as its initial author, I did have the hope that it would
ultimately be installed and be used to write other testsuites than the
compiler's one.

**Comment by madroach** [comment]
ok. Thanks for your insights.

**Pull request closed without merging**
