### PR TITLE
Improve parse error messages in case of mismatched struct/sig

### PR DESCRIPTION
**Pull request by Julow**
Hi !

This PR improves parsing error messages in case `struct` was expected instead of `sig`, or the opposite.

This error (in a signature):

```
Line 3, characters 18-24:
3 |   module type S = struct end
                      ^^^^^^
Error: Syntax error: 'end' expected
Line 2, characters 16-19:
2 | module type S = sig
                    ^^^
  This 'sig' might be unmatched
```

Becomes:

```
Line 3, characters 18-24:
3 |   module type S = struct end
                      ^^^^^^
Error: Syntax error: sig expected.
```

There is also a fix for mismatched `=` and `:` in module declaration, or the opposite, especially this one (in a signature):

```
Line 3, characters 11-12:
3 |   module M = struct end
               ^
Error: Syntax error: : expected.
```

Which previously was parsed until the end:

```
Line 3, characters 0-2:
3 | ;;
    ^^
Error: Syntax error
```

### CODE REVIEW

**Comment by gasche** [comment]
The long-term plan is to get rid of `error` rules in the parser and replace it with a better syntax-error mechanism. This said, currently we don't have better syntax-error mechanism, and we still have error rules, so low-maintenance improvements to existing errors is perfectly reasonable in principle.

I reviewed the code and it looks fairly sensible. One question, though: why these errors? I suppose that you have a reason for working on those. Is it just that you were bitten by them recently, or you got reports from people that they are difficult to understand, or something else? It would help justify the change if we had some justification for it.

**Comment by Julow** [comment]
The reason is that I'm bitten by them regularly, personally. I decided to work on these now because I made the mistake again and because I noticed similar rules in the parser recently.

**Review by gasche — APPROVED** [review]
I waited too long on this PR, which I think is perfectly fine. (In the long run we want to do things differently, but in the short- to medium-term this is a nice improvement and th ecode is perfectly fine.)

@Julow could you rebase on the current trunk?

**Comment by Julow** [comment]
Rebased. I also noticed that the location wasn't right in this case:

```ocaml
module M : sig end
let next_item = ()
```

It was pointing to the 'let' so I changed it to highlight "after" the location of the module type, in this example the end of the first line.
This removes the highlighting, but it was wrong anyway, this PR will bring it back: https://github.com/ocaml/ocaml/pull/11679

**Comment by gasche** [comment]
I don't like the `loc_after` business. Pointing to the `let` in your example above is not wrong, this is indeed the first token that is invalid. Other `expecting` cases in the parser use the location of the error token, let's keep doing that. If you are convinced that the error message is confusing in this case, you can remove the corresponding production from the parser and focus the PR on sig/struct. (But I think that the `=`/`:` cases are also fine.)

**Comment by Julow** [comment]
You are right, let's not add a special case for that. I reverted that commit. The error message is still improved.

**Comment by gasche** [comment]
This is good for merging when the CI agrees. Do you wish to rebase your commits or should I squash them together?

**Comment by Julow** [comment]
Squash is fine, thanks!

**Comment by gasche** [comment]
Merged, thanks!

If you want to thank your kind reviewer and are not sure how to, I have an issue on a repo of yours that would benefit from the attention of a maintainer:

https://github.com/ocaml/ocaml.org/issues/534

**Pull request merged**
