### PR TITLE
remove experimental/

### PR DESCRIPTION
**Pull request by gasche**
This subdirectory was used to store experimental patches on some older
version-control system where branching (or discussing branches?) was
inconvenient. It doesn't make much sense anymore now, and getting rid
of it simplifies a couple places that had to grow around it.

Suggested-by: Nicolás Ojeda Bär

(no change entry needed)

### CODE REVIEW

**Comment by gasche** [comment]
cc @alainfrisch @garrigue @damiendoligez, who still have stuff in `experimental/`.

**Comment by pmetzger** [comment]
I'm in favor, though I will note that `experimental/frisch/extension_points.txt` contains some information that still isn't documented anywhere else. (It also contains a lot of stuff that doesn't need saving.)

**Comment by gasche** [comment]
Link: https://github.com/ocaml/ocaml/blob/8106136/experimental/frisch/extension_points.txt

That's a good point. This doesn't prevent removing the content from the git repo (the link right above, for example, gives access to the content), but it would be nice to move this content somewhere else. (This is orthogonal to the present PR.) 

My suggestion would be to merge the content there into the documentation of attributes and extensions in the reference manual, with a particular eye to integrating the nice examples, small and larger, that @alainfrisch used -- the manual mostly contains grammar rules, so it is much drier to read.

@pmetzger, would you be able to help with this transition? cc @Octachron as well.

**Comment by pmetzger** [comment]
> That's a good point. This doesn't prevent removing the content from the git repo (the link right above, for example, gives access to the content), but it would be nice to move this content somewhere else. (This is orthogonal to the present PR.)

Oh, absolutely. The directory should be removed, we can preserve that content regardless.

> My suggestion would be to merge the content there into the documentation of attributes and extensions in the reference manual, with a particular eye to integrating the nice examples, small and larger, that @alainfrisch used -- the manual mostly contains grammar rules, so it is much drier to read.

Agreed.

> @pmetzger, would you be able to help with this transition? cc @Octachron as well.

If @Octachron is willing to help, I'm willing to try doing it.

**Comment by garrigue** [comment]
I'm fine with this. The data will still be available in old branches anyway.

**Comment by alainfrisch** [comment]
I'm also fine with this.

**Comment by gasche** [comment]
@alainfrisch, as the one remaining active users of `experimental/`, I think that if someone is to approve this PR it should be you. (I think that we don't need to wait for @damiendoligez who generally doesn't reply.)

All of you, do you have opinions/recommendation on which content should be preserved in the repository by being placed somewhere else, similarly to the attributes/extensions design documentation that we discussion?

**Review by alainfrisch — APPROVED** [review]

**Comment by alainfrisch** [comment]
> All of you, do you have opinions/recommendation on which content should be preserved in the repository by being placed somewhere else, similarly to the attributes/extensions design documentation that we discussion?

The information that `ocamllex -ml` can be faster than `ocamllex` (as described in https://github.com/ocaml/ocaml/blob/4.07/experimental/frisch/bench_ocamllex_optims.md) might be useful to keep somewhere, perhaps just as a note in the manual?

**Comment by shindere** [comment]
Gabriel Scherer (2018/09/10 00:34 -0700):
> @alainfrisch, as the one remaining active users of `experimental/`, I
> think that if someone is to approve this PR it should be you. (I think
> that we don't need to wait for @damiendoligez who generally doesn't
> reply.)

I discussed with him in the past about experimental and as far as his
subdirectory is concerned, he said that`checkheaders` has been
integrated to `check-typos`and can be safely removed.
`check-bounds.diff` is joint work with @mshinwell I think but we started
discussing its integration to the compiler so I believe it's not a big
deal getting rid of the patch.

**Comment by gasche** [comment]
Thanks @shindere!

@alainfrisch, would you volunteer to submit a manual PR for `ocamllex -ml`?

**Comment by alainfrisch** [comment]
Sure, done.

**Comment by gasche** [comment]
Thanks!

(The ocamllex-related PR is #2037 )

**Comment by Octachron** [comment]
@pmetzger , sure, I am willing to help integrating the relevant information of `experimental/frisch/extension_points.txt` into the manual.

**Comment by shindere** [comment]
Gabriel Scherer (2018/09/10 02:17 -0700):
> Thanks @shindere!

My pleasure! :)

**Comment by pmetzger** [comment]
@Octachron Poke me in one of the usual channels. One problem is I'm very busy this week, so feel free to start without me unless you share that problem.

**Pull request merged**
