### PR TITLE
[minor] runtime/Makefile: deduplicated C source files + diff-friendly format

### PR DESCRIPTION
**Pull request by gasche**
Adding a new .c file to the runtime right now involves guessing an insertion into an unordered list with weird formatting, and you have to do it twice because the lists for bytecode and nativecode are duplicated (with different orders). This trivial PR makes adding a new file a no-brainer.

### CODE REVIEW

**Comment by gasche** [comment]
This is a trivial change that would make runtime hacking easier, so do not hesitate to review :-)

**Review by nojb — APPROVED** [review]
LGTM. Nice cleanup, thanks!

**Comment by gasche** [comment]
Thanks!

(I'd like to return the favor by reviewing something for you... but maybe I'll wait after this META matter is settled :-D)

**Comment by nojb** [comment]
> I'd like to return the favor by reviewing something for you

Thanks. If you find yourself with time on your hands and feel in desperate need of PRs to review, you may want to give a shot to one or both of #11002 and #10986, which should be relatively uncontroversial...

**Pull request merged**
