### PR TITLE
expect_test: add a flag to get short errors

### PR DESCRIPTION
**Pull request by trefis**
Ping @diml .

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by shindere** [comment]
@trefis the ocamltests file in tests/typing-sigsubst mentions a test_locations.ml
file which is missing, causing CI to be currently broken for trunk.

Did this actually pass AppVeyor and Travis?

Are you subscribed to Inria CI notifications?

**Comment by trefis** [comment]
Ah indeed, that's my bad, sorry.
That was some leftover for another thing I was working on in parallel; I guess both Jérémie and I missed that in the diff.

I just pushed a commit ( https://github.com/ocaml/ocaml/commit/b3ad13d2d9b6039b06e2b14c4d97e20e9b65e214 ) to remove it.

I am not subscribed to Inria CI notifications; where can one subscribe?

**Comment by shindere** [comment]
Thomas Refis (2018/04/24 08:42 -0700):
> Ah indeed, that's my bad, sorry.

No problem.

> That was some leftover for another thing I was working on in parallel;
> I guess both Jérémie and I missed that in the diff.

Yep yep, no problem. It's just that I owuld have expect that the other
IC which are used to test PRs would hhave failed, which could have
helped you to notice the thing before merging rather than after.

> I just pushed a commit (
> https://github.com/ocaml/ocaml/commit/b3ad13d2d9b6039b06e2b14c4d97e20e9b65e214
> ) to remove it.

Thanks!

> I am not subscribed to Inria CI notifications; where can one
> subscribe?

https://sympa.inria.fr/sympa/info/ocaml-ci-notifications

In cas you can't access the page let me know, just send me the
email-adress you'like to use and I'll add you.

**Comment by trefis** [comment]
Thanks, just subscribed!

Yes, the CI would have failed, had I waited for it...

**Comment by shindere** [comment]
Thomas Refis (2018/04/24 08:53 -0700):
> Thanks, just subscribed!

Great!

> Yes, the CI would have failed, had I waited for it...

I'm also a bit impatient sometimes. :)

**Pull request merged**
