### PR TITLE
Adding a left-to-right function composition operator to Pervasives module

### PR DESCRIPTION
**Pull request by ghost**
Batteries Included [provides](http://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatPervasives.html) a "left-to-right" function composition operator `%>`.

This pull-request:
- adds a definition of `%>` operator to the `Pervasives` module
- adds a few tests for it to the test-suite

In practice, there are many valid opportunities and [good reasons](https://www.cs.kent.ac.uk/people/staff/dat/miranda/whyfp90.pdf) to use it.
It is a pity that the standard library of Ocaml does not yet provide it.

### CODE REVIEW

**Comment by ghost** [comment]
I am not quite sure whether `%>` is a good name but in this case I followed Batteries Included to avoid capricious differences.

**Comment by yminsky** [comment]
I'm not excited about adding such operators. While operators increase concision, they often detract from readability. Point free code with lots of different combinator-operators is especially opaque. We already have |> and @@, and in many third party libraries >>| and >>=.  I suggest that we should be very reluctant to add more.

**Comment by ghost** [comment]
I think that the questions:
- Was it a good idea to add `|>` to the standard library?
- Was it a good idea to add `@@` to the standard library?

make sense and deserve an answer but they should be considered separately from this pull-request.

Let me first state that I consider you @yminsky as well as [John Hughes](https://www.cs.kent.ac.uk/people/staff/dat/miranda/whyfp90.pdf) smarter than me.
I find it odd that you two have different opinion on the matter.

I was able to follow John Hughes arguments but I was not able to follow yours
(e.g. I do not understand how "it is a bad idea to provide an operator enabling us to conveniently compose functions follows from "Point free code with lots of different combinator-operators is especially opaque.")

**Comment by nojb** [comment]
In my experience these kind of operators are only useful in trivial cases, since compositions written using them are hard to understand as soon as the terms involved are complicated, include side-effects, other (!) such operators, etc.

It also breaks polymorphism in OCaml: if we `let h = f %> g` then `h` is not generalized since it is a function application, while `let h x = g (f x)` is properly generalized (and only one character longer).

**Comment by SGrondin** [comment]
I 100% agree with @yminsky . One of the strengths of OCaml is a culture that favors readability over concision-at-all-costs. One only has to look at [Haskell](https://hackage.haskell.org/package/lens-4.14/docs/Control-Lens-Operators.html) or Scala to see that this road leads to madness. 

Sure, you can already define your own operators and your reasoning is that standardizing those operators would lead to better cohesion and code that is easier to understand. I disagree and I'd rather we keep that cat in the proverbial bag for as long as possible. Once operators are added, they can't be removed easily and we'll pay the cost of the added weight (however small) forever.

**Comment by paurkedal** [comment]
I believe there may be a slight performance gain by choosing a right associative operator for the one proposed here and a left associative for the classic composition (∘).  At least as benchmark of ∘, suggested around 10 % which confirmed my initial guess, so I renamed my own to `@>` and `<@`.
There was not much choice after adding the requirement that the operators should be maximum two characters and look mirrored.

These operators are trivial to add as needed, so I think the best argument to add them is if there is an opportunity to optimise by making them builtins.  I accept the argument about the value restriction, if this can't be avoided using a builtin.  I think readability, on the other hand, depends on how the operators are used.  Where there are certainly opportunities of obscure uses, there are other cases where it's natural to think in terms of composition, where (semi-)point-free style gives the right suggestion.

**Comment by DemiMarie** [comment]
I think that the value restriction can be avoided by making this operator be treated specially by the type checker.

**Comment by ghost** [comment]
@paurkedal 

> I believe there may be a slight performance gain by choosing a right associative operator for the one proposed here and a left associative for the classic composition (∘).

Yes. We have the possibility to introduce either the left-associative or the right-associative version of this operator. Since I did not think that it makes sense to propose introducing both versions, I have decided to picked only one of them. There are different criterias that could guide our choice:
- tradition
- practicality
- performance

If the tradition meant more to us than practicality, we would have chosen the right-associative variant because that one is already routinely used by mathematicians.

If the practicality means more to us than tradition, we might want to choose the left-associative variant because it allows us to write functions in the same order in which they will be applied.

I must admit I did not consider performance.

@paurkedal 

> I think readability, on the other hand, depends on how the operators are used. Where there are certainly opportunities of obscure uses, there are other cases where it's natural to think in terms of composition, where (semi-)point-free style gives the right suggestion.

This is exactly how I feel.

(I wasn't able to follow arguments of @yminsky @SGrondin relevant to this pull-request.)

@paurkedal 

>  I accept the argument about the value restriction, if this can't be avoided using a builtin.

@DemiMarie 

> I think that the value restriction can be avoided by making this operator be treated specially by the type checker.

I am not sure what you mean by _value restriction_.

**Comment by alainfrisch** [comment]
> If the tradition meant more to us than practicality, we would have chosen the right-associative variant because that one is already routinely used by mathematicians.
> 
> If the practicality means more to us than tradition, we might want to choose the left-associative variant because it allows us to write functions in the same order in which they will be applied.

I'm lost: composition is semantically associative and thus making it syntactically left- or right-associative should be irrelevant to the user, no?

**Comment by paurkedal** [comment]
> I'm lost: composition is semantically associative and thus making it syntactically left- or right-associative should be irrelevant to the user, no?

@alainfrisch Yes, left- vs right-associative is only about performance.  I'm sure @matej-kosik meant left-to-right (pipe-style) vs right-to-left (classic (f ∘ g) x = f (g x)) evaluation order.

@matej-kosik I agree we don't need both in the standard library, though the left-to-right variant is the one where it makes a difference.

**Comment by ghost** [comment]
@alainfrisch

> I'm lost: composition is semantically associative and thus making it syntactically left- or right-associative should be irrelevant to the user, no?

Sorry for the confusion. It does not makes sense to refer to left- or right- associativity.

I was trying to refer to either `%>` or to `%` [operators](http://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatPervasives.html#6_Fundamentalfunctionsandoperators) (regardless of the names we in the end decide to choose).

Sorry about that.
(the associativity of both, due to Ocaml rules, would be the same, if I am not mistaken again).

**Comment by paurkedal** [comment]
> I am not sure what you mean by _value restriction_.

@matej-kosik [1] seems like a good explanation.  The issue is usually avoidable by η-expanding definitions (let f = ... --> let f x = ... x), though the situation has changed a bit with GADTs.  The issue here is that a composition operator invites a programming style where one easily bumps into the value restriction unnecessarily. That is, unless the compiler knows about the composition operator and does the right transformations or analysis.

[1] https://realworldocaml.org/v1/en/html/imperative-programming-1.html#side-effects-and-weak-polymorphism

**Comment by damiendoligez** [comment]
> That is, unless the compiler knows about the composition operator and does the right transformations or analysis.

I really don't think it would be a good idea to add complexity to the type-checker just to support these operators.

**Comment by DemiMarie** [comment]
In OCaml, the result of a function call cannot in general be assigned a
polymorphic type.  This is necessary to preserve soundness: otherwise, a
polymorphic mutable object could be created that could be written as one
type and read as a different one.  In fact, it is Haskell's lack of a value
restriction that makes unsafePerformIO type unsafe.

However, we know that function composition creates no mutable state.  So
OCaml could treat its result as a potentially polymorphic value.

**Comment by alainfrisch** [comment]
Technically, it does not seem very difficult to add a `non-expansive` marker on `external` primitives (introduced with an attribute), so that the application of such a primitive to N non-expansive arguments (where N is the primitive's arity) would be declared as non-expansive (by Typecore.is_nonexpansive).

This would cover a built-in composition operator as discussed here (defined as a %-external in Pervasives), but also, for instance `Obj.magic` (it's often a bit annoying that the value restriction prevents the generalization of an application of `Obj.magic`).  Having the composition operator mapped to a %-external would also make it easy to optimize its compilation even in bytecode (and with JS backends).  The compiler would turn a maximal sequence of nested composition `f1 %> ... %> fn` (with arbitrary parenthesizing) into `fun x -> fn (... (f1 x)...)`, avoiding many closure allocations.

**Comment by paurkedal** [comment]
Though outside the scope of this PR, a non-expansive attribute for regular value definitions could help generalising GADTs, as well, providing an "escape mechanism" from the value restriction for cases where mutability is not needed.  This would require checking expansiveness of used-defined functions, and take it into account when matching signatures, so presumably more work to implement, but along the same lines.

**Comment by paurkedal** [comment]
Given the possibility of optimising chains of `%>` in the compiler, I have no reservation about the chosen operator.  The reason for batteries choice it may be because there is a single-letter `%` free to use as the classic composition operator, and maybe I'm asking too much, but it would be nice to have that variant, as well.

@matej-kosik

> If the practicality means more to us than tradition, we might want to choose the left-associative variant because it allows us to write functions in the same order in which they will be applied.

The order of evaluation is not necessarily the order one understands the problem.  I often use the `|>` operator, so I partially agree, but it's also natural to start thinking about what you need, decide which function will provide it, then ask what the arguments need to be, recursively producing a function call or composition in the classic order.

**Comment by alainfrisch** [comment]
> Though outside the scope of this PR, a non-expansive attribute for regular value definitions could help

This would need to be tracked thoroughly in the type system, and might be non trivial to design (the notion of being non-expansive in a signature should be accompanied with the "natural" arity for the function).  I was proposing a much less ambitious design based on `external` primitives, which already implement the required plumbing (explicit representation in signature; ability to attach and track properties -- such as the "noalloc&friends" stuff currently; explicit tracking of the function arity).

**Comment by paurkedal** [comment]
@alainfrisch I see.  I was actually wondering about the natural arity and the fact that the expansiveness of the function may depend on the expansiveness of its arguments.  Good had a simpler solution in mind.

(I understand these annotations would only be a coarse approximation to a full effect system.  We declare a function non-expansive in the sense that it will not itself, on any of its "own" reductions produce or modify mutable state, provided that any function passed to it directly or though another value is also non-expansive.  Without modifying value types, it would be necessary to propagate non-expansiveness up to the definition, so that a compound value containing a single expansive value makes the whole value expansive when bound to a module.  It's not a full solution, but one can hope to factor out any mutable state out of the GADT parts of the API.)

**Comment by ghost** [comment]
@paurkedal 

> I believe there may be a slight performance gain by choosing a right associative operator for the one proposed here and a left associative for the classic composition (∘).

I have tried to reproduce what you say like this:

``` Ocaml
let (%) f g x = f (g x)
let (%>) f g x = g (f x)
let id x = x
let ignore _ = ()

let number_of_iterations = Scanf.sscanf Sys.argv.(1) "%d" id

let test1 () =
  for _ = 1 to number_of_iterations do
    ignore ((succ % succ % succ % succ) 0)
  done

let test2 () =
  for _ = 1 to number_of_iterations do
    ignore ((succ %> succ %> succ %> succ) 0)
  done

let time label f =
  let t = Sys.time() in
  let result = f () in
  Printf.printf "Execution time : %s : %fs\n" label (Sys.time() -. t);
  result

;;

Printf.printf "DEBUG: number_of_iterations = %d\n" number_of_iterations;
time "% % % %" test1;
time "%> %> %> %>" test2;
```

``` make
MLFILES = $(wildcard *.ml)
EXECUTABLES_BYTE = $(patsubst %.ml,%.byte,$(MLFILES))
EXECUTABLES_OPT = $(patsubst %.ml,%.opt,$(MLFILES))

all : $(EXECUTABLES_OPT) $(EXECUTABLES_BYTE)

%.byte : %.ml
        ocamlc -annot -o $@ $<

%.opt : %.ml
        ocamlopt -annot -o $@ $<

clean :
        rm -f *.annot *.o *.cmi *.cmo *.cmx $(EXECUTABLES_BYTE) $(EXECUTABLES_OPT)
```

```
$ make && ./main.byte 100000000

   DEBUG: number_of_iterations = 100000000
   Execution time : % % % % : 25.133571s
   Execution time : %> %> %> %> : 23.545471s

make &&  ./main.opt 500000000

   DEBUG: number_of_iterations = 500000000
   Execution time : % % % % : 6.356397s
   Execution time : %> %> %> %> : 5.648353s
```

but I have failed. I am not sure how meaningful my test is, but it shows that there is a case in which `%>` is slightly faster than `%`, not the other way around.

**Comment by ghost** [comment]
I am not sure how would a meaningful benchmark(s) look like. But if the result were 10% performance difference (either way), I would still consider that as a noise rather than a signal. Although it would be good to track that and set an alarm if the performance difference reaches 50% or so.

**Comment by paurkedal** [comment]
@matej-kosik <strike>Yes, 10 % is what I got too, see my above post.</strike>  This was what I used:

``` ocaml
let ( *< ) f g x = f (g x)
let ( **< ) f g x = f (g x)

let testL f g = f *< g *< f *< g *< f *< g *< f *< g *< f *< g
let testR f g = f **< g **< f **< g **< f **< g **< f **< g **< f **< g

let clock () = Unix.((times ()).tms_utime)

let () =
  let x = ref 0 in
  let tL = ref 0.0 in
  let tR = ref 0.0 in
  for round = 0 to 9 do
    tL := !tL -. clock ();
    for i = 0 to 1000000 do
      x := testL succ pred !x
    done;
    tL := !tL +. clock ();
    tR := !tR -. clock ();
    for i = 0 to 1000000 do
      x := testR succ pred !x
    done;
    tR := !tR +. clock ()
  done;
  Printf.printf "\
    Left associative:  %g\n\
    Right associative: %g\n\
    Ratio: %g\n" !tL !tR (!tR /. !tL)
```

**Comment by damiendoligez** [comment]
This was discussed at the developer meeting two days ago and the consensus was in agreement with @yminsky and @SGrondin, so we decided to close this PR.

**Comment by bluddy** [comment]
@damiendoligez I appreciate the value of these dev meetings. Would it be possible either to record them and post them online or to transcribe them?

**Comment by gasche** [comment]
Note that giving a summary of each PR's discussion is effectively a way to produce distributed minutes of the discussions, where each part is placed where it is relevant. I think this is a reasonable trade-off (some aspects in the balance are the amount of work required, whether someone actually took detailed notes, and whether giving too detailed information about discussions incurs a risk of making people less tempted to give their opinion (especially when it is negative) or to rekindle an argument in a not-so-productive way).

**Comment by bluddy** [comment]
OK well, crazy idea here: how about we stream the meeting and have people participate somewhat on IRC?

**Pull request closed without merging**
