### PR TITLE
Build flambda

### PR DESCRIPTION
**Pull request by chambart**
This adds the required parts to the Makefile to build flambda (not use it yet).
The build now requires the `Compflags` script for per module options (like the stdlib) because flambda use constructor disambiguation (and use -principal to ensure that it is reasonable).

This is expected to fail until everything required by flambda is merged to trunk. I will rebase this branch when needed.

### CODE REVIEW

**Comment by gasche** [comment]
I seem to remember some script invocation during build adding a non-neglectible overhead to the build time. Is it possible to measure the impact of build time of the `Compflags` use? If it was an issue, maybe we could just  compile everything with `-principal`. (Or we could also use `ocaml.warning` attributes for module-specific warning selection.)

**Comment by mshinwell** [comment]
I do want to emphasise that the other warnings are as important (more so in some cases) as -principal for those files.

**Comment by alainfrisch** [comment]
Compiling everything with -principal might be slower than calling Compflags (to be checked).  What's missing is perhaps a way to specify global flags (such as -principal, but also inlining control, etc) directly in the source file.  It would be quite easy to interpret floating toplevel attributes (on the top of the file, before any non-attribute item) to control such settings; this would allow us to get rid of Compflags (also for the stdlib), and to simplify per-file settings also for user projects.

**Comment by hcarty** [comment]
@alainfrisch I've been wondering if the same could be done

**Comment by mshinwell** [comment]
I was going to post this morning basically what @alainfrisch writes above, about specification of global flags.

The disadvantage with this approach is that it doesn't allow per-directory control of warnings.

Another problem with the Compflags approach, conversely, is that it's easy to forget to add files there in the case where the flags do not apply to the whole directory.

I think on balance I'm leaning towards adding warnings at the top of the files if we could have global flags too.

**Comment by alainfrisch** [comment]
There are already functions that scan through floating attributes on top of compilation units (Builtin_attributes.{deprecated_of_sig, deprecated_of_str}).  It would make sense to rename these functions and have them handle other unit-wide compilation properties (principal, rectypes, safe-strings, optimization settings, etc).  Of course, they should then be called (from Compile/Optcompile) before type-checking, and we need to add the logic to backtrack the changes to Clflags after the current unit (when multiple units are compiled with a single invocation of the compiler).  All this should be pretty straightforward.

**Comment by mshinwell** [comment]
In which case maybe we should merge the Compflags on the understanding that we then work on the global attributes.  I would like this issue not to hold up the remainder of the flambda merge, which we are going to try to complete this week.

**Comment by alainfrisch** [comment]
The `-principal` flag is perhaps not a strong requirement (and it could slow down compilation quite a bit in itself), and warnings can already be controlled within each file.  So can we do without Compflags?  

And even for warnings: if I understand correctly, you need to disable those that prevent relying on type-based disambiguation.  But one could very well decide to allow this style globally in the compiler code base?  (I'm in favor of it, anyway.)

**Comment by gasche** [comment]
> In which case maybe we should merge the Compflags on the understanding that we then work on the global attributes. I would like this issue not to hold up the remainder of the flambda merge, which we are going to try to complete this week.

I think that's a reasonable argument, which I would support, but I would still be interested in a measurement of actual build time impact.

**Comment by mshinwell** [comment]
Well, part of the idea of using the global attributes is that there wouldn't be any build time impact.  I don't think it's worth spending manpower doing measurements of code (Compflags) that we're about to delete...

**Comment by xavierleroy** [comment]
GNU make has a relatively simple mechanism to set variables depending on the target being made.  This can be used as a cleaner and probably faster replacement for Compflags.  I don't think Compflags adds significantly to the compilation time, but I agree it's not very pretty.

**Comment by mshinwell** [comment]
Is there any problem with Windows support if we did something in the Makefile?

**Comment by xavierleroy** [comment]
GNU make is very portable between Unix and Windows, in my experience.

**Comment by alainfrisch** [comment]
The problem on Windows would rather be with Compflags, since the cost of spawning a new process is usually higher on this platform (and in this case, we go through Cygwin).

**Comment by mshinwell** [comment]
Does anyone favour a Makefile-based approach over declarations in each source file?
- With the declarations inside each file we lose the ability to specify these flags on a per-directory basis.  Some files may end up without the warnings, or maybe more likely, a slightly different set of warnings.  I think I'm more worried about the divergence implied by the latter since a complete absence of these declarations is probably quite noticeable.
- With the Compflags/Makefile-based approaches it's easy to miss the application of these warnings to file(s) in a directory where not all files are covered, e.g. asmcomp/ (where only the Flambda files have the higher warning level at the moment).

**Comment by alainfrisch** [comment]
I'm in favor of normalizing the set of warnings across all units.  I don't see why we would allow ourselves to a use a specific coding style (relying on type-based selection) only in one part of the project.  Couldn't we simply globally disable warnings that prevent this style?  As for using -principal or not, one could try to see the impact if we enable it globally;  it might very well be lost in the noise.  If not, one could not enable it by default, and either do the test once in a while, or only on the CI servers.

**Comment by mshinwell** [comment]
We can't reasonably normalize the set of warnings without a lot of work, unfortunately.  There is a lot of code which will fall foul of them at the moment.
I will try to measure whether just compiling current trunk with -principal produces any noticeable difference in speed.  If it does not, maybe we could enable that for all units.  (Then the warnings can go in the Flambda source files for the moment.)

**Comment by alainfrisch** [comment]
> We can't reasonably normalize the set of warnings without a lot of work, unfortunately. There is a lot of code which will fall foul of them at the moment.

I don't understand.  I thought you were only suggesting to disable warnings for flambda.  Do you allow suggest to enable more?

**Comment by mshinwell** [comment]
No no, it's enabling _lots_ more warnings for the flambda passes. :)

**Comment by alainfrisch** [comment]
Well, there is certainly no hurry to enable extra warnings. The only requirement is to disable those related to type-based selection, and I don't see why not to do it globally, then (esp. if -principal can be enabled for the entire project; and if not, it's fine for me as well).

**Comment by mshinwell** [comment]
I'm not quite sure what you meant, but I don't want to decrease the warning level below what we have at present for the flambda files.  However I don't think there is a problem with this; I can just put the extra warning specifications in each file.

**Comment by mshinwell** [comment]
Actually, I just checked Compflags, and there is in fact more apart from -principal which I was forgetting about:

-w +a-4-9+27-30-40-41-42 -principal -safe-string -strict-formats

Again, I don't really want to regress in terms of the amount of checking the compiler does on our code for the flambda files.

**Comment by mshinwell** [comment]
(However we could implement both safe-string and strict-formats in the manner @alainfrisch suggested earlier, I imagine.)

**Comment by mshinwell** [comment]
I just pulled a few more bits into this

**Comment by mshinwell** [comment]
@alainfrisch Could I have your opinion on strict-formats and safe-string as global attributes please?

I am tending to think we should merge this PR with the Compflags approach and then fix it next week using attributes.  I _really_ would like not to leave the merge in a half-done state lest trunk starts to diverge.

**Comment by alainfrisch** [comment]
> Could I have your opinion on strict-formats and safe-string as global attributes please?

I still think it's a good idea, and I'm fine if you commit the version based on Compflags, esp. if you can remove if before the release.

**Comment by mshinwell** [comment]
OK.  We will take care of implementing the attributes at this end (at Jane Street) and use Compflags in the meantime.  We should report back next week.

**Comment by mshinwell** [comment]
@chambart I am looking at the build failure for this feature now

**Comment by mshinwell** [comment]
Ah, of course, this won't compile yet until the array patch has been merged.  I made a couple of other fixes though.

**Comment by ghost** [comment]
Note that we already build the compiler with `-safe-string`. I tried to add `-strict-format` and had nothing else to change to make the compiler build so I just enabled it (87ef307)

**Comment by mshinwell** [comment]
I'm updating this patch now to remove Compflags and use warning attributes at the top of the files.

**Comment by mshinwell** [comment]
@chambart I will take care of making this patch compile once the necessary prerequisites have been merged

**Comment by damiendoligez** [comment]
One drawback of having attributes at the top of files is that you have to decide who has priority between them and `OCAMLFLAGS`. If the former, then `OCAMLFLAGS` becomes a lot less useful. If the latter, then the implementation is probably more complex. For warnings it's OK, but if we add more flags to this mechanism, we'll have to think about it.

At least for the stdlib stuff, I'm in favor of using GNU make features instead of `Compflags`, but that's orthogonal to this PR.

**Comment by mshinwell** [comment]
@chambart Please rebase this and try to get it to compile...

**Comment by chambart** [comment]
The build is fixed. I also needed to add a few more things in Compilenv in https://github.com/chambart/ocaml-1/commit/f1f0a798f680b9a8f43f6f2852e2752e21151b65

Two functions are left not implemented there to avoid pulling a too change, here.

**Comment by mshinwell** [comment]
@damiendoligez Please approve

**Comment by mshinwell** [comment]
(Or someone else)

**Pull request merged**
