### PR TITLE
Fix Unix.create_process cmdline escaping windows

### PR DESCRIPTION
**Pull request by nojb**
As discussed in [MPR#7480](https://caml.inria.fr/mantis/view.php?id=7480):

`Unix.create_process` takes a `string array` as second argument that is supposed to be passed as `argv` of the child process.  However this does not always work on Windows because the individual strings are not escaped correctly before passing them to `win_create_process` in `otherlibs/win32unix/createprocess.c`.

The correct escaping rules (which are implemented in this PR) are explained in:

https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

### CODE REVIEW

**Comment by nojb** [comment]
Is it still possible to consider this for inclusion in 4.05 ?

**Comment by xavierleroy** [comment]
Please don't rush.  First, show us an example of wrong quoting.  Second, tell us what is different in your code from the Win32 implementation of Filename.quote.  Thank you.

**Comment by nojb** [comment]
Wise words.  Indeed:

1) `Filename.quote` implements the same quoting algorithm.
2) The argument to `create_process` have been correctly quoted for over 10 years (judging by git history).
3) We had a bad local modification that indeed caused bad quoting but I missed that and got thrown off track.

Sorry for the waste of time!

**Comment by dra27** [comment]
You got in before I reviewed more closely, thanks :)

The tests look good, though - we could repurpose that commit or I can cherry-pick?

**Comment by nojb** [comment]
Feel free to cherry pick the one commit, it should work.

**Comment by fdopen** [comment]
I think you are correct in at least one point: The current code doesn't quote parameters with `'\t'`:
https://github.com/ocaml/ocaml/blob/46676cde6eede81aefc964830b5a65349c581dc2/otherlibs/win32unix/unix.ml#L846

`\n` and `\011` don't seem to need special quoting, see: http://www.daviddeley.com/autohotkey/parameters/parameters.htm and http://www.daviddeley.com/autohotkey/parameters/msvcrtparsing.htm

**Pull request closed without merging**
