### PR TITLE
Allow finalizers on custom blocks in the minor heap, fix pr 3612

### PR DESCRIPTION
**Pull request by chambart**
This subsume the pull request https://github.com/ocaml/ocaml/pull/82

Note that this also make functions like Bigarray.Array1.sub a lot faster:

```
  for i = 0 to n do
    ignore(Array1.sub a 3 5)
  done
```

Is more than twice faster.

### CODE REVIEW

**Comment by gasche** [comment]
The patch should be merge-ready, but on my machine many backtrace-related tests fail because of it. Can you reproduce the failures?

```
List of failed tests:
    tests/backtrace/backtrace.ml
    tests/backtrace/backtrace.ml
    tests/backtrace/backtrace.ml
    tests/backtrace/backtrace2.ml
    tests/backtrace/raw_backtrace.ml
    tests/backtrace/backtrace_deprecated.ml
    tests/backtrace/backtrace_slots.ml
```

**Comment by gasche** [comment]
PS: I have pushed the rebased version of this patch (moving headers to the `caml/` namespace, plus a Changelog entry, two in fact) to a private branch [PR#92-rebased](https://github.com/gasche/ocaml/tree/PR%2392-rebased). See [comparison with trunk](https://github.com/ocaml/ocaml/compare/trunk...gasche:PR%2392-rebased).

**Comment by xavierleroy** [comment]
I reviewed the rebased version and I'm (more than ever) OK for merging.

**Comment by gasche** [comment]
So the backtrace problem seems to be due to a bug in byterun/backtrace.c, I'll fix it before merging this one.

**Comment by gasche** [comment]
Merged in trunk. Thanks for the good work!

Congratulations for fixing the oldest fixed issue in the release cycle for now. The next contender, PR#4539, is 3 years older.

**Comment by DemiMarie** [comment]
@bobot I think that the breakage is a bug in lablgtk.

**Pull request closed without merging**
