### PR TITLE
Remove force-instrumented-runtime configure option

### PR DESCRIPTION
**Pull request by abbysmal**
This PR is a follow up to #11655 where I was reminded of the existence of the `--enable-force-instrumented-runtime` configure option.

The idea behind this feature was to simplify the workflow with Sandmark, in order to have a simple compiler build that would always build programs with the instrumented runtime.

However this is not necessary anymore, as Eventring allows us to extra meaningful data without having to link-in the instrumented runtime.

I think we can remove this option safely, since it was always meant to be a development option for Multicore developers.

Maybe we can check in with the people working on Sandmark to see if they need this option at all anymore? (not sure who to cc?)

Also paging in @OlivierNicole , since he was using this option recently.

### CODE REVIEW

**Comment by dra27** [comment]
I've put this in the 5.0 milestone, just because if we do merge then it might be worth merging to 5.0 as otherwise 5.0 would be the only release with it.

(I'm neutral on its removal!)

**Comment by shindere** [comment]
Since the logic for choosing one variant of the runtime as the default
runtime is already in place, one other possibility, rather than
removing it, would be to generalise it so that it becomes possible
to select any variant of the runtime to become the default one.

For instance something like

```
./configure DEFAULT_RUNTIME_VARIANT=i
```

So, not passing the variable to configure would mean choose the "normal"
runtime as the default one and passing it would promote the selected
variant as the default runtime.

The option sugested above can be implemented with `AC_ARG_VAR` in
`configure.ac`, there are already examples showing how to use the macro.

Thoughts?

**Comment by OlivierNicole** [comment]
I think this could be useful in some situations. For ThreadSanitizer support we had to implement this functionality. We don’t know if we will keep using it in the future, but this illustrates that such needs can arise.

**Comment by abbysmal** [comment]
After discussing it with @dra27 and reading the comments here, we seem to all agree that a more generalized option would be welcome.
However before we agree on a good interface (for TSAN or instrumented runtime usages), it would be nice to at least have the removal of this non-released option merged into 5.0 and trunk.
We can then resume conversations about a generalized, default linked runtine, configure option in a seperate issue.
Does this sound good?

**Comment by dra27** [comment]
Agreed, yes! @Octachron - is this OK to be applied to 5.0, given that we're in beta? (see https://github.com/ocaml/ocaml/pull/11660#issuecomment-1289034310)

For the generalised feature, we already have the `OCAMLPARAM` variable, and `OCAMLPARAM=runtime-variant=i,_` should have the same effect as this configure option used to be. For Sandmark, etc. having to set that via an environment variable is potentially brittle, but we also have `$LIBDIR/ocaml_compiler_internal_params` and adding `* : runtime-variant=i` to that also has as similar effect. As far as I know, there is no way at present of using `ocaml_compiler_internal_params` to set _defaults_ (i.e. adding that setting _unconditionally_ selects the instrumented runtime) so I wonder if the generalised feature should rather be an update to this mechanism to allow specify _defaults_, rather than necessarily having to thread more of these things via `configure` to the `Config` module. There's a (relative) usability benefit here, because it's somewhat easier to edit that configuration file or set an environment variable than it is to feed non-standard options to `configure` when opam's involved.

**Review by gasche — APPROVED** [review]
Honestly it is a bit weird at to remove a feature that is simple and natural, has and will have a variety of potential use-cases -- it is not Multicore-specific in any way, anyone that needs the instrumented runtime now or in the future could benefit from it. I don't understand why @Engil and @dra27 care about getting it removed now, but they have thought about this harder than I have so I'm willing to play along. The patch is correct, so here is an approval.

**Comment by dra27** [comment]
What's your opinion, @Octachron? (both in general, and in terms of 5.0)

**Comment by Octachron** [comment]
Since this is a configuration flag with a very limited visibility, it is okay to remove it during the beta. At the same time, it would also be fine to keep it as a compiler developer only option.

For the sake of configuration simplicity, I agree that it might be better to remove it temporarily in order to take the time to design a generally useful option before exposing it.

**Comment by gadmm** [comment]
> `./configure DEFAULT_RUNTIME_VARIANT=i`

This would have been useful to me at some point (but replacing `i` with `d`), and it would have been simpler than the alternatives suggested in this discussion.

**Pull request merged**
