### PR TITLE
Add new optional checks to the CI

### PR DESCRIPTION
**Pull request by samoht**
Shell fragments for the additional checks were provided by @gasche

### CODE REVIEW

**Comment by samoht** [comment]
@gasche let me know what you think, it should do what you want.

**Comment by gasche** [comment]
This is very good, thanks a lot! I wonder how the new optional tests will look like in the github UI, but I guess I'll know when they're merged.

I have one big-picture question: where should I write some message to explain what the test does, how to fix a failure, and when it's ok to fail? I assume external contributors will be surprised when this test failure; can we show a specific message in case of failure? I guess one way to do this is to just add a big `echo` at the beginning of the script with an explanation, which is what I'll do.

Then in full-nitpick mode: I think that the name `CheckTests` is unfortunate, because to the reader of the script it really looks like this is running the testsuite. Could you rename the targets as `BuildAndTest`, `CheckChangesModified`, `CheckTestsuiteModified`?

**Comment by samoht** [comment]
If you click on the green cross, you'll be redirect to Travis CI which the result of the 3 runs. The cross is green because all the required tests (currently only one) are green.

And yes, just add comment in the script. I'll rename the functions.

**Comment by samoht** [comment]
done

**Comment by gasche** [comment]
Ok, I had not understood that the travis script was being executed in this pull request itself.

This let me realize one frustrating thing: the failed tests do not show in the "Show all checks" list on github. They show up (they fail in the case of this PR, so it's an interesting test!) if you click on "Show all checks", and then "Details". I would have expected a better UI: a less-green notification with "All mandatory checks have passed (some optional tests failed)", and then a "Show all checks" button that would show the three tests, the passing testsuite one and the two new (failing) ones.

As a result, these two tests are virtually invisible to the contributors. The only people that will check their results are those that know they exist, and this kind of defeats the purpose of the checks, as they are trivial to check manually by looking at the list of changed files. I would like contributors that _do not_ know about the need to update Changes or improve the testsuite to be warned/alerted by those failures.

The github UI seems to suggest that it should be possible to have several tests listed in the "Show all checks" list. Would you by chance have any idea how to get those tests there?

(Worst comes to worst, we can make those checks mandatory and see what happens. I'm a bit frustrated at the idea that some contributors would then see "checks failed" while their PR is perfectly reasonable, but I think doing this is better that accepting the PR as-is or not changing anything.)

**Comment by samoht** [comment]
I agree that the UI is not ideal. It should be possible to add more crosses using the Github API, but I don't have time to investigate further. The good thing with the current set-up is that:
- it's fast (as it uses Travis'CI container infrastructure) even if not related to the tests :-)
- and it's easy to extend, test other platform, etc. Also you have the list of tests in one place instead of checking manually that you didn't forgot anything.

**Comment by Drup** [comment]
@gasche The multiple checks in the github UI are for different hooks, see the list in settings/hooks. As far as github is concerned, "travis" is only one hook.

**Comment by gasche** [comment]
@Drup : thanks for information.

I added some documentation on the travis tests in 5cdb5a7b4e957de15d8fccc297c062f6860e1543 . I would like to try making the two new tests mandatory for a while, and see how people react. I will probably experiment with that soon.

**Comment by xavierleroy** [comment]
@gasche : don't get carried away :-)  Many pull requests don't come with tests, and for good reasons.  For example, algorithmic improvements in the typechecker ( #294 ), in the compiler ( #313 ), or in the standard library ( #304 ); wording of error messages; code documentation ( #310 ); or configuration stuff ( #308 ).  You don't reasonably test specifically for any of this.

**Comment by gasche** [comment]
Well #304 _does_ come with a testsuite, and I think that firmly asking people that do algorithmic improvements in parts of the stdlib that is not covered by tests to improve this coverage is actually a very good idea -- fortunately we didn't even have to ask in this case.

I hear your not-quite-convinced-ness and may try to collect better statistics: in the Nth last PRs, how many time did we have to ask for Changes or testsuite? How many times would we have to justify the absence of Changes or testsuite? If the former happens sensibly more often than the latter, then marking those checks as (virtually) mandatory is still a better default.

In particular, I think the Changes test could rather safely be made mandatory. There are some rare corner cases where not changing Changes is the right thing to do (this is a very minor fix (no need for crediting) of previous stuff that is not visible to end-users), but in general it comes from an external contributor, or a maintainer felt the need for public exposure, it's almost always a good idea to have something in Changes.

(Making a test mandatory simply means that user see a red button instead of a green button in their PR. Common sense prevails and we can still merge PRs that fail one of those test, and in fact we regularly do because the existing test tries to install OCaml software that is occasionally broken for reasons independent of the PR.)

> You don't reasonably test specifically for any of this.

For config-only or documentation-only changes, we could support a textual tag (for example `[nochange]`, for "no observable change in behaviour") to use in commit messages. I would automatically pass my TestsuiteModified check if all commits in the PR have [nochange], but it would also be useful for other things. For example, when bisecting to find the cause of a regression, we can skip all [nochange] comments.

Such a tag should not be used for algorithmic improvements, because they can be the cause of bugs and you want to bisect them. But that suggests that asking people that improve the algorithms to also improve the testsuite may not be such a bad idea in general.

**Pull request merged**
