### PR TITLE
Fix regressions in Unix.sleep

### PR DESCRIPTION
**Pull request by hannesm**
see report at http://caml.inria.fr/mantis/view.php?id=7257

### CODE REVIEW

**Comment by gasche** [comment]
I'm tempted to merge this. @damiendoligez, any opinion?

**Comment by hannesm** [comment]
should be merged into trunk as well

**Comment by damiendoligez** [comment]
I reviewed the patch, it's good to merge.

**Comment by gasche** [comment]
I merged this in trunk -- in trunk only, as I understand that no 4.03 bugfix release is planned. Thanks for the excellent report and patches!

@damiendoligez , it might be time to give some information on the upcoming release calendar (as you did in advance of the 4.03 release; but maybe with less unreasonable feature hints, please!:).

**Pull request closed without merging**
