### PR TITLE
`do .. done`: report "unclosed" error if `done` is missing

### PR DESCRIPTION
**Pull request by nojb**
- Allow `do done` (equivalent to `do () done`)
- Allow "shortcut" attributes, extensions: `do%foo ... done`, `do[@foo] ... done`.
- Give "unclosed" error when `done` is missing.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Do we write so many busy waiting loops
```
for i = 1 to n do () done
```
that we need a special syntax to save three keystrokes?  :-)

**Comment by alainfrisch** [comment]
> Do we write so many busy waiting loops
> 
> ```
> for i = 1 to n do () done
> ```
> 
> that we need a special syntax to save three keystrokes? :-)

I often write `while (...) do () done` (as a way to do `do-while` or similar loops). (I'm not claiming I cannot live with the `()`.)

**Comment by nojb** [comment]
No problem taking the `do done` sugar out of the PR, but do we agree that there is no reason to reject the other two tweaks?

**Comment by xavierleroy** [comment]
I'm not looking for reasons to reject, just for reasons to accept. 

The "unclosed" error explanation is nice to have.  

Attributes and  extensions on `do`, I'll let someone more competent than me say.  

`do done` as a shortcut for `do () done` doesn't seem very useful to me, even for `while` where it makes more sense than for `for`.  There's something to be said in favor of regularity in the syntax.  Plus, all Algol-like languages have explicit empty statements (`skip` in IMP, a lone `;` in C), and `()` works reasonably well as OCaml's explicit empty statement.

**Comment by gasche** [comment]
What is the meaning of `do[@foo] e done` or `do%foo e done`? If I understand the parsing rule correctly, this is considered as equivalent to `do e[@foo] done` or `do [%foo e] done`, which I find a bit confusing. Are we sure that this is the right behavior, is there a precedent for this? Ohter uses of `ext_attributes` I could easily find apply to the first keyword of the construct (here `for`, `while` where they are already supported), not inside.

(I guess I'm not convinced by the "attributes" part of this PR either.)

**Comment by nojb** [comment]
> Are we sure that this is the right behavior, is there a precedent for this?

It is similar to what we do for `begin%foo e end` and `begin[@foo] e end`: https://github.com/ocaml/ocaml/blob/85a3d4d4e22a5fc8a5b6e080b3ce5ed3ffa87ec5/parsing/parser.mly#L2369-L2370

**Comment by nojb** [comment]
I updated this PR with only the "unclosed" error, which should be uncontroversial :)

**Review by gasche — APPROVED** [review]
Clearly a nice improvement. Thanks!

**Pull request merged**
