### PR TITLE
Turn C warnings into errors on AppVeyor

### PR DESCRIPTION
**Pull request by dra27**
Bring the AppVeyor testing more into parity with Travis (which has -Werror)

### CODE REVIEW

**Comment by dra27** [comment]
More commits to follow - I just need AppVeyor to test each step

**Comment by dra27** [comment]
OK, hopefully once the CI catches up, this should be ready to go. The primary goal of this PR is to enable `-Werror` (or `-WX` for MSVC) for our CI builds, just as Travis does.

This instantly catches a very long-standing bug in the declarations of two functions in win32graph/draw.c (I think that these two will have worked by fluke since the parameters are all OCaml `int`s and extremely unlikely to be 32+ bit values)

During my testing for Visual Studio 2017, I noticed that otherlibs/win32unix/channels.c does not correctly load _get_osf_handle for MSVC64 (this is also true for VS2015) and this is resulting in an incorrect cast (which I think could cause problems if the underlying HANDLE being returned is more than 32-bits wide). However, owing to a bug in Visual Studio 2010, this is not caught by AppVeyor.

My solution has been to switch AppVeyor to use Visual Studio 2015 but this has two potentially serious consequences:
 1. FlexDLL cannot be installed solely from a binary release (because binary releases of FlexDLL don't *yet* support Visual Studio 2015/2017 - though Alain and I may do something about this later in the year)
 2. Visual Studio 2015 is C99 where Visual Studio 2010 is C89 (with various extras arising from supporting more recent C++ standards) - this change would mean that we'd stop catching people scandalously declaring variables where they want them rather than strictly at the start of blocks, etc... more seriously, that could be a darned nuisance for people still developing using Windows 7 SDKs. That said, maybe it's just something we check and update around release time instead.

I think that these two consequences can be lived with, for the sake of catching real bugs - can this be be for 4.04/4.05/trunk please, @damiendoligez?

**Comment by gasche** [comment]
> That said, maybe it's just something we check and update around release time instead.

Err, downvote, I wouldn't want to have to go back at C files deep into the runtime to think about reordering variable declarations at release time.

I'm not saying that is the good long-term solution, but asking the naive question anyway: would it be possible for AppVeyor to test with *both* compilers?

**Comment by dra27** [comment]
Fair enough! I could test with both, yes. I'd suggest:

- MSVC64 with VS2015 - full testsuite (correct default catching of /Wp64)
- MSVC32 with VS2010 - but only world and asmrun as I think that tests all not-testsuite C files
- mingw32 in full, as we currently do

**Comment by damiendoligez** [comment]
The Inria CI is using an old SDK[1] anyway so we'll probably catch such things way before release time.

[1] Microsoft Windows SDK v7.0 and `cl` version 15.00.30729.01

**Comment by dra27** [comment]
True - though I do see Gabriel's point that it would be irritating to be catching these things well after the PR - hopefully the build I've just pushed will actually work!

**Comment by dra27** [comment]
Right, that seems to be working and just doing world+runtimeopt+native systhreads stubs has only added a couple of minutes to the AppVeyor build, rather than the weight of a full build and test.

This is good to go, I think - I have a 4.04 branch version as well which can follow shortly.

**Comment by dra27** [comment]
This has been merged into 4.04 - I shall wait for the CI to come back on this rebase and then merge this one and rebase to trunk.

**Pull request merged**
