### PR TITLE
Reduce size of bootstrap compilers by stripping debug info

### PR DESCRIPTION
**Pull request by xavierleroy**
Recently, we added "-g" to the build of the OCaml compilers, to make them easier to debug.  This has the unfortunate effect of increasing their sizes: ocamlc goes from 2 Mbytes to 10 Mbytes.  It's OK for the newly compiled compilers (those that will be installed), but a little too much for the bootstrap compilers (those in boot/, which are under version control and part of the .tgz source distribution).

This pull request proposes to strip the debug information from the bootstrap compilers.  This way, the new compilers can still be debugged, but the bootstrap compilers revert to their sizes before the "-g" change.

The stripping is done during bootstrap, when copying the new ocamlc, ocamllex and ocamldep to boot/.  The new "stripdebug" tool performs this task.

As a consequence, comparing the new compilers with the boot/ compilers at the end of bootstrap is more complicated, since the debug section must be ignored.  A new tool, "cmpbyt" in tools/, performs this comparison.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Yes, it strips everything up to the beginning of the bytecode executable proper (= the beginning of the first section of the bytecode executable).

**Comment by xavierleroy** [comment]
Ping?  In the absence of negative opinions, I'll merge this by the end of the week.

**Comment by damiendoligez** [comment]
1. Out of curiosity, why did you have to change the perl script?
2. Could `stripdebug` be useful to the general public? And installed with the other tools? If so, you should rename it to `ocamlstrip` and probably provide an option to keep the header.

Maybe do (2) as a follow-up to this PR.

**Comment by xavierleroy** [comment]
1- To silence a perl warning.  (Apparently, "do" for function calls went out of fashion in the 1990's.)

2- The idea crossed my mind, but I couldn't find much of a general use for the tool, so let's keep it private for the moment.

**Comment by lefessan** [comment]
For the general public, "ocamlclean" would be a better choice, as it strips debug, but also removes dead code. I have been using it for a while, with great results (program stripped from 400k without debug to 16k...)

**Comment by lefessan** [comment]
Actually, it makes me think we could use it too, just before releasing a new version to have the smallest boot/ possible.

**Pull request merged**
