### PR TITLE
ocamldep: .ml in earlier include dirs should shadow .mli in later include dir

### PR DESCRIPTION
**Pull request by nojb**
This PR addresses the following problem of `ocamldep` discovered while working on #2218.

Suppose that you have the following files:
```
- a.ml
- dir1/b.ml
- dir2/b.ml
- dir2/b.mli
```
and `a.ml` mentions `B` inside it. If you use `ocamldep` to compute dependencies:
```
ocamldep -I dir1 -I dir2 a.ml
```
you will get
```
a.cmo : dir2/b.cmi
a.cmx : dir2/b.cmx
```
Rather, one would expect to get dependencies in `dir1` since that directory is passed first.

The reason for this behaviour is that `ocamldep` looks for `.mli` files *first* and only if that fails it looks for `.ml` files. Instead, this PR proposes to look for both `.mli` and `.ml` files at the same time.

The diff is really small modulo indentation; I suggest to read it ignoring whitespace.

### CODE REVIEW

**Comment by gasche** [comment]
(Is it possible to have a test for this?)

**Comment by nojb** [comment]
Yes, should be possible. I will give it a try.

**Comment by nojb** [comment]
Added a test.

**Comment by Octachron** [comment]
This seems to be a simpler way to resolve module conflicts in ocamldep. Did you check on the opam repository that no one relies on the current mli-first arbitrage?

**Comment by nojb** [comment]
No, I didn't and am not sure how to do it. How could I go about it?

**Comment by Octachron** [comment]
A good first-order approximation might be to check that this PR does not break any opam packages. Otherwise, it might be interesting to detect situation where the current and new conflict resolutions leads to a different module resolution?

**Comment by nojb** [comment]
> A good first-order approximation might be to check that this PR does not break any opam packages. 

I am not super familiar with `opam`; do you know of a script or instructions somewhere explaining how one can build "all" packages?

**Comment by Octachron** [comment]
I am not sure which tool is the more adapted here. Maybe [opamcheck](https://github.com/janestreet/opamcheck)?

**Comment by ghost** [comment]
Note that both `dune` and `ocamlbuild` are using `ocamldep -modules`, which I believe is not affected by this PR. So the vast majority of opam packages shouldn't be affected by this PR.

**Comment by nojb** [comment]
Good point.  Plus, I think it is rather unusual to have multiple modules with the same name in usual OCaml projects. So I'm not sure it is worth going through the trouble of setting up some `opam`-wide testing.

**Comment by damiendoligez** [comment]
What is the algorithm used by the compiler itself? Whatever it is, `ocamldep` should try to match it. Installing and using `opamcheck` is rather involved, so I don't think it's warranted for this PR.

**Comment by damiendoligez** [comment]
BTW the proper link for opamcheck is https://github.com/damiendoligez/opamcheck, the JS version of the project is stale.

**Comment by Octachron** [comment]
The compiler uses the first matching cmi and cm(x)o in the list of included directories. The current choice of ocamldep is thus respected by the compiler only until the point where the first directory cm{i,x} files are built (and there are potential failing states where non-matching cmi and cmo files are selected).

**Review by Octachron — APPROVED** [review]
The code itself looks good to me, and the new inferred dependency should lead to more stable build for the few people concerned.

**Comment by nojb** [comment]
> The code itself looks good to me, and the new inferred dependency should lead to more stable build for the few people concerned.

Thanks for the approval!

I rebased the PR and will merge it based on @Octachron's approval unless someone shouts.

**Pull request merged**
