### PR TITLE
Phantom let support in Clambda

### PR DESCRIPTION
**Pull request by mshinwell**
This patch enables the Clambda language to represent "phantom let" expressions.  These have no dynamic semantics but are used for the emission of debugging information.  Typically, when a value is optimised out by Flambda, a phantom let binding will be left behind to ultimately enable visibility of such value in the debugger.  Fairly complicated values can be represented in this way thanks to the DWARF constructs involving "implicit pointers", which enable heap-allocated structures to be reconstituted in the memory space of the debugger at runtime, even though they have been optimised out from the code running on the target.

@chambart or @lthls , perhaps one of you could look at this.

### CODE REVIEW

**Comment by mshinwell** [comment]
I should add: future patches will deal with the setting of `Clflags.debug_full` and also the generation of those "phantom defining expression" cases that currently may appear to be unused.

**Review by lthls — APPROVED** [review]
I have reviewed this pull request. It introduces a bit of infrastructure for generating more precise debugging information, and doesn't otherwise affect normal code generation.

A small question for @mshinwell: I believe that the phantom lets introduced in un_anf (when the new debug_full flag is enabled) bind mostly variables that were created in the middle-end. Is it relevant to generate debugging information for such variables ? I expect later pull requests to refine the generation of these phantom constructions anyway, but maybe it would already make sense to restrict the phantom let generation to variables with an actual provenance.

**Comment by mshinwell** [comment]
I'm going to have to think about your question some more, but I'm not sure that needs to delay the merge.  We're going to have to refine the behaviour here anyway as we see how things pan out in practice.  I'm suspecting that we might end up with phantom lets with provenance that depend on phantom lets without provenance---in which case we need to be careful what we delete.

**Review by damiendoligez — APPROVED** [review]
Approved based on @lthls's review.

**Pull request merged**
