### PR TITLE
Fix bug in Scanf.format_from_string when argument contains character that need escaping

### PR DESCRIPTION
**Pull request by nojb**
See [MPR#7799](https://caml.inria.fr/mantis/view.php?id=7799).

Fix consists in replacing the (incorrect) implementation of string escaping in `Scanf.string_to_String` by `String.escaped`.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Thanks!

**Comment by nojb** [comment]
Should we get this into 4.07 ?

**Comment by gasche** [comment]
Yes if you do the work of cherry-picking and moving the Changes entry to the right place on both sides. But personally I don't think this is worth the trouble -- this function is obscure anyway.

**Comment by nojb** [comment]
OK, let's leave it in `trunk` only then.

**Pull request merged**
