### PR TITLE
Remove the NATIVECCPROFOPTS build variable

### PR DESCRIPTION
**Pull request by shindere**
This variable is actually always empty

### CODE REVIEW

**Review by damiendoligez — APPROVED** [review]
Looks good, but @xavierleroy should have the opportunity to comment before we merge.

**Comment by xavierleroy** [comment]
This variable is clearly not useful, so OK for removal.  I have no idea what purpose it served or was supposed to serve.

**Comment by shindere** [comment]
Merged, thanks.

**Comment by yakobowski** [comment]
commit 58357910577dffc3fb5448dc84cfc278b595560e
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Mon Mar 11 10:12:43 2002 +0000

    Workaround gcc 2.96 bug (RH 7.2, Mandrake 8.[01])


Should bring back some sweet memories :smile:

**Pull request merged**
