### PR TITLE
Simplify Makefile

### PR DESCRIPTION
**Pull request by nojb**
Working on the build system, spotted this "gem"... For the life of me I cannot figure out what it is supposed to do (maybe left over from pre-autoconf days). In any case, it looks like it can be removed.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Maybe you could have asked the original author privately first?

**Comment by nojb** [comment]
> Maybe you could have asked the original author privately first?

Indeed! I did now, and I will report back if I hear back.

Nonetheless, note that this is effectively dead code, since the `configure` script never produces a value of `unix` for the `SYSTEM` variable:
https://github.com/ocaml/ocaml/blob/82f77b8ebd5e96ccbe8aa6d25382c35acb766e41/configure.ac#L928-L1007

**Comment by nojb** [comment]
From the author:

> This code handles string escaping in the makefiles.  Its purpose
is to ensure that OCaml builds correctly even if the installation
directory has unusual characters in its name.  However, it is broken:
> 
> - It fails to additionally escape BINDIR for ocamlmkconfig.ml.
> 
> - Due to two missing characters, I do not believe it could have
  ever worked.  If it had been executed, it would have set BINDIR to
  the literal string “BINDIR”, which is obviously wrong.
> 
> - It doesn’t consider macOS to be a Unix-like system, even though
  some versions are certified UNIX!
> 
> Feel free to delete it.

Additionally, as mentioned above, the code is not currently exercised as `$(SYSTEM)` is never `unix`.

**Comment by dra27** [comment]
Rather than simplifying, is it possible that we should instead fix it - the concept of the issue is still present, I think? AppVeyor installs to `C:\projects\🐫реализация-…` precisely to exercise this kind of thing.

**Comment by nojb** [comment]
> Rather than simplifying, is it possible that we should instead fix it - the concept of the issue is still present, I think? AppVeyor installs to `C:\projects\🐫реализация-…` precisely to exercise this kind of thing.

Sure, why not? It is not my cup of tea, though, so in that case, I would lean towards closing this PR or passing the relay to some other interested party...

**Comment by gasche** [comment]
I would be in favor of merging the present patch, because it simplifies the code noticeably. If we want more escaping, it could be done between the configure and the makefiles, instead of being done a-posteriori by redefining makefile variables in a way that relies on delayed substitution for their users.

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
( I would like to merge once @dra27 confirms that it works for him as well. )

**Comment by dra27** [comment]
Agreed - looking at the history, `configure` never wrote `SYSTEM=unix` even when #587 was merged, so I don't think that code's ever done anything.

**Comment by dra27** [comment]
One thing, because I'm not sure - does changing the `=` to `:=` affect overriding `DESTDIR`?

**Comment by nojb** [comment]
> One thing, because I'm not sure - does changing the `=` to `:=` affect overriding `DESTDIR`?

As far as I understand, this would only be the case if `DESTDIR` where to be set after the invocation of `make` (eg inside a `Makefile`). This is not the case today and it seems a dubious thing to do anyway.

**Comment by dra27** [comment]
That's my conclusion too - let's merge...

**Comment by nojb** [comment]
Thanks!

**Pull request merged**
