### PR TITLE
OCaml 5.00.0 rather than 5.0.0

### PR DESCRIPTION
**Pull request by dra27**
FlexDLL's build system assumes that the minor version number is formatted `%02d` (as it was for OCaml 4.00.0). This PR is as much for "discussion" as to whether it's 5.0.0 or 5.00.0 as anything else.

The main benefit for now is that it restores AppVeyor without needing a rapid release of FlexDLL...

The dev date also didn't get reset which I guess was an oversight?

### CODE REVIEW

**Comment by smorimoto** [comment]
Actually, many software, not just FlexDLL, expect the single-digit minor version of OCaml compiler version to start with 0. (`5.00.0`, `5.01.0`, `5.02.0`, etc...) Unless there is a special reason, I think it would be better to introduce this change in order not to break the ecosystem.

**Comment by Octachron** [comment]
@dra27: this change of version number has already been discussed, hasn't it?

With the switch to a full debian order for version number, there is little reason to keep a `%d.%02.%d` scheme; except for backward compatibility reason. If the backward compatibility issue is real, we certainly should revert to our previous numbering scheme. However, I don't know if there is many softwares that require the OCaml minor version number to be zero-padded to length 2.

We cannot really afford to have the Appveyor CI broken now, thus it seems fine to revert the version number temporarily, while waiting for FlexDll to fix its build system. However,  an early release version with a fixed build system would still be needed, since if we alter our version numbering, it is better to evaluate the consequences as soon as possible (to catch faulty version parser in our CI cone of dependency for instance).

(For the dev date, it was updated, but it seems that my subconscious erased one Cæsar from the calendar)

**Comment by xavierleroy** [comment]
> this change of version number has already been discussed, hasn't it?

Well, I can't remember any really compelling reason for the change, and now we have one reason against, so...

**Comment by Octachron** [comment]
Let's merge first and fix the CI, and eventually discuss later.

**Comment by shindere** [comment]
Update: a discussion took place which concluded that the transition to
version 5 ocf OCaml is a good time
to make our versionning scheme more standard.


This is implemented in #11049.

**Pull request merged**
