### PR TITLE
Add Float.pi

### PR DESCRIPTION
**Pull request by Chris00**
Fixes https://caml.inria.fr/mantis/view.php?id=4170

### CODE REVIEW

**Review by damiendoligez — APPROVED** [review]
I checked the value against http://piday.org/million and https://en.wikipedia.org/wiki/Pi, it's very probably the right one.

**Comment by nojb** [comment]
@Chris00 If you can add Damiel Doligez as a reviewer in the `Changes` file, we can merge this.

**Comment by Chris00** [comment]
Done.

**Comment by nojb** [comment]
Thanks!

**Pull request merged**
