### PR TITLE
rename create_domain into domain_create

### PR DESCRIPTION
**Pull request by gasche**
Before this commit we had `create_domain` and `domain_terminate`, and the inconsistency was annoying. We could have renamed `domain_terminate` into `terminate_domain` instead, but I chose to keep `domain` as a prefix to be consistent with the external functions of the module, `caml_domain_spawn` etc.

### CODE REVIEW

**Comment by gasche** [comment]
Note: my personal preference was for `create_domain` and `terminate_domain` instead, they read better. I chose the `domain_*` form for better consistency with the other functions in domain.c.

**Comment by gasche** [comment]
(cc @Engil)

**Review by damiendoligez — APPROVED** [review]
Looks good and I agree that inconsistent naming is annoying.

**Comment by gasche** [comment]
Great! Merged and cherry-picked in 5.0 as aadde5e2ea16c79f35dac068e04e0c911bd9e6f4.

**Pull request merged**
