### PR TITLE
Emacs: more versatile specification of locations of .annot files

### PR DESCRIPTION
**Pull request by Chris00**
Emacs: more versatile specification of locations of .annot files

### CODE REVIEW

**Comment by Chris00** [comment]
The failure seems to be unrelated to my changes.

**Comment by planar** [comment]
Shouldn't the `caml-types-annot-dir` take precedence over the `project-dir`? If I take the trouble of setting it up file by file, I wouldn't expect it to be overridden by the build system.

**Comment by Chris00** [comment]
That's sensible, will do that.

**Comment by Chris00** [comment]
Anything more I can do to help this patch be merged?

**Comment by planar** [comment]
Merged in 4.02 (commit 15872). Thanks for the patch.

**Pull request closed without merging**
