### PR TITLE
Force linking required globals

### PR DESCRIPTION
**Pull request by trefis**
While testing 4.03 at janestreet we noticed that sometimes the units linked in an executable were different depending on which compiler middle-end is used.

The first commit adds such an example to the test suite. The expected behavior, which is the one of 4.02 and 4.03 without flambda, is for `Submodule` to be linked in the executable and `linked` to be printed on stdout. With flambda, this doesn't happen.
From what I understand, the explanation is basically: flambda sees that the include is unused, drops it, and then since the unit/global `Submodule` is not mentioned anymore, it is not linked.

There is already some code in the compiler (in bytecomp/translmod.ml) to force some "required globals" to be linked, at the moment it works as follow:

> for every "required global" (that set of globals is computed by the typechecker, and we will assume it is correct):
> - if it is already mentioned in the lambda code for the module, there is nothing to do; the unit will be linked
> - if it is not already mentioned, add a reference to it at the beginning of the lambda code; which forces the unit to be linked

As we saw in the example, with flambda it is not always enough anymore that the global be mentioned for the unit to be linked.
Similarly, simply adding a reference to it at the beginning will not suffice, flambda will notice it is unused and drop it.
What we want to do is to add, in all cases, a reference that flambda will not drop (we do this by using the `opaque` primitive).

### CODE REVIEW

**Comment by mshinwell** [comment]
I think this is OK.

**Comment by trefis** [comment]
Note about the implementation: I'm adding an `flambda` parameter to `wrap_globals` instead of simply using `Config.flambda` because with the later the behavior of the bytecode compiler is different depending on whether you enabled flambda at configure time or not, which seemed wrong.

@damiendoligez I'm considering this to be a bugfix and as such made the PR against 4.03. Does that make sense to you?

**Comment by damiendoligez** [comment]
@trefis Makes sense. Can we have a second review?

**Comment by lpw25** [comment]
I've reviewed it and think it is fine to merge.

**Pull request merged**
