### PR TITLE
Testsuite fixes

### PR DESCRIPTION
**Pull request by dra27**
Predominantly cosmetic or minor fixes to the test-suite affecting our favourite Redmond OS.

### CODE REVIEW

**Comment by dra27** [comment]
This has all been tested with/without flambda on Ubuntu 14.04 and Windows 7 Pro msvc, msvc64, mingw, mingw64 - i.e. 10 builds.

**Comment by dra27** [comment]
23c0ac4 has not received the same level of testing as the others, but it seems fine on the quick mingw with/without flambda I just ran.

**Comment by alainfrisch** [comment]
About fa244ddaea2aa258fc8f4e38ac0768affd2f31c5 : the fix seems a bit heavy.  Perhaps one could simply drop the attribute (if inlining is broken, the test would probably fails anyway because the code would start allocating) for now.

Apart from that, everything looks good to me, although I'm not sure this is worth merging in 4.04 rather than trunk.

**Comment by dra27** [comment]
For fa244dd, is that definitely the case (I don't know - I just don't want to break a test inadvertently).

**Comment by dra27** [comment]
It would be better, given that this is only the testsuite, for it to be correct in the release version - it's a useful reference point (as in 4.03.0) and also moving forwards useful for any systems which want to run testsuites as part of building (OPAM is moving in that direction, I believe).

**Comment by alainfrisch** [comment]
@chambart Can you confirm that dropping the attribute is ok (inline will still happen and if it ever doesn't anymore, this will be detected because of boxing)?

**Comment by alainfrisch** [comment]
@damiendoligez Are you comfortable with touching the testsuite in 4.04 so close from the release date?

**Comment by dra27** [comment]
Sorry - for 4.05, I'll try to do all this earlier in the process... it's not been a great time of year (for me) for the release cycle!

**Comment by damiendoligez** [comment]
@alainfrisch I am quite comfortable with touching the test suite at any point in the release process because I don't see it as a critical part of the system. Moreover, when it's broken CI tells us very quickly.
@chambart can you have a look at https://github.com/ocaml/ocaml/commit/fa244ddaea2aa258fc8f4e38ac0768affd2f31c5 and @alainfrisch's remark [https://github.com/ocaml/ocaml/pull/807#issuecomment-247538535]?

**Comment by damiendoligez** [comment]
@chambart ping?

**Comment by dra27** [comment]
Original commits rebased

**Comment by dra27** [comment]
Those six commits deal with new issues and need reviewing, please.

**Comment by dra27** [comment]
Those five commits deal with newly spotted issues, and need reviewing, please.

**Comment by damiendoligez** [comment]
> Those five commits deal with newly spotted issues, and need reviewing, please.

They're good.

**Comment by dra27** [comment]
4 configurations (vanilla, flambda, safe-string, safe-string+flambda) all tested OK on msvc/msvc64/mingw/mingw64/Ubuntu x64 as well.

**Comment by damiendoligez** [comment]
@dra27 ready for merge?

**Comment by dra27** [comment]
As far as I'm concerned, yes - I thought it was waiting on feedback from @chambart?

**Comment by damiendoligez** [comment]
I've decided we can merge without waiting.

**Pull request merged**
