### PR TITLE
French comment translation

### PR DESCRIPTION
**Pull request by Octachron**
This pull request translates (or deletes in some specific cases) the few remaining french comments in the compiler. I have tried to be as exhaustive as possible and translated all comments that I could detect; in the hope to make the codebase a little more non-french compliant.

The majority of the comments have been translated with the exception of
- An old todo comment from 1997 in "typing/ctype.ml"
- Aged metacomments
- Historical comments in the num library on either function deletion or implementation change between Caml Light and its predecessor.

which have been simply deleted. Note that I would gladly translate the ctype todo if the translation is deemed useful.

To respect the authorship of signed comments, e.g. `(* AAA ... *)`, I have added the translated text in addition to the unaltered original rather than directly replacing it.

( N.B. the translation could definitively be improved/defrenchified )

### CODE REVIEW

**Comment by Drup** [comment]
Nice, but half of those are so useless they would be better removed.

**Comment by xavierleroy** [comment]
Several of those comments are not / no longer useful indeed, but thanks for the translation effort anyway.  No idea why CI fails.  Assuming the CI failure is spurious, OK for merging.

**Comment by Octachron** [comment]
As far as I understand, the CI Failure was a problem with type_conv 0.113.00 and is unrelated to this patch.

**Comment by Octachron** [comment]
I have updated the pull request to solve the merge conflict with the faster test suite commit and corrected some typographical errors.

**Comment by gasche** [comment]
I'm afraid it was too late, I already merged it in trunk. Would you re-send the typographical fixes?

**Comment by Octachron** [comment]
The  typographical fixes are here https://github.com/Octachron/ocaml/tree/french_translation_typo.
Please tell me, if you would prefer a separate pull request.

**Comment by gasche** [comment]
Done, thanks.

**Pull request closed without merging**
