### PR TITLE
add colors into error reporting for `[%ocaml.error "oops"]`

### PR DESCRIPTION
**Pull request by c-cube**
Should fix http://caml.inria.fr/mantis/view.php?id=7147

### CODE REVIEW

**Comment by ghost** [comment]
@c-cube that's going to print the `Error:` prefix before the location. `print_error_prefix` should go in `default_error_reporter`.

There is another problem: all errors coming from the compiler have the `Error:` prefix directly included in the `Location.error` value, so it's going to be printed twice. I think we should just stop including the (possibly colored `Error:` prefix) in the error message and let `default_error_reporter` deal with it. That makes more sense especially for errors coming from ppx rewriters, as when the rewriter create the error it doesn't even know where the error is going to be displayed (terminal supporting color or something else)

**Comment by c-cube** [comment]
I removed `errorf_prefixed` (since the prefix is now in the default reporter), and it seems to work on both regular errors and ppx-induced errors. I am not totally sure there is no duplication though, I don't know the error paths well.

Side note: @Drup suggested that hints be colored, too (in blue? cyan?) for better visibility. Opinions?

**Comment by damiendoligez** [comment]
Cyan is invisible on a white background.

**Comment by c-cube** [comment]
Coloring `hint:` can go into another PR anyway, this is more of a bugfix…

**Comment by ghost** [comment]
The patch looks good. I did some grepping and didn't saw other hand-written `Error:` prefix, so there should be no duplication left.

One thing I just realized is that if we don't include the `Error:` prefix directly in the error string, `Format` will break the string at the wrong position when constructing this error string. For instance:

```
(* trunk *)
# let x = 1 + 'e';;
Error: This expression has type char but an expression was expected of type
         int
(* with this patch *)
# let x = 1 + 'e';;
Error: This expression has type char but an expression was expected of type int
```

Ideally the rendering done by `Format` should be done at the very end, when actually printing the error, but that's a big change.

I can think of several workarounds:
1. in the various error-creation functions (`error_of_printer`, `raise_errorf`, ...) we insert a `Format.pp_print_string ppf 7 ""`. Which will shift the formater offset by the length of `Error:`.
2. we keep inserting the prefix directly in the string and we do it as well in `raise_errorf` and co. To deal with externally constructed errors, we always include the color escape sequences in the error string and have the compiler strip them if necessary
3. same as (2), but we don't add colors when constructing the error string. The compiler does it if the string starts with `"Error: "`

I think (3) is the less-surprising and easiest to implement solution

**Comment by c-cube** [comment]
If I understand correctly, the issue is that `Error:` is added after the error message is formatted, right? I would think that 1. is the simplest option, by far (I'd just modify the format strings to start with "@<7>%s" and add "" as argument?), compared to detecting whether a string starts with "Error: ". Currently the escape sequences are inserted by tags, it would not be easy to insert them manually…

**Comment by ghost** [comment]
> If I understand correctly, the issue is that Error: is added after the error message is formatted, right?

Yes

You are right that (1) is the simplest option and should be enough

>  it would not be easy to insert them manually…

I wasn't thinking of inserting them manually, basically you would call `set_color_tag_handling` only for `Format.{std,err}_formatter` and `default_error_reporter` would do:

``` ocaml
if is_prefix msg ~prefix:"Error: " then
  fprintf "@{<error>Error:@} %s" (String.sub msg 7 ...)
```

**Comment by alainfrisch** [comment]
@diml Do you think one could merge this for 4.04 in its current state?  (The testsuite seems to be broken, btw.)

**Comment by ghost** [comment]
We can merge it, but we should implement the option 1 discussed above to avoid changing the layout of error messages which could end up going over the margin. I'm looking at this

**Comment by ghost** [comment]
I finished the patch and merged by hand (9e21876a283a56d976976a8ea905a2200ecbdd1f). I squashed the commits to avoid the intermediate commits that broke the testsuite

**Comment by gasche** [comment]
Could someone comment on why this change is marked as a breaking change in the Changelog? Am I correct in assuming that it is only for people that would have used `Location.errorf_prefixed` through `compiler-libs`? Are there other ways to use this function? Other breakages in the patch?

**Pull request closed without merging**
