### PR TITLE
Various fixes for -dtimings

### PR DESCRIPTION
**Pull request by v-gb**
When I tried to use -dtimings to figure out where the time is spent in the compiler pipeline, I ran into the problem that it gives unreliable results:
1. the "typing" category is completely missing for mli's, resulting in a big gap between the "all" category and the sum of everything else
2. anything that runs subcommands, like -pp, is not measured because Sys.time doesn't count time spent in subprocesses. This means the compiler underestimates its running time by a good amount.
3. the -ppx commands, reading marshalled ast and checking its invariants are not measured (other than in the "all" category)

This pull request fixes these points, and I now get relatively good measurements.

Fixing 1. is straightforward.

For 2., I know of two ways to get the resource usage of subprocesses on linux: getrusage and wait4, and judging from searching around and looking at the python stdlib, neither of them works on windows.
So I added a function similar to Sys.time that includes cpu time of subprocesses if possible, but I don't expose it in Sys, since it's not very portable.

For 3., I redefined the "parsing" category to include everything from "we have a filename" to "we have an ast we can typecheck". I made a subcategory for -ppx as it's probably worth separating out, like -pp.

### CODE REVIEW

**Comment by gasche** [comment]
Is it necessary to bootstrap here, or did you do it out of habit? I thought that #324 had made bootstrapping unnecessary in that scenario.

**Comment by v-gb** [comment]
I bootstrapped because I couldn't build otherwise.
Maybe #324 only solves gets rid of bootstrap for adding primitives to modules that aren't linked in the compiler?

**Comment by gasche** [comment]
I reviewed the code and it looks OK to me. One thing I wondered about is if it wouldn't be nice to separate computation of self-process time and children-time, both in the exposed primitive (we could have two functions instead of one trying to do both) and in the display of results.

(One way to do this that I hadn't thought of when writing my comment is to have hierarchical timer, and add a timer around what we know is the sub-process call. This allows the user to differentiate both without having to do an explicit separation of the two measurements. So maybe this isn't so useful after all.)

**Comment by v-gb** [comment]
Thanks.

I think if we wanted more detailed breakdown, we would create more categories, like -pp is a subcategory of parsing. The split between subprocess or current process is not really how you want to split time, as you could have plugins as subprocesses or as cmxs.

The current interface of dtimings is actually annoying with subcategories because you have to know which categories include what other categories to make sense of it. If people agree, I wouldn't mind changing the code so we print categories as a tree: /, /parsing, /parsing/-pp, /parsing/-ppx, /typing, /generate, generate/clambda, generate/cmm etc instead ol all, parsing, -pp, -ppx, typing, generate, clambda, cmm etc.

**Comment by gasche** [comment]
Yes, I think giving a hierarchical view would be important.

(Another thing I wondered about your PR is whether it's really worth having separate `-pp` and `-ppx` timer, or whether just having the `Preprocessing` timer for both would be fine. I am undecided on it, and would respect the choice you made, but I must say that `Dash_ppx` is a rather ugly constructor name.)

**Comment by v-gb** [comment]
Ok. I think I prefer to change the display as a second pull request, then (it's nice-to-have, but this pull request is necessary to be able to use -dtimings at all).

About -pp and -ppx, I don't feel strongly either way. Iit seems marginally better to separate them, as "parsing" is already essentially -pp + -ppx.
I can make a change to hide lines that would reported as 0.000s, since these lines are essentially noise, so that at least the -ppx line wouldn't show up if you don't use -ppx.

**Comment by mshinwell** [comment]
For the avoidance of doubt this work will be covered by Jane Street's corporate CLA.

**Comment by chambart** [comment]
I do approve the change too. I didn't really care about preprocessing when I added that so I
didn't even notice the limitation. Thank you for solving that.

If you are willing to spend some more time on that, it would be a great improvement to have
hierarchical timers. When I try to optimize some part of the compiler I usually add some finer
grain timers that I don't commit to avoid adding too much noise. I never took the time to
seriously do that.

Lexify [landmark](https://github.com/LexiFi/landmarks) can be a good example.

If you are willing to spend even more time. Recording allocated blocks (Gc.minor_words)
can be quite useful. (I have some implementation somewhere, but I would be ashamed to
show it in the current state...)

This PR is good as it is right now. If you want to go further, this should go in another one.

**Comment by gasche** [comment]
Based on @chambart's review (thanks!) I decided to go ahead and merge.

**Pull request merged**
