### PR TITLE
Make asmgen tests run

### PR DESCRIPTION
**Pull request by Gbury**
This PR makes it so that the asmgen tests (written in Cmm) are run (they are currently only compiled). Not all tests are run (1 was already skipped), because some produce segfaults (specifically: `catch-try.cmm`, `catch-try-float.cmm`, `soli.cmm` on my machine; I'll look into fixing these if this PR is accepted). Assuming all these tests worked when they were written, this shows that the semantic of Cmm changed enough so that some tests broke, which should be a good enough reason to actually run these tests in the testsuite.

`ocamltest` itself only need a tiny bit of patching in order to generate complete paths for programs generated by these tests. cc @shindere

### CODE REVIEW

**Comment by dra27** [comment]
See also the note at the start of #974 and some of the comments in it

**Comment by xavierleroy** [comment]
I still think these asmgen tests hand-written in C-- are not useful (outside of porting to a new instruction set architecture) and not worth the maintenance effort.  I'm considering removing them entirely, so that people don't waste time submitting PRs about them.

**Comment by chambart** [comment]
It covers more than just adding a new ISA. It is a lot easier to track bugs when changing the backend when your input comes from cmm rather that through the whole compiler. Also, writing backend tests in OCaml is quite fragile. A change in an intermediate pass can transform the generated cmm and avoid a tricky point.

It did catch some problems for me, and I was glad there where those tests to experiment with some changes.

**Comment by shindere** [comment]
Sorry for being very late on that one.

Sorry, too, for having promised @Gbury to work on this for a very long
time and not having done so. Thanks a lot for having done it yourself
finally, @Gbury!

Although @xavierleroy seems to not like the idea of keeping these tests
around, it seems at least two people find them useful and worth having
and these persons give arguments I can very well connect with.

I did not review the cmm tests themselves but am generally speaking in
favour of this PR being merged.

I do not however understand the change to ocamltest. Why exactly do you
need to make the program path absolute, @GBury? As far as I know it will be
executed from the test directory any way and I'd rather avoid absolute
paths as much as possible because they are more fragile and OS
dependent.

**Comment by Gbury** [comment]
Without the patch I have the following error (on tests/asmgen/even-odd for instance):
```
Specified modules: even-odd.cmm
Source modules: even-odd.cmm
Running test asmgen with 3 actions
Running action 1/3 (setup-simple-build-env)
Action 1/3 (setup-simple-build-env) passed
Running action 2/3 (codegen)
Running codegen on even-odd.cmm
Commandline: /home/guigui/build/ocaml/trunk/runtime/ocamlrun /home/guigui/build/ocaml/trunk/testsuite/tools/codegen -S even-odd.cmm
  Redirecting stdout to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/compiler-output 
  Redirecting stderr to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/compiler-output 
Action 2/3 (codegen) passed
Running action 3/3 (cc)
Running C compiler to build even-odd.out
Commandline: gcc -O2 -fno-strict-aliasing -fwrapv -Wall -Werror -fno-tree-vrp -ffunction-sections -I/home/guigui/build/ocaml/trunk/runtime -o even-odd.out -DINT_INT -DFUN=is_even main.c even-odd.s /home/guigui/build/ocaml/trunk/testsuite/tools/asmgen_amd64.o
  Redirecting stdout to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/compiler-output 
  Redirecting stderr to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/compiler-output 
Action 3/3 (cc) passed
Running test run with 1 actions
Running action 1/1 (run)
Commandline: even-odd.out 5
  Redirecting stdout to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/even-odd.output 
  Redirecting stderr to /home/guigui/build/ocaml/trunk/testsuite/tests/asmgen//_ocamltest/tests/asmgen/even-odd/even-odd.output 
run_unix.c:227: Cannot execute even-odd.out: No such file or directory
Action 1/1 (run) failed (Running program even-odd.out with arguments 5: command
even-odd.out 5
failed with exit code 1)
```

In bash, since the executable to run is local (and the local ocamltest directory is not in the PATH), you would need to use a path to run the executable, so either a relative path using `./`, such as `./even-odd.out`, or an absolute path, and it seems that is the problem here (although the ocamltest code actually running the command is in C so I can't really tell what it does, ^^).

**Comment by shindere** [comment]
The program is not run by bash but directly by a C function (fork/exec).

I didn't check the code but it might be the case that there is a
directory change missing somewhere. I really think making program names
absolute is not the right way to go. Just let me know if you can't
figure that out and I'll investigate.

**Comment by Gbury** [comment]
Ah, so the problem is that the C code is using `execvp`, which according to man:

```
duplicate the actions of the shell in searching for an executable file
if  the  specified  filename does not contain a slash (/) character. 
The file is sought in the colon-separated list of directory pathnames
specified in the PATH environment variable.
```

Which basically make it behave a bit like bash: since there is no `/` in the name of the executable, it is searched in the `PATH`, which fails for obvious reasons.

**Comment by shindere** [comment]
Well, can you see what's different from other tests where things work
without absolute names?

**Comment by Gbury** [comment]
In other tests the name of the executable always contain a slash `/`, as far as I can tell, because it is in another directory (either `native` of `byte` if I remember correctly): the problem is precisely that ocamltest is in exactly the same directory as the executable.

**Comment by shindere** [comment]
Guillaume Bury (2020/02/18 09:36 -0800):
> In other tests the name of the executable always contain a slash `/`,
> as far as I can tell, because it is in another directory (either
> `native` of `byte` if I remember correctly): the problem is precisely
> that ocamltest is in exactly the same directory as the executable.

You are correct that the program names are absolute in other tests, too.

Now I remember that I made this decision not because of the run stage
since this stage is done from the test's current directory so "./" would
have been enough. Actually, the motivation behind using absolute paths
in the other contexts was that some binaries are compared (to make sure
e.g. ocamlopt and ocamlopt.opt produce dientical programs) and the
programs are in different directories.

Coming back to the present PR, and although it would make the code not
so consistent with the other set-ups of program, perhaps you could
simplify the code a bit and just use "./"? That would result in slightly
simpler logs, well unless youprefer to keep the absolute paths, I don't
feel that strong about it.

Should the command runner use execv rather than execvp, actually?

**Comment by shindere** [comment]
It would also be good to see why the CI fail. I'm sorry I can't help a
lot with that, the interfaces of Travis and AppVeyor are of really low
quality from an accessibility perspective.

**Comment by Gbury** [comment]
So the CI failure is because of floating point computations on 32-bits architectures.
@chambart suggested the fix in the last commit (using a volatile to force gcc to adequately store the fp computation result before comparing).

**Comment by Gbury** [comment]
I switched to using a relative path as suggested.
The CI now only fails on the change check, and I don't think this needs a change entry (as it does not affect users in any way) ?

**Comment by shindere** [comment]
It doesn't, indeed.
I thus added the no-change-entry-needed label.

**Comment by shindere** [comment]
Will you please rebase and cleanup the history?

**Comment by Gbury** [comment]
I rebased and kept 2 commits:
- the first simply make the asmgen tests run + the ocamltest fix (and update the reference files), but does not alter the contents of the tests
- the second commit fixes the arith.cmm test

**Comment by Gbury** [comment]
So the AppVeyor failure is basically a repeat of the travis 32-bit error it seems: looks like the volatile fix does not work for mingw32.

**Comment by Gbury** [comment]
So I ended up skipping the arith.cmm test on windows. Hopefully CI should be green now.

**Comment by shindere** [comment]
Merged, thanks a lot for your work.

**Comment by shindere** [comment]
@GBury: the even-odd-spill-float and even-odd-spill produce bus errors on
BSDs, making our CI fail. My bad, I should have odne a precheck run
before merging. Do you think you can fix this? Or shall we skip these
tests at least on BSD?

**Comment by shindere** [comment]
The tests also fail on MinGW64, actually.

Perhaps we should revert this to aovid noise on trunk, see how best to
fix//skip the failing tests and re-merge once we are happy?

**Comment by Gbury** [comment]
> Perhaps we should revert this to aovid noise on trunk, see how best to
> fix//skip the failing tests and re-merge once we are happy?

That seems like a good option, yes.

**Comment by shindere** [comment]
@Octachron is going to do the revert. I am not confident enough to do it
myself.

**Comment by Octachron** [comment]
I revert the last commit.

**Comment by shindere** [comment]
Thanks a lot @Octachron!

@GBury would you mind opening a new PR based on latest trunk (including
the revert) so that we can test your fix on Inria's CI?

**Pull request merged**
