### PR TITLE
Remove the places where warning 3 was raised in str.

### PR DESCRIPTION
**Pull request by bschommer**
There were a few places where the lowercase/uppercase functions where used.

### CODE REVIEW

**Comment by alainfrisch** [comment]
This changes the semantics of Str.  There could be people relying on its current Latin-1 oriented semantics...

**Comment by bschommer** [comment]
That is right. Maybe one wants to duplicate the function with the ascii and latin-1 version?

**Comment by damiendoligez** [comment]
cc @xavierleroy

**Comment by DemiMarie** [comment]
OCaml really needs UTF-8 versions (which are what people almost always need).  However, Unicode breaks so many assumptions that this would not be backwards-compatible &ndash; in general, the only way to correctly handle Unicode (unless you are doing something simple like escaping ASCII metacharacters) is with a library designed for the purpose.

**Comment by bschommer** [comment]
I updated this PR to include ascii version of the case insensitive regexp matching. There are also some test for the new versions.

**Comment by xavierleroy** [comment]
I'm still unsure what to do about this one.  My inner voice says that we should just silently remove Latin-1 support from the existing functions, not create new "_ascii" functions.  But that's not the direction that was taken in the standard library.  Should I tow the party line?  or join the dissidents?  Still undecided.

**Comment by bschommer** [comment]
The problem with just changing the implementation is that it will probably break existing code. However since it was never documented what uppercase/lowercase functions were used it would not be that problematic.

Alternatively one could just expose the internal function and allow users to pass a `fold_case` and a `fold_string`function to the functions.

**Comment by dra27** [comment]
Sorry if it's been previously discussed, but does a change like this make a case for cutting Str out of the standard distribution? That way conforming to the behaviour becomes tied to the version of the library, rather than OCaml?

**Comment by xavierleroy** [comment]
@dra27: yes, sending dissidents abroad is one way to preserve the party line...

**Comment by dra27** [comment]
:smile: I was thinking it could be made compliant **and** sent abroad!

**Comment by shindere** [comment]
FWIW: as far as I know this is the only place where there are still
warnings while compiling OCaml.

In my opinion, reaching a situation where the compiler compiles without
any warning looks very suitable, because once this point is reached,
every new warning that is introduced becomes even more visible.

So, although I don't have any opinion about how this particular problem
should be solved, I wish it gets solved ASAP.

**Comment by xavierleroy** [comment]
If your problem is just to see no warning, just put the correct [@ocaml.warning] attributes to silence the warning at the points where `Char.lowercase` and `Char.uppercase` are used.  We know they are used, purposefully, and don't need constant reminder.

**Comment by bschommer** [comment]
Removing the warnings with the correct [@ocaml.warning] would be okay. But additionally one maybe wants to document that these functions use the latin-1 versions to avoid confusion.

**Comment by shindere** [comment]
Xavier Leroy (2016/12/05 00:37 -0800):
> If your problem is just to see no warning, just put the correct
> [@ocaml.warning] attributes to silence the warning at the points where
> `Char.lowercase` and `Char.uppercase` are used.  We know they are
> used, purposefully, and don't need constant reminder.

OK if this is an acceptable solution, will submit a PR soon. Thanks.

**Pull request closed without merging**
