### PR TITLE
Use Fun.id in the documentation of StdLabels

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by nojb** [comment]
Hello, thanks for the suggestion. This is kind of subjective, but I find this change gratuitous: there is nothing wrong with the existing code, and the new code does not provide any real improvement either (and it introduces a "dependency" between `StdLabels` and `Fun`). All in all, it doesn't seem worth it. Thanks anyway!

**Comment by gasche** [comment]
My personal rule of the thumb is that `Fun.id` makes sense in terms that are formed of several combinators to describe transformations, for example `Either.map ~left:f ~right:Fun.id`, which goes from `f : ('a -> 'b)` to `('a, 'c) Either.t -> ('b, 'c) Either.t`. (We already have a specialized `map_left` for this, but you get the point of the example.) On the other hand, I avoid it "at the toplevel", when the function I want to describe is the identity (I just write the more readable `(fun i -> i)`; by the way, not sure why `(function i -> i)` is used here in the documentation, it sounds like a minor style mistake). I think that `List.init` is in a grey area where one could see it either ways, and in this case I tend to agree that avoiding functions that have to be known from the reader is the best choice.

**Comment by favonia** [comment]
Thanks! Should we change it to `fun i -> i`, then? I should explain that this PR was inspired by the [new documentation on TMC](https://www.ocaml.org/manual/tail_mod_cons.html), which uses `Fun.id` with `List.init` twice without explanation. I thus got the impression that the documentation of `StdLabels` could use an update. I don't have a strong opinion, and since I have brought this issue to your (the core developers') attention, I believe I have done my part and should leave further discussions to you.

**Comment by gasche** [comment]
Ouch! I wrote the TMC chapter, but I blame @dra27 on this one ( https://github.com/ocaml/ocaml/pull/10740#discussion_r739870880 ).

In the present case I think that `fun i -> i` would certainly be an improvement over `function i -> i`. I only use `function` when there is a real pattern-matching at play.

**Comment by dra27** [comment]
Blame taken - but FWIW I prefer `Fun.id` 🙂 I wholeheartedly agree with only using `function` for pattern matching.

**Pull request closed without merging**
