### PR TITLE
Improve location handling in the middle-end

### PR DESCRIPTION
**Pull request by lpw25**
This PR makes a few improvements to how locations are handled in the middle-end. Some of these are useful precursors to both the spacetime profiler (#585) and the improved debugging (#574). (Note that #585 also needs some fixes to location handling in the backend, which are not included in this PR).

The changes are as follows:
1. Add `Location.t` to the `Lprim` constructor of `Lambda.t`.
2. Add `Location.t` to the `Lambda.lfunction` type.
3. Remove `dinfo_kind` field from `Debuginfo.t` as it was always either meaningless (when the record was not representing a backtrace slot) or redundant (when the record was attached to a call or a raise).
4. Move `debuginfo.ml(i)` from `bytecomp` to `middle_end` since it was not used in the bytecode compiler anymore.
5. Make the representation of `none` in `Debuginfo.t` explicit rather than using a dummy value.
6. Construct `Debuginfo.t`s directly from the attached locations on lambda rather than fetching it out of separate events.
7. Turn off the creation of debug events in native code since they are no longer used for anything.

### CODE REVIEW

**Comment by bobzhang** [comment]
FYI: I had one of my local patch to attach location to `Lprim`, glad you did it

**Comment by alainfrisch** [comment]
> Move debuginfo.ml(i) from bytecomp to middle_end since it was not used in the bytecode compiler anymore.

Since middle_end is for flambda, does the proposal impacts the non-flambda mode?

**Comment by lpw25** [comment]
The changes do impact the non-flambda mode as well. It seems middle_end is the only place to put things used by both flambda and `closure.ml` without including them in the bytecode compiler. Possibly `closure.ml` should go into `middle_end` as well as it is the "middle end" of the non-flambda path.

**Comment by lpw25** [comment]
> It seems middle_end is the only place to put things used by both flambda and closure.ml without including them in the bytecode compiler

Actually it could probably just go in asmcomp. Although I suspect some of the coming debugging changes will end up spliting the uses of this type into multiple related types, so it probably doesn't matter too much where it lives for now.

**Comment by chambart** [comment]
I'll take the review for that PR.

**Comment by mshinwell** [comment]
@chambart : Ping

**Comment by chambart** [comment]
I finished reading this and the code is straightforward and ok.
This is a clear improvement on the Levent based approched.

The locations of raise expressions changed in native code.
The displayed location in backtraces is on the raise expression
and not on the argument of the raise. This is an improvement
I think, but this adds some difference to bytecode. It would
probably be better to update bytecode one accordingly if it does
not take too much effort.

**Comment by chambart** [comment]
If there is some significant change after rebase, I will try to look at it.

**Comment by lpw25** [comment]
I've rebased. It is probably worth another quick look. I agree it would be nice to get bytecode to agree with native code about the position of raises, but it seems to require a bit of work so I'd like to leave it for now.

**Comment by mshinwell** [comment]
@chambart Please could you review the rebase changes?  I'd like to leave the bytecode/native code thing until later if possible.

**Comment by chambart** [comment]
I'm still ok after rebasing.

If nobody objects, I'm merging this today

**Comment by mshinwell** [comment]
Thanks for reviewing it again.  I will merge this---there are some conflicts with the other patch I just pushed, but it's nothing major.

**Comment by mshinwell** [comment]
This has been merged as #666

**Pull request closed without merging**
