### PR TITLE
Allow recursive bindings with "_"

### PR DESCRIPTION
**Pull request by OlivierNicole**
## Description of the problem from the Compiler hacking wiki:

Currently, you cannot use _ in recursive bindings:

``` ocaml
let rec _ = () and x = 3;;
Characters 8-9:
  let rec _ = () and x = 3;;
          ^
Error: Only variables are allowed as left-hand side of `let rec'
```

This is because patterns aren't allowed there, only variables. Really _ should be considered a variable in this context.
## What has been done

Just like with let bindings, _ is now allowed as a variable name in let rec bindings. As with let bindings, this construction is translated into a sequence.

A test has also been added to the test suite to make sure that _ bindings work and can produce effects. Evaluation order is not tested as it may be changed by flambda.

### CODE REVIEW

**Comment by alainfrisch** [comment]
> Currently, you cannot use _ in recursive bindings

True, but why is this a problem?    In which case would it be useful to do so?

**Comment by lpw25** [comment]
> True, but why is this a problem?

It's not so much a problem as a mildly annoying inconsistency. I think we should aim for a situation where `_` can be used in place of any binding occurrence of a variable.

**Comment by alainfrisch** [comment]
Then one should also allow:

``` ocaml
let _ x y = x + y
```

which is even worse since it produces a non-informative "Syntax error".

**Comment by lpw25** [comment]
> Then one should also allow:

Indeed. Although I assume we can merge this PR and leave that fix to a separate one.

**Comment by yallop** [comment]
Something's not quite right.  Perhaps the case where there are no named bindings needs special treatment.

```
$ cat rec.ml
let rec _ = () = ()
$ ocamlc -o rec rec.ml
$ ./rec
Fatal error: exception Out_of_memory
```

**Comment by bobzhang** [comment]
This created more confusion. a simple underscore is mostly used as a place holder. why would people write such code 

``` ocaml
let rec _ = () = ()
```

**Comment by xavierleroy** [comment]
Eight months later, any new opinions?  Mine is that more consistency doesn't always translate into better usability.  The examples of new uses of underscore shown here are confusing and best left as syntax errors.

**Comment by OlivierNicole** [comment]
I don't have a particular opinion on this. I worked on this PR as an exercise and because it was listed in https://github.com/ocamllabs/compiler-hacking/wiki/Things-to-work-on, but I haven't encountered a case where using `_` in recursive bindings would have been useful, so I perfectly understand if it's not merged.

**Comment by mshinwell** [comment]
@lpw25 I think you need to argue for inclusion of this one, if you want to.

**Comment by lpw25** [comment]
Well, I'm very much in favour of improving the consistency of things like this. I think that inconsistency causes unnecessary surprises and confusion for users. So I'm in favour of merging, but I'm hardly going to kick up a fuss if people are dead set against it.

As for the patch itself, I suspect it could be simplified by just creating a fresh ident in `transl_let` for the `_` case rather than treating it specially.

**Comment by bobzhang** [comment]
I think the added test case should never pass a code review, if it is not useful, it is better to prevent it as early as we can

**Comment by yallop** [comment]
@bobzhang: that's a good argument for having a warning, but it's not a reason to reject the code altogether.

In fact, a more general warning that code is unnecessarily recursive (perhaps by extending the meaning of warning 39) would be useful.  For example, it would be convenient if the compiler could point out that this code:

```ocaml
let rec f x = if x <> 0 then (print x; f (pred x))
    and g x = f x
```

could be rewritten like this:

```ocaml
let rec f x = if x <> 0 then (print x; f (pred x))
let g x = f x
```

Warning about a `_` binding in a `let rec` would then be a special case

**Comment by bobzhang** [comment]
This is a change to the language without clear benefit except it cost more cpu power and add more complexity to the compiler.
In my opinion, OCaml is a practical language, the added benefit -- more consistency -- does not justify its inclusion.

**Comment by damiendoligez** [comment]
We discussed this at the developer meeting two days ago and the consensus is in agreement with @bobzhang.

**Pull request closed without merging**
