### PR TITLE
Remove the Makefile.nt files

### PR DESCRIPTION
**Pull request by shindere**
@dra27

### CODE REVIEW

**Review by nojb — APPROVED** [review]
Please also remove the mention of `Makefile.nt` from `HACKING.adoc`.

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2018/05/24 13:08 -0700):
> nojb approved this pull request.

Thanks!

> Please also remove the mention of `Makefile.nt` from `HACKING.adoc`.

Oops! I intended to do it but then this change somehow got lost, many
thanks for your care!

**Comment by shindere** [comment]
Merged

**Comment by dra27** [comment]
Hooray! (Sorry for not replying yesterday - I was on the road!)

**Comment by shindere** [comment]
David Allsopp (2018/05/25 03:11 -0700):
> Hooray! (Sorry for not replying yesterday - I was on the road!)

Oh cool! Initially I read "Horror" and was aobut to propose to revert
the change.

Thanks, @dra27 !

**Pull request merged**
