### PR TITLE
Fixes for out-of-range Ialloc

### PR DESCRIPTION
**Pull request by mshinwell**
This should fix the underlying problem in #1250.  When a closure is larger than the maximum permitted size for a minor heap value it is now allocated on the major heap instead.

I couldn't see any other places in `Cmmgen` that might suffer from a similar problem.  I added an assertion in `Selectgen` for good measure.  This patch also marginally improves debug info for closures.

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by mshinwell** [comment]
Hmm, the test case takes far too long under Flambda by the look of it.  I'll reduce the number of functions (it's also a bit slow when not using Flambda as well).

**Comment by xavierleroy** [comment]
I was afraid of long compilation times for this test, indeed.

**Comment by xavierleroy** [comment]
I'll record my thoughts here although they should probably go elsewhere.

Some of the current code emitters start to emit syntactically incorrect assembly code for Ialloc past a certain allocation size, which is:
* amd64: 2^31 bytes
* arm: no limit
* arm64: 2^12
* i386: no limit
* power: 2^15
* s390x: 2^19

With `Max_young_wosize` = 256 as of today, none of those limits can be reached, so no action (of the kind considered in #1250) is necessary on the code emitters.

This said, this value of `Max_young_wosize` is quite low compared with the default minor heap size of 262144 words.  We could increase it, in which case the arm64 port is the one that needs fixing along the lines of #1250.

**Comment by mshinwell** [comment]
@xavierleroy Perhaps you could merge this, the tests have passed ok now.

**Comment by xavierleroy** [comment]
Merged!  And cherry-picked on the 4.05 branch (commit 664f076).

**Pull request merged**
