### PR TITLE
Fix Pervasives.LargeFiles functions under Windows

### PR DESCRIPTION
**Pull request by alainfrisch**
io.c uses lseek, but under Windows, one must use _lseeki64 to
have 64-bit offsets.  Before this commit, calling e.g.
LargeFile.in_channel_length on large file would result in an
exception being raised ("System error: Invalid argument").

Notes:

 - There are occurrences of lseek in startup.c, but they use
   long offsets anyway (which means 32-bit under Windows).

 - Unix.LargeFile is not affected (it uses SetFilePointer).

One should probably add some tests, but one might not want to spend
time creating large files. @dra27 mentions:

> it looks like you can use fsutil to create sparse files on NTFS, which might mean we could add tests for these?

### CODE REVIEW

**Comment by alainfrisch** [comment]
I believe we should integrate this bug fix, even without a proper automated non-regression test.  Of course, I tested it manually.  (And we are using it in production at LexiFi.)

@nojb @dra27 : would one of you have time to review the PR?

@damiendoligez : do you think this should go to 4.07?

**Review by nojb — APPROVED** [review]
LGTM.

Just FTR, this is another bug that would have been caught with reasonable compiler warnings activated (we were passing a variable of type `file_offset` which is 64-bit wide under Windows to the 32-bit `lseek`).

**Comment by alainfrisch** [comment]
Ok, it's probably too later for 4.07.  Merged to trunk only.

**Comment by damiendoligez** [comment]
@alainfrisch It's still time to cherry-pick to 4.07 if you feel strongly about it.
(but you'll have to fix the Changes file in both branches)

**Comment by alainfrisch** [comment]
Thanks.  The bug has been there forever under Windows and nobody noticed, so I think the fix can wait for the next release.

**Pull request merged**
