### PR TITLE
Fix mpr7620

### PR DESCRIPTION
**Pull request by garrigue**
Call `Typecore.force_delayed_checks` before printing the signature for `ocamlc -i`

Cf [MPR#7620](https://caml.inria.fr/mantis/view.php?id=7620).

### CODE REVIEW

**Comment by alainfrisch** [comment]
Cf the comment a bit below:

> It is important to run these checks after the inclusion test above, so that value declarations which are not used internally but exported so that value declarations which are not used internally but exported are not reported as being unused.

I think that running the checks without checking inclusion with the .mli signature would result in false positives.

**Comment by alainfrisch** [comment]
Sorry, I did not see your comments on Mantis.  But this PR currently does nothing to disable the unused warnings in case of -i, right?

But if we consider that `ocamlc -i` is supposed to run the full type-checker and report all warnings as the compiler would normally do, why no perform the inclusion check as well?

**Comment by garrigue** [comment]
I checked, but it seems that these warnings are not enabled by default (am I wrong?), so there was nothing to do.

Sometimes one calls `-i` to generate a new interface, so coercing with the old one would be self-defeating.

**Comment by alainfrisch** [comment]
> I checked, but it seems that these warnings are not enabled by default (am I wrong?), so there was nothing to do.

But they could be enabled explicitly.  I don't know why people would do that, but it seems better to explicitly disable the warnings (or just not register the corresponding delayed checks).

Anyway, this is rather minor, and the current patch is already better than the status quo, so I think this can go in 4.06.

**Review by alainfrisch — APPROVED** [review]
LGTM.  As said, it would be better to protect against the unused warnings in case they are explicitly enabled, but this is rather minor.

**Comment by alainfrisch** [comment]
Cf https://caml.inria.fr/mantis/view.php?id=7656

**Pull request merged**
