### PR TITLE
ocaml tool to extract opcode information

### PR DESCRIPTION
**Pull request by ghost**
This tiny `ocamllex` script replaces ["the unholy combination of sed and awk"](https://github.com/ocaml/ocaml/pull/307#issuecomment-162002012) that extracts opcode names & numbers from `instruct.h`.

### CODE REVIEW

**Comment by nojebar** [comment]
The Travis failure seems unrelated...

**Comment by nojb** [comment]
Bonus fix for `tests/typing-missing-cmi`.

**Comment by gasche** [comment]
cc @xavierleroy and @alainfrisch (for the Makefile.nt part at least)

(If by chance Alain already reviewed the PR, you should feel free to indicate it explicitly, not unlike the "Acknowledged by: ..." that matter in the Linux community.)

I looked at the patch and it looks fine. One thing that temporarily alerted me is that there is a loss of flexibility: the sed script greps the name of the C `enum` and use `let names_of_\1` in the generated code, while the new tool hardcodes the `instructions` name. This seems fine as the script was only ever called on `instruct.h` which has only one enum always called `instructions`; besides, it would be easy to change the ocamllex program back to the old behavior by having `find_enum` return a pair of the enum name and opcode names.

(Also, I wondered about the copyright header.)

**Comment by nojb** [comment]
Thanks @gasche for the comments - I amended the patch as suggested.  What is the issue about the copyright header? How should I amend it?

**Comment by ghost** [comment]
Thanks @gasche for the comments - I amended the patch as suggested. What is the issue about the copyright header? How should I amend it?

**Comment by alainfrisch** [comment]
1996 -> 2016?

**Comment by damiendoligez** [comment]
The patch looks good. IIRC the sed script flexibility was inherited from Caml Light, where `instruct.h` contains two `enum` declarations: one for regular opcodes and one for float operations.

**Comment by ghost** [comment]
Ping; since this is not being planned for inclusion in the near future, I am closing this PR and re-opening later in order to resolve some GH account issues.

**Comment by gasche** [comment]
(I had forgotten about this PR and would be fine with merging it in trunk.)

**Comment by nojb** [comment]
Cool, I will re-submit it shortly.

**Pull request closed without merging**
