### PR TITLE
more docstring tests

### PR DESCRIPTION
**Pull request by trefis**
As asked by @lpw25 .

### CODE REVIEW

**Review by lpw25 — APPROVED** [review]

**Comment by trefis** [comment]
Note: I'm a bit sad that warning 50 is not enabled on that file. I tried turning it on but the warnings appear on my terminal, not in the expect output...

**Comment by xavierleroy** [comment]
This one was reviewed and approved one year ago.  Is there any reason it wasn't merged?

**Comment by gasche** [comment]
I restarted the whole Travis CI (we can't trust positive results from a year ago), this should be good to merge if the CI passes.

**Comment by trefis** [comment]
@gasche: I admire your enthusiasm, but have you looked at the diff of this PR?

**Comment by gasche** [comment]
I did, but you never know. (We made changes to ocamltest, end-of-line handling and what not, in the meantine, and to error messages, etc.)

**Pull request merged**
