### PR TITLE
OCaml Inline Assembly

### PR DESCRIPTION
**Pull request by vbrankov**
## Summary

This feature allows embedding assembler instructions within OCaml.  It works and feels like inline assembly in GCC and supports almost everything that GCC supports.  The main goal is to let OCaml use what modern CPUs have, like vectors, hardware FP or cache control, or be able to hand tune performance sensitive code.  The feature grew out of my interest on how to introduce new native primitives.  I tried to keep the compiler changes as small as possible.  It's tested for amd64 and I wrote some [use cases](https://github.com/vbrankov/ocaml-demos/tree/master/intrin) to illustrate its usefulness:
## Goals

Modern CPUs introduce hundreds of new instructions.  For example, vectors alone use well over a hundred dedicated instructions.  A substantial compiler patch is required currently to introduce a single native primitive.  The slowness by which new instructions have been trickling into the language might be an illustration of the difficulties.  Introducing a support for new CPU instructions using inline assembly is much simpler, see for example [binomial_pricer.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/binomial_pricer.ml).  Such adaptability can make OCaml lag much less behind the developments in the CPU world or make it be used in new roles.  Here's [an overview of the intrinsics used in the Intel C compiler](https://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-712779D8-D085-4464-9662-B630681F16F1.htm).

Embedded inline assembly also allows hand tuning performance sensitive code, since it avoids the OCaml to C cross which is too slow for some uses.  The compiler is fully aware of the structure of the assembly code and can perform additional optimizations, for instance pull arguments directly from the memory, commute operands or avoid boxing.  OCaml is arguably increasingly being used in places where speed is important and this may help.

Furthermore, the design of the compiler might get simpler, since introducing native primitives does not require adding to the compiler.  Many recent additions to the compiler could arguably have been smaller or avoided, for example "%caml_string_get/set" or "sqrt".
## How to use it?

In most cases, a single line is required to create a native primitive, for example ([float_round.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/float_round.ml)):

``` ocaml
external floor : float -> float
  = "%asm" "floor_stub" "roundsd        $1, %0, %1      # floor" "mx" "=x"
```

The syntax and the feature set for the largest part closely follows GCC's inline assembly.  GCC was used because its support for inline assembly is mature.  Here's a [good tutorial for GCC's inline asm](http://locklessinc.com/articles/gcc_asm/).  The unit test [comprehensive.ml](https://github.com/vbrankov/ocaml/blob/intrin/testsuite/tests/inline-asm/amd64/comprehensive.ml) shows many of the examples from the tutorial implemented in OCaml.

I'm currently working on a proper manual.
## The design

I tried to keep the patch minimal.  In most cases the code is not changed, only new functions are added or a single "match" branch, so the current code should not be affected.  A test suite is provided as well.  The changes grouped by topic are:
- The description of inline assembly primitives and parsing the OCaml code (typing/inline_asm.ml, typedecl.ml).
- The main handling of inline assembly is in selectgen.ml.  It chooses the cheapest alternative, selects the argument source (register, memory or immediate), assigns registers and inserts register moves.
- Handles boxing/unboxing (asmcomp/cmmgen.ml).
- A support was created for 128 and 256 bit integer and float vector types (asmcomp/cmm.ml, cmmgen.ml, printcmm.ml, selectgen.ml).
- The stack size was increased for functions that use 128 or 256-bit vectors.  Note: There is clearly a better solution, to increase the size of only slots that contain vector values, not all slots, however, I for now chose this approach to keep the patch simpler (asmcomp/reg.ml, amd64/emit.mlp).
- the support for handling the vector registers (emit.mlp, x86_ast.mli, x86_gas.ml, x86_masm.ml).
- Unit tests (testsuite/tests/inline-asm).
## Platform dependent code

The architecture amd64 is well supported and tested.  I created a framework and some support for the other architectures but it's not tested.  Only small parts of the patch are architecture specific so finishing the support should be doable.

To write inline assembly for multiple platforms, a separate implementation must be provided for each platform.  Since inline assembly primitives are indistinguishable from the standard OCaml to C externals, some platforms can have assembly calls, some C calls, and some can have OCaml code.  This is the approach taken in many low level C libraries, such as glibc.

Code for different generations of CPUs can be specialized similarily, by having a superset for each new generation.  For example, `Float.SSE2` can implement `floor` using a C call, while `Float.SSE4.1` can implement `floor` using a hardware primitive.  This is very similar to what GCC does with the switches like -msse4.1 and is actually more general because it allows the code for different generations to exist within the same compiled executable.

For the byte code, an inline assembly primitive needs to have a C call provided.
## Examples and benchmarks

Benchmarks on Xeon E5-2687W
- [float_min.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/float_min.ml) - fast float minimum using a hardware primitive, 4.8x speedup
- [float_round.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/float_round.ml) - fast float `floor` and `ceil` using hardware primitives, 16.2x speedup
- [three_operand.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/three_operand.ml) - faster float addition and multiplication using AVX hardware primitives, 1.74x speedup
- [string_index.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/string_index.ml) - fast `String.index` using hardware primitives, 1.07-9.42x speedup
- [fast_complex.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/fast_complex.ml) - fast complex number operations using hardware primitives, 6x speedup
- [binomial_pricer.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/binomial_pricer.ml) - fast mathematical operations using hardware vector operations, 3.7x speedup
- [packed_type.ml](https://github.com/vbrankov/ocaml-demos/blob/master/intrin/packed_type.ml) - packed data records using inline assembly fields.  Among other uses, this is necessary for the interface with HDF5.

### CODE REVIEW

**Comment by vbrankov** [comment]
bobot, let me address some of your questions.

1\. I thought about not extending the external feature but using a call to a function, like GCC does.  Ocaml differs to GCC in that it has to know the types of the arguments in order to box/unbox.  Any way we correspondingly extend the syntax it becomes equivalent to the "external" syntax.  For example:

```ocaml
let a = 5. in
let b = 6. in
let c = asm "addsd %1, %2" (float -> float -> float) ("x", "x", "=x") a b in ...
```

The "external" syntax is already established in the language, compiler and with the users, so minimal effort is necessary to extend it.  That's why I chose this path, but it's possible to implement inline assembly as a function call if the community finds it preferable.

2-4. I admit that __cpuid's implementation is not great so I fixed it.

5\. Calls are currently doable by passing a function reference, but no "goto" is possible since not even OCaml supports it.

```ocaml
let add () = Printf.printf "test\n"

external call : (unit -> unit) -> unit = "%asm" "" "call        *(%0)" "D" "="

let () =
  call add
```

6\. I've included speedups in the description above.

**Comment by vbrankov** [comment]
bobot,

7\. regarding zarith, this implementation is between 2-3x faster when the numbers are small.  This is apples to apples comparison, although the assembly can be optimized further.

```ocaml
external add_asm : Z.t -> Z.t -> Z.t = "%asm" "ml_z_add"
       "test    $1, %dil
        jz      add%=
        test    $1, %sil
        jz      add%=
        lea     -1(%rdi), %rax
        add     %rsi, %rax
        jo      add%=
        jmp     end%=
add%=:
        movq    ml_z_add@GOTPCREL(%rip), %rax
        call    caml_c_call@PLT
end%=:"
  "D" "S" "=a" "cc" "memory" "%rdi" "%rsi" "%rax" "%rbx" "%rcx" "%rdx" "%r8" "%r9" "%r10"
  "%r11" "%r12" "%r13" "%xmm0" "%xmm1" "%xmm2" "%xmm3" "%xmm4" "%xmm5" "%xmm6" "%xmm7"
  "%xmm8" "%xmm9" "%xmm10" "%xmm11" "%xmm12" "%xmm13" "%xmm14" "%xmm15"
```

**Comment by chambart** [comment]
There is effectively a need in the OCaml compiler for a simpler and
lighter way to handle new instructions.

To explain to anybody who didn't try to add new intructions to the
compiler how tedious it is. For adding a (simple to handle)
instruction, we need to:
* Declare the instruction in the backend/arch.ml
* Add a C version for unhandled architectures
* Add it emision in backend/emit.mlp
* Declare what registers are used, returned, clobered
* Handle it in CSE
* Handle spilling/reloading
* Probably other things I forgot

And in many cases there are additionnal complexity to handle boxing/tagging

A lot of this is basically declaring informations about the instruction,
but this is done as code. This would gain a lot of simplicity by having
a structured format for declaring them. Of course some instructions would
still need special handling, but I think we cover the majority of simd like
instructions with only basic cases.

This proposition has some kind of format for that, but I'm not certain this is
really the kind we want. I would be more in favor of having something declared
in the compiler, with an enforced need for an OCaml or C equivalent.

By the way, I'm don't think I'd like users to have acces to it, in particular since
problems with register allocation and CSE are the kind of exceptionnaly
hard to debug when you don't know where to looking for.

Also something that could make this kind of declaration a lot simpler would
be not have to take care of boxing at all. If the compiler knows about unboxed
float/int/whatever simd types, you could constrain every declared instruction
to work only on unboxed types which would directly correspond to the registers
used. Doing that correctly also requires that unboxed types cannot be passed
to unaware functions: those types must be of another kind to avoid unification
with type variables. (I have some patch doing that somewhere if you want to try).

**Comment by lpw25** [comment]
> By the way, I'm don't think I'd like users to have acces to it, in particular since
problems with register allocation and CSE are the kind of exceptionnaly
hard to debug when you don't know where to looking for.

Without commenting on the specifics of this proposal, I don't think there is too much harm in providing access to this kind of thing to users. It is not like bugs in C bindings are easy to debug either, but we let people write those. These are very much "use at your own risk" features. The benefits can also be quite large, as it releases the development team from trying to keep up with all the intrinsics people want (which hasn't even really happened in the past).

**Comment by samoht** [comment]
What's happen when you try to run your program (or use a library that someone else wrote) using inline assembly on a different platform?

**Comment by vbrankov** [comment]
@samoht The behavior is the same as any other `external` calls.  I suppose by different platform you mean different architecture, for instance amd64 and arm64.  It's obviously not possible to link to a native code library compiled on a different architecture regardless of whether inline assembly is used or not.  For byte code, Inline assembly needs a C call and behaves like any other `external` call.

**Comment by vbrankov** [comment]
@chambart let me address some of your points.  The patch consists of:
1. The user interface built in the code parser which specifies how a user declares a new instruction.
2. The OCaml data structure which describes custom instructions ([inline_asm.mli](https://github.com/vbrankov/ocaml/blob/intrin/typing/inline_asm.mli)).
3. The changes to the each layer of the OCaml code generator which make custom instructions be handled (asmcomp/*.ml).

2 and 3 are the largest and the most complicated parts of the patch.  Any other implementation of a simpler way to handle new instructions would roughly have to go the same way there.  I believe that's good news, since the code handling user's interface is both small and easy to change.

The current implementation follows GCC's syntax letter for letter so that GCC's tutorial produces the same assembly code.  GCC, Intel and Microsoft all share this syntax.  If this syntax happens not to be used as a model for OCaml, there is a value in examining it because it can point to problems and solutions which might not be visible without the experience built into it.  An example are the register alternatives and disparagement.  I'm willing to hear other proposals for the user interface.

%

Just in the case it was misunderstood, the current proposal enforces the need for a C equivalent and I believe handles boxing the way you described.  Handling boxing and avoiding it when possible is a necessity for producing the fastest possible machine code for vector types.

%

Preventing users' access to inline assembly would prevent some in my opinion useful features: the ability to hand tune performance sensitive code and custom usage.  For example, packed types are currently impossible in OCaml and that prevents OCaml from fully using HDF5.

**Comment by xavierleroy** [comment]
Concerning the Zarith example, I don't see how a proper frame descriptor is put on the "call caml_c_call@PLT" instruction.  Without such a descriptor the GC will crash.

**Comment by vbrankov** [comment]
Xavier, thank you for pointing at the frame descriptors, I'm surprised by how difficult it turned out to be.  Here's an attempt at solving it, although I'm not entirely happy with it and I haven't convinced myself it's correct.

The solution was to extended the syntax of the assembly template to introduce recording frame pointers.  There is nothing similar in GCC so the extension is incompatible with GCC, which I'm not happy about.  An alternative is to parse the assembly for "call", but that is unreliable.  The format string "%f" records the frame pointer.  I managed to reproduce GCC not crashing after this change.

```ocaml
add%=:
        movq    ml_z_add@GOTPCREL(%rip), %rax
        call    caml_c_call@PLT
%f
end%=:"
```

**Comment by vbrankov** [comment]
I tried to remove the call from the asm part, but no solution was as fast and simple.  After all, calls from assembly to OCaml should be expected and since this solution was a small change, I'd be happy if we could keep it in some form.

**Comment by vbrankov** [comment]
- Francois, regarding your comments about multiple output arguments breaking OCaml semantics, the same problem exists in OCaml to C bindings.  Multiple output arguments are especially bad because their very essence breaks the language semantics and it's tricky to use, as you demonstrated.  I carried the feature just to be in line with GCC and I won't be sad if it is removed.  It can be avoided, for example ```imul``` returns two values in ```rax:rdx```:

```ocaml
external mul128 : int -> int -> int = "%asm" ""
       "sar     $1, %1  # mul128
        xorq    $1, %0
        imul    %0
        xorq    $1, %0
        xorq    $1, %2" "%rm" "a" "=a"
external register_d : unit -> int = "%asm" ""
       "sal     %1      # register_d
        xorq    $1, %1" "" "=d"

let mul128 a b r =
  let a = mul128 a b in
  r := register_d ();
  a
```

- Regarding your proposed syntax, I don't feel strongly about any syntax and I'd accept whatever the majority likes.  The current syntax was easy to implement because it reuses the current code and I guess the users are somewhat familiar with it.  I should also point out that some features in your proposed syntax may not be trivial to implement, for example type inference and avoiding creating closures.

**Comment by lpw25** [comment]
> Why do you choose to extend the external feature, you are not really defining a function (multiple output). Why not put the inlined assembly in expressions using perhaps an extension point (but they are perhaps not meant for use in the compiler)?

I think that the extending the external feature seems a pretty good place to put this kind of feature. It avoids any issues around type inference by ensuring that a type annotation is given, and it is already the standard syntax for FFI in OCaml. It is certainly better than using a fake function call syntax.

As for the issue of multiple output, plenty of OCaml functions have multiple output:
```ocaml
let two_ones () = (1, 1)
let x,y = two_ones ()
```
Sure, the output is boxed by default, but when `two_ones` is inlined this code should not actually box the result. Since the whole point of inline assembly is to inline it, treating multiple outputs as a tuples which are not boxed unless absolutely necessary seems like a sensible approach.

**Comment by planar** [comment]
I also prefer the `external` syntax, it looks more natural to me.

For multiple outputs, here's an idea: is there a way to connect them with the "unboxed reference" optimization? This is the closest we have to C-style variables.

**Comment by lpw25** [comment]
> The format6 story (string -> GADT) make me think that we should not use string for specifying the assembly code interface (input, output, effect) but instead precise algebraic datatypes.

`format` still uses a string as it's input, the GADT is how the information is represented not how it is parsed. The change in `format` was about parsing the input string into a GADT at compile-time rather than interpreting the unparsed string directly at run-time.

The question here is not about whether to parse the input or not, but about what form that input should take, whether it should be GCC-style specification syntax or something that resembles OCaml's syntax for run-time data. The interface is a compile-time description, not run-time data within the program, so there is no particular reason that its syntax should match the syntax of program data. If anything, the continued existence of format strings demonstrates people's preference for a domain-specific syntax over writing algebraic datatypes explicitly (which people can do by writing the format GADTs by hand).

**Comment by lpw25** [comment]
> The interface is a compile-time description, not run-time data within the program, so there is no particular reason that its syntax should match the syntax of program data. 

Note that if OCaml had a macro system, then the interface could be compile-time data -- capable of being processed by macros. Then this would not simply be a matter of syntax, but a choice of data representation, in which case algebraic datatypes are obviously preferable to strings.

**Comment by vbrankov** [comment]
@planar I find multiple outputs exceptionally hard to do for many reasons.  Here are some:

- Integer values are treated as constants.  In this case, the compiler will print ```0``` instead of ```1``` because it assumes that ```x``` will never change.

```ocaml
external foo : int -> unit = "%asm" "" "movq $3, %0" "=r" "="
let () =
  let x = 0 in
  foo x;
  Printf.printf "%d\n" x
```

A solution is to create a dummy register, but it's hack.

```ocaml
external register : unit -> int = "%asm" "" "" "" "=r"
let () =
  let x = register () in
  foo x;
  Printf.printf "%d\n" x
```

- Returning multiple outputs as a tuple would force allocating the tuple.  The compiler seems not to optimize this case.

- Boxed values are also assumed not to change, but if they're never used as function arguments they are always unboxed.  Again, this requires good knowledge of the internals to use multiple outputs.  Fixing boxing optimization to work in this case has to be done in ```cmmgen.ml``` but I don't see a clean or easy solution.

For now, I'd either remove multiple outputs or use the current solution.  As my example from the previous post shows, it's possible to avoid it using other mechanisms.

**Comment by lpw25** [comment]
> Inline asm is a very advanced feature and not used often. So we should prefer precision to conciseness. For me the main point of the format6 story was that @bvaugon found many little errors in the parsing or interpretation of format string.

As I said, these bugs were from using strings as the internal representation of formats at runtime, not because formats are written in the program source as strings: because they still are written in the program source as strings.

It is no harder to parse the GCC specs than to parse OCaml's syntax for ADT's.

Without a macro system, which would allow actual OCaml values to meaningfully exist at compile-time, it does not seem worthwhile to reuse OCaml's constructor syntax for compile-time information.

**Comment by lpw25** [comment]
> Returning multiple outputs as a tuple would force allocating the tuple. The compiler seems not to optimize this case.

I think that returning tuples is the only reasonable behaviour for multiple outputs. If the compiler's support for unboxing is not good enough yet, then it is probably best to leave out support for multiple outputs for now.

**Comment by vbrankov** [comment]
@lpw25 I agree that returning tuples seems like a best way and it feels doable, but I don't see a simple implementation.  This patch is already large and I'd be happy to leave such feature for later.

**Comment by vbrankov** [comment]
@bobot @lpw25 @planar The inline assembly is parsed to the OCaml type [typing/inline_asm.ml](https://github.com/ocaml/ocaml/pull/162/files#diff-b4061f0d7b6795287d221db2bca77cf2) relatively early in the compilation process, in [typing/typedecl.ml](https://github.com/ocaml/ocaml/pull/162/files#diff-aa5ff89b777ddc4932a276703533682a).  I'm not saying this is similar to format6, but it should be known that strings are replaced at some point.

**Comment by alainfrisch** [comment]
Concerning multiple outputs: I don't know if this is already possible, but an intermediate goal would be to let inline assembly access directly local variables corresponding to unboxed references, including the (doubly) unboxed version for float variables.  This would not give the absolute best performance, but moving to such variables is certainly better than allocating tuples (and boxing floats).  That could be exposed by declaring "output parameters" (of type 'a ref), perhaps with some attributes, on the external declaration (and the compiler would ensure the code is inlined and the corresponding parameters is indeed represented as a local mutable variable).

**Comment by vbrankov** [comment]
Multiple outputs are further complicated because parameters can be input-output.  This may eliminate tuples as a solution.  I will investigate which obstacles exist in getting output and input-output parameters not to be treated as constants.

@bobot Can you give me an example which can be handled by jumps but not with calls?

@alainfrisch Just to be sure, this patch lets the inline assembly access input and the one output variable corresponding to unboxed references.  Making inline assembly understand "ref" for multiple outputs sounds like a good idea.

**Comment by planar** [comment]
@bobot I'm curious about this:
> Often you don't need to type the argument because the context will fix theirs by inference. If it is not the case the compilation fail and the user add the information `(e : ty)`.

How can you tell the difference between "the context gave this argument type `'a`" and "the context didn't give a type to the argument"?

About the "+=rm" syntax, on the one hand it's extremely cryptic, but on the other hand it's well documented with examples and a tutorial (in the gcc docs). If we change the syntax, we'll have to write (or translate) the documentation.

**Comment by vbrankov** [comment]
Why with a simple jump we need to kill only %rax?

**Comment by vbrankov** [comment]
@bobot Another question, why if asm code has an ````a``` argument it will not work with a float?

**Comment by vbrankov** [comment]
@bobot We cannot ```jump``` to a function, one reason that we will crash when the function tries to return.  A function can only get ```call```ed, in which case all the registers need to be parked.

**Comment by vbrankov** [comment]
@bobot I agree that the second function will not be correct, but who will make such a change?  If the user makes such a change, they are required to fix the assembly template.  As far as I know, such a change never happens automatically.  The compiler doesn't specialize the function at the point of the call, it specializes the function at the point of the definition, which is actually an argument for ```external``` syntax.  Non-external syntax may have this problem.

And just to correct a previous statement, there are C externals in which floats are not boxed.

**Comment by alainfrisch** [comment]
> here float are boxed, no?

No, precisely: the (undocumented) "float" annotation tells the compiler that the native version of the primitive (which is `exp` not `caml_exp_float`) works on unboxed floats.

**Comment by vbrankov** [comment]
@bobot Regarding ```goto```, you wrote that ```%ladd``` would be replaced by the label that correspond to the C function ```ml_z_add```.  However, you say that the call would not be done by the programmer, but by the OCaml.  I don't understand how both can be true.

**Comment by vbrankov** [comment]
@bobot For the ```float``` question, I just want to make sure I understand your request.  Instead of determining whether an argument is unboxed based on its type, you advocate an explicit annotation.  Is there anything else you advocate as a part of that discussion?

> And if you have some asm code that work with argument of type 'a it will not work if written with a float which break a property of polymorphic function.

And just to make sure, if a ```float``` is passed to an asm external which accepts an argument ```'a```, the value will not be unboxed and the assembly argument will be the pointer.  Therefore ```float``` will be treated as any other type.

**Comment by lpw25** [comment]
> Instead of determining whether an argument is unboxed based on its type, you advocate an explicit annotation.

I also prefer explicit annotations over reading the type, since reading the type plays badly with abstraction. Although it is worth noting that external already uses `->` in the type to determine arity, rather than an annotation.

> In order to simplify the documentation we can use ocaml syntax and typing.

It is not a good idea to make a compile-time operation look like a runtime one. The `x86` in your example looks like a function, but it is not one. At least wrap this thing in `[%asm ... ]` to indicate it is not actual OCaml code.

**Comment by vbrankov** [comment]
@bobot I think it's a great idea that you implement your input syntax.  It might reveal non obvious problems.

Here's one: ```~continuation``` takes closures or something that looks like closures as arguments.  If those are allocated like closures, it won't be efficient.  Not allocating closures looks like a complicated problem, for example what can be the body of such blocks.

An alternative may be to allow using exceptions from asm in some way.  Exceptions are IMHO to some extent the closest thing in OCaml to ```goto```.  My recent experience with callbacks from asm to OCaml suggest that something like this might work.

**Comment by lpw25** [comment]
> what I like in using a usual module Asm with usual function x86, input_value (defined as primitive `external input_value: ?force_reg:register -> string -> 'a -> asm_input = "%asm_input_value" ) is that Merlin or Odoc will be able to autocomplete or link the documentations naturally without any specific treatment

Link to what documentation? There is no function `Asm.x86` to document.

```
let add x y =
   match Asm.(x86
   ~input:[input_value ~force_reg:`Sil "x" x;
           input_value ~force_reg:`Dil "y" y]
   "test    $1, %x
     jz      %ladd
     test    $1, %y
     jz      %ladd
     lea     -1(%x), %res
     add     %y, %res
     jo      %ladd"
     ~effect:[write_effect_registers [`Rax]]
     ~output_value:(output_value ~force_reg:`Rax "res"))
  with
 | `End, res -> res
 | `Label "ladd", _ -> gmp_add x y
)
```

What are `input_value`, `write_effect_registers` and `output_value` in this code? They look like values, but I guess that they are really keywords in the DSL.

**Comment by vbrankov** [comment]
Output arguments should now be properly implemented.  For example, this function adds the first argument to the second argument:

``` ocaml
external add : int64 -> int64 ref -> unit = "%asm" "add_stub"
       "add     %0, %1  # add" "imr" "+r" "" "cc"
```

The produced code is efficient, boxing and eliminated references are handled.  The given example produces a single assembly line per call.

``` ocaml
let () =
  let x = ref 1L in
  add 6L x;
  add 6L x;
```

``` asm
        movq    $1, %rax
        add     $6, %rax  # add
        add     $6, %rax  # add
```

**Comment by vbrankov** [comment]
@bobot Regarding `goto`, I don't think that only one register would be killed in the example that you provided.  When it encounters a branch, OCaml assumes that the killed registers is a union of the registers killed in each branch.  If a code can lead to a function call, even only conditionally, it will be treated as if it will destroy all the registers and all the registers will be spilled immediately and not only in the branch which requires spilling.  In the given example both `x` and `y` will be spilled even though that's not necessary for one branch:

``` ocaml
let add x y =
  let z = if x < 0 then 0 else max x y in
  z + x + y
```

If this is true, then I see no benefits in supporting `goto`.

**Comment by vbrankov** [comment]
@bobot This is an illustration that even C spills registers despite `goto` being used.  If C had a strategy to spill the registers right before the call, that would mean that having calls in a loop would mean a lot of spilling and reloading.

``` c
int slow_add(int a, int b);

int add(int a, int b)
{
  int c;
  if (a < 0) goto slow;
  if (b < 0) goto slow;
  return a + b;
slow:
  return slow_add(a, b);
}

int main()
{
  int a, b, c;

  scanf("%d %d\n", &a, &b);
  c = add(a, b);
  printf("%d\n", a + b + c);
} 
```

**Comment by vbrankov** [comment]
@bobot In order to check whether an operation causes spilling, we should use some variables, do the operation and use the variables again.  The C `add` function doesn't spill because it does nothing after the call.  The loop doesn't spill `b` because it's in `ebx` which is [caller safe](http://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI).  And generally, providing an example, even if it was correct, could not be a proof.

In your OCaml discussion, I used `max` exactly because I know it would produce a call and not get inlined.

I disagree with the conclusion that having asm-goto would make things simpler.  The only argument that I see is that the calls would be in OCaml.  How much simpler is that, can we have a side-by-side example?  On the other hand, asm-goto looks like Pandora's box.  For start, OCaml syntax doesn't have the means to represent it, so we need to come up with new language constructs.  The compiler support would also be very complicated since an inline assembly is an OCaml primitive.  I don't see any free lunch in trying to treat asm-goto differently, it would come down to introducing goto capability in OCaml.

**Comment by gasche** [comment]
On a more general viewpoint, my understanding of vbrankov's proposition is that its main advantage (compared to safer and also interesting approaches such as letting users write lambda and cmm code directly to define some of their primitives to avoid the cost of the C boundary without having to fork the compiler) is the support for exotic assembly instructions that the OCaml backend doesn't know about. If this is the problem that we aim to solve in this pull request, we should maybe focus on this use-case by assuming small ASM snippets with little to no control-flow.

That is not to diminish bobot's efforts to allow richer control flow to be expressed: it could be very interesting of course, but maybe we could converge on the simpler thing for this PR, discuss whether it is mergeable for this more specific purpose, and consider extensions that solve other problems only a second step.

**Comment by vbrankov** [comment]
@bobot Leo and me discussed possible solutions for your problem to avoid spills and some ideas came up.
- A special pair of primitives which spills and reads back all live registers.  The code around this "block" would be treated as if it destroys no registers.  In this example the effect would be that the registers would be spilled only if a branch with the call is taken, but then the cost of the call would eclipse the cost of spilling:

``` ocaml
let add x y =
  let z = if x < 0 then 0 else begin
    spill_live ();
    max x y
    restore_live ()
  end in
  z + x + y
```
- Write the C function with [register variables](https://gcc.gnu.org/onlinedocs/gcc/Local-Reg-Vars.html#Local-Reg-Vars) to control precisely which registers are destroyed and hence reduce the set of destroyed variables on that call.

**Comment by vbrankov** [comment]
Regarding alternative syntax for the calls, @lpw25 had a good suggestion to use attributes.  Some possibilities

``` ocaml
(* GCC identifiers, less verbose *)
external floor : (float [@unbox][@param "x"]) -> (float [@unbox][@param "=x"])
  = "%asm" "round_stub" "roundsd $0, %0, %1"
external mov : (int [@param "m,r,r"]) -> (int ref [@param "=r,m,r"]) -> unit
  = "%asm" "mov_stub" "mov %0, %1"

(* more verbose *)
external floor :
     (float [@unbox][@xmm])
  -> (float [@unbox][@output][@xmm])
  [@asm "roundsd $0, %0, %1"] = "round_stub"
external mov :
     (int [@memory][@alt][@register][@alt][@register])
  -> (int ref [@output][@register][@alt][@memory][@alt][@register])
  -> unit
  [@asm "mov %0, %1"] = "mov_stub"
```

**Comment by vbrankov** [comment]
@bobot Thanks for the comprehensive example.  Regarding multiple branches, I'm nicely surprised that avoiding creating closures doesn't look as difficult as I expected, although I haven't read the code.  However, I am not convinced that all the problems are solved.  This example boxes floats:

``` ocaml
let x =
  let i = 1. in
  let open Asm in
  let y =
    match arch with
    | AMD64 ->
        amd64
          ~input:[ifloat "%0" i]
          "addsd        %0, %1  # func1"
          ~effect:[`VReg "%1"]
          ~output:(ofloat "%1" oend)
          ~label:[`End,(fun x () -> x)]
    | _ -> assert false
  in
  y > 1.
```

``` assembly
        movsd   .L105(%rip), %xmm0
        addsd   %xmm0, %xmm1    # func1
.L103:
        call    caml_alloc1@PLT
.L106:
        leaq    8(%r15), %rax
        movq    $1277, -8(%rax)
        movsd   %xmm1, (%rax)
.L102:
        movsd   .L105(%rip), %xmm0
        movsd   (%rax), %xmm1
        comisd  %xmm0, %xmm1
```

Not having branches allows the compiler to eliminate boxing.  I feel it is difficult to implement this optimization with multiple branches.

``` ocaml
external addsd : float -> float = "%asm" "" "addsd %0, %1" "x" "=x"

let x =
  let i = 1. in
  let y = addsd i in
  y > 1.
```

``` assembly
        movsd   .L103(%rip), %xmm0
        addsd %xmm0, %xmm1
        comisd  %xmm0, %xmm1
```

This is just an example, there may be more optimizations that may be difficult because the compiler needs to "see" and modify the code inside the branches.

**Comment by vbrankov** [comment]
@bobot The pull request [107](https://github.com/ocaml/ocaml/pull/107) should do more unboxing.

**Comment by vbrankov** [comment]
@bobot All right, I now feel multiple branches is doable.  I will examine it in detail and get back.

**Comment by vbrankov** [comment]
I've heard that there had been a discussion about this patch in the last OCaml Dev meeting and the conclusion was generally negative.  Whoever knows about that meeting please let me know if there's any followup, questions or if anything can be salvaged out of this patch.  For example, easily adding native primitives might still be a useful thing to have.

**Comment by xavierleroy** [comment]
At the dev meeting, the following points were raised (in no particular order).
- Complexity.  Even with your best efforts, this is a fairly big and complex extension.  (I know exactly what you went through here because at about the same time I was adding extended inline asm to the CompCert C compiler...).
- Further adding to the complexity is the need for a mechanism (preprocessor or otherwise) to select the appropriate asm fragment for the target, or a fallback implementation.
- Aesthetics.  Some developers just don't want to see ugly asm templates with obscure % holes in their nifty Caml source files, and feel that the proper place for such code is in separate .s or .c with inline assembly files.
- Performance gains wrt "noalloc" C/asm external functions.  Calling "alloc" external functions is expensive indeed.  However, with the new unboxing annotations (which all devs at the meeting liked, by the way), many more external functions can be declared "noalloc", including those for which you would typically feel the need for inline asm.  The overhead of calling a "noalloc" external functions is relatively low.  So, a plausible alternative to inline asm is just "noalloc" external functions implemented either in C with inline asm, or in assembly.
- As a performance data point, I mentioned a recent experiment with the Zarith library where some "fast paths" are rewritten in portable OCaml, using Hacker's Delight tricks for overflow detection and what not, then inlined by ocamlopt, leaving the "alloc" external calls to the slow path.  The performance obtained is not quite what you'd get with inlining "branch on overflow" asm instructions, but not that far either.  Sometimes, the best way to use asm is to recognize that you don't need it :-)

The conclusion of our discussions is that we are not going to integrated this PR.

The question you raise about the difficulty of adding new, inlined primitives is a good one and remains open.  My personal take on it is that perhaps we should think twice before adding such primitives and try "noalloc" external functions first.

**Comment by DemiMarie** [comment]
One approach would be to allow inline primitives to be written as compiler plug-ins, written in OCaml, that use an embedded DSL (possibly Camlp4/ppx based?) to describe the assembly code and/or bytecode that needs to be generated.

Note that external functions &ndash; even if "noalloc" &ndash; are still far too heavyweight for primitives that are single machine instructions.

**Comment by xavierleroy** [comment]
I'm closing this pull request so that we can better focus on other requests.

**Pull request closed without merging**
