### PR TITLE
Native toploop consolidation

### PR DESCRIPTION
**Pull request by gerdstolpmann**
This PR gets rid of the separate toplevel/opt\* modules and unifies all toploop functionality into the modules that are also used in the bytecode case.  That way, the latest improvements for the bytecode toplevel are also available for the native version. Also, this makes it simpler to use the native toplevel (e.g. important for findlib). In particular:
- `Toploop` is built from a single source `toploop.mlp`, which is preprocessed resulting into `toploop.mlbyte` and `toploop.mlopt`. The code sections that are only for one of the versions are marked with `BEGIN_BYTE`/`END_BYTE` and `BEGIN_NATIVE`/`END_NATIVE`, respectively.
- `Topdirs.load_file` also went into `Toploop`
- The tracing directives from `Topdirs` went into `Trace`
- The cmx files of the toplevel are installed

There are two open issues:
- No support for `#use load_rec`
- No solution for the Windows problem that loaded DLLs cannot be unlinked

It is also not clear to me what happens when we get conflicting symbols, e.g. when modified versions of the same module are loaded. (If this does not work reliably, we should catch it and reject it.)

This branch is not yet super-well tested. I'm sending this PR in particular because I'm hoping for testers. Use `make ocamlnat` after `make world.opt` to build the native toplevel.

There is a findlib branch supporting the native toploop: https://gitlab.camlcity.org/gerd/lib-findlib/tree/ocamlnat

I did not include the .depends files in the PR, so you'll have run `make depend` before building.

### CODE REVIEW

**Comment by lefessan** [comment]
I am a bit concerned with the use of BEGIN_BYTE/END_BYTE and idem for native code. Wouldn't it be possible to create a shared functor (maybe in `topdirs.ml`), and instantiate it differently in `toploop.mlbyte` and `toploop.mlopt` ?

Also, since `Compdynlink` already has some different implementations in bytecode and native, and since `ocamlnat` is only available if `compdynlink.mlopt` is used, maybe it is possible to move some of the byte/native specific code to `Compdynlink` ?

**Comment by gerdstolpmann** [comment]
I guess the functor approach would be possible, in order to isolate the code that is specific for byte/native. Not sure whether `topdirs.ml` is the right place for the functor (because Topdirs is a user of Toploop), this would probably be a new file (e.g. `toploop_common.ml`).

The core part are the different implementations of `load_lambda` and `transl_toplevel_phrase`. I don't see here immediately what could go to `Compdynlink`.

**Comment by gerdstolpmann** [comment]
Will provide this externally. Sorry for disturbing you.

**Comment by alainfrisch** [comment]
This sounded like a useful contribution.  Any opposition to having it included if someone else wants to put some more effort to it?

**Comment by gerdstolpmann** [comment]
Please take it if you want.

**Pull request closed without merging**
