### PR TITLE
make CI bootstrap script compatible with Macos

### PR DESCRIPTION
**Pull request by damiendoligez**
This will help me test locally on my machine, and also show the world how to make a portable script that uses `sed -i`.

### CODE REVIEW

**Comment by dra27** [comment]
FWIW, in opam repository this is achieved just by always doing `sed -ib` (e.g. [back-porting configure fixes](https://github.com/ocaml/opam-repository/blob/master/packages/ocaml-base-compiler/ocaml-base-compiler.4.07.1/opam#L14-L19)). The backup file can then be deleted afterwards if it matters?

**Comment by nojb** [comment]
> This will help me test locally on my machine, and also show the world how to make a portable script that uses `sed -i`.

As per https://stackoverflow.com/a/4247319 the `-i''` does not work for older versions of OS X (10.6).

**Comment by damiendoligez** [comment]
>FWIW, in opam repository this is achieved just by always doing sed -ib (e.g. back-porting configure fixes). The backup file can then be deleted afterwards if it matters?

Interesting, it works on macos, though it's undocumented. At first I went with `sed -i -e <expr> <file>` but it was rather hacky and left spurious backup files.

>As per https://stackoverflow.com/a/4247319 the `-i''` does not work for older versions of OS X (10.6).

Well, stackoverflow is (unsurprisingly) wrong: `-i''` is the same as `-i` and does not work on recent versions of OSX either.

**Comment by damiendoligez** [comment]
@dra27 I followed your suggestion. Would you give me a formal review?

**Review by dra27 — APPROVED** [review]
LGTM! There are only two instances, but it could possibly be done with another function to avoid any risk of typo in the filename, but you either have to meta-program slightly to get the last argument to the function (which looks weirdly complicated for the want of `${-1}`) or put the filename first, which looks very non-`sed`-like 🙂:

```bash
sed_i() {
  sed -i.tmp "$@"
  eval "rm -f \"\${$#}.tmp\""
}

change_exe_magic_number() {
  # ...
  sed_i 's/let \+exec.../' utils/config.mlp
```

**Pull request merged**
