### PR TITLE
Follow Emacs Lisp conventions for caml.el

### PR DESCRIPTION
**Pull request by Chris00**
This is important to make sure the package keeps being distributed in
MELPA.  See https://github.com/melpa/melpa/issues/5002

### CODE REVIEW

**Review by garrigue — APPROVED** [review]
The revised attribution wording looks fine to me.

**Comment by damiendoligez** [comment]
Since you remove the standard OCaml copyright header, you'll have to update `.gitattributes` accordingly by adding this line:
```
emacs/caml.el            ocaml-typo=long-line,unused-prop,missing-header
```

**Comment by monnier** [comment]
Could we also fix the problem that Emacs always asks to save abbrevs after loading caml.el?
In tuareg.el I just installed a workaround for it which rebinds `abbrevs-changed` while loading `caml.el`, but the problem is really in `caml.el` and can be fixed with the patch below:

    --- a/emacs/caml.el
    +++ b/emacs/caml.el
    @@ -432,15 +429,10 @@ have caml-electric-indent on, which see.")
     (defvar caml-mode-abbrev-table nil
       "Abbrev table used for Caml mode buffers.")
     (if caml-mode-abbrev-table nil
    -  (setq caml-mode-abbrev-table (make-abbrev-table))
    -  (define-abbrev caml-mode-abbrev-table "and" "and" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "do" "do" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "done" "done" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "else" "else" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "end" "end" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "in" "in" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "then" "then" 'caml-abbrev-hook)
    -  (define-abbrev caml-mode-abbrev-table "with" "with" 'caml-abbrev-hook))
    +  (define-abbrev-table 'caml-mode-abbrev-table
    +    (mapcar (lambda (keyword)
    +              `(,keyword ,keyword caml-abbrev-hook nil t))
    +            '("and" "do" "done" "else" "end" "in" "then" "with"))))
     
     ;; Other internal variables
 
[ Not sure where to report those issues for those of us who don't want to use github's pull requests.  ]

**Comment by gasche** [comment]
> [ Not sure where to report those issues for those of us who don't want to use github's pull requests. ]

I would be happy to commit your patch directly, but I would prefer to get it in `git --format-patch --stdout` format to preserve proper commit message and credit information. (Feel free to post that here or send me an email with the patch attached.)

If you do not wish to use github pull requests, you can submit/upload patches by creating an issue on [Mantis](http://caml.inria.fr/mantis/) -- although that is not the preferred contribution venue anymore and review/integration may be longer.

(cc @alainfrisch)

**Comment by xavierleroy** [comment]
Merging @Chris00's branch right now.  Then I'll edit the credits in `caml.el` to take my name off, because nothing is left from the awful elisp code I wrote back in 1993, and I'm grateful for this.

**Comment by xavierleroy** [comment]
Done and cherry-picked to 4.06.

**Comment by xavierleroy** [comment]
While I have the attention of Emacs Lisp experts: what should we do about the disappearing `last-command-char` variable ?  See https://caml.inria.fr/mantis/view.php?id=7610

**Comment by monnier** [comment]
@xavierleroy: It didn't disappear, it was just renamed (many many years ago) to `last-command-event`.

**Comment by xavierleroy** [comment]
Thanks for the confirmation.  `last-comment-event` it is.  [trunk 16efe10] [4.06 341a1e7]

**Pull request merged**
