### PR TITLE
More ThreadSanitizer atomics and ignorelist

### PR DESCRIPTION
**Pull request by sadiqj**
This is another https://github.com/ocaml/ocaml/issues/11040 PR.

The first six commits either add `CAMLno_tsan` with a justification for why the race in that function isn't problematic or add relaxed atomics.

The last three commits add an ignorelist to ThreadSanitizer that adds function-ignores for `Field` and `Tag_val` races that we currently don't have a way of dealing with (I plan to elaborate more on the issue).

With these changes I'm down to 34 'failing' tests on the testsuite (that is where ThreadSanitizer reports a race). Unfortunately the remaining ones are going to be pretty difficult to actually address because half the stack traces are in the interpreter.

### CODE REVIEW

**Comment by gadmm** [comment]
I am not familiar of how TSAN works so it is a bit difficult for me to understand the reality of the reported races without more context. However, this lets me judge whether the comments are convincing and informative by themselves regarding thread-safety.

I understand a lot of the added comments as saying “all the writes are protected by a mutex, so races are benign”. Does this mean that some reads happen without the lock being held? If so, you still need at least a relaxed atomic load for these reads. (If not, sorry for the noise, but this is how I am understanding these comments currently, so maybe we will find some helpful clarification. Also, I lack context about the alleged races, but I would be surprised if TSAN had false positives for accesses entirely protected by mutexes. So what is really going on?)

More generally, when you argue about benign races in the presence of plain load/stores, are you taking into account [load/store tearing and invented load/stores](https://lwn.net/Articles/793253/)?

**Comment by sadiqj** [comment]
@OlivierNicole is working on a more general approach that I think obivates this.

**Comment by gadmm** [comment]
I do not see the more general PR yet so I guess this will arrive later. Seeing that there was no progress since March and that it was removed from the 5.0 milestone, do we agree that it is a programming error to do plain reads on variables that are modified concurrently, regardless of the stores being made while holding a mutex? TSAN warns correctly in these cases; such reads should be relaxed atomic.

**Comment by OlivierNicole** [comment]
I agree with @gadmm that this is a data race in the C11 sense, and so theoretically UB. Turning these reads into relaxed atomics would be the principled way to fix it.

**Comment by OlivierNicole** [comment]
> @OlivierNicole is working on a more general approach that I think obivates this.

In fact, the approach we’ve been working on in [ocaml-tsan](https://github.com/ocaml-multicore/ocaml-tsan) (which we intend to propose to upstream soon) aims only at detecting data races in code written by the user, or in the libraries called by that code; usability would not be great if the user had to deal with unrelated data races in the runtime. So we simply silence those. As a consequence it does not subsume the task of hunting data races in the runtime, although it is related.

Incidentally, we have found a number of additional data races in the runtime which I intend to report at some point.

It is also worth noting that TSan should not have false positives so every report effectively points to a data race. The only way we can have false positives is when a function that performs synchronizing operations (atomics, mutexes…) has been explicitly un-instrumented, and that makes TSan miss some necessary happens-before relations.

**Pull request closed without merging**
