### PR TITLE
New representation for queues, avoiding Obj.magic

### PR DESCRIPTION
**Pull request by ghost**
This patch makes use of inline records to avoid the Obj.magic in queue.ml without compromising on performances.

First I tried to keep the same representation but simply enrich the types to avoid the Obj.magic, but the implementation became quite complicated. See [here](https://github.com/diml/ocaml/blob/remove-Obj-magic-in-Queue-2/stdlib/queue.ml).

Instead this patch change the implementation to use a simply-linked list, and the queue keeps a pointer to the end of the list. This uses one more word per queue, but on the other hand the implementation is much simpler.

I wrote some simple micro-benchmarks with core_bench and the implementation proposed in this pull-request is slightly faster than the two other ones (one in trunk and the [more complicated one](https://github.com/diml/ocaml/blob/remove-Obj-magic-in-Queue-2/stdlib/queue.ml)).

### CODE REVIEW

**Comment by gasche** [comment]
This is nice. I also tried to remove the Obj.magic when inline records where introduced, but quickly found out it was (in that particular case) harder than I first thought.

I would be in favor of doing the change (especially now that we have discussed whether inline-records-using code can go in trunk and there seems to be consensus that it can), but I haven't reviewed the implementation yet, and there is no coverage for queues in the testsuite to convince myself without a review (there is a bit of usage of queues in the compiler, but not enough, eg. Queue.copy is never used).

There were two changes to the previous implementation, [one](https://github.com/ocaml/ocaml/commit/54a131a2) to meet tail-recursion requirements (I checked that it still holds in your patch) and [the other](https://github.com/ocaml/ocaml/commit/b2cbd03b35e25f) related to signal-safety (try to have structure invariants preserved at allocation points). The latter is not guaranteed in general for stdlib functions, but it would be nice to check that the re-implementation is not a regression on this point. Is it?

**Comment by ghost** [comment]
I'll look for the signal-safety. It'd be nice to keep the current behavior indeed, especially if people rely on it.

In core, we use `(* BEGIN ATOMIC *)` and `(* END ATOMIC *)` to mark such sections of code for [functions that are mean to be signal-safe](https://github.com/janestreet/core_kernel/blob/master/src/thread_safe_queue.ml). Do you think we should do something similar here? It might also be possible to have `[%begin_atomic]` and `[%end_atomic]` and have the compiler check that there is no call to the runtime in the middle.

**Comment by mshinwell** [comment]
I think we should document in the .mli if a function has been deliberately designed to be thread-safe, as appears to be the case for [Queue.add].

**Comment by ghost** [comment]
I think the implementation of `Queue.add` is as signal-safe as the old one.

**Comment by ghost** [comment]
I added unit tests. Tested against both trunk and this branch

**Comment by gasche** [comment]
Merged in trunk. Thanks, but no thanks for the lack of Changes change!

**Pull request closed without merging**
