### PR TITLE
Define ARCH_INT64_PRINT_FORMAT correctly on mingw-w64

### PR DESCRIPTION
**Pull request by dra27**
Addresses (hopefully) https://github.com/ocaml/ocaml/pull/9939#issuecomment-735909808

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
Looks good to me, thanks a lot!

**Comment by xavierleroy** [comment]
I was about to merge, but this PR has Draft status.  What is holding it?

**Comment by dra27** [comment]
The commit marked "DO NOT MERGE: additional CI". I'm actually just separating that - happy to push the updated branch without that commit and then merge later. Thanks for reviewing!

**Comment by dra27** [comment]
The temporary change was both to upgrade Cygwin and also to test both mingw64 and mingw32 - it adds well over an hour to AppVeyor runs!

**Comment by xavierleroy** [comment]
> The temporary change was both to upgrade Cygwin and also to test both mingw64 and mingw32 - it adds well over an hour to AppVeyor runs!

OK, I see now.  FYI, I upgraded the Mingw 64 machine used by the Jenkins CI at Inria so that it tests the new mingw-w64 compiler.  So that configuration is tested, regardless of what you decide to do with Appveyor.

**Comment by dra27** [comment]
That's good that the Jenkins workers are updated, thanks. I wasn't planning on forcing AppVeyor to upgrade Cygwin as it adds several minutes to each build.

**Pull request merged**
