### PR TITLE
Refactor inlining/specialisation (flambda)

### PR DESCRIPTION
**Pull request by xclerc**
This PR rewrites the `Inlining_transforms.inline_by_copying_function_declaration`
function to make it easier to understand, and adds the information about free variables
of sets of closures to exported infos.

### CODE REVIEW

**Comment by xclerc** [comment]
The refactoring also fixes a bug (triggered by the file added to the test suite).

**Comment by shindere** [comment]
Many thanks for the test, Xavier!

**Comment by xclerc** [comment]
This PR has only been reviewed by @lpw25.
We hence need another review, typically from @chambart.

**Comment by chambart** [comment]
I'm overall ok with this patch. I won't approve yet since I need a bit more time to go through some details, but I think nothing bad will lurk there.

The only thing that doesn't convince me right now is the record for binding variables. This feels a bit like uninitialized variables to me. For instance, if some refactoring forget to initialize some field or some part becomes dead, the compiler won't be able to tell that to us. I understand the syntactic/documentation benefit here, I just don't know if we can do better.

**Comment by lpw25** [comment]
> The only thing that doesn't convince me right now is the record for binding variables.

Do you mean the `let_bindings` field of the `state` type? If so, then that seems to be identical to the `free_vars_for_lets` variable in the old code, so I don't think the risk of not updating it is any different in the new code.

**Comment by chambart** [comment]
That's ok. It's only some nitpicking. I don't have a better way to write that part. It just feel that we are losing some compiler help.

Anyway I'm ok.

**Comment by mshinwell** [comment]
(I'm going to merge this now and keep an eye on the CI on the trunk branch, since any further failures due to the latest rebase are unlikely.)

**Pull request merged**
