### PR TITLE
[runtime] Minor mingw64/cygwin cleanup

### PR DESCRIPTION
**Pull request by ghost**
This trivial PR fixes the definition of the `GREL` macro on mingw64 and cygwin, which allows a special casing of them when deciding how to define the `LEA_VAR` macro to be removed.

No functional change; no `Changes` entry needed.

### CODE REVIEW

**Review by nojb — APPROVED** [review]
LGTM

**Comment by nojb** [comment]
There is an issue with one of the tests with the MSVC backend.

**Comment by ghost** [comment]
This should be fixed now.

**Comment by ghost** [comment]
Argh, this is trickier than I expected. Withdrawing for now.

**Pull request closed without merging**
