### PR TITLE
Fix "nodynlink"

### PR DESCRIPTION
**Pull request by mshinwell**
This should fix the problems reported today by @damiendoligez in GPR#1063.

### CODE REVIEW

**Comment by dra27** [comment]
See also #2160!

**Review by damiendoligez — APPROVED** [review]
Looks good. I tried to test locally: the build is fixed although the test suite apparently is not ready for configuring with `-no-shared-libs` (which should probably be fixed in another PR).

[Edit] sorry for the duplicate report. This is subsumed by #2160.

**Comment by gasche** [comment]
I ran a `precheck` job at https://ci.inria.fr/ocaml/job/precheck/167/

**Comment by dra27** [comment]
@damiendoligez - I fixed it weeks ago!

**Comment by damiendoligez** [comment]
@dra27 Yes, sorry. I jumped at the CI failure but I'd forgotten your PR.
@gasche You can stop your precheck. We should work on #2160 instead.

**Comment by XVilka** [comment]
So I guess this can be closed then?

**Comment by gasche** [comment]
Good catch @XVilka, thanks!

**Pull request closed without merging**
