### PR TITLE
manual: refresh moduleref macro

### PR DESCRIPTION
**Pull request by Octachron**
This PR proposes to refresh the `\moduleref` macro used in the manual. Before this PR, the macro was typically used as

```latex
"Hashtabl"[\moduleref{Hashtabl}]
```
and rendered to

|    Latex                                         |   Html                                                   |
|----------------------------------------------|-----------------------------------------------------|
| Hashtbl[[23.20](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Hashtbl.html)] | Hashtbl[[Hashtbl](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Hashtbl.html)] |

With this PR, the latex syntax is simplified to
```latex
\stdmoduleref{Hashtbl}
```
which is rendered to

|    Latex                                         |   Html                                                   |
|----------------------------------------------|-----------------------------------------------------|
| [Hashtbl](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Hashtbl.html)[[23.20](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Hashtbl.html)] |[Hashtbl](https://caml.inria.fr/pub/docs/manual-ocaml-4.08/libref/Hashtbl.html) |

This PR replaces all uses of `\moduleref` and few handwritten links with this new `\stdref` .

### CODE REVIEW

**Review by gasche — APPROVED** [review]
This looks nice and useful, thanks.

Could you write a Changes entry?

In the LaTeX output, I don't understand what 23.20 refers to. Is it the Chapter/Section of the PDF rendering of the stdlib documentation? Maybe we don't need the numbers anymore, as long as the PDF output makes it sufficiently clear that the module name itself is clickable (by using a link-specific color)?

(Did we cherry-pick the recent manual improvements #2272 and #2273, which justified this feature, to 4.08? If so, then we should cherry-pick this one as well. If we didn't, maybe we should. @Octachron, can I let you merge and decide for 4.08)

I wonder if it's possible to have a macro for specific identifiers within modules, like {!Foo.bar} in ocamldoc notation. I don't know if we have uses of this in the current manual, but I'm fairly confident that use-cases exist today or in the future.

**Comment by Octachron** [comment]
The numbering refers to the manual chapter (23 for the standard library chapter) and the section (the latex output has one section by standard library module in lexicographic order). This `[chapter.section]` numbering is still useful with paper instances of the manual.

I added a Change entry in the 4.08 section: I was planning to cherry-pick this PR and #2272 to 4.08 at the same time. (I had finished the review of #2273 a bit earlier and I have already cherry-picked it).

It would be possible to have a macro for referring components, if the namespace (e.g. type, value, module) is precised, something like:
```TeX
\stdref[type]{Lazy}{t}
```
with `value` as the default namespace. There is however a small caveat (with the current latex output) on the latex side: all references targets a section. For instance, following the link for `Array.make` leads to the start of the `Array` section.
I will send a subsequent PR for this macro while I still have the detail in mind.

**Comment by gasche** [comment]
Thanks! Feel free to merge.

(I have forgotten to check that the two manual PRs have a Changes entry. Could you ensure that this is the case, by adding one if necessary?)

**Comment by Octachron** [comment]
(Both manual PRs already have a Change entry)

**Comment by Octachron** [comment]
Cherry-picked on 4.08 with #2272 .

**Pull request merged**
