### PR TITLE
Hexadecimal notation for floating-point numbers

### PR DESCRIPTION
**Pull request by xavierleroy**
(This code was developed in July 2015, and discussed on the caml-devel mailing list, but I forgot to make a PR with it.)

This pull request adds support for floating-point numbers in hexadecimal notation.  For those who are not familiar, hex FP notation looks like

```
-0x1.ffffp+987
```

with a mantissa in hexadecimal, and an exponent (written after 'p') in decimal, denoting a power of 2.  So, the example above is

```
- (1 + 65535/65536) * 2^{987}
```

This notation is a godsend for people who need to represent IEEE binary FP numbers as text without loss of information.  Unlike the usual base-10 textual representation, the base-16 representation has no issues with complicated rounding, too many / too few significant digits, etc.

The hex FP notation was introduced in C in the ISO C99 standard.  It found its way in other languages, e.g. C++, Java, etc.

What this pull request does:
- Add support in byterun/floats.c for conversions between floats and strings in hex notation.  We cannot rely on the C standard library here because Microsoft consistently fails at supporting hex notation as standardized in C99.  Instead, the conversions are implemented from scratch.
- Add support in the lexer so that hex float literals are recognized in OCaml sources.
- Add support in formats.  The ISO C99 format letters for hex floats are %a and %A, but %a is already taken.  I chose %h and %H, which are rejected today as bad formats (hence no backward incompatibility) and don't mean anything in C either (h is a modifier, not a format letter).  I'm open to other suggestions.
- Add support in printf.  All the trimmings are there in the implementation of %h and %H, including sign modifier and fixed precision.
- Benoit Vaugon contributed support in scanf.

The following points were raised during the discussion on caml-devel:
- NaNs and infinities are printed following ISO C conventions, e.g. nan, -nan, infinity, -infinity.  This is not OCaml-parsable syntax of the kind that printf "%F" produces.  One proposal is to have formats '%#f' and '%#F' that produce OCaml-parsable hex FP.
- scanf "%F" should perhaps accept hex notation as input.

### CODE REVIEW

**Comment by dbuenzli** [comment]
> I chose %h and %H, which are rejected today as bad formats (hence no backward incompatibility) and don't mean anything in C either (h is a modifier, not a format letter). I'm open to other suggestions.

Isn't the backward compatibility constraint only about finding an unused single letter prefix ? If that is the case why not use two letters, i.e. `hf`, `Hf` and reserve all the other two letters formats that start with `h` and `H` for future usage. There could be a few other uses for that `h` prefix; e.g. I'm thinking about `hs` and  `Hs`.

Other than that I'm glad the implementation doesn't rely on libc, it avoids problems with locale and simplifies bare metal OCaml projects...

**Comment by xavierleroy** [comment]
In the C tradition, a single format letter indicates both the type of data (e.g. integer) and the major printing style (e.g. hexadecimal): we write `%x` for integer hexa, not `%hi`.  For this reason, I prefer `%h` / `%H`.  The issue was raised yesterday at the developer's meeting and the consensus is that we have enough format letters left so that we can afford one for hexa FP.

**Comment by gasche** [comment]
Could you give a quick summary of the {Print,Scanf}f,Format support that is still missing? I can try to share the load with @bvaugon to implement them.

**Comment by xavierleroy** [comment]
As far as I know, the only missing feature is that scanf "%F" does not recognize hex notation.  A case could be made that it should recognize all the FP notations accepted by OCaml's lexer, including hex.  But this is definitely not high priority.

**Comment by dbuenzli** [comment]
Would it be possible to add documentation for the new formats in the `mli`s ?

**Comment by xavierleroy** [comment]
(Minimal) documentation was added in printf.mli and scanf.mli as part of commit  86d29bf.

**Pull request merged**
