### PR TITLE
Fix the behavior of Unix.read on Windows + Makefile changes

### PR DESCRIPTION
**Pull request by msprotz**
As discussed in http://caml.inria.fr/mantis/view.php?id=7342

### CODE REVIEW

**Comment by gasche** [comment]
Could we have a test in the testsuite that would fail (on Windows, I guess) with present-day code and works after your patch?

**Comment by gasche** [comment]
Is 725b80c433c08731b5e6d929ce7e29f608bae19e meant to be part of the PR?

**Comment by msprotz** [comment]
Yes I've fixed the runtop target because I needed it to test my fix, so I've submitted these changes along with the pull request.

**Comment by msprotz** [comment]
I meant: I added the runtop target to Makefile.nt (it wasn't there)

**Comment by msprotz** [comment]
Your request for a test is legitimate. I shall point out, however, that:
- there is no `testsuite/tests/lib-unix` (no comment);
- I just tried writing a test, and of course, the tests are not capable of adding the right PATH (not LD_LIBRARY_PATH) like I did for `runtop` on Windows.

This is definitely not fun.

**Comment by msprotz** [comment]
So the tests are run in bytecode and native; the bytecode version needs an extra -I ../../../otherlibs/win32unix after path/to/ocamlrun.exe, but the Makefile doesn't have a way of differentiating the native and bytecode targets...

**Comment by msprotz** [comment]
I couldn't find out how to add a new directory to the test suite, but looking at the Appveyor logs it was correctly picked up (and the test was successful it seems).

**Comment by fdopen** [comment]
This change will break third party code that re-use `Unix.file_descr` for named pipes (e.g. https://github.com/djs55/ocaml-named-pipe/ ). So it should be documented properly.
(In the case of named pipes you have to distinguish between `0` and `EPIPE`. `0` means that `WriteFile` was called with `0`, `EPIPE` that the pipe was closed. Your change conflates both, so `Unix.read` can't be used any longer for named pipes)

**Comment by msprotz** [comment]
Any suggestion on how to fix this cleanly?

**Comment by msprotz** [comment]
Also, are you saying that `WriteFile` with `0` is ok on a named piped but not on an anonymous pipe?

**Comment by msprotz** [comment]
I am told that there's no way to distinguish a named pipe from an anonymous pipe using the Windows API.

**Comment by msprotz** [comment]
Had a quick chat with Damien.
- Rename the existing function read_raw (or something similar)
- Write a `read` wrapper that catches the EPIPE exception and turns it into a zero-read
- Document in the description of Unix.read that advanced users who wish to tell apart EPIPE and 0 because they're on Windows should bind read_raw using an `external` declaration.

Thoughts?

**Comment by xavierleroy** [comment]
The proposed code is an improvement over what we have today and which makes pipes completely nonportable between Unix and Windows. So, I'm in favor of merging this PR as is.

The problem with named pipes and zero-length writes is weird.  I'm positive that under Unix a write of length 0 has no effect.  I'm not sure we want to go out of our way to preserve this strange Win32 idiom.

**Comment by protz** [comment]
Apparently ocaml-named-pipes is aware of the issue and certainly will adapt their code if needed... Who should I see to actually perform the merge? (My personal account, i.e. this one, doesn't have commit rights on GitHub.)

**Comment by gasche** [comment]
I merged manually to squash as appropriate.

**Pull request closed without merging**
