### PR TITLE
MPR#7598: bump AST magic number

### PR DESCRIPTION
**Pull request by damiendoligez**
As a follow-up to https://caml.inria.fr/mantis/view.php?id=7598
I'm pretty sure we need to bump the magic number for ast_impl. @ocaml/ocaml-dev what other magic numbers do we need to update? ast_intf? others?

Here are (I think) all the commits that touched `parsetree.mli` since 4.05.0:
* 5cb27d8ebbc22a5eb2e921b63819aaad7bc96021
* ff05023fdecb83dff9cc1685fca8422776e19503
* f29cd5ab6dcd544b52493fece64563f2621f4ff3
* fd47ba9649f784c7d0772bdf282b8e7c8f1fe5aa
* 9dc86f84172a565c221516289eaadc7f0dad1d5e

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'd suggest keeping ast_impl and ast_intf in sync and bumping them both, because it's the same tools that consume or produce both representations.

A git blame on utils/config.mlp shows the following last changed dates for magic numbers:
* exec : 2014 Apr 06
* cmi  : 2016 May 25
* cmo, cma : 2015 Aug 25
* cmx, cmxa : 2015 Dec 17
* cmxs : 2014 May 07
* cmt : 2016 Oct 14

For "cmi", I see at least commit 30c7967  (Record the safe/unsafe_string mode in .cmi files) that might deserve bumping the magic number.

For "cmx", I wonder about b1ec44f (Add location information to Lswitch).

**Comment by alainfrisch** [comment]
To reduce the risk of problems, shouldn't we simply bump all magic number at each versions?  Which tool/scenario would this affect?

**Comment by shindere** [comment]
Alain Frisch (2017/10/10 09:23 +0000):
> To reduce the risk of problems, shouldn't we simply bump all magic
> number at each versions?  Which tool/scenario would this affect?

It could probably be done that way, sure. At the same time, IMO such an
approach would somehow defeat the very purpose of the magic numbers
which is, AIUI, to track changes that do not coincide with version
changes.

**Comment by xavierleroy** [comment]
> To reduce the risk of problems, shouldn't we simply bump all magic number at each versions?

@damiendoligez and I were discussing an even more radical solution: just derive the magic numbers from the version number, e.g. `Caml`TMMmmpp, where T identifies the type of file, MM the major version number, mm the minor version number, and pp the patchlevel.  No more bumping necessary!

**Comment by alainfrisch** [comment]
> to track changes that do not coincide with version changes.

Do you mean that it would still be a good idea to bump the magic numbers as soon as the file formats change?  This can certainly be useful (e.g. to prevent segfaults when working with dev versions), but what situation do we degrade if we bump the magic numbers also for each release, to be on the safe side at least for released versions?

**Comment by xavierleroy** [comment]
> such an approach would somehow defeat the very purpose of the magic numbers which is, AIUI, to track changes that do not coincide with version changes

For bytecode executable files, I tend to agree: there is a modicum of compatibility from one version of OCaml to the next one, so keeping the magic number unchanged between releases would really mean "bytecode executables built for the previous version still work with the new version of OCaml".

Other Caml-generated files need to be rebuilt when a new version of OCaml is installed, as far as I can see, so why not change the magic numbers at each OCaml version indeed.

**Comment by alainfrisch** [comment]
> CamlTMMmmpp

It's nice, also because it allows tools to report more useful error messages (e.g. "This file was produced by Caml 4.06.0...").

We only need to be careful with the magic number for bytecode executable, to allow using the current ocamlrun on boot/ocamlc of the previous version.

**Comment by damiendoligez** [comment]
Here is a version that synchronizes all the magic numbers, except for `exec`. A bootstrap will be needed.

**Review by xavierleroy — APPROVED** [review]
Looks fine.  Go ahead with the bootstrap and commits.

**Comment by shindere** [comment]
Alain Frisch (2017/10/10 03:01 -0700):
> > to track changes that do not coincide with version changes.
> 
> Do you mean that it would still be a good idea to bump the magic
> numbers as soon as the file formats change?

No I was above all thinking of not bumping it if the file format does
not change, between two compiler versions, say.

**Comment by shindere** [comment]
Xavier Leroy (2017/10/10 10:05 +0000):
> Other Caml-generated files need to be rebuilt when a new version of
> OCaml is installed, as far as I can see, so why not change the magic
> numbers at each OCaml version indeed.

Sure, if they already need to be rebuilt and if this behavior is
considered satistactory, then why not.

**Comment by Drup** [comment]
> CamlTMMmmpp

I also really like that scheme, it stays convenient for forks that keeps the representation but need to forbid vanilla OCaml of loading the files (4 letter is far enough to figure out a unique identifiers among compiler forks).

**Comment by xavierleroy** [comment]
> CamlTMMmmpp

Some work might be needed to update the patterns of the `file` command:
https://github.com/file/file/blob/master/magic/Magdir/ocaml

To avoid confusion with the previous schema, the prefix could be `OCaml` instead of `Caml`.

**Comment by gasche** [comment]
This went in trunk but not in 4.06, does this not mean that the issue still stands with the 4.06 release branch (that they are unchanged since 4.04)? Or is the plan to bump them just before the release (but why wait until then?).

**Comment by damiendoligez** [comment]
Sorry, I forgot to cherry-pick. This is now done (commit 1b703e5c491df7eaa96844bf34efd60a73b17547).

**Comment by bluddy** [comment]
Just a thought on this -- the mli/ml split seems like it was at least potentially designed to allow a scheme whereby a library producer provides interface files + binaries, rather than the source code. This could allow library designers to live in the OCaml ecosystem as closed-source vendors for specific niche purposes. I'm not sure if such professionals currently exist in the OCaml ecosystem - it seems too small to support such a profession right now - but in my mind at least this was one of the justifications for keeping the split mli/ml scheme around. In this case, bumping the magic numbers on each version change would mean that such (hypothetical?) vendors would need to update binaries on each compiler upgrade, as opposed to only doing so when required.

**Comment by alainfrisch** [comment]
There is little hope to link a binary library compiled with some version of OCaml with some other modules compiled with a different version.  For this to work, one would need to have absolutely no change in the data structures stored in .cmi/.cmo/.cmx files (this is almost never the case) and also no change in any of the stdlib modules used by the library -- not only the interfaces but also the implementation (also very unlikely).

This scenario is simply not supported: it is ok to ship OCaml binary libraries, but only for a specific version of OCaml.

**Pull request merged**
