### PR TITLE
Fix for PR#7042: CSE confuses +0.0 and -0.0

### PR DESCRIPTION
**Pull request by xavierleroy**
The fix consists in representing float literals by their bit patterns (int64) in the Mach and Linear intermediate languages.  Conversion from float to int64 takes place during instruction selection.  Since +0.0 and -0.0 have different bit patterns, they can no longer be identified by generic equality.

I'm submitting this patch for review because I think all changes in intermediate languages should be reviewed.  

This change impacts every emitter for every supported platform, current or future.  However, the impact is limited and positive (removes a float->int64 conversion that was present in every code emitter).

### CODE REVIEW

**Comment by alainfrisch** [comment]
Wouldn't it make sense to modify Pervasives.compare in order to distinguish -0. and +0. ?  I assume that people using e.g. Hashtbl to memoize pure functions (on immutable structures containing floats) expect the language semantics to be invariant when arguments are replaced by equal values (w.r.t. Pervasives.compare).

**Comment by chambart** [comment]
The code seems ok.
Would it make sense to have something like:
`type float_representation = int64`
in mach to document a bit ?

**Comment by xavierleroy** [comment]
@alainfrisch : having Pervasives.compare 0.0 (-0.0) <> 0 would cause more problems than it fixes, I'm afraid.  In your hash table example, I expect that keys that compare equal with (=) map to identical values, which would no longer be the case with your proposal.

**Comment by alainfrisch** [comment]
@xavierleroy: it's just weird not to have an equality operator easily available on floats which is compatible with basic operations on floats (i.e. equal arguments map to equal results).  How can we implement memoization for, say, functions (float -> float) or (float -> float -> float)?

**Comment by mshinwell** [comment]
As I wrote on Mantis, I think the flambda branch needs to be careful with this as well.
How about having everything from [Lambda] onwards use this new representation?

**Comment by xavierleroy** [comment]
@bobot: sorry for the dyslexia; I fixed the title of this PR.

@bobot @mshinwell: Yes, I thought about propagating this change "upwards" in other intermediate representations.  For clambda (the Uconst_float constructor), it would introduce some extra code because the closure conversion pass performs FP operations over arguments of Uconst_float constructors, as part of FP constant propagation.  Nothing dramatic, but it made me pause.

**Comment by gasche** [comment]
The consensus at the developer meeting was to merge this patch. There is interest in propagating the change of representation to later passes of the compiler. The flambda people were interested in having the relevant operations (float operations on the Int64.t representations) be put in an auxiliary module, that they could use in flambda as well.

**Comment by xavierleroy** [comment]
Merged manually, commit [trunk 6cd8656], so as to fix the wrong PR number.

**Comment by xavierleroy** [comment]
In the near future, I'll try pushing the float -> int64 change to higher intermediate languages and submit this as a separate PR.

**Pull request closed without merging**
