### PR TITLE
Add comment to amd64/emit.mlp about caml_c_call

### PR DESCRIPTION
**Pull request by nojb**
As far as I can see there is no reason for the diff.

### CODE REVIEW

**Comment by stedolan** [comment]
Making both the same sounds good, but there's an issue with this code sequence (which I realise isn't your fault, but it's a bug nonetheless): `pop; sub rsp` is not "equivalent to pushing last return address", as it is not safe to assume that memory below the stack pointer does not change between two instructions. (Various OS or debugger-level things can cause this memory to change. Read [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20190111-00/?p=100685) for more details).

I think this might happen to work OK on Linux because of the red zone (the OS promises not to touch 128 bytes below the stack pointer), but it's definitely not OK on Windows. Instead of a pop, we should just use a `mov` to load the return address from the top of the stack.

**Comment by nojb** [comment]
> I think this might happen to work OK on Linux because of the red zone (the OS promises not to touch 128 bytes below the stack pointer), but it's definitely not OK on Windows. Instead of a pop, we should just use a `mov` to load the return address from the top of the stack.

Thanks for the quick review @stedolan! I replaced `sub rsp, 8` by `push r12`. I didn't replace the first `pop` by a `mov` because I didn't see an easy way to adapt the second line that comes after it `Store_bottom_of_stack rsp` accordingly.

**Comment by xavierleroy** [comment]
It's better to understand this code in historical context, but I agree this context is hard to gather!  (The SVN history was partially destroyed, and even my mail archives from July 2012 didn't help much.)

From what I gathered, amd64.S was changed by Fabrice Le Fessant in july 2012 so that caml_c_call would tail call the C function.  Before, it would call the C function, then reload r15, then return to the OCaml.  The motivation for the tail call was to produce more meaningful stack backtraces, probably in the context of profiling tools (gprof? perf?  I don't know).

The downside of the tail call is that the reloading of r15 must be performed after the call to caml_c_call, at every call site for caml_c_call, increasing code size to some extent.

Since the profiling tools in question are not available for the pure Win64 port of OCaml, or since Fabrice didn't care about this port,  amd64nt.asm was not changed and kept the code-size-efficient approach where r15 reloading is done in the shared caml_c_call code instead of being duplicated at every call site.

So, of course we can make the amd64-win64 port of OCaml as inefficient as the amd64-unix port :-), but do we really want to do that?

**Comment by xavierleroy** [comment]
> here's an issue with this code sequence (which I realise isn't your fault, but it's a bug nonetheless): pop; sub rsp is not "equivalent to pushing last return address", as it is not safe to assume that memory below the stack pointer does not change between two instructions.

This is a separate issue that would ideally be discussed and addressed in a separate PR.

I do agree that this idiom is very likely safe with the ELF ABI because of the red zone, and very likely unsafe with the Win64 ABI.

**Comment by nojb** [comment]
> So, of course we can make the amd64-win64 port of OCaml as inefficient as the amd64-unix port :-), but do we really want to do that?

Thanks for the context @xavierleroy! I agree there isn't much of an argument to do this. I can change this PR to instead add some documentation to `amd64/emit.mlp` to save time to future readers.

**Comment by xavierleroy** [comment]
It's a tough call performance-wise.  Reloading r15 in caml_c_call executes 2 extra instructions (push r12; ret) at every call, but reduces total code size.  I tend to think that caml_c_call is hot code that stays in the code cache, hence the 2 extra instructions are cheap, but I may be wrong.

**Comment by nojb** [comment]
> It's a tough call performance-wise. Reloading r15 in caml_c_call executes 2 extra instructions (push r12; ret) at every call, but reduces total code size. I tend to think that caml_c_call is hot code that stays in the code cache, hence the 2 extra instructions are cheap, but I may be wrong.

I don't think it is worth much, but out of curiosity I tried the following:
```
$ cat c_foo.c
#include <caml/mlvalues.h>
value foo(value unit)
{
  return Val_unit;
}
$ cat foo.ml
external foo : unit -> unit = "foo"
let () =
  for i = 1 to 100_000_000 do
    foo ()
  done
```
compiled with:
```
$ ocamlopt -o foo.exe c_foo.c foo.ml
```
got:
```
# tail-call
$ time ./foo.exe

real    0m0,250s
user    0m0,015s
sys     0m0,000s

# non-tail-call (current trunk)
$ time ./foo.exe

real    0m0,267s
user    0m0,000s
sys     0m0,000s
```

**Comment by xavierleroy** [comment]
A small benchmark like yours fits in the L1 code cache, so code size doesn't matter and fewer instructions executed wins.  On real programs like those you develop at Lexifi, smaller code matters for performance.

**Comment by nojb** [comment]
> A small benchmark like yours fits in the L1 code cache, so code size doesn't matter and fewer instructions executed wins. On real programs like those you develop at Lexifi, smaller code matters for performance.

Indeed; are you happy with the comment in `emit.mlp`? If yes, I propose to squash and merge.

**Review by xavierleroy — APPROVED** [review]
LGTM.  An informative comment beats a "TODO" comment any time :-)

**Comment by nojb** [comment]
> LGTM. An informative comment beats a "TODO" comment any time :-)

Thanks!

**Pull request merged**
