### PR TITLE
Libraries for writing DWARF-4

### PR DESCRIPTION
**Pull request by mshinwell**
This pull request provides libraries for writing the DWARF-4 debugging information format.  This is not yet fully comprehensive and also does not yet provide support for reading DWARF, which might be useful in the future.

Some soundness checks on DWARF generated using this library are provided via the OCaml type system.  The user interface provided by the high-level library makes the construction of DWARF debugging information entry trees straightforward, abstracting away from some of the awkward details.

This pull request will not yet build due to other changes that haven't yet been merged, but comments are welcome.

### CODE REVIEW

**Comment by bschommer** [comment]
It would really be nice if this lib would also be available outside of the compiler.

**Comment by mshinwell** [comment]
@bschommer I think we should be able to arrange that.

**Comment by mshinwell** [comment]
@bschommer Although we would have to work out what to do about the `Asm_directives` dependency.  Not insurmountable I'm sure.

**Comment by mshinwell** [comment]
I think the only significant thing that now needs doing here, for the first release, is to clear up the mess about "rvalues" in Operator and Simple_location_description.

**Comment by bschommer** [comment]
If you need someone for reviewing the Debug PR's I can offer my help. I would really appreciate if this would land in 4.07

**Comment by mshinwell** [comment]
@bschommer The offer of help is much appreciated, I will be in touch.

**Comment by mshinwell** [comment]
This is going to be superceded.

**Pull request closed without merging**
