### PR TITLE
testsuite: remove dead code

### PR DESCRIPTION
**Pull request by shindere**
This PR gets rid of the testsuite/makefiles subdirectory.
The summarize.awk file is moved to the testsuite directory, while
Makefile.one and Makefile.common are removed because they are no longer used.

### CODE REVIEW

**Review by dra27 — APPROVED** [review]

**Comment by dra27** [comment]
This makes a certain amount of hygiene sense for 4.09 as well, but it can't go on unless #8666 is cherry-picked too. @gasche / @damiendoligez?

**Comment by shindere** [comment]
Many thanks for having merged this!

**Comment by damiendoligez** [comment]
I don't think it's worth the trouble of cherry-picking this one.

**Comment by shindere** [comment]
Damien Doligez (2019/06/19 13:45 +0000):
> I don't think it's worth the trouble of cherry-picking this one.

Fine with me! Thanks!

**Pull request merged**
