### PR TITLE
ocamltest: convert ocamldoc tests

### PR DESCRIPTION
**Pull request by Octachron**
This PR converts all ocamldoc related tests to ocamltest. Moreover, the last commit merges together the `tool-ocamldoc`, `tool-ocamldoc-2`, `tool-ocamldoc-html`, and  `tool-ocamldoc-man` test directories. Those directories where separated by ocamldoc backend, which can now be selected on a file-by-file basis.

Beyond the ocamldoc specific code and variables, this PR also adds the option to specify a number of skipped line in the output file when comparing the reference and output file in a test. It was useful for the man backend which outputs the current date in the header of the main file.

Similarly, I have added a text file type in order to handle test-only documentation file, and a new variable "plugins" for plugins that needs to be compiled. Currently, the `plugins` variable is only used for the custom ocamldoc generator but it seems potentially useful in a larger settings.

On the ocamldoc-specific side,  after some discussion with @shindere, I choose to have a `ocamldoc_flags` in order to keep an independent `flags` for compiling plugins and interface files.

### CODE REVIEW

**Comment by shindere** [comment]
Many thanks for this contribution, Florian!

I started to review and will try to give a complete feedback still
today.

Just a question: do you intend to cleanup your history a bit?

I am asking because, at the moment, e.g.
0015a4b62ac43ce3946ce95c88f10b830a57b27d would not even compile because
it still contains conflict marking lines.

A clean history would make it easier for me to review and is also
important for the future, in case a bisection falls in this series
ofchanges.

Actually, what I would find great would be to havetwo series of changes:

- The ocamltes-related changes that were needed to migrate the tests

- the migration of the tests itself.

Do you think it would bepossibleto reach this?

Thanks again for your help!

**Comment by xclerc** [comment]
I would suggest to run these tests iff ocamldoc has not been disabled at configure-time,
as discussed in https://github.com/ocaml/ocaml/pull/1611.

**Comment by Octachron** [comment]
@shindere, I have cleaned a bit the history, splitting the commits into an ocamltest part and a testsuite part. I am hesitating to squash most commits on the ocamltest side into one.

@xclerc , thanks for reminding me of this point! The last commit 
2c84b0d should take care of skipping ocamldoc tests when ocamldoc itself is disabled.

**Comment by shindere** [comment]
Xavier Clerc (2018/03/05 10:03 +0000):
> I would suggest to run these tests iff ocamldoc has not been disabled at configure-time,
> as discussed in https://github.com/ocaml/ocaml/pull/1611.

Indeed, thanks a lot for the reminder Xavier!

@octachron: regarding the implemnetation, I think it would be good to
implemnet it in a way similar to the nativetest: if ocamldoc is neabled
then the test should be the list of actionsasit is now, otherwise the
list of actions should contain only the skip action.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Merged. Thanks a lot for this great work!

**Pull request merged**
