### PR TITLE
Generate local jump labels on OS X (PR#7133)

### PR DESCRIPTION
**Pull request by btj**
See [PR#7133](http://caml.inria.fr/mantis/view.php?id=7133)

### CODE REVIEW

**Comment by mshinwell** [comment]
@damiendoligez I think we should consider this for 4.03, since at least one of the deficiencies this rectifies is a serious nuisance (labels appearing instead of function names in lldb).

**Comment by xavierleroy** [comment]
Thanks @btj for explaining the mysterious link failures when proper MacOS X local labels are used.

I have one reservation about this patch, which is that it puts data (jump tables) in the middle of code.  This is semantically correct but could have a performance impact owing to "bubbles" in the code cache.  (= bytes that are never executed as machine code, yet are fetched into the code cache because they are adjacent to machine code instructions.)  That's why many compilers (GCC and ocamlopt included) try to put jump tables in a different section than the code section.  However, I don't know whether this performance hit is significant in practice.  

A way to have one's cake and eat it too would be to record the jump tables occurring in Lswitch instructions, then emit them all in end_assembly().  This way, even if the jump tables are put in the code section, they are less interspersed with actual code.

**Comment by xavierleroy** [comment]
Also: there is another use of local labels that cannot be resolved at assembly-time and must be resolved at link-time, namely the code labels that are put in the frame table.  These are code labels defined in the .text section (put e.g. just after a function code) and referenced from the .data or .const section (the frame table).  How comes that those local labels are correctly handled by the MacOS X assembler and linker, while those corresponding to jump tables are not?

**Comment by alainfrisch** [comment]
- In addition to avoiding bubbles in the code cache, could it be that emitting all jump tables together improve (data) cache efficiency?
- Emitting the jump tables in the code was already the case for msvc64.  I'm glad that the merger of emit.mlp and emit_nt.mlp will allow us to benefit to both if we improve the situation here!
- If one groups the table as suggested, I'd suggest doing it for all ports, not just OS X and MSVC64 (and perhaps even always emitting to the text section if this is ok).  Removing useless differences is always a good idea.

**Comment by xavierleroy** [comment]
2016-02-03 10:10 GMT+01:00 Alain Frisch notifications@github.com:

>    -
> 
>    In addition to avoiding bubbles in the code cache, could it be that
>    emitting all jump tables together improve (data) cache efficiency?
> 
> It is good for data cache efficiency in general, yes.  But note that this
> grouping effect is already achieved today for the non-MSVC ports, as the
> jump tables are emitted consecutively in a readonly data section where
> nothing else is emitted.
> 
>    -
> 
>    Emitting the jump tables in the code was already the case for msvc64.
>    I'm glad that the merger of emit.mlp and emit_nt.mlp will allow us to
>    benefit to both if we improve the situation here!
> 
> Yes, the MSVC64 port would benefit.
> 
>    -
> 
>    If one groups the table as suggested, I'd suggest doing it for all
>    ports, not just OS X and MSVC64
> 
> Agreed.
> 
>    -
> 
>    (and perhaps even always emitting to the text section if this is ok).
> 
> There are pros and cons.  Pro: the assembler shoudl be able to resolve the
> label arithmetic in jump tables entirely, possibly reducing the amount of
> relocations emitted and the amount of link-time work.  Cons: I still prefer
> data to be in data sections, and code sections to contain machine code
> only.

**Comment by damiendoligez** [comment]
> How comes that those local labels are correctly handled by the MacOS X assembler and linker, while those corresponding to jump tables are not?

Experimentation seems to show that the only problematic case is a subtraction where the two operands come from different sections and the second one is a local label.

About the impact on cache performance, the jump table ends up located between the jumping code and the code for the cases, so the cache will only see a difference when jumping to the first branch.

I move that we merge this patch, as it is a very simple (and safe) change that solves a real problem. Refinements can come later.

**Comment by damiendoligez** [comment]
Merged in trunk (commit 0a914a4765b8b97f230806706fedc6112a033f77).

Thanks.

**Pull request closed without merging**
