### PR TITLE
Remove unused variable from the build system

### PR DESCRIPTION
**Pull request by shindere**

### CODE REVIEW

**Comment by shindere** [comment]
Especially interested in your comments, @alainfrisch, @gasche,
@whitequark and @adrien-n

**Comment by whitequark** [comment]
LGTM--looks like the last major user was removed in 3958a92c729c6588bdd4a39d6d8bc5dadb00b3de, and last user was labltk.

**Comment by gasche** [comment]
So according to [debian code search](https://codesearch.debian.net/search?q=DLLCCCOMPOPTS), there is no Debian package that use this variable (the OCaml compilers define it but don't use it). Google indicates that it was used in old `%.c.$(DO)` Makefile rules for Windows, which are still copy-pasted in a few projects that include the OCaml sources (for example [ucsd-progsys](https://github.com/ucsd-progsys/dsolve/blob/master/byterun/Makefile.nt), [loop](https://github.com/s3team/loop/blob/master/pcre-ocaml/pcre_make.win32/Makefile.win32)), but those occurrences were removed from the compiler distribution in commit https://github.com/ocaml/ocaml/commit/3958a92c729c6588bdd4a39d6d8bc5dadb00b3de , when @alainfrisch merged the natdynlink branch. Alain may know why these variables are not necessary anymore.

This variable DLLCCCOMPOPTS is exported in `%{lib}/ocaml/Makefile.config`, so it is in theory possible that third-party packages would rely on it as part of their build. But I can't find any on google. I would guess that if it's not necessary to build the compiler anymore, any package using the variable could also rewrite their build system to not use it.

**Comment by adrien-n** [comment]
I don't have much to add to what has already been said: indeed, it is unused in the compiler and seems to have been lingering for several years now.

As for it being present in Makefile.config, I'm not surprised it's difficult to find something using it because that file has not been exported for very long as far as I remember and the entry is probably only there because now everything from the ocaml configure step is exported, regardless of any actual usefulness.

**Comment by gasche** [comment]
@whitequark, @adrien-n: thanks a lot for your feedback -- not only on this PR, but the others as well.

**Comment by shindere** [comment]
@gasche, @whitequark, @adrien-n: many thanks for your useful feedback
on this PR. Will try to investigate more in the future so that you guys
do not have to do the checkings.

**Pull request merged**
