### PR TITLE
ThreadSanitizer support for s390x

### PR DESCRIPTION
**Pull request by ghost**
This adds TSan support for Linux/s390x.

s390x support in TSan is quite recent (last fall), so you need recent gcc or clang binaries.

I have tested it with both. When using gcc, all uses of `pthread_create` trigger an internal consistency check in TSan regarding the layout of thread-local storage, which breaks 80 tests. When using clang, this assertion does not fire, so I suppose `lld` builds slightly different binaries (this also hints that s390x TSan support has never really been tested with gcc on this platform).

Using clang, there are nevertheless ~4~3 test failures:
- ~`tests/callback/callback_effects_gc.ml` always triggers a TSan alarm (`ERROR: ThreadSanitizer: SEGV on unknown address 0x255434484000 (pc 0x02aa1a1ef006 bp 0x000000000000 sp 0x03ffecf7e258 T2381383). The signal is caused by a UNKNOWN memory access.`). This might be a real problem. I have not been able to make this test fail under TSan under amd64, arm64 or riscv64.~ EDIT: different issue, fixed by #12919 
- three tests in `tests/tsan` (`array_elt.ml`, `exn_in_callback.ml` and `record_field.ml`) show minor differences in their backtrace output. This happens because the affected symbols have the same address as `code_begin` symbols, and for some reason libunwind returns e.g. `camlArray_elt.code_begin` instead of `camlArary_elt.writer`. This is probably not fixable without some tinkering with libunwind or explicit code to prefer any symbol over `code_begin` when multiple symbols match an address, which in any case is out of the scope of that PR.

Despite the tragic failures with gcc, I have nevertheless opted to allow TSan to be enabled with both gcc and clang, in the hope that things will improve in the near future.

~With this PR (and the other pending TSan PRs), support for TSan is available (at least under Linux) on all platforms for which a native compiler is available. Note that all these PRs will conflict with each other due to changes in the same locations in `configure`; I have also omitted changes to the documentation (`manual/src/cmds/tsan.etex`), and will update this file in the last PR to be merged (this assumes that these PR won't spend too much time waiting for enthusiastic reviewers).~ EDIT: done

### CODE REVIEW

**Comment by ghost** [comment]
I forgot to mention that the changes in this backend are very similar to the POWER changes in #12876 (no assembler macros, reserved space at the bottom of the stack to be setup by the caller of C-linkage functions).

**Comment by dra27** [comment]
(added to 5.2 milestone for discussion later)

**Comment by ghost** [comment]
Ping @AlekseiNikiforovIBM, you might want to have a look at this.

**Review by tmcgilchrist — APPROVED** [review]
Looking good to me. 

One question on s390x assembly. The s390x provides some instructions for doing multiple stores and loads in a single instruction, the LOAD ACCESS MULTIPLE and STORE ACCESS MULTIPLE instructions. Is there a reason why these instructions are not used when saving and restoring registers across function calls? It might be faster / more efficient.

**Comment by ghost** [comment]
> One question on s390x assembly. The s390x provides some instructions for doing multiple stores and loads in a single instruction, the LOAD ACCESS MULTIPLE and STORE ACCESS MULTIPLE instructions. Is there a reason why these instructions are not used when saving and restoring registers across function calls? It might be faster / more efficient.

The reason these instructions are not used is that, in this PR, I strived to keep a consistent coding style with the remainder of the file, and to keep the changes to non-TSan code paths as limited as possible, in order to help review.

A further PR could address this and use these instructions (after checking they are indeed available on z>=13 systems). Generally speaking, the assembler code in `runtime/s390x.S` uses quite conservative mnemonics and almost no `as(1)` sugar, but since OCaml 5 requires a C11 compiler, one can expect a quite modern toolchain and thus a modern `as` as well...

**Comment by shindere** [comment]
It looks absolutely wise to me to not introduce new instructions here
and to consider this as a separate PR.

I am thus going to approve on behalf of @tmcgilchrist and merge.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
OK merged, to be backported to 5.2 I think!

**Comment by shindere** [comment]
Miod Vallat (2024/02/08 02:01 -0800):
> Ping @AlekseiNikiforovIBM, you might want to have a look at this.

Oops, sorry, it seems I overlooked this...

**Pull request merged**
