### PR TITLE
Turn flambda invariants checks off by default

### PR DESCRIPTION
**Pull request by chambart**
I think that flambda is mature enough for this change. Now it doesn't seem to catch enough bugs in the wild to justify the increased compilation time.

This change includes a new compile time option to turn the checks on, and a configure option to change the default. The configure option is used to keep those checks enabled for travis. It might be a good idea to keep them on also for Inria's CI. @damiendoligez What do I need to do for that ?

If this goes in 4.07, we might want to merge that after the beta.

### CODE REVIEW

**Comment by shindere** [comment]
Replying to this for @damiendoligez: see the tools/ci-build and
tools/ci-build-other-configs scripts to enable this.

If there is any adjustment to do t the Jenkins level,feel free to
contact me in private.

**Comment by chambart** [comment]
@shindere, Is https://github.com/ocaml/ocaml/pull/1686/commits/0fe10067636b8c43536c5fba59a6b79bee43fe12 the right way to do that ?

**Comment by shindere** [comment]
Pierre Chambart (2018/03/30 13:54 +0000):
> @shindere, Is
> https://github.com/ocaml/ocaml/pull/1686/commits/0fe10067636b8c43536c5fba59a6b79bee43fe12 the right way to do that ?

After a quick look I'd say yes, this is correct.

It may be good for you to let this go through precheck, so that you will
be able to juge by yourself whether this does what you want or not.

The HACKING file has instructions on how to do that and if you need more
guidance or support in any form do not hesitate to contact mein private.
It is possible that I won't reply during this week-end,though, but I'll
definitely respond from next Tuesday.

**Comment by mshinwell** [comment]
I've reviewed the whole of this and it looks correct.  I don't think we need to precheck this one, so merging now.

**Pull request merged**
