### PR TITLE
Check for misplaced attributes on module aliases (Fix #7538)

### LINKED ISSUE #7538: @inlined doesn't seem to work with module aliases
**Original bug ID:** 7538
**Reporter:** talex
**Assigned to:** @mshinwell
**Status:** assigned (set by @mshinwell on 2017-05-23T13:46:02Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.04.1
**Category:** middle end (typedtree to clambda)

## Bug description

When building a project with @inlined annotations using jbuilder, OCaml complains that 'the "inlined" attribute cannot appear in this context'. Turning off "wrapped" mode made the warning go away. It looks like @inlined doesn't work with module aliases.

## Steps to reproduce

(simplified by lpw25)

module M = Map.Make[@inlined](String);;

works, but:

module N = Map
module M = N.Make[@inlined](String);;

gives:

Warning 53: the "inlined" attribute cannot appear in this context

### PR DESCRIPTION
**Pull request by lpw25**
Adds checks for misplaced attributes on module aliases.

### CODE REVIEW

**Comment by gasche** [comment]
(The email I received for this PR contained no information that would let me know what the PR was about. The github interface is slightly better as it mentions the cross-reference you posted on #7538, including its title: "@inlined doesn't seem to work with module aliases".)

**Comment by xavierleroy** [comment]
These extra warnings look nice.  Could we have a review?

**Review by Octachron — APPROVED** [review]
The warnings for misplaced inline and inlined attributes on module aliases look good to me.

**Comment by lpw25** [comment]
Rebased, check-typo fix applied and Changes entry added

**Pull request merged**
