### PR TITLE
Replace "noalloc" and "float" by attributes

### PR DESCRIPTION
**Pull request by ghost**
OCaml allows to annotate externals with `"noalloc"` and `"float"`, as follow:

``` ocaml
external f : float -> float = "byte-code-func" "noalloc" "native-code-func" "float"
```

But this is a bit tedious as `"noalloc"` and `"float"` are only recognized if they are at the right place in the list of strings. Moreover the manual just says that the strings after the `=` are supposed to be either:
- `"stub"`
- `"byte-code stub" "native-code stub"`

Now that we have attributes, it seems natural to use attributes for these annotations. This patch introduces the following attributes on external declarations:
- `[@@noalloc]` to replace `"noalloc"`
- `[@@unboxed]` to generalize `"float"`. It has the same effect as adding `[@unboxed]` to all arguments and the result but is syntactically lighter
- `[@@untagged]` for consistency with `[@@unboxed]`

The above declaration can be rewritten:

``` ocaml
external f : float -> float = "byte-code-func" "native-code-func" [@@noalloc] [@@unboxed]
```

The patch also updates external declarations in the stdlib and otherlibs. Declaration that were marked with only `"float"` are now marked with both `[@@noalloc]` and `[@@unboxed]`. This is because  `"noalloc"` is assumed when `"float"` is present.

### CODE REVIEW

**Comment by gasche** [comment]
I find the feature natural and desirable, and appreciate the fact that it comes with extensive testing.  Below are two remarks I had during my review, but none or them correspond to change requests, I'm trying to make sure I understand the fine prints here.
1. What about namespacing of attributes? It looks like the compiler is now reserving `unboxed` and `untagged`, at least as attributes to external declarations. (That seems reasonable). Do we want to also allow the more explicit form `ocaml.unboxed` and `ocaml.untagged`, as we did for `ocaml.deprecated`? Maybe we don't have enough experience handling namespace issues to make a good choice, and thus your default choice of doing nothing is good enough.
2. There is something slightly unpalatable in your implementation, which was present in the previous patch for unboxed/untagged (and I believe introduced by it), which is that you convert from a highly structured (good!) to an unstructured representation (bad!) of the same information inside the compiler, while usually we try to go the other way around. I'm thinking of the function [attr_of_native_repr](https://github.com/ocaml/ocaml/pull/240/files#diff-45a4c1ad1037b1f20296d05c1bad2b94R129) inside `primitive.ml`. The unstructured representation is more visible with this new patch, because you add a new `string list` field to the `Osig_value` constructor. Would it make sense to pass structured information instead?
   
   My understanding is that doing it this way (with `string list`) is not better design in absolute terms (we don't need the flexibility to pass unstructured information at this point in the compiler), but it makes it easier to ensure that this patch does not change current behavior, in particular that stuff that is parsed with `"float"` will not be pretty-printed back in `@@float` by `oprint.ml` -- a natural side-effect of the natural implementation using structured information in `Osig_value` fields. Can you confirm that you preserve this property today?

**Comment by alainfrisch** [comment]
About namespacing, all attributes currently interpreted by the compiler can use either form xxxx or ocaml.xxxx.  I think we should stick to this property, which gives users an escape route in case of a clash with external packages.

**Comment by ghost** [comment]
About the namespacing, yeah I agree it's better to accept `ocaml.name`. I'll do the change.

For the outcometree, we can surely change `Osig_value` to:

``` ocaml
  | Osig_value of out_val_decl
and out_val_decl =
  { oval_name: string;
    oval_type: out_type;
    oval_prims: string list;
    oval_attributes: out_attribute list }
and out_attribute =
  { oattr_name: string }
```

And move the `Primitive.description -> out_val_decl` code to `Primitive` to avoid creating string lists. However I'm not convinced we should be more precise than `out_attribute list` for `unboxed`, `noalloc`, ... as we'll just end up copying the `Primitive.description` type and move the printing logic of externals to `oprint.ml`

> Can you confirm that you preserve this property today?

Yes, I added tests for all the forms accepted by `Primitive.parse_declaration`

**Comment by gasche** [comment]
I do think the code is mergeable in its current state.

**Comment by ghost** [comment]
@gasche, OK. I did the modification for `Osig_value` in the end, the type is a bit cleaner now. I'm out for the next few days, I can merge that next week

**Comment by xavierleroy** [comment]
"noalloc" as an attribute is very nice.  For "unboxed" and "untagged", I was initially on the fence: a case could be made that it is clearer to annotate earch relevant argument as unboxed or untagged, rather than annotate the whole declaration.  But it is true that per-argument annotation is syntactically heavier and makes library documentation harder to read, while the per-declaration annotation looks better in the documentation.  

One question (that I could probably answer by reading the patch, but I'm too tired): what happens to the old-style "noalloc" and "float" magic strings?  They keep working?  They keep working but generate a "deprecated" warning?  They stop working?  Even though they were never documented, they are used in a bunch of OCaml/C binding libraries...

**Comment by bobzhang** [comment]
This is a good idea. Since you are chaning `typing/primitive.mli`, I am suggesting doing it in a more general way(Note that I am working against 4.02.3, so I don't have a patch at hand)

https://github.com/bobzhang/ocaml/blob/master/typing/primitive.mli

``` ocaml
type 'a description =
  { prim_name: string;         (* Name of primitive  or C function *)
    prim_arity: int;           (* Number of arguments *)
    prim_alloc: bool;          (* Does it allocates or raise? *)
    prim_native_name: string;  (* Name of C function for the nat. code gen. *)
    prim_native_float: bool;
    prim_attributes: Parsetree.attributes;

    prim_ty: 'a

      (* should not be optional, the only missing place 
          is built in primitives*) 
  }  (* Does the above operate on unboxed floats? *)
```

The idea is pass all meta data including `Parsetree.attributes` and type declarations into description.

The motivation is now you can have a single declaration for both c and javascript backend, for example,

``` ocaml
external test_c_and_js : int -> bool -> int = "c_implemenation" [@@js.call "js_implemenation"]
```

Having both the type information and attributes are important, since the Js version will do type conversion between js object and ocaml object automatically.

Note that I use `'a description` instead of `Types.type_expr Primitive.description` is just a technical thing to make my patch minimal. see https://github.com/bobzhang/ocaml/blob/master/bytecomp/lambda.mli

There is a limitation of my current implementation, for example

``` ocaml
external f : (float [@unboxed]) ->  bool
```

The attribute `@[unboxed]` is not carried into `Types.type_expr`, it would be nice to keep this information as well

**Comment by ghost** [comment]
@xavierleroy, I kept support for `"noalloc"` and `"float"` as they are indeed used quite often. I'm adding a "deprecated" warning

@bobzhang, the changes you propose should be discussed in a dedicated pull-request, as they are not related to the current one. The compiler already keeps the declaration attributes in `Types.value_description`, keeping these attributes and types in the lambda is a different problem

**Comment by ghost** [comment]
Committed in trunk, revisions 16451 to 16461

**Pull request closed without merging**
