### PR TITLE
Constify C constructors and flags tables

### PR DESCRIPTION
**Pull request by MisterDA**
There's little value to this considering the constructors tables are `static`, used very locally, but this serves nonetheless as an indication to the programmer that the tables are not to be modified.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Looks fine to me.

**Review by xavierleroy — APPROVED** [review]
Nice touch.  Now these tables will go in the readonly segment, where they belong.

**Comment by xavierleroy** [comment]
Can you add a Changes entry?  Then I'll merge.

**Comment by avsm** [comment]
There's also another opportunity for the same treatment for `static int posix_signals[]` in `runtime/sys.c`, in case you want to constify that too.

**Comment by MisterDA** [comment]
Done and done!
While grepping, I've also found this:
https://github.com/ocaml/ocaml/blob/683d0ca1de0b8bea7ae9e62cc2415a576b6e35b8/bytecomp/bytelink.ml#L488
maybe the generated `caml_code` could be made `const` too, if it's not self-modifying, or no changes are made to the array?

**Comment by xavierleroy** [comment]
> maybe the generated caml_code could be made const too, if it's not self-modifying, or no changes are made to the array?

If memory serves, the bytecode can be modified before execution to replace opcodes by code pointers into the interpreter (the so-called indirect threaded code technique).

**Pull request merged**
