### PR TITLE
List.map_{option,result}

### PR DESCRIPTION
**Pull request by gasche**
```
val List.map_opt : ('a -> 'b option) -> 'a list -> 'b list option
val List.map_result : ('a -> ('b, 'e) result) -> 'a list -> ('b list, 'e) result
```

(both are tail-recursive)

### CODE REVIEW

**Comment by dbuenzli** [comment]
Just reading the name and the signature: confused. Seems a bit ad-hoc. What's your use case ? (E.g. often I want to report as much errors as possible, not just the first one).

**Comment by xvw** [comment]
I think these to be two useful functions but, from an outside point of view, I find that their names are not particularly clear. Even if being prefixed by the module (and helping with the signature) we can easily understand the behavior of functions. Naively `map_opt` and` map_result` reminds me:
`('a -> 'b) -> 'a (option | result) -> 'b (option | result)`. I am not aware of the naming conventions for this kind of functions in the Stdlib but what do you think of `travserse_XXX`?

**Comment by gasche** [comment]
> (E.g. often I want to report as much errors as possible, not just the first one).

This is what `partition_map_result` or `partition_result` would do. (I need to go update that PR.)

> what do you think of `traverse_XXX`?

I'm happy with `traverse_*`, which is the Haskell terminology, if there is a consensus that people prefer this over `map_*`. I think that `map_*` also makes sense because those are instances of `mapM`.

**Comment by craigfe** [comment]
- > I think that `map_*` also makes sense because those are instances of `mapM`.

  Personally, this makes much more sense in Haskell since `fmap` is named separately. I agree with  @xvw that `map_` in OCaml makes me think of functors and not traversables. Additionally, the `List.map` documentation does not guarantee a traversal order (and my impression is that this is quite deliberate). :+1: for `traverse_` in favour of `map_`.

- I think `map_opt` might be the first function in the Stdlib to _not_ follow the pattern of being an exception-less variant of `map`. I wonder if `_option` is the more appropriate suffix for this reason. See for instance `Format.pp_print_option` and `Result.to_option`.

- I think these operations are equally applicable to arrays and, to a lesser extent, sets.

**Comment by gasche** [comment]
> Additionally, the List.map documentation does not guarantee a traversal order (and my impression is that this is quite deliberate). 

I don't think it is deliberate, we have specified orders in later functions (List.init for example), and the implementation deliberately implements a left-to-right traversal.

> I think map_opt might be the first function in the Stdlib to not follow the pattern of being an exception-less variant of map. I wonder if _option is the more appropriate suffix for this reason.

Excellent point, `_option` it will be.

>  these operations are equally applicable to arrays and, to a lesser extent, sets.

I prefer to focus on the datastructure(s) for which I saw an actual need, instead of trying to define everything at once.

Note: an alternative option would be to have them in `Option` and `Result` instead of `List`:

```
val Option.sequence_list : 'a option list -> 'a list option
val Result.sequence_list : ('a, 'e) result list -> ('a list, 'e) result
```

But I think that this would be the wrong choice. We can assume that Option and Result (and lists) are "basic datatypes" that everyone knows about and is allowed to depend on. On the other hand, we cannot have `sequence_foo` in Option for all data structures `foo` (extensible arrays, hashtables, etc.) as this would create cyclic dependencies. So each datastructure module could have a sequence/traverse function, instead of trying to push them in Option/Result.

**Comment by gasche** [comment]
I started changing the patch to use `traverse_{option,result}`, but that convinced me that personally I prefer `map_{option,result}`, so I kept it in the end. (We will see if there is deciding feedback either way coming later.) In the OCaml world, `List.map` is an effectful map, not a pure map (in particular, we do not have `map (f . g) = map f . map g` due to the importance of traversal order), and those functions are natural extensions of the existing `map` function.

@dbuenzli the use-case is to change code that currently looks as follows:

```
match List.map f xs with
| exception Blarg -> ...
| ys -> ...
```

to not use exceptions anymore.

**Comment by lpw25** [comment]
I have given this idea at most 5 seconds thought, but is `map_option` perhaps `forall_map`?

**Comment by gasche** [comment]
Yes, and `exists_map` is `find_map`. In both cases I think that the quantifier-based naming would make it harder for others to find/discover.

**Comment by dbuenzli** [comment]
@gasche ok thanks for the use case. Oddly enough I don't think I ever felt the need for that -- I may be constantly encoding this as recursive loops though (I don't know).

> In both cases I think that the quantifier-based naming would make it harder for others to find/discover.

I think @lpw25's idea should be worth pondering. I find the `map_{option,result}` non obvious to *read* which is what interests us. Maybe in the haskell world `mapM` is "odd" enough to read that you end up learning it, what you propose has not this property (e.g. I could read this as map a list of options/results).

**Comment by gasche** [comment]
One other difficulty for `forall_map` is that it is a one-shot: we only get to use it for `option`, or for `result`, but not both. Existing `foo_map` functions use `option`, because they do not carry additional information in the non-`'a` case (one exception would be my `partition_map` proposal), and there is no established pattern of using `result` there, but note that for `forall` it is strictly more expressive to use `result` than `option`, because we may want to pass information in the failure case (in my example: whenever the exception has a parameter). So:
- it's not completely clear which type to use
- there is no established naming pattern to signal which one we use, or make several ones available

Remark: the symmetrical situation (for `exists` rather than `forall`, with shortcutting behavior but rich failure handling) would be to have `exists_map : ('a -> ('b, 'e) result) -> 'a list -> ('b, 'e list) result`; this is an instance of `map_result` with the two result parameters swapped.

**Comment by Drup** [comment]
The most common name for `map_option` that I have seen in practice is `filter_map`, and it is indeed very useful. The result version is far less useful since it's trivially obtained via `Result.to_option`, but it's okay. If we have both, @gasche's name choices sound good.

Can we have the same ones in `seq` ?

**Comment by gasche** [comment]
@Drup wait, for me `filter_map` is `('a -> 'b option) -> 'a list -> 'b list`, it always return a result list by dropping elements that map to `None`. This is not what the function proposed above do.

I don't think that the `result` version can be trivially obtained from the `option` one, it's rather the other way around (the result option carries more information, but you can define the option one by coercing in and out of `('a,  unit) result`).

**Comment by gasche** [comment]
In particular, the `map_*` functions proposed above do not make much sense in `Seq`, because they would require forcing the input sequence to produce any output.

Edit: actually that could be an argument in favor of the `traverse_*` terminology, which makes this point more explicit.

**Comment by Drup** [comment]
Oh, you're right, I read the type too fast. Well, then I'm also not extremely convinced by their usefulness.

**Comment by gasche** [comment]
Currently there is no consensus that other people than myself and @xvw  would find these functions useful, despite the [proposed use-case](https://github.com/ocaml/ocaml/pull/9630#issuecomment-638976256). (It may be easier to convince people by having the use-case in the first message, but I actually like the presentation where people have to guess what the function does from the type, which is a good way to kill more proposals.)

If someone else would actually like to have those functions in, they should make it known sooner rather than later; otherwise eventually the PR will die, and be closed by lack of consensus.

**Comment by lthls** [comment]
There's one related function in `utils/misc.ml`, named `some_if_all_elements_are_some` (but without the mapping function). You could use this as an example of use case.

**Comment by Octachron** [comment]
I think that having a `map_option` function might be useful to offer a practical alternative to an exception based control flow. I am not convinced by the name `map_option` which seems hard to decipher without going through Haskell documentation and doesn't follow the pattern of `map`, `find_map`, `filter_map`. And if the main advantage is the possibility to cater to both option and result, could we simply duplicate `forall_map` into `forall_map` and `forall_map_result` or `forall_map_with_error`?

**Comment by nojb** [comment]
Just to try to move the discussion forward, what about having a submodule `Option.List`, `Result.List` where the function `map` (or some other name) would live ?

**Comment by gasche** [comment]
This PR is dead, let's close it and move on.

**Pull request closed without merging**
