### PR TITLE
Move depend.ml into compilerlibs (ocamlcommon).

### PR DESCRIPTION
**Pull request by alainfrisch**
This allows external tools to rely on the features provided by this module.  An example
is ocamldoc itself, which could now be implemented as an external tool.

Note that LexiFi's variant of OCaml has been embedding depend.ml in the compiler for a long
time in order to support a stricter dependency mode where the compiler is only allowed to load .cmi
files corresponding to dependencies as inferred by ocamldep (hereby ensuring that ocamldep is
sound by construction).

This could also be seen as a first step towards supporting ocamldep features directly from ocamlc/ocamlopt (as a subcommand). This could be interesting in particular because one could always rely on boot/ocamlc to compute dependencies.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Would be nice to document the `.mli`.

**Comment by alainfrisch** [comment]
Documenting would be nice, but since I haven't looked at the alias stuff, I won't do it myself.  Anyway, this can be done after the change suggested here.

Anyone opposed to merging this PR?

**Comment by dbuenzli** [comment]
> Anyone opposed to merging this PR?

I am since it adds one more undocumented API to compiler libs. 

> Anyway, this can be done after the change suggested here.

One can dream... Documentation is a design strategy, not an afterthought.

**Comment by alainfrisch** [comment]
What a lame argument, and an insult to people who contributed documentation to modules that were part of the compiler-libs for a long time.

Anyone else opposed to the proposed change?

**Comment by dbuenzli** [comment]
> What a lame argument, and an insult to people who contributed documentation to modules that were part of the compiler-libs for a long time.

If you feel insulted by this then I'm sorry there's not much I can do for you. Speaking of lame arguments, you should check out yours for justifying the act of not documenting the API: basically it means you are exposing functionality you don't understand yourself which can only lead to API design disaster.

**Pull request merged**
