### PR TITLE
Faster test suite

### PR DESCRIPTION
**Pull request by xavierleroy**
The test suite takes significant time to run.  This is annoying when testing on small devices (Raspberry Pi) or, even worse, using emulators (QEMU).  

This pull request reduces the running time of the test suite by
- Simplifying some tests that were initially designed as benchmarks, e.g. misc-kb.  For benchmarking purposes, the test was repeated several times.  A single run is enough for testing purposes.
- Reducing the size of the data sets for some other tests.

With the proposed changes, almost every test run in 1 second or less (in bytecode as well as in native code) on a modern PC.  The exception is tests/lib-threads, which still takes a long time (about 1 minute), and needs to be redesigned and rewritten.

### CODE REVIEW

**Comment by gasche** [comment]
On my machine, the testsuite before this patch takes about 3m30s to run (when already hot), while after the patch it only takes 2m20s. For reference, `make world.opt -j5` from a clean state takes 1m11s. I'm in favor of this change, as running the testsuite can be a bottleneck of my merge-rebase-test-commit cycle during pull request integration work.

(Eventually we'll want to be able to run some of the tests in parallel to further gain speed on beefy machines, but this requires a more invasive redesign of the testsuite scripts. `make clean` is also much slower than necessary due to the recursive make profusion.)

**Comment by xavierleroy** [comment]
The latest commits revise tests/lib-threads so that it takes less time (30 secs instead of 1 minute) and (one can hope) is more reliable (less sensitive to timing effects).  Not tested under Windows, however.

**Comment by gerdstolpmann** [comment]
fyi, I was also working on the test suite, in particular I want to support cross-compile targets. The idea is to compile all tests into a single binary that is started as a TCP server on the device. The compilation and scripting still takes place on the host. So far it mostly works by providing additional Makefile targets. It's not yet finished, but one of the problems is that there are too many special tests (i.e. neither using Makefile.several or Makefile.one). If that could be improved this would be great.

Find my work here: https://github.com/gerdstolpmann/ocaml/tree/gs-4.02.3%2Bios%2Btestsuite/testsuite

**Comment by gasche** [comment]
@xavierleroy , do you plan to merge this in trunk eventually? I've been doing my stuff-to-merge testing on top of this branch, and it would be convenient to have this directly in trunk because there are small conflicts ( against the french comment translation work, which changed stuff in `tests/threads` ).

If you think the current state is mergeable I can do it this week-end, with the other easy PRs.

**Comment by damiendoligez** [comment]
Tested on MSVC-32 and mingw-64. OK for merging.

**Comment by damiendoligez** [comment]
Merged (rev 16466).

**Pull request closed without merging**
