### PR TITLE
Reorganize release information

### PR DESCRIPTION
**Pull request by Octachron**
This PR proposes to reorganize the information in release-checklist in order to make it more discoverable following @shindere suggestion during the last beta release process.

More precisely, this PR creates a new repository containing the current release how-to, separate template files for the beta, rc, and production announce, and and an updated of @gasche's "Changes to markdown" script .

cc @shindere and @damiendoligez

### CODE REVIEW

**Review by damiendoligez — APPROVED** [review]
Looks very good to me.

**Comment by shindere** [comment]
Many thanks for having accepted to work on this, @Octachron.

It's all good to me, feel free to merge whenever you like.

What I can see:

"# check that dependencies are fine"

I'd suggest to uppercase the initial C and to replace "fine" by
"up-to-date"

And perhaps "the dependencies" rather than jsut dependencies.

"# Check that the the stored dependencies are up-to-date": doubled word

And perhaps one could merge the two dependencies-related steps into one?

"# check-typo": you may wnat to add a verb, like "Run the thcck-typo
scrpt".

"Clone the opam-repository.": you could include the command, or at least
the URL, especially given that you do it afterwards.

"You can test the new opam package before sending a PR to the +main
ocaml-repository": you meant opam-repository, didn't you?

"## 13: announce the release on caml-list, caml-announce, and discuss.":
at least in french, you wouldn't put a comma just before an "and".

"See the email announce templates at the end of this file.": I believe
this should be updated to reflect the new locations of templates, right?

**Comment by johnwhitington** [comment]
This document does not mention the `News' file.

This file has, however, not been updated for 4.08, 4.09, or 4.10. Should it be removed? Or at least should it have a note at the top pointing readers to the `Changes' file instead?

**Comment by Octachron** [comment]
The `News` file has been forgotten and was only actively maintained between July and October 2018.
We should either remove it or update it.
I think that removing it might be the best option, but maybe @gasche has some arguments to keep it?

**Comment by Octachron** [comment]
@shindere ,  thanks for your review. I have updated the PR accordingly (the comma after the penultimate item of an enumeration is a standard Oxford comma).

**Comment by shindere** [comment]
Thanks a lot, @Octachron! I fully trust you on the comma business!
Since the PR has already been formally approved, I won't bother
approving it once more but feel free to merge whenever you like!

**Comment by gasche** [comment]
The idea of the News file was to collect somewhere permanent the "highlights of the release" information that were spread through emails. I think it's a good idea to keep this information somewhere (if only for its historical value), but it doesn't need regular maintenance (updating it every 5 years is fine) and it could go in a less visible place than `News`, for example in your new subdirectory. (We could also add it to the Changes entry in the forefront of each released-version changelog, but that would make that file even longer and slightly more redundant.)

**Comment by Octachron** [comment]
I am moving `News` to the new `release-info` directory. Let's see if it knows more success in this new place.

**Comment by xavierleroy** [comment]
> The idea of the News file was to collect somewhere permanent the "highlights of the release" information that were spread through emails. I think it's a good idea to keep this information somewhere (if only for its historical value), but it doesn't need regular maintenance (updating it every 5 years is fine)

Short reply: no, it is not fine.

Longer reply: every release comes with a short list of highlights, see e.g. https://github.com/ocaml/ocaml/releases .  This is useful information but only if it is timely and provided at the time of the release.  Either this information is transcribed in the "News" file before the release (not 5 years after, please), or the "News" file is useless and should be removed.

**Comment by gasche** [comment]
If you have an issue with the idea that users would encounter the News file (which is strange giving that it was sitting here all this time and, essentially, nobody noticed), then moving them to a less public place as @Octachron fixes this issue. If this is just a subtle trick into forcing me to refresh the file right now, it's working.

**Comment by shindere** [comment]
Before the Changes file became so big, it seems to me it was exactly
the News file we are discussing now.

At that time things were so much simpler it feel and less bureaucratic.

I'm really wondering what exactly it is that we have gained with the
Changes file the way it is right now.

**Comment by shindere** [comment]
Gabriel Scherer (2020/07/10 12:21 -0700):
> If you have an issue with the idea that users would encounter the News
> file (which is strange giving that it was sitting here all this time
> and, essentially, nobody noticed), then moving them to a less public
> place as @Octachron fixes this issue. If this is just a subtle trick
> into forcing me to refresh the file right now, it's working.

But you broke Inria's extra-checks job, probably becuase of check-typos.
You may want to enable David's pre-commit hook to aovid such problems
int hte future.

**Comment by Octachron** [comment]
One of the advantage of the current exhaustiveness of Change files is traceability: if you observe a change of behavior in the compiler between versions, you can track it down to a precise item in the Change log. (even if the item identification might be tricky).

**Pull request merged**
