### PR TITLE
Keep general types of Printf.{ifprintf,ikfprintf}

### PR DESCRIPTION
**Pull request by zoggy**
For PR#6904 http://caml.inria.fr/mantis/view.php?id=6904

### CODE REVIEW

**Comment by gasche** [comment]
I think those signatures would be more readable with `('a, 'b, 'c, 'd) format4` than `('c, 'a, 'b, 'd) format4`, but as it applies to all the functions in this module it could be a separate patch.

**Comment by zoggy** [comment]
I reordered all type variables in all functions, as you suggest.

**Comment by gasche** [comment]
Thanks! This is mergeable as far as I'm concerned.

**Comment by gasche** [comment]
Merged in trunk. Thanks for the patch.

**Pull request closed without merging**
