### PR TITLE
Enable native code on FreeBSD/aarch64

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Same as https://github.com/ocaml/ocaml/pull/11092 but for FreeBSD

### CODE REVIEW

**Review by avsm — APPROVED** [review]
Looks good. This doesn't need a Changes entry I think, since FreeBSD/aarch64 was supported pre-multicore merge. It makes the changelog inaccurate if added since it makes it look like a new 5.0 feature.

**Comment by gasche** [comment]
I'm not sure while this waited so long, apologies for this (and to @VoxSciurorum who redid the work in #11459.) @kit-ty-kate, I think this is good to go, could you fix the conflicts?

**Comment by kit-ty-kate** [comment]
I just fixed the conflict and removed the entry to the changelog per @avsm’s comment

**Comment by gasche** [comment]
Merged, thanks! Apologies for letting this PR slip by.

**Comment by avsm** [comment]
Can this be cherry picked into the 5.0 branch? Otherwise it’ll need a Changes entry for 5.1 (as 5.0 won’t have had this arch)

**Comment by gasche** [comment]
Sure, I cherry-picked in 5.0 at 6a95faa9e4a97007c8433f6e78bbfa6350e49dd6.

**Comment by kit-ty-kate** [comment]
@gasche the commit you linked does not belong to any branches it seems.
Github notes:
```
This commit does not belong to any branch on this repository,
and may belong to a fork outside of the repository.
```

**Pull request merged**
