### PR TITLE
Make caml-mode an independent project

### PR DESCRIPTION
**Pull request by Chris00**
This was requested by Gabriel Scherer:
https://github.com/ocaml/ocaml/pull/2078#issuecomment-443322613
Independent version: https://github.com/Chris00/caml-mode

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm always in favor of moving stuff out of the core distribution :-)

I think the standalone repository deserves to be hosted by the ocaml/ organization on Github.  An opinion from @agarwal, @amirmc, @avsm, @samoht ?

Whatever we end up doing, just make sure to notify the maintainers of the MELPA package (https://melpa.org/#/caml).

**Comment by gasche** [comment]
I would like to clarify that this is not a "request", in the sense that it's perfectly okay for @Chris00 to say no, that he doesn't want to take this responsibility. Then the code would probably stay in the upstream distribution as today -- and we would probably be asking him if he's willing to do reviews when we need them, as today. It was more of an invitation of my part, although indeed an invitation to perform some work.

**Comment by gasche** [comment]
@Chris00 the change seems fine to me, would you add a Changes entry?

**Comment by Chris00** [comment]
@gasche Changes entry added.

**Review by gasche — APPROVED** [review]
Good to merge once the CI passes. @Chris00, thanks!

**Comment by avsm** [comment]
Just catching up on my messages -- it would of course be fine to create a new repository on `ocaml/` for this.  Please ping me if I can do so @Chris00!

**Comment by Chris00** [comment]
@avsm Please do!

**Comment by avsm** [comment]
Sure, what should the repository be called? And is there any connection to [ocaml/tuareg](https://github.com/ocaml/tuareg]?  As a non-emacs user, I only have the faintest idea what all this lisp is doing :-)

**Comment by avsm** [comment]
(Note: we could call it caml-mode, but I thought that something with "emacs" in the repository title might be clearer)

**Comment by nojb** [comment]
`caml-mode` is standard; e.g. https://github.com/haskell/haskell-mode

**Comment by avsm** [comment]
Sounds good. I'll create a caml-mode repository for now with @Chris00 and the caml-dev teams having merge rights.

**Comment by avsm** [comment]
This has now been setup in https://github.com/ocaml/caml-mode with the same privs as the tuareg repository. Let me know if that needs to be changed.

**Comment by andyleejordan** [comment]
@avsm @Chris00 I updated Melpa in https://github.com/melpa/melpa/pull/5966

**Comment by Chris00** [comment]
@andschwa Thanks.  If you have time to test further and some points in the checklist do not pass, do not hesitate to open issues for caml-mode.

**Comment by andyleejordan** [comment]
@Chris00 MELPA fix is merged 😄

**Pull request merged**
