### PR TITLE
Add an explicit afl-fuzz test

### PR DESCRIPTION
**Pull request by jmid**
This PR adds a simple, explicit test of `afl-run` which is run with a timeout - following up on #10888

The fuzzed program is a reduced variant of the readline-example from the manual which `afl-fuzz` has no problem breaking in 30 secs.

I renamed the existing afl-showmap accordingly. They each test for different aspects.

Things to consider:
- Is `timeout` available on all architectures where we support `-afl-instrument`? (input to make it more portable is welcome)
- This adds 30 secs to a testsuite run! In https://github.com/google/AFL/blob/master/docs/env_variables.txt 
   I learned of `AFL_BENCH_UNTIL_CRASH=1` for an early exit. We would probably still need a timeout to ensure that it always stops, e.g., if broken instrumentation somehow makes it hard to find the crash.
   Pro: That would cut down the 30 secs on a common path.
   Con: The test would be further from the common end-user scenario
- The 30 secs just has to leave time to find a crash. This naturally varies with machine strength.
  It is plenty sufficient on my old Thinkpad - and I would suspect so generally (again: input welcome).

### CODE REVIEW

**Comment by gasche** [comment]
A few remarks:
- yes, the early exit, with the timeout just for protection in broken scenarios, sounds like a good idea
- can't we trivially make the test shorter by changing the needle in the haystack from `cam` to `ca` or just `c`?
- if we are testing that afl works correctly (so the instrumentation is correct) and does something, I think that neither the early-exit nor a slightly easier test are issues. But what is it that we want to test here?

(Do we also check stability? There have been fixes in the compiler runtime to improve afl-fuzz stability, maybe it would make sense to check that it is 100% here?)

**Comment by kayceesrk** [comment]
> can't we trivially make the test shorter by changing the needle in the haystack from cam to cam or just c?

I agree with this. It would be sufficient if the set-up finds the trivial example. 

> But what is it that we want to test here?

To ensure that this case is caught: https://github.com/ocaml/ocaml/pull/10888#issuecomment-1012341986

**Review by gasche — APPROVED** [review]
I understand that the test was now reduced to take only 1s. All looks good to me, so here is an approval stamp.

Note: the test is skipped automatically if `afl-fuzz` is not available. We could fail to notice a regression (say on CI systems) if we forget to install `afl-fuzz` on our test systems.

Note: our check-typo tool complains about a Major Programming Mistake, to be fixed before this is actually mergeable:

> ./testsuite/tests/afl-instrumentation/afl-fuzz-test.ml:10.30: [tab] TAB character(s)

**Comment by jmid** [comment]
OK. I've cut down the timeout to 1s by following @gasche's suggestion of making the needle easier to find.
This is still intended as a conservative upper bound on the needed time
(on my old machine at around 0.15s I encounter both successful and unsuccessful runs).
 
> if we are testing that afl works correctly (so the instrumentation is correct) and does something, I think that neither the early-exit nor a slightly easier test are issues. But what is it that we want to test here?

I agree that the existing tests check the instrumentation for correctness.
This is done with `afl-showmap` which executes a single instrumented run and prints its branch info IIRC. 
Since `afl-showmap` doesn't use the fork-server mode the existing afl-tests do not exercise `caml_setup_afl` below line 113:
  https://github.com/ocaml/ocaml/blob/ade6577539477d165bb4cf1cf7186031d54ba188/runtime/afl.c#L110-L114
which caused the fork-server handshake code to break undetected.

This explicit `afl-fuzz` test intends to remedy this situation.
See https://lcamtuf.blogspot.com/2014/10/fuzzing-binaries-without-execve.html for a description of the tested "afl protocol".

> (Do we also check stability? There have been fixes in the compiler runtime to improve afl-fuzz stability, maybe it would make sense to check that it is 100% here?)

No, I don't believe we check stability in either of the afl-tests.
BTW, I found a description of the stability metric here: https://github.com/google/AFL/blob/61037103ae3722c8060ff7082994836a794f978e/docs/status_screen.txt#L303
```
That last bit is actually fairly interesting: it measures the consistency of
observed traces. If a program always behaves the same for the same input data,
it will earn a score of 100%. When the value is lower but still shown in purple,
the fuzzing process is unlikely to be negatively affected. If it goes into red,
you may be in trouble, since AFL will have difficulty discerning between
meaningful and "phantom" effects of tweaking the input file.
```

It would definitely be useful, but I think tests for this should be considered in a separate issue/PR.

**Comment by jmid** [comment]
> Note: our check-typo tool complains about a Major Programming Mistake, to be fixed before this is actually mergeable:
>>    ./testsuite/tests/afl-instrumentation/afl-fuzz-test.ml:10.30: [tab] TAB character(s)

Oops. Sorry should be fixed now.

**Comment by jmid** [comment]
> Note: the test is skipped automatically if `afl-fuzz` is not available. We could fail to notice a regression (say on CI systems) if we forget to install `afl-fuzz` on our test systems.

Ah, good point! For `afl-fuzz` I just went with mirroring what was done for `afl-showmap`.

I'm unsure what the best solution would be here though.
For a compiler developer running the test-suite locally, I'm not sure we would want to make these external tools a dependency.
However in a CI we want to ensure that `afl-fuzz` and `afl-showmap` are installed so that we actually run the afl tests.

**Comment by gasche** [comment]
I don't think there is a good solution to this issue of forgetting to install afl-fuzz to test this.
Better documentation would help; ideally `testsuite/HACKING.adoc` would provide an overview of which tests are conditionally enabled and why, so that CI people can decide what they want to install on their test setups. (Is it, a short summary of skipping conditions, something that you might be interested in doing as another PR? Well maybe we should wait a bit that the multicore merging dust settles and we have a clearer vision of what is supported in upcoming OCaml relases.)

Regarding the choice of timeout: we want to avoid probabilistic failures where the CI fails every 10^4 run. Are we reasonably sure that 1s is enough? If not, maybe we could use a longer timeout (10s, 30s as before) provided that we also enable early termination. (Do I currently understand that your test code currently does not ask for early termination when a crash is found?). Then we get a very low expected runtime, but a Really Small probability of having the test fail due to just bad luck. (This could also be more robust to testing on slower machines, for example machines where "fork" is emulated and 100x slower.)

**Comment by xavierleroy** [comment]
Some CI configurations have afl-fuzz installed (that's how I found the problem!) and most do not, and that's just fine this way.  Please don't demand AFL to be installed before the test suite can be run.

**Comment by jmid** [comment]
> Regarding the choice of timeout: we want to avoid probabilistic failures where the CI fails every 10^4 run. Are we reasonably sure that 1s is enough? If not, maybe we could use a longer timeout (10s, 30s as before) provided that we also enable early termination. (Do I currently understand that your test code currently does not ask for early termination when a crash is found?). Then we get a very low expected runtime, but a Really Small probability of having the test fail due to just bad luck. (This could also be more robust to testing on slower machines, for example machines where "fork" is emulated and 100x slower.)

Yes, the test is non-deterministic - and will fail with a really small probability.
I considered the 1s conservative because it is over 6x the time to find the trivial needle on my old laptop.
With such a low timeout I saw less need for `AFL_BENCH_UNTIL_CRASH=1`.

At the bottom of 
https://github.com/google/AFL/blob/61037103ae3722c8060ff7082994836a794f978e/docs/status_screen.txt#L376 I've now found out that these statistics are also written to a `readline-output/fuzzer_stats` file.

I've just committed a version that instead uses that file and triggers an early exit with  `AFL_BENCH_UNTIL_CRASH=1`.
Here's a sample copy of the file from one such run:
```
start_time        : 1642699909
last_update       : 1642699909
fuzzer_pid        : 2442659
cycles_done       : 0
execs_done        : 489
execs_per_sec     : 750.00
paths_total       : 9
paths_favored     : 1
paths_found       : 8
paths_imported    : 0
max_depth         : 2
cur_path          : 0
pending_favs      : 1
pending_total     : 9
variable_paths    : 0
stability         : 100.00%
bitmap_cvg        : 0.00%
unique_crashes    : 1
unique_hangs      : 0
last_path         : 1642699909
last_crash        : 1642699909
last_hang         : 0
execs_since_crash : 402
exec_timeout      : 20
afl_banner        : readline
afl_version       : 2.52b
target_mode       : default
command_line      : afl-fuzz -m none -i readline-input -o readline-output ./readline
```

So
- even with `AFL_BENCH_UNTIL_CRASH=1` afl-fuzz continues for 402 readline executions despite finding the crash after 489 - 402 = 87
- It also reports 100% stability of the test 🙂

Here's the timing of 5 consecutive executions of  ./afl-fuzz-test.run on my old Thinkpad:
```
real	0m0.368s
user	0m0.019s
sys	0m0.019s

real	0m0.362s
user	0m0.011s
sys	0m0.028s

real	0m0.394s
user	0m0.019s
sys	0m0.022s

real	0m0.347s
user	0m0.022s
sys	0m0.017s

real	0m0.363s
user	0m0.014s
sys	0m0.024s
```
so this is fast and a 10s timeout should be plenty.

**Comment by damiendoligez** [comment]
@gasche do we want a Changes entry for this PR?

**Comment by gasche** [comment]
I understand this as encouragement to merge the PR. Let's do it.
I do think that the general work of @jmid on taking care of AFL after the multicore merge would deserve crediting in the changes.

**Comment by gasche** [comment]
I pushed a Changes entry in a72c499f382e6ae8feaba7999769b7fcbaca7c87.

**Pull request merged**
