### PR TITLE
add a regression test for issue 9460

### PR DESCRIPTION
**Pull request by gasche**
This is a regression test for #9460 (contributed by Richard Jones).
We currently expect this test to fail on 32bit systems, and succeed on 64bits systems.

I am sending it as a PR so that we can get CI testing (should confirm that we observe the failure on our CI machines), and also to help whoever is going to write the fix.

### CODE REVIEW

**Comment by rwmjones** [comment]
Will the github CI tests try this on i686?  (I'm currently trying to get an i686 container or VM up so I can test the regression test.)

**Comment by xavierleroy** [comment]
Yes, the Travis CI runs in 32 and 64 bits, and you can already see the failure in 32 bits.

**Comment by rwmjones** [comment]
Indeed it does.  The system works!

**Comment by gasche** [comment]
This PR is now superseded by #9463 which includes the test, closing (now that we were heart-warmed by our continuous robot friends).

**Pull request closed without merging**
