### PR TITLE
Simplify the range of values used for `Config.system`

### LINKED ISSUE #10613: Get the `system` variable to be consistent
Currently, in OCaml code in the wild, people use the output of `ocamlc -config` to detect the architecture and OS of the system they are on.

However while debugging https://github.com/janestreet/core/issues/145 I discovered that the variable `system`, in particular, is not consistent and does not always return "linux" on linux systems for example.

This pattern of using the `system` variable to detect the OS is especially prevalent in dune where there is no other builtin way to get this information (see https://github.com/ocaml/dune/issues/4895).

In addition of fixing dune and other build systems with similar issues (I believe `oasis`, back in the days, also used the `system` variable: https://github.com/ocaml/oasis/blob/master/setup.ml#L4133), I think it would be nice to make the variable more consistent. e.g.
* regroup all the linux variants as `linux`
* regroup `bsd_elf` and `bsd` as `bsd`
* regroup all the openbsd variants as `openbsd` (currently it's split between `bsd` and `openbsd` depending on the architecture)
* regroup `win32` and `win64` into one (not sure which name it should have, but having the `system` variable carry the same information as the `architecture` variable doesn't seem right to me)
* same for `mingw` and `mingw64` (cc @dra27 who probably has ideas about windows)

See https://github.com/ocaml/ocaml/blob/12523517cf5c6c782563f8b76e661b67748e010b/configure.ac#L1044-L1132 for the list of current possible values of `system`

### PR DESCRIPTION
**Pull request by dra27**
As @kit-ty-kate notes in #10613, the values used for `Config.system` (and displayed in `ocamlopt -config`) are quite inconsistent. At the time (in 2021), that felt a too bit tricky to address, but I've had cause to be looking at this as part of something else and I think two important things have changed:
1. Most of the affected systems are 32-bit, and therefore do not have native compilers in 5.x (and won't).
2. The use of OCaml stacks has vastly simplified the signal and C stack processing code, which is where most of these values were used.

Note that since #10044, `ocamlc -config` displays the detected values for `architecture`, `model` and `system` even when the native code compiler is not built.

This PR proposes:
- Using `system=linux` for all Linux variants, in particular:
  - ppc64 and s390x use it instead of `system=elf` (@Octachron - given that s390x is only being restored to full native support in 5.1, might this commit be suitable for 5.1?)
  - x86_32 uses it instead of `linux_elf`
  - aarch32 in all its forms uses it instead of `linux_eabi` / `linux_eabihf`. The `eabi`/`eabihf` is now preserved in a new `Config.abi` (`abi:` in `ocamlc -config`). **NB** We don't use this (or `SYS_linux_eabi` / `SYS_linux_eabihf`) in the runtime, which uses ARM's own C preprocessor defines.
- FreeBSD, NetBSD and OpenBSD now always have `system=freebsd`, `system=netbsd` or `system=openbsd` as appropriate; in particular:
  - aarch32 on OpenBSD no longer reports `system=bsd`, but `system=openbsd` (as aarch64 and x86_64 already did)
  - x86_32 no longer reports `system=bsd` for everything matching `*bsd` (very pedantically, this means that a system matching `*bsd` but not matching `freebsd*|netbsd*|openbsd*` now reports `unknown` for `system` (and `none` for architecture), but remember that these are bytecode only systems)

That implements the suggestions in #10613, apart from the `bsd` and Windows ones. I'd prefer to leave the Windows ones as they are - the biggest inconsistency before was that both Cygwin and Cygwin64 reported `system=cygwin`, but the world has made that easy for us by eliminating 32-bit Cygwin completely. Apart from worrying about how many years it would take to remember the changed values, a more practical reason for leaving them be is that they _are_ used in the compiler's codebase, and elsewhere - all the other values I'm changing here affect largely retired systems and the values themselves are not used at all in the compiler's codebase anymore.

This then gives us:

| `system:` | OS (and possible `architecture:` values)
|      ---: | :---
|      beos | [Haiku](https://www.haiku-os.org); `amd64`, `i386`
|    cygwin | [Cygwin](https://www.cygwin.com); `amd64`, `i386`[^1]
| dragonfly | [DragonFly BSD](https://www.dragonflybsd.org); `amd64`
|   freebsd | [FreeBSD](https://www.freebsd.org); `amd64`, `arm64`, `arm`, `i386`
|       gnu | [GNU Operating System](https://gnu.org) using [GNU Hurd](https://www.gnu.org/software/hurd); `amd64`, `i386`
|     linux | [Linux](https://kernel.org); `amd64`, `arm64`, `arm`, `i386`, `power`, `riscv`, `s390x`
|    macosx | [macOS](https://www.apple.com/macos); `amd64`, `arm64`
|     mingw | [Microsoft Windows](https://www.microsoft.com/windows), [mingw-w64 32-bit GCC](https://www.mingw-w64.org); `i386`
|   mingw64 | [Microsoft Windows](https://www.microsoft.com/windows), [mingw-w64 64-bit GCC](https://www.mingw-w64.org); `amd64`
|    netbsd | [NetBSD](https://www.netbsd.org); `amd64`, `arm64`, `arm`, `i386`
|   openbsd | [OpenBSD](https://www.openbsd.org); `amd64`, `arm64`, `arm`, `i386`
|   solaris | [Solaris](https://www.oracle.com/solaris/solaris11); `amd64`
|     win32 | [Microsoft Windows](https://www.microsoft.com/windows), [Microsoft Visual Studio x86 (32-bit)](https://visualstudio.microsoft.com); `i386`
|     win64 | [Microsoft Windows](https://www.microsoft.com/windows), [Microsoft Visual Studio x64 (64-bit)](https://visualstudio.microsoft.com); `amd64`
|   unknown | Everthing else; `none`
-----------------

[^1]: the x86 version of Cygwin [was retired in 2022](https://cygwin.com/pipermail/cygwin-announce/2022-November/010777.html)

### CODE REVIEW

**Comment by shindere** [comment]
The code is very well shaped as usually and the change does look very
reasonable to me.

Given that `abi` does get kind of an official status, shouldn't its
documentation be made slightly more precise and explain what ABI we are
talking about?

**Comment by xavierleroy** [comment]
I would suggest to not bother with `Config.abi`: it matters only for native-code compilation for ARM 32 bits, which is no longer supported in OCaml 5.  Moreover, most ARM systems use the "hard float" ABI these days, the "soft float" ABI being a relic of a past when ARM chips did not have VFP hardware support.

**Comment by dra27** [comment]
`Config.abi` gone, with the nice side-effect that the PR only changes the configure-time constants. I've used a mix of the wonderful [Sherlocode](https://sherlocode.com/) and [opam-grep](https://github.com/kit-ty-kate/opam-grep) tools to go through opam-repository. I couldn't find anything that would be broken by this change (apart from a couple of tests in OASIS...).

**Comment by dra27** [comment]
As an aside, I spotted that a possible i386 BSD which would have been matched before and isn't here is Debian GNU/kFreeBSD. I was tempted to make the i386 FreeBSD case `*freebsd*`, therefore, except that the last release of kFreeBSD is long-expired (Debian 8) and we never handled the amd64 version of it anyway.

**Comment by glondu** [comment]
https://lists.debian.org/debian-devel/2023/07/msg00176.html

**Review by xavierleroy — APPROVED** [review]
This looks like a useful clean-up and simplification.  The amount of breakage in OPAM packages seems manageable.  I think it's better to merge now than let this PR bit-rot.

**Comment by dra27** [comment]
Thank you!

**Pull request merged**
