### PR TITLE
fix doc comment for unit type

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

Currently [the doc](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Stdlib.Unit.html) is broken. This should fix it.

Cheers.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Looks good. How could we find the other instances of this issue ?(which is really us being bitten by a hard-to-fix ocamldoc usability issue)

**Comment by Octachron** [comment]
There is another instance of the issue with [Seq.t](https://caml.inria.fr/pub/docs/manual-ocaml-4.10/libref/Seq.html). To avoid it, we could check (with an external tool?) that there are no variant type declarations with only one documentation comment on its last constructor.

**Comment by redianthus** [comment]
We could just grep for `(*` in the generated HTML.

**Comment by Octachron** [comment]
Grepping `(*` would lead to quite a lot of false positives.

**Comment by redianthus** [comment]
Indeed, I just realized the output for a doc comment of a constructor gives something like `| Foo (* comment *)`. I guess it's to look like ocaml syntax but I find it a little bit ugly, so maybe it could be possible to change this and then it could be possible to grep without false positives. :)

EDIT: no that wouldn't work because it would also remove the `(*` we were looking for. Sorry, I'm tired...

**Comment by redianthus** [comment]
> no variant type declarations with only one documentation comment on its last constructor

Well, I found at least [one](
https://caml.inria.fr/pub/docs/manual-ocaml-4.10/libref/Ephemeron.GenHashTable.html). :)

**Pull request merged**
