### PR TITLE
Avoid checking twice if divisor is zero

### PR DESCRIPTION
**Pull request by chambart**
The flambda branch before merging assumed that Pdivint and Pmodint where
already checked when entering Cmmgen. This was not the case anymore
after merging and this change was lost. This fix this overlook by adding
an annotation to the Pdivint and Pmodint primitive telling whether the
division by zero was already checked.

The reason to move the test generation to Closure_conversion in the
flambda branch was to allow the division primitive to be considered as
pure without needing to check for the effective value of the
divisor. This simplified Semantics_of_primitives a lot.

### CODE REVIEW

**Comment by chambart** [comment]
Also contains a fix for http://caml.inria.fr/mantis/view.php?id=7328

The justification for adding the fix here rather than in a separate patch is that it share a lot of this patch.

@damiendoligez would you still accept such a patch for 4.04 ?

**Comment by mshinwell** [comment]
I think we should merge this for 4.04 given half of it was actually a merge mistake in 4.03, IIUC.

**Comment by bobzhang** [comment]
according to the docs:

> -unsafe
> Turn bound checking off for array and string accesses (the v.(i) and s.[i] constructs). Programs compiled with -unsafe are therefore slightly faster, but unsafe: anything can happen if the program accesses an array or string outside of its bounds.

div by zero should always raise.
Btw, if you want to turn `-unsafe` on to avoid div by zero check, would you use inline record to make life easier for people who consume lambda? thanks

**Comment by chambart** [comment]
Well the doc was missing something then. It should probably be fixed.
By the way this only apply to native code.

**Comment by bobzhang** [comment]
here `Lambda.primitive` types are changed, it would be nice that we use inline records whenever we use tuple

**Comment by chambart** [comment]
@bobzhang I tried and it don't look too heavy, so here it is.

**Comment by damiendoligez** [comment]
@chambart OK for 4.04 but what does this have to do with the `-unsafe` flag?

If you think the doc is missing something, you need to update it in this PR...

**Comment by lpw25** [comment]
This looks correct to me.

@damiendoligez It doesn't have anything to do with the `-unsafe` flag, but it is adjacent to the code which disables raising an exception for division by zero when using `-unsafe`. I guess @bobzhang noticed it when looking at the patch and was surprised by it since it is not mentioned in the docs.

**Comment by damiendoligez** [comment]
@lpw25 Thanks for the clarification. I see the doc change is not so urgent and it belongs in another PR anyway.

This one seems ready to merge. Any objections?

**Comment by mshinwell** [comment]
Now this has been read we should be good to go.

**Comment by gasche** [comment]
@damiendoligez I cannot find a trace of this in 4.04, did we forget to cherry-pick it?

**Comment by damiendoligez** [comment]
cherry-picked to 4.04 (commit 0ea09d20e70ff6fb0eb2f8f070a7ed0eaf52b0c9)

**Pull request merged**
