### PR TITLE
Minor ocamltest cleanups

### PR DESCRIPTION
**Pull request by shindere**
- Remove run_main.c that was not intended to be published

- Remove useless commented code

It's probably good to cherry-pick this to 4.06.

### CODE REVIEW

**Review by gasche — APPROVED** [review]

**Comment by mshinwell** [comment]
There's a spurious indentation change at the top of run_stubs.c.
This is ok to be merged after that is fixed.

**Comment by shindere** [comment]
Mark Shinwell (2017/09/21 15:39 +0000):
> There's a spurious indentation change at the top of run_stubs.c.
> This is ok to be merged after that is fixed.

Oops, sorry. Thanks. Fixed.

**Comment by damiendoligez** [comment]
Merged. @shindere, can you cherry-pick to 4.06?

**Comment by shindere** [comment]
Damien Doligez (2017/09/21 09:11 -0700):
> Merged.

Thanks!

> @shindere, can you cherry-pick to 4.06?

Sure, done: 94cc3d3538b37452312d1f69d92534efecd42073

**Pull request merged**
