### PR TITLE
Fix exhaustivity checking in presence of empty types

### PR DESCRIPTION
**Pull request by trefis**
Alternative to #9309. 

This is a slightly updated version of @Octachron's proposal, with updated docs.

### CODE REVIEW

**Comment by gasche** [comment]
@Octachron, @trefis and myself collaborated on this PR to fully develop @Octachron's approach as suggested by https://github.com/ocaml/ocaml/pull/9309#issuecomment-587097506. I would like to give it another round of review, but I think that it is the right approach to fix the bug reported by @smuenzel-js.

**Review by gasche — APPROVED** [review]
I reviewed this PR again and believe that it is correct. This should be good to go in trunk, and I'll merge this afternoon.

**Comment by garrigue** [comment]
I love how @gasche argues for discussing and the ignores the arguments silently...

**Comment by gasche** [comment]
@garrigue Florian, Thomas and myself met in person on Wednesday morning and we spent an hour and a half going over the potential designs and building a consensus on which approach was best.

You came up later with *a wrong characterization of the difference* (you call a "hack" or an "optimization" what is a nicer design) and unreasonable ideas about stopping the release train and adding more work to everyone for a last-minute bug report that affects three other major releases. I explained all of that in [my reply to your first message](https://github.com/ocaml/ocaml/pull/9309#issuecomment-588477963).

I made the judgment call that stopping the work that we had started on Wednesday to discuss further what to do for the release *on the day the release was supposed to happen* is stressful and a waste of time for everyone.

If you wish to do a review of this PR after it was merged, please be my guest. If you find a pressing issue to address, let's discuss it.

**Comment by garrigue** [comment]
This is not about the release since you are just merging this in trunk.
My problem is just that this version, in my opinion, adds extra complexity, without a clear benefit.
And I'm not the only one not to see the difference between an empty sum type and a contradictory GADT.

**Comment by gasche** [comment]
> My problem is just that this version, in my opinion, adds extra complexity, without a clear benefit.

What is the proposed alternative?

The previous PR was unsuitable because its behavior could not be explained in a way that is consistent with the explanations for the current code. Currently the documentation says that we backtrack *because* GADT constraints may make other parts of the term ill-typed. Empty types do not introduce any GADT constraints, so how would you explain that they use the same backtracking mechanism?

> And I'm not the only one not to see the difference between an empty sum type and a contradictory GADT.

The present PR does not make an a-priori difference between those two cases, it considers as empty types all the types for which `Parmatch.ppat_of_type` returns `PT_empty`. If you wanted to try harder in `pats_of_type` to prune patterns that correspond to inconsistent GADT instantiations (without mutating the current typing environment), we could of course add this logic as another PR. I am not sure what the benefits would be.

**Comment by lpw25** [comment]
> What is the proposed alternative?

Surely the alternative is to document that you backtrack if the type may be empty or may add local constraints to the environment and then use a single sensibly named mechanism to do that backtracking.

The way the code is written and documented in this PR implies that we backtrack on GADTs only because they may introduce local constraints, but this is not the case: we backtrack because they may introduce local constraints and they may be empty. Not being clear about this could theoretically lead to someone altering the code to not backtrack on GADTs that do not introduce local constraints but are empty.

**Comment by gasche** [comment]
There are two different things at play here:
- If an or-pattern introduces different GADT constraints in its branches, we may need to perform global backtracking, doing a counter-example search (*also* in the rest of the pattern) for each branch.
- If a pattern is at an empty type, it is not a valid counter-example so it should be filtered out; we should only return counter-example candidates that match at least one value.

Empty types do not require global backtracking, only the introduction of non-local constraints does.

The previous backtracking-avoidance optimization (the `Refine_or` strategy) was wrong: it considered that global backtracking could be avoided for each or-pattern with at least one branch not introducing constraints. (If global search fails for this unconstrained branch, it will fail in all other branches, so no need for backtracking.) It should instead look for one branch that does not introduce constraints and is non-empty (inhabited).

One way to do this is to demand that all empty types require global backtracking -- but again, I see no justification for global backtracking here other than "well this approximation is not wrong".

The present PR has the following properties:
- if all branches are empty, the counter-example is rejected as empty
- if there is at least one inhabited non-constrained branch, we avoid backtracking
- if there are no inhabited non-constrained branches and at least one constrained branch, we perform global backtracking

(One could try to refine this to not backtrack on branches that were found to be empty, but this would add implementation complexity.)

> Not being clear about this could theoretically lead to someone altering the code to not backtrack on GADTs that do not introduce local constraints but are empty.

Not doing *global* backtracking in this case would be completely correct. They would still need to reject the counter-example as empty, and this is done (after the present PR) simply by raising the `Empty` exception.

**Comment by lpw25** [comment]
> Not doing global backtracking in this case would be completely correct. They would still need to reject the counter-example as empty, and this is done (after the present PR) simply by raising the Empty exception.

Sure, but the current code and documentation does not make that clear. It clearly implies that the possibility of constraints is all that need be considered for GADTs.

**Comment by gasche** [comment]
The toplevel documentation for the counter-example mode says the following:

```ocaml
  (** In [Counter_example] mode, we are checking a counter-example
      candidate produced by Parmatch. This is a syntactic pattern that
      represents a set of values by using or-patterns (p_1 | ... | p_n)
      to enumerate all alternatives in the counter-example
      search. These or-patterns occur at every choice point, possibly
      deep inside the pattern.

      Parmatch does not use type information, so this pattern may
      exhibit two issues:
      - some parts of the pattern may be ill-typed due to GADTs, and
      - some wildcard patterns may not match any values: their type is
        empty.

      The aim of [type_pat] in the [Counter_example] mode is to refine
      this syntactic pattern into a well-typed pattern, and ensure
      that it matches at least one concrete value.
      - It filters ill-typed branches of or-patterns.
        (see {!splitting_mode} below)
      - It tries to check that wildcard patterns are non-empty.
        (see {!explosion_fuel})
  *)
```

I think that it is fairly clear from this documentation that refining a wildcard counter-example `(_ : foo)` into just a wildcard pattern would be incorrect if `foo` is an empty GADT.

That said, we could of course make the documentation the documentation for `Refine_or` more explicit by turning "branches that do not introduce new constraints" into  "*inhabited* branches that do not introduce new constraints".

Finally, the function in charge of exploding wildcard patterns is Parmatch.ppat_of_type; its own documentation says:

```
(** [ppat_of_type] builds an untyped pattern from its expected type,
    for explosion of wildcard patterns in Typecore.type_pat.

    There are four interesting cases:
    - the type is empty ([PT_empty])
    - no further explosion is necessary ([PT_any])
    - a single pattern is generated, from a record or tuple type
      or a single-variant type ([PE_single])
    - an or-pattern is generated, in the case that all branches
      are GADT constructors ([PE_gadt_cases]).
 *)
```

I think it is relatively clear again that if the type is empty, `PT_empty` should be raised (although `PE_gadt_cases` will also behave correctly), and that generating `PT_any` in this case would violate the specification. This said, again, please feel free to propose further clarifications.

**Comment by gasche** [comment]
Note: I'm not trying to suggest that the documentation is perfect and should not be improved! I may be still in my honeymoon period, given that we wrote it just a few months ago, but of course further improvements/clarifications will be necessary and they are warmly welcome.

**Pull request merged**
