### PR TITLE
Add local type definition syntax

### PR DESCRIPTION
**Pull request by zeyonaut**
This PR introduces local type definitions such as:
```ocaml
let type t = A | B in
match B with A -> 0 | B -> 1
```
Local type definitions are implemented as syntactic sugar for type definitions in an immediately-opened module.
```ocaml
let open struct
  type t = A | B
end in
match B with A -> 0 | B -> 1
```
This is consistent with the existing constructs `let exception` and `let module` and allows the local use of type definitions without polluting the top-level environment.

This was done as part of a compiler hacking session at Tarides and is joint work with @OlivierNicole, @thiciu, and @PeterHUistyping.

### CODE REVIEW

**Comment by gasche** [comment]
The syntax is consistent with local exceptions, but the implementation is not: it is done by a desugaring in the parsetree, while local exceptions have their own AST node. If we decide that we want the feature, I would be in favor of an implementation that adds a proper AST node in the parsetree and in the typedtree. (We are not good at re-sugaring and we need to do it semi-regularly.)

Regarding the feature itself: I agree that this is a natural feature to have, and it would be occasionally useful to define local datatypes inside a function (instead of using a less precise type or polymorphic variants).

**Comment by smuenzel** [comment]
> If we decide that we want the feature, I would be in favor of an implementation that adds a proper AST node in the parsetree and in the typedtree.

Here's a more general alternative: We could create an AST node for `Pexp_letstructure` to allow all structure items that make sense in an expression context, this would subsume `Pexp_letmodule`,`Pexp_letexception`, `Pexp_letopen`. I think structure items that qualify are `primitive_declaration`, `type_declaration`, `str_type_extension`, `str_exception_declaration`, `module_binding`, `rec_module_bindings`, `module_type_declaration`, `open_declaration`, `class_declarations`,`class_type_declarations`.

**Comment by gasche** [comment]
I agree that this is a nice suggestion. In this case the AST would typically support more programs than the parser, which is fine.

Note: currently `let x = def in body` and `let open struct let x = def end in body` are not equivalent, given that the scoping of type variables is the nearest structure item (so, for variables in `def`: the enclosing toplevel declaration in the first form, and the local structure item in the second form).

**Comment by gasche** [comment]
The feature is interesting, but the implementation is not ready yet, and I am not aware of progress towards a more satisfying one -- that adds a proper AST construct instead of doing a desugaring. I move to close the PR for now. Feel free to ask to reopen -- or to submit a new PR -- if there is interest in exploring a better implementation.

**Pull request closed without merging**
