### PR TITLE
Remove `Lev_module_definition` from lambda

### PR DESCRIPTION
**Pull request by ncik-roberts**
This PR removes `Lev_module_definition` from the lambda AST. This node wraps every module definition. However, the presence of this node isn't used for anything in the compiler, so it should be fine to remove.

The diff in the test suite shows how this wrapper node is removed and how its former payload is inlined.

@mshinwell originally added this construct in an early aborted attempt for GDB support, but he now thinks that the extra scoping information in `Debuginfo.t` that was added for memtrace should suffice. In other words: we can't think of a good reason to keep this AST node around. Furthermore, I'm finding it expedient to remove this node in the course of other work I'm doing. (I'm a new joiner on the type systems team at Jane Street.)

If you would like to reference the PR to Jane Street's internal branch, that's [here](https://github.com/ocaml-flambda/ocaml-jst/pull/135), with review provided by @mshinwell.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
The explanation are clear and the code appears indeed to be just a simplification. Approved.

**Comment by ncik-roberts** [comment]
Thanks. Hmm, I see a test is failing (one that checks a backtrace produced by the flambda compiler). This function is no longer being inlined after my change. I'm taking a look at this.

```
> !Called from Dynlink_common.Make.load.(fun) in file "otherlibs/dynlink/dynlink_common.ml" (inlined), line 363, characters 13-56
```

**Comment by ncik-roberts** [comment]
After looking some more, the change in test output reflects a change in an inlining decision by the flambda compiler. (For this test case, the removal of this wrapper AST node led to one function's body becoming small enough to inline, which caused the inlined-into function to become too large to inline.) This seems benign, so I just updated the test output.

**Comment by lthls** [comment]
The flambda change is *not* benign. It is a bug that would be fixed by #11383. Please don't merge this yet.

**Comment by lthls** [comment]
What happens is that we have a functor `Make(Arg : S_arg) : S_full` in the implementation that is restricted in the interface to `Make(_ : S_arg) : S_restricted`. The code generated for this looks like:
```ocaml
let Make = Lev_module_def (fun Arg -> (* full structure *)) in
let _stub_ = fun funarg -> let full = Make funarg in (* extract the relevant fields *) in
Global_block(_stub_)
```
But after this PR, this is transformed by the local function optimisation into:
```ocaml
let _stub_ = fun funarg -> let full = (* full structure *) in (* extract the relevant fields *) in
Global_block(_stub_)
```
So what we have is a reasonably large functor that is being treated by Flambda as a stub, which has two bad consequences:
- It will be inlined everywhere, even though it might not be beneficial
- No optimisation is done on its body
And this is why we have inlining differences.

Debug events are always dropped when entering Flambda, so this PR should have no effect at all on the code produced by the compiler. That it has one reveals a bug somewhere else, in this case a known bug.

**Comment by ncik-roberts** [comment]
Thanks. I agree we should avoid merging until your PR is merged. Upon reading your initial comment, I was confused about the linked PR (#11383) demonstrating the [same diff](https://github.com/ocaml/ocaml/pull/11383/commits/3f221382fd1a011b090602588bdf93d41c25d331#diff-be6900158230cf74e60dc42ae033b4279b467b20fa9a5f310ea99fd24468b36e), but upon inspecting the output of compiling `otherlibs/dynlink/dynlink_common.ml`, I agree that the test diff in your PR is of a different nature than the one in this PR. (I.e., it is truly owed to different inlining decision, whereas the diff in this PR is as you describe.)

**Comment by lthls** [comment]
#11383 has been merged, so I think this PR should be safe now (modulo the conflict in the testsuite).

**Comment by ncik-roberts** [comment]
The conflicts are resolved. I think this should be good to go now.

**Pull request merged**
