### PR TITLE
Fix integer overflows when unmarshaling a bigarray

### PR DESCRIPTION
**Pull request by glondu**
This pull request is an adaptation of https://github.com/ocaml/ocaml/pull/1718 for the 4.05 branch.

The patch has been applied in Debian, it might be useful for others who are still using the 4.05 branch.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
I reviewed the code again and it seems correct to me. (`caml_ba_multov` is an old overflow-handling function that was removed when introduced the new operators in b3bfc5f18f634232a239023de2a0b4b58beb7fa2). Could you maybe include the github hash of the original commit in the commit message, as you did in the PR description?

(General context: I have been in touch with @glondu to discuss the idea of merging upstream some of the Debian work to backport critical fixes in the OCaml version they maintain. Currently the OCaml upstream does *not* provide any sort of support for old branches, but I am personally willing to help care for them if there is interest.)

**Comment by glondu** [comment]
> Could you maybe include the github hash of the original commit in the commit message, as you did in the PR description?

Done.

**Comment by gasche** [comment]
@glondu: could you also include the Changes entry for this entry into the head of the Changes section (there is already a `4.05.x` section for some maintenance patches that went there)? Mainting this Changes properly would make it easy to look at what went in the maintenance branch.

**Comment by gasche** [comment]
@glondu: I just cherry-picked two other patches on top of 4.05 so that I can build the branch locally for testing (I'm using a recent gcc emits fatal errors on 4.05). (You should probably rebase your own patch to avoid conflicts in `Changes`.)

**Comment by glondu** [comment]
@gasche: I've just added the Changes entry and rebased.

**Comment by gasche** [comment]
Merged, thanks!

**Pull request merged**
