### PR TITLE
Remove unnecessary surrounding parentheses for immediate objects

### LINKED ISSUE #7308: Parenthesis surprisingly needed by immediate objects
**Original bug ID:** 7308
**Reporter:** SpiceGuid
**Status:** acknowledged (set by @xavierleroy on 2017-02-23T16:07:04Z)
**Resolution:** open
**Priority:** low
**Severity:** feature
**Version:** 4.03.0
**Category:** lexing and parsing

## Bug description

This is a oneliner :

object method one = 1 end # one;;

Trivially corrected as :

(object method one = 1 end) # one;; 

Immediate objects also must also be parenthesised when used as a function actual argument.

## Additional information

My intuition is that the end keyword closes a parenthesis.
I don't understand why i should add more nesting.

### PR DESCRIPTION
**Pull request by dyzsr**
Closes #7308

- Parse immediate objects as `simple_expr` with highest precedence.
- Immediate objects don't have to be surrounded with parentheses when used as arguments.

``` ocaml
object method one = 1 end # one;;
Some object method one = 1 end;;
ignore object method one = 1 end;;
```

### CODE REVIEW

**Comment by nojb** [comment]
The patch looks OK to me, but as with any syntax change we will want to wait for other developers to chime in.

The last commit (change `menhir` version) seems unrelated to the PR. If so, I would suggest leaving it out.

**Comment by dyzsr** [comment]
Thanks.

> The last commit (change `menhir` version) seems unrelated to the PR. If so, I would suggest leaving it out.

This commit intends to leave `menhirLib.ml/mli` in `boot/menhir` unmodified. So I think we can preserve it.

**Comment by Octachron** [comment]
An argument in favor of this change is that this matches the grammar described in the manual: https://ocaml.org/manual/expr.html#expr . Overall, I agree with the change since this is a simplification.

Concerning the last commit, upgrading menhir version is fine, so there is no need to fix the upgrade.

**Review by gasche — APPROVED** [review]
I'm approving this PR. There seems to be a consensus in favor of the change (in particular in the #7308 discussion), and the patch is nice -- in fact, it is suprisingly well done for an author I don't remember contributing in the past!

@dyzsr : could you add a Changes entry for this feature? It is a user-visible change.

**Comment by dyzsr** [comment]
Thanks!
Indeed, this is my first time contribution :D

**Comment by gasche** [comment]
Merged! Thanks for the nice contribution.

**Pull request merged**
