### PR TITLE
ppxs: no empty polymorphic type binders in parsetree

### LINKED ISSUE #11129: Conflicting error message whether to be or not to be a function
## Problem
While working on a ppx deriver and trying to figure out where I need to insert `Ptyp_poly`s to make the generated code typecheck, I happened on this conflicting error message:
```
Error: This expression should not be a function, the expected type is
       Ppx_deriving_ord_helper.t -> Ppx_deriving_runtime.int
```
It's saying that the (`function ...`) expression should be a function (i.e. of a function type), but at the same time not be a function!

When I printed out the generated code and tried compiling that directly, the error suddenly disappeared, confusing things even further, so I cannot even provide simple reproducible example code for it.

## Hypothesis
Since I was messing around with `Ptyp_poly`, I realized I'm inserting some with empty lists for type parameters. Avoiding those made the confusing error disappear.
I'm not familiar with the compiler code, but I have a hypothesis how this happened.

Here `Tpoly` is completely unhandled, so the `Not_a_function` error is raised:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/typing/ctype.ml#L3225-L3237
And when printing the expected type for the error message, the `Tpoly` with empty type parameter list is quietly thrown away:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/typing/printtyp.ml#L1153-L1154

Similarly, `Pprintast` ignores them, which is why manually compiling the generated and printed code suddenly worked:
https://github.com/ocaml/ocaml/blob/d0eba6b39a7f1b49172aa88b69c0440b99bbe6a4/parsing/pprintast.ml#L306-L307

## Solutions
I can think of the following things that could be changed:
1. Also handle `Tpoly (_, [])` in `Ctype.filter_arrow`.
2. Somehow distinguish `Tpoly (ty, [])` in error message types.

### PR DESCRIPTION
**Pull request by Octachron**
This PR proposes to check that ppxs do not produce parsetree with empty explicit universal quantifications, for instance in fantasy syntax
```ocaml
type t = { r: . int -> int }
```
instead of 
```ocaml
type t = { r: 'a 'b. int -> int }
```
Adding this invariant avoids the need to handle unexpected and sometimes invisible (see #11129) `Ptyp_poly([],_)` in the typechecker itself.

There is however a small exception to this rule for constraint on patterns, due to the fact that
```ocaml
let p : t = e
```
is currently encoded as
```ocaml
let (p: . t) = (e:t)
``` 
and the ast pretty printer relies on this encoding to resugar the second form in the first form.

close #11129

### CODE REVIEW

**Comment by gasche** [comment]
The fact that our own parsetree uses this empty-polymorhpism gives me cold feet. We are telling PPX authors to that it is invalid, with a special case for when our own parsetree producer actually uses it. Is there a reasonable way to avoid using this horrible hack in the parsetree, to avoid the hypocrisy?

**Comment by gasche** [comment]
For example, maybe we could:
- enrich `Parsetree.value_binding` with a toplevel `pvb_constraint` field that stores the handled-in-a-special-way toplevel annotation
- or, if we want to stay in the country of ugly workarounds, add a magic ocaml-namespaced attribute to notify that the toplevel constraint is to be desugared specially

**Comment by garrigue** [comment]
Well, I suppose that the special processing for non-quantified types could be done in `typecore.ml` rather than in `parser.mly`. Just have to be careful of what is assumed where.

**Comment by Octachron** [comment]
I had a look at moving the processing of constraints on let binding to typecore. That seems potentially simpler, I will submit a PR once my todo list for 5.0 is less full.

**Comment by gasche** [comment]
ping @Octachron

**Comment by Octachron** [comment]
I have updated this PR now that the parsetree is not using empty binders in encoding anymore.

**Comment by smuenzel** [comment]
small side-question about these kinds of parsetree invariants: What about introducing a non-empty list type to prevent something like this by construction? maybe that's more useful for records/tuples -- but preventing invalid data by proper type construction seems like a good property.

**Comment by Octachron** [comment]
It would make sense, but it is a more involved change: 
First, it is a visible change in the parsetree.
Second, once we have a non-empty list, we probably want a non-empty list module that mirrors the `List` module.

**Review by gasche — APPROVED** [review]
Sorry for forgetting about this PR. I am fine with the new, simpler version. This might break some ppx-produced code, but that code would probably have broken in more obscure ways later on in the type-checker, so this is in fact an interface improvement.

**Pull request merged**
