### PR TITLE
GPR#1041 regression

### PR DESCRIPTION
**Pull request by dra27**
While assisting with [MPR#7873](https://caml.inria.fr/mantis/view.php?id=7873), I have discovered a regression caused by #1041 that, in spite of the comments and changes made in that GPR, directives added by calling `Topdirs.dir_directory` are lost when building custom toplevels.

It turns out this same issue has always existed when invoking a custom toplevel with a script argument (e.g. `./mytoplevel foo.ml`). This latter issue is exacerbated by [MPR#6081](https://caml.inria.fr/mantis/view.php?id=6081), though the fix included there merely preserves this bad behaviour.

In both cases, the issue is that `Config.load_path` is in some way reset and although care was taken to preserve `-I` options, this didn't allow for any changes caused by `Topdirs.dir_directory`.

I have in this pull request reverted #1041 and then done a hopefully more comprehensive fix. The principle in operation is that `Compmisc.init_path` should not be called more than once. I have added `Compmisc.reinit_path` which, as long as the block of directories added by the call to `Compmisc.init_path` has not been messed around with, will remove the old list of directories and replace it with a new list (preserving both the prefix and suffix - so directories added with `Topdirs.dir_directory` and also the legacy `+camlp4` which is added at the end of the search path). For toplevels this means that during module initialisation, `Config.load_path` may include invalid directories (e.g. the standard library) and may not include some which it should (e.g. the threads library directory) but that by the time either `Toploop.run_script` or `Toploop.main` begins evaluating code, `Config.load_path` should both reflect the parsed command-line args and also any previous calls to `Topdirs.dir_directory`.

I have also added tests for all four of these cases. @shindere - I'd be very grateful if you have some time to look at the tests as I hope there may be a more elegant way of expressing them in ocamltest?

### CODE REVIEW

**Comment by shindere** [comment]
@dra27 many thanks for the detailed explanations!

It will take me a bit of time to look at the tests because they are
non-trivial but I will try to do it as soon as possible.

**Comment by XVilka** [comment]
Was this forgotten for 4.08? Seems no activity since December 2018.

**Comment by dra27** [comment]
@XVilka - have you hit this issue "in the wild"? It's been broken in two released versions, I expect this will be re-targeted for 4.09.

**Comment by shindere** [comment]
Had no time to look at the tests so far but didn't intend this to be a
blocker!

@dra27 do you expect this to go into 4.08?

If so, we should find somebody to review...

**Comment by shindere** [comment]
David Allsopp (2019/04/23 08:01 -0700):
> @XVilka - have you hit this issue "in the wild"? It's been broken in
> two released versions, I expect this will be re-targeted for 4.09.

Well if somebody can review, perhaps we can even put this into 4.08,
it's a bug fix after all.

**Comment by dra27** [comment]
@shindere - I'm just rebasing it, but I'm not convinced this is worth the risk for 4.08 - the actual fixing-commit is affected by #2041. Up to you and @damiendoligez!

**Comment by XVilka** [comment]
No, I am just waiting for 4.08 release and saw this PR in the 4.08
milestone and no action so far.

**Comment by shindere** [comment]
Many thanks for the reminder.
Let's wait for @damiendoligez's decision.

**Comment by damiendoligez** [comment]
This is a pretty obscure bug and a large-ish patch so I'm pushing it back to 4.09. If someone wants to object, do it quickly!

**Comment by shindere** [comment]
David Allsopp (2019/04/23 08:27 -0700):
> @shindere - I'm just rebasing it, but I'm not convinced this is worth
> the risk for 4.08 - the actual fixing-commit is affected by #2041. Up
> to you and @damiendoligez!

Do you expect it to be in 4.09 then? Or not even that?

**Comment by dra27** [comment]
I can do something for this in the next days for 4.09, if we’re happy to view it as a bug fix, and so ok to cherry pick

**Comment by damiendoligez** [comment]
Yes, it's OK to cherry-pick to 4.09.

**Comment by shindere** [comment]
It now seems there are conflicts that need to be resolved.
Not sure what else is needed on that one?

**Comment by dra27** [comment]
@shindere - this needs a complete re-write, which I will try to get to!

**Comment by Octachron** [comment]
@dra27 , any news on this front? I am thinking of retargerting this PR for 4.10 (or later if you prefer?).

**Comment by gasche** [comment]
Here is my understanding from reading the discussion:

- There is a real bug worth fixing.
- The fix proposed in 2018 by @dra27 is somewhat invasive, as it touches tricky logic in the state-initialization of the compiler. (This is an important aspect and it may be that the changes are beneficial to other people than `ocamlmklib` users.) It does not apply anymore and basically needs a rewrite.
- Since the issue was first reported, it looks like no one else complained about it again. The bug seems to matter for a very small number of users, making the issue lower-priority.
- No one seems to be interested in actively working on it. In particular we are already putting demands on @dra27's time with several higher-priority PRs.

As a result, I am closing the PR. Anyone should feel free to open a new PR with a new fix for this issue.

**Pull request closed without merging**
