### PR TITLE
Branchless computation of the integer absolute value

### PR DESCRIPTION
**Pull request by murmour**
This patch makes `abs` a built-in operation with a more efficient implementation.

A bit of background: one program of mine involves computing [Manhattan distances](https://en.wikipedia.org/wiki/Taxicab_geometry) inside tight loops, and `abs` function is used at the heart of it. While studying the performance of this program, I found out that `Pervasives.abs` has a naïve implementation based on a conditional branch, and that it's a source of frequent branch mis-predictions (according to Valgrind), which should result in a performance hit on modern OoO architectures. Indeed -- replacing `abs` with an optimized builtin (based on a branchless bitmask trick) made my program run 1.5 times as fast on a recent Intel CPU.

A simple benchmark to demonstrate the performance differences:
``` ocaml
let () =
  let sum = ref 0 in
  for i = -100_000_000 to 100_000_000 do
    for j = 52 to 62 do
      sum := !sum + abs (i lsl j);
    done
  done;
  Printf.printf "%d\n" !sum
```

The benchmark is designed to trigger cache misses, without trying too hard.

Results on my PC (i5 Broadwell), taking the minimum of 10 runs:

-- | Before | After |
--|--|--|
ocamlc | 69.524s | 37.688s | 
ocamlopt | 9.404s | 4.280s |

So, the benchmark now runs about twice as fast, which is significant.

I haven't used the more complicated algorithm in the byte-code interpreter, because the benefits of it seem to get lost in the noise of interpretive overhead. The program still runs twice as fast, because there are less opcodes to process, and because there is no function call now.

`ocamlopt` now produces nice code for `abs` on AMD64:
```
sarq $63, %rdx
addq %rdx, %rsi
addq %rdx, %rsi
addq %rdx, %rsi
xorq %rsi, %rdx
```

To be honest, I have no clue how good will it work on non-x86 platforms. Perhaps I should have added an `Iabs` constructor to `Mach` and pushed the implementation further into `amd64` and `i386` backends?

One more thing -- the branchless `abs` computation algorithm that I used here [is patented](http://patents.justia.com/patent/6073150) on behalf of Sun Microsystems, and is probably now a part of Oracle's patent portfolio. Please use the button in the top right corner of this PR form to cast a vote:

- Press :laughing: if you're not afraid of Oracle and their nasty lawyers.
- Press :confused: if you think that this legal issue is to be taken seriously.
- Press :heart: if you like me.

Thank you!

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm with Linus Torvalds here: never do a patent search when you're working on an open source project.  Damages are much higher when you knowingly infringe on a patent than when you unknowingly infringe.  By documenting the infringement publicly, and making it easy for lawyers to locate the infrigement by a simple Web search, you've made this PR impossible to accept.  Closing!

**Comment by murmour** [comment]
Understood! Sorry.

The patent is totally bogus though, and variations of this very algorithm are used in several language implementations (e.g. MSVC).

**Comment by xavierleroy** [comment]
Now a few more remarks.  First, Hacker's Delight lists 3 branchless sequences for absolute value, and there are probably more, and with high probability not all of them are patented.  (But, again, don't do patent searches yourself.)

Second, adding a new primitive and pushing it to all code emitters is a lot of work: at 20+ modified files you're still not done.  Even more so given that you don't use processor-specific features (e.g. conditional moves, predicated instructions). Try to implement your magic formula in OCaml itself, inside pervasives.ml.  ocamlopt will do a half-assed job at it, with a bit of tagging remaining, but it will still be branchless.  Also, bytecode will suffer...

Third, the benchmark is useful but for completeness you should also benchmark the case where branch prediction is perfect, i.e. the sign of the argument is always the same.

**Comment by xavierleroy** [comment]
The bogusness of a patent doesn't matter unless you're big enough and rich enough to actually fight the patent in court.  For small fry like us the only viable strategy is first to stay under the radar, then to claim "we didn't know" in good faith.

**Comment by murmour** [comment]
> Try to implement your magic formula in OCaml itself, inside pervasives.ml. ocamlopt will do a half-assed job at it, with a bit of tagging remaining, but it will still be branchless. Also, bytecode will suffer...

That was the first thing I tried, and it truly wasn't too bad (6 instructions instead of 5). Bytecode suffering was the reason that motivated me to add a compiler primitive (as `abs` seemed fundamental enough to warrant such move). I'll think more about all this. Thanks for the remarks!

> The bogusness of a patent doesn't matter unless you're big enough and rich enough to actually fight the patent in court. For small fry like us the only viable strategy is first to stay under the radar, then to claim "we didn't know" in good faith.

Makes total sense. I apologize again. I only mentioned the patent because it seemed an amusingly stupid fact of life.

**Comment by xavierleroy** [comment]
Re: bytecode suffering, you could have your cake (pun intended) and eat it too as follows:
```
let abs =
  if Sys.backend_type = Sys.Native then
      (fun x -> let y = x asr (Sys.word_size - 1) in (x lxor y) - y)
  else
      (fun x -> if x >= 0 then x else -x)
```
ocamlopt is good enough to specialize on `Sys.backend_type` and `Sys.word_size`, giving the same code as
```
let abs x = let y = x asr 63 in (x lxor y) - y)
```
(on a 64-bit platform, say).  At the same time, in bytecode, you just pay the test at start-up time, and applications are as fast as with the current definition of `abs`.

**Comment by murmour** [comment]
> if Sys.backend_type = Sys.Native then

Oh yes! This is a great suggestion. I was thinking of conditional compilation, and this is exactly it, in disguise.

For the record, I've done an alternative benchmark with a perfectly predictable branch:
```ocaml
let () =
  let sum = ref 0 in
  for i = 0 to 1_000_000_000 do
    sum := !sum + abs i;
  done;
  Printf.printf "%d\n" !sum
```
-- | Before | After |
--|--|--|
ocamlc | 23.128s |  13.408s |
ocamlopt | 0.904s | 1.148s |

Surely enough, there is a slight regression with `ocamlopt`.

The big question is: what are the typical use-cases of `abs`? I've just grepped through a big pile of sources in various languages that happened to reside on my hard drive and studied the uses of `abs`. Surprisingly, I only found two kinds of uses:
1) Distance computation (`abs (a - b)`). Very often (dozens of projects).
2) Simplification of rationals (`let simplify (a, b) = let g = abs (gcd a b) in (a / g, b / g)`). Quite rare (three programs).
  
Based on these questionable data points, I make an educated guess that `abs` is typically used in situations where the argument can be either positive or negative with comparable probability, and a branchless implementation of `abs` can bring substantial benefits. Those who read this: what are your typical uses of `abs`? I'm genuinely curious.

**Comment by murmour** [comment]
More on the damned patent (that will haunt me till the end of my days, no less):

I've studied it very carefully and... turns out that the described algorithm is completely different from the one that I've implemented here!

The algorithm from the patent ("enterprise abs") is:
1) Arithmetic shift;
2) Xor;
3) Subtraction.

And my algorithm ("tagged bit abs") is:
1) Arithmetic shift;
2) Addition;
3) Addition;
4) Addition;
5) Xor.

As should be obvious to anyone reading this, it is the ideological opposite of "enterprise abs". Not only the core idea is turned upside down, it also contains a novel groundbreaking solution that makes it applicable to bit-tagged integers!

If I were an enterprise jerk, I'd surely file a patent.

**Comment by murmour** [comment]
Regarding invasiveness of the patch: one thing that hadn't occurred to me earlier is simply adding a new C primitive ("caml_absint"). It would also allow to make use of `abs` from the C standard library (an optimized compiler primitive, typically).

**Comment by xavierleroy** [comment]
Calling a C function (even of the "noalloc" kind) is more expensive than evaluating the original OCaml definition of "abs".  Remember, C primitives are not inlined, while OCaml definitions are.

**Comment by chambart** [comment]
By the way, if you want to play with other solutions, there is the predicated version:
```assembly
        movq    $2, %rbx
        subq    %rax, %rbx
        cmovnl  %rbx, %rax
```
It seems to be better than both the if and bit-fiddling versions on both well and badly predicted cases.
It could somewhat be done as a general optimization on if. Yet it would be tricky to be able to use
`subq` for both the computation and the conditional in a general way.

**Comment by murmour** [comment]
Good suggestion, @chambart. This is what I came up with on ARM, using the same core idea that plays well with bit-tagging:
```asm
CMP r0, #0
RSBLT r0, r0, #2 ; if r0 is less than zero, set r0 to 2 - r0
```

I've planned an alternative PR with a thrice larger scope named "Branchless computation of abs, min, and max" that will compare:
1) The hardcore approach of adding an "abstract cmov" operation to `Mach` and extending all code emitters. I'm currently having high-quality entertainment with this.
2) The simple approach of putting the branchless formulas right into `Pervasives`, as suggested by @xavierleroy. With `ocamlopt`, on x86, it's about as good (performance-wise) as the solution proposed in this PR.

I haven't decided yet for which approach I will argue (there are more factors to consider beside performance), but you'll get the whole picture.

**Pull request closed without merging**
