### PR TITLE
Tentative fix for #8561

### PR DESCRIPTION
**Pull request by xclerc**
This PR fixes the typos causing the problems reported in https://github.com/ocaml/ocaml/issues/8561.

### CODE REVIEW

**Comment by xclerc** [comment]
(If accepted, it should be cherry-picked for 4.08.)

**Comment by gasche** [comment]
This should be compared with #8573.

Two remarks:

- This PR defines `INCLUDES` that is used in `lex/Makefile` according to https://github.com/ocaml/ocaml/issues/8561#issuecomment-478606107, #8573 does not.

- Both PR fix the SHARED_LIBRARIES issue by rewriting both tests to `ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"`, but I don't understand the point of having two conditional in a row that test the exact same thing. First, we could merge the two conditionals, and second, this means that the previous state was not just a typo, but an intended separation between two distinct concepts. @shindere, could you confirm that this was a work-in-progress that you decided to not include in the end, or say what was the intent of having two variables?

**Comment by shindere** [comment]
@æasche I think the `INCLUDES` stuff could be ignored at the moment
because it is not directly related to the issue we are trying to fix.

Re:the two blocks, I think they just came from two makefiles and I
forgot to merge them into one when I merged the `asmrun` and `byterun`
directories into `runtime`. i'm sorry I have missed your PR, I switched
to `not watching` on GitHub a few days ago.

**Comment by gasche** [comment]
I guess I'm happy to approve whichever of the two PRs merge the two conditionals into one; it doesn't make sense from a readability perspective to have two consecutive conditionals on the same variable.

**Comment by shindere** [comment]
Gabriel Scherer (2019/04/02 06:00 -0700):
> I guess I'm happy to approve whichever of the two PRs merge the two
> conditionals into one; it doesn't make sense from a readability
> perspective to have two consecutive conditionals on the same variable.

You are totally right, @gasche.
I'm really sorry for having introduced this problem and for not having
noticed the present PR. I have updated #8573 to merge the two blocks
according to your suggestion.

**Comment by gasche** [comment]
I see that @xclerc just closed this PR, but what's up with `INCLUDES` in lex/Makefile? Does anyone know if this variable used to be defined, or if it should just remain empty? (In many other makesfiles, INCLUDES point to directories in the rest of the compiler distribution, but `ocamllex` is self-contained enough that this doesn't seem necessary.)

**Comment by shindere** [comment]
Gabriel Scherer (2019/04/02 15:42 +0000):
> I see that @xclerc just closed this PR, but what's up with `INCLUDES`
> in lex/Makefile? Does anyone know if this variable used to be defined,
> or if it should just remain empty? (In many other makesfiles, INCLUDE
> point to directories in the rest of the compiler distribution, but
> `ocamllex` is self-contained enough that this doesn't seem necessary.)

As I said, I think it's unrelated and if something needs to be done it
can be done elsewhere, I'd say.

**Comment by xclerc** [comment]
As explained [here](https://github.com/ocaml/ocaml/issues/8561#issuecomment-478606107), `INCLUDES` in `lex/Makefile` is a use of an undefined
variable. It is definitely true that `ocamllex`is self-contained, which essentially
leads to two resolutions: remove the use of `INCLUDES`, or define it to be
empty. For coherence with other directories, I chose the latter.

(I was too lazy to open two PRs, but one could also argue that all the fixes
are the result of enabling the "use of undefined variable" warning of `make`.)

**Comment by xclerc** [comment]
At any rate, the warning in `lex/Makefile` is harmless.

**Comment by gasche** [comment]
@shindere: I agree that the change doesn't need to be fast-forwarded in 4.08, but using undefined variables in a Makefile is arguably a bug, and this issue is the first to propose a fix for it, so I find it natural to discuss it here -- now that the more pressing fixes have been handled in your separate PR.

@xclerc: I agree with your reasoning on defining it to be empty so I would suggest reopening your PR with just this fix, so that we can get rid of all undefined variables.

(If we were perfectionist about it we could think of changing things so that makefiles error on undefined variable, at least during CI testing or something like that, but I don't know how to do that.)

**Comment by shindere** [comment]
Gabriel Scherer (2019/04/02 08:54 -0700):
> @shindere: I agree that the change doesn't need to be fast-forwarded in 4.08, but using undefined variables in a Makefile is arguably a bug, and this issue is the first to propose a fix for it, so I find it natural to discuss it here -- now that the more pressing fixes have been handled in your separate PR.
> 
> @xclerc: I agree with your reasoning so I would suggest reopening your PR with just this fix, so that we can get rid of all undefined variables.
> 
> (If we were perfectionist about it we could think of changing things
> so that makefiles error on undefined variable, at least during CI
> testing or something like that, but I don't know how to do that.)

I agree it would be nice to enforce the definition of every variable
before it is used.
And reopening the PR with that purpose sounds very good to me.

This blog post may be relevant:

https://www.artificialworlds.net/blog/2015/04/22/treat-warnings-as-errors-in-a-gnu-makefile/

**Comment by xavierleroy** [comment]
It would be useful to stop on an error when a Makefile uses an undefined variable.  However this doesn't seem to be possible with GNU make:
* option `--warn-undefined-variables` produces a warning but doesn't stop on an error;
* there seems to be no way to specify it from within the Makefile.  Our top-level Makefile can add it when invoking sub-Makefiles, though.

The best we could do is tweak some of all CI jobs to 1- build with `make --warn-undefined-variables`, and 2- grep the output of `make` for warnings, failing the build if we find any.  Yuck.

**Comment by xclerc** [comment]
I did it by setting the `MAKE` environment variable to `make --warn-undefined-variables`,
but do not consider this piece of information as an incentive to do it in the CI.

There are other uses of undefined variables in `otherlibs/`; I did not report them because
they appeared more deliberate.

**Comment by dra27** [comment]
Another option might be to adapt the solution in the post @shindere shared as a development mode enabled by `configure` it a Git clone is detected. It’d be annoying for someone to develop a change which relied on using undefined variables only to discover at CI-time that we chose not to permit it!

**Comment by shindere** [comment]
We could also check this at the same time when the C compiler warnings
are turned into errors

**Pull request closed without merging**
