### PR TITLE
Move Location.absname to Clflags.absname

### PR DESCRIPTION
**Pull request by Armael**
A comment in `location.ml` indicates that the reference for the `absname` option should be defined in Clflags, but is defined in Location because otherwise it would complicate Camlp4's bootstrap.

Since Camlp4 is now packaged separately, maybe this is not the case anymore? If so, this PR moves the `absname` reference to `Clflags` where it apparently belongs.

### CODE REVIEW

**Comment by trefis** [comment]
Ping @diml .

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
There are a few more instances to fix (see CI failures) but otherwise this change looks fine to me. 

`grep -r absname .` in camlp4 yielded no result, so no worries on this side.

**Comment by Armael** [comment]
Oops, hopefully the remaining occurrences are now fixed.

**Comment by ghost** [comment]
Thanks, could you also add a changelog entry in the section `Internal/compiler-libs changes`?

**Comment by Armael** [comment]
Done, thanks for the review.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
No problem, thanks for the PR. We'll merge as soon as CI finishes

**Pull request merged**
