### PR TITLE
[Changes] Additional text for PR615

### PR DESCRIPTION
**Pull request by rbonichon**
Follows from discussion of PR #1382.

A word for the changes required if you want to keep the old behavior as it was.

### CODE REVIEW

**Review by gasche — APPROVED** [review]
Very nice, thank you!

**Comment by mshinwell** [comment]
@rbonichon I noticed earlier this week that PR#615 has introduced a closure allocation every time a formatter's queue is flushed (because of the new `clear_tag_stack` function).  This seems gratuitous but I'm not sure if it should be fixed for 4.06.

**Comment by gasche** [comment]
Cherry-picked in 4.06 : af8f9e8b5f86e35ef7fd385c83f9f3e52497cbf8.

**Comment by rbonichon** [comment]
@mshinwell 
Do you mean that in

```.caml
let clear_tag_stack state =
  List.iter
    (fun _ -> pp_close_tag state ())
    state.pp_tag_stack
```
the `(fun _ -> pp_close_tag state ())` is gratuitous ?
 
The type of `_` here is actually `string`. The `clear_tag_stack` function was actually added to fix the tag closing behavior on flushes --- which was buggy.

**Pull request merged**
