### PR TITLE
Allow to lookup and load cmi files from memory or other sources

### PR DESCRIPTION
**Pull request by ghost**
This patch adds a hook in the `Env` module for looking up and loading cmi files.
## API

``` ocaml
module Persistent_signature : sig
  type t =
    { filename : string; (** Name of the file containing the signature. *)
      cmi : Cmi_format.cmi_infos }

  (** Function used to load a persistent signature. The default is to look for
      the .cmi file in the load path. This function can be overridden to load
      it from memory, for instance to build a self-contained toplevel. *)
  val load : (unit_name:string -> t option) ref
end
```
## Motivation

Using this one can easily embed cmi files in an executable to create a self-contained toplevel. A test doing exactly this is added to the testsuite. This is something that I wanted to do on several occasions.

It's already possible to do something similar by playing with `LD_PRELOAD`, this patch just makes it easier and more portable.
## Changes

This patch moves the lookup in the load path and reading of the cmi file from `Env.find_pers_struct` to the initial value of the `load` function. The only suspicious change is that before this patch `add_import` was called between the lookup and `read_cmi` by `find_pers_struct` while it's now called after `read_cmi`. I did this change as otherwise the user would have to manually call `add_import` in the hook, which doesn't seem right.

As far as I can see, only `check_pers_struct` catches and handles `Cmi_format.Error` exceptions raised by `find_pers_struct`. Moreover `add_import` is always called before `check_pers_struct` (line 524). In other cases the exception just leaks to the driver so this path shouldn't _drop_ imports by mistake.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me.

**Comment by alainfrisch** [comment]
Other hooks recently introduced by @lefessan have an API where plugins can register new functions, and we maintain a list of such functions.  Perhaps we should do something more similar here.  E.g. letting plugins register resolver functions that return an optional result (`None` -> continue with other resolvers).

**Comment by chambart** [comment]
@alainfrisch in that case you probably want something that also allow to prevent other resolvers from providing a result. I would have use cases for that.

**Comment by alainfrisch** [comment]
Well, the first resolver that returns a result "wins" and prevent others from being run.  One just need to specify the priority.

**Comment by chambart** [comment]
I was thinking of preventing other resolvers to find a cmi when some failed. This would allow to avoid potential incompatible cmx error when it was in fact not available.
This is what the currently proposed api provides by default, you can keep and call the old resolver if you want.

**Comment by ghost** [comment]
In this case I indeed wanted to be able to completely replace the default lookup function. For instance if one wants to use exclusively the embed cmi infos and prevent the compiler libs to go look elsewhere. The proposed API allows to either continue with the previous resolver or stop immediately.

The hooks introduced for the compiler passes are mappers and it make sense to have many independent ones defined by plugins. For this use case I imagine that you would take the decision of where to look for cmi files on a per-application basis rather than adding resolvers via plugins.

To match the other hooks I suppose we could have something like this in Misc but it feels a bit over engineered:

``` ocaml
type 'a resolver_hook_result =
  | Found of 'a
  | Continue (** Try other resolvers *)
  | Stop (** Don't try other resolvers and consider the lookup unsuccessful *)

module type ResolverHookSig = sig
   type key
   val add_hook : ?priority:int -> string -> (key -> 'a resolver_hook_result) -> unit
   val lookup : key -> 'a option
end

module MakeResolverHooks : functor (M : sig type key end) -> ResolverHookSig with type key = M.key
```

**Comment by alainfrisch** [comment]
Ok, I agree, let's keep it simple.

**Comment by ghost** [comment]
Alright, this is a simple change and we reached a consensus so I'm merging it

**Comment by bobzhang** [comment]
can we also provide a hook to `save_cmi`, so that we can build an in memory compiler

**Comment by bobzhang** [comment]
@diml IIUC, this patch does not intercept all `read_per_structure` calls, like `Env.read_pers_struct` will do the IO directly

**Comment by ghost** [comment]
@bobzhang no, this patch only allows to change the resolution logic of the compiler for persistent signatures. `Env.read_signature` is only used for things you are compiling, for instance to read the .cmi file when compiling a .ml file or to read the .cmi files when packing .cmo files into a .cma. So intercepting it is not really in the scope of the PR.

To build an in memory compiler, instead of adding hooks for the various `read`/`save` functions I would look at abstracting the file-system operations. Then one one would just have to provide a different FS implemetation.

**Pull request merged**
