### PR TITLE
Remove propagation from previous branches on 4.10

### PR DESCRIPTION
**Pull request by garrigue**
This is a backport of #9811 to 4.10, to be able to check it on opam.

### CODE REVIEW

**Comment by trefis** [comment]
Ping @kit-ty-kate

**Comment by dra27** [comment]
This is wanted for 4.10.1, right? Your cherry-pick of the `Changes` entry has been somewhat unprincipaled if so 🙂

**Comment by Octachron** [comment]
No, this PR should not be backported to 4.10 : it is purely for testing purpose on a potential package-breaking change for 4.12 .

**Comment by dra27** [comment]
Sorry, reading further in the linked PRs I realised! Kate's on holiday soon, so testing may be delayed. Can I suggest it's converted to a Draft PR ("Convert to draft" up in the Reviewers part) since that clearly shows it shouldn't be merged (and it then can't be)

**Comment by xavierleroy** [comment]
Converted this PR to draft status, as suggested.

**Comment by garrigue** [comment]
Could it be possible to test this on opam @kit-ty-kate
(We expect it to have limited impact, but it some people may have used the extra laxism)

**Comment by gasche** [comment]
(If @kit-ty-kate is on well-deserved vacation, I'm sure @Octachron could be convinced to run the opam check.)

**Comment by avsm** [comment]
Kate is on vacation. If @Octachron can't do the bulk run, let me know and I'll do it.

**Comment by Octachron** [comment]
I will run an opamcheck test next week.

**Comment by kit-ty-kate** [comment]
I just ran opam-health-check (with all tests enabled) on 4.10.1 vs. this PR. I should have a result by tomorrow evening.

Sorry for the long wait.

**Comment by kit-ty-kate** [comment]
Dune does not compile with this branch:
```
#=== ERROR while compiling dune.2.7.0 =========================================#
# context              2.1.0~alpha3 | linux/x86_64 | ocaml-variants.4.10.1+pr9812 | file:///home/opam/opam-repository
# path                 ~/.opam/4.10.1+pr9812/.opam-switch/build/dune.2.7.0
# command              ~/.opam/4.10.1+pr9812/bin/ocaml bootstrap.ml -j 71
# exit-code            2
# env-file             ~/.opam/log/dune-6-b76d46.env
# output-file          ~/.opam/log/dune-6-b76d46.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# ./.duneboot.exe -j 71
# cd _boot && /home/opam/.opam/4.10.1+pr9812/bin/ocamlopt.opt -c -g -no-alias-deps -w -49 -I +threads dune__obj_dir.ml
# File "src/dune/obj_dir.ml", line 284, characters 25-28:
# Error: This expression has type path = Stdune.Path.t
#        but an expression was expected of type
#          Dune.Import.Path.t = Stdune.Path.t 
#        This instance of Stdune.Path.t is ambiguous:
#        it would escape the scope of its equation
# 
```
Apart from that I don't see any other related failures, however opam-health-check couldn't test many packages as most packages nowadays rely on dune. So to summarize:
* 1199 packages compile fine
* 5229 package fail because every versions of dune fail (apart from dune `1.6.x`)
* no packages fail that weren't failing with a regular 4.10.1 installation (apart from dune != 1.6.x of course)

If this failure is expected I'll try to make a patch to get dune to work and I'll re-run opam-health-check.

**Comment by garrigue** [comment]
Thanks for testing. We have at least part of our answer: inter-branch propagation is used in the wild, in particular in dune, and maybe in packages depending on dune.
It would be better to retry after fixing dune (i.e. add a type annotation at the place where the error is reported).
I'll have a look into it.

**Comment by garrigue** [comment]
@kit-ty-kate : I create a PR for dune in opam-repository which includes a patch fixing the typing errors.
Can it be used to test the repository again?
https://github.com/ocaml/opam-repository/pull/17147

**Comment by garrigue** [comment]
BTW, there were actually 3 places in dune which relied on inter-branch propagation.
The main reason seems to be that dune prefers to write:
```ocaml
  let path_of_build (type path) (t : path t) (dir : path) = ...
```
rather than the suggested
```ocaml
  let path_of_build : type path. path t -> path -> Path.t = fun t dir -> ...
```
Sticking to the latter would avoid most problems.

**Comment by gasche** [comment]
Wouldn't just adding a return-type annotation

```ocaml
  let path_of_build (type path) (t : path t) (dir : path) : path = ...
```

be robust in the same way? Personally I generally don't like the `type foo . ... = fun ...` approach and I avoid it when I can (when no polymorphic recursion is involved), because it loses the locality of annotating each argument with its type and thus makes it harder to see the type of the arguments.

**Comment by kit-ty-kate** [comment]
The opam-health-check run with https://github.com/ocaml/opam-repository/pull/17147 finished earlier today and the result was that `lwt`, `merlin`, `parsexp` (janestreet package) and `functoria-runtime` have the same issue (as well as 2 other minor packages `refl` and `pkcs11`).

So far in this run, out of 6422 available packages:
* :green_circle: 4181 compiled fine
* :red_circle: 6 packages failed due to this issue (see list above)
* :yellow_circle: the rest could not be tested yet due to those 6 packages

Fortunately they were easily fixed by adding very simple type annotations and I'm currently running another check with those packages fixed.
I'll keep updating the result of my tests tomorrow morning when the new run will be done.

**Comment by kit-ty-kate** [comment]
Oh, I forgot. One thing I was surprise of when fixing Lwt was for this definition here (https://github.com/ocsigen/lwt/blob/50fd7a4a30846c72d514d27ba725e8724551a1c6/src/core/lwt.ml#L631):
```
  let rec underlying
      : 'u 'c. ('a, 'u, 'c) promise -> ('a, underlying, 'c) promise =
    fun
      (type u)
      (type c)
      (p : ('a, u, c) promise) ->
```
`let x : 'u 'c. <type of the function> = fun ...` is not the same as `let x : type u c. <type of the function> = fun ...`.

Is that expected? Looking at the manual (http://caml.inria.fr/pub/docs/manual-ocaml/locallyabstract.html#p:polymorpic-locally-abstract) I'm assuming this is expected but I just want to be sure.

**Comment by garrigue** [comment]
> `let x : 'u 'c. <type of the function> = fun ...` is not the same as `let x : type u c. <type of the function> = fun ...`.
> 
> Is that expected? Looking at the manual (http://caml.inria.fr/pub/docs/manual-ocaml/locallyabstract.html#p:polymorpic-locally-abstract) I'm assuming this is expected but I just want to be sure.

They are not the same, in that the latter additionally turns the internal variables into locally abstract types.
This is necessary to allow refinement through GADT matching.
Reciprocally, if there are no GADTs involved, and the types `u` and `c` are not explicitly used, the two forms should be equivalent.

**Comment by garrigue** [comment]
> Wouldn't just adding a return-type annotation
> 
> ```ocaml
>   let path_of_build (type path) (t : path t) (dir : path) : path = ...
> ```
> 
> be robust in the same way? Personally I generally don't like the `type foo . ... = fun ...` approach and I avoid it when I can (when no polymorphic recursion is involved), because it loses the locality of annotating each argument with its type and thus makes it harder to see the type of the arguments.

Indeed this solves the problem too, and I used this form in most cases.
I have no opinion on which looks nicer. My point was just that if you write a type for the whole function, you have to write the return type too (or `_`, but then you indicate explicitly that it doesn't matter), so that you do not risk forgetting to write it, as is the case with most problematic code.

**Comment by gasche** [comment]
Given the amount of code in the wild that found itself depending on this feature (in a shallow way), it would be nice if the change could show up as a warning first for a few versions, to give people more time to notice the issue and fix their code. I'm not sure however that we can easily implement a warning; the idea would be to first check if the levels "would be corrected", warn, and then correct them?

(Are we sure we do want to remove propagation from previous branches?)

**Comment by garrigue** [comment]
You can already get an error (but not a warning) by compiling in `-principal` mode.
I'm not sure of how to make it a warning, short of backtracking in case of ambivalence error.
(i.e. something exponential in terms of the nesting of GADT pattern-matchings, which should not be a problem in practice.)
I can give it a try.
Note that since this seems to concern exclusively packages compiled with `dune`, which makes warnings fatal, this means that this will still break all of them in developer mode (but maybe this is exactly what we want).

**Comment by gasche** [comment]
If I understand correctly, the change that is breaking is to remove a call to `correct_levels` on the branch output type. This is why I proposed running a pass before this `correct_levels` that checks whether correct_levels would be a no-op, and warns otherwise. We could also instrument `correct_levels` to optionally raise a warning when it performs a level change. Or are you worried that the warning would then be raised in innocuous situations where correct_level does change levels but does not hide ambiguities?

**Comment by trefis** [comment]
> Or are you worried that the warning would then be raised in innocuous situations where correct_level does change levels but does not hide ambiguities?

I think that's right.

**Comment by gasche** [comment]
My impression is that we have now learned that this is breaking enough code that making it an error outright is not practical. I would propose to close this PR and focus on the one trying to implement this in the best possible way on trunk, #9812

**Comment by kit-ty-kate** [comment]
Sorry to have taken so much time, I had an issue with our solver, it now fixed.

Anyway, so, I ran opam-health-check again and the result is that `core_kernel` is not compatible either. So grand total so far
* :green_circle: ~2000 individual packages compiled fine
* :red_circle: 7 packages failed due to this issue
* :yellow_circle: ~200 individual packages could not be tested yet due to core_kernel failing

The fix for `core_kernel` was a tiny~ bit more annoying to understand how to do (due to the heavy use of higher-order functions) but it ended up being a one line fix anyway (https://github.com/kit-ty-kate/core_kernel/commit/b59b3f7456580fec3d4adbceeb77399f528a1678). I'm not really a great fan of it but oh well, it does the job and it's a one line change.

So far, I think that even if the error shows up in a few major packages, I would personally be in favour of adding this to OCaml 4.12, seeing how this version breaks a good number of major packages without this change already (base, lwt, dune, fpath, …). I don't know, I'm no complier dev and I'm not sure I understand this change fully, but it seems to me like this change is wanted and the fixes are minimal. I'll be there to fix the community packages like I've done for 4.11 and 4.10 at least, for sure. For the rest I feel like companies are slower to adopt the latest compiler and adding two type annotations here and there wouldn't be a big deal anyway as long as the change is announced properly.

**Comment by garrigue** [comment]
I have updated the 4.12 version of this PR so that it (hopefully) only produces an informative warning (this works with dune itself).
Since this only seems to concern packages compiled with dune, and since dune makes warnings fatal in developer mode, this means that developers will fix the breakages in their next release, but that distributed packages still compile.

**Comment by Octachron** [comment]
Since the warning version of #9811 has been merged, I am closing this PR.

**Pull request closed without merging**
