### PR TITLE
Fix 32-bit build on OpenIndiana

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by gasche** [comment]
I missed your pull request so @lijunsong and myself reimplemented a part of it in #588 (the `XOPEN_SOURCE` change) -- sorry about that. The part of your proposal that remain is the `aspp` change, but my understanding of [MPR#6831](http://caml.inria.fr/mantis/view.php?id=6831) is that, at the time at least, `as -P` was still considered to be the correct practice on OpenIndiana. Why the change now, is it only for more recent (or older) OpenIndiana versions?

**Comment by avsej** [comment]
The OpenIndiana tries not to use sun compiler, and not to mix with gnu toolchain. I've tested on recent distribution, because it is rolling release

**Comment by mshinwell** [comment]
@damiendoligez Should this be considered for 4.04?

**Comment by damiendoligez** [comment]
I'm OK to merge this into 4.04.

**Comment by gasche** [comment]
(I don't have time to merge.)

**Comment by damiendoligez** [comment]
@avsej Could you add an entry to the `Changes` file?

**Comment by avsej** [comment]
@damiendoligez added

**Comment by gasche** [comment]
I think that this was not merged in 4.04, so we should probably do it now.

**Comment by damiendoligez** [comment]
cherry-picked to 4.04 (commit 2b389439167112671f7b68b6fe92adf66332037c)

**Pull request merged**
