### PR TITLE
Close bug 0004023: usleep feature

### PR DESCRIPTION
**Pull request by johnlepikhin**

### CODE REVIEW

**Comment by xavierleroy** [comment]
This pull request has been sleeping (pun!) for too long.  If we can collectively agree on a name for this alternate "sleep" function, it will get in.

**Comment by murmour** [comment]
Trivia:
- There is no function in the stardard library, the name of which has _prefix_ `f` that stands for `float`.
- There is exactly one function name with _suffix_ `f` that means `float` — it's `modf`.

Considering the above, I change my suggestion from `fsleep` to `sleepf`.

**Comment by SGrondin** [comment]
I agree with cakeplus.

**Comment by damiendoligez** [comment]
OK for merging as soon as the function is renamed to `sleepf` and the `Changes` file is updated.

@johnlepikhin can you make these changes?

**Comment by johnlepikhin** [comment]
OK, I'll do it in the next two days.

**Comment by xavierleroy** [comment]
This got me thinking about the behavior of sleep(f) with respect to signals (those that are handled).  sleep() can be interrupted and return early in this case, but since Unix.sleep ignores the return code of sleep(), execution continues on the Caml side, albeit earlier than planned.  With Unix.select and the proposed Unix.sleepf, interrupting select() results in a Unix_error exception, which is probably not what we want.

I'm tempted to implement what it takes in Unix so that Unix.sleep/sleepf restart by themselves in case of interrupt, and return only when the requested time elapsed.  Any objections to this new behavior?  I think it is closer to the user's intent than what we have currently.

**Comment by edwintorok** [comment]
On 11/11/2015 07:28 PM, Xavier Leroy wrote:

> This got me thinking about the behavior of sleep(f) with respect to signals (those that are handled). sleep() can be interrupted and return early in this case, but since Unix.sleep ignores the return code of sleep(), execution continues on the Caml side, albeit earlier than planned. With Unix.select and the proposed Unix.sleepf, interrupting select() results in a Unix_error exception, which is probably not what we want.
> 
> I'm tempted to implement what it takes in Unix so that Unix.sleep/sleepf restart by themselves in case of interrupt, and return only when the requested time elapsed. Any objections to this new behavior? I think it is closer to the user's intent than what we have currently.

This would make Unix.sleep(f) consistent with Unix.write, and SIGINT -> Sys.break (on Sys.catch_break true) would keep working right?

How about also providing the user with the ability to turn on SA_RESTART for signal handlers installed by OCaml? This won't help with sleep/select but at least for C libraries on POSIX I found that to work more reliably than trying to fix every library to handle EINTR correctly (e.g. SQLite http://sqlite.1065341.n5.nabble.com/SQLite3-and-EINTR-td73118.html)

**Comment by xavierleroy** [comment]
Implemented in commit [trunk 50648ed], including the "restart on EINTR" behavior.

@edwintorok : yes, if the signal handler raises an exception (a la Sys.catch_break true), the exception terminates the sleep.  Concerning SA_RESTART, it is not POSIX, just a BSD and Linux extension.  Moreover, it doesn't apply uniformly to all system calls.  For example, under Linux, nanosleep() always return with EINTR on an handled signal.  See "man 7 signal" for details.

**Comment by Chris00** [comment]
:+1:

**Pull request closed without merging**
