### PR TITLE
[asmcomp] riscv64: minor simplification

### PR DESCRIPTION
**Pull request by ghost**
There is no way for `Clflags.pic_code` to be set on riscv64, so don't bother checking its value.

No change entry needed.

### CODE REVIEW

**Review by nojb — APPROVED** [review]
LGTM

I wonder however what is (if any) the relationship between `Clflags.dlcode` and `Clflags.pic_code`...

**Comment by ghost** [comment]
> I wonder however what is (if any) the relationship between `Clflags.dlcode` and `Clflags.pic_code`...

`dlcode` is set by default if dynlink was enabled at compiler `configure` time, and can be disabled with `-nodynlink`. In spirit, this is a superset of `pic_code`.

**Comment by nojb** [comment]
> > I wonder however what is (if any) the relationship between `Clflags.dlcode` and `Clflags.pic_code`...
> 
> `dlcode` is set by default if dynlink was enabled at compiler `configure` time, and can be disabled with `-nodynlink`. In spirit, this is a superset of `pic_code`.

By "superset", do you mean that `dlcode` should imply `pic_code`?

**Comment by ghost** [comment]
> By "superset", do you mean that `dlcode` should imply `pic_code`?

Yes. `dlcode` being set implies production of PIC code.

**Comment by nojb** [comment]
> > By "superset", do you mean that `dlcode` should imply `pic_code`?
> 
> Yes. `dlcode` being set implies production of PIC code.

Right, thanks for the clarification.

**Pull request merged**
