### PR TITLE
config/Makefile.m* tidy

### PR DESCRIPTION
**Pull request by dra27**
This PR is a leftover from debugging the Windows changes for the original autoconf PR. I'd quite like it merged just so that the Git history is "correct" prior to the deletion of these files (i.e. when we hit regressions, it's possible to look back at "what were the old files").

Once this is merged, I'd move that these files, and all the remaining support files for the old `configure` system, can be removed.

### CODE REVIEW

**Comment by dra27** [comment]
The final commit of this PR can be verified as only re-ordering lines by the bash incantation:

```bash
for i in $(git diff HEAD~1 HEAD --name-only)
do
  diff <(git cat-file --textconv HEAD~1:$i | sort) <(git cat-file --textc onv HEAD:$i | sort)
done
```

There's a simpler view of the diff [on my fork](https://github.com/dra27/ocaml/pull/7/files) without the last line-reordering commit.

cc @shindere

**Comment by shindere** [comment]
Great, many thanks!

Do you plan to include the removal of the `config/Makefile.m*` files in
this PR or maybe in a subsequent one?

**Review by shindere — APPROVED** [review]

**Comment by dra27** [comment]
@shindere - sorry for extreme lag here - I was expecting the files to be removed in a subsequent PR (which you've done with https://github.com/ocaml/ocaml/pull/8720)

**Comment by shindere** [comment]
David Allsopp (2019/06/10 00:58 -0700):
> @shindere - sorry for extreme lag here - I was expecting the files to
> be removed in a subsequent PR (which you've done with
> https://github.com/ocaml/ocaml/pull/8720)

No problem. Perhaps this PR should be merged first and then the one that
removes the files?

**Comment by dra27** [comment]
@shindere - sorry, I'm confusing things by having taken so long to respond to some PRs recently - you already merged this!

**Comment by shindere** [comment]
David Allsopp (2019/06/10 03:19 -0700):
> @shindere - sorry, I'm confusing things by having taken so long to
> respond to some PRs recently - you already merged this!

Gosh, sorry I didn't double-check.

Then if you have time to review the PR that removes the config directory
that would be really great.

**Pull request merged**
