### PR TITLE
Add {Bool,Char,Int}.hash

### LINKED ISSUE #10259: hash function in modules Bool/Int/Char/String
It would be convenient if modules `Bool`/`Int`/`Char`/`String` would provide a `hash` function, so that we can pass them to functors such as `Hashtbl.Make`.

Of course, we can use the polymorphic hash function `Hashtbl.hash` for this purpose, or define custom hash function (e.g. the identity for type `int`), but that's less convenient from a user's perspective.

Note: module `Float` already provides a `hash` function.

### PR DESCRIPTION
**Pull request by nojb**
Fixes #10259

### CODE REVIEW

**Comment by lthls** [comment]
A few comments:
- Is it really important to expose these functions as external in the interface ?
- I'm not an expert in the subject but the identity seems a rather poor hash function. I'd expect at least a comment saying that `Hashtbl.hash` might be a better choice.
- It's unfortunate that it's not possible for a module to implement both `Hashtbl.HashedType` and `Hashtbl.SeededHashedType`. Do you have a particular reason to go with the `HashedType` variant instead of `SeededHashedType` ?

**Comment by nojb** [comment]
> A few comments:
> 
> * Is it really important to expose these functions as external in the interface ?

No, I removed them from the interface.

> * I'm not an expert in the subject but the identity seems a rather poor hash function. I'd expect at least a comment saying that `Hashtbl.hash` might be a better choice.

Indeed, I changed it to use the same function as `Hashtbl.hash`.

> * It's unfortunate that it's not possible for a module to implement both `Hashtbl.HashedType` and `Hashtbl.SeededHashedType`. Do you have a particular reason to go with the `HashedType` variant instead of `SeededHashedType` ?

Not really, except that the original request in #10259 was in reference to the usual (non-seeded) functor.

**Comment by nojb** [comment]
> > * It's unfortunate that it's not possible for a module to implement both `Hashtbl.HashedType` and `Hashtbl.SeededHashedType`. Do you have a particular reason to go with the `HashedType` variant instead of `SeededHashedType` ?
> 
> Not really, except that the original request in #10259 was in reference to the usual (non-seeded) functor.

Actually this point and the question of adding hash functions is discussed at length in the thread starting at https://github.com/ocaml/ocaml/pull/8878#issuecomment-546716090

**Comment by nojb** [comment]
After reading the whole discussion in #8878 it is clear that the present PR is misguided :)

**Comment by xavierleroy** [comment]
In perfect hindsight, the `Hashtbl.SeededHashedType` interface should ask for a `seeded_hash` function, not a `hash` function, so that a module can implement both interfaces  `Hashtbl.SeededHashedType` and  `Hashtbl.HashedType`.  

Until we make this (incompatible but maybe not too breaking) change, it seems unwise to add `hash` functions to stdlib modules, just because we would not know whether they should be of the seeded kind or not.

**Pull request closed without merging**
