### PR TITLE
#JeSuisBunzli

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by lpw25** [comment]
Missing `@` on a couple of the `since` tags.

**Comment by jpdeplaix** [comment]
Fixed.
@dbuenzli, sorry your comments were hidden by the ```push --force```. If you want to comment a specific line, please comment on the ```Files changed``` tab. I think it works better.

> besides since it seems I still do care, I would simply say `flip f x y`  is `f y x`.

Mmmh, in fact I took this from the Haskell documentation. But yeah, maybe it's better to just say this.

> I don't think the name of the PR and commit is right since it's not clear to myself who I am and wouldn't like that to be in the commit history of the compiler. In any case I appreciate that you still have the energy for that kind of thing but please put your own name there for `flip` and not mine. Best, D.

To be honest, this PR was half serious and half not serious (for the PR and commit name). You made my day yesterday, really :joy:.

**Comment by gasche** [comment]
So it turns out `List.cons` is relatively consensual, but `flip` in Pervasives isn't. In particular, several people pointed out that `(fun xs x -> x::xs)` is not much longer than `(flip List.cons)` yet more readable. I just included `List.cons` in trunk, so it should be in 4.03.

**Comment by ygrek** [comment]
btw, why `(::)` is not a regular operator? It could be a replacement for `cons` (which then could have reversed signature)..

**Comment by gasche** [comment]
`( + )` is syntactic sugar for a function. `( :: )` is syntactic sugar for a binary data constructor. In OCaml (to my regrets) constructors are not functions.

**Pull request closed without merging**
