### PR TITLE
OCaml now require Vista to build

### PR DESCRIPTION
**Pull request by Et7f3**
Cf. https://discuss.ocaml.org/t/ocaml-4-07-0-default-unsafe-string-mingw32-working-for-windows-xp-sp3/8208/4

### CODE REVIEW

**Comment by bschommer** [comment]
Why not require Windows 8.1, which is the oldest version that still has support?

**Review by dra27 — APPROVED** [review]
(side-note: Windows 7 is still supported, you just have to pay for it ... no idea if any OCaml user out there has, though!)

At the moment we do still "support" Vista inasmuch as OCaml still builds on it. For museum interest only, OCaml does actually still build on Windows XP with only a minor tweak, but I'm not sure how proud we should actually be of that 🙂

I'd prefer formally adopting Windows 8.1 as a minimum to be accompanied by reviewing the versions of Visual Studio and setting appropriate Windows header flags, etc. so in the meantime approving this as it updates the README to reflect actual reality!

**Comment by Et7f3** [comment]
A OCaml with the patch from discuss applied 👀 https://github.com/Et7f3/ocaml-win-xp (the original OP didn't know understand how to fix) This ocaml can't load str module.

**Comment by Et7f3** [comment]
8.1 support (5 years + 5 years) ended yesterday (or maybe there is 3 years agains ?). So minimum support can be bumped to windows 10 build 1507.

**Pull request merged**
