### PR TITLE
ocamlc: more robust implementation of Misc.no_overflow_mul

### PR DESCRIPTION
**Pull request by murmour**
The old version of `Misc.no_overflow_mul` fails on `a = min_int, b = -1` and on `b = 0`, which may (or may not) be the cause of incorrect code transformations in `Cmmgen`. I suggest replacing this function with a more robust version, which is based on a similar function [from Batteries](https://github.com/ocaml-batteries-team/batteries-included/blob/7b382ecaae31de6304944977746fab8a5bdd2a39/src/batInt.ml#L256).

### CODE REVIEW

**Comment by murmour** [comment]
Shall I add a test for this?
Also, I'm not sure if it deserves an entry in Changes.

**Comment by gasche** [comment]
Yes, you should add tests for it, and yes, it deserves a Changes entry. Thanks!

**Comment by xavierleroy** [comment]
> Yes, you should add tests for it

I'm sorry to disagree but so far we don't use unit tests for compiler functions, we only do integration tests for the whole compiler (= check that some input program is correctly compiled), and I don't see how to test this function via integration tests.

**Comment by gasche** [comment]
We have unit tests for some Misc functions in `testsuite/tests/utils`.

P.S.: I think it would be fairly reasonable to require that new functions in Misc or the standard library come with unit tests.

**Comment by xavierleroy** [comment]
This implementation looks like table 2.2 from chapter 2 of _Hacker's Delight_.  This is good because it's almost certainly correct, like all of _Hacker's Delight_.  But: please add a reference in a comment.

Also: a few lines above, _Hacker's Delight_ proposes the following test for `x * y` multiplication overflow:
```
   let z = x * y in
   (y < 0 && x = min_int) || (y <> 0 && z / y <> x)
```
To me this looks simpler than your code.

**Comment by xavierleroy** [comment]
I have mixed feelings about unit tests.  They take a lot of time to write and rarely find bugs.  Committing ourselves to writing unit tests for (parts of) the compiler functions is attaching a ball and chain to our ankles.

**Comment by mshinwell** [comment]
I must say, I share similar feelings to @xavierleroy 's about unit tests, although I do think they have clear value at times.  I would have thought this was such a case.

**Comment by murmour** [comment]
@xavierleroy 
> This implementation looks like table 2.2 from chapter 2 of Hacker's Delight. This is good because it's almost certainly correct, like all of Hacker's Delight. But: please add a reference in a comment.
>
> Also: a few lines above, Hacker's Delight proposes the following test for x * y multiplication overflow:
> ```ocaml
>    let z = x * y in
>    (y < 0 && x = min_int) || (y <> 0 && z / y <> x)
> ```
> To me this looks simpler than your code.

The proposed test is from [CERT C Coding Standard](https://wiki.sei.cmu.edu/confluence/display/c/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow), and is notable for avoiding an overflow while checking for overflow. However, since [overflows are perfectly defined in OCaml](https://github.com/ocaml/ocaml/pull/1458#discussion_r147942628) (palmface), we have the luxury of relying on a particular behaviour; so I've updated the patch with the shorter test, which looks simpler to me as well.

I've added the Changes entry.

As for extending the testsuite, I share the sentiment that unit testing is rarely of any value, especially so in compilers. My rule of thumb is: the only things that are worth testing are those things that can break, and I don't see this trivial one-line function breaking (now that I've audited and tested it carefully).

**Comment by gasche** [comment]
My idea was that if you keep track, in the testsuite, of the sanity checks that you performed on your new definition, then later if you decide to change the implementation you can quickly check that it still passes them. (For example this could have saved you time when you decided to simplify the implementation.)

It also serves as a way to store the knowledge of which edge cases have been considered already and of the fact that the function's behavior in this case is intentional.

**Comment by murmour** [comment]
> It also serves as a way to store the knowledge of which edge cases have been considered already and of the fact that the function's behavior in this case is intentional.

All of it is encoded in the source of the formula that is pointed in the comment (Hacker's Delight, chapter "Overflow Detection").

But of course we can be more explicit, yes. It's not much of a hassle. Will add tests a bit later.

**Review by xavierleroy — APPROVED** [review]
LGTM

**Comment by murmour** [comment]
A test is added. It also covers `Misc.no_overflow_add` and `Misc.no_overflow_sub`.

**Review by xavierleroy — APPROVED** [review]
Looks good to me (again).  Merging!

**Comment by gasche** [comment]
This is a very minor comment but when you use "Squash and merge", the weird stuff that is proposed in the awkwardly small textarea is actually the commit message -- the default value is a concatenation of the messages of each commit. It is often appropriate to delete or reformulate the lines corresponding to the minor commits that you decided to squash.

**Comment by xavierleroy** [comment]
Yes, that is my understanding too, and I often edit the small textarea intensively.  Here I edited lightly because the default commit message looked pretty good already.  Don't you agree?

**Comment by gasche** [comment]
I think it's okay, I just wasn't sure you were aware of the feature -- many people just ignore the textarea. Sorry for the noise.

**Pull request merged**
