### PR TITLE
testsuite: convert typing-unboxed-types to expect-style tests

### PR DESCRIPTION
**Pull request by gasche**
This will be very useful for an upcoming PR implementing a different
unboxing check, which change the result for some of the tests. Without
the present change, the diff in test results was unreadable, which
is problematic for development and for code review.

### CODE REVIEW

**Comment by trefis** [comment]
A nice property of the previous version of the test (i.e. before your diff) was that we were sure that the same thing was tested with and without flat float arrays. Now, nothing's preventing the files from diverging.

Is there some work that could be done on expect_test to have both with and without flat float arrays results in the same file / expect block (similarly to what is done for `-principal`)?

**Comment by ghost** [comment]
It's possible, however it means that the user will have to run the test with both configurations manually.

It works as follow for `-principal`: every node has two expectations: one without `-principal` and one with. During one run, only one of the expectation is updated, corresponding to the current setting. When both expectations are equal, they are displayed as a single expectation. Because `-principal` is a runtime flag, the test harness runs the test twice in a row: once without `-principal` and once with. After the first step, many nodes might have two different expectations, however after the second run most of them will be collapsed again to a single expectation.

Because flat float arrays is not a runtime flag, the test harness cannot do the two runs automatically. So it means that the user would see the intermediate state where only one of the expectation has been updated, which might be a bit confusing.

I suggest to do the following: allow to disable tests depending on the compiler settings. When the outcome of a test depends on the flat float arrays setting, it should be duplicated into two tests: one that is enabled iff flat float arrays if off and one that is enabled iff flat float arrays is on. Then the CI should test both configurations to make sure all tests are up to date.

**Comment by gasche** [comment]
Note: if "duplicating into two tests" means also duplicating the tested code, then it is what I have done manually here. Duplicating within a single file is nicer because the two copies remain close together, but still not so nice. On the other, duplicating *expectations* only

```
foo;;
[%%expect ~when:Config.flat-float-array {|...|}]
[%%expect ~when:(not Config.flat-float-array) {|...|}]
```

would work nicely.
(Would that require parsing and interpreting the ~when argument at ppx-processing time? Wild stuff!)

In the specific case of this PR, frankly I think that "testing the same thing on both side" is overrated: in the -no-flat-float-array case, the check is trivial, so the only thing we are testing is the dynamic behavior (which is not actually tested in most cases). Since I don't want to wait for hypothetical expect-test features, I think the change as proposed is a good compromise. I could also remove the test-noflat, or keep only the ones that have some interesting dynamic behavior.

**Comment by gasche** [comment]
P.S.: @trefis, do you approve of this reasoning?

**Comment by ghost** [comment]
I hadn't considered manually duplicating the expectation this way, but yes it should work well.

**Comment by trefis** [comment]
> In the specific case of this PR, frankly I think that "testing the same thing on both side" is overrated: in the -no-flat-float-array case, the check is trivial, so the only thing we are testing is the dynamic behavior (which is not actually tested in most cases). Since I don't want to wait for hypothetical expect-test features, I think the change as proposed is a good compromise. I could also remove the test-noflat, or keep only the ones that have some interesting dynamic behavior.

Ack.
I think it's indeed fine to take the PR as is until someone finds the time to update expect_test.

**Review by trefis — APPROVED** [review]

**Comment by gasche** [comment]
Thanks!

Should we track the conditional-expectations idea / feature request somewhere?

**Pull request merged**
