### PR TITLE
Add missing @since annotation to Gc.eventlog_resume / Fix annotation @since to Effect to 5.0.0 rather than 5.00.0

### PR DESCRIPTION
**Pull request by Nymphium**
This PR is for #10996.

### CODE REVIEW

**Comment by Nymphium** [comment]
Should I add `no-change-entry-needed` tag?

**Comment by shindere** [comment]
Nymphium (2022/04/21 07:53 +0000):
> Should I add `no-change-entry-needed` tag?

Yes, please.

And the version in the since attribute should be `5.0` rather than
`5.00` (only one zero).

Thanks!

**Comment by Nymphium** [comment]
Thank you for the comments!

> And the version in the since attribute should be `5.0` rather than
`5.00` (only one zero).

But I found annotations `@since 5.00`, `@since 5.0.0` and `@since 5.0`:

```shell-session
$ ag '@since 5.0'
stdlib/effect.mli
17:    @since 5.00.0 *)

stdlib/string.mli
501:    @since 5.0.0 *)
508:    @since 5.0.0 *)

stdlib/random.mli
149:      @since 5.0.0 *)
167:    @since 5.0.0 *)

stdlib/stringLabels.mli
501:    @since 5.0.0 *)
508:    @since 5.0.0 *)

stdlib/scanf.mli
264:    @since 5.0 *)
486:    @since 5.0 *)
496:    @since 5.0 *)

stdlib/gc.mli
433:   @since 5.0
```

Should I apply your comment (`5.00` to `5.0`) and/or unify the above annotations to `5.0` (or `5.0.0`)?

**Comment by dra27** [comment]
They should all really be `@since 5.0`, although it's only the one in effect.mli which is actually "wrong"

**Comment by Nymphium** [comment]
I modified the first commit that adds annotation `@since 5.0.0` and in the second I changed `@since 5.00.0` in stdlib/effects.mli to `@since 5.0.0`.

**Comment by shindere** [comment]
Nymphium (2022/04/21 20:23 -0700):
> I modified the first commit that adds annotation ***@***.*** 5.0.0` and in
> the second I changed ***@***.*** 5.00.0` in stdlib/effects.mli to ***@***.***
> 5.0.0`.

Thanks, but it should really be `5.0` in the second commit, as @dra27
told you.

**Comment by Nymphium** [comment]
Oh sorry, I changed it to `@since 5.0`.

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Yes, this time it's okay. Thanks. Just waiting for all tests to pass and
then I will merge.

**Comment by Nymphium** [comment]
I don't know why some of tests are failing. Should I rebase master?

**Comment by dra27** [comment]
We had a brief period where the trunk branch was broken - CI’s fine with a fresh merge commit

**Comment by dra27** [comment]
Thanks!

**Pull request merged**
