### PR TITLE
Short circuit simple inclusion checks

### PR DESCRIPTION
**Pull request by lpw25**
When checking that a module type `S` is equal to a module type `S` the compiler currently expands `S` and checks it against itself.

Similarly, when checking that a module `M` of module type `S` has module type `S` the compiler currently strengthens `S` with `M` and checks that against `S`.

This PR short-circuits such checks in some places where this is currently easy to do. This can have a noticeable improvement on the compilation times of actual files if the definition of `S` is very large.

### CODE REVIEW

**Comment by gasche** [comment]
Out of curiosity, why do you need a bootstrap?

**Comment by lpw25** [comment]
I think that doing fewer checks can mean creating fewer identifiers, so this change can affect cmi digests. Which sometimes seems to force a bootstrap to get things to compile. It seems like it shouldn't in principle, but the current build seems to sometimes mix cmis from the bootstrap compiler with cmis from the new compiler.

**Comment by lpw25** [comment]
We've backported this and #9246 for our compiler at Jane Street, and it appears that they've reduced our build times by around 2%.

**Comment by trefis** [comment]
I'll try and do a review of this early next week.

**Comment by trefis** [comment]
> I'll try and do a review of this early next week.

By which I meant that I will do the review this Monday.

**Review by trefis — APPROVED** [review]
This looks correct to me (as in: I believe the new version of the code gives the same answers as the previous one in all situations).


PS: have a nice Monday everyone!

**Comment by lpw25** [comment]
I've rebased and added a changes entry. This should be good to merge.

**Pull request merged**
