### PR TITLE
Tweaks to amd64 emitter

### PR DESCRIPTION
**Pull request by xclerc**
This PR suggests the following changes to `amd64/emit.mlp` in order to
emit shorter instructions when possible:

- when moving a known constant to a register;
- when and-ing a register with a known constant;
- when xor-ing a register with itself.

These changes are based on the fact that when using a 32-bit register,
the lower part is used to performed the actual computation while the
higher part is cleared.

This PR also disables `inc`/`dec` instructions, as suggested by the Intel
manual because, contrary to `add`/`sub` instructions, they do not set all
flags, which can in turn add data dependencies.

(The PR is split into multiple commit to easily apply only a subset.)

### CODE REVIEW

**Comment by alainfrisch** [comment]
Does this come from aesthetic considerations, or did you observe noticeable reductions in code size?  If so, please share your findings!

**Comment by xclerc** [comment]
These changes are part of a larger patch we successfully
tested against the critical path of one of our applications.
However we did not test of these changes individually;
I will add a variant on [1] to ensure there is no regression.

[1] https://github.com/OCamlPro/ocamlbench-repo

**Comment by xclerc** [comment]
It just occurred to me that the following rewrites should probably
be enabled iff `fast_code` is false:

- `mov` ~> `mov+cdqe`;
- `mov` ~> `mov+sal`.

(We could also ban `inc`/`dec` instructions iff `fast_code` is true.)

**Comment by xavierleroy** [comment]
> These changes are part of a larger patch we successfully tested against the critical path of one of our applications.

Good to know, but that wasn't @alainfrisch's question.  Does all this reduce the code size significantly?  By how much?

**Comment by xclerc** [comment]
Sorry, I misread Alain's question.

Here are the sizes for the binaries from the distribution:


  | before (bytes) | after (bytes) | change (bytes) | change (percentage)
-- | -- | -- | -- | --
./tools/ocamlobjinfo.opt | 8974040 | 8952760 | -21280 | -0.24
./tools/read_cmt.opt | 8324456 | 8307312 | -17144 | -0.21
./tools/ocamlmktop.opt | 1765248 | 1761032 | -4216 | -0.24
./tools/ocamlmklib.opt | 1640024 | 1635816 | -4208 | -0.26
./tools/ocamloptp.opt | 2074832 | 2070608 | -4224 | -0.20
./tools/ocamlprof.opt | 2747760 | 2739320 | -8440 | -0.31
./tools/cmpbyt.opt | 8304136 | 8282896 | -21240 | -0.26
./tools/dumpobj.opt | 1803112 | 1798888 | -4224 | -0.23
./tools/ocamldep.opt | 8293872 | 8272632 | -21240 | -0.26
./tools/stripdebug.opt | 8295408 | 8274168 | -21240 | -0.26
./tools/ocamlcp.opt | 2059496 | 2055272 | -4224 | -0.21
./tools/primreq.opt | 1344272 | 1344208 | -64 | -0.00
./ocamldoc/ocamldoc.opt | 10808664 | 10779192 | -29472 | -0.27
./ocamltest/ocamltest.opt | 8525824 | 8504584 | -21240 | -0.25
./lex/ocamllex.opt | 1724056 | 1723960 | -96 | -0.01
./ocamlc.opt | 8573992 | 8552640 | -21352 | -0.25
./ocamlopt.opt | 11621056 | 11597560 | -23496 | -0.20

**Comment by alainfrisch** [comment]
And do these tiny reductions lead to any observable performance improvement?   Smaller code is usually better, except if you start using less-optimized instructions.

I'm trying to find reasons to add complexity to the compiler and risk performance regressions (on specific versions of the CPU).

**Comment by xclerc** [comment]
I will measure the gains in tight loops; in the meantime, here is an illustration
of the gain (or loss in the case of `inc`/`dec`) for each rewrite:

```
  # use 32-bit legacy instructions when data size is 32 bits -- section 9.2.1
  48 31 c0             	xor    %rax,%rax
  31 c0                	xor    %eax,%eax

  # ibid
  48 25 ff ff ff 7f    	and    $0x7fffffff,%rax
  25 ff ff ff 7f       	and    $0x7fffffff,%eax

  # ibid
  48 c7 c0 01 00 00 00 	mov    $0x1,%rax
  b8 01 00 00 00       	mov    $0x1,%eax

  # ibid
  48 c7 c0 ff ff ff 7f 	mov    $0x7fffffff,%rax
  b8 ff ff ff 7f       	mov    $0x7fffffff,%eax

  # avoid instruction that are eight+ bytes in length -- section 3.4.2.7
  48 b8 ff ff ff ff 00 	movabs $0xffffffff,%rax
  00 00 00 
  b8 ff ff ff ff       	mov    $0xffffffff,%eax
  48 98                	cltq   

  # ibid
  48 b8 00 00 00 00 01 	movabs $0x100000000,%rax
  00 00 00 
  b8 01 00 00 00       	mov    $0x1,%eax
  48 c1 e0 20          	shl    $0x20,%rax

  # avoid inc -- section 3.5.1.1
  48 ff c0             	inc    %rax
  48 83 c0 01          	add    $0x1,%rax

  # ibid
  48 ff c8             	dec    %rax
  48 83 e8 01          	sub    $0x1,%rax
```

The sections refer to "Intel 64 and IA-32 Architectures Optimization Manual",
available [here](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf).

**Comment by xavierleroy** [comment]
I had a quick look at the new instruction patterns.

Using `movl $n, %R32` instead of `movq $n, %R64` when n is in [0...0xFFFF_FFFF] is a clear win: two bytes saved, very common idiom, no risk of performance regression.

The other patterns for "load integer constant" are less convincing to me.  Replacing one `movabsq` instruction by two dependent instructions is smaller but might run slower!  Plus, I suspect those cases of "load integer constant" to occur rarely.

**Comment by xclerc** [comment]
> Using movl $n, %R32 instead of movq $n, %R64 when n is in [0...0xFFFF_FFFF] is a clear win: two bytes saved, very common idiom, no risk of performance regression.

(The submitted patch considered only the values in the range of `Int32.t`.)
Your example leads to an even larger win:

```
movq $0xffffffff, %rax ~> 48 b8 ff ff ff ff 00 00 00 00
movl $0xffffffff, %eax ~> b8 ff ff ff ff
```

**Comment by xclerc** [comment]
Here is the comparison against trunk mentioned above:
    http://bench.flambda.ocamlpro.com/compare?test=2017-11-24-1724%2F4.07.0%2Bamd64tweaks%2Bbench&reference=2017-11-24-1724%2F4.07.0%2Btrunk%2Bbench

**Comment by xclerc** [comment]
An instrumented version of the compiler gives the following distribution
of `Iconst_int` instructions for a run of `make world.opt`:

compilation | percentage
-- | --
32-bit `xor` | 7.1
32-bit `mov` | 89.2
`mov` + `cdqe` | 0.3
`mov` + `sal` | 0.3
no optimization | 3.1

As @xavierleroy pointed out, there is no risk of performance regression if we
restrict the patch to only the first two cases.

Would you consider such a patch for merge?

**Comment by xclerc** [comment]
Sorry to insist, but would you accept a patch reduced to the following changes?

1. the use of 32-bit instructions for `xor` / `mov` / `and` when the operand
  is in [0..0xFFFF_FFFF]
2. the use of `add` / `sub` instructions instead of `incr` / `decr` ones

**Comment by xavierleroy** [comment]
> the use of 32-bit instructions for xor / mov / and when the operand is in [0..0xFFFF_FFFF]

Definitely yes.

> the use of add / sub instructions instead of incr / decr ones

Yes, but this is trading increased code size for reduced dependencies, so perhaps keep inc / dec if fast_code is false.

**Comment by xclerc** [comment]
> > the use of 32-bit instructions for xor / mov / and when the operand is in [0..0xFFFF_FFFF]

> Definitely yes.

I have removed the complex patterns around the `mov` instruction.


> > the use of add / sub instructions instead of incr / decr ones

> Yes, but this is trading increased code size for reduced dependencies, so perhaps keep inc / dec if fast_code is false.

As suggested, I have made the code emitting `inc` / `dec` depend on
the value of `fastcode_flag`.

**Comment by xclerc** [comment]
Travis is not happy. The `check_all_arch` fails because the last
commit uses a constant (`0x01_0000_0000n`) that is invalid on
a 32-bit architecture. See https://github.com/ocaml/ocaml/pull/1571.

**Comment by xavierleroy** [comment]
>  the last commit uses a constant (0x01_0000_0000n) that is invalid on a 32-bit architecture.

Just write `n <= 0xFFFF_FFFFn` instead of `n < 0x01_0000_0000`.  Just as clear + syntactically valid on a 32-bit system.

**Comment by xclerc** [comment]
> Just write n <= 0xFFFF_FFFFn instead of n < 0x01_0000_0000. Just as clear + syntactically valid on a 32-bit system.

Of course. My gut feeling was that it would hide a real issue.
I guess my understanding was slightly wrong: the code built
my `check_all_arches` is only expected to be compiled but not
to be executed (some operations over `nativeint` values
in `cmmgen.ml` would probably produce invalid results on
32-bit platforms anyway).

**Comment by xclerc** [comment]
Travis is still not happy, but this time it is not even clear why.
The last two lines of the [log](https://travis-ci.org/ocaml/ocaml/jobs/329519153) are:

    ========= CHECKING asmcomp/arm64 ==============
    make: *** [check_all_arches] Error 1

**Comment by xavierleroy** [comment]
You have another occurrence of ` 0x01_0000_0000 ` left.

**Comment by xclerc** [comment]
How embarrassing... I guess I was puzzled by the change/lack
of error message.

However, isn't this occurrence a bit more annoying? As it is an
`int` value on a 32-bit machine, I will probably not be allowed to
write `0xFFFF_FFFF`. Of course, I can promote the value to be
compared to `int64`, but that does not feel right...

**Comment by xclerc** [comment]
@xavierleroy, do you agree to merge this PR as is, after https://github.com/ocaml/ocaml/pull/1571 is merged?
(disabling the check on 32-bit architecture, already approved by @damiendoligez)

My understanding is that it is not unreasonable to use 64-bit features when writing
the 64-bit backends.

**Comment by xavierleroy** [comment]
I'm OK with the fact that 64-bit ports do not compile on 32-bit hosts.  (That compilation scenario sounds rather useless.)

**Comment by smuenzel-js** [comment]
@xclerc: Looks like you merged trunk into your branch, and this resulted in the pull request being messed up. Can you remove the merge commit and rebase instead? 

Some other ideas (for a future PR):
- For Iand: when n = 0xFF, use movzx
```
25 ff 00 00 00       	and    $0xff,%eax
0f b6 c0             	movzbl %al,%eax
```
- For other operations with 8-bit immediates: We may get a shorter encoding if we use 8-bit registers. This transformation is valid when the high 56-bits are not affected by the operation. IIRC this does not result in an extra merge micro-op.
```
48 83 cb 01          	or     $0x1,%rbx
80 cb 01             	or     $0x1,%bl
```
- We may want to consider two-instruction sequences that start with zero-cost operations (xor r32,r32) if they result in a shorter overall encoding. 
```
48 c7 c0 01 00 00 00    mov $0x1,%rax
b8 01 00 00 00          mov $0x1,%eax
31 c0 b0 01             xor %eax,%eax; mov %0x1,%al
```

**Comment by smuenzel** [comment]
ping?

**Comment by damiendoligez** [comment]
ping @xclerc

**Comment by gasche** [comment]
Ping again. What is the status here? If @xclerc is not interested in working on this anymore, maybe @smuenzel you would be interested in rebasing the restricted version of this PR and proposing it again, as a new PR?

(I am planning to close next time I encounter this PR if there has not been any progress.)

**Comment by gasche** [comment]
Closing. We can always reopen if there is interest.

**Pull request closed without merging**
