### PR TITLE
Fix type equality for the result type

### PR DESCRIPTION
**Pull request by hhugo**
No entry in the changelog because the issue is only present on trunk.

### CODE REVIEW

**Comment by nojb** [comment]
LGTM. Note that you don't need to use the `Stdlib.` prefix if you are using `nonrec`.

**Comment by hhugo** [comment]
I added `Stdlib` afterward trying to fix some dependency issue.
I'm not sure which of `nonrec` or `Stdlib` is necessary.

**Comment by hhugo** [comment]
@nojb, I've removed the reference to Stdlib.

**Review by nojb — APPROVED** [review]
Good to merge when CI green.

**Comment by hhugo** [comment]
travis is green-ish

**Comment by nojb** [comment]
Thanks!

**Pull request merged**
