### PR TITLE
Strongly connected components

### PR DESCRIPTION
**Pull request by mshinwell**
This code implements Kosaraju's algorithm for strongly connected components.  It is required in flambda for the identification of recursive functions and recursive constant definitions.

Unlike the majority of flambda, this piece still needs a full review for correctness.  I would be pleased if someone could help with that.

To make this compile you also need GPR #361.  I will update this pull request once that one has been resolved.

### CODE REVIEW

**Comment by braibant** [comment]
Out of curiosity, what was the rationale behind implementing Kosaraju's rather than Tarjan's algorithm for strongly connect components? I understand that the former makes two traversal of the graphs, while the latter makes a single pass. (However, Kosaraju's might be simpler to implement.)

**Comment by fpottier** [comment]
Along the same lines as Thomas, I wonder why not re-use one of the existing OCaml implementations of Tarjan's algorithm. There is one in the ocamlgraph library:
  https://github.com/backtracking/ocamlgraph/blob/master/src/components.ml
There is also one in Menhir's source code, under the name tarjan.ml:
  http://gallium.inria.fr/~fpottier/menhir/menhir-20151112.tar.gz
Both have been tested and should be reasonably bug free.

**Comment by mshinwell** [comment]
We will have to wait for @chambart to return from vacation to get an answer to that.  He is back after New Year.  Thanks for the references to alternative implementations.

**Comment by mshinwell** [comment]
Two questions for @fpottier :
1. Why does Menhir have another implementation given that there is one in ocamlgraph?  Is it because that one wasn't known about, or because the Menhir one is more performant, for example?
2. If we desired to use the Menhir one, would it be possible for that code to be relicensed to match the new OCaml licence (LGPL 2.1 + static linking exception)?

**Comment by fpottier** [comment]
Yes, the Menhir implementation is older than the one in ocamlgraph, I think. I originally wrote this code in 1999. And yes, it would be possible to include it in OCaml and re-license it.

**Comment by lefessan** [comment]
About the license, OCaml license is not LGPL+exn, but a full CLA that allows Consortium Members to re license all the code under whatever license they want. But I think Francois is ok with that too :-)

For SCC, in our memprof, we improved the SCC module of Ocamlgraph to avoid stack-overflows (patch integrated upstream) and tested it quite a lot !

**Comment by chambart** [comment]
I made a new implementation to avoid license problems. I chose Kosaraju's algorithm for simplicity since this is not yet used in any performance critical situations (the graphs are quite small).

I would suggest merging it that way and switching to a better implementation when licensing problems are resolved.

**Comment by chambart** [comment]
The provided test suite is not wonderful, but the implementation is already quite well tested by the different uses in the compiler.

**Comment by mshinwell** [comment]
I think I'm leaning towards using the Menhir one actually, just because it saves someone having to read Kosaraju in detail (which we should do, even if it appears correct).

**Comment by mshinwell** [comment]
We decided for the moment that the testing for the one that Pierre wrote should be sufficient for the moment, and we'll merge this one to start with.  However we should consider replacing it with one of the others in the future perhaps.

**Comment by damiendoligez** [comment]
Note that Menhir is copyright Inria, so we won't have to do any paperwork to relicense it, as long as @fpottier agrees.

OK for merging this version for the time being.

**Comment by gasche** [comment]
It looks like the tests do not compile right now.

**Pull request merged**
