### PR TITLE
Migrate more tests to ocamltest

### PR DESCRIPTION
**Pull request by nojb**
The list of commits speaks for itself; extended `ocamltest` in two small ways:

- added an `include ocamlcommon` modifier (used in `ast-invariants` for example)
- added a syntax to *append* to a variable: `variable += VALUE` (used in `lib-stdlabels` and `lazy`)

Other than that, I am not fully happy about the the modification to `ast-invariants/test.ml`: this test parses all `*.ml` files in the repository so it needs to be able to find the repository root. I could not find a simple way to transmit the repository root using `ocamltest`, so I changed it so it keeps going up parent directories until it finds `VERSION`.

### CODE REVIEW

**Comment by nojb** [comment]
@shindere

**Comment by shindere** [comment]
Well first of all, and most importantly, a big thanks for this very nice
contribution, @nojb.

Then two general remarks.

1. Regarding the commit messages. I noticed that I tend to like the
following convention.

- Commit messages starting with "ocamltest:" for the modification of the
tool itself

- Commit messages of the form "Migrate tests under ${dir}" to ocamltest
for the test migration commits, ${dir} being relative to the root
directory of the repository

2. The migration commits sometime seem to include a bit of cleanup, like
removing spaces at end of lines, undue blank lines and so on.
I was thinking that it would perhaps be possible to do one big
cleanup commit on all the testsuite, before the migration commits,
so that these ones because trivial and kind of canonical.

All this being said, if you don't want to rebase according to the
previous suggestions that's okay, the suggestions are also for future
commits.

Regarding the letrec tests: there seems to be no .ml file corresponding
to the disallowed.reference file so what shall we do? Shall we really
keep the reference file?

@yallop ?

Regarding the ocamlcommon modifier. I indeed had in mind to add such a
modifier which will be useful in other places. Just two suggestions:

1. Could you please name it "compilerlibs"?

2. Regarding its definition, I'd write it something like this:

let compilerlibs_subdirs =
  [
    "utils"; "parsing"; "typing"; "bytecomp"; "compilerlibs"; "ocamlcommon"
  ]

let add_compilerlibs_subdir subdir =
  Append (Ocaml_variables.libraries, wrap subdir)

let compilerlibs =
  List.map add_compilerlibs_subdir compilerlibs_subdirs

Regarding the AST invariants test:

- The way you have written the DSL is definitely correcdt.

- However, the same thing could be achieved with:

(* TEST
   * native with compilerlibs, unix
*)

(I think)

- Regarding the way to find the root of the repository. ocamltest has a
variable named ocamlsrcdir that has this information and I think it
should be possible to give it as an argument that will be passed to the
test when it gets run. To achieve this, you'd replace the previously
suggested block by this one:

(* TEST
   * native with compilerlibs, unix
     arguments = "${ocamlsrcdir}"
*)

(I didn't test but I'd say this *should* work so if it doesn't that's
probably a bug so let me know and I'll fix)

In testsuite/tests/lib-format/tformat.ml: you could perhaps pu the *)
closing the TSL block at the beginning of a line, like in other tests.
(this also applies to a few other tests like in lib-printf)

testsuite/tests/lib-obj/reachable_words.ml: very cool change!

The "+=" thing is of course an excellent idea. Actually that was the
intention but somehow I was side-tracked and forgot to add it to the
language so thanks a lot for having done so.

In testsuite/tests/lib-stdlabels/test_stdlabels.ml: perhaps remove the
blank line just after the beginning of the test block?

(also in a few other tests, those defining variables, I think)

And I am very happy with the other commits and to see the Makefiles
going away slowly so I renew my thanks to you, @nojb.

**Comment by nojb** [comment]
Thanks for the review @shindere!

- I did the suggested stylistic changes
- I prefer to leave the whitespace changes with each individual test; the changes are small in all cases and were performed automatically by my editor, I prefer not to have to split them off.
- Regarding the `disallowed.ml` file I believe that test became the `letrec-disallowed` directory but that the `.reference` file was left behind, which is why I removed it.
- Regarding `ocamlcommon`: I did not want to name it `compilerlibs` because there is also `ocamlbytecomp`, `ocamloptcomp`.
- I tried the `include foo, bar` comma-separated syntax but it does not seem to work at the moment.

Also, I went ahead and migrated a bunch of `toplevel` tests, mostly routine but:

- Had to fix a file path in `ocamltest`: see the `ocamltest: fix toplevel output path` commit
- The `.reference` files needed to be updated because we do not capture the toplevel prompt anymore

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2017/12/03 05:20 -0800):
> Thanks for the review @shindere!

My pleasure!

> - I did the suggested stylistic changes

Thanks

> - I prefer to leave the whitespace changes with each individual test;
> the changes are small in all cases and were performed automatically by
> my editor, I prefer not to have to split them off.

Okay

> - Regarding the `disallowed.ml` file I believe that test became the
> - `letrec-disallowed` directory but that the `.reference` file was
> - left behind, which is why I removed it.

Right, sorry, I think I misread the diff.

> - Regarding `ocamlcommon`: I did not want to name it `compilerlibs`
> - because there is also `ocamlbytecomp`, `ocamloptcomp`, etc.

OK. Not found of those names, but I guess if they are those people are
used to they are probably the best ones.

> - I tried the `include foo, bar` comma-separated syntax but it does
> - not seem to work at the moment.

No in fact the include syntax does not surrently support a
comma-separated list of environemnts, it's jsut the "with" syntax which
does. Perhaps this should change in the future, but that's the current
situation.

> Also:
> 
> I went ahead and migrated a bunch of `toplevel` tests, mostly routine but:
> 
> - Had to fix a file path in `ocamltest`: see the `ocamltest: fix
> - toplevel output path` commit

I didn't try to migrate toplevel tests since I restarted working again
on ocamltest so thanks a lot for having done so.

It seems okay to me.

> - The `.reference` files needed to be updated because we do not
> - capture the toplevel prompt anymore

Yes that's expected (did yousee the tests I migrated on the
origina-ocamltest branch on my GitHub public repository?)

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
@nojb while migrating the tests in lib-digest, is there any reason why
you didn't preserve the -w a flags?

**Comment by nojb** [comment]
No good reason (even though it seems unrelated to the test).  Will put it back in. Thanks!

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2017/12/04 06:32 -0800):
> No good reason (even though it seems unrelated to the test).  Will put
> it back in. Thanks!

Great, thanks. Yeah it didn't seem very related to me either, it's just
to avoid, when possible, to mix the migration itself with other changes.

**Comment by yallop** [comment]
> Regarding the disallowed.ml file I believe that test became the letrec-disallowed directory but that the .reference file was left behind, which is why I removed it.

Yes, it looks like that's exactly what happened.  Thanks for clearing it up, @nojb.

**Comment by shindere** [comment]
(hopefully) fixed trunk in commit c965e525d00261c0681f4f9b813c3a5cb67a3486

Fellow developers: next time I am reluctant to use precheck.. Insist!

**Comment by shindere** [comment]
Just ran this through Inria's precheck. It works on every platform
except freebsd-64. On this platform, there is just one test that fails,
namely the native test for lib-format/tformat.ml.

The test fails because the compiler's output is not empty as expected.
The error comes from the linker:

/usr/bin/ld: error in tformat.o(.eh_frame); no .eh_frame_hdr table
will be created.

Trying to investigate this currently and to figure out what makes
this test so unique! First search suggests a missing -shared option
somewhere.

Actually, the error shows up in the log already with the legacy test
harness, it's just that it went unnoticed until now.

**Comment by nojb** [comment]
It may be worth checking that it is not a bug in their `binutils` e.g. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47829

**Comment by shindere** [comment]
Nicolás Ojeda Bär (2017/12/05 19:57 +0000):
> It may be worth checking that it is not a bug in their `binutils` e.g.
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47829

Ah, thanks.

Well cc --version says
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on
LLVM 4.0.0)

And ld --version is

GNU ld 2.17.50 [FreeBSD] 2007-07-03

I'll see whether I can upgrade the system.

**Comment by shindere** [comment]
With more recent versions of ld, the warning disappears and the test thus
passes.

However, I also noticed that the test that fails with the old ld does so
for flambda=true, while it passes for flambda=false

I quick examination of the build system does not allow me to understand why
this is so, since there seems to be no obvious link between the way FLAMBDA
is set and the link options.

**Comment by shindere** [comment]
Given that this PR passes CI both on Travis and AppVeyor, and given
how marginal the remaining failure is, I'm merging.

**Pull request merged**
