### PR TITLE
Fix access to C symbols when using Dynlink

### LINKED ISSUE #9209: Access to C symbols dropped inbetween two calls to Dynlink with OCaml 4.10
`nocrypto` currently fails on OCaml 4.10 with the following error message:
```
- + ocamlfind ocamldep -package zarith -package ppx_sexp_conv -package bytes -package sexplib -package cstruct -modules src/nocrypto.mli > src/nocrypto.mli.depends
- File "_none_", line 1:
- Error: Cannot load ppx_sexp_conv: error loading shared library: Dynlink.Error
-        (Dynlink.Cannot_open_dll "(Failure\n 
-        \"/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs: undefined symbol:
-        Base_internalhash_fold_float\")")
```
Trying to debug the issue further made me write the following code:
```
let () =
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/sexplib0/sexplib0.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/base_internalhash_types/base_internalhash_types.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/caml/caml.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/shadow_stdlib/shadow_stdlib.cmxs";
  Dynlink.loadfile "/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs"
```
which compiles perfectly but fails with the same error:
```
Fatal error: exception Dynlink.Error (Dynlink.Cannot_open_dll "Dynlink.Error (Dynlink.Cannot_open_dll \"(Failure\\n  \\\"/home/opam/.opam/4.10.0+trunk/lib/base/base.cmxs: undefined symbol: Base_internalhash_fold_float\\\")\")")
```
Trying to decompose the issue a bit further here is a very minimal test case:
```
$ cat test.c
int testdynfail() {
  return 0;
}
$ cat lib.ml
external test : unit -> unit = "testdynfail"
$ cat lib2.ml
let test = Lib.test
$ cat dyn.ml
let () =
  Dynlink.loadfile "lib.cmxs";
  Dynlink.loadfile "lib2.cmxs"
$ ocamlopt test.c
$ ocamlmklib test.o -o test
$ ocamlopt -shared -linkall -I . -cclib -ltest lib.ml -o lib.cmxs
$ ocamlopt -shared -linkall lib2.ml -o lib2.cmxs
$ ocamlopt -linkall dynlink.cmxa dyn.ml
$ ./a.out
Fatal error: exception Dynlink.Error (Dynlink.Cannot_open_dll "Dynlink.Error (Dynlink.Cannot_open_dll \"Failure(\\\"/tmp/dynlink-fail/lib2.cmxs: undefined symbol: testdynfail\\\")\")")
```
The same minimal test case works with OCaml 4.09.0 and older. I'm not really sure what changed in Dynlink since 4.09 but it now seems to drop the accessibility of C symbols between two calls to `Dynlink.loadfile`.

In case you need access to some of the packages required to test the compilation of `nocrypto` or `base` you might need the following opam overlay:
```
$ opam remote add alpha git://github.com/kit-ty-kate/opam-alpha-repository.git
```

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #9209 

As @dra27 stated in #9209, the issue came from https://github.com/ocaml/ocaml/pull/2288. It appears that one of the piece of code moved to `Primitive.native_name_is_external` was not correctly translated (i.e. `native_name p` is not equivalent to `p.priv_native_name`).

cc @mshinwell

### CODE REVIEW

**Comment by dra27** [comment]
Snap!

**Comment by dra27** [comment]
If @shindere could have a check of the long `ocamltest` header - I confess to having hacked it until the log was doing what I was after, rather than thinking about it properly...

**Comment by shindere** [comment]
David Allsopp (2019/12/26 12:02 -0800):
> If @shindere could have a check of the long `ocamltest` header - I
> confess to having hacked it until the log was doing what I was after,
> rather than thinking about it properly...

I fear what you have come up with is almsot the best that can be
achieved with the current implementation of ocamltest, very sorry aobut
that.

One simplification I can see is in the lines:

```
program = "${test_build_directory}/main.exe"
```

I think the "${test_build_directory}/" is not needed because the test
build directory is noramlly the test's current directory so I'd
recommend to get rid of it to simplify the code and gain portability
(the less paths you have, the more the code is likely to work also on
windows)

**Comment by dra27** [comment]
No problem, @shindere, and thanks for checking it - I was more ensuring that I hadn't missed something daft!

**Comment by shindere** [comment]
David Allsopp (2020/01/06 08:09 -0800):
> No problem, @shindere, and thanks for checking it - I was more
> ensuring that I hadn't missed something daft!

Well I didn't test myself, but the story the header is telling looked
coherent to me.

**Comment by gasche** [comment]
What needs to be done before merging this PR? (@dra27, are you approving?)

**Review by gasche — APPROVED** [review]
I reviewed the PR and believe that it is correct. (The bug comes from using the type `string` to represent optional information. I'm considering sending a second PR to fix this.)

I will merge now, and cherry-pick in trunk.

**Pull request merged**
