### PR TITLE
Add an empty type to the standard library

### LINKED ISSUE #11265: Define an empty variant type in the standard library (e.g., empty, void, or Void.t)
There have been lots of discussions about empty types. (See https://github.com/ocaml/ocaml/issues/9459, https://github.com/ocaml/ocaml/issues/9975, https://github.com/ocaml/ocaml/issues/10687 on polymorphic ones, ....) I'd like to throw in yet another proposal that seems to provide some immediate benefits without a need to hack the type-checking algorithm. That is, to define an empty variant type directly in the standard library.

## Pros

* No changes to the type system!
* The undesirable generativity can be solved in practice by using literally the same empty type.

## Cons

* Yet another name would be taken. I personally prefer `void` or `Void.t` because `empty` and `Empty` seem to be popular.
* This does not implement any advanced feature (subtyping, etc.) requested in other GitHub issues.

### PR DESCRIPTION
**Pull request by favonia**
~~This PR is a draft because some tests were skipped (and thus the expected outputs were not updated)---most related to `no-flat-float-array` and `flambda`. I hope the CI will pick up all skipped tests. It is expected that the compiler will output different error messages due to the introduction of a new type.~~ Magically, the CI passed---even though I did not update those test cases. I suppose it's ready for review.

Closes #11265. Related: #9459 and #10552. 

---

About copyrights: If this PR is protected by copyright (not sure), I intend to assign the copyright of my contribution to the GitHub repository ocaml/ocaml to INRIA and/or whatever "OCaml programmers" refer to. Is that okay? If this is not possible, I am using [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) to waive all my rights to the extent allowed by law. Should I still sign the CLA?

### CODE REVIEW

**Comment by favonia** [comment]
I'm surprised that all tests were passed---I thought the backtrace outputs for the flambda variant would change, for example. I guess this PR is ready for review.

**Comment by gasche** [comment]
My motivation for supporting a built-in empty type is https://github.com/ocaml/ocaml/issues/10552#issue-958838670, which asks for a bottom type that is a subtype of everything. This is not achieved in the present PR, which merely gives a standard generative/nominal empty variant type. (Here "variant" means "sum type", not "polymorphic variant".)

Personally I would feel better with a built-in *non-variant* type that is a subtype of everything, instead of adding a non-structural subtyping relation just for empty variants. My take-away of the discussion in #9459 is that I'm not alone with this gut feeling / opinion.

Summary: your proposal is not quite what I was hoping for; a built-in type that is not declared as a variant, and is a subtype of everything. It may not be that easy to implement.

Re. copyright: non-trivial contributions are expected to come with a Contributor License Agreement (CLA), that gives relicensing rights to INRIA. See [CONTRIBUTING.md#CLA](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#contributor-license-agreement). You've given a lot of nice feedback and useful contributions in the last few months, I hope you consider signing the CLA and contributing even more in the future :-)

**Comment by favonia** [comment]
Got it. Should we close this PR, then? I do have cases where a variant empty type is enough. However, having a variant empty type _now_ will make the adoption of a non-variant empty type in the future more difficult, because that would constitute a change to the standard library. It's probably better not to have any built-in empty type until we are ready to have the best one.

Re: copyright: I wasn't sure if this PR is "significant" enough. And I want to just assign the copyright to INRIA (as in the FSF-style CLA) so that INRIA has the fullest power allowed by the law, because I want INRIA to handle any potential legal issues (if any) without notifying me. This is much stronger than giving INRIA the re-licensing right.

**Comment by favonia** [comment]
I don't feel this PR can go anywhere because so I am closing this.

**Pull request closed without merging**
