### PR TITLE
Revert user defined indexing operators

### PR DESCRIPTION
**Pull request by gasche**
During the last developer meeting, we realized that there were competing proposals about how to define indexing operator that was worth considering as a short-to-medium-term evolution of the OCaml language (one suggestion was to resolve them in a type-directed way, similar to record projections, instead of by binding scope as currently done in trunk).

Because this proposal is in direct conflict with the @octachron's feature of user-defined indexing operators (GPR #69), which has not been part of an OCaml release yet, we decided to pull user-defined indexing operators _out_ of the next OCaml release (4.03), to give us more time to evaluate where we want to go with indexing operators.

This PR implements this decision: it reverts the various patches implementing and documenting indexing operators. Because it impacted various aspect of the language (typing, parsing, new compiler primitives, bigarrays...), some posterior changes had mixed with the patches code and conflicts had to be manually resolved -- this is not just a mechanical "git revert" application.

I would like to also create a `user-defined-indexing-operators` branch in the ocaml/ocaml repository, that keeps the feature. I would like to keep this branch synchronized with the trunk branch, so that by the 4.03 release time we have an easy way to test the 4.03 release _plus_ user-defined indexing operators. (Contributions to help maintain this branch would be very much appreciated, given that my own time to do so will be rather limited.) One thing that _should_ go into this branch is a patch to avoid the current Bigarray breakage (users of the (.{..})  operators need to `open Bigarray`) by catching the identifier-lookup error and falling back to the correct `Bigarray.{..}` operator

### CODE REVIEW

**Comment by lpw25** [comment]
>  we realized that there were competing proposals about how to define indexing operator that was worth considering

I would just like to clarify that the other proposal is _not_ a competing proposal for defining indexing operators. It is a proposal to allow defining fresh array types, which _requires_ at least one non-user-definable indexing operator for use with these types. The conflict arises because the user-defined indexing operators proposal makes all operators user-definable, leaving none available for use with the new array types.

**Comment by ghost** [comment]
There is also 7a318f1a6406a970a8054d972d10a5b1c3350373 for the pretty-printing. I did some refactoring at the same time, so it's better not to git revert it. I can update pprintast.ml once this is merged.

**Comment by gasche** [comment]
@diml thanks for watching this! If you can write the not-quite-a-revert commit and send it to me, I'll include it in the PR.

**Comment by gasche** [comment]
(I just uploaded Jérémie's patch.)

**Comment by alainfrisch** [comment]
Out of curiosity, what does the cwn label mean?

**Comment by gasche** [comment]
@alainfrisch it means [Caml Weekly News](http://alan.petitepomme.net/cwn/); Alan can include the marked PRs in his weekly newsletter (a couple at a time).

**Comment by gasche** [comment]
I just merged this, and pushed a branch [user-defined-indexing-operators](https://github.com/ocaml/ocaml/tree/user-defined-indexing-operators) in the central repository.

We are still missing two commits in `user-defined-indexing-operators`:
- one implementing the fallback logic for `Bigarray.({..})` operators: when identifier lookup fails on a `(.{..})` operator, emit a warning and fallback to `Bigarray.({...})`
- one adding a `Bigarray.Operators` submodule to indicate in the aforementioned warning (I think there should be a mergeable PR lying around for this part)

**Pull request merged**
