### PR TITLE
ocaml tool to extract opcode information

### PR DESCRIPTION
**Pull request by nojb**
Re-submission of #449, rebased and squashed onto trunk.

### CODE REVIEW

**Comment by mshinwell** [comment]
@nojb Please resolve conflicts
@gasche Please confirm you still approve, like you said for #449.

**Comment by nojb** [comment]
Done.

**Comment by gasche** [comment]
I approve and @damiendoligez in #449 seemed happy with the patch as well.

On first sight this seems to fall under Xavier's "if it ain't broke..." principle, but [the idea comes from Xavier in the first place](https://github.com/ocaml/ocaml/pull/307#issuecomment-162002012) and we have had much more trouble with `sed` than with `ocaml` in the build system in the past, so it does seem wise.

**Comment by mshinwell** [comment]
@nojb Please add a Changes entry.

**Comment by nojb** [comment]
I thought only user-visible changes go into Changes.

**Comment by gasche** [comment]
It's also a way to keep a trace of the people that make nice contributions. The "### Compiler distribution build system" category would be a good fit for this change.

**Comment by nojb** [comment]
Done. Thanks!

**Comment by gasche** [comment]
Thanks, merged.

**Pull request merged**
