### PR TITLE
MPR#7631: -linscan option crashes ocamlopt

### PR DESCRIPTION
**Pull request by xclerc**
Bug cause: when frame pointers are enabled, there is a register such
that its index >= `Proc.num_available_registers.(c)` where `c` is the
register class, but the linear scan allocator builds a *map* from register
indexes to their availabilities as an array (namely `regmask`) of size
`Proc.num_available_registers.(c)`.

Proposed fix: protect access to `regmask` according to its size. It means
that the availability of a register with index >= `Proc.num_available_registers.(c)`
is not set, but it should be fine, as registers with such indexes are not
considered by the `assign` function.

### CODE REVIEW

**Comment by gasche** [comment]
That was very fast, thanks!

Could you add a Changes entry, and a comment on the `regmask` declaration that some registers may fall off-bounds and its accesses should be protected?

**Comment by xclerc** [comment]
Done.

**Review by gasche — APPROVED** [review]

**Comment by xclerc** [comment]
(if the fix is deemed correct, it should be considered for inclusion in 4.06.)

**Comment by gasche** [comment]
I'd be happy to merge and cherry-pick, but I would like to understand why there was an AppVeyor failure. When I looked, it seemed ocamltest-related, so maybe we could merge here in any case, but I'd rather find out the issue and fix it as we do want a functioning Windows CI.

**Comment by xclerc** [comment]
I do agree - however, I have seen the same failure in e.g. #1334,
meaning it is quite probably not related to my patch...

**Comment by gasche** [comment]
I left a comment on the ocamltest PR ( https://github.com/ocaml/ocaml/pull/681#issuecomment-330526195 ). I'll merge this (and cherry-pick) when the Travis CI completes, so that we can ask the Coq people for another round of testing.

**Comment by gasche** [comment]
Cherry-picked in 4.06: e5bc07a128b83a352779d92dc4dfe6741ead21f2

**Pull request merged**
