### PR TITLE
Change the alignment of the errors/warnings main message

### PR DESCRIPTION
**Pull request by Armael**
Following #2035, this PR proposes to change the way the body of the message is aligned in errors and warnings.

In order to avoid wasting terminal columns, it changes the current setup, where the body of the message is aligned on the right of `Error: `, `Warning x: ` (or in the future `Alert <arbitrarily long string>:`), and instead inserts a line break after `Error: ` (/...) if the message does not fit on a single line.

As one might expect, this impacts more or less all error messages of the testsuite, hence the huge diff.

The first commit also contains a fix for a bug I noticed when creating this PR, which I found hard to isolate (because not exercised by the current errors of the compiler, and hard to test because specific to the toplevel).

### CODE REVIEW

**Comment by gasche** [comment]
Example from the testsuite changes:

```
(* before *)
Warning 8: this pattern-matching is not exhaustive.

(* after *)
Warning 8:
this pattern-matching is not exhaustive.
```

```
(* before *)
Error: Cannot safely evaluate the definition of the following cycle
       of recursively-defined modules: B -> E -> D -> C -> B.
       There are no safe modules in this cycle (see manual section 8.3)

(* after *)
Error:
Cannot safely evaluate the definition of the following cycle
of recursively-defined modules: B -> E -> D -> C -> B.
There are no safe modules in this cycle (see manual section 8.3)
```

I must say that I don't like the changes much:
- Having one more line in general makes printing less compact.
- I find that the indentation helped visually delimit where the error starts and stop. (But maybe it matters less in a terminal with color highlighting the "Error" and "Warning" starts.)

**Comment by gasche** [comment]
Would it be possible to solve your concern with `Alert <long name>:` by indenting by a fixed amount (say, 2) on every next line?

**Comment by Armael** [comment]
> I must say that I don't like the changes much:

To be honest I'm not completely satisfied with the current status of the PR myself -- it is open for discussion.

```
(* before *)
Warning 8: this pattern-matching is not exhaustive.

(* after *)
Warning 8:
this pattern-matching is not exhaustive.
```
This is because this is not the whole message: this sentence is followed by `Here is an example of case...`, and the message is defined in a monolithic fashion. This can be improved, on top of the current PR, by splitting the message into `this pattern-matching is not exhaustive` as the main message, and the rest as a sub-message.

> Would it be possible to solve your concern with Alert <long name>: by indenting by a fixed amount (say, 2) on every next line?

Do you mean turning:
```
Error:
Cannot safely evaluate the definition of the following cycle
of recursively-defined modules: B -> E -> D -> C -> B.
There are no safe modules in this cycle (see manual section 8.3)
```
into
```
Error:
  Cannot safely evaluate the definition of the following cycle
  of recursively-defined modules: B -> E -> D -> C -> B.
  There are no safe modules in this cycle (see manual section 8.3)
```

If so that's surely possible and easy to do, yes.

**Comment by gasche** [comment]
Ideally I would be the first line to follow the marker unindented, and only the following lines indented:

```
Error: Cannot safely evaluate the definition of the following cycle
  of recursively-defined modules: B -> E -> D -> C -> B.
  There are no safe modules in this cycle (see manual section 8.3)
```

**Comment by Armael** [comment]
Hum, I'm not sure this is easily possible: typically the body of the message has been wrapped in a format box by the part of the code that emitted the error (and I think that's a good thing).

Assuming that `Cannot safely ... section 8.3)` is wrapped in a format box, I don't know how to obtain what you show above. Maybe some Format experts will have an idea? (cc @Drup @Octachron )

**Comment by Octachron** [comment]
It seems indeed hard without modifying the warning messages: Format's layout engine prefers to insert breaks in parent boxes when it is possible to do so.

**Comment by gasche** [comment]
I'm still unconvinced by the way the proposed change adds a new line to each warning or error message, and I would propose to close the PR for now.

**Comment by Armael** [comment]
sure.

**Pull request closed without merging**
