### PR TITLE
Remove Const_pointer from Lambda and Clambda

### PR DESCRIPTION
**Pull request by stedolan**
Lambda and Clambda distinguish Const_int from Const_pointer only so that they can pass the information to Cmm. But now that that Const_pointer is gone from Cmm (#9578), there's no need for the distinction in Lambda either. (This roughly un-reverts @lthls's #1580).

While preparing this PR, I only found one case where the compiler distinguishes between `Const_int` and `Const_pointer`: in Flambda, a different subset of primitives were constant-folded in the two cases. Removing the distinction means that slightly more constant folding can be done. In particular, when compiled with Flambda this function does an allocation on trunk but returns a constant with this patch:

    let z () = Int64.of_int (Bool.to_int false)

This PR contains a bootstrap, because the `.cmo` format changes: `Lambda.structured_constant` has one fewer constructor.

### CODE REVIEW

**Review by xavierleroy — APPROVED** [review]
This is a nice simplifcation and cleanup of the "middle end".  It's a big change, but quite systematic.  I only skimmed the Flambda parts because I'm not too familiar with this part of the code.  I'm quite confident about the changes to the other parts.

This PR contains a bootstrap, so it will have to be merged manually, doing the bootstrap in a separate commit.

It would be good to have a second pair of eyes looking at this PR: @lthis? @chambart ?

**Review by lthls — APPROVED** [review]
I've looked at the changes, with a particular focus on the flambda parts, and everything looks fine.

**Comment by xavierleroy** [comment]
Thanks @lthis for the second review.  Now I'll try to merge.

**Comment by xavierleroy** [comment]
Manually merged as 0d44a6cfe (source changes) and 0ca651b95 (bootstrap).

**Pull request closed without merging**
