### PR TITLE
Fix Unix.create_process cmdline escaping windows

### PR DESCRIPTION
**Pull request by fdopen**
A new pull request, so that https://github.com/ocaml/ocaml/pull/1038#issuecomment-279425487 isn't forgotten.

The current quoting algorithm seem to be correct, but parameters with `'\t'` are not quoted, although they must be quoted. However, neither `'\n'` nor `'\011'` (vertical tab) need quoting (contrary to https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/).

I've cherry-picked the test case from @nojb  (slightly edited). A not included brute force test ( https://gist.github.com/anonymous/4a98fa17cffaaffc8775ab36286e3e70 ) didn't reveal any further problems (beside the ones that are imposed by the windows API).

### CODE REVIEW

**Comment by nojb** [comment]
Thanks!

I take the liberty of piggybacking on your PR to mention that the documentation of `Unix.in_channel_of_descr` seems to be incorrect: it states that the function `Unix.set_binary_mode_in` will always fail on channels created by that function under Windows.  But this is not the case (as the test shows).

**Comment by xavierleroy** [comment]
This looks good to me.  CI is unhappy because there is no Changes entry but we can fix that.  I'm in favor of merging in master.  @damiendoligez do you want it in 4.05 as well?

**Comment by xavierleroy** [comment]
@nojb: yes, the doc of `Unix.in_channel_of_descr` is weird.  What is not supported is text mode on channels over sockets.

**Comment by damiendoligez** [comment]
This is a bugfix that warrants a `Changes` entry. Let's have it both in trunk and in 4.05.

**Comment by xavierleroy** [comment]
Merged in trunk and cherry-picked for 4.05.

This is the first time that I cherry-pick a merge.  Hope I did it right.

**Pull request merged**
