### PR TITLE
Add --disable-ocamltest to configure

### PR DESCRIPTION
**Pull request by dra27**
This PR adds `--disable-ocamltest` to go alongside `--disable-ocamldoc` and `--disable-debugger`.

We don't install `ocamltest`, and I don't expect we're likely to in the near future, which means it would be sensible for opam to be using this switch, but it also makes me wonder if we should stop building `ocamltest` by default. `make -C testsuite all` *could* check that `ocamltest` is built (in the same way as it checks that the testsuite libraries are built). Alternatively, `ocamltest` could be built by default for development builds (in the same way as `-Werror` is activated).

@shindere, what do you think?

### CODE REVIEW

**Review by nojb — APPROVED** [review]
LGTM

**Review by shindere — APPROVED** [review]

**Comment by shindere** [comment]
Sorry for being very late on that one. Just approved.

@dra27 you may want to update the Changes entry.

David Allsopp (2020/01/16 08:59 -0800):
> This PR adds `--disable-ocamltest` to go alongside
> `--disable-ocamldoc` and `--disable-debugger`.

That's a very good idea, thanks.

> We don&#39;t install `ocamltest`, and I don&#39;t expect we&#39;re
> likely to in the near future,

Unfortunately, indeed. :)

It was my hope that ocamltest could become useful to other ocmal
projects, but I am indeed not sure this is going to happen soon.

> which means it would be sensible for
> opam to be using this switch,

yeah, and likewise for all distribution packaging.

> but it also makes me wonder if we should
> stop building `ocamltest` by default. `make -C testsuite all` *could*
> check that `ocamltest` is built (in the same way as it checks that the
> testsuite libraries are built). Alternatively, `ocamltest` could be
> built by default for development builds (in the same way as `-Werror`
> is activated).


>
> @shindere, what do you think?

No strong opinion, I have to say. Especially given that it remains
possible for every developer to enable it in his/her personal
configuration.

Thanks again for the work!

Will be happy to press the merge button as soon as the Changes entry has
been completed, I think @nojb reviewed the code, too.

@dra27 would you mind leaivng a short note here? I am not always
notified when changes are pushed to a branch, I don't know what decides
whether I get notified or not.

**Comment by dra27** [comment]
Thanks, @shindere - I've updated `Changes` but pushed an additional commit which changes the default. As with `-Werror`, if the version contains `+dev` then ocamltest is built by default, otherwise it is not. I've added `--enable-ocamltest` to all the relevant parts of the CI scripts, but it's belt and braces because even at release the tip of the branch doesn't have a non-dev `VERSION`

**Comment by shindere** [comment]
David Allsopp (2020/02/13 08:57 -0800):
> Thanks, @shindere - I've updated `Changes` but pushed an additional
> commit which changes the default.

Ah, I didn't necessarily expect that to happen in this PR, but why not,
after all.

**Pull request merged**
