### PR TITLE
Remove spurious file in testsuite

### PR DESCRIPTION
**Pull request by shindere**
This PR removes an unused file
introduced by commit
6526a0c3d9457705fa5403650f0810e7cc2a2965

It is important to remove this file because it does not quite work:
it assumes ocamlc.byte has already been installed and thus uses an
installed compiler rather than the one to test so that would be a
misleading source of inspiration for test writers.

Cc @mshinwell

### CODE REVIEW

**Review by damiendoligez — APPROVED** [review]
Looks fine.

**Comment by shindere** [comment]
Thanks!

**Comment by shindere** [comment]
Merged and cherry-picked to 4.08.

**Comment by trefis** [comment]
Seems like c4d0fec0251883decc6e82fc243159b785c4e874 was manually pushed to trunk.
Closing.

**Pull request closed without merging**
