### PR TITLE
Remove otherlibs/num [WIP]

### PR DESCRIPTION
**Pull request by xavierleroy**
This is an attempt at removing the "num" library for arbitrary-precision arithmetic from the core OCaml system.  A standalone distribution of this library already exists and is hosted at https://github.com/ocaml/num . 

Do not merge yet: I'm making a pull request out of this branch so that it becomes available as an opam switch, making it easier to create the appropriate OPAM packages for the "num" library.

### CODE REVIEW

**Comment by gasche** [comment]
The `4.06.0+pr1178` switch should now be available.

**Comment by xavierleroy** [comment]
Much appreciated, thanks.

**Comment by xavierleroy** [comment]
Progress report:
* Dummy `base-num` and `num`-version-0 packages were added to OPAM.
* Dependencies on package `num` were added to many OPAM packages that seem to use the Num library.
* The latest ocamlfind is compatible with the removal of Num from the base OCaml installation (this PR).
* The `num` package version 1.0 (based on https://github.com/ocaml/num) is ready and was tested locally.

Next steps (to be done as atomically as possible):
* Merge this PR, removing the Num library from the base OCaml installation
* Say that the `base-num` package is not available in 4.06 and up
* Publish the `num` package version 1.0 in OPAM.

To do in time for 4.06 freeze.

**Review by mshinwell — APPROVED** [review]

**Comment by xavierleroy** [comment]
Rebased, added Changes entry, and removed WIP label.  Ready for merging...

**Comment by xavierleroy** [comment]
AppVeyor failure is unrelated (can't download 7zip...).  Merging!

**Comment by Octachron** [comment]
The manual would need to be updated to replace the documention of num with a reference to its new home. Would you prefer that I take care of this point?

**Comment by xavierleroy** [comment]
I forgot to update the manual myself, indeed, but it's extremely nice of you to volunteer, thank you!  

You may want to wait a few days until it's confirmed that the OPAM side of this procedure (adding packages for the standalone Num library, etc) work.

**Pull request merged**
