### PR TITLE
Allow more module aliases in strengthening

### PR DESCRIPTION
**Pull request by lpw25**
This PR adds explicit support for module aliases which at runtime are represented by the aliased module, in addition to the ordinary module aliases which have no runtime representation (or more accurately are often represented by `()` at runtime). The presence or absence of a runtime representation is represented by the type:

```
type alias_presence =
  | Mta_present
  | Mta_absent
```

This means we can safely treat:

```
module M = struct module A = ... module B = ... end
```

as having type:

```
sig module A = M.A module B = M.B end
```

without producing gratuitous coercions that reconstruct M from its constituent parts.

As a simple example, the following file:

```
module M = struct module B = struct end end

module N : sig module B : sig end end = M
```

produces this lambda code with trunk:

```
(setglobal Test!
  (let (M/1199 = (let (B/1200 = (makeblock 0)) (makeblock 0 B/1200)))
    (makeblock 0 M/1199 (makeblock 0 (field 0 M/1199)))))
```

whereas with this patch it produces:

```
(setglobal Test!
  (let (M/1199 = (let (B/1200 = (makeblock 0)) (makeblock 0 B/1200)))
    (makeblock 0 M/1199 M/1199)))
```

Note that `N` is defined directly as `M` rather than as a fresh block.

In addition, this PR takes advantage of the improved handling of alias coercions to add module aliases when strengthening during module inclusion checks. This allows examples such as:

```
module F (X : sig end) = struct type t end;;
module M : sig
  type a
  module Foo : sig
    module Bar : sig end
    type b = a
  end
end = struct
  module Foo = struct
    module Bar = struct end
    type b = F(Bar).t
  end
  type a = Foo.b
end;;
```

to be type-checked successfully.

The above is a reduced example of a pattern that we naturally encounter in Jane Street and the work-around is fairly painful, so fixing it would be a definite plus.

Finally, I believe this support would be a prerequisite for supporting aliases to functor applications, if we decide to go down that route.

### CODE REVIEW

**Comment by alainfrisch** [comment]
Cosmetic remark: several functions get a new `bool` argument;  I think it would make the core more readable if that argument was labeled.

**Comment by lpw25** [comment]
True. I'll fix.

**Comment by lpw25** [comment]
Fixed

**Comment by gasche** [comment]
This change seems to break camlp4 (according to the CI), and the is no changelog entry.

**Comment by garrigue** [comment]
This looks ok, but we may still have trouble when introducing aliases of functor applications.
Namely, IIRC, we may end up in situations where there are two aliases, a concrete one (i.e. absent in your naming) and a stronger one, valid only for module equality.
I'm not sure you can always factorize in these situation (i.e. have the stronger alias be a concrete alias pointing to a present alias).
It would be worth checking that first, as this changes the way we should represent aliases.

**Comment by lpw25** [comment]
I've fixed the problem with camlp4, added a changelog entry and done a bootstrap.

**Comment by lpw25** [comment]
@garrigue I'm not sure I quite follow you. Are you talking about something like:

``` ocaml
module M : sig ... end
module N a= M
module O p= N
```

(where `a=` is an absent alias and `p=` is a present alias).

Does the problem you are concerned about only appear once you start trying to alias functor applications? If so, would it be alright to merge this as is and then reevaluate the approach when we start trying to do that? Because I would like to fix the example in the PR description for 4.04 if possible.

**Comment by garrigue** [comment]
OK, maybe I didn't understand everything correctly.
Do you allow to alias things that couldn't be aliased before (such as functor arguments),
or do you only introduce an optimization on coercion generation, and use it to introduce more aliases (at low cost)?

In order to handle aliases of functor applications, one needs really two different notions of alias, and sometimes both simultaneously, so what you are doing here may be completely orthogonal to that.

**Comment by lpw25** [comment]
> Do you allow to alias things that couldn't be aliased before (such as functor arguments)

No, it should have the same restrictions as before

> do you only introduce an optimization on coercion generation, and use it to introduce more aliases (at low cost)?

Exactly.

I  only mentioned aliases to functor application as I believe that such aliases would need to hold the result of applying the functor at runtime, so they would need to have the notion of "alias that has its value at runtime" which this PR introduces.

> In order to handle aliases of functor applications, one needs really two different notions of alias, and sometimes both simultaneously, so what you are doing here may be completely orthogonal to that.

I had thought that aliases to functor applications were relatively simple (unlike aliases to functor arguments -- which I believe require something like transparent ascription). Whilst they are not directly relevant to this PR, I am quite interested in them, so would you mind giving an example to show why two notions of alias are needed and especially why they might be needed simultaneously.

**Comment by garrigue** [comment]
> > do you only introduce an optimization on coercion generation, and use it to introduce more aliases (at low cost)?
> 
> Exactly.

OK, then there is no theoretical problem.
However I wonder whether you can really do without an explicit syntax for those: how are you going to write in a mli that the implementation is present? Or is it just limited to analysis inside the same module?

> I had thought that aliases to functor applications were relatively simple (unlike aliases to functor arguments -- which I believe require something like transparent ascription). Whilst they are not directly relevant to this PR, I am quite interested in them, so would you mind giving an example to show why two notions of alias are needed and especially why they might be needed simultaneously.

Not sure I can recall everything just now. If you only want to have aliases of functor applications, then things are still simple indeed, since one can recompute the signature from the path. Note however that this still differs from your notion of present/absent, because in your case you can expend the alias when looking for an implementation even if it present, whereas with functor applications you would need a way to say that the alias can only be expended when checking module path equality. But this is not too complex as no diamond situation seems to appear.
Things seemed more complex if you also allow aliases of functor arguments, and keeping aliases when coercing modules, which would make module equality stronger.
The idea then would be to have a different syntax in signatures:

```
module M : MT = Path
```

Thinking of it now, it still seems ok: those would just behave like aliases of functor applications, just with an explicit type.
So my conclusion for now is that, for these features, this is probably ok, but that we need a way to have both an alias and a concrete type, meaning that the change is not going to be completely trivial.

There is one last thing that I had probably in mind: completely separating type dependencies from object dependencies. I.e. allow to write something like

```
module M = (Path1 : MT) = Path2
```

Here Path1 is used for type equality, and Path2 for linking.
One potential advantage is not having to refer to the file containing Path2 at compile time, only at link time. But I admit that this was not explored so much.

**Comment by lpw25** [comment]
> However I wonder whether you can really do without an explicit syntax for those: how are you going to write in a mli that the implementation is present? Or is it just limited to analysis inside the same module?

I don't think an explicit syntax is needed, as present aliases are just an optimization, and the optimization is really targeted at allowing the type-checker to give a more accurate type to a module which is about to be used at a given type. For cases where the user is making the aliases themselves I don't think the optimization really matters.

> Note however that this still differs from your notion of present/absent, because in your case you can expend the alias when looking for an implementation even if it present, whereas with functor applications you would need a way to say that the alias can only be expended when checking module path equality.

Good point. This would indeed need more care for functor applications.

> The idea then would be to have a different syntax in signatures:
> 
> module M : MT = Path

Yes that is what I was referring to as "something like transparent ascription". I had in mind direct support for a transparent ascription syntax (probably using `:>`) more generally, as it is a useful feature on its own.

So:

```
module Foo = (Bar :> S)
```

or

```
module Foo :> S = Bar
```

would produce a module `Foo` that only contained the elements of `S` but was still known to be an alias of `Bar`.

It would also work with unnamed structures, for example:

```
module Foo :> S = struct
  type t = foo
  ...
end
```

would have module type `S with type t = foo`

Beyond functor argument aliases this would also be useful for `open`:

```
open (Bar :> Monad.S)
```

and for modular implicits when you want to ensure that an implicit module matches the desired syntax without writing out all the required type aliases:

```
implicit module ListMonad :> Monad.S = struct
  type 'a t = 'a list
  ...
end
```

**Comment by gasche** [comment]
For the record, [MPR#7302](http://caml.inria.fr/mantis/view.php?id=7302) is a severe compile-time regression caused by 4.03 aliases removing some sharing compared to 4.02, which seems to be fixed by the present PR.

**Comment by lpw25** [comment]
That compile-time regression has actually come up quite often for us internally now that we've switched to 4.03.0. We're probably going to have to use a version of 4.03.0 with this patch applied.

@garrigue Are you okay with this being merged as is, or would you like some additional discussion/review?

**Comment by garrigue** [comment]
My only remaining concern was the potential impact on printed types, but seeing that this fixes an important regression, the priority is on merging it now. So this is go.

**Comment by gasche** [comment]
Merging this branch caused a continuous integration failure on trunk-cygwin64 configurations, both with and without flambda:

```
List of failed tests:
    tests/lib-threads/fileio.ml
    tests/tool-debugger/basic
    tests/lib-systhreads/testfork.ml
    tests/tool-debugger/no_debug_event
```

This seems likely to come from the bootstrap commit rather than the branch changes itself, but it is still problematic and should be fixed.

**Comment by gasche** [comment]
On the trunk-cygwin64+flambda configuration, the failure report is actually as follows:

```
List of failed tests:
    tests/lib-threads/fileio.ml
    tests/tool-debugger/basic
    tests/lib-systhreads/testfork.ml
    tests/tool-debugger/find-artifacts

List of unexpected errors:
    tests/lib-scanf-2
```

Edit: `lib-scanf-2` failure also observed without flambda since the bootstrap commit.

**Comment by lpw25** [comment]
I didn't get any failures on my machine, or with the Travis CI. As you say, it is probably from the bootstrap, are there any obvious recent changes that might break cygwin on bootstrap? Does anyone with a cygwin configuration have time to figure out the issue?

**Comment by lpw25** [comment]
Yes, I suspected it might be. It's also possibly the cause of 7314. I'll try to have a look at both of them tomorrow.

**Comment by garrigue** [comment]
Looking at your code, I'm confused by the way you discarded all calls to Env.add_functor_arg, while keeping the function. Could you explain the logic behind that.

**Comment by lpw25** [comment]
I discarded those calls to `Env.add_functor_arg` as I felt they were better handled using an `aliasable` parameter for `Mtype.strengthen`: they weren't being used for functor arguments but just to prevent aliasing during strengthening, so it seemed better to handle that directly.

The "`functor_arg`" tracking is still used for actual functor arguments, so `add_functor_arg` is still needed. However, I hadn't noticed that the only use is now within `Env` so I guess it should probably be removed from `Env`'s interface.

**Comment by garrigue** [comment]
OK, I agree that the use of `add_functor_arg` for `strengthen` was a bit hacky.
Note that now `add_functor_arg` is actually only used through `Env.enter_module`, so it would even be more natural if `Env.add_module` did not export it.

**Comment by lpw25** [comment]
It seems that [7313](http://caml.inria.fr/mantis/view.php?id=7313) is uncovered by this patch rather than caused by it.  You get the same error with the commit before this PR was merged, if you change the code slightly:

bug.ml:

```
let mk_fun () = ref (fun () -> assert false)


module T = struct
  module B = struct
    type t_ctx = A
    let f = mk_fun ()
  end
end

module R = T
```

bug.mli:

```
module R : sig
  module B : sig
    type t_ctx = A
    val f: (unit -> t_ctx) ref
  end
end
```

Which doesn't give an error in 4.03. So there has been a regression, but I don't think it is in this PR.

**Comment by gasche** [comment]
Bisecting tells me that the change that broke this example is e85ba9c77f680ab574b0836830554c2b4b74091a . cc: @garrigue

**Pull request merged**
