### PR TITLE
Fix `unix_getsockopt_aux` always returning EINVAL.

### PR DESCRIPTION
**Pull request by dbuenzli**
Regression introduced by f022f9b9d2f8598.

/cc @nojb

### CODE REVIEW

**Comment by gasche** [comment]
Oops! I'm afraid that otherlibs/win32unix/sockopt.c also needs fixing.

**Review by nojb — COMMENTED** [review]
Oomph. Embarrassing. LGTM, but as @gasche observed the sme fix is need in the Windos version of `sockopt.c`. Thanks!

**Comment by dbuenzli** [comment]
Sorry, indeed, I was too eager to fix "my" problem. I amended the commit.

**Review by nojb — APPROVED** [review]
LGTM. Good to merge if CI passes.

**Comment by gasche** [comment]
Merged, thanks!

**Pull request merged**
