### PR TITLE
Make OCaml case-insensitive

### PR DESCRIPTION
**Pull request by Drup**
With reasonML and bucklescript, the ocaml community has received an influx of programmers coming from Web programming languages, notably Javascript. While OCaml programmers traditionally follow the snake_case convention, these new programmers usually follow the camlCase convention. The camlCase convention also has the advantage of mapping very well to Javascript APIs, and has thus been adopted by
new libraries, notably Bucklescript's alternative standard library, [Belt](https://bucklescript.github.io/bucklescript/api/Belt.html).

This has led to some [remarks](https://github.com/facebook/reason/issues/1689) and quite a bit of churn, which led to the creation of libraries such as [Tablecloth](https://github.com/darklang/tablecloth#design-of-tablecloth) which offers wrappers over both Core and Belt to provide both camlCase and snake_case.

This patchset makes the typechecker insensitive to cases. identifiers can be arbitrarily used in camlCase or snake_case. Example:

```ocaml
# let some_int = 2 ;;
val some_int : int = 2
# stringOfInt someInt ;;
- : string = "2"
```

The printers have also been adapted and can be toggled to snake_case of camlCase at will via both toplevel directives and compiler options.

```ocaml
# type foo_bar = Foo_bar of int | BarBaz of fooBar ;;
type foo_bar = Foo_bar of int | Bar_baz of foo_bar
# #camelCase true ;;
# Bar_baz (FooBar 3) ;;
- : fooBar = BarBaz (FooBar 3)
```

## Implementation

The changes are done at the typechecker level, which means that alternative syntaxes such as Reason and ppxs also benefits from such changes transparently. Practically, the tables in `Env` now use a modified comparison function that turns everything into snake_case before doing a comparison. The implementation of some warnings have not been adapted yet.

Naturally, the `snake_case` comparison is performance sensitive. I have not optimized it fully. I believe the perf impact will be negligible in practice once it is done.

The change itself is implemented by https://github.com/ocaml/ocaml/commit/1c25d9772dd03e5714c736486c5fd250e43ab02b but can be seen in action in the printer changes (https://github.com/ocaml/ocaml/commit/f98d6c26d6477bca8c17b22e2a19f7dc05382ebf).

## Breakage and adoption

One might fear that such change could cause breakage in the OCaml and Reason ecosystem. Considering that this patch had to modify various pieces of the compiler (`mk_i`/`mk_I` and various constructors in format), this seems justified. This could be mitigated by first enabling warnings that indicate identifiers that would conflict, if they were case-translated, before enabling this change, similar to what was done for safe strings. I believe this change is worth it.

Thanks to @Armael for the initial idea. cc @jordwalke

### CODE REVIEW

**Comment by Drup** [comment]
It has been brought to my attention that this feature, which might seem fairly unusual and unsightly at first, is in fact already present in [Nim](https://narimiran.github.io/nim-basics/#_variable_declaration):

> Note however that Nim is both case- and underscore-insensitive meaning that helloWorld and hello_world would be the same name. The exception to this is the first character, which is case-sensitive. Names can also include both numbers and other UTF-8 characters, even emojis should you wish that, but keep in mind you and possibly others will have to type them

So, there is a strong precedent of this feature which could help us evaluate how beneficial it is in practice.

**Comment by hcarty** [comment]
All date-related issues aside, this would be really really nice to have.  It would help a lot with ecosystem fragmentation over the aesthetic choices of snake_case vs camelCase.

**Comment by jordwalke** [comment]
This one is a little too real since it is often requested. I think we *should* seriously think about a way to avoid large forks of libraries on the basis of naming convention alone. If anyone has a serious suggestion about how to do this less invasively, I'm all ears.

**Comment by Drup** [comment]
@jordwalke made some various comments regarding the production-readiness of this change, notably concerning ocamldep. I'll close this PR in the meantime, and will revisit it later, depending on user requests.

**Comment by msvbg** [comment]
This may or may not have been an April fools' joke, but I think it's not a completely terrible idea.

**Pull request closed without merging**
