### PR TITLE
Merge debugger/Makefile into the root Makefile

### PR DESCRIPTION
**Pull request by shindere**
This continues the work started in #11243, #11248, #11268, #11420 and #11675.

### CODE REVIEW

**Comment by shindere** [comment]
Note that, to be consistent with the rest of the build system, this PR
enables `-g` for ocamldebug.

Also, the debugger's dependencies are computed in `debugger/.depend` as
before, so that it is simple to specifiy a different list of directories.

**Comment by shindere** [comment]
This branch now starts with two commits that may seem unrelated but here is
what they are and why they are here.

On trunk, `make alldepend` computes the dependencies for the other libraries
*before* those of the debugger, ocamldoc and ocamltest. This matters in a
slightly subtle way because, on trunk, it's the computation of the
dependencies for the Unix library which
creates the `otherlibs/unix/unix.ml`
file (when building a minimal compiler as is done to verify the dependencies
by our GitHub actions), whose existence has an impact on the
dependencies as computed e.g. for the debugger.

On the PR branch, the order enforced on trunk is no longer enforced so that
there is no guarantee that `otherlibs/unix/unix.ml` exists when the
dependencies for the debugger get computed.

Although it would be possible to impose an ordering on the computation of
the dependencies as was done on trunk by using constraints on GNU make
targets, that looks convoluted (and, actually, a bit artificial and not very
well justified) and it felt both simpler and more accurate to jsut generate
`otherlibs/unix/unix.ml` as part of the configure stage.

That's what the first commit of this PR does, using the `AC_CONFIG_LINKS`
macro to create a link in the build tree so that `otherlibs/unix/unix.ml`
points to the right implementation of the Unix module. It is worth
mentionning that this macro will work fine even in the context of
out-of-source builds. Also, the macro will always create symlinks if
possible, falling back to hard-links and then plain copies if necessary.

The subsequent commit, authored by @dra27 and reviewed by me, makes sure
that only genuine native Windows symlinks will be used (rather than WSL or
Cygwin ones), because the links are to OCaml files and must thus be
understood by the native Windows OCaml compiler, which only understands
native Windows links.

**Comment by shindere** [comment]
One other thing to note is that, in its present state, this PR compiles the
files under the `debugger/` directory with `-bin-annot`, which was not the
case on trunk. The total size of the `.cmt` and `.cmti` files created
because of this change is 2,4MB. The option has been added for
uniformity and I believe we can live with the overhead. What's missing here is
a `-no-bin-annot` option that we could add to the default compiler flags on
a per-target basis.

**Review by dra27 — APPROVED** [review]
Another one bites the dust! The force push history and logs record the offline reviewing which has taken place. This is the first of the merges where the artefacts are all built using the root compiler (i.e. `./ocamlc` rather than `boot/ocamlc`), and so also the first time `Makefile.best_binaries` gets pulled into the root `Makefile`. This has been through [precheck#832](https://ci.inria.fr/ocaml/job/precheck/832/).

**Comment by shindere** [comment]
Many thanks to David for his review comments which were, as always, both
incredibly valuable andincredibly supportive. To the point where it
feels he deserves authorship even more than I do.

**Pull request merged**
