### PR TITLE
Anonymous type functors

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR implements anonymous type functors.

### Brief overview

These are similar to the usual named type functors (defined with `type ('a1, ..., 'an) t = ...`), except that they can only define type aliases, and that the alias is inline. The current syntax is
```ocaml
('a1, ..., 'an) ('b1 ... 'bn. T)
```
for some type expression `T` over `'b1`, ..., `'bn`, which represents the type when each `'a` is substituted for the corresponding `'b` in `T`.

For example, you could (verbosely) write
```ocaml
(int, bool, unit) ('a 'b 'c. 'a * 'b)
```
instead of
```ocaml
int * bool
```

Due to the limitations of the `Tpoly` polymorphic type, these types cannot carry constraints. Thus, attempts to constrain the variables `'b1`, ..., `'bn` in `T` will result in an error. (See the tests for some examples of this.)

### Justification

This PR is intended as part of a series of PRs to implement higher-arity type variables, to let us write more generic functions such as

```ocaml
let map (type a b (_) t) ~(bind : a t -> f:(a -> b t) -> b t) ~(return : b -> b t) ~f x =
  bind x ~f:(fun x -> return (f x))

val map : bind:('a 't -> f:('a -> 'b 't) -> 'b 't) -> return:('b -> 'b 't) -> f:('a -> 'b) -> 'a 't -> 'b 't
```

and express more generic types, such as the general monad type:

```ocaml
type ((_) 't) monad = {bind : 'a 'b. 'a 't -> f:('a -> 'b t) -> 'b t; return : 'a. 'a -> 'a 't}
```

**This PR alone adds no extra expressiveness to the type system.** However, this does set up some of the infrastructure that we can use for these higher-arity type variables, so that these variables have some way of interacting with the rest of the type system correctly.

Despite being useless on its own, I'm spinning this out as its own PR to make sure that the semantics and syntax are sane. (And that the feature itself is sane, before I do too much more work on it!)

### CODE REVIEW

**Comment by lpw25** [comment]
> This PR is intended as part of a series of PRs to implement higher-arity type variables

Could you give an outline of how you intend to do that? I do not think it is an easy thing to do.

**Comment by mrmr1993** [comment]
> Could you give an outline of how you intend to do that?

Sure! At the moment, the game plan is:
* Modify `Tvar` and `Tunviar` to carry an extra `int` representing their arity
  -  I imagine that most of this will be finding places to throw an appropriate error where a non-zero-arity variable doesn't belong.
  - Arity tests and appropriate errors for points where different variables are unified.
* Accept type variables as the RHS of a `Pexp_apply`
  -  Main part of this should be making sure that unification with a `Tpoly` from another `Tapply` works properly.
  - Lots of testing, presumably some bugfixes where the tests identify errors.
  - This would live in the same PR as the previous part, so that the previous part can also have tests.
* Extend the `Pexp_newtype` syntax to support declaring higher-arity constructors
  - Proposed syntax is `let x (type (_, ..., _) t) ... = ...`.
  - This is the next least-powerful way of introducing new type variables, extend the tests accordingly.
  - Minor detail: I'm planning to capitalise the names of the newtypes when cast to variable names (e.g. `type t` becomes `'T`), so that it is more obvious that they are not just garden-variety type variables.
* Extend the `Ptyp_poly` and `Pexp_newtype` syntaxes to support higher-arity variables in their arguments.
  - This opens up the possibility of passing higher-arity variables to eachother, and passing them to other forms of `Tapply`, with appropriate tests.
  - Some new cases are available, such a `Tpoly` in a record field containing higher-arity variables, which can also be tested.
* Expose a syntax for higher-arity type variables as arguments to type constructors.
  - My main concerns at this stage are with GADTs involving type variables, but this may prove to be more/less of a problem come the time.
  - Lots of tests, presumably lots of bugfixes
  - Proposed syntax is `type ((_, ..., _) 'T, ...) t`

This is the stage at which I would consider the base feature complete, although there are obviously more things that could be done once all of these pieces are in place.

> I do not think it is an easy thing to do.

Neither do I. I would still like to do it.

**Comment by lpw25** [comment]
I don't entirely follow your description. Perhaps if you gave an example of how you think the `map` function you wrote above would be used that would make things clearer.

**Comment by mrmr1993** [comment]
A concrete example I would like would look something like:

```ocaml
type ((_) 'T) monad = {bind: 'a 'b. 'a 'T -> f:('a -> 'b 'T) -> 'b 'T; return: 'a. 'a -> 'a 'T}

type ('a 'b, 'c) t = {a: 'a; b: 'b; c: 'c}

let join_over_t ~(m : 'M monad) (x : ('a 'M, 'b 'M, 'c 'M) t) : ('a, 'b, 'c) t 'M =
  m.bind x.a ~f:(fun a ->
  m.bind x.b ~f:(fun b ->
  m.bind x.c ~f:(fun c ->
    {a; b; c} )))
```

I tend to need this style of function quite often, and it would be convenient if I could write it once instead of per-monad, or using module functors. You could write similar for `'a 'M list -> 'a list 'M` etc.

**Comment by lpw25** [comment]
I see. I suggest that you read Section 1.1 of [this paper](https://www.cl.cam.ac.uk/~jdy22/papers/lightweight-higher-kinded-polymorphism.pdf) for a description of why it is not really possible to support that style in OCaml. Also see [this paper](https://arxiv.org/pdf/1512.01895.pdf) for a description of a system that would support what you are hoping for and does not have the issues discussed in the first paper.

**Comment by bluddy** [comment]
So the whole problem is the lack of distinction between data types and alias types? Why don't we create two new keywords then, and gradually deprecate `type`?

**Comment by lpw25** [comment]
The problem is more that Haskell's approach to higher-kinded constructors is anti-modular and does not play nicely with the full abstraction supported by a proper module system. Removing alias types is essentially the same as removing functors from the language.

**Comment by mrmr1993** [comment]
Thanks @lpw25. Part of the idea behind this syntax is that we can disambiguate: if we have an `f : ('a, 'b) 'M -> ...` then we can always annotate `f (x : (int, bool) ('a 'b. 'a -> 'b))`. In general, the idea was to throw an 'ambiguous type variable' error when the higher-arity variable is, well, ambiguous, so that I could avoid exactly this problem.

**Comment by lpw25** [comment]
The higher-arity variable is always going to be ambiguous unless you essentially annotate all your type applications. In your example above you assume that `'a 'T` unifying with `'b 'M` gives `'a = 'b` and `'T = 'M` but that is not a most general solution so you can't make that assumption.

**Comment by mrmr1993** [comment]
> In your example above you assume that `'a 'T` unifying with `'b 'M` gives `'a = 'b` and `'T = 'M` but that is not a most general solution so you can't make that assumption.

As you mentioned before, the most general solution is problematic to the point of being unworkable. I'm suggesting that we should take the easy way out: we should just *assert* that `'T = 'M` and `'a = 'b`, given that `'a 'T = 'b 'M`. Using these semantics, we can still get something useful, avoid nearly all of the hard problems around aliasing, and only have to annotate the types when the type is ambiguous or typed with the wrong alias at the unification site.

**Comment by lpw25** [comment]
That sounds to me like it breaks both principality -- the result of inference will depend on the whims of the inference algorithm -- and abstraction -- revealing the definition of a type can make code fail to type check when it previously succeeded. It also goes against the idea the equal types are equal in all contexts -- I'll get different results if I write `int t` or `(int * int) list` given `type 'a t = ('a * 'a) list` even though those types are supposed to be identical.

At the very least you would need a clear declarative specification of what precisely you mean by "ambiguous".

**Comment by lpw25** [comment]
One proposal, which I know @let-def was interested in trying, is to implement the support for module parameters to functions from modular implicits:
```ocaml
let map {M : Monad} f x =
  M.bind x ~f:(fun x -> M.return (f x))

val map : {M : Monad} -> f:('a -> 'b) -> 'a M.t -> 'b M.t

let map_plus {M : Monad} m =
  map {M} (fun (x, y) -> x + y)
```
without (yet) adding the support for implicitly filling in the module arguments.

Do you think that would address the kinds of use cases you had in mind?

**Comment by mrmr1993** [comment]
> That sounds to me like it breaks both principality -- the result of inference will depend on the whims of the inference algorithm -- and abstraction -- revealing the definition of a type can make code fail to type check when it previously succeeded.

As it stands, this shouldn't break abstraction: any constraints on the type parameters to a `Tapply` are rejected, so all of the acceptable types have the same 'shape'. This is an invariant I was planning on keeping, so I don't think that should be an issue.

I hadn't worried as much about principality, since any implementation of this would have to break it by design, and the issue only arises in code using this feature (modulo weak higher-arity type variables, which could reasonably be banned). Still, I'll think on this and see if there are different/better compromises that we can make.

> support for module parameters to functions from modular implicits
> Do you think that would address the kinds of use cases you had in mind?

This would be a great feature to have! It covers most of the straightforward cases I had. There's still quite a big miss for me in types parametrised over higher-arity types though, e.g.
```ocaml
type ((_) 'T, _, _) polylist =
| [] : ('T, unit, unit) polylist
| (::) : 'a 'T -> ('T, _, 'rest) polylist -> ('T, 'a, 'a -> 'rest) polylist
```
and the corresponding type transformers
```ocaml
type ((_) 'T, (_) 'U) swap = {f : 'a. 'a 'T -> 'a 'U}

let swap :
    (_) 'T (_) 'U 'a 'b.
      f:('T, 'U) swap -> ('T, 'a, 'b) polylist -> ('U, 'a, 'b) polylist =
  fun ~f l ->
    match l with
    | [] -> []
    | x :: rest -> f.f x :: rest
```

If we were to aim to support examples like this first and foremost, I think we could get by if we insist that the higher-arity type variables must appear unapplied somewhere in their scope (like the parameters `'T` and `'U` to `swap` and `polylist` above), rejecting any other higher-arity variables as 'ambiguous'.

**Comment by stedolan** [comment]
> As it stands, this shouldn't break abstraction

I think it does, unfortunately. Here's an example that will hopefully clarify what @lpw25's getting at. Suppose `'a` and `'b` are ordinary unification variables ranging over types, and `'f` is a unification variable of arity 1 (that is, ranging over types with one parameter), and `_ t` is some type constructor that's in scope.

You've explained that if we come across a constraint `'a t = 'b 'f`, then we should solve it by instantiating `'b = 'a` and `'f = t`.

What should we do with a constraint `int = 'b 'f`? It sounds like you're saying that unification should fail here (if not, what should `'b` and `'f` be instantiated to?).

But then what if `_ t` is defined by `type 'a t = int`? Then expanding the alias `'a t = int` turns the solvable constraint `'a t = 'b 'f` into the unsolvable constraint `int = 'b 'f`, which is a Bad Thing - expanding a definition should not make a program that was typeable suddenly fail to typecheck. You end up with something that typechecks *only if the definition of `_ t` is unknown*.

---

Perhaps there's some confusion here because of how this feature works in Haskell. In Haskell, it works because the type constructor `_ t` above *cannot be defined*. You can come pretty close:
```
newtype P a = P { getP :: Int }
type Q a = Int
```
Both of these have caveats: `P` defines `P a` as a new type, which can be converted back and forth to `Int` using `P` and `getP`, but the type `P a` and `Int` are not equated by the type system. This means that if you want to convert a `[P String]` into a `[Int]`, you need to use `map` and iterate over the list.

On the other hand, `Q a` and `Int` are actually identified, so a `[Q a]` is also a `[Int]`. However, Haskell does not view `Q` as a real type constructor: you cannot pass `Q` anywhere something of kind `* -> *` is expected. For instance, you get a compiler error if you try to write `Instance Functor Q`. If you define `type H f = f String`, you get an error if you attempt to use `H Q`.

In OCaml (or other ML-ish languages), you can write a type constructor `type 'a t = int` that has both of these useful properties: the types `string t list` and `int list` are equated with no conversion between them being necessary, and you can abstract over things like `_ t` and pass them in module arguments. The price is that the simple Haskell-style unification algorithm (solving `'a 'f = 'b 'g` by `'a = 'b`, `'f = 'g`) is insufficient, so the syntax you need to use to abstract over these things is quite verbose (modules and functors).

**Comment by mrmr1993** [comment]
Okay. I guess I'll have to abandon that model for unification.

I think the most we can do easily and reliably then is what I mentioned above:

> insist that the higher-arity type variables must appear unapplied somewhere in their scope (...), rejecting any other higher-arity variables as 'ambiguous'.

Once we have a bare higher-arity variable, the path to unification becomes clear again. I don't think this should stop us from doing anything either, since we can always have one or more extra parameters like

```ocaml
type ((_, _, _) 'A) tfun_3 = Tfun_3

let f (_ : 'A tfun_3) (x : (int, bool, bool) 'A) = ...
```
which should make the unification unambiguous, albeit needing a type annotation at the callsite.

*Edit: Alternatively (although preferably not for the MVP, because of its wide-reaching effects) we could introduce inline type constraints to let us manually specify the type functor at call time.*

I think that most of the code I would like to use this for will involve a record type with the higher-arity variable as a type parameter (so that you can have polymorphism over the parameters to the variable, see e.g. the example in my last comment), in which cases we shouldn't need any type annotations at all.

Is this a reasonable path to go down?

**Comment by bluddy** [comment]
So what is the relationship between the dual nature of OCaml's `type`, type abstraction and functors?

1. Functors require type abstraction as they bind abstract types to concrete ones.
2. `type` does both type definition and type aliasing, which is more convenient for abstraction, since more concrete types can map to the same abstract types.

However, it doesn't seem like we *need* `type` to have this duality, right? It's just a convenience that makes functors more powerful. But we *could* have had 2 `type` keywords, same as Haskell, at the cost of no abstraction between the two? Or is there a more fundamental connection to abstraction that I'm missing?

Also, it doesn't seem like there is any other need for type abstraction other than for functors (and first class modules), right? Abstraction could be enforced by the type checker while it keeps track of the concrete type of everything.

**Comment by mrmr1993** [comment]
> So what is the relationship between the dual nature of OCaml's `type`, type abstraction and functors?

> it doesn't seem like we *need* `type` to have this duality, right?

I think that the big reason that Haskell doesn't have this duality is that it dispatches some code based only on types (via typeclasses). Considering anything less than physically equal types (modulo type variables) to be equivalent could generate different programs from the same code, depending only on the choice between these equivalent types. I think avoiding this is part of the 'abstraction' principle above.

Since OCaml only does name-based dispatch, the types aren't constrained in the same way and more types can be considered equivalent. Functors are the main place these are used, with the obvious advantage that code can abstract over multiple types at once far more easily.

On reflection, I'm not sure that splitting the duality will have much benefit, to either this feature or OCaml itself.

**Comment by lpw25** [comment]
> This would be a great feature to have! It covers most of the straightforward cases I had. There's still quite a big miss for me in types parametrised over higher-arity types though

Supporting those is also part of the modular implicits plan. You could similarly add some support for it without any support yet for implicit or inferred module variables. Something like:

```ocaml
type (M : S, 'a) t = Foo of 'a M.t

let foo {M : S} x : (M, _) t = Foo x
```

Since there wouldn't be any inferred or implicit module variables yet, you wouldn't be able to give a single type to the constructors (e.g. `Foo`) above and would need to rely on type annotations in order to type check uses of the constructors. Fortunately, we already have an established system for propagating type annotations to decide which constructor you meant, so that should be pretty easy and unsurprising to users.

As with other modular implicit features, without the implicit part this is really just some nice sugar for using functors, but sometimes sugar is nice.

**Comment by mrmr1993** [comment]
I'm sorry for my slow reply, I've had an exceptionally busy week.

> Supporting those is also part of the modular implicits plan. You could similarly add some support for it without any support yet for implicit or inferred module variables.

Ahh, I had misunderstood; it seems the 'named modules' for types part of modular implicits and the higher-arity type variables are equivalent then, e.g.

```ocaml
type (M : S, 'a) t = A of 'a M.t
```
and
```ocaml
type ('M, 'a) t = A of 'a 'T constraint 'M = (module S with type 'b t = 'b 'T)
```

Please correct me if I'm wrong, but AFAICT the biggest differences are that
* this part of the modular implicits proposal always requires an explicit module
* the issues above with ambiguity above still exist, but are left until the implicit/deferred part
* the syntax for extracting modules' types with non-zero arity (as above) is heavier using higher-arity type variables
* the syntax for abstracting over higher-arity types is heavier for modular implicits because of the modules and signatures it needs.

I would still prefer to have higher-arity type variables available. However, if there's consensus that we shouldn't, and should implement (this subset of?) modular implicits instead, I'm happy to lend my efforts to that instead.

(/cc @let-def, do you have a concrete plan for this? I'm assuming something along the lines of
* add the option to carry names in module types
  - as part of this, checking that the same name isn't assigned to multiple modules within a type, printing them with distinct names, etc.
* making named modules available within their containing type, so that its types can be referred to by name
* relax the escape checks for modules that feature in the type)

Whichever way this goes, I'm keen to push forward and get something implemented in the near-term.

**Comment by lpw25** [comment]
> However, if there's consensus that we shouldn't, and should implement (this subset of?) modular implicits instead, I'm happy to lend my efforts to that instead.

Consensus is probably too strong a word. I think that this is the best way to go about this, and there is general support for trying to get modular implicits into the langauage at some point, but any change like this would need to be approved by more people than just me.

> do you have a concrete plan for this? I'm assuming something along the lines of
> [...]

If I were implementing the types part I would precede roughly as follows:

- Update parser to allow module paths as arguments to types
- Update parser to allow module parameters in type declarations
- Update `typing/types.ml` to allow module paths as arguments to types
- Update `typing/types.ml` and `typing/typedecl.ml` to allow module parameters to
  types without yet allowing them to be referred to in the definition of the type and without
  allowing such types to have a definition (i.e. no variant constructors or record fields)
- Update operations in `typing/ctype.ml` to take account of module arguments
- Update `typing/typetexp.ml` to allow types with module parameters to take module path arguments.

At this point you should have a sound working system that lets you gratuitously annotate types with module parameters, checks that these module parameters are given modules of the right module  type, and treats these module parameters as relevant for type equality. From there we can allow the module parameters to be referred to in type equations.

- Update `typing/typedecl.ml` to allow module parameters of types to be used in their equations (a.k.a. manifests) but still without allowing such types to have a definition (i.e. no variant constructors or record fields)
- Update type expansion in `typing/ctype.ml` to do substitution of module arguments for module parameters.

Again you should be back to a sound working system at this point. Finally you can add support for having variant constructors and record fields in types with module parameters.

- Update `typing/typedecl.ml` to allow types with module parameters to have variant constructors and record fields.
- Update `typing/env.ml` and `typing/datarepr.ml` to mark constructors and fields that depend on module parameters.
- Update `typing/typecore.ml` to error if a module-dependent constructor or field is used without a type annotation. We already have precise tracking of type annotations here for doing disambiguation, so you can just use that. If there is a type annotation it should be used to choose the module arguments for the result type of the constructor or field. Do not forget to warn if the type annotation is not principal and to substitute the module argument for the module parameter in the type of the constructor/field.

If you decide to give it a shot, let me know if you have any questions or issues. It would probably be best to submit a PR as soon as you have something vaguely working, so that you can get more official approval for the approach before spending large amounts of time polishing everything.

**Comment by mrmr1993** [comment]
> If I were implementing the types part I would precede roughly as follows:

@lpw25 thank you for the detailed overview! In the radio silence, I've been prototyping a slightly more involved version of this, implementing named modules within types along the lines of

```ocaml
type t = (module M : S) -> 'a M.t
type ('a, 'b) u = 'b M.t constraint 'a = (module M : S)
type 'a v = 'a M.t * (module M : S)
```
etc. I think the modular implicits type changes are roughly equivalent to the second of these, albeit with better sugar.

> I think that this is the best way to go about this, and there is general support for trying to get modular implicits into the langauage at some point

Do you think it's reasonable to continue in the direction I've been working in? I'm close to finishing the types side of it, and I would rather not abandon what I've done so far.

**Comment by garrigue** [comment]
I'm not sure what you mean by "continue in the direction I've been working".
As @lpw25 pointed, implementing this over the current OCaml unification algorithm is going to give you a completely unpredictable behavior. This is much worse than losing principality, which is mostly about depending on the order in which sub-expressions of terms are visited, still keeping mgus in unification, while in your case this is the whole unification algorithm that loses its properties.
At the very least this requires a constraint solver, able to delay unification constraints until more information is available. The modular implicit implementation does that, and for this reason does not rely on unification.

IIUC, @lpw25 's suggestion is closer to Scala: allow types to depend on modules, but without accessing them, so that beta-reduction is not involved, and we can still use first-order unification.

**Comment by mrmr1993** [comment]
> I'm not sure what you mean by "continue in the direction I've been working".

@garrigue sorry, I probably misspoke there. I meant to ask whether I should keep working on named modules within types, as in my comment above.

I think I've come up with a way to integrate it after Leo's suggestion is implemented, so I'm going to shelve named modules for now and shift to working on that instead.

Also, I'm closing this PR, since it clearly isn't the way to go. I'll open a new one when I have something implemented, hopefully within the next few days.

**Pull request closed without merging**
