### PR TITLE
documentation: clarify that l=x only affects byte-code runtime

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Review by gasche — APPROVED** [review]

**Comment by hannesm** [comment]
dear @gasche, thanks for your positive review. the documentation string is borrowed from the GC control record (http://caml.inria.fr/pub/docs/manual-ocaml/libref/Gc.html#TYPEcontrol).

the motivation behind this commit is that it took me some time to figure out the stack size limit did not work for native programs, and I wanted to avoid future users (and my future self) from spending time on discovering that the stack size limit only works for bytecode.

I'm curious why you added and removed "no changes entry needed" -- do you think this minor documentation clarification should entail a changes entry? if the answer is yes, in which section and which release should this be in?

thanks again for reading.

**Comment by gasche** [comment]
> I'm curious why you added and removed "no changes entry needed" -- do you think this minor documentation clarification should entail a changes entry? if the answer is yes, in which section and which release should this be in?

You didn't add a change entry, and at first I assumed this was intentional, so I added the label to quiet the CI test for change entries. But then I wondered: what if Hannes had just forgotten the Changes entry, am I belittling the certainly-useful contribution by suggesting that it is minor? Gasp! Not knowing what to do, I removed the label.

I will assume from your reply that you are fine with not having a Changes entry, so I will merge now. Thanks for the ping.

**Comment by hannesm** [comment]
thanks for the merge @gasche, and indeed I consider this modification so little that it doesn't need a changes entry. I'll be more explicit in the future. :)

**Comment by hannesm** [comment]
FWIW, I think this could be safely merged into 4.11 branch as documentation fix //cc @Octachron @gasche

**Comment by gasche** [comment]
Yes, I had also merged it in 4.11 in 36176ca4238409efb919939d5a2ce3bedf35a173, I should have been more explicit.

**Comment by gasche** [comment]
@hannesm you may be interested in the related https://github.com/ocaml/ocaml/pull/10736 which was just merged, and should be in 4.14.

**Pull request merged**
