### PR TITLE
Rebase of #1617 (make string/bytes distinguishable in bytecode)

### PR DESCRIPTION
**Pull request by nojb**
This is a rebase of #1617 with the bootstrap commits re-done (it does not seem possible to push to the existing PR).

### CODE REVIEW

**Comment by dra27** [comment]
I'm not sure if I've got the house rule right, but I thought it's more that a core dev needs to repeat the bootstrap and verify that the binary in the GPR is the same (@xavierleroy?)

**Comment by nojb** [comment]
In this case, the GPR needs to be rebased in order to be mergeable - so the GPR author would have had to rebase the PR, redoing the bootstraps and then a core dev would have needed to re-do the re-done bootstraps to check that they are the same. Seems a bit inefficient.

**Comment by hhugo** [comment]
@nojb, thanks for the rebase. Unfortunately, it needs to be rebased again.

**Comment by nojb** [comment]
Thanks, will update shortly.

**Comment by nojb** [comment]
Rebased. I will merge by end-of-day unless someone speaks up.

**Comment by hhugo** [comment]
Is it end-of-day already ? :)

**Comment by nojb** [comment]
Yes, will merge as soon as the CI is green. Sorry for the wait, but I had to rebase once again due to some recently merged PR.

**Comment by nojb** [comment]
Merged, thank you!

**Pull request merged**
